import { SiteChrome } from "../site-chrome";

export type Section = { heading:string; paragraphs:string[]; bullets?:string[] };

export function ArticleContent({ tag, title, dek, slug, sections }:{ tag:string; title:string; dek:string; slug:string; sections:Section[] }){
  const wordCount=[title,dek,...sections.flatMap(s=>[s.heading,...s.paragraphs,...(s.bullets??[])])].join(" ").trim().split(/\s+/).length;
  const canonical=`https://spreadsheet-hipobuy.net/articles/${slug}/`;
  const schema=[
    {"@context":"https://schema.org","@type":"Article",headline:title,datePublished:"2026-08-22",dateModified:"2026-08-24",wordCount,mainEntityOfPage:canonical,image:"https://spreadsheet-hipobuy.net/og.png",author:{"@type":"Organization",name:"Hipobuy Sheet editorial desk"},reviewedBy:{"@type":"Organization",name:"Hipobuy Sheet catalogue verification desk"},publisher:{"@type":"Organization",name:"Hipobuy Sheet",logo:{"@type":"ImageObject",url:"https://spreadsheet-hipobuy.net/hipobuy-logo.png"}}},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://spreadsheet-hipobuy.net/"},{"@type":"ListItem",position:2,name:"Articles",item:"https://spreadsheet-hipobuy.net/articles/"},{"@type":"ListItem",position:3,name:title,item:canonical}]},
  ];
  return <SiteChrome><main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="article-hero"><div><span>{tag}</span><small>PUBLISHED 22 AUG 2026 · UPDATED 24 AUG 2026</small></div><h1>{title}</h1><p>{dek}</p><div className="article-byline">By Hipobuy Sheet editorial desk · Reviewed by the catalogue verification desk</div><nav><a href="/articles/">All guides</a><a href="/spreadsheet/">Open spreadsheet</a></nav></header><article className="article-body"><aside><span>ON THIS PAGE</span>{sections.map((s,i)=><a href={`#section-${i+1}`} key={s.heading}>0{i+1} {s.heading}</a>)}</aside><div className="article-copy"><div className="article-research"><strong>Research basis · checked 24 Aug 2026</strong><p>Sources reviewed: the current Hipobuy website and Hipobuy’s official Apple App Store and Google Play descriptions. Third-party review platforms are used only for reported themes, never as proof of a typical result.</p></div><div className="article-callout"><strong>Scope note</strong><p>This independent guide explains a decision process. Product availability, platform rules, services and shipping routes can change; confirm live terms before payment.</p></div>{sections.map((s,i)=><section id={`section-${i+1}`} key={s.heading}><small>0{i+1}</small><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}</div></article></main></SiteChrome>;
}
