import type { LocalArticle, Locale } from "./site-data";

export const polandRouteAvailabilityArticle: Record<Locale, LocalArticle> = {
  en: {
    seoTitle: "USFans Poland Route Availability: Live Comparison Guide",
    title: "USFans Poland Route Availability: Compare Live Shipping Options",
    excerpt: "A dated method for checking Poland routes with identical parcel inputs, reading tax and service labels, and choosing without treating an estimate as a promise.",
    intro: `USFans Poland route availability is a live result, not a permanent list. The official estimator changes its output according to destination, postcode, item category, actual weight, dimensions, and the rules active when the query is made. A route that appears for ordinary clothing may disappear for a battery, liquid, oversized carton, different postcode, or later submission date. That is why a useful comparison records the inputs and time before it records a price.

On 15 September 2026, the public estimator returned thirteen route cards for a controlled Poland scenario: postcode 00-001, Clothing, 1,000 g, and 30 × 25 × 10 cm. The cards included InPost, DHL, DPD, EUB, EMS, UPS, European-federal and economy-labelled options. They showed different tax labels, delivery ranges, delivery-rate figures, volumetric divisors, address requirements, return limits, and compensation notes. This guide explains how to read that evidence. It is not a recommendation of a named line, and every value must be checked again with the actual warehouse parcel before payment.`,
    points: [
      "Compare every route with the same destination, category, weight, dimensions, and postcode.",
      "Save the query date because names, eligibility, discounts, limits, and prices can change.",
      "Read the route card's tax, billing, address, return, tracking, and compensation notes before price.",
      "Use the route-specific volumetric divisor rather than applying one formula to every line.",
      "Re-run the comparison with final warehouse data and treat the submitted parcel record as decisive."
    ],
    sections: [
      ["1. Build one controlled Poland scenario", `Open the current USFans shipping estimator and select Poland before comparing anything. Enter the real delivery postcode, the closest available item category, actual or expected packed weight, and plausible packed length, width, and height. Keep those inputs identical while reading every result. The dated test for this article used postcode 00-001, Clothing, 1,000 g, and 30 × 25 × 10 cm; it is an example that makes the cards comparable, not a quote for another parcel. Save a screenshot or note containing the date, currency, category, postcode, weight, dimensions, and number of returned cards. If the category is uncertain, test the stricter plausible category as a second scenario instead of choosing ordinary clothing merely to reveal more lines. A mixed parcel should be tested against its most restrictive item, because one battery, liquid, cosmetic, food item, or fragile component can change eligibility for the whole parcel. Do not compare a compact clothing result with a bulky shoe-box result and call the difference a route-price difference; the inputs answer different questions.`],
      ["2. Treat the returned list as a dated snapshot", `The controlled query returned thirteen cards on 15 September 2026. The displayed names included PL inpost-PL-2, several Poland DHL variants, Poland EUB-2, European Federation of Poland -2, DPD variants, Poland-Guangzhou EMS-2, Poland UPS, and Poland-KH-2. Those labels are useful evidence that multiple service families were visible for that exact scenario, but they are not a permanent Poland catalogue. Names can be adjusted, a promotion can end, a carrier can pause intake, or an item classification can remove a line before warehouse submission. Record what the estimator actually displayed rather than shortening several similarly named cards into one “DHL” or “DPD” option. Cards with similar delivery ranges can still differ in customs handling, accepted contents, redelivery, return destination, tracking, or compensation. If a saved name is no longer present when the parcel is ready, do not force the old comparison. Start a new dated snapshot with the final data and explain the change in your order record.`],
      ["3. Read tax labels without inventing a guarantee", `The September scenario showed cards marked “Tax Exemption,” cards marked “Duties Payable by Recipient,” and at least one card where the visible summary did not present the same tax badge. Treat these as route-card labels under the current estimator, not as a legal promise that every charge is settled or that customs cannot request information. A tax-exemption or commercial-clearance label does not replace accurate product descriptions, values, quantities, recipient details, or any document required by the carrier or Polish authorities. Conversely, a recipient-duties label means the budget must keep room for the consignee's customs and payment obligations; it is not a calculation of the final amount. Save the exact wording beside the route name and date. Before payment, open the current details for the chosen card and verify whether the label still applies to the real contents and value. If tax treatment materially changes the purchase decision, use current official Polish or EU guidance or qualified advice rather than relying on an old estimator screenshot.`],
      ["4. Use the billing rule printed on each card", `USFans' estimator FAQ describes a general volumetric formula of length × width × height in centimetres ÷ 6000 and says chargeable weight is the higher of actual and volumetric weight. The returned route cards also showed route-specific rules. The InPost-labelled card in the dated scenario printed a divisor of 8000, while the Poland-KH card printed a divisor of 7000. That difference proves why one universal calculation is not enough. For 30 × 25 × 10 cm, the volumetric results are 1.25 kg at 6000, about 1.07 kg at 7000, and 0.94 kg at 8000. Against an actual 1.00 kg parcel, the chargeable input could therefore differ by line. Recalculate using the exact rule on the chosen current card, including rounding or minimum-charge increments shown in its details. Warehouse measurements and the carrier's verified parcel control the final bill. A pre-purchase dimension guess is useful for risk planning, but it cannot establish the final chargeable weight.`],
      ["5. Compare service conditions before the headline amount", `For the controlled scenario, visible promotional shipping amounts ranged from $22.50 on the InPost-labelled card to $182.37 on the Poland-KH card, with multiple results between them. These figures are only a dated USD-interface snapshot for the stated inputs and included visible promotional labels; they are not current quotes for the reader. Read the operating notes first. Several cards required the exact house number. Multiple DHL- or DPD-labelled cards said a returned parcel could go to an overseas warehouse for redelivery but could not be returned to China. The EUB card warned that signature records and additional compensation for loss, delay, damage, or customs inspection were unavailable. Some cards used commercial customs clearance; postal cards described recipient customs responsibility. A low amount can therefore purchase a different evidence, return, and risk package. Compare price only after the parcel is eligible and the service terms fit the value, urgency, address, and loss tolerance.`],
      ["6. Interpret delivery windows as route-stage estimates", `The returned cards displayed ranges such as 7–18, 8–18, 10–18, 15–25, 7–12, and 20–25 business days. Those ranges describe the currently displayed route estimate, not the complete clock from marketplace payment to a Polish doorstep. Seller dispatch, China domestic transport, warehouse intake, QC review, consolidation, parcel preparation, carrier collection, export processing, customs, European handoff, and Polish last-mile delivery occur in separate stages. Record the route range exactly and add buffers for stages outside it. The estimator also displayed delivery-rate percentages, but a percentage cannot promise the outcome or date of one parcel; preserve it only as a dated interface field. If timing matters, compare the slower credible outcome rather than the fastest number. After submission, track the actual carrier record and any last-mile reference. Do not continue to judge the parcel from the pre-purchase estimate once a real shipment timeline exists.`],
      ["7. Make a pass, hold, or reject decision", `Create a route worksheet with one row per current card and columns for exact name, query date, category, postcode, actual weight, dimensions, volumetric divisor, chargeable-weight method, tax label, estimated range, amount, address rule, permitted contents, return destination, tracking, compensation, and unresolved questions. Mark Pass only when the real parcel appears eligible, the billing rule is understood, the address fits, and the service's loss and return conditions are acceptable. Mark Hold when a decisive field is missing, the category classification is uncertain, or a detail page contradicts the summary. Mark Reject when the parcel is prohibited, exceeds a limit, needs a service the route excludes, or fails the buyer's maximum cost or risk threshold. Do not rank all thirteen cards from cheapest to most expensive as if they were interchangeable. A route with duties payable by the recipient, limited tracking, or no compensation belongs to a different decision class from a fully tracked option whose current terms fit the contents.`],
      ["8. Recheck at warehouse submission and preserve evidence", `Repeat the estimator query after the items have arrived, visible discrepancies have been resolved, and the intended parcel composition is known. Replace guessed weight and dimensions with the best current warehouse or packed values. Use the exact postcode and the actual category or restricted-item classification. Compare only the cards returned at that moment, then open the chosen route's current details before payment. Save the final result, parcel contents, weight, dimensions, route name, billing rule, tax label, delivery range, amount, optional protection, declaration record, and timestamp. If the submitted amount or line later differs from the first snapshot, the two records should show whether dimensions, contents, category, promotion, or availability changed. The durable answer to “Which USFans route is available to Poland?” is a repeatable method, not a memorised list: hold inputs constant, read every condition, reject incompatible lines, and replace the estimate with the final parcel confirmation.`]
    ]
  },
  pl: {
    seoTitle: "USFans Polska: dostępność tras i porównanie na żywo",
    title: "USFans Polska: jak porównywać aktualnie dostępne trasy",
    excerpt: "Metoda porównania tras do Polski przy identycznych danych paczki, z właściwym odczytem etykiet podatkowych, zasad rozliczenia i ograniczeń.",
    intro: `Dostępność tras USFans do Polski jest wynikiem na żywo, a nie stałą listą. Oficjalny kalkulator zmienia wyniki zależnie od kraju, kodu pocztowego, kategorii, wagi rzeczywistej, wymiarów oraz zasad obowiązujących w chwili zapytania. Trasa widoczna dla zwykłej odzieży może zniknąć dla baterii, płynu, dużego kartonu, innego kodu lub późniejszej daty.

15 września 2026 publiczny kalkulator zwrócił trzynaście kart dla kontrolowanego scenariusza: Polska, kod 00-001, kategoria Clothing, 1 000 g i 30 × 25 × 10 cm. Widoczne były opcje oznaczone m.in. InPost, DHL, DPD, EUB, EMS, UPS i liniami ekonomicznymi. Karty różniły się podatkami, czasem, wzorem objętościowym, adresem, zwrotem, trackingiem i rekompensatą. To opis sposobu czytania danych, a nie rekomendacja konkretnej linii.`,
    points: ["Porównuj trasy przy identycznym kraju, kodzie, kategorii, wadze i wymiarach.", "Zapisuj datę, bo nazwy, ceny, promocje i dostępność mogą się zmienić.", "Czytaj podatki, rozliczenie, adres, zwrot, tracking i rekompensatę przed ceną.", "Stosuj dzielnik objętościowy podany dla konkretnej trasy.", "Powtórz kalkulację z finalnymi danymi magazynowymi przed płatnością."],
    sections: [
      ["1. Zbuduj jeden kontrolowany scenariusz", `W kalkulatorze wybierz Polskę, rzeczywisty kod odbiorcy, najbliższą kategorię, wiarygodną wagę oraz zapakowane wymiary. Nie zmieniaj tych pól podczas porównywania kart. Scenariusz 00-001, Clothing, 1 000 g i 30 × 25 × 10 cm służy wyłącznie do porównania wyników z 15 września 2026, nie jest wyceną cudzej paczki. Zapisz datę, walutę, kategorię, kod, wagę, wymiary i liczbę kart. Gdy klasyfikacja jest niepewna, wykonaj drugi test z bardziej restrykcyjną kategorią. Paczkę mieszaną sprawdzaj według najbardziej ograniczającego produktu, bo bateria, płyn, kosmetyk, żywność lub element kruchy może zmienić dostępność całości.`],
      ["2. Traktuj listę jako datowany zrzut", `W kontrolowanym teście widoczne były trzynaście kart: PL inpost-PL-2, kilka wariantów Poland DHL, Poland EUB-2, European Federation of Poland -2, warianty DPD, Poland-Guangzhou EMS-2, Poland UPS oraz Poland-KH-2. Nazwy potwierdzają, że dla tego scenariusza istniało kilka rodzin usług, lecz nie tworzą stałego katalogu. Przewoźnik może wstrzymać przyjęcia, promocja się skończyć, a klasyfikacja produktu usunąć linię. Zapisuj pełną nazwę, ponieważ podobne karty DHL lub DPD mogą różnić się odprawą, zwrotem, trackingiem i rekompensatą. Jeśli zapisana trasa zniknie przed nadaniem, rozpocznij nowe porównanie na finalnych danych.`],
      ["3. Czytaj etykiety podatkowe bez obietnic", `Wyniki pokazywały oznaczenia „Tax Exemption”, „Duties Payable by Recipient” oraz karty bez identycznej etykiety w skrócie. Są to bieżące opisy kalkulatora, nie gwarancja prawna braku kosztów lub kontroli. Oznaczenie odprawy nie zwalnia z prawidłowego opisu, wartości, ilości i dokumentów. Etykieta o opłatach odbiorcy oznacza konieczność pozostawienia budżetu na obowiązki adresata, lecz nie wylicza ich końcowej wysokości. Zapisz dosłowne brzmienie, trasę i datę, a przed płatnością otwórz aktualne szczegóły. Gdy podatki decydują o zakupie, korzystaj z bieżących źródeł polskich i unijnych lub fachowej porady.`],
      ["4. Używaj wzoru przypisanego do karty", `FAQ kalkulatora podaje ogólny wzór długość × szerokość × wysokość w cm ÷ 6000 i wybór wyższej wagi. Karty pokazały jednak inne dzielniki: InPost 8000, a Poland-KH 7000. Dla 30 × 25 × 10 cm daje to odpowiednio 1,25 kg przy 6000, około 1,07 kg przy 7000 i 0,94 kg przy 8000. Przy wadze rzeczywistej 1,00 kg wynik rozliczeniowy może więc zależeć od linii. Sprawdź dokładny wzór, zaokrąglenie i minimum w bieżących szczegółach wybranej trasy. Dopiero finalne pomiary magazynu i weryfikacja przewoźnika określą rachunek.`],
      ["5. Porównuj warunki przed kwotą", `W datowanym scenariuszu promocyjne kwoty widoczne w USD mieściły się od 22,50 USD dla karty InPost do 182,37 USD dla Poland-KH. Są to wyłącznie dane interfejsu dla zapisanych parametrów. Kilka kart wymagało dokładnego numeru domu. Warianty DHL i DPD informowały o zwrocie do magazynu zagranicznego w celu ponownego doręczenia, bez możliwości zwrotu do Chin. EUB wskazywał brak podpisu i dodatkowej rekompensaty za utratę, opóźnienie, szkodę lub kontrolę celną. Linie różniły się też odprawą i obowiązkami odbiorcy. Najniższa kwota może więc oznaczać inny poziom dowodów i ryzyka.`],
      ["6. Traktuj czas jako zakres etapu trasy", `Karty pokazywały m.in. 7–18, 8–18, 10–18, 15–25, 7–12 i 20–25 dni roboczych. To zakres konkretnej trasy, a nie czas od zapłaty sprzedawcy do drzwi. Wcześniej występują wysyłka krajowa, przyjęcie, QC, kompletowanie i odbiór przez przewoźnika; później eksport, cło, przekazanie europejskie i ostatnia mila w Polsce. Zapisz zakres i dodaj bufor dla etapów poza nim. Procent doręczeń jest datowanym polem interfejsu, nie obietnicą wyniku pojedynczej paczki. Po nadaniu opieraj się na realnym trackingu, a nie starym szacunku.`],
      ["7. Podejmij decyzję pass, hold lub reject", `W arkuszu utwórz wiersz dla każdej karty oraz kolumny: nazwa, data, kategoria, kod, waga, wymiary, dzielnik, metoda rozliczenia, podatki, czas, kwota, adres, dozwolona zawartość, zwrot, tracking, rekompensata i pytania. Pass oznacza zgodność paczki, zrozumiałe rozliczenie i akceptowalne ryzyko. Hold stosuj przy niepewnej kategorii, brakującym polu lub sprzeczności szczegółów. Reject stosuj przy zakazie, przekroczonym limicie, braku potrzebnej usługi albo przekroczeniu kosztu i ryzyka. Nie ustawiaj wszystkich trzynastu linii tylko od najtańszej: różne obowiązki i ochrona tworzą różne klasy decyzji.`],
      ["8. Powtórz test przy nadawaniu", `Po przyjęciu produktów i ustaleniu składu paczki zastąp założenia aktualną wagą i wymiarami magazynowymi. Wprowadź dokładny kod oraz rzeczywistą klasyfikację, porównaj tylko linie zwrócone wtedy i otwórz bieżące szczegóły wybranej karty. Zapisz zawartość, wymiary, wagę, nazwę trasy, wzór, podatki, czas, kwotę, ochronę, deklarację i godzinę. Jeżeli wynik różni się od pierwszego zrzutu, oba rekordy pokażą zmianę wymiarów, zawartości, kategorii, promocji lub dostępności. Poprawna odpowiedź o trasie do Polski jest procesem: stałe dane, pełne warunki, odrzucenie niezgodnych opcji i finalne potwierdzenie paczki.`]
    ]
  },
  de: {
    seoTitle: "USFans Polen: Live-Routen richtig vergleichen",
    title: "USFans Polen: Aktuell verfügbare Versandrouten vergleichen",
    excerpt: "Eine datierte Methode, um Polen-Routen mit identischen Paketdaten sowie Steuer-, Abrechnungs- und Servicehinweisen zu vergleichen.",
    intro: `Die Verfügbarkeit von USFans-Routen nach Polen ist ein Live-Ergebnis und keine dauerhafte Liste. Ziel, Postleitzahl, Kategorie, Gewicht, Maße und die Regeln zum Zeitpunkt der Abfrage bestimmen die Ausgabe. Eine Linie für normale Kleidung kann bei Batterien, Flüssigkeiten, einem großen Karton oder späterem Datum fehlen.

Am 15. September 2026 lieferte der öffentliche Schätzer für Polen, 00-001, Clothing, 1.000 g und 30 × 25 × 10 cm dreizehn Karten. Darunter waren InPost-, DHL-, DPD-, EUB-, EMS-, UPS-, europäische und Economy-Bezeichnungen. Steuerlabel, Laufzeit, Volumenformel, Adresspflicht, Rückgabe, Tracking und Entschädigung unterschieden sich. Das ist eine Lesemethode, keine Empfehlung; vor Zahlung muss mit echten Lagerdaten neu geprüft werden.`,
    points: ["Alle Linien mit identischem Ziel, Kategorie, Gewicht, Maßen und Postleitzahl vergleichen.", "Datum speichern, weil Namen, Preise, Rabatte und Zulässigkeit wechseln.", "Steuer-, Abrechnungs-, Adress-, Rückgabe-, Tracking- und Entschädigungshinweise zuerst lesen.", "Den Volumendivisor der konkreten Karte verwenden.", "Mit finalen Lagerdaten erneut prüfen und die Paketeinreichung als maßgeblich behandeln."],
    sections: [
      ["1. Ein kontrolliertes Polen-Szenario bilden", `Polen, echte Empfänger-PLZ, passende Kategorie, realistisches Gewicht und gepackte Maße eingeben und während des Vergleichs unverändert lassen. Das Beispiel 00-001, Clothing, 1.000 g und 30 × 25 × 10 cm macht nur den Test vom 15. September vergleichbar. Datum, Währung, Kategorie, PLZ, Gewicht, Maße und Kartenzahl sichern. Bei unsicherer Einordnung zusätzlich die strengere plausible Kategorie testen. Ein gemischtes Paket nach dem restriktivsten Inhalt prüfen, weil Batterie, Flüssigkeit, Kosmetik, Lebensmittel oder Zerbrechliches alle Optionen verändern kann.`],
      ["2. Die Liste als Momentaufnahme behandeln", `Die dreizehn Karten umfassten PL inpost-PL-2, mehrere Poland-DHL-Varianten, Poland EUB-2, European Federation of Poland -2, DPD-Varianten, Poland-Guangzhou EMS-2, Poland UPS und Poland-KH-2. Sie belegen mehrere sichtbare Servicefamilien für genau diesen Test, aber keinen festen Katalog. Annahmestopps, geänderte Aktionen oder Artikelklassen können Linien entfernen. Den vollständigen Namen speichern, denn ähnlich benannte DHL- oder DPD-Karten unterscheiden sich bei Zoll, Rückgabe, Tracking oder Entschädigung. Verschwindet eine Linie, mit den finalen Daten neu beginnen.`],
      ["3. Steuerlabel nicht als Garantie lesen", `Im Test erschienen „Tax Exemption“, „Duties Payable by Recipient“ und Karten ohne dasselbe Kurzlabel. Das sind aktuelle Schnittstellenangaben, keine rechtliche Garantie gegen Gebühren oder Prüfung. Eine Clearance-Angabe ersetzt keine korrekte Beschreibung, Menge, Wert- oder Empfängerdaten. Empfängerabgaben verlangen Budgetspielraum, berechnen aber keinen Endbetrag. Wortlaut, Linie und Datum speichern, vor Zahlung die aktuellen Details öffnen und bei entscheidender Steuerfrage offizielle polnische oder EU-Quellen beziehungsweise Fachberatung nutzen.`],
      ["4. Die Formel der jeweiligen Karte verwenden", `Die FAQ nennt allgemein Länge × Breite × Höhe in cm ÷ 6000 und den höheren Wert aus realem und volumetrischem Gewicht. Die Karten zeigten zusätzlich 8000 bei InPost und 7000 bei Poland-KH. Für 30 × 25 × 10 cm entstehen 1,25 kg bei 6000, rund 1,07 kg bei 7000 und 0,94 kg bei 8000. Gegenüber 1,00 kg Realgewicht kann die Abrechnungslage wechseln. Aktuelle Kartenregel, Rundung und Mindestschritt prüfen; Lagermaße und Carrier-Prüfung bestimmen die Endabrechnung.`],
      ["5. Bedingungen vor dem Preis vergleichen", `Im datierten Szenario lagen sichtbare Aktionsbeträge zwischen 22,50 USD für InPost und 182,37 USD für Poland-KH. Sie gelten nur für die gespeicherten Eingaben. Mehrere Karten verlangten eine genaue Hausnummer. DHL- und DPD-Varianten begrenzten Rücksendungen auf ein Auslandswarenlager zur erneuten Zustellung statt China. EUB nannte fehlende Unterschrift und keine zusätzliche Entschädigung für Verlust, Verzögerung, Schaden oder Zollprüfung. Customs- und Empfängerpflichten unterschieden sich ebenfalls. Ein niedriger Preis kann daher weniger Nachweise oder Schutz kaufen.`],
      ["6. Laufzeiten als Routenschätzung verstehen", `Angezeigt wurden etwa 7–18, 8–18, 10–18, 15–25, 7–12 und 20–25 Werktage. Das ist nicht die gesamte Zeit von Verkäuferzahlung bis Haustür. Inlandsversand, Wareneingang, QC, Packen und Abholung liegen davor; Export, Zoll, Übergabe und polnische letzte Meile folgen. Bereich speichern und Puffer ergänzen. Die angezeigte Zustellquote bleibt ein datiertes Feld und verspricht nichts für ein Paket. Nach Einreichung gilt der echte Carrier-Verlauf statt der alten Schätzung.`],
      ["7. Pass, Hold oder Reject entscheiden", `Eine Zeile je Karte mit Name, Datum, Kategorie, PLZ, Gewicht, Maßen, Divisor, Abrechnung, Steuerlabel, Zeit, Betrag, Adresse, Inhalt, Rückgabe, Tracking, Entschädigung und offenen Fragen anlegen. Pass nur bei Zulässigkeit, verstandener Abrechnung und akzeptablem Risiko. Hold bei fehlendem entscheidendem Feld, unsicherer Kategorie oder Widerspruch. Reject bei Verbot, Limitüberschreitung, fehlender benötigter Leistung oder zu hohen Kosten und Risiken. Dreizehn nicht bloß nach Preis sortieren, denn Pflichten und Schutz sind nicht austauschbar.`],
      ["8. Bei Paketeinreichung erneut prüfen", `Nach Lagereingang und festem Paketinhalt Annahmen durch aktuelle Gewichte und Maße ersetzen. Echte PLZ und Klassifikation nutzen, nur die dann angezeigten Linien vergleichen und aktuelle Details öffnen. Inhalt, Gewicht, Maße, Name, Formel, Steuerlabel, Zeit, Betrag, Schutz, Deklaration und Zeitpunkt sichern. Unterschiede zur ersten Aufnahme lassen sich so auf Maße, Inhalt, Kategorie, Aktion oder Verfügbarkeit zurückführen. Eine belastbare Polen-Routenentscheidung ist ein wiederholbarer Prozess, keine gemerkte Liste.`]
    ]
  },
  fr: {
    seoTitle: "USFans Pologne : comparer les itinéraires en direct",
    title: "USFans Pologne : comparer les options d’expédition disponibles",
    excerpt: "Méthode datée pour comparer les routes vers la Pologne avec les mêmes données et lire fiscalité, facturation et limites de service.",
    intro: `La disponibilité des routes USFans vers la Pologne est un résultat en direct, pas une liste permanente. Destination, code postal, catégorie, poids, dimensions et règles actives modifient la réponse. Une ligne visible pour des vêtements peut disparaître pour une batterie, un liquide, un carton volumineux ou une date ultérieure.

Le 15 septembre 2026, l’estimateur public a affiché treize cartes pour Pologne, 00-001, Clothing, 1 000 g et 30 × 25 × 10 cm. Elles portaient notamment les noms InPost, DHL, DPD, EUB, EMS, UPS, lignes européennes et économiques. Fiscalité, délai, formule volumétrique, adresse, retour, suivi et indemnisation variaient. Il s’agit d’une méthode de lecture, non d’une recommandation; il faut recommencer avec les données réelles avant paiement.`,
    points: ["Comparer chaque route avec destination, catégorie, poids, dimensions et code identiques.", "Conserver la date car noms, prix, promotions et éligibilité changent.", "Lire fiscalité, facturation, adresse, retour, suivi et indemnisation avant le prix.", "Appliquer le diviseur volumétrique de la carte concernée.", "Refaire le test avec les données finales de l’entrepôt avant paiement."],
    sections: [
      ["1. Construire un scénario polonais contrôlé", `Sélectionnez Pologne, le vrai code du destinataire, la catégorie la plus proche, un poids crédible et les dimensions emballées, puis ne changez plus ces champs. Le scénario 00-001, Clothing, 1 000 g et 30 × 25 × 10 cm sert uniquement à comparer le test du 15 septembre. Enregistrez date, devise, catégorie, code, poids, dimensions et nombre de cartes. Si la classification est incertaine, testez aussi la catégorie plausible la plus stricte. Un colis mixte doit être évalué selon son élément le plus restrictif, car batterie, liquide, cosmétique, aliment ou objet fragile peut modifier toutes les routes.`],
      ["2. Traiter la liste comme un instantané", `Les treize cartes comprenaient PL inpost-PL-2, plusieurs variantes Poland DHL, Poland EUB-2, European Federation of Poland -2, des variantes DPD, Poland-Guangzhou EMS-2, Poland UPS et Poland-KH-2. Elles prouvent plusieurs familles visibles pour ce scénario, pas un catalogue fixe. Suspension, fin de promotion ou nouvelle classification peuvent supprimer une ligne. Conservez le nom complet: deux cartes DHL ou DPD proches peuvent différer en douane, retour, suivi ou indemnisation. Si une ligne disparaît avant l’envoi, recommencez avec les données finales.`],
      ["3. Lire les mentions fiscales sans promesse", `Le test affichait « Tax Exemption », « Duties Payable by Recipient » et des cartes sans la même mention résumée. Ce sont des libellés actuels de l’interface, pas une garantie juridique d’absence de frais ou de contrôle. Une mention de dédouanement ne remplace ni description, valeur, quantité ni documents exacts. Les droits à la charge du destinataire exigent une marge budgétaire mais ne calculent pas le montant final. Notez texte, route et date, ouvrez les détails actuels avant paiement et consultez les sources polonaises ou européennes si la fiscalité décide l’achat.`],
      ["4. Utiliser la formule de chaque carte", `La FAQ donne la formule générale longueur × largeur × hauteur en cm ÷ 6000 et retient le plus élevé du poids réel et volumétrique. Les cartes montraient aussi 8000 pour InPost et 7000 pour Poland-KH. Pour 30 × 25 × 10 cm, on obtient 1,25 kg à 6000, environ 1,07 kg à 7000 et 0,94 kg à 8000. Face à 1,00 kg réel, la base facturable peut varier. Vérifiez règle, arrondi et minimum actuels; les mesures d’entrepôt et le contrôle du transporteur fixent la facture finale.`],
      ["5. Comparer les conditions avant le montant", `Dans ce scénario daté, les montants promotionnels visibles allaient de 22,50 USD pour InPost à 182,37 USD pour Poland-KH. Ils ne valent que pour les paramètres enregistrés. Plusieurs cartes exigeaient le numéro de maison exact. Des variantes DHL et DPD limitaient le retour à un entrepôt étranger pour réexpédition, sans retour vers la Chine. EUB signalait l’absence de signature et d’indemnisation supplémentaire en cas de perte, retard, dommage ou contrôle douanier. Les obligations de dédouanement variaient aussi. Le prix le plus bas peut donc correspondre à moins de preuves ou de protection.`],
      ["6. Interpréter le délai comme une estimation de route", `Les cartes affichaient notamment 7–18, 8–18, 10–18, 15–25, 7–12 et 20–25 jours ouvrés. Ce n’est pas le temps total depuis le paiement du vendeur. Expédition intérieure, entrée, QC, emballage et collecte précèdent; export, douane, transfert et dernier kilomètre polonais suivent. Conservez la plage et ajoutez une marge. Le taux de livraison affiché est un champ daté, pas une promesse individuelle. Après soumission, utilisez le vrai suivi du transporteur plutôt que l’ancienne estimation.`],
      ["7. Décider Pass, Hold ou Reject", `Créez une ligne par carte avec nom, date, catégorie, code, poids, dimensions, diviseur, facturation, fiscalité, délai, montant, adresse, contenu, retour, suivi, indemnisation et questions. Pass si le colis paraît éligible, la facturation comprise et le risque acceptable. Hold si un champ décisif manque, si la catégorie est incertaine ou si les détails se contredisent. Reject en cas d’interdiction, limite dépassée, service indispensable absent ou seuil de coût et de risque dépassé. Ne classez pas les treize options seulement par prix: leurs obligations et protections diffèrent.`],
      ["8. Refaire la vérification lors de la soumission", `Après réception et composition du colis, remplacez les hypothèses par le poids et les dimensions disponibles à l’entrepôt. Utilisez le vrai code et la classification réelle, comparez seulement les lignes renvoyées à cet instant et ouvrez les détails de la ligne choisie. Enregistrez contenu, données, nom, formule, fiscalité, délai, montant, protection, déclaration et heure. La comparaison avec le premier instantané expliquera un changement de dimensions, contenu, catégorie, promotion ou disponibilité. Une bonne décision est un processus répétable, pas une liste mémorisée.`]
    ]
  },
  it: {
    seoTitle: "USFans Polonia: confronto delle rotte disponibili",
    title: "USFans Polonia: come confrontare le rotte di spedizione attuali",
    excerpt: "Metodo datato per confrontare le rotte con gli stessi dati del pacco e leggere tasse, fatturazione e limiti operativi.",
    intro: `La disponibilità delle rotte USFans verso la Polonia è un risultato in tempo reale, non un elenco permanente. Destinazione, CAP, categoria, peso, dimensioni e regole attive cambiano l’output. Una linea per abbigliamento può sparire per batterie, liquidi, scatole ingombranti o in una data successiva.

Il 15 settembre 2026 lo stimatore pubblico ha restituito tredici schede per Polonia, 00-001, Clothing, 1.000 g e 30 × 25 × 10 cm. Comparivano opzioni InPost, DHL, DPD, EUB, EMS, UPS, europee ed economiche, con etichette fiscali, tempi, formule volumetriche, requisiti di indirizzo, resi, tracking e compensazione diversi. È un metodo di lettura, non una raccomandazione; prima del pagamento va ripetuto con i dati reali.`,
    points: ["Confronta ogni rotta con destinazione, categoria, peso, dimensioni e CAP identici.", "Salva la data perché nomi, prezzi, promozioni e idoneità cambiano.", "Leggi tasse, calcolo, indirizzo, reso, tracking e compensazione prima del prezzo.", "Usa il divisore volumetrico della singola scheda.", "Ripeti il controllo con i dati finali del magazzino prima di pagare."],
    sections: [
      ["1. Crea uno scenario polacco controllato", `Seleziona Polonia, CAP reale, categoria più vicina, peso credibile e dimensioni imballate, mantenendo gli stessi campi per tutte le schede. Lo scenario 00-001, Clothing, 1.000 g e 30 × 25 × 10 cm serve solo a confrontare il test del 15 settembre. Salva data, valuta, categoria, CAP, peso, misure e numero di risultati. Se la classificazione è incerta, prova anche quella plausibile più restrittiva. Un pacco misto va testato sul contenuto più limitante, perché batteria, liquido, cosmetico, cibo o componente fragile può cambiare tutte le opzioni.`],
      ["2. Considera l’elenco un’istantanea", `Le tredici schede includevano PL inpost-PL-2, più varianti Poland DHL, Poland EUB-2, European Federation of Poland -2, varianti DPD, Poland-Guangzhou EMS-2, Poland UPS e Poland-KH-2. Dimostrano più famiglie disponibili per quello scenario, non un catalogo fisso. Sospensioni, fine di promozioni o nuova classificazione possono rimuovere una linea. Salva il nome completo: schede DHL o DPD simili possono differire per dogana, reso, tracking e compensazione. Se una rotta scompare, ricomincia con i dati finali.`],
      ["3. Leggi le etichette fiscali senza inventare garanzie", `Il test mostrava “Tax Exemption”, “Duties Payable by Recipient” e schede senza lo stesso badge sintetico. Sono etichette correnti dell’interfaccia, non garanzie legali contro costi o controlli. Lo sdoganamento non sostituisce descrizione, valore, quantità e documenti corretti. Gli oneri a carico del destinatario richiedono margine, ma non calcolano il totale. Salva testo, rotta e data, apri i dettagli attuali prima del pagamento e usa fonti polacche o UE se la fiscalità è decisiva.`],
      ["4. Applica la formula della singola rotta", `La FAQ indica in generale lunghezza × larghezza × altezza in cm ÷ 6000 e il maggiore tra peso reale e volumetrico. Le schede mostravano anche 8000 per InPost e 7000 per Poland-KH. Con 30 × 25 × 10 cm risultano 1,25 kg a 6000, circa 1,07 kg a 7000 e 0,94 kg a 8000. Rispetto a 1,00 kg reale, il peso addebitabile può cambiare. Verifica formula, arrotondamento e minimo attuali; misure di magazzino e controllo del vettore determinano il conto finale.`],
      ["5. Confronta le condizioni prima dell’importo", `Nello scenario datato gli importi promozionali visibili andavano da 22,50 USD per InPost a 182,37 USD per Poland-KH e valgono solo per quei parametri. Più schede richiedevano il numero civico esatto. Varianti DHL e DPD limitavano il reso a un magazzino estero per la riconsegna, senza ritorno in Cina. EUB indicava assenza di firma e di compensazione aggiuntiva per perdita, ritardo, danno o controllo doganale. Anche lo sdoganamento differiva. Il prezzo più basso può quindi offrire prove e protezioni diverse.`],
      ["6. Interpreta i tempi come stime di tratta", `Le schede mostravano intervalli come 7–18, 8–18, 10–18, 15–25, 7–12 e 20–25 giorni lavorativi. Non coprono l’intero periodo dal pagamento al domicilio. Spedizione cinese, ingresso, QC, imballaggio e ritiro precedono; export, dogana, passaggio europeo e ultimo miglio polacco seguono. Salva l’intervallo e aggiungi margine. La percentuale di consegna è un campo datato, non una promessa individuale. Dopo l’invio vale il tracking reale, non la vecchia stima.`],
      ["7. Decidi Pass, Hold o Reject", `Prepara una riga per scheda con nome, data, categoria, CAP, peso, misure, divisore, fatturazione, tasse, tempo, importo, indirizzo, contenuti, reso, tracking, compensazione e dubbi. Pass solo se il pacco è idoneo, il calcolo chiaro e il rischio accettabile. Hold se manca un dato decisivo, la categoria è incerta o i dettagli contrastano. Reject per divieto, limite superato, servizio necessario assente o soglia di costo e rischio superata. Non ordinare tredici linee solo per prezzo: obblighi e protezioni non sono equivalenti.`],
      ["8. Ripeti al momento dell’invio", `Dopo l’arrivo e la definizione del pacco, sostituisci le ipotesi con peso e dimensioni disponibili in magazzino. Usa CAP e classificazione reali, confronta solo le linee restituite allora e apri i dettagli correnti della scelta. Salva contenuto, dati, nome, formula, tasse, tempo, importo, protezione, dichiarazione e orario. I due snapshot spiegheranno differenze di dimensioni, contenuto, categoria, promozione o disponibilità. La risposta affidabile è un metodo ripetibile, non un elenco imparato.`]
    ]
  },
  es: {
    seoTitle: "USFans Polonia: comparar rutas disponibles en vivo",
    title: "USFans Polonia: cómo comparar las rutas de envío actuales",
    excerpt: "Método fechado para comparar rutas con los mismos datos de paquete y leer impuestos, facturación y límites del servicio.",
    intro: `La disponibilidad de rutas USFans hacia Polonia es un resultado en vivo, no una lista permanente. Destino, código postal, categoría, peso, dimensiones y reglas activas cambian la respuesta. Una línea para ropa puede desaparecer por una batería, líquido, caja voluminosa u otra fecha.

El 15 de septiembre de 2026 el estimador público devolvió trece tarjetas para Polonia, 00-001, Clothing, 1.000 g y 30 × 25 × 10 cm. Había opciones InPost, DHL, DPD, EUB, EMS, UPS, europeas y económicas, con etiquetas fiscales, tiempos, fórmulas volumétricas, requisitos de dirección, devoluciones, seguimiento y compensación distintos. Es un método de lectura, no una recomendación; hay que repetirlo antes de pagar con los datos reales.`,
    points: ["Compara todas las rutas con destino, categoría, peso, dimensiones y código idénticos.", "Guarda la fecha porque nombres, precios, promociones y elegibilidad cambian.", "Lee impuestos, cálculo, dirección, devolución, seguimiento y compensación antes del precio.", "Usa el divisor volumétrico indicado en cada tarjeta.", "Repite el control con datos finales de almacén antes del pago."],
    sections: [
      ["1. Construye un escenario polaco controlado", `Selecciona Polonia, código real, categoría más cercana, peso creíble y dimensiones embaladas, manteniendo todo igual para cada tarjeta. El ejemplo 00-001, Clothing, 1.000 g y 30 × 25 × 10 cm solo compara el test del 15 de septiembre. Guarda fecha, moneda, categoría, código, peso, medidas y número de resultados. Si la clasificación es incierta, prueba también la categoría plausible más restrictiva. Un paquete mixto debe evaluarse por su contenido más limitado, porque batería, líquido, cosmético, alimento o pieza frágil puede cambiar todas las rutas.`],
      ["2. Trata la lista como una instantánea", `Las trece tarjetas incluían PL inpost-PL-2, varias Poland DHL, Poland EUB-2, European Federation of Poland -2, variantes DPD, Poland-Guangzhou EMS-2, Poland UPS y Poland-KH-2. Prueban varias familias visibles para ese escenario, no un catálogo fijo. Pausas, fin de promociones o reclasificaciones pueden quitar una línea. Guarda el nombre completo: tarjetas DHL o DPD parecidas pueden diferir en aduana, devolución, tracking o compensación. Si desaparece una ruta antes del envío, reinicia la comparación con datos finales.`],
      ["3. Lee las etiquetas fiscales sin prometer", `El test mostró “Tax Exemption”, “Duties Payable by Recipient” y tarjetas sin la misma insignia resumida. Son etiquetas actuales de la interfaz, no garantías legales contra cargos o revisión. Una mención de despacho no sustituye descripción, valor, cantidad y documentos correctos. Los derechos a cargo del destinatario exigen margen, pero no calculan el importe final. Guarda texto, ruta y fecha, abre los detalles vigentes antes de pagar y consulta fuentes polacas o de la UE si la fiscalidad decide la compra.`],
      ["4. Usa la fórmula de cada tarjeta", `La FAQ indica en general largo × ancho × alto en cm ÷ 6000 y el mayor entre peso real y volumétrico. Las tarjetas mostraron además 8000 para InPost y 7000 para Poland-KH. Con 30 × 25 × 10 cm salen 1,25 kg a 6000, unos 1,07 kg a 7000 y 0,94 kg a 8000. Frente a 1,00 kg real, el peso facturable puede variar. Comprueba fórmula, redondeo y mínimo actuales; las medidas de almacén y la verificación del transportista fijan el total.`],
      ["5. Compara condiciones antes del importe", `En el escenario fechado los importes promocionales visibles iban de 22,50 USD para InPost a 182,37 USD para Poland-KH y solo valen para esos datos. Varias tarjetas exigían número de casa exacto. Versiones DHL y DPD limitaban la devolución a almacén extranjero para reentrega, sin vuelta a China. EUB indicaba ausencia de firma y de compensación adicional por pérdida, retraso, daño o inspección aduanera. También cambiaban las obligaciones de despacho. El menor precio puede ofrecer pruebas y protección distintas.`],
      ["6. Interpreta los tiempos como estimación de ruta", `Las tarjetas mostraban 7–18, 8–18, 10–18, 15–25, 7–12 y 20–25 días laborables. No cubren todo el tiempo desde el pago hasta la puerta. Envío nacional, entrada, QC, embalaje y recogida ocurren antes; exportación, aduana, transferencia y última milla polaca después. Guarda el rango y añade margen. La tasa de entrega es un campo fechado, no una promesa individual. Tras presentar el paquete usa el tracking real, no la estimación antigua.`],
      ["7. Decide Pass, Hold o Reject", `Crea una fila por tarjeta con nombre, fecha, categoría, código, peso, medidas, divisor, facturación, impuestos, tiempo, importe, dirección, contenido, devolución, tracking, compensación y preguntas. Pass solo si el paquete es elegible, el cálculo comprensible y el riesgo aceptable. Hold si falta un dato decisivo, la categoría es incierta o hay contradicción. Reject por prohibición, exceso de límite, ausencia de servicio necesario o umbral de coste y riesgo superado. No ordenes trece líneas solo por precio: obligaciones y protección son distintas.`],
      ["8. Repite al presentar el paquete", `Después de la llegada y de fijar la composición, sustituye supuestos por peso y dimensiones disponibles en almacén. Usa código y clasificación reales, compara solo las líneas devueltas entonces y abre los detalles actuales. Guarda contenido, datos, nombre, fórmula, impuestos, tiempo, importe, protección, declaración y hora. Los dos registros explicarán cambios de dimensiones, contenido, categoría, promoción o disponibilidad. Una decisión fiable es un proceso repetible, no una lista memorizada.`]
    ]
  },
  ro: {
    seoTitle: "USFans Polonia: compararea rutelor disponibile",
    title: "USFans Polonia: cum compari rutele actuale de transport",
    excerpt: "Metodă datată pentru compararea rutelor cu aceleași date ale coletului și citirea taxelor, facturării și limitelor de serviciu.",
    intro: `Disponibilitatea rutelor USFans către Polonia este un rezultat în timp real, nu o listă permanentă. Destinația, codul poștal, categoria, greutatea, dimensiunile și regulile active schimbă rezultatul. O linie pentru haine poate dispărea pentru baterii, lichide, cutii voluminoase sau la o dată ulterioară.

La 15 septembrie 2026, estimatorul public a returnat treisprezece carduri pentru Polonia, 00-001, Clothing, 1.000 g și 30 × 25 × 10 cm. Au apărut opțiuni InPost, DHL, DPD, EUB, EMS, UPS, europene și economice, cu etichete fiscale, termene, formule volumetrice, cerințe de adresă, retur, urmărire și compensație diferite. Este o metodă de citire, nu o recomandare; verificarea trebuie repetată înainte de plată cu date reale.`,
    points: ["Compară toate rutele cu aceeași destinație, categorie, greutate, dimensiuni și cod.", "Salvează data deoarece numele, prețurile, promoțiile și eligibilitatea se schimbă.", "Citește taxele, calculul, adresa, returul, trackingul și compensația înaintea prețului.", "Folosește divizorul volumetric al cardului concret.", "Repetă verificarea cu datele finale din depozit înainte de plată."],
    sections: [
      ["1. Construiește un scenariu polonez controlat", `Selectează Polonia, codul real, categoria cea mai apropiată, greutatea credibilă și dimensiunile ambalate, păstrând aceleași câmpuri pentru toate cardurile. Exemplul 00-001, Clothing, 1.000 g și 30 × 25 × 10 cm compară doar testul din 15 septembrie. Salvează data, moneda, categoria, codul, greutatea, dimensiunile și numărul rezultatelor. Dacă încadrarea este incertă, testează și categoria plauzibilă mai restrictivă. Un colet mixt trebuie verificat după produsul cel mai limitativ, deoarece bateria, lichidul, cosmeticul, alimentul sau obiectul fragil poate schimba toate opțiunile.`],
      ["2. Tratează lista ca pe un instantaneu", `Cele treisprezece carduri includeau PL inpost-PL-2, mai multe Poland DHL, Poland EUB-2, European Federation of Poland -2, variante DPD, Poland-Guangzhou EMS-2, Poland UPS și Poland-KH-2. Ele dovedesc mai multe familii vizibile pentru scenariul exact, nu un catalog fix. Suspendarea, finalul promoției sau reclasificarea pot elimina o linie. Salvează numele complet: carduri DHL ori DPD similare pot avea vamă, retur, tracking și compensație diferite. Dacă ruta dispare înainte de expediere, reia comparația cu date finale.`],
      ["3. Citește etichetele fiscale fără promisiuni", `Testul a afișat „Tax Exemption”, „Duties Payable by Recipient” și carduri fără aceeași insignă sumară. Sunt etichete curente ale interfeței, nu garanții juridice împotriva costurilor sau controlului. O mențiune de vămuire nu înlocuiește descrierea, valoarea, cantitatea și documentele corecte. Taxele destinatarului cer marjă de buget, dar nu calculează suma finală. Salvează formularea, ruta și data, deschide detaliile actuale înainte de plată și folosește surse poloneze sau UE dacă fiscalitatea decide achiziția.`],
      ["4. Folosește formula fiecărui card", `FAQ-ul indică în general lungime × lățime × înălțime în cm ÷ 6000 și valoarea mai mare dintre greutatea reală și volumetrică. Cardurile au arătat și 8000 pentru InPost, respectiv 7000 pentru Poland-KH. La 30 × 25 × 10 cm rezultă 1,25 kg cu 6000, aproximativ 1,07 kg cu 7000 și 0,94 kg cu 8000. Față de 1,00 kg real, baza taxabilă poate diferi. Verifică formula, rotunjirea și minimul actual; măsurile depozitului și verificarea transportatorului decid suma finală.`],
      ["5. Compară condițiile înaintea sumei", `În scenariul datat, sumele promoționale vizibile erau între 22,50 USD pentru InPost și 182,37 USD pentru Poland-KH și se aplică doar datelor salvate. Mai multe carduri cereau numărul exact al imobilului. Variante DHL și DPD limitau returul la un depozit extern pentru re-livrare, fără întoarcere în China. EUB menționa lipsa semnăturii și a compensației suplimentare pentru pierdere, întârziere, daună sau control vamal. Obligațiile de vămuire diferă și ele. Cel mai mic preț poate cumpăra dovezi și protecție diferite.`],
      ["6. Interpretează timpul ca estimare de rută", `Cardurile afișau intervale precum 7–18, 8–18, 10–18, 15–25, 7–12 și 20–25 zile lucrătoare. Acestea nu acoperă tot timpul de la plata vânzătorului la ușă. Transportul intern, recepția, QC, ambalarea și preluarea preced ruta; exportul, vama, transferul și ultima milă poloneză urmează. Salvează intervalul și adaugă rezervă. Rata de livrare este un câmp datat, nu o promisiune individuală. După depunerea coletului, folosește trackingul real.`],
      ["7. Decide Pass, Hold sau Reject", `Creează un rând per card cu nume, dată, categorie, cod, greutate, dimensiuni, divizor, facturare, taxe, timp, sumă, adresă, conținut, retur, tracking, compensație și întrebări. Pass doar dacă pachetul este eligibil, calculul înțeles și riscul acceptabil. Hold dacă lipsește un câmp decisiv, categoria este incertă ori detaliile se contrazic. Reject pentru interdicție, limită depășită, serviciu necesar absent sau prag de cost și risc depășit. Nu ordona treisprezece rute doar după preț: obligațiile și protecția diferă.`],
      ["8. Repetă verificarea la trimitere", `După sosire și stabilirea conținutului, înlocuiește presupunerile cu greutatea și dimensiunile disponibile în depozit. Folosește codul și clasificarea reale, compară numai liniile returnate atunci și deschide detaliile curente. Salvează conținut, date, nume, formulă, taxe, timp, sumă, protecție, declarație și oră. Cele două instantanee vor explica schimbări de dimensiuni, conținut, categorie, promoție sau disponibilitate. O decizie sigură este un proces repetabil, nu o listă memorată.`]
    ]
  }
};
