import type { Locale } from "./site-data";

export const researchedSteps: Record<Locale, Array<[string, string]>> = {
  en: [
    ["Open the current marketplace link", "USFans supports pasted product links from Taobao, 1688, and Weidian. Verify the live listing instead of relying only on a spreadsheet snapshot."],
    ["Confirm the exact option", "Match variant, size, colour, quantity, price, and domestic delivery before payment. USFans product pages currently state purchases are processed from 09:00–18:00 (UTC+8)."],
    ["Wait for warehouse intake", "The marketplace seller sends the item within China to the USFans warehouse; this is separate from the later international parcel."],
    ["Review QC promptly", "Review warehouse photos promptly. Check the current return deadline, eligibility and restrictions on the specific order; seller acceptance is not guaranteed."],
    ["Estimate and submit the parcel", "Use the packed weight and dimensions. Check the selected route’s volumetric divisor, rounding, limits and billing rules; do not apply one formula to every route."],
  ],
  pl: [
    ["Otwórz aktualny link marketplace", "USFans obsługuje linki z Taobao, 1688 i Weidian. Sprawdź bieżącą ofertę, a nie tylko zapis w arkuszu."],
    ["Potwierdź dokładny wariant", "Przed płatnością porównaj wariant, rozmiar, kolor, ilość, cenę i dostawę krajową. Strony USFans podają zakup w godzinach 09:00–18:00 (UTC+8)."],
    ["Poczekaj na przyjęcie do magazynu", "Sprzedawca wysyła produkt w Chinach do magazynu USFans; to etap oddzielny od późniejszej przesyłki międzynarodowej."],
    ["Szybko sprawdź QC", "Szybko sprawdź zdjęcia magazynowe. Zweryfikuj termin, możliwość i ograniczenia zwrotu na konkretnym zamówieniu; akceptacja sprzedawcy nie jest gwarantowana."],
    ["Oszacuj i nadaj paczkę", "Użyj wagi i wymiarów zapakowanej paczki. Sprawdź dzielnik objętościowy, zaokrąglenia, limity i rozliczenie wybranej trasy; jedna formuła nie musi dotyczyć każdej linii."],
  ],
  de: [
    ["Aktuellen Marktplatz-Link öffnen", "USFans unterstützt Links von Taobao, 1688 und Weidian. Prüfe das aktuelle Angebot statt nur den Spreadsheet-Eintrag."],
    ["Genaue Variante bestätigen", "Vor der Zahlung Variante, Größe, Farbe, Menge, Preis und Inlandsversand abgleichen. USFans-Produktseiten nennen 09:00–18:00 Uhr (UTC+8) als Einkaufszeit."],
    ["Lagereingang abwarten", "Der Verkäufer sendet den Artikel innerhalb Chinas an das USFans-Lager; der internationale Versand folgt als eigener Schritt."],
    ["QC zeitnah prüfen", "Lagerfotos zeitnah prüfen. Rückgabefrist, Berechtigung und Einschränkungen am konkreten Auftrag kontrollieren; die Zustimmung des Verkäufers ist nicht garantiert."],
    ["Paket schätzen und absenden", "Gewicht und Maße des verpackten Pakets verwenden. Volumendivisor, Rundung, Grenzen und Abrechnung der gewählten Linie prüfen; eine Formel gilt nicht automatisch für alle Routen."],
  ],
  fr: [
    ["Ouvrir le lien marketplace actuel", "USFans accepte les liens Taobao, 1688 et Weidian. Vérifiez l’annonce actuelle, pas seulement la ligne du tableau."],
    ["Confirmer l’option exacte", "Avant paiement, contrôlez variante, taille, couleur, quantité, prix et livraison intérieure. Les pages USFans indiquent des achats de 09:00 à 18:00 (UTC+8)."],
    ["Attendre l’entrée en entrepôt", "Le vendeur expédie l’article en Chine vers l’entrepôt USFans; l’envoi international constitue une étape distincte."],
    ["Contrôler rapidement le QC", "Examinez rapidement les photos. Vérifiez délai, admissibilité et restrictions du retour sur la commande précise ; l’accord du vendeur n’est pas garanti."],
    ["Estimer puis soumettre le colis", "Utilisez le poids et les dimensions emballés. Vérifiez diviseur volumétrique, arrondi, limites et facturation de la ligne choisie ; aucune formule unique ne doit être supposée pour toutes les lignes."],
  ],
  it: [
    ["Apri il link marketplace aggiornato", "USFans supporta link da Taobao, 1688 e Weidian. Verifica l’inserzione corrente, non solo la riga del foglio."],
    ["Conferma l’opzione esatta", "Prima del pagamento controlla variante, taglia, colore, quantità, prezzo e consegna nazionale. Le pagine USFans indicano acquisti 09:00–18:00 (UTC+8)."],
    ["Attendi l’arrivo in magazzino", "Il venditore spedisce l’articolo in Cina al magazzino USFans; la spedizione internazionale è una fase distinta."],
    ["Controlla subito il QC", "Controlla subito le foto. Verifica scadenza, ammissibilità e restrizioni del reso sull’ordine specifico; l’accettazione del venditore non è garantita."],
    ["Stima e invia il pacco", "Usa peso e dimensioni imballati. Verifica divisore volumetrico, arrotondamenti, limiti e fatturazione della linea scelta; non applicare una formula a tutte le rotte."],
  ],
  es: [
    ["Abre el enlace actual del marketplace", "USFans admite enlaces de Taobao, 1688 y Weidian. Revisa el anuncio actual, no solo la fila de la hoja."],
    ["Confirma la opción exacta", "Antes de pagar comprueba variante, talla, color, cantidad, precio y envío nacional. Las páginas de USFans indican compras de 09:00 a 18:00 (UTC+8)."],
    ["Espera la entrada en almacén", "El vendedor envía el artículo dentro de China al almacén de USFans; el envío internacional es una fase separada."],
    ["Revisa pronto el QC", "Revisa pronto las fotos. Comprueba plazo, elegibilidad y restricciones de devolución en el pedido concreto; no se garantiza la aceptación del vendedor."],
    ["Estima y presenta el paquete", "Usa peso y dimensiones embalados. Comprueba divisor volumétrico, redondeos, límites y facturación de la línea elegida; no apliques una fórmula a todas las rutas."],
  ],
  ro: [
    ["Deschide linkul actual din marketplace", "USFans acceptă linkuri Taobao, 1688 și Weidian. Verifică oferta curentă, nu doar rândul din foaie."],
    ["Confirmă opțiunea exactă", "Înainte de plată verifică varianta, mărimea, culoarea, cantitatea, prețul și livrarea internă. Paginile USFans indică achiziții între 09:00–18:00 (UTC+8)."],
    ["Așteaptă recepția în depozit", "Vânzătorul trimite produsul în China la depozitul USFans; transportul internațional este o etapă separată."],
    ["Verifică rapid QC", "Verifică rapid fotografiile. Consultă termenul, eligibilitatea și restricțiile returului în comanda concretă; acceptarea vânzătorului nu este garantată."],
    ["Estimează și trimite coletul", "Folosește greutatea și dimensiunile ambalate. Verifică divizorul volumetric, rotunjirea, limitele și taxarea rutei alese; nu aplica aceeași formulă tuturor rutelor."],
  ],
};

export const researchedFaqs: Record<Locale, Array<[string, string]>> = {
  en: [
    ["What is USFans?", "USFans presents itself as a shopping-agent service that purchases products from Chinese marketplaces and receives them at a warehouse before international parcel shipping."],
    ["Which marketplace links does USFans publicly support?", "The USFans home page names Taobao, 1688, and Weidian and describes a paste-the-link ordering flow."],
    ["When does USFans purchase paid orders?", "Current USFans product pages state that purchasing is handled from 09:00 to 18:00 China time (UTC+8) after payment. Seller dispatch time is separate."],
    ["How many free QC photos are provided?", "Current USFans product pages advertise 3–7 free HD quality-inspection photos after warehouse arrival."],
    ["Can I return an item after seeing warehouse photos?", "Review warehouse photos promptly. Check the current return deadline, eligibility and restrictions on the specific order; seller acceptance is not guaranteed."],
    ["Is the spreadsheet price the delivered price?", "No. The listing price is only one layer. Domestic delivery, packaging or services, international freight, and possible destination charges can affect the delivered total."],
    ["How does USFans calculate volumetric weight?", "Use the packed weight and dimensions. Check the selected route’s volumetric divisor, rounding, limits and billing rules; do not apply one formula to every route."],
    ["Do QC photos prove authenticity or durability?", "No. They can document visible condition and order identity in the supplied views, but they do not prove authenticity, hidden construction, material composition, or long-term performance."],
    ["How many countries does USFans ship to?", "The current USFans home page advertises shipping to more than 50 countries. Actual route availability depends on destination, parcel, product category, and current carrier rules."],
    ["Does this independent directory sell or inspect the products?", "No. This site organises product discovery and research. Always verify the current listing, warehouse evidence, parcel quote, and applicable terms on the service you use."],
  ],
  pl: [
    ["Czym jest USFans?", "USFans przedstawia się jako agent zakupowy kupujący na chińskich marketplace’ach i przyjmujący produkty do magazynu przed wysyłką międzynarodową."],
    ["Jakie linki marketplace obsługuje USFans?", "Strona główna USFans wymienia Taobao, 1688 i Weidian oraz opisuje zamawianie przez wklejenie linku."],
    ["Kiedy USFans kupuje opłacone zamówienia?", "Aktualne strony produktów podają godziny 09:00–18:00 czasu chińskiego (UTC+8). Czas wysyłki przez sprzedawcę jest osobny."],
    ["Ile bezpłatnych zdjęć QC otrzymam?", "Aktualne strony produktów USFans informują o 3–7 bezpłatnych zdjęciach kontrolnych HD po przyjęciu do magazynu."],
    ["Czy mogę zwrócić produkt po obejrzeniu QC?", "Szybko sprawdź zdjęcia magazynowe. Zweryfikuj termin, możliwość i ograniczenia zwrotu na konkretnym zamówieniu; akceptacja sprzedawcy nie jest gwarantowana."],
    ["Czy cena w arkuszu jest ceną z dostawą?", "Nie. Dostawa krajowa, opakowanie lub usługi, transport międzynarodowy i możliwe opłaty docelowe mogą zmienić łączny koszt."],
    ["Jak obliczana jest waga objętościowa?", "Użyj wagi i wymiarów zapakowanej paczki. Sprawdź dzielnik objętościowy, zaokrąglenia, limity i rozliczenie wybranej trasy; jedna formuła nie musi dotyczyć każdej linii."],
    ["Czy zdjęcia QC potwierdzają autentyczność?", "Nie. Pokazują widoczny stan w dostarczonych ujęciach, ale nie dowodzą autentyczności, składu, ukrytej konstrukcji ani trwałości."],
    ["Do ilu krajów wysyła USFans?", "Strona główna reklamuje wysyłkę do ponad 50 krajów. Dostępność trasy zależy od celu, paczki, kategorii produktu i bieżących zasad przewoźnika."],
    ["Czy ten niezależny katalog sprzedaje produkty?", "Nie. Katalog pomaga je odkrywać i analizować. Przed decyzją sprawdź aktualną ofertę, QC, wycenę paczki i obowiązujące warunki."],
  ],
  de: [
    ["Was ist USFans?", "USFans beschreibt sich als Einkaufsagent, der auf chinesischen Marktplätzen kauft und Artikel vor dem internationalen Versand im Lager empfängt."],
    ["Welche Marktplatz-Links unterstützt USFans?", "Die Startseite nennt Taobao, 1688 und Weidian und beschreibt eine Bestellung durch Einfügen des Produktlinks."],
    ["Wann kauft USFans bezahlte Bestellungen?", "Aktuelle Produktseiten nennen 09:00–18:00 Uhr chinesischer Zeit (UTC+8). Die Versandzeit des Verkäufers ist davon getrennt."],
    ["Wie viele kostenlose QC-Fotos gibt es?", "Aktuelle USFans-Produktseiten nennen 3–7 kostenlose HD-Prüffotos nach dem Lagereingang."],
    ["Kann ich nach den QC-Fotos zurückgeben?", "Lagerfotos zeitnah prüfen. Rückgabefrist, Berechtigung und Einschränkungen am konkreten Auftrag kontrollieren; die Zustimmung des Verkäufers ist nicht garantiert."],
    ["Ist der Spreadsheet-Preis der Lieferpreis?", "Nein. Inlandsversand, Verpackung oder Dienste, internationale Fracht und mögliche Zielgebühren können den Gesamtpreis ändern."],
    ["Wie wird Volumengewicht berechnet?", "Gewicht und Maße des verpackten Pakets verwenden. Volumendivisor, Rundung, Grenzen und Abrechnung der gewählten Linie prüfen; eine Formel gilt nicht automatisch für alle Routen."],
    ["Beweisen QC-Fotos Echtheit?", "Nein. Sie zeigen den sichtbaren Zustand in den gelieferten Ansichten, beweisen aber weder Echtheit noch Material, verborgene Konstruktion oder Haltbarkeit."],
    ["In wie viele Länder versendet USFans?", "Die Startseite wirbt mit mehr als 50 Ländern. Die tatsächliche Route hängt von Ziel, Paket, Produktkategorie und aktuellen Regeln ab."],
    ["Verkauft dieses unabhängige Verzeichnis Produkte?", "Nein. Es organisiert Entdeckung und Recherche. Prüfe vorab Live-Angebot, QC, Paketpreis und geltende Bedingungen."],
  ],
  fr: [
    ["Qu’est-ce que USFans ?", "USFans se présente comme un agent d’achat qui commande sur des marketplaces chinoises et reçoit les articles en entrepôt avant l’envoi international."],
    ["Quels liens marketplace sont acceptés ?", "La page d’accueil cite Taobao, 1688 et Weidian et décrit une commande par collage du lien produit."],
    ["Quand USFans achète-t-il les commandes payées ?", "Les fiches actuelles indiquent 09:00–18:00, heure de Chine (UTC+8). Le délai d’expédition du vendeur est distinct."],
    ["Combien de photos QC gratuites sont fournies ?", "Les pages produit USFans annoncent actuellement 3 à 7 photos d’inspection HD gratuites après l’arrivée en entrepôt."],
    ["Puis-je demander un retour après le QC ?", "Examinez rapidement les photos. Vérifiez délai, admissibilité et restrictions du retour sur la commande précise ; l’accord du vendeur n’est pas garanti."],
    ["Le prix de la feuille est-il le prix livré ?", "Non. Livraison intérieure, emballage ou services, fret international et éventuels frais à destination peuvent modifier le total."],
    ["Comment calculer le poids volumétrique ?", "Utilisez le poids et les dimensions emballés. Vérifiez diviseur volumétrique, arrondi, limites et facturation de la ligne choisie ; aucune formule unique ne doit être supposée pour toutes les lignes."],
    ["Les photos QC prouvent-elles l’authenticité ?", "Non. Elles montrent l’état visible dans les vues fournies, mais ne prouvent ni authenticité, ni composition, ni structure cachée, ni durabilité."],
    ["Vers combien de pays USFans expédie-t-il ?", "La page d’accueil annonce plus de 50 pays. Les routes réelles dépendent de la destination, du colis, de la catégorie et des règles actuelles."],
    ["Ce répertoire indépendant vend-il les produits ?", "Non. Il organise la découverte et la recherche. Vérifiez l’annonce, le QC, le devis du colis et les conditions applicables."],
  ],
  it: [
    ["Cos’è USFans?", "USFans si presenta come agente d’acquisto che compra su marketplace cinesi e riceve gli articoli in magazzino prima della spedizione internazionale."],
    ["Quali link marketplace supporta?", "La home cita Taobao, 1688 e Weidian e descrive l’ordine tramite incolla del link prodotto."],
    ["Quando acquista gli ordini pagati?", "Le pagine prodotto attuali indicano 09:00–18:00 ora cinese (UTC+8). Il tempo di spedizione del venditore è separato."],
    ["Quante foto QC gratuite vengono fornite?", "Le pagine prodotto USFans pubblicizzano 3–7 foto d’ispezione HD gratuite dopo l’arrivo in magazzino."],
    ["Posso chiedere il reso dopo il QC?", "Controlla subito le foto. Verifica scadenza, ammissibilità e restrizioni del reso sull’ordine specifico; l’accettazione del venditore non è garantita."],
    ["Il prezzo del foglio è il prezzo consegnato?", "No. Consegna nazionale, imballaggio o servizi, trasporto internazionale e possibili oneri a destinazione possono cambiare il totale."],
    ["Come si calcola il peso volumetrico?", "Usa peso e dimensioni imballati. Verifica divisore volumetrico, arrotondamenti, limiti e fatturazione della linea scelta; non applicare una formula a tutte le rotte."],
    ["Le foto QC provano l’autenticità?", "No. Mostrano condizioni visibili nelle immagini fornite, ma non provano autenticità, materiali, struttura interna o durata."],
    ["In quanti paesi spedisce USFans?", "La home pubblicizza oltre 50 paesi. Le rotte effettive dipendono da destinazione, pacco, categoria e regole correnti."],
    ["Questo catalogo indipendente vende prodotti?", "No. Organizza scoperta e ricerca. Verifica inserzione, QC, preventivo del pacco e condizioni applicabili."],
  ],
  es: [
    ["¿Qué es USFans?", "USFans se presenta como agente de compra que adquiere en marketplaces chinos y recibe los artículos en almacén antes del envío internacional."],
    ["¿Qué enlaces de marketplace admite?", "La página principal menciona Taobao, 1688 y Weidian y describe pedidos pegando el enlace del producto."],
    ["¿Cuándo compra los pedidos pagados?", "Las fichas actuales indican 09:00–18:00 hora de China (UTC+8). El tiempo de envío del vendedor es independiente."],
    ["¿Cuántas fotos QC gratuitas proporciona?", "Las páginas de USFans anuncian actualmente 3–7 fotos de inspección HD gratuitas tras la llegada al almacén."],
    ["¿Puedo pedir devolución tras el QC?", "Revisa pronto las fotos. Comprueba plazo, elegibilidad y restricciones de devolución en el pedido concreto; no se garantiza la aceptación del vendedor."],
    ["¿El precio de la hoja es el precio entregado?", "No. Envío nacional, embalaje o servicios, transporte internacional y posibles cargos en destino pueden cambiar el total."],
    ["¿Cómo se calcula el peso volumétrico?", "Usa peso y dimensiones embalados. Comprueba divisor volumétrico, redondeos, límites y facturación de la línea elegida; no apliques una fórmula a todas las rutas."],
    ["¿Las fotos QC prueban autenticidad?", "No. Documentan el estado visible en las tomas facilitadas, pero no prueban autenticidad, materiales, construcción interna ni duración."],
    ["¿A cuántos países envía USFans?", "La página principal anuncia más de 50 países. Las rutas reales dependen del destino, paquete, categoría y reglas actuales."],
    ["¿Este directorio independiente vende productos?", "No. Organiza descubrimiento e investigación. Revisa anuncio, QC, presupuesto del paquete y condiciones aplicables."],
  ],
  ro: [
    ["Ce este USFans?", "USFans se prezintă ca agent de cumpărături care achiziționează de pe marketplace-uri chineze și primește produsele în depozit înaintea expedierii internaționale."],
    ["Ce linkuri marketplace acceptă?", "Pagina principală menționează Taobao, 1688 și Weidian și descrie comanda prin lipirea linkului produsului."],
    ["Când cumpără comenzile plătite?", "Paginile actuale indică 09:00–18:00 ora Chinei (UTC+8). Timpul de expediere al vânzătorului este separat."],
    ["Câte fotografii QC gratuite sunt oferite?", "Paginile USFans anunță în prezent 3–7 fotografii HD gratuite după sosirea în depozit."],
    ["Pot solicita retur după QC?", "Verifică rapid fotografiile. Consultă termenul, eligibilitatea și restricțiile returului în comanda concretă; acceptarea vânzătorului nu este garantată."],
    ["Prețul din foaie este prețul livrat?", "Nu. Livrarea internă, ambalarea sau serviciile, transportul internațional și posibilele taxe la destinație pot modifica totalul."],
    ["Cum se calculează greutatea volumetrică?", "Folosește greutatea și dimensiunile ambalate. Verifică divizorul volumetric, rotunjirea, limitele și taxarea rutei alese; nu aplica aceeași formulă tuturor rutelor."],
    ["Fotografiile QC dovedesc autenticitatea?", "Nu. Ele arată starea vizibilă în imaginile oferite, dar nu dovedesc autenticitatea, materialele, structura ascunsă sau durabilitatea."],
    ["În câte țări expediază USFans?", "Pagina principală promovează peste 50 de țări. Rutele reale depind de destinație, colet, categorie și regulile actuale."],
    ["Acest catalog independent vinde produse?", "Nu. Organizează descoperirea și cercetarea. Verifică oferta, QC, estimarea coletului și condițiile aplicabile."],
  ],
};

