import { researchedEnglishArticles } from "./english-articles";

export type Locale = "pl" | "en" | "de" | "fr" | "it" | "es" | "ro";
export type PageKind = "home" | "finds" | "categories" | "guides" | "articles" | "faq" | "article";

export const locales: Array<{ code: Locale; label: string; short: string; lang: string }> = [
  { code: "pl", label: "Polski", short: "PL", lang: "pl-PL" },
  { code: "en", label: "English", short: "EN", lang: "en" },
  { code: "de", label: "Deutsch", short: "DE", lang: "de-DE" },
  { code: "fr", label: "Français", short: "FR", lang: "fr-FR" },
  { code: "it", label: "Italiano", short: "IT", lang: "it-IT" },
  { code: "es", label: "Español", short: "ES", lang: "es-ES" },
  { code: "ro", label: "Română", short: "RO", lang: "ro-RO" },
];

export const products = [
  { name: "P6000 / Gel-Kayano Mix", category: "Footwear", price: "$43", image: "https://www.cnbuycha.com/uploads/allimg/20260806/1-260P6164I0217.webp", href: "https://www.cnbuycha.com/AllProducts/3402.html", qcTip: "Compare both shoes, size labels, soles, stitching, and colour panels." },
  { name: "The North Face Down Jacket", category: "Outerwear", price: "$98", image: "https://www.cnbuycha.com/uploads/allimg/20260806/1-260P6163I3956.webp", href: "https://www.cnbuycha.com/AllProducts/3396.html", qcTip: "Check the size label, zip, logo placement, seams, and even down filling." },
  { name: "Mertra Hoodie", category: "Hoodies", price: "$31", image: "https://www.cnbuycha.com/uploads/allimg/20260806/1-260P616301A57.webp", href: "https://www.cnbuycha.com/AllProducts/3393.html", qcTip: "Verify chest length, print alignment, cuffs, stitching, and fabric colour." },
  { name: "LOUIS VUITTON Runner Tatic", category: "Footwear", price: "$88", image: "https://www.cnbuycha.com/uploads/allimg/20260804/1-260P4220203120.webp", href: "https://www.cnbuycha.com/AllProducts/3388.html", qcTip: "Compare the pair, heel shape, panel alignment, outsole, and size tag." },
  { name: "Adidas Bag", category: "Accessories", price: "$27", image: "https://www.cnbuycha.com/uploads/allimg/20260804/1-260P4220335407.webp", href: "https://www.cnbuycha.com/AllProducts/3389.html", qcTip: "Inspect the zip, strap hardware, seams, interior, and visible marks." },
  { name: "Louis Vuitton Wallet", category: "Accessories", price: "$17", image: "https://www.cnbuycha.com/uploads/allimg/20260729/1-260H9212KN32.webp", href: "https://www.cnbuycha.com/AllProducts/3382.html", qcTip: "Check edge paint, stitching, card slots, fold alignment, and surface marks." },
];

export const categories = [
  ["Shoes", "01", "https://www.cnbuycha.com/shoes/"],
  ["Hoodies", "02", "https://www.cnbuycha.com/hoodies-sweaters/"],
  ["T-Shirts", "03", "https://www.cnbuycha.com/t-shirts/"],
  ["Jackets", "04", "https://www.cnbuycha.com/jackets/"],
  ["Pants", "05", "https://www.cnbuycha.com/pants-shorts/"],
  ["Headwear", "06", "https://www.cnbuycha.com/headwear/"],
  ["Accessories", "07", "https://www.cnbuycha.com/accessories/"],
  ["Jerseys", "08", "https://www.cnbuycha.com/Jersey/"],
  ["Electronics", "09", "https://www.cnbuycha.com/electronics/"],
  ["Other finds", "10", "https://www.cnbuycha.com/other-stuff/"],
] as const;

export const allProducts = "https://www.cnbuycha.com/AllProducts/";
export const articleSlugs = ["first-time-spreadsheet-checklist", "read-usfans-qc-photos", "product-price-vs-parcel-cost"] as const;
export type ArticleSlug = typeof articleSlugs[number];

type Copy = {
  nav: Record<"home" | "finds" | "categories" | "guides" | "articles" | "faq", string>;
  browseAll: string; language: string; independent: string; updated: string;
  heroLines: [string, string, string]; heroBody: string; searchLabel: string; searchPlaceholder: string; search: string;
  explore: string; howLink: string; categoriesKicker: string; categoriesTitle: string; categoriesBody: string;
  findsKicker: string; findsTitle: string; findsBody: string; viewIndex: string; approx: string; priceNote: string;
  howKicker: string; howTitle: string; howBody: string; steps: Array<[string, string]>;
  guidesKicker: string; guidesTitle: string; guidesBody: string; articleKicker: string; articlesTitle: string; articlesBody: string;
  readArticle: string; planned: string; faqKicker: string; faqTitle: string; faqIntro: string;
  faqs: Array<[string, string]>; finalEyebrow: string; finalTitle: string; finalCta: string;
  disclaimer: string; backTop: string; currentPage: string; articleIndex: string; keyTakeaways: string;
};

export const copy: Record<Locale, Copy> = {
  pl: {
    nav: { home: "Start", finds: "Znaleziska", categories: "Kategorie", guides: "Poradniki", articles: "Artykuły SEO", faq: "FAQ" },
    browseAll: "Zobacz wszystko", language: "Język", independent: "Niezależny katalog produktów", updated: "Aktualizacja 2026",
    heroLines: ["USFans Spreadsheet Polska:", "Znaleziska produktów", "i zdjęcia QC."],
    heroBody: "Przejrzysty sposób przeglądania znalezisk z arkuszy USFans — według kategorii, z rzeczywistymi zdjęciami produktów i wygodnie na telefonie.",
    searchLabel: "Przeszukaj katalog produktów", searchPlaceholder: "Wpisz: bluza, buty, torba…", search: "Szukaj", explore: "Zobacz najnowsze znaleziska", howLink: "Jak działa katalog",
    categoriesKicker: "Zacznij szeroko", categoriesTitle: "Wybierz kategorię, potem zawęź wybór.", categoriesBody: "Każda kategoria prowadzi do osobnej, aktualnej kolekcji produktów.",
    findsKicker: "Aktualny katalog", findsTitle: "Znaleziska warte otwarcia jako pierwsze.", findsBody: "Krótka lista produktów zamiast tysięcy trudnych do przejrzenia wierszy.", viewIndex: "Pełny katalog produktów", approx: "około", priceNote: "Ceny w USD są orientacyjne. Aktualna oferta, wybrany wariant, dostawa krajowa, usługi i wysyłka międzynarodowa mogą zmienić końcową kwotę.",
    howKicker: "Prostsza droga", howTitle: "Od inspiracji do strony produktu w trzech krokach.", howBody: "Najpierw kategoria lub wyszukiwanie, następnie krótka lista, a na końcu pełna strona produktu do samodzielnej weryfikacji.", steps: [["Szukaj lub przeglądaj", "Wybierz słowo kluczowe albo jedną z dziesięciu kategorii."], ["Otwórz szczegóły", "Sprawdź zdjęcia produktu oraz aktualnie dostępne informacje."], ["Zweryfikuj przed decyzją", "Porównaj cenę, wariant, sprzedawcę, zdjęcia QC i warunki wysyłki."]],
    guidesKicker: "Praktyczna wiedza", guidesTitle: "Poradniki rozwiązujące realne problemy.", guidesBody: "Osobne strony o zdjęciach QC, kosztach przesyłki i bezpiecznym przeglądaniu ofert.", articleKicker: "Centrum treści", articlesTitle: "Artykuły SEO pisane dla ludzi.", articlesBody: "Oryginalne, oparte na sprawdzonych faktach materiały odpowiadające na konkretne pytania użytkowników.", readArticle: "Czytaj artykuł", planned: "Pełny poradnik", faqKicker: "Krótkie odpowiedzi", faqTitle: "Najczęstsze pytania", faqIntro: "Podstawowe informacje przed otwarciem oferty lub użyciem katalogu.",
    faqs: [["Czym jest arkusz USFans?", "To uporządkowany katalog linków do produktów z chińskich platform handlowych. Ta witryna zmienia długi arkusz w wygodny katalog na telefon."], ["Czy pokazane ceny są ostateczne?", "Nie. To orientacyjne przeliczenia na USD. Cena wariantu, przesyłka krajowa, usługi oraz wysyłka międzynarodowa wpływają na końcowy koszt."], ["Czy ta witryna sprzedaje produkty?", "Nie. Jest niezależnym katalogiem informacyjnym. Karty otwierają osobne strony produktów, na których można sprawdzić aktualne dane."], ["Czy zmiana języka usuwa treść?", "Nie. Każda wersja językowa zachowuje te same strony, moduły, produkty, artykuły i FAQ."]],
    finalEyebrow: "Mniej przewijania. Lepsze pierwsze kliknięcia.", finalTitle: "Znajdź następny produkt.", finalCta: "Otwórz katalog", disclaimer: "Niezależny katalog produktów. Brak powiązania z USFans, Taobao, Weidian, 1688 ani agentem zakupowym. Przed zakupem sprawdź aktualny produkt, sprzedawcę, QC, cenę i warunki wysyłki.", backTop: "Na górę", currentPage: "Bieżąca strona", articleIndex: "Wszystkie artykuły", keyTakeaways: "Najważniejsze wnioski"
  },
  en: {
    nav: { home: "Home", finds: "Finds", categories: "Categories", guides: "Guides", articles: "SEO Articles", faq: "FAQ" }, browseAll: "Browse all", language: "Language", independent: "Independent product finder", updated: "Updated 2026",
    heroLines: ["USFans Spreadsheet 2026:", "Product Finds, QC Photos", "& Guides."], heroBody: "A cleaner way to explore USFans-style spreadsheet finds—organized by category, presented with real product imagery, and built for fast mobile browsing.", searchLabel: "Search the product index", searchPlaceholder: "Try hoodie, runner, bag…", search: "Search", explore: "Explore this week's finds", howLink: "How the index works",
    categoriesKicker: "Start broad", categoriesTitle: "Pick a category, then go specific.", categoriesBody: "Every category opens a separate, current product collection.", findsKicker: "Fresh index", findsTitle: "Finds worth opening first.", findsBody: "A focused product shortlist instead of thousands of difficult spreadsheet rows.", viewIndex: "View full product index", approx: "approx.", priceNote: "USD prices are approximate guides. The current listing, selected option, domestic delivery, services, and international shipping may change the final amount.", howKicker: "A better route", howTitle: "From inspiration to the product page in three steps.", howBody: "Start with search or a category, compare a short list, then open the full detail page and verify the current information.", steps: [["Search or browse", "Use a keyword or choose one of ten focused collections."], ["Open the detail", "Review product imagery and the information currently available."], ["Verify before deciding", "Check the price, option, seller, QC imagery, and shipping terms."]],
    guidesKicker: "Practical knowledge", guidesTitle: "Guides for real shopping questions.", guidesBody: "Independent pages covering QC photos, parcel costs, and safer listing research.", articleKicker: "Content hub", articlesTitle: "SEO articles written for people.", articlesBody: "Original, fact-checked content that answers a specific user question without filler.", readArticle: "Read article", planned: "Complete guide", faqKicker: "Short answers", faqTitle: "Frequently asked questions", faqIntro: "The essentials to understand before opening a listing or using the index.", faqs: [["What is a USFans spreadsheet?", "It is an organized directory of product links from Chinese marketplaces. This site turns a long spreadsheet into a mobile-friendly catalog."], ["Are displayed prices final?", "No. They are approximate USD conversions. The option, domestic delivery, services, and international shipping can change the total."], ["Does this website sell products?", "No. It is an independent information directory. Product cards open separate detail pages where current information can be checked."], ["Does changing language remove content?", "No. Every language keeps the same pages, modules, products, articles, and FAQ items."]], finalEyebrow: "Less scrolling. Better first clicks.", finalTitle: "Find your next piece.", finalCta: "Open the index", disclaimer: "Independent product discovery directory. Not affiliated with USFans, Taobao, Weidian, 1688, or any shopping agent. Verify the current product, seller, QC, price, and shipping terms before purchase.", backTop: "Back to top", currentPage: "Current page", articleIndex: "All articles", keyTakeaways: "Key takeaways"
  },
  de: {
    nav: { home: "Start", finds: "Fundstücke", categories: "Kategorien", guides: "Ratgeber", articles: "SEO-Artikel", faq: "FAQ" }, browseAll: "Alle ansehen", language: "Sprache", independent: "Unabhängiger Produktfinder", updated: "Aktualisiert 2026",
    heroLines: ["Finde das Produkt.", "Prüfe die Details.", "Kaufe klüger."], heroBody: "Eine übersichtliche Möglichkeit, USFans-Spreadsheet-Fundstücke nach Kategorie, mit echten Produktbildern und mobilfreundlich zu entdecken.", searchLabel: "Produktindex durchsuchen", searchPlaceholder: "Hoodie, Sneaker, Tasche…", search: "Suchen", explore: "Aktuelle Fundstücke", howLink: "So funktioniert der Index", categoriesKicker: "Breit starten", categoriesTitle: "Kategorie wählen, Auswahl verfeinern.", categoriesBody: "Jede Kategorie öffnet eine eigene aktuelle Produktsammlung.", findsKicker: "Aktueller Index", findsTitle: "Fundstücke, die sich zuerst lohnen.", findsBody: "Eine kurze Auswahl statt tausender schwer lesbarer Tabellenzeilen.", viewIndex: "Vollständiger Produktindex", approx: "ca.", priceNote: "USD-Preise sind Richtwerte. Angebot, Variante, Inlandsversand, Dienste und internationaler Versand können den Endbetrag ändern.", howKicker: "Der bessere Weg", howTitle: "In drei Schritten zur Produktseite.", howBody: "Suche oder Kategorie öffnen, eine kurze Liste vergleichen und anschließend die aktuellen Details prüfen.", steps: [["Suchen oder stöbern", "Suchbegriff nutzen oder eine von zehn Kategorien wählen."], ["Details öffnen", "Produktbilder und derzeit verfügbare Informationen prüfen."], ["Vorher verifizieren", "Preis, Variante, Verkäufer, QC-Bilder und Versandbedingungen prüfen."]], guidesKicker: "Praktisches Wissen", guidesTitle: "Ratgeber für echte Fragen.", guidesBody: "Eigene Seiten zu QC-Fotos, Paketkosten und sicherer Angebotsprüfung.", articleKicker: "Content-Hub", articlesTitle: "SEO-Artikel für Menschen.", articlesBody: "Originelle, faktengeprüfte Inhalte ohne Fülltext.", readArticle: "Artikel lesen", planned: "Vollständiger Ratgeber", faqKicker: "Kurze Antworten", faqTitle: "Häufige Fragen", faqIntro: "Wichtige Grundlagen vor dem Öffnen eines Angebots.", faqs: [["Was ist ein USFans Spreadsheet?", "Ein geordnetes Verzeichnis von Produktlinks chinesischer Marktplätze, hier als mobilfreundlicher Katalog."], ["Sind die Preise endgültig?", "Nein. Es sind ungefähre USD-Werte; Optionen, Dienstleistungen und Versand ändern den Gesamtpreis."], ["Verkauft diese Website Produkte?", "Nein. Sie ist ein unabhängiges Informationsverzeichnis mit Links zu separaten Detailseiten."], ["Verschwindet Inhalt beim Sprachwechsel?", "Nein. Seiten, Module, Produkte, Artikel und FAQ bleiben vollständig erhalten."]], finalEyebrow: "Weniger scrollen. Besser klicken.", finalTitle: "Finde dein nächstes Produkt.", finalCta: "Index öffnen", disclaimer: "Unabhängiges Produktverzeichnis. Keine Verbindung zu USFans, Taobao, Weidian, 1688 oder einem Einkaufsagenten. Aktuelle Produkt-, Verkäufer-, QC-, Preis- und Versanddaten vor dem Kauf prüfen.", backTop: "Nach oben", currentPage: "Aktuelle Seite", articleIndex: "Alle Artikel", keyTakeaways: "Das Wichtigste"
  },
  fr: {
    nav: { home: "Accueil", finds: "Sélection", categories: "Catégories", guides: "Guides", articles: "Articles SEO", faq: "FAQ" }, browseAll: "Tout voir", language: "Langue", independent: "Répertoire indépendant", updated: "Mis à jour 2026",
    heroLines: ["Trouvez l’article.", "Vérifiez les détails.", "Achetez mieux."], heroBody: "Une façon plus claire d’explorer les trouvailles de type USFans Spreadsheet, classées par catégorie et pensées pour le mobile.", searchLabel: "Rechercher dans l’index", searchPlaceholder: "Sweat, chaussures, sac…", search: "Rechercher", explore: "Voir les nouveautés", howLink: "Fonctionnement de l’index", categoriesKicker: "Commencer largement", categoriesTitle: "Choisissez une catégorie, puis affinez.", categoriesBody: "Chaque catégorie ouvre une collection de produits distincte et actuelle.", findsKicker: "Index actuel", findsTitle: "Les trouvailles à ouvrir d’abord.", findsBody: "Une sélection courte plutôt que des milliers de lignes difficiles à lire.", viewIndex: "Index complet", approx: "env.", priceNote: "Les prix USD sont indicatifs. L’offre, l’option, les services et l’expédition peuvent modifier le total.", howKicker: "Un meilleur parcours", howTitle: "De l’idée à la fiche produit en trois étapes.", howBody: "Recherchez, comparez une courte liste, puis vérifiez les informations actuelles sur la fiche.", steps: [["Rechercher ou parcourir", "Utilisez un mot-clé ou l’une des dix catégories."], ["Ouvrir la fiche", "Examinez les images et les informations disponibles."], ["Vérifier avant de décider", "Contrôlez prix, option, vendeur, photos QC et expédition."]], guidesKicker: "Conseils pratiques", guidesTitle: "Des guides pour de vraies questions.", guidesBody: "Pages dédiées aux photos QC, aux coûts de colis et à la vérification des annonces.", articleKicker: "Centre de contenu", articlesTitle: "Des articles SEO utiles.", articlesBody: "Contenu original et vérifié répondant précisément aux questions des utilisateurs.", readArticle: "Lire l’article", planned: "Guide complet", faqKicker: "Réponses courtes", faqTitle: "Questions fréquentes", faqIntro: "L’essentiel avant d’ouvrir une annonce.", faqs: [["Qu’est-ce qu’un USFans Spreadsheet ?", "Un répertoire organisé de liens produits de marketplaces chinoises, transformé ici en catalogue mobile."], ["Les prix sont-ils définitifs ?", "Non. Ce sont des conversions USD approximatives; options, services et transport modifient le total."], ["Ce site vend-il des produits ?", "Non. C’est un répertoire indépendant renvoyant vers des fiches séparées."], ["Le changement de langue supprime-t-il du contenu ?", "Non. Pages, modules, produits, articles et FAQ restent identiques."]], finalEyebrow: "Moins de défilement. De meilleurs clics.", finalTitle: "Trouvez votre prochaine pièce.", finalCta: "Ouvrir l’index", disclaimer: "Répertoire indépendant, sans affiliation avec USFans, Taobao, Weidian, 1688 ou un agent d’achat. Vérifiez produit, vendeur, QC, prix et expédition avant achat.", backTop: "Haut de page", currentPage: "Page actuelle", articleIndex: "Tous les articles", keyTakeaways: "À retenir"
  },
  it: {
    nav: { home: "Home", finds: "Prodotti", categories: "Categorie", guides: "Guide", articles: "Articoli SEO", faq: "FAQ" }, browseAll: "Vedi tutto", language: "Lingua", independent: "Catalogo indipendente", updated: "Aggiornato 2026",
    heroLines: ["Trova il prodotto.", "Controlla i dettagli.", "Acquista meglio."], heroBody: "Un modo più chiaro per esplorare prodotti da spreadsheet in stile USFans, organizzati per categoria e ottimizzati per smartphone.", searchLabel: "Cerca nel catalogo", searchPlaceholder: "Felpa, scarpe, borsa…", search: "Cerca", explore: "Scopri le novità", howLink: "Come funziona", categoriesKicker: "Parti dal generale", categoriesTitle: "Scegli una categoria, poi restringi.", categoriesBody: "Ogni categoria apre una raccolta separata e aggiornata.", findsKicker: "Catalogo aggiornato", findsTitle: "Prodotti da aprire per primi.", findsBody: "Una selezione breve invece di migliaia di righe difficili.", viewIndex: "Catalogo completo", approx: "circa", priceNote: "I prezzi USD sono indicativi. Inserzione, variante, servizi e spedizione possono cambiare il totale.", howKicker: "Percorso semplice", howTitle: "Dall’ispirazione alla pagina prodotto in tre passaggi.", howBody: "Cerca o scegli una categoria, confronta pochi prodotti e verifica i dettagli attuali.", steps: [["Cerca o esplora", "Usa una parola chiave o una delle dieci categorie."], ["Apri i dettagli", "Controlla immagini e informazioni disponibili."], ["Verifica prima di decidere", "Controlla prezzo, opzione, venditore, foto QC e spedizione."]], guidesKicker: "Conoscenza pratica", guidesTitle: "Guide per domande reali.", guidesBody: "Pagine dedicate a foto QC, costi del pacco e controllo delle inserzioni.", articleKicker: "Centro contenuti", articlesTitle: "Articoli SEO utili alle persone.", articlesBody: "Contenuti originali e verificati senza testo riempitivo.", readArticle: "Leggi l’articolo", planned: "Guida completa", faqKicker: "Risposte brevi", faqTitle: "Domande frequenti", faqIntro: "Le informazioni essenziali prima di aprire un’inserzione.", faqs: [["Cos’è uno USFans Spreadsheet?", "Un catalogo ordinato di link prodotto da marketplace cinesi, trasformato qui per smartphone."], ["I prezzi sono definitivi?", "No. Sono stime USD; opzioni, servizi e spedizione modificano il totale."], ["Questo sito vende prodotti?", "No. È un catalogo informativo indipendente con pagine dettaglio separate."], ["Il cambio lingua rimuove contenuti?", "No. Pagine, moduli, prodotti, articoli e FAQ restano completi."]], finalEyebrow: "Meno scorrimento. Clic migliori.", finalTitle: "Trova il prossimo prodotto.", finalCta: "Apri il catalogo", disclaimer: "Catalogo indipendente, non affiliato a USFans, Taobao, Weidian, 1688 o agenti. Verifica prodotto, venditore, QC, prezzo e spedizione prima dell’acquisto.", backTop: "Torna su", currentPage: "Pagina corrente", articleIndex: "Tutti gli articoli", keyTakeaways: "Punti chiave"
  },
  es: {
    nav: { home: "Inicio", finds: "Hallazgos", categories: "Categorías", guides: "Guías", articles: "Artículos SEO", faq: "FAQ" }, browseAll: "Ver todo", language: "Idioma", independent: "Buscador independiente", updated: "Actualizado 2026",
    heroLines: ["Encuentra la pieza.", "Revisa los detalles.", "Compra mejor."], heroBody: "Una forma más clara de explorar hallazgos tipo USFans Spreadsheet, organizados por categoría y pensados para móvil.", searchLabel: "Buscar en el catálogo", searchPlaceholder: "Sudadera, zapatillas, bolso…", search: "Buscar", explore: "Explorar novedades", howLink: "Cómo funciona", categoriesKicker: "Empieza en general", categoriesTitle: "Elige una categoría y luego concreta.", categoriesBody: "Cada categoría abre una colección separada y actual.", findsKicker: "Catálogo actual", findsTitle: "Hallazgos que conviene abrir primero.", findsBody: "Una selección breve en lugar de miles de filas difíciles.", viewIndex: "Catálogo completo", approx: "aprox.", priceNote: "Los precios USD son orientativos. Anuncio, variante, servicios y envío pueden cambiar el total.", howKicker: "Una ruta mejor", howTitle: "De la inspiración a la ficha en tres pasos.", howBody: "Busca o elige categoría, compara una lista corta y verifica la información actual.", steps: [["Busca o explora", "Usa una palabra clave o una de las diez categorías."], ["Abre los detalles", "Revisa imágenes e información disponible."], ["Verifica antes de decidir", "Comprueba precio, opción, vendedor, fotos QC y envío."]], guidesKicker: "Conocimiento práctico", guidesTitle: "Guías para preguntas reales.", guidesBody: "Páginas sobre fotos QC, costes de paquete y revisión de anuncios.", articleKicker: "Centro de contenido", articlesTitle: "Artículos SEO escritos para personas.", articlesBody: "Contenido original y contrastado que responde preguntas concretas.", readArticle: "Leer artículo", planned: "Guía completa", faqKicker: "Respuestas breves", faqTitle: "Preguntas frecuentes", faqIntro: "Lo esencial antes de abrir un anuncio.", faqs: [["¿Qué es un USFans Spreadsheet?", "Un directorio de enlaces de productos de marketplaces chinos convertido aquí en catálogo móvil."], ["¿Los precios son definitivos?", "No. Son estimaciones en USD; opciones, servicios y envío cambian el total."], ["¿Este sitio vende productos?", "No. Es un directorio independiente con enlaces a fichas separadas."], ["¿Cambiar idioma elimina contenido?", "No. Páginas, módulos, productos, artículos y FAQ siguen completos."]], finalEyebrow: "Menos desplazamiento. Mejores clics.", finalTitle: "Encuentra tu próxima pieza.", finalCta: "Abrir catálogo", disclaimer: "Directorio independiente, no afiliado a USFans, Taobao, Weidian, 1688 ni agentes. Verifica producto, vendedor, QC, precio y envío antes de comprar.", backTop: "Volver arriba", currentPage: "Página actual", articleIndex: "Todos los artículos", keyTakeaways: "Puntos clave"
  },
  ro: {
    nav: { home: "Acasă", finds: "Produse", categories: "Categorii", guides: "Ghiduri", articles: "Articole SEO", faq: "FAQ" }, browseAll: "Vezi tot", language: "Limbă", independent: "Catalog independent", updated: "Actualizat 2026",
    heroLines: ["Găsește produsul.", "Verifică detaliile.", "Cumpără mai informat."], heroBody: "O modalitate mai clară de a explora produse din foi de calcul de tip USFans, organizate pe categorii și optimizate pentru mobil.", searchLabel: "Caută în catalog", searchPlaceholder: "Hanorac, pantofi, geantă…", search: "Caută", explore: "Vezi produsele noi", howLink: "Cum funcționează", categoriesKicker: "Începe general", categoriesTitle: "Alege categoria, apoi restrânge.", categoriesBody: "Fiecare categorie deschide o colecție separată și actuală.", findsKicker: "Catalog actual", findsTitle: "Produse de deschis mai întâi.", findsBody: "O selecție scurtă în locul miilor de rânduri greu de urmărit.", viewIndex: "Catalog complet", approx: "aprox.", priceNote: "Prețurile USD sunt orientative. Oferta, varianta, serviciile și transportul pot modifica totalul.", howKicker: "Un traseu mai bun", howTitle: "De la inspirație la pagina produsului în trei pași.", howBody: "Caută sau alege categoria, compară o listă scurtă și verifică informațiile actuale.", steps: [["Caută sau navighează", "Folosește un cuvânt-cheie sau una dintre cele zece categorii."], ["Deschide detaliile", "Verifică imaginile și informațiile disponibile."], ["Verifică înainte de decizie", "Controlează prețul, opțiunea, vânzătorul, imaginile QC și transportul."]], guidesKicker: "Informații practice", guidesTitle: "Ghiduri pentru întrebări reale.", guidesBody: "Pagini despre fotografii QC, costurile coletului și verificarea ofertelor.", articleKicker: "Centru de conținut", articlesTitle: "Articole SEO scrise pentru oameni.", articlesBody: "Conținut original și verificat, fără text inutil.", readArticle: "Citește articolul", planned: "Ghid complet", faqKicker: "Răspunsuri scurte", faqTitle: "Întrebări frecvente", faqIntro: "Informațiile de bază înainte de a deschide o ofertă.", faqs: [["Ce este un USFans Spreadsheet?", "Un catalog organizat de linkuri către produse din marketplace-uri chineze, adaptat aici pentru mobil."], ["Prețurile sunt finale?", "Nu. Sunt estimări USD; opțiunile, serviciile și transportul modifică totalul."], ["Acest site vinde produse?", "Nu. Este un catalog independent cu linkuri spre pagini separate."], ["Schimbarea limbii elimină conținut?", "Nu. Paginile, modulele, produsele, articolele și FAQ rămân complete."]], finalEyebrow: "Mai puțină derulare. Clickuri mai bune.", finalTitle: "Găsește următorul produs.", finalCta: "Deschide catalogul", disclaimer: "Catalog independent, neafiliat cu USFans, Taobao, Weidian, 1688 sau agenți. Verifică produsul, vânzătorul, QC, prețul și transportul înainte de cumpărare.", backTop: "Sus", currentPage: "Pagina curentă", articleIndex: "Toate articolele", keyTakeaways: "Idei principale"
  }
};

type LocalArticle = { seoTitle?: string; title: string; excerpt: string; intro: string; points: string[]; sections: Array<[string, string]> };

const englishArticles = researchedEnglishArticles as unknown as Record<ArticleSlug, LocalArticle>;

const articleTranslations: Record<Exclude<Locale, "en">, Record<ArticleSlug, LocalArticle>> = {
  pl: {
    "read-usfans-qc-photos": { title: "Jak czytać zdjęcia QC USFans przed wysyłką międzynarodową", excerpt: "Praktyczna lista kontroli zdjęć magazynowych, wymiarów i widocznych wad.", intro: "Zdjęcia QC są ostatnim wizualnym punktem kontroli przed wysyłką międzynarodową. Strony produktów USFans informują o kilku zdjęciach inspekcyjnych HD, ale ich wartość zależy od tego, czy wiesz, co mogą — i czego nie mogą — potwierdzić.", points: ["Najpierw sprawdź kolor, metkę z rozmiarem i wybrany wariant.", "Porównaj obie strony, szwy, nadruk, okucia i widoczne uszkodzenia.", "Poproś o zdjęcie z miarką, gdy liczy się dopasowanie lub wymiar.", "Nie traktuj zdjęcia magazynowego jako dowodu autentyczności lub trwałości."], sections: [["Zacznij od zgodności zamówienia", "Potwierdź, że zdjęcia pokazują zamówiony produkt, kolor, rozmiar i liczbę sztuk. Nawet ostre zdjęcie nie pomaga, jeśli przedstawia inny wariant."], ["Sprawdzaj systematycznie", "Przejdź od ogólnego kształtu do detali: szwów, krawędzi, podeszew, zamków, logo, plam, zarysowań i opakowania. Elementy symetryczne porównuj obok siebie."], ["Podejmij decyzję przed końcem okresu zwrotu", "Jeśli widoczna wada ma znaczenie, opisz ją precyzyjnie i skorzystaj z dostępnej obsługi posprzedażowej przed wysyłką międzynarodową. Po opuszczeniu magazynu rozwiązanie problemu jest znacznie trudniejsze."]] },
    "product-price-vs-parcel-cost": { title: "Cena produktu a koszt paczki: czego nie pokazuje arkusz", excerpt: "Dlaczego niska cena oferty nie jest końcowym kosztem dostawy.", intro: "Cena w arkuszu zwykle dotyczy wyłącznie produktu. Końcowa kwota może obejmować dostawę krajową, usługi dodatkowe, opakowanie, wagę rozliczeniową przesyłki, transport międzynarodowy i opłaty w kraju docelowym.", points: ["Traktuj cenę produktu jako punkt startowy, nie koszt z dostawą.", "Oszacuj wagę rzeczywistą i objętościową przed zbudowaniem dużej paczki.", "Porównuj trasy dla tego samego kraju, wymiarów, wagi i typu produktu.", "Oddziel cło oraz opłaty lokalne od wyceny transportu agenta."], sections: [["Rozdziel warstwy kosztów", "Zapisz osobno cenę produktu, dostawę krajową, usługi magazynowe, opakowanie, transport międzynarodowy i możliwe opłaty w kraju odbiorcy."], ["Zrozum wagę rozliczeniową", "Niektóre trasy rozliczają wagę rzeczywistą, inne porównują ją z wagą objętościową. Dlatego lekki, ale duży produkt może kosztować więcej, niż wskazuje waga na skali."], ["Traktuj wycenę jako szacunek", "USFans udostępnia kalkulator wysyłki, jednak dopiero dane gotowej paczki i dostępne trasy określają rzeczywistą ofertę. Zostaw margines zamiast planować co do ostatniego dolara."]] },
    "first-time-spreadsheet-checklist": { title: "Lista kontrolna dla pierwszego arkusza USFans", excerpt: "Prosty proces sprawdzania linków, wariantów, zdjęć i kosztów.", intro: "Dobry arkusz ułatwia odkrywanie produktów, ale nie zastępuje weryfikacji. Linki, stan magazynowy sprzedawcy, warianty, zdjęcia i ceny mogą zmienić się po dodaniu pozycji do arkusza.", points: ["Otwórz aktualną stronę produktu zamiast polegać na zapisanym zrzucie.", "Przed płatnością dopasuj nazwę wariantu i jego zdjęcie.", "Zapisz szczegóły zamówienia użyte do porównania.", "Kontrolę QC i wycenę paczki traktuj jako dwie osobne decyzje."], sections: [["Używaj arkusza do odkrywania", "Zacznij od kategorii lub słowa kluczowego, a potem otwórz kilka najlepszych propozycji. Nie zamawiaj wyłącznie na podstawie tytułu lub miniatury."], ["Sprawdź aktualną ofertę", "Zweryfikuj bieżącą cenę, dostępne warianty, dane sprzedawcy, opis produktu oraz każde ostrzeżenie lub ograniczenie na stronie szczegółów."], ["Zaplanuj kontrolę magazynową", "Z góry ustal, co sprawdzisz po dotarciu produktu: wymiary, stan, liczbę sztuk, akcesoria i opakowanie. Dzięki temu kontrola QC jest szybsza i bardziej spójna."]] }
  },
  de: {
    "read-usfans-qc-photos": { title: "USFans QC-Fotos vor dem internationalen Versand richtig lesen", excerpt: "Praktische Prüfliste für Lagerfotos, Maße und sichtbare Mängel.", intro: "QC-Fotos sind die letzte visuelle Kontrolle, bevor ein Paket international versendet wird. USFans-Produktseiten nennen mehrere HD-Prüffotos; ihr Nutzen hängt jedoch davon ab, was die Bilder tatsächlich belegen können.", points: ["Zuerst Farbe, Größenetikett und gewählte Variante prüfen.", "Beide Seiten, Nähte, Druckposition, Beschläge und Schäden vergleichen.", "Bei wichtigen Maßen ein Foto mit Maßband anfordern.", "Lagerfotos beweisen weder Echtheit noch langfristige Haltbarkeit."], sections: [["Mit der Bestellidentität beginnen", "Prüfe, ob Produkt, Farbe, Größe und Menge auf den Fotos mit deiner Bestellung übereinstimmen. Ein scharfes Foto der falschen Variante hilft nicht."], ["Systematisch prüfen", "Arbeite vom Gesamtbild zu den Details: Nähte, Kanten, Sohlen, Reißverschlüsse, Logos, Flecken, Kratzer und Verpackung. Vergleiche symmetrische Teile direkt."], ["Vor Ende der Rückgabefrist entscheiden", "Dokumentiere sichtbare relevante Mängel und nutze den verfügbaren Kundendienst vor dem internationalen Versand. Nach Verlassen des Lagers wird eine Korrektur deutlich schwieriger."]] },
    "product-price-vs-parcel-cost": { title: "Produktpreis und Paketkosten: Was das Spreadsheet nicht zeigt", excerpt: "Warum ein niedriger Angebotspreis nicht den Endpreis bedeutet.", intro: "Ein Spreadsheet-Preis beschreibt meist nur den Artikel. Zum Lieferpreis können Inlandsversand, Zusatzleistungen, Verpackung, Abrechnungsgewicht, internationale Route und Gebühren im Zielland hinzukommen.", points: ["Produktpreis als Ausgangswert, nicht als Lieferpreis behandeln.", "Tatsächliches und volumetrisches Gewicht vor großen Paketen schätzen.", "Routen nur mit gleichem Ziel, Gewicht, Maß und Produkttyp vergleichen.", "Zoll und lokale Gebühren von der Transportofferte trennen."], sections: [["Kostenebenen trennen", "Notiere Produktpreis, Inlandsversand, optionale Lagerdienste, Verpackung, internationalen Transport und mögliche Zielgebühren als einzelne Positionen."], ["Abrechnungsgewicht verstehen", "Je nach Route zählt das tatsächliche Gewicht oder ein Vergleich mit dem Volumengewicht. Große leichte Artikel können daher mehr kosten, als die Waage vermuten lässt."], ["Schätzungen als Schätzungen nutzen", "USFans bietet einen Versandkostenrechner, doch erst die fertigen Paketdaten und verfügbaren Routen ergeben den tatsächlichen Preis. Plane einen Puffer ein."]] },
    "first-time-spreadsheet-checklist": { title: "USFans Spreadsheet Checkliste für Einsteiger", excerpt: "Ein einfacher Ablauf für Links, Varianten, Bilder und Kosten.", intro: "Ein gutes Spreadsheet hilft beim Entdecken, ersetzt aber keine Prüfung. Links, Lagerbestand, Varianten, Bilder und Preise können sich nach der Aufnahme eines Artikels ändern.", points: ["Aktuelle Detailseite statt eines gespeicherten Screenshots öffnen.", "Variantenname und Bild vor der Zahlung abgleichen.", "Die für den Vergleich genutzten Bestelldaten speichern.", "QC-Prüfung und Paketkalkulation getrennt entscheiden."], sections: [["Spreadsheet zur Entdeckung nutzen", "Starte mit Kategorie oder Suchwort und öffne nur wenige Kandidaten. Bestelle nicht allein anhand von Titel oder Vorschaubild."], ["Live-Angebot prüfen", "Prüfe aktuellen Preis, Varianten, Verkäuferangaben, Beschreibung sowie Warnungen oder Einschränkungen auf der Detailseite."], ["Lagerprüfung planen", "Lege vorher fest, was du nach der Ankunft kontrollierst: Maße, sichtbaren Zustand, Menge, Zubehör und Verpackung. Das macht die QC-Prüfung schneller und einheitlicher."]] }
  },
  fr: {
    "read-usfans-qc-photos": { title: "Lire les photos QC USFans avant l’expédition internationale", excerpt: "Liste pratique pour les photos d’entrepôt, mesures et défauts visibles.", intro: "Les photos QC sont votre dernier contrôle visuel avant l’expédition internationale. Les pages produit USFans annoncent plusieurs photos d’inspection HD, mais leur utilité dépend de ce qu’elles peuvent réellement confirmer.", points: ["Vérifiez d’abord la couleur, l’étiquette de taille et l’option choisie.", "Comparez les deux côtés, coutures, imprimés, pièces métalliques et dommages.", "Demandez une photo avec mesure lorsque les dimensions comptent.", "Une photo d’entrepôt ne prouve ni l’authenticité ni la durabilité."], sections: [["Commencer par l’identité de la commande", "Confirmez que le produit, la couleur, la taille et la quantité correspondent à la commande. Une image nette reste inutile si elle montre la mauvaise variante."], ["Inspecter méthodiquement", "Passez de la forme générale aux détails : coutures, bords, semelles, fermetures, logos, taches, rayures et emballage. Comparez les éléments symétriques."], ["Décider avant la fin du délai de retour", "Signalez précisément tout défaut visible important et utilisez le service après-vente disponible avant l’envoi international. Une correction devient bien plus difficile après le départ de l’entrepôt."]] },
    "product-price-vs-parcel-cost": { title: "Prix du produit et coût du colis : ce que la feuille ne montre pas", excerpt: "Pourquoi le prix affiché n’est pas le coût final livré.", intro: "Le prix d’une feuille correspond généralement à l’article seul. Le total livré peut aussi inclure transport intérieur, services, emballage, poids facturable, route internationale et frais du pays de destination.", points: ["Considérez le prix produit comme un départ, pas comme le total livré.", "Estimez poids réel et volumétrique avant de créer un gros colis.", "Comparez les routes avec les mêmes destination, poids, dimensions et produit.", "Séparez douane et frais locaux du devis de transport de l’agent."], sections: [["Séparer les couches de coût", "Notez séparément prix du produit, livraison intérieure, services d’entrepôt, emballage, transport international et éventuels frais à destination."], ["Comprendre le poids facturable", "Certaines routes facturent le poids réel, d’autres le comparent au poids volumétrique. Un article léger mais encombrant peut donc coûter plus que ne le suggère la balance."], ["Garder une marge dans les estimations", "USFans propose un outil d’estimation, mais les données finales du colis et les routes disponibles fixent le devis réel. Prévoyez une marge plutôt qu’un budget au centime près."]] },
    "first-time-spreadsheet-checklist": { title: "Checklist USFans Spreadsheet pour débuter", excerpt: "Un processus simple pour liens, variantes, images et coûts.", intro: "Une bonne feuille facilite la découverte, mais ne remplace pas la vérification. Liens, stock vendeur, variantes, photos et prix peuvent changer après l’ajout d’un article.", points: ["Ouvrez la fiche actuelle plutôt qu’une capture enregistrée.", "Faites correspondre nom et image de la variante avant de payer.", "Conservez les détails de commande utilisés pour comparer.", "Traitez contrôle QC et estimation du colis comme deux décisions."], sections: [["Utiliser la feuille pour découvrir", "Commencez par une catégorie ou un mot-clé, puis ouvrez quelques candidats. Ne commandez jamais à partir du seul titre ou de la miniature."], ["Vérifier l’annonce actuelle", "Contrôlez le prix, les variantes, le vendeur, la description et les avertissements ou restrictions affichés sur la fiche actuelle."], ["Préparer le contrôle en entrepôt", "Définissez à l’avance ce que vous inspecterez : mesures, état visible, quantité, accessoires et emballage. Le contrôle QC sera plus rapide et cohérent."]] }
  },
  it: {
    "read-usfans-qc-photos": { title: "Come leggere le foto QC USFans prima della spedizione", excerpt: "Checklist pratica per foto, misure e difetti visibili.", intro: "Le foto QC sono l’ultimo controllo visivo prima della spedizione internazionale. Le pagine prodotto USFans indicano diverse foto d’ispezione HD, ma il loro valore dipende da ciò che possono davvero dimostrare.", points: ["Controlla prima colore, etichetta della taglia e opzione scelta.", "Confronta lati, cuciture, stampa, ferramenta e danni visibili.", "Chiedi una foto con misura quando contano vestibilità o dimensioni.", "Una foto di magazzino non prova autenticità o durata."], sections: [["Parti dall’identità dell’ordine", "Conferma che prodotto, colore, taglia e quantità corrispondano all’ordine. Una foto nitida non aiuta se mostra la variante sbagliata."], ["Controlla in modo sistematico", "Passa dalla forma generale ai dettagli: cuciture, bordi, suole, zip, loghi, macchie, graffi e imballaggio. Confronta direttamente le parti simmetriche."], ["Decidi prima della scadenza del reso", "Descrivi chiaramente ogni difetto importante e usa l’assistenza disponibile prima della spedizione internazionale. Dopo l’uscita dal magazzino la correzione è molto più difficile."]] },
    "product-price-vs-parcel-cost": { title: "Prezzo del prodotto e costo del pacco", excerpt: "Perché un prezzo basso non è il costo finale consegnato.", intro: "Il prezzo nel foglio di solito riguarda solo l’articolo. Il totale può includere consegna nazionale, servizi, imballaggio, peso addebitabile, trasporto internazionale e oneri a destinazione.", points: ["Considera il prezzo del prodotto come partenza, non totale consegnato.", "Stima peso reale e volumetrico prima di creare un pacco grande.", "Confronta rotte con stessa destinazione, peso, misure e tipo di prodotto.", "Separa dogana e costi locali dal preventivo di trasporto."], sections: [["Separa i livelli di costo", "Annota separatamente prodotto, spedizione nazionale, servizi di magazzino, imballaggio, trasporto internazionale e possibili costi a destinazione."], ["Comprendi il peso addebitabile", "Alcune rotte usano il peso reale, altre lo confrontano con quello volumetrico. Un prodotto leggero ma ingombrante può costare più di quanto suggerisca la bilancia."], ["Usa le stime come stime", "USFans offre uno strumento di stima, ma il preventivo reale dipende dai dati finali del pacco e dalle rotte disponibili. Lascia un margine nel budget."]] },
    "first-time-spreadsheet-checklist": { title: "Checklist USFans Spreadsheet per principianti", excerpt: "Un flusso semplice per link, varianti, immagini e costi.", intro: "Un buon foglio aiuta a scoprire prodotti, ma non sostituisce la verifica. Link, disponibilità, varianti, foto e prezzi possono cambiare dopo l’inserimento.", points: ["Apri la pagina attuale invece di affidarti a uno screenshot.", "Abbina nome e immagine della variante prima di pagare.", "Salva i dettagli dell’ordine usati nel confronto.", "Tratta controllo QC e stima del pacco come decisioni separate."], sections: [["Usa il foglio per scoprire", "Parti da categoria o parola chiave e apri pochi candidati. Non ordinare basandoti solo su titolo o miniatura."], ["Controlla l’inserzione attuale", "Verifica prezzo, varianti, venditore, descrizione e ogni avviso o limitazione mostrati nella pagina dettagli."], ["Pianifica il controllo in magazzino", "Decidi prima cosa controllare all’arrivo: misure, condizioni visibili, quantità, accessori e imballaggio. Il controllo QC sarà più rapido e coerente."]] }
  },
  es: {
    "read-usfans-qc-photos": { title: "Cómo leer las fotos QC de USFans antes del envío", excerpt: "Lista práctica para fotos, medidas y defectos visibles.", intro: "Las fotos QC son el último control visual antes del envío internacional. Las páginas de producto de USFans anuncian varias fotos de inspección HD, pero su utilidad depende de entender qué pueden confirmar.", points: ["Comprueba primero color, etiqueta de talla y opción elegida.", "Compara lados, costuras, impresión, herrajes y daños visibles.", "Pide una foto con medida cuando importen el ajuste o las dimensiones.", "Una foto de almacén no demuestra autenticidad ni durabilidad."], sections: [["Empieza por identificar el pedido", "Confirma que producto, color, talla y cantidad coincidan con el pedido. Una imagen nítida no sirve si muestra la variante equivocada."], ["Inspecciona de forma sistemática", "Ve de la forma general a los detalles: costuras, bordes, suelas, cremalleras, logotipos, manchas, arañazos y embalaje. Compara las partes simétricas."], ["Decide antes de que cierre la devolución", "Documenta claramente los defectos importantes y utiliza la posventa disponible antes del envío internacional. Corregir un problema es mucho más difícil tras salir del almacén."]] },
    "product-price-vs-parcel-cost": { title: "Precio del producto y coste del paquete", excerpt: "Por qué un precio bajo no es el coste final entregado.", intro: "El precio de una hoja suele cubrir solo el artículo. El total puede incluir entrega nacional, servicios, embalaje, peso facturable, transporte internacional y cargos en destino.", points: ["Toma el precio del producto como inicio, no como total entregado.", "Estima peso real y volumétrico antes de crear un paquete grande.", "Compara rutas con igual destino, peso, dimensiones y tipo de producto.", "Separa aduanas y cargos locales del presupuesto del agente."], sections: [["Separa las capas de coste", "Anota por separado producto, envío nacional, servicios de almacén, embalaje, transporte internacional y posibles cargos de destino."], ["Comprende el peso facturable", "Algunas rutas cobran peso real y otras lo comparan con el volumétrico. Un producto ligero pero voluminoso puede costar más de lo que sugiere la báscula."], ["Usa las estimaciones como estimaciones", "USFans ofrece una calculadora de envío, pero los datos finales del paquete y las rutas disponibles fijan la tarifa real. Mantén un margen en el presupuesto."]] },
    "first-time-spreadsheet-checklist": { title: "Checklist USFans Spreadsheet para principiantes", excerpt: "Un proceso sencillo para enlaces, variantes, imágenes y costes.", intro: "Una buena hoja facilita descubrir productos, pero no sustituye la verificación. Enlaces, stock, variantes, fotos y precios pueden cambiar después de añadir un artículo.", points: ["Abre la ficha actual en lugar de confiar en una captura guardada.", "Comprueba nombre e imagen de la variante antes de pagar.", "Guarda los detalles del pedido usados para comparar.", "Trata la revisión QC y la estimación del paquete por separado."], sections: [["Usa la hoja para descubrir", "Empieza con una categoría o palabra clave y abre pocos candidatos. No compres basándote solo en el título o la miniatura."], ["Revisa el anuncio actual", "Comprueba precio, variantes, vendedor, descripción y cualquier aviso o restricción de la página de detalle."], ["Planifica la revisión de almacén", "Decide antes qué revisarás al llegar: medidas, estado visible, cantidad, accesorios y embalaje. Así el control QC será más rápido y coherente."]] }
  },
  ro: {
    "read-usfans-qc-photos": { title: "Cum citești fotografiile QC USFans înainte de expediere", excerpt: "Listă practică pentru fotografii, măsurători și defecte vizibile.", intro: "Fotografiile QC sunt ultimul control vizual înainte de expedierea internațională. Paginile USFans menționează mai multe fotografii HD de inspecție, dar valoarea lor depinde de ceea ce pot confirma în realitate.", points: ["Verifică întâi culoarea, eticheta mărimii și opțiunea aleasă.", "Compară părțile, cusăturile, imprimeul, accesoriile și defectele.", "Cere o fotografie cu măsurătoare când dimensiunile contează.", "O fotografie din depozit nu dovedește autenticitatea sau durabilitatea."], sections: [["Începe cu identitatea comenzii", "Confirmă că produsul, culoarea, mărimea și cantitatea corespund comenzii. O imagine clară nu ajută dacă arată varianta greșită."], ["Inspectează sistematic", "Treci de la forma generală la detalii: cusături, margini, tălpi, fermoare, logo-uri, pete, zgârieturi și ambalaj. Compară piesele simetrice."], ["Decide înainte de expirarea returului", "Documentează clar orice defect important și folosește serviciul post-vânzare înainte de expedierea internațională. După plecarea din depozit, corectarea devine mult mai dificilă."]] },
    "product-price-vs-parcel-cost": { title: "Prețul produsului și costul coletului", excerpt: "De ce prețul mic nu este costul final livrat.", intro: "Prețul din foaie descrie de obicei doar produsul. Totalul poate include livrare internă, servicii, ambalaj, greutate taxabilă, transport internațional și taxe la destinație.", points: ["Consideră prețul produsului un început, nu totalul livrat.", "Estimează greutatea reală și volumetrică înaintea unui colet mare.", "Compară rute cu aceeași destinație, greutate, dimensiuni și tip de produs.", "Separă vama și taxele locale de oferta de transport a agentului."], sections: [["Separă straturile de cost", "Notează separat produsul, livrarea internă, serviciile de depozit, ambalajul, transportul internațional și posibilele taxe la destinație."], ["Înțelege greutatea taxabilă", "Unele rute folosesc greutatea reală, altele o compară cu cea volumetrică. Un produs ușor, dar voluminos, poate costa mai mult decât sugerează cântarul."], ["Folosește estimările ca estimări", "USFans oferă un calculator de transport, însă datele finale ale coletului și rutele disponibile determină oferta reală. Păstrează o marjă în buget."]] },
    "first-time-spreadsheet-checklist": { title: "Checklist USFans Spreadsheet pentru începători", excerpt: "Un proces simplu pentru linkuri, variante, imagini și costuri.", intro: "O foaie bună ajută la descoperire, dar nu înlocuiește verificarea. Linkurile, stocul, variantele, imaginile și prețurile se pot schimba după adăugare.", points: ["Deschide pagina actuală, nu te baza pe o captură salvată.", "Potrivește numele și imaginea variantei înainte de plată.", "Salvează detaliile comenzii folosite la comparație.", "Tratează controlul QC și estimarea coletului ca decizii separate."], sections: [["Folosește foaia pentru descoperire", "Începe cu o categorie sau un cuvânt-cheie și deschide puțini candidați. Nu comanda doar după titlu sau miniatură."], ["Verifică oferta actuală", "Controlează prețul, variantele, vânzătorul, descrierea și orice avertisment sau restricție de pe pagina de detalii."], ["Planifică verificarea din depozit", "Stabilește dinainte ce vei verifica: măsurători, stare vizibilă, cantitate, accesorii și ambalaj. Controlul QC va fi mai rapid și coerent."]] }
  }
};

export function getArticles(locale: Locale): Record<ArticleSlug, LocalArticle> {
  if (locale === "en") return englishArticles;
  return articleTranslations[locale];
}

type IndexPage = Exclude<PageKind, "article">;

const pageSeo: Record<Locale, Record<IndexPage, { title: string; description: string }>> = {
  pl: {
    home: { title: "USFans Spreadsheet Polska 2026: Znaleziska, QC i Kategorie", description: "Przeglądaj USFans Spreadsheet Polska 2026: zweryfikowane znaleziska produktów, kategorie, zdjęcia QC i praktyczne poradniki zakupowe." },
    finds: { title: "USFans Znaleziska Produktów 2026", description: "Otwórz aktualne znaleziska USFans z pełnymi nazwami, kategoriami, cenami orientacyjnymi USD, zdjęciami oraz wskazówkami kontroli QC." },
    categories: { title: "Kategorie USFans Spreadsheet Polska", description: "Przeglądaj osobne kategorie USFans Spreadsheet: buty, bluzy, kurtki, koszulki, akcesoria, elektronika i inne zweryfikowane kolekcje." },
    guides: { title: "Poradniki USFans: QC, Koszty i Weryfikacja", description: "Praktyczne poradniki USFans o czytaniu zdjęć QC, sprawdzaniu wariantów, szacowaniu kosztu paczki i bezpiecznym wyborze oferty." },
    articles: { title: "Artykuły USFans Spreadsheet i QC", description: "Czytaj oparte na faktach artykuły USFans dotyczące pierwszego zamówienia, zdjęć QC, ceny produktu i kosztów wysyłki międzynarodowej." },
    faq: { title: "USFans FAQ: Produkty, QC i Wysyłka", description: "Odpowiedzi na najczęstsze pytania o katalog USFans, ceny orientacyjne, zdjęcia QC, dostawę krajową i wysyłkę międzynarodową." },
  },
  en: {
    home: { title: "USFans Spreadsheet 2026: Product Finds, QC Photos & Guides", description: "Explore USFans Spreadsheet 2026 product finds, verified category links, QC photo guidance, approximate USD prices, and practical buying guides." },
    finds: { title: "USFans Product Finds 2026", description: "Browse current USFans product finds with full names, categories, approximate USD prices, real product images, direct links, and focused QC checks." },
    categories: { title: "USFans Spreadsheet Product Categories", description: "Open focused USFans Spreadsheet categories for shoes, hoodies, jackets, T-shirts, accessories, jerseys, electronics, and more product finds." },
    guides: { title: "USFans Guides: QC Photos, Costs & Checks", description: "Use practical USFans guides to read QC photos, verify variants, understand parcel costs, and check current product listings before deciding." },
    articles: { title: "USFans Spreadsheet & QC Articles", description: "Read fact-checked USFans articles covering first-order research, warehouse QC photos, product prices, parcel costs, and shipping decisions." },
    faq: { title: "USFans FAQ: Products, QC & Shipping", description: "Find clear answers about the USFans product index, approximate prices, QC photos, domestic delivery, parcel submission, and international shipping." },
  },
  de: {
    home: { title: "USFans Spreadsheet 2026: Produkte, QC-Fotos & Ratgeber", description: "Entdecke USFans Spreadsheet 2026 mit Produktfunden, Kategorien, QC-Hinweisen, ungefähren USD-Preisen und praktischen Einkaufsratgebern." },
    finds: { title: "USFans Produktfunde 2026", description: "Aktuelle USFans Produktfunde mit vollständigen Namen, Kategorien, USD-Richtpreisen, echten Produktbildern, Direktlinks und konkreten QC-Prüfpunkten." },
    categories: { title: "USFans Spreadsheet Produktkategorien", description: "Öffne USFans Kategorien für Schuhe, Hoodies, Jacken, T-Shirts, Accessoires, Trikots, Elektronik und weitere geprüfte Produktsammlungen." },
    guides: { title: "USFans Ratgeber: QC, Kosten & Prüfung", description: "Praktische USFans Ratgeber zu QC-Fotos, Variantenprüfung, Paketkosten und der Kontrolle aktueller Produktangebote vor der Entscheidung." },
    articles: { title: "USFans Spreadsheet und QC Artikel", description: "Faktengeprüfte USFans Artikel über erste Bestellungen, Lager-QC, Produktpreise, Paketkosten und internationale Versandentscheidungen." },
    faq: { title: "USFans FAQ: Produkte, QC und Versand", description: "Klare Antworten zum USFans Produktindex, USD-Richtpreisen, QC-Fotos, Inlandsversand, Paketabgabe und internationalem Versand." },
  },
  fr: {
    home: { title: "USFans Spreadsheet 2026 : Produits, photos QC et guides", description: "Explorez USFans Spreadsheet 2026 avec trouvailles, catégories, conseils QC, prix USD indicatifs et guides d’achat pratiques." },
    finds: { title: "Sélection de produits USFans 2026", description: "Consultez les produits USFans avec noms complets, catégories, prix USD indicatifs, vraies images, liens directs et contrôles QC précis." },
    categories: { title: "Catégories de produits USFans Spreadsheet", description: "Ouvrez les catégories USFans pour chaussures, sweats, vestes, T-shirts, accessoires, maillots, électronique et autres sélections." },
    guides: { title: "Guides USFans : QC, coûts et vérification", description: "Guides pratiques USFans pour lire les photos QC, vérifier les variantes, estimer le colis et contrôler une offre avant de décider." },
    articles: { title: "Articles USFans Spreadsheet et QC", description: "Articles USFans vérifiés sur la première commande, les photos QC, le prix produit, le coût du colis et l’expédition internationale." },
    faq: { title: "FAQ USFans : produits, QC et expédition", description: "Réponses claires sur l’index USFans, les prix indicatifs, les photos QC, la livraison intérieure et l’expédition internationale." },
  },
  it: {
    home: { title: "USFans Spreadsheet 2026: Prodotti, foto QC e guide", description: "Esplora USFans Spreadsheet 2026 con prodotti, categorie, controlli QC, prezzi indicativi in USD e guide pratiche all’acquisto." },
    finds: { title: "Prodotti USFans 2026", description: "Scopri prodotti USFans con nomi completi, categorie, prezzi indicativi USD, immagini reali, link diretti e controlli QC specifici." },
    categories: { title: "Categorie prodotti USFans Spreadsheet", description: "Apri categorie USFans per scarpe, felpe, giacche, T-shirt, accessori, maglie, elettronica e altre raccolte di prodotti." },
    guides: { title: "Guide USFans: QC, costi e verifica", description: "Guide pratiche USFans per leggere foto QC, controllare varianti, stimare il costo del pacco e verificare l’inserzione attuale." },
    articles: { title: "Articoli USFans Spreadsheet e QC", description: "Articoli USFans verificati su primo ordine, foto QC, prezzi dei prodotti, costi del pacco e spedizione internazionale." },
    faq: { title: "FAQ USFans: prodotti, QC e spedizione", description: "Risposte chiare su catalogo USFans, prezzi indicativi, foto QC, consegna nazionale, invio del pacco e spedizione internazionale." },
  },
  es: {
    home: { title: "USFans Spreadsheet 2026: Productos, fotos QC y guías", description: "Explora USFans Spreadsheet 2026 con productos, categorías, consejos QC, precios aproximados en USD y guías de compra prácticas." },
    finds: { title: "Productos USFans 2026", description: "Consulta productos USFans con nombres completos, categorías, precios aproximados USD, imágenes reales, enlaces directos y controles QC concretos." },
    categories: { title: "Categorías de productos USFans Spreadsheet", description: "Abre categorías USFans de calzado, sudaderas, chaquetas, camisetas, accesorios, prendas deportivas, electrónica y otros productos." },
    guides: { title: "Guías USFans: QC, costes y verificación", description: "Guías prácticas USFans para leer fotos QC, revisar variantes, calcular costes del paquete y comprobar un anuncio antes de decidir." },
    articles: { title: "Artículos USFans Spreadsheet y QC", description: "Artículos USFans verificados sobre primer pedido, fotos QC, precio del producto, coste del paquete y envío internacional." },
    faq: { title: "FAQ USFans: productos, QC y envío", description: "Respuestas claras sobre el índice USFans, precios aproximados, fotos QC, entrega nacional, paquete y envío internacional." },
  },
  ro: {
    home: { title: "USFans Spreadsheet 2026: Produse, fotografii QC și ghiduri", description: "Explorează USFans Spreadsheet 2026 cu produse, categorii, verificări QC, prețuri USD orientative și ghiduri practice de cumpărare." },
    finds: { title: "Produse USFans 2026", description: "Vezi produse USFans cu denumiri complete, categorii, prețuri USD orientative, imagini reale, linkuri directe și verificări QC concrete." },
    categories: { title: "Categorii de produse USFans Spreadsheet", description: "Deschide categorii USFans pentru pantofi, hanorace, jachete, tricouri, accesorii, echipamente sportive, electronice și alte produse." },
    guides: { title: "Ghiduri USFans: QC, costuri și verificare", description: "Ghiduri practice USFans pentru fotografii QC, verificarea variantelor, estimarea coletului și controlul ofertei înainte de decizie." },
    articles: { title: "Articole USFans Spreadsheet și QC", description: "Articole USFans verificate despre prima comandă, fotografii QC, prețul produsului, costul coletului și transportul internațional." },
    faq: { title: "USFans FAQ: produse, QC și transport", description: "Răspunsuri clare despre catalogul USFans, prețuri orientative, fotografii QC, livrare internă, colet și transport internațional." },
  },
};

export function getPageSeo(locale: Locale, page: IndexPage) {
  return pageSeo[locale][page];
}

export function routeFor(locale: Locale, page: Exclude<PageKind, "article"> | "article", article?: ArticleSlug) {
  const prefix = locale === "pl" ? "" : `/${locale}`;
  if (page === "home") return prefix ? `${prefix}/` : "/";
  if (page === "article" && article) return `${prefix}/articles/${article}/`;
  return `${prefix}/${page}/`;
}

export function parseRoute(slug: string[]): { locale: Locale; page: PageKind; article?: ArticleSlug } | null {
  const segments = [...slug];
  let locale: Locale = "pl";
  if (segments[0] && locales.some((item) => item.code === segments[0])) locale = segments.shift() as Locale;
  if (segments.length === 0) return { locale, page: "home" };
  const section = segments[0] as PageKind;
  if (["finds", "categories", "guides", "articles", "faq"].includes(section) && segments.length === 1) return { locale, page: section };
  if (section === "articles" && segments.length === 2 && articleSlugs.includes(segments[1] as ArticleSlug)) return { locale, page: "article", article: segments[1] as ArticleSlug };
  return null;
}
