import type { ArticleCopy, Lang } from "./site-data";

export const spreadsheetFieldsArticle: Record<Lang, ArticleCopy> = {
  en: {
    title: "Superbuy Spreadsheet Fields: A Transparent Product Record",
    category: "Data Dictionary",
    excerpt: "A field-by-field framework for reading a Superbuy spreadsheet, spotting incomplete rows and separating recorded facts from editorial notes.",
    read: "12 min read",
    intro: "Superbuy spreadsheet fields determine whether an index is genuinely useful or merely a long list of links. A transparent product record should tell you what an editor observed, where that observation came from, and when it was last checked. It should also make missing information obvious. This guide treats each row as a small data record rather than a recommendation. It explains the minimum fields worth keeping, the difference between source facts and editorial labels, and a repeatable way to decide whether a row is complete enough to use. It does not replace the current destination listing or promise that a recorded price, option, image, or availability remains unchanged.",
    sections: [
      { heading: "Start with identity, not a persuasive label", paragraphs: ["The first job of a row is identification. A useful record needs a stable internal ID, a neutral product title, a category and the exact destination URL. The title should describe the object that the link currently presents, not the object an editor hoped to find. A row called “black zip hoodie” should not lead to a deposit page, replacement drawstring or unrelated colour. The internal ID matters because titles and URLs can change; it lets editors discuss the same record without relying on a fragile row number.", "Keep title and category separate. The title answers “what is this record?” while the category answers “where should it be browsed?” Categories should come from a controlled list, so “sneakers,” “trainers” and “shoes” do not create three accidental sections. A descriptive title can include a visible style or form, but it should avoid claims about authenticity, material or performance unless the source provides reliable evidence. Identification fields help retrieval; they are not endorsements."], bullets: ["Record ID", "Neutral product title", "Controlled category", "Exact destination URL", "Listing type", "Last-verified date"] },
      { heading: "Treat the destination URL as a typed field", paragraphs: ["A URL is not complete simply because it opens. The record should also label the destination type: full product, add-on, deposit, difference payment, replacement part or another clearly defined page. Similar images may appear across several link types, and a low displayed amount can belong to a deposit rather than the full item. Storing the type beside the link makes that ambiguity visible before anyone compares prices or options.", "Preserve the exact destination that was checked and avoid silently swapping a dead page for a loosely similar item. When a redirect occurs, record the final destination separately from the submitted URL. If the final page no longer matches the title, image and listing type, the right status is “needs review,” not “verified.” This turns URL checking into an auditable process and prevents a spreadsheet from appearing current just because every link returns an HTTP success code."], bullets: ["Full product", "Deposit", "Add-on", "Difference payment", "Replacement component", "Unknown—review required"] },
      { heading: "Separate source facts from editorial fields", paragraphs: ["Source fields reproduce what can be observed on the destination page at the time of review: displayed title, available option labels, visible price snapshot, seller identifier when shown, first image and any published measurements. Editorial fields are created by the index: normalized title, category, completeness status, risk note and verification date. Mixing the two makes it impossible to know whether a phrase came from the listing or from an editor’s interpretation.", "A simple convention solves the problem. Group raw source values separately from normalized values, and write notes as bounded observations. “Listing shows sizes M–XL on 14 August 2026” is traceable. “Fits true to size” is not supported without dependable measurement or fit evidence. “First image matches the black option” is a checkable relationship. “Best quality” is an undefined opinion. The Superbuy spreadsheet database becomes more trustworthy when it records the limits of each statement."] },
      { heading: "Record price as a dated snapshot", paragraphs: ["A price field needs context: amount, currency, the option to which it applies and the date checked. Marketplace pages may show a starting value, a range, a deposit or a price that changes with the selected variant. A single number without those qualifiers invites a false comparison. The spreadsheet should never convert a starting price into a claim about the full product or present an old snapshot as a live quote.", "Keep any converted currency in a separate estimated field with the exchange-rate date and a clear rounding rule. That value is useful for rough sorting, not checkout. Product cost is also not delivered cost: domestic delivery, payment handling, international shipping and destination charges sit outside a basic product-price field. A transparent row therefore makes the price snapshot searchable while directing the user to verify the current amount and selected option at the destination."] },
      { heading: "Make variants structured enough to compare", paragraphs: ["Do not squeeze every colour, size and style into one free-text cell. Use separate fields for option groups, then keep the source wording where it matters. A row can say that size information is present, absent or supplied only as labels; it should not imply that an XL from one seller equals an XL from another. Measurements, when published, belong in their own field with units and the referenced variant.", "Coverage is different from availability. “Recorded options: black and grey; sizes M–XL” describes the captured page. “Available now” is a volatile claim that should be checked at the destination. If the listing has too many combinations to represent accurately, use a coverage note such as “partial—open listing for full matrix.” This is better than truncating the list without warning. The goal is comparison while preserving uncertainty."] },
      { heading: "Use images as matching evidence", paragraphs: ["An image field should identify the first image used by the record and, when practical, retain a source-image reference for editorial audits. The important test is not whether an image looks attractive; it is whether the record title, selected listing type and destination page describe the same object. A product card showing a bag while the destination opens a strap-only option has failed even if both pages load correctly.", "Images can change independently of URLs. Record an image-match status such as matched, changed, missing or uncertain, plus the check date. Do not use an image to infer material, authenticity, included quantity or exact colour under real lighting. If the page contains several variants, note which visible option the saved image represents. This keeps the image useful for mismatch detection without asking it to prove qualities it cannot prove."] },
      { heading: "Add completeness and confidence without fake precision", paragraphs: ["Completeness answers whether required fields are present; confidence answers how strongly the fields agree. They are not the same. A row can be complete but conflicting—for example, it contains a title, image and URL, yet the image shows a different model. Another row can be incomplete but not misleading because it openly marks a missing size chart. Use named states rather than a decorative score whose formula readers cannot inspect.", "A practical completeness state is complete, usable with gaps, or hold for review. Confidence can be high when title, first image, listing type and destination agree; medium when a non-critical field is unclear; and low when identity signals conflict. Each label should have a written rule and an editor note explaining the exception. This makes prioritization possible without pretending that “92% confidence” has scientific meaning."], bullets: ["Complete: all required identity and audit fields present", "Usable with gaps: identity agrees but a secondary field is missing", "Hold: identity conflict, unknown link type or stale destination", "Never publish a numeric confidence score without a disclosed method"] },
      { heading: "Use a worked row audit", paragraphs: ["Imagine a row titled “navy zip hoodie.” It has record ID H-042, category Hoodies, a full-product destination, a first image that shows the same navy zip design, recorded options navy/grey and M–XL, a CNY price snapshot tied to the M option, and a last-verified date. The row also states that no measurement chart was found. That is not a perfect listing, but it is a transparent, usable record: identity signals agree and the missing fit evidence is visible.", "Now change one fact: the destination redirects to a generic add-on page. The record should move to hold even if the old title, image and price remain populated. Editors should not preserve a high-confidence label from the last audit or substitute a similar hoodie without recording a new identity. The recovery sequence is exact-link check, listing-type check, image/title comparison, variant review, then a fresh date. One conflict can outweigh many filled cells because identity is the foundation."] },
      { heading: "Apply a compact pre-use checklist", paragraphs: ["Before using a row, confirm that the title describes the current destination, the category uses the shared taxonomy, the URL type is known, the first image matches, the relevant variant is identified, and price or measurement values have dates and units. Then read the missing-field and confidence notes. This takes less time than resolving a wrong item after relying on an attractive but ambiguous card.", "For editors, the same checklist becomes a maintenance queue. Recheck holds first, then records with missing identity fields, then rows whose verification dates are oldest. Keep every change attributable through an internal ID and short note. A well-designed Superbuy spreadsheet index does not promise that every row is permanently correct. It shows exactly what was checked, what remains uncertain and where the current destination must make the final decision."], bullets: ["Identity fields agree", "Link type is explicit", "Price and measurements include context", "Variant coverage is not overstated", "Image match has a date", "Gaps and confidence are visible"] },
    ],
  },
  fr: {
    title: "Champs d’un tableau Superbuy : une fiche produit transparente", category: "Dictionnaire de données", excerpt: "Un cadre champ par champ pour lire un tableau Superbuy, repérer les lignes incomplètes et distinguer faits sources et notes éditoriales.", read: "12 min de lecture", intro: "Les champs d’un tableau Superbuy déterminent si l’index est réellement utile ou s’il ne s’agit que d’une liste de liens. Une fiche transparente indique ce qui a été observé, d’où vient l’information et quand elle a été vérifiée. Elle rend aussi les données manquantes visibles. Ce guide considère chaque ligne comme une petite fiche de données, pas comme une recommandation. Il présente les champs minimaux, sépare faits sources et libellés éditoriaux, et propose une méthode pour décider si une ligne est exploitable. La fiche de destination actuelle reste toujours la référence.", sections: [
      { heading: "Commencer par l’identité, pas par une formule vendeuse", paragraphs: ["Une ligne doit d’abord identifier : ID interne stable, titre neutre, catégorie et URL exacte. Le titre décrit l’objet présenté aujourd’hui, non celui que l’éditeur espérait trouver. L’ID permet de suivre la même fiche lorsque titre ou URL changent.", "Séparez titre et catégorie. Le titre répond à « quel objet ? », la catégorie à « où le classer ? ». Utilisez une taxonomie contrôlée et évitez les affirmations d’authenticité, de matière ou de performance sans preuve fiable."], bullets: ["ID de fiche", "Titre neutre", "Catégorie contrôlée", "URL exacte", "Type d’annonce", "Date de vérification"] },
      { heading: "Traiter l’URL comme un champ typé", paragraphs: ["Une URL ouverte ne suffit pas. Indiquez si elle mène au produit complet, à un ajout, un acompte, un complément de paiement ou une pièce. Des images proches et un faible montant peuvent masquer un type différent.", "Conservez l’URL contrôlée et le résultat final d’une redirection. Si titre, image et type ne correspondent plus, passez la ligne à « à revoir » plutôt que de la déclarer vérifiée sur le seul code HTTP."], bullets: ["Produit complet", "Acompte", "Ajout", "Complément de paiement", "Pièce de remplacement", "Inconnu — contrôle requis"] },
      { heading: "Séparer faits sources et champs éditoriaux", paragraphs: ["Les champs sources reprennent les éléments observables : titre affiché, options, instantané de prix, vendeur visible, première image et mesures publiées. Les champs éditoriaux ajoutent titre normalisé, catégorie, état, risque et date.", "« Tailles M–XL affichées le 14 août 2026 » est traçable ; « taille normalement » ne l’est pas sans mesures fiables. « L’image correspond à l’option noire » est vérifiable ; « meilleure qualité » ne définit rien."] },
      { heading: "Enregistrer le prix comme instantané daté", paragraphs: ["Le prix doit préciser montant, devise, option et date. Une page peut montrer prix de départ, plage, acompte ou variation par option. Un nombre isolé produit une fausse comparaison.", "Placez toute conversion dans un champ estimatif séparé avec date de change et règle d’arrondi. Elle sert au tri, pas au paiement, et ne représente jamais le coût livré complet."] },
      { heading: "Structurer les variantes pour comparer", paragraphs: ["Séparez couleur, taille et style au lieu de tout placer dans une cellule libre. Conservez les mots sources et distinguez présence d’une taille, simple étiquette ou mesure publiée avec unité.", "La couverture n’est pas la disponibilité. Si la matrice est trop vaste, indiquez « partielle — ouvrir la fiche ». Le tableau aide à rechercher sans prétendre que toutes les options capturées sont encore disponibles."] },
      { heading: "Utiliser les images comme preuve de correspondance", paragraphs: ["Le champ image doit identifier la première image contrôlée. Le test porte sur l’accord entre titre, type de lien et destination, pas sur l’esthétique. Un sac menant à une sangle seule échoue.", "Marquez l’image comme correspondante, modifiée, absente ou incertaine, avec une date. Elle ne prouve ni matière, authenticité, quantité incluse ni couleur exacte sous lumière réelle."] },
      { heading: "Ajouter complétude et confiance sans fausse précision", paragraphs: ["La complétude mesure la présence des champs ; la confiance mesure leur accord. Une fiche complète peut être contradictoire, et une fiche incomplète peut rester honnête si le manque est visible.", "Employez complet, exploitable avec lacunes ou en attente. La confiance est élevée si titre, image, type et URL concordent ; moyenne pour un doute secondaire ; faible en cas de conflit d’identité."], bullets: ["Complet : identité et audit présents", "Exploitable : identité cohérente, donnée secondaire absente", "En attente : conflit, type inconnu ou destination périmée", "Pas de score numérique sans méthode publiée"] },
      { heading: "Appliquer un exemple d’audit", paragraphs: ["Une fiche « sweat zippé marine » avec ID, catégorie, produit complet, image concordante, options, prix CNY daté et date de contrôle est exploitable même si elle signale l’absence de tableau de mesures.", "Si l’URL redirige ensuite vers un ajout générique, la fiche passe en attente malgré ses cellules remplies. Contrôlez URL exacte, type, titre/image, variantes puis datez de nouveau."] },
      { heading: "Finir par une courte checklist", paragraphs: ["Avant usage, contrôlez titre, taxonomie, type de lien, image, variante et contexte des prix ou mesures. Lisez ensuite les lacunes et la confiance.", "Pour la maintenance, traitez d’abord les attentes, puis les identités incomplètes et les dates les plus anciennes. Un bon index montre ce qui a été contrôlé, ce qui reste incertain et où vérifier la décision finale."], bullets: ["Identité cohérente", "Type explicite", "Prix et mesures contextualisés", "Couverture non exagérée", "Image datée", "Lacunes visibles"] },
    ] },
  de: {
    title: "Superbuy-Spreadsheet-Felder: ein transparenter Produktdatensatz", category: "Datenwörterbuch", excerpt: "Ein Feld-für-Feld-Modell zum Lesen einer Superbuy-Tabelle, Erkennen unvollständiger Zeilen und Trennen von Quellenfakten und Redaktion.", read: "12 Min. Lesezeit", intro: "Die Felder eines Superbuy-Spreadsheets entscheiden, ob ein Index nützlich oder nur eine Linkliste ist. Ein transparenter Datensatz zeigt Beobachtung, Herkunft und Prüfdatum und macht fehlende Werte sichtbar. Dieser Leitfaden behandelt jede Zeile als Datensatz statt Empfehlung. Er erklärt Mindestfelder, die Trennung von Quellenwerten und redaktionellen Labels sowie eine wiederholbare Vollständigkeitsprüfung. Die aktuelle Zielseite bleibt die entscheidende Referenz.", sections: [
      { heading: "Mit Identität statt Werbesprache beginnen", paragraphs: ["Jede Zeile braucht stabile interne ID, neutralen Titel, Kategorie und exakte Ziel-URL. Der Titel beschreibt das aktuell sichtbare Objekt. Die ID hält den Datensatz auffindbar, wenn Titel oder Link wechseln.", "Titel und Kategorie bleiben getrennt. Eine kontrollierte Taxonomie verhindert zufällige Doppelgruppen. Aussagen zu Echtheit, Material oder Leistung gehören nur hinein, wenn belastbare Quellen sie stützen."], bullets: ["Datensatz-ID", "Neutraler Titel", "Kontrollierte Kategorie", "Exakte Ziel-URL", "Angebotstyp", "Prüfdatum"] },
      { heading: "Die Ziel-URL als typisiertes Feld behandeln", paragraphs: ["Ein öffnender Link reicht nicht. Kennzeichne Vollprodukt, Zusatz, Anzahlung, Differenzzahlung oder Ersatzteil. Ähnliche Bilder und kleine Beträge können einen anderen Angebotstyp verdecken.", "Speichere geprüfte und endgültige Redirect-Adresse. Stimmen Titel, Bild und Typ nicht mehr überein, lautet der Status „prüfen“ statt „verifiziert“, auch bei erfolgreichem HTTP-Aufruf."], bullets: ["Vollprodukt", "Anzahlung", "Zusatz", "Differenzzahlung", "Ersatzteil", "Unbekannt — Prüfung nötig"] },
      { heading: "Quellenfakten von Redaktionsfeldern trennen", paragraphs: ["Quellenfelder erfassen sichtbaren Titel, Optionen, Preis-Snapshot, Verkäuferkennung, erstes Bild und veröffentlichte Maße. Redaktionelle Felder enthalten normalisierten Titel, Kategorie, Vollständigkeit, Risiko und Datum.", "„Größen M–XL am 14. August 2026 angezeigt“ ist nachvollziehbar; „fällt normal aus“ nicht ohne Messbeleg. Bildabgleich ist prüfbar, „beste Qualität“ nicht definiert."] },
      { heading: "Preise als datierte Snapshots führen", paragraphs: ["Preisfelder benötigen Betrag, Währung, betroffene Option und Datum. Startwert, Spanne, Anzahlung und Variantenpreis dürfen nicht zu einer einzigen scheinbar aktuellen Zahl verschmelzen.", "Umrechnungen gehören mit Kursdatum und Rundungsregel in ein eigenes Schätzfeld. Sie dienen grobem Sortieren, nicht Checkout oder Aussage über vollständige Lieferkosten."] },
      { heading: "Varianten vergleichbar strukturieren", paragraphs: ["Farbe, Größe und Stil sollten getrennte Felder erhalten. Quellenbegriffe bleiben erhalten; Größenetikett, vorhandene Tabelle und Messwert mit Einheit sind unterschiedliche Evidenz.", "Erfasste Abdeckung ist keine aktuelle Verfügbarkeit. Bei zu großer Matrix kennzeichnet „teilweise — Angebot öffnen“ die Grenze besser als eine unbemerkte Kürzung."] },
      { heading: "Bilder als Zuordnungsbeleg verwenden", paragraphs: ["Das Bildfeld identifiziert das geprüfte erste Bild. Entscheidend ist die Übereinstimmung von Titel, Linktyp und Zielobjekt. Eine Tasche, die nur zu einem Riemen führt, besteht den Test nicht.", "Status kann passend, geändert, fehlend oder unklar sein und braucht ein Datum. Das Bild beweist weder Material, Echtheit, Stückzahl noch exakte Farbe bei Tageslicht."] },
      { heading: "Vollständigkeit und Vertrauen ohne Scheingenauigkeit", paragraphs: ["Vollständigkeit fragt, ob Pflichtfelder existieren; Vertrauen fragt, ob sie zusammenpassen. Ein vollständiger Datensatz kann widersprüchlich, ein lückenhafter offen und ehrlich sein.", "Nutze vollständig, nutzbar mit Lücken oder zurückhalten. Hohes Vertrauen verlangt Übereinstimmung von Titel, Bild, Typ und Ziel; Identitätskonflikte bedeuten niedrig."], bullets: ["Vollständig: Identität und Audit vorhanden", "Nutzbar: Identität stimmt, Nebenfeld fehlt", "Zurückhalten: Konflikt, unbekannter Typ oder altes Ziel", "Kein Zahlenwert ohne offengelegte Methode"] },
      { heading: "Ein Zeilenaudit durchspielen", paragraphs: ["Ein Datensatz „navy Zip-Hoodie“ mit ID, Kategorie, Vollprodukt, passendem Bild, Optionen, datiertem CNY-Preis und fehlender Maßtabelle ist transparent nutzbar.", "Leitet die URL später auf ein allgemeines Zusatzangebot, wird er zurückgehalten. Danach folgen Link-, Typ-, Bild/Titel- und Variantenprüfung sowie ein neues Datum."] },
      { heading: "Mit einer kurzen Checkliste abschließen", paragraphs: ["Vor Nutzung prüfe Titel, Taxonomie, Linktyp, Bild, Variante sowie Kontext von Preisen und Maßen. Lies anschließend Lücken- und Vertrauensnotizen.", "Bei der Pflege kommen zurückgehaltene, identitätsarme und älteste Datensätze zuerst. Ein guter Index zeigt Prüfung, Unsicherheit und den Ort der finalen aktuellen Entscheidung."], bullets: ["Identität stimmt", "Linktyp eindeutig", "Preis und Maße mit Kontext", "Abdeckung nicht übertrieben", "Bildprüfung datiert", "Lücken sichtbar"] },
    ] },
  id: {
    title: "Field Superbuy Spreadsheet: Catatan Produk yang Transparan", category: "Kamus Data", excerpt: "Kerangka per field untuk membaca spreadsheet Superbuy, menemukan baris yang kurang lengkap, dan memisahkan fakta sumber dari catatan editor.", read: "12 menit", intro: "Field dalam Superbuy spreadsheet menentukan apakah indeks benar-benar berguna atau hanya daftar tautan. Catatan transparan menjelaskan apa yang diamati, sumbernya, dan tanggal pemeriksaan, sekaligus menampilkan data yang hilang. Panduan ini memperlakukan setiap baris sebagai catatan data, bukan rekomendasi. Isinya menjelaskan field minimum, pemisahan nilai sumber dan label editor, serta cara berulang untuk menilai kelengkapan. Halaman tujuan terkini tetap menjadi rujukan akhir.", sections: [
      { heading: "Mulai dari identitas, bukan kata promosi", paragraphs: ["Baris membutuhkan ID internal stabil, judul netral, kategori, dan URL tujuan yang tepat. Judul harus menggambarkan objek yang tampil sekarang. ID menjaga identitas saat judul atau URL berubah.", "Pisahkan judul dan kategori serta gunakan taksonomi terkontrol. Jangan menyatakan keaslian, bahan, atau kinerja tanpa bukti sumber yang dapat diandalkan."], bullets: ["ID catatan", "Judul netral", "Kategori terkontrol", "URL tepat", "Jenis listing", "Tanggal verifikasi"] },
      { heading: "Perlakukan URL sebagai field bertipe", paragraphs: ["Tautan yang terbuka belum cukup. Tandai produk penuh, add-on, deposit, pembayaran selisih, atau komponen pengganti. Gambar serupa dan harga rendah dapat menyembunyikan jenis berbeda.", "Simpan URL yang diperiksa dan tujuan akhir redirect. Jika judul, gambar, dan jenis tidak lagi cocok, ubah status menjadi perlu ditinjau meskipun HTTP berhasil."], bullets: ["Produk penuh", "Deposit", "Add-on", "Pembayaran selisih", "Komponen pengganti", "Tidak diketahui — perlu tinjau"] },
      { heading: "Pisahkan fakta sumber dan field editorial", paragraphs: ["Field sumber memuat judul tampilan, opsi, snapshot harga, identitas penjual, gambar pertama, dan ukuran yang diterbitkan. Field editorial memuat judul normal, kategori, kelengkapan, risiko, dan tanggal.", "“Ukuran M–XL tampil pada 14 Agustus 2026” dapat dilacak; “ukurannya normal” tidak tanpa pengukuran. Kecocokan gambar dapat diuji; “kualitas terbaik” tidak terdefinisi."] },
      { heading: "Catat harga sebagai snapshot bertanggal", paragraphs: ["Harga perlu nilai, mata uang, opsi, dan tanggal. Harga awal, rentang, deposit, dan harga varian tidak boleh disederhanakan menjadi satu angka seolah tetap berlaku.", "Konversi mata uang harus menjadi estimasi terpisah dengan tanggal kurs dan aturan pembulatan. Gunakan untuk penyortiran kasar, bukan checkout atau total biaya sampai tujuan."] },
      { heading: "Buat varian cukup terstruktur untuk dibandingkan", paragraphs: ["Pisahkan warna, ukuran, dan gaya. Pertahankan istilah sumber dan bedakan label ukuran, tabel, serta pengukuran bersatuan.", "Cakupan tercatat bukan ketersediaan langsung. Untuk matriks besar, tulis “sebagian — buka listing” agar pemotongan data tidak tersembunyi."] },
      { heading: "Gunakan gambar sebagai bukti kecocokan", paragraphs: ["Field gambar mengidentifikasi gambar pertama yang diperiksa. Uji kecocokan judul, jenis tautan, dan objek tujuan, bukan daya tarik visual. Gambar tas yang menuju strap saja gagal.", "Status gambar dapat cocok, berubah, hilang, atau tidak pasti, disertai tanggal. Gambar tidak membuktikan bahan, keaslian, jumlah, atau warna tepat di cahaya nyata."] },
      { heading: "Tambahkan kelengkapan dan keyakinan tanpa presisi palsu", paragraphs: ["Kelengkapan menilai apakah field wajib ada; keyakinan menilai apakah semuanya konsisten. Catatan lengkap bisa konflik, sedangkan catatan kurang lengkap dapat tetap jujur.", "Gunakan lengkap, dapat dipakai dengan celah, atau tahan untuk tinjau. Keyakinan tinggi memerlukan judul, gambar, jenis, dan tujuan yang cocok; konflik identitas berarti rendah."], bullets: ["Lengkap: identitas dan audit tersedia", "Dapat dipakai: identitas cocok, field sekunder hilang", "Tahan: konflik, jenis tidak diketahui, atau tujuan usang", "Tanpa skor angka jika metode tidak dibuka"] },
      { heading: "Jalankan contoh audit baris", paragraphs: ["Catatan “hoodie zip navy” dengan ID, kategori, produk penuh, gambar cocok, opsi, harga CNY bertanggal, dan catatan tanpa tabel ukuran masih transparan dan dapat dipakai.", "Jika URL kemudian menuju halaman add-on umum, tahan catatan walau sel lain terisi. Periksa tautan, jenis, gambar/judul, varian, lalu beri tanggal baru."] },
      { heading: "Gunakan checklist singkat sebelum dipakai", paragraphs: ["Periksa judul, taksonomi, jenis link, gambar, varian, serta konteks harga dan ukuran. Setelah itu baca catatan celah dan keyakinan.", "Untuk pemeliharaan, dahulukan catatan ditahan, identitas yang hilang, lalu tanggal tertua. Indeks yang baik memperlihatkan apa yang diperiksa, apa yang belum pasti, dan tempat keputusan terkini dibuat."], bullets: ["Identitas konsisten", "Jenis link jelas", "Harga dan ukuran berkonteks", "Cakupan tidak dibesar-besarkan", "Gambar bertanggal", "Celah terlihat"] },
    ] },
  "zh-cn": {
    title: "Superbuy Spreadsheet 字段指南：透明的商品数据记录", category: "数据字段说明", excerpt: "逐字段理解 Superbuy Spreadsheet，识别信息不完整的行，并区分来源事实与编辑备注。", read: "阅读 12 分钟", intro: "Superbuy Spreadsheet 的字段决定一个索引是真正有用，还是仅仅堆放了很多链接。透明的商品记录应该说明编辑看到了什么、信息来自哪里、何时完成核验，也应明确显示缺失项。本指南把每一行当作一条数据记录，而不是商品推荐，说明值得保留的最小字段、来源事实与编辑标签的区别，以及判断一行是否足以使用的可重复方法。实时目标页仍是价格、选项和可用性的最终依据。", sections: [
      { heading: "从商品身份开始，而不是营销名称", paragraphs: ["每行首先需要稳定的内部 ID、中性标题、分类和准确目标网址。标题应描述目标页现在展示的对象，而不是编辑希望找到的对象。即使标题或网址变化，内部 ID 仍能指向同一记录。", "标题回答“这是什么”，分类回答“应该在哪里浏览”。分类应使用受控词表，避免同类商品被拆成多个偶然分组。没有可靠来源时，不应声称真伪、材质或性能。"], bullets: ["记录 ID", "中性商品标题", "受控分类", "准确目标网址", "Listing 类型", "最后核验日期"] },
      { heading: "把目标网址作为有类型的字段", paragraphs: ["网址能够打开并不等于记录完整，还应标注完整商品、附加项、定金、补差价或替换配件等类型。相似图片和很低的显示金额可能对应不同类型。", "保存实际核验的网址和跳转后的最终地址。标题、图片与类型不再一致时，应改为“需要复核”，不能只因返回成功状态就继续标记已核验。"], bullets: ["完整商品", "定金", "附加项", "补差价", "替换配件", "未知——需要复核"] },
      { heading: "区分来源事实与编辑字段", paragraphs: ["来源字段记录可观察信息：页面标题、规格、价格快照、可见卖家标识、首图和公开尺寸。编辑字段包括规范标题、分类、完整度、风险备注和核验日期。", "“2026 年 8 月 14 日显示 M–XL”可以追溯；没有可靠尺寸时，“尺码标准”不能追溯。“首图对应黑色选项”可核对，“最佳质量”则没有明确标准。"] },
      { heading: "把价格记录为带日期的快照", paragraphs: ["价格字段要同时包含金额、币种、对应规格和日期。页面可能显示起售价、区间、定金或随规格变化的价格，孤立数字会造成错误比较。", "换算币种应使用独立估算字段，并写明汇率日期与舍入规则。它只能用于粗略筛选，不代表结账金额，更不代表包含境内外运输的到手总成本。"] },
      { heading: "让规格字段足以支持比较", paragraphs: ["颜色、尺码和款式应分别记录，不要全部塞进自由文本。保留来源用词，并区分只有尺码标签、存在尺码表和存在带单位测量值这三种证据。", "已记录范围不等于实时有货。规格组合太多时，标记“部分——打开详情页查看完整组合”比无提示截断更透明。"] },
      { heading: "把图片用作匹配证据", paragraphs: ["图片字段应标识核验过的首图。重点不是图片是否吸引人，而是标题、链接类型和目标对象是否一致。商品卡显示包袋但只打开肩带选项，就未通过匹配。", "图片状态可分为匹配、已变化、缺失或不确定，并附日期。图片不能证明材质、真伪、包含数量或真实光线下的准确颜色。"] },
      { heading: "用完整度和置信状态避免虚假精确", paragraphs: ["完整度回答必填字段是否存在；置信状态回答字段是否相互一致。字段齐全的记录仍可能冲突，缺少次要信息的记录也可以诚实可用。", "可使用完整、有缺口但可用、暂停复核三种状态。标题、首图、类型与目标一致时置信较高；次要项不清楚时为中等；身份信号冲突时为低。"], bullets: ["完整：身份和审计字段齐全", "可用：身份一致但缺少次要字段", "暂停：身份冲突、类型未知或地址过期", "没有公开方法就不要给数字置信分"] },
      { heading: "用一条记录演示审计", paragraphs: ["一行“海军蓝拉链卫衣”具有 ID、分类、完整商品地址、匹配首图、规格、带日期的人民币价格，并明确说明未找到尺码表。它不完美，但透明且可用。", "如果该地址之后跳到通用附加项页面，即使旧字段都已填写，也应暂停。恢复顺序是检查准确链接、类型、标题与图片、规格，再写入新的日期。"] },
      { heading: "使用前执行简短清单", paragraphs: ["使用一行前，核对标题、分类词表、链接类型、首图、相关规格，以及价格和尺寸的上下文，再阅读缺失项与置信备注。", "维护时先处理暂停项，再处理身份字段缺失项，最后按最旧日期排序。好的 Superbuy Spreadsheet 索引不会承诺永久正确，而会清楚展示已核验内容、仍不确定内容和最终实时核对位置。"], bullets: ["身份字段一致", "链接类型明确", "价格和尺寸有上下文", "没有夸大规格覆盖", "图片核验有日期", "缺失项清晰可见"] },
    ] },
};
