import type { Metadata } from "next";
import { InnerHero, SiteChrome } from "../site-chrome";
export const metadata:Metadata={title:"Hipobuy Shipping Cost 2026: Price per KG & Calculator",description:"Calculate Hipobuy shipping cost from weight, parcel dimensions and live routes, with 2026 guides for the UK, France, Germany and Netherlands.",alternates:{canonical:"/shipping/"},openGraph:{title:"Hipobuy Shipping Cost 2026: Price per KG & Calculator",description:"Use chargeable weight and live route data instead of a made-up flat rate.",url:"/shipping/",images:["/og.png"]}};
const countryGuides=[
  ["NETHERLANDS","Cost, VAT and parcel planning","/articles/hipobuy-shipping-netherlands/"],
  ["UNITED KINGDOM","Cost, VAT, routes and the £135 question","/articles/hipobuy-shipping-uk/"],
  ["FRANCE","Price per KG, calculator and customs","/articles/hipobuy-shipping-france/"],
  ["GERMANY & EU","Cost, VAT and 2026 route checks","/articles/hipobuy-shipping-germany-eu/"],
];
export default function ShippingPage(){return <SiteChrome><main className="inner-main"><InnerHero eyebrow="Hipobuy shipping calculator · 2026" title="Calculate shipping cost from the parcel—not a guessed price per KG." intro="Hipobuy shipping cost depends on destination, route, packed dimensions, actual weight and contents. Use this method to turn an early estimate into a realistic delivered-cost range."/><section className="formula-card"><span>CHARGEABLE WEIGHT</span><h2>Actual weight <i>vs</i> volumetric weight</h2><p>Some routes charge the larger of the parcel’s measured weight and a dimensional calculation. The divisor and rounding method can vary, so use the live estimator for the selected route rather than copying a rate from another parcel.</p></section><section className="shipping-grid"><article><span>01</span><h2>Item subtotal</h2><p>Record the current listing price, selected variant and any domestic delivery to the warehouse.</p></article><article><span>02</span><h2>Parcel build</h2><p>Estimate consolidated contents, protective packing and whether boxes materially increase dimensions.</p></article><article><span>03</span><h2>Route eligibility</h2><p>Filter for destination, item type and restrictions before comparing speed or headline price.</p></article><article><span>04</span><h2>Final quote</h2><p>Use measured warehouse data and the live quote. Treat earlier values only as planning references.</p></article></section><section className="shipping-warning"><strong>Do not promise delivery dates from an estimate.</strong><p>Processing, carrier handoff, customs and last-mile delivery are separate stages. Keep the tracking record and allow for route-specific uncertainty.</p></section><section className="guide-section shipping-guides"><div className="section-kicker">COUNTRY GUIDES</div><div className="section-heading compact"><h2>Use the destination-specific checklist.</h2><p>Tax, handling and last-mile details differ. Each guide keeps freight, VAT and customs questions separate.</p></div><div className="guide-grid">{countryGuides.map((guide,index)=><article key={guide[0]}><div><span>{guide[0]}</span><small>{String(index+1).padStart(2,"0")}</small></div><h3>{guide[1]}</h3><p>Build the estimate with current parcel data and official destination guidance.</p><a href={guide[2]}>Read country guide <b>→</b></a></article>)}</div></section></main></SiteChrome>}
