import type { ArticleSlug, Lang } from "./site-data";

type LocalizedLang = Exclude<Lang, "en">;
type LegacySlug = Exclude<ArticleSlug, "hipobuy-review-2026">;

export const localizedParityDetails: Record<LocalizedLang, Record<LegacySlug, string[]>> = {
  de: {
    "how-to-buy-with-hipobuy": [
      "Der Google-Play-Eintrag beschreibt Käufe über chinesische Marktplätze wie Taobao und 1688, professionelle Käufer rund um die Uhr, 90 Tage kostenlose Lagerung, mehr als 200 Zielländer, zahlreiche Versandoptionen und eine Lieferung im günstigsten Fall ab fünf Tagen. Diese Angaben erklären den beworbenen Ablauf, sind aber keine Zusage für einen bestimmten Artikel, eine Adresse oder einen Termin. Auch die auf der öffentlichen Landingpage gezeigten Zahlungsmarken PayPal, Klarna, Visa, Mastercard und JCB müssen im eigenen Checkout geprüft werden. Speichere deshalb den Endbetrag nach Währungsumrechnung, die angebotene Zahlungsart und die für dein Konto sichtbaren Bedingungen.",
      "Ein belastbares Budget besteht aus drei getrennten Bereichen: dem bestätigten Warenwert, einer Arbeitsschätzung für Inlandsversand und mögliche Service- oder Zahlungskosten sowie einer Bandbreite für den internationalen Versand. Vor der Vermessung im Lager ist eine Spanne ehrlicher als ein scheinbar exakter Rechnerwert. Modellieren solltest du mindestens ein kompaktes und ein voluminöses Paket. Öffentliche Rezensionen loben teilweise den einfachen Ablauf und die QC-Bilder, andere Nutzer berichten von später als erwartet sichtbaren Versandkosten oder unklaren Erstattungen. Diese Einzelerfahrungen beweisen keine allgemeine Quote, zeigen aber, warum Produktzahlung und Paketfreigabe zwei getrennte Entscheidungen bleiben müssen.",
      "Der erste Auftrag sollte nicht die maximale Ersparnis, sondern den gesamten Ablauf testen. Wähle einen überschaubaren Artikel mit eindeutig erkennbarer Variante, messbaren Merkmalen und einem Wert, bei dem eine Verzögerung kein finanzielles Problem verursacht. Notiere Bestelldatum, Verkäufer-Versand, Lagereingang, Bereitstellung verwertbarer QC-Fotos, Rückfrage und Paketangebot. Prüfe danach, welche Erwartung falsch war: Lieferte der Verkäufer später, fehlte eine Messung, änderte sich die Kartongröße oder war eine Gebühr erst in einem späteren Schritt sichtbar? Daraus entstehen konkrete Regeln für die nächste Bestellung, etwa ein Kostenlimit, eine maximale Zahl offener Artikel und ein spätester Konsolidierungstermin.",
      "Vor der internationalen Zahlung gehören Route, Inhaltserklärung, Abrechnungsgewicht, Außenmaße, Verpackungsleistungen, Zieladresse und Gesamtbetrag in einen einzigen gespeicherten Datensatz. Falls Schutz oder Entschädigung angeboten wird, lies die gedeckten Ereignisse und erforderlichen Nachweise statt nur das Produktlabel. Beim Tracking sind Ausnahmen wichtiger als bloße Bewegungen: Zollrückfrage, fehlende Information oder gescheiterter Zustellversuch verlangen jeweils eine andere Reaktion. Fotografiere ein sichtbar beschädigtes Außenpaket vor dem Öffnen mit lesbarem Label und vergleiche den Inhalt anschließend mit dem QC-Protokoll. Auch problemlose Sendungen sollten mit Gewicht, Laufzeit und Gesamtkosten dokumentiert werden, weil eigene vergleichbare Daten für die nächste Planung aussagekräftiger sind als fremde Extremfälle.",
    ],
    "hipobuy-shipping-cost-guide": [
      "Öffentliche Bewertungen eignen sich dazu, Unsicherheiten zu finden, nicht dazu, einen Preis zu kopieren. Positive Beiträge nennen mitunter akzeptable Laufzeiten, intakte Verpackung oder hilfreiches Tracking; kritische Beiträge beschreiben hohe oder erst nach Lagereingang verständliche internationale Kosten. Länder, Postleitzahlen, Paketformen, Routen, Aktionen und Erwartungen unterscheiden sich jedoch. Ein Satz wie „vier Kilogramm kosteten X“ lässt meist Außenmaße, Volumengewicht, eingeschränkte Inhalte, Schutz, Umrechnung und Angebotsdatum weg. Formuliere daraus Prüffragen für dein eigenes Paket: Wurde Volumen berechnet, blieben Verkaufskartons erhalten, welche Linie war zulässig und welcher Betrag war vor Zahlung tatsächlich bestätigt?",
      "Sobald das Lager Gewicht und Maße zeigt, muss die frühe Schätzung vollständig neu aufgebaut werden. Kläre, ob die Anzeige Waagengewicht, berechnetes Volumengewicht oder bereits gerundetes Abrechnungsgewicht bedeutet, und ob Ziel sowie Produktbeschränkungen zur geplanten Route passen. Eine Abweichung ist nicht automatisch ein Fehler: Schutzmaterial, Verkäuferkartons, eine besonders lange Seite oder eine Tarifstufe können den Betrag verändern. Wenn die Rechnung nicht nachvollziehbar ist, stelle jeweils eine konkrete Frage nach den gespeicherten Außenmaßen, einer optionalen Verpackungsleistung oder der verwendeten Gewichtsregel. Eine genaue Anfrage liefert einen überprüfbaren Sachverhalt; „Versand ist zu teuer“ liefert dem Support keine belastbare Ursache.",
      "Vergleiche mindestens zwei vollständige Szenarien mit demselben Warenkorb und Ziel. Eine Variante kann Verkaufskartons und stärkeren Schutz behalten, eine andere unnötige Hohlräume entfernen, einen kleineren Außenkarton verwenden oder das Paket teilen. In jede Variante gehören Verpackungsentgelt, mögliche Absicherung, Zahlungsumrechnung, geschätzte Zielkosten und die tatsächliche Routenberechtigung. Ein Gutschein zählt erst, wenn Bedingungen, Ablaufdatum und zulässige Linie feststehen. Entscheidend ist der kontrollierbare Gesamtwert, nicht die niedrigste Schlagzeile: Eine kleine Ersparnis lohnt sich nicht, wenn die Linie den Inhalt ablehnt, Tracking zu schwach ist oder ein strukturierter Artikel seinen notwendigen Schutz verliert.",
      "Nach der Zustellung berechnest du die Gesamtkosten aus Ware, Inlandsfracht, Service oder Transaktion, internationalem Versand und tatsächlich angefallenen Zielgebühren. Verteile Versand nicht automatisch nach Warenpreis, denn ein günstiger voluminöser Artikel kann mehr Paketkapazität verbrauchen als ein kompakter teurer. Speichere Datum, Route, Ziel, Außenmaße, Waagen- und Abrechnungsgewicht, Verpackungswahl, Laufzeit sowie Endsumme. Nach mehreren vergleichbaren Bestellungen entsteht daraus ein persönlicher Referenzbereich. Er bleibt gegenüber Routenänderungen unsicher, ist aber wesentlich nützlicher als fremde Screenshots. Überschreitet der reale Gesamtwert wiederholt dein Vorablimit, muss sich Produktmix oder Paketstrategie ändern – nicht nur der nächste Rabattcode.",
    ],
    "hipobuy-warehouse-qc-photos": [
      "Ein Lagerfoto zeigt einen Artikel zu einem Zeitpunkt, unter einer Beleuchtung und aus wenigen Winkeln. Es kann Farbeindruck, Form, Etikett, Anzahl, sichtbare Maße und Oberflächenschäden belegen; Haltbarkeit, innere Konstruktion, Geruch, exakte Materialzusammensetzung oder individuelle Passform kann es nicht zuverlässig beweisen. Deshalb darf ein attraktives Bild nicht mehr Vertrauen erzeugen, als die sichtbaren Daten tragen. Positive öffentliche Beiträge nennen QC-Fotos häufig als nützlich, während andere Nutzer trotz Fotos mit dem erhaltenen Produkt unzufrieden waren. Beides ist möglich: QC reduziert Unsicherheit, beseitigt sie aber nicht. Definiere vor dem Öffnen der Bilder, welche sichtbaren Abweichungen eine Rückgabe auslösen.",
      "Farbe und Proportionen werden besonders leicht durch Weißabgleich, Bildschirm, Spiegelung und Weitwinkel verändert. Vergleiche mehrere Aufnahmen mit neutralem Hintergrund und suche nach stabilen Unterschieden: eine andere Farbfamilie, fehlende Paneele, falsche Grafik oder abweichende Beschläge sind belastbarer als ein kleiner Helligkeitswechsel. Für Maße müssen Nullpunkt und Endpunkt des flach liegenden Bandes sichtbar sein; ein außerhalb des Bildes beginnendes oder gebogenes Band trägt keine exakte Aussage. Bei symmetrischen Produkten vergleichst du entsprechende Landmarken links und rechts. Diese einfachen Kontrollen ersetzen subjektives „sieht komisch aus“ durch eine wiederholbare Prüfung, die sich bei einer späteren Rückfrage konkret beschreiben lässt.",
      "Lege drei Schwellen fest: materieller Fehler, offene Frage und akzeptable kosmetische Abweichung. Falsche Größe, fehlendes Teil, Riss oder nicht funktionierender Verschluss können materiell sein; ein loser Faden, eine Verpackungsfalte oder eine leichte Lichtabweichung kann je nach Produkt kosmetisch bleiben. Entscheide mit drei klaren Ergebnissen: freigeben, wenn Identität, Maße und sichtbarer Zustand passen; klären, wenn genau ein Bild oder Maß fehlt; zurückgeben, wenn die dokumentierte Grenze bereits überschritten ist. Formuliere bei einer Zusatzaufnahme gleich die Folgeregel, etwa „behalten, wenn der Fleck abwischbar ist; zurückgeben, wenn es ein Schnitt ist“. Dadurch wird die Anfrage zu einer Entscheidung statt zu weiterem Warten.",
      "Speichere ausgewählte Angebotsoption, Lagerdatensatz, ursprüngliche QC-Bilder, Zusatzanfrage und endgültige Freigabe zusammen. Wo möglich sollten Artikelkennung und Datum im Nachweis erkennbar bleiben, damit ähnliche Produkte nicht verwechselt werden. Nach Zustellung prüfst du in derselben Reihenfolge: Identität, praktische Maße, Konstruktion und sichtbarer Zustand. Dokumentiere eine Differenz vor Nutzung und beschreibe nur, was der Vergleich tatsächlich zeigt. Das garantiert keine Erstattung, schafft aber eine klare Zeitlinie. Persönliche Bestell-, Lager- oder Adressdaten gehören nicht in öffentliche Beiträge; die Aufnahmen sind zunächst private Belege und sollten nur mit sauberer Anonymisierung und eigener Berechtigung veröffentlicht werden.",
    ],
    "hipobuy-actual-vs-volumetric-weight": [
      "Volumengewicht entsteht häufig aus Länge mal Breite mal Höhe geteilt durch einen routenspezifischen Faktor. Die Rechnung ist einfach, doch Einheit, Divisor, Rundung, Mindeststufe und Größenband sind nicht universell. Luft-, Bahn- und Expresslinien können unterschiedliche Regeln anwenden, die sich außerdem ändern. Deshalb nennt dieser Ratgeber keinen angeblich festen Hipobuy-Divisor. Maßgeblich ist die aktuelle Beschreibung oder das Live-Angebot der konkreten Route. Schon eine Verkürzung um zehn Prozent senkt das rechnerische Volumen ungefähr um zehn Prozent, solange die anderen Seiten gleich bleiben; das Überschreiten einer Tarifgrenze kann den Effekt jedoch stärker machen. Notiere daher alle drei Außenmaße und ob das Lager aufgerundet hat.",
      "Bevor du allgemein um Umpacken bittest, finde die Seite, die den Schaden verursacht. Ein Schuhkarton kann die Höhe bestimmen, ein gerollter Gegenstand die Länge und mehrere weiche Textilien die gesamte Fülle. Bitte um ein Foto oder einen Packplan, der zeigt, welche Produkte die Außenform festlegen. Danach lässt sich gezielt entscheiden: Verkaufskarton entfernen, weiche Ware falten, einen passenderen Außenkarton wählen oder einen langen Artikel getrennt senden. Jede Änderung hat einen Schutzpreis. Kompression eignet sich eher für weiche Kleidung als für strukturierte Schuhe, empfindliche Beschläge oder Elektronik. Das Ziel ist nicht die kleinste mögliche Box, sondern das kleinste Format, das die vereinbarte Schutzschwelle noch erfüllt.",
      "Erstelle mit denselben Produkten und demselben Ziel drei Szenarien: kompakt, stärker geschützt und – falls sinnvoll – geteilt. Trage für jedes Szenario geschätzte Außenmaße, Istgewicht, routeabhängiges Abrechnungsgewicht, Verpackungsleistung, zulässige Linien und Gesamtkosten ein. Zwei kleinere Pakete können weniger Volumen je Einheit haben, erzeugen aber doppelte Mindestentgelte, mehr Verpackung und zwei Fehler- oder Zustellpfade. Ein einziges Paket kann günstiger wirken, aber wegen einer langen Seite eine wichtige Route verlieren. Berechne erst nach Prüfung der Inhaltsbeschränkungen. Ein mathematisch niedriger Wert ist wertlos, wenn die ausgewählte Linie einen Teil der Ware nicht akzeptiert.",
      "Vor Zahlung speicherst du die gemessenen Außenmaße, das Waagengewicht, den berechneten Wert, das endgültige Abrechnungsgewicht, die Rundung und den Gesamtpreis. Weicht eine spätere Messung ab, kann genau erkannt werden, welcher Input sich änderte. Frage den Support nach messbaren Daten statt nach einer allgemeinen Preiszusage: Gewicht und Zentimeter lassen sich nachprüfen, „sollte günstig sein“ nicht. Nach Erhalt ergänzt du tatsächliche Laufzeit, Zustand und Endkosten. Mit mehreren Sendungen siehst du, welche Produktarten regelmäßig Volumen erzeugen und welche Verpackungsentscheidung wirklich Geld spart. So wird die nächste Schätzung aus vergleichbaren eigenen Beobachtungen gebaut und nicht aus einer Formel ohne Routenkontext.",
    ],
    "hipobuy-90-day-warehouse-storage": [
      "Bestätige für jeden Artikel, wann die beworbene Lagerzeit tatsächlich beginnt und welches Ablaufdatum im Konto angezeigt wird. Bestelltag, Verkäufer-Versand, physischer Lagereingang und Freigabe der QC-Fotos können auseinanderliegen. Gleichzeitig kann die Möglichkeit zur Rückgabe an den Verkäufer wesentlich früher enden als die Lagerung. Speichere Ankunft, QC-Verfügbarkeit, spätesten realistischen Reklamationstag und geplante Konsolidierung in einer Zeile. Wenn die Anzeige fehlt oder widersprüchlich wirkt, frage früh mit eindeutiger Artikelkennung nach. Ein allgemeiner Satz über 90 Tage ist kein verlässlicher Kalender für einen konkreten Vorgang; die sichtbaren Kontodaten und die aktuellen Bedingungen müssen die Planung steuern.",
      "Eine feste wöchentliche Lagerprüfung ist sinnvoller als ständiges Aktualisieren oder wochenlanges Ignorieren. Sortiere jede Position in erwartet, eingetroffen ohne QC, offene Frage, Rückgabe läuft oder versandbereit. Ergänze, wer als Nächstes handeln muss – Verkäufer, Support oder du – und an welchem Datum Schweigen zur Eskalation wird. Beende jede Prüfung mit einer Paketentscheidung, selbst wenn sie nur „noch sieben Tage warten“ lautet. Schreibe dazu, welche ausstehenden Produkte dieses Warten rechtfertigen und was bei Nichterfüllung geschieht. So verlängern optionale Käufe den Plan nicht unbegrenzt und aus einem kleinen kompatiblen Paket wird nicht unbemerkt ein sperriger Mix mit anderen Einschränkungen.",
      "Definiere Auslöser, bevor der Sicherheitspuffer knapp wird: Verkäufer überschreitet das erwartete Versandfenster, ein Frageartikel bleibt nach einer gezielten Beweisanfrage offen, die kombinierte Sendung verliert die geplante Route oder der erwartete Gesamtbetrag übersteigt das Budget. Ein Auslöser zwingt nicht automatisch zum Versand, aber zu einem Vergleich klarer Optionen: Artikel zurückgeben, fertige Gruppe separat schicken oder weitere Käufe stoppen. Bereits investierte Wartezeit ist kein Grund, einen ungeeigneten Artikel oder ein teures Paket zu behalten. Vergleiche nur die verbleibenden Kosten, Schutzbedürfnisse, Routen und den Nutzen weiterer Verzögerung. Aktuelle Warnungen im Konto gehen dem ursprünglichen Plan vor.",
      "Arbeite von dem Datum rückwärts, an dem das Paket tatsächlich benötigt wird. Internationale Beförderung, Exportbearbeitung, Zoll und letzte Meile beginnen erst nach Lagerung und Verpackung. Ziehe von Reise, Geschenk oder Saison eine konservative Transitspanne, einen Zollpuffer, die Packzeit und einen Entscheidungspuffer ab. Die Formulierung „ab fünf Tagen“ beschreibt einen beworbenen Bestfall und darf nicht die einzige Reserve für einen festen Termin sein. Wenn Zeit wichtiger ist als ein möglicher Konsolidierungsvorteil, wird früher versendet. Bei flexibler Zeit kann das Lagerfenster gestaffelte Einkäufe unterstützen, doch Route und Schätzung müssen unmittelbar vor Einreichung erneut geprüft werden, weil sie sich während des Wartens ändern können.",
    ],
    "hipobuy-warehouse-return-checklist": [
      "Öffentliche Beiträge nennen unter anderem Rückgabe- oder Transaktionskosten, stornierte Bestellungen, verspätete Erstattungen und schwierige Kommunikation; andere Nutzer berichten von schneller Hilfe und reibungsloser Lösung. Kein einzelner Beitrag beweist den Ausgang deines Falls oder ein allgemeines Fehlverhalten. Die Themen zeigen jedoch, welche Felder im Vorgangsprotokoll nicht fehlen dürfen: beantragte Lösung, erwarteter Betrag, mögliche Inlands- oder Servicekosten, Ziel der Rückzahlung, zugesagte Bearbeitungsstufe und nächster Prüftermin. Nutze fremde Erfahrungen als Fragen an die aktuellen Kontobedingungen, nicht als Beleg in einer Auseinandersetzung. Deine Bestellung, sichtbaren Regeln und dokumentierten Antworten sind die maßgebliche Beweiskette.",
      "Eine handlungsfähige erste Nachricht kann aus fünf Zeilen bestehen: Bestellkennung, exakt gewählte Option, beobachtbare Abweichung, zugehöriger Nachweis und gewünschtes Ergebnis. Statt pauschaler Vorwürfe beschreibst du beispielsweise, dass Größe M bestellt wurde, das Lageretikett L zeigt, die markierten Bilder beigefügt sind und vor der sichtbaren Frist Rückgabe oder Umtausch gewünscht wird. Reicht das vorhandene Bild nicht, verlange zuerst das eine fehlende Etikett, Maß oder Detail und nenne den Bezug zur Rückgabeentscheidung. Aktualisiere anschließend denselben Gesprächsverlauf. Mehrere parallele Threads erschweren die Zeitlinie und können widersprüchliche Anweisungen erzeugen.",
      "Unterscheide vier Ereignisse: Eingang der Anfrage, Annahme durch die zuständige Stelle, physische Rückbewegung des Artikels und sichtbare Erstattung. Eine freundliche Eingangsbestätigung bedeutet nicht automatisch, dass Verkäuferzustimmung, Versand oder Geldfluss abgeschlossen sind. Notiere für jedes Ereignis Datum und Referenz und kläre, ob ein Ersatz einen neuen Lagerdatensatz erzeugt sowie ob Geld auf Kontoguthaben oder das ursprüngliche Zahlungsmittel zurückgeht. Entferne den Artikel nach bestätigter Entscheidung aus der Paketprognose, behalte aber den Fall bis zum finanziellen Ergebnis. Ein Ersatz braucht neue QC- und Konsolidierungsfristen; er passt nicht automatisch in den alten Zeitplan.",
      "Wenn eine zugesagte Zeitspanne endet, sende eine kurze Eskalation mit Anfragedatum, Annahmereferenz, letztem versprochenem Schritt und genau dem einen Status, den du benötigst. Hänge vorhandene Nachweise an, statt die Geschichte emotional zu verlängern. Nutze einen formalen Streit- oder Eskalationsweg innerhalb der sichtbaren Frist und veröffentliche keine persönlichen Zahlungs-, Adress- oder Bestelldaten. Bei Abschluss dokumentierst du ursprünglichen Warenwert, einbehaltene Gebühren, Erstattungsbetrag, Ziel und Abschlussdatum. Weichen Zahlen von der schriftlichen Regel ab, verlange eine aufgeschlüsselte Erklärung. Danach aktualisierst du Verkäufer- und Produktnotiz, damit der Rückgabegrund die nächste Beschaffung verbessert. Prüfe abschließend auch, ob die erledigte Position noch in einer alten Paketansicht auftaucht; ein veralteter Entwurf kann sonst Gewicht oder Abrechnungsplanung verfälschen. Ein Ersatzartikel beginnt außerdem einen neuen Prüfzyklus und übernimmt nicht automatisch die frühere Freigabe.",
    ],
  },
  es: {
    "how-to-buy-with-hipobuy": [
      "La ficha de Google Play presenta Hipobuy como intermediario para comprar en mercados chinos como Taobao y 1688, con compradores profesionales disponibles todo el día, 90 días de almacenamiento gratuito, más de 200 países de destino, numerosas opciones logísticas y entregas desde cinco días en el mejor caso anunciado. Son descripciones del servicio, no garantías para un artículo, una dirección o una fecha. La landing pública también muestra PayPal, Klarna, Visa, Mastercard y JCB, pero la disponibilidad puede variar por país y cuenta. Antes de un pedido grande, prueba el flujo previsto, revisa el importe tras la conversión y guarda las condiciones visibles del pago.",
      "Un presupuesto resistente al paso por almacén separa tres cifras: valor confirmado de los productos, estimación de transporte nacional y posibles servicios o conversión, y un intervalo independiente para el envío internacional. Antes de medir el paquete, una horquilla compacta y otra voluminosa son más honestas que una cifra exacta. Las opiniones públicas explican por qué: algunos usuarios valoran el proceso sencillo, las imágenes QC y la ayuda, mientras otros dicen que el coste internacional apareció más tarde de lo esperado o que tasas y reembolsos no fueron claros. Son experiencias individuales, pero señalan que pagar productos y aprobar el paquete deben ser dos decisiones presupuestarias distintas.",
      "El primer pedido debe comprobar el sistema, no maximizar el ahorro. Elige un artículo asequible, con variante fácil de reconocer, dimensiones comprobables y un valor que no genere presión si el proceso tarda. Registra compra, envío del vendedor, llegada, publicación de fotos QC, consultas y primera cotización. Después compara expectativa y realidad: ¿llegó tarde el vendedor?, ¿faltó una medida?, ¿el embalaje fue mayor?, ¿alguna comisión apareció en otra fase? Convierte esas respuestas en reglas para el siguiente pedido, como máximo de artículos pendientes, fecha límite de consolidación y techo de coste total. Un ciclo controlado enseña más que muchas publicaciones promocionales de países y rutas diferentes.",
      "Antes del pago internacional guarda ruta elegida, contenido declarado, peso facturable, tres medidas exteriores, servicios de embalaje, dirección y total. Si existe protección o compensación, lee qué hechos cubre y qué pruebas exige; el nombre comercial no basta. Con el seguimiento, vigila excepciones como petición de información, retención aduanera o intento de entrega fallido, porque requieren acciones diferentes. Al recibir, fotografía la caja visiblemente dañada antes de abrirla, dejando la etiqueta en el encuadre, y compara el contenido con el registro del almacén. Conserva también los envíos sin incidencias con peso, medidas, tiempo y coste: tus propios casos comparables son una referencia mejor que un envío ajeno excepcionalmente rápido o caro.",
    ],
    "hipobuy-shipping-cost-guide": [
      "Las reseñas públicas sirven para localizar incertidumbre, no para copiar tarifas. Algunas describen tránsito aceptable, embalaje intacto o seguimiento útil; otras afirman que la factura internacional fue alta o solo se entendió cuando la mercancía ya estaba en almacén. País, código postal, forma, ruta, promoción, fecha y expectativas cambian entre usuarios. Decir que cuatro kilos costaron una cantidad no crea una tarifa si faltan medidas exteriores, peso volumétrico, productos restringidos, protección y conversión. Convierte el relato en preguntas para tu paquete: ¿se mantuvieron cajas?, ¿qué peso se cobró?, ¿la línea admitía el contenido?, ¿el total estaba confirmado antes del pago? Sin esos datos, la cifra no es comparable.",
      "Cuando aparezcan peso y dimensiones del almacén, reconstruye la estimación desde cero. Confirma si la pantalla muestra peso de báscula, cálculo volumétrico o peso facturable después del redondeo y verifica que destino y restricciones coincidan con la línea prevista. Una diferencia no demuestra error: protección, cartones del vendedor, un lado largo o una banda tarifaria pueden explicarla. Si no puedes reconciliarla, plantea una pregunta precisa cada vez: medidas exteriores registradas, embalaje opcional aplicado o regla de peso utilizada. Un mensaje con valores concretos permite investigar; decir únicamente que el envío parece caro no identifica qué entrada produjo el resultado ni deja una respuesta reutilizable para el siguiente paquete.",
      "Compara por lo menos dos escenarios completos con los mismos productos y destino. Uno puede mantener cajas y mayor protección; otro eliminar volumen inútil, usar un cartón ajustado, cambiar a otra línea admisible o dividir la carga. Incluye en ambos embalaje, posible seguro, conversión del pago, costes estimados en destino y restricciones. Solo incorpores un cupón después de comprobar condiciones, vencimiento y ruta elegible. Busca el total controlable, no el titular más bajo: un ahorro pequeño es mal intercambio si la línea rechaza el contenido, el seguimiento no satisface tu tolerancia o un artículo estructurado pierde protección necesaria. Escribe por qué ganó una opción para repetir el análisis más rápido.",
      "Tras la entrega calcula el coste completo: productos, transporte nacional, servicios o transacciones, envío internacional y cualquier cantidad realmente pagada en destino. No repartas el transporte solo según el precio del artículo; uno barato y voluminoso puede ocupar más capacidad que otro compacto y caro. Guarda fecha, ruta, país, peso de báscula y facturable, dimensiones, embalaje, duración y total. Con varios pedidos comparables se forma una base personal que comparte dirección, hábitos y mezcla de productos. No predice cambios futuros, pero supera a capturas públicas sin contexto. Si el total real rebasa repetidamente el límite previo, cambia la selección o el diseño del paquete antes de confiar en otra promoción.",
    ],
    "hipobuy-warehouse-qc-photos": [
      "Una foto de almacén registra un artículo, un momento, una iluminación y pocos ángulos. Puede aportar evidencia fuerte sobre familia de color, forma visible, etiquetas, cantidad, medidas y daños superficiales; no demuestra duración, construcción interior, olor, composición exacta ni ajuste en una persona. Ese límite evita que una imagen atractiva produzca más confianza de la que merece. En opiniones públicas algunos usuarios valoran las fotos QC y otros siguen insatisfechos con el producto recibido. Ambos relatos pueden coexistir porque QC reduce incertidumbre, no la elimina. Define antes de mirar las fotos qué diferencia visible exige devolución, cuál requiere otra prueba y cuál aceptarías como variación cosmética.",
      "El color cambia con balance de blancos, pantalla y reflejos, y la perspectiva gran angular puede deformar zapatos o bolsos. Compara varios fotogramas con fondo neutro y busca diferencias estables: familia de color distinta, panel ausente, gráfico incorrecto o herraje cambiado pesan más que un pequeño cambio de brillo. Para una medida, deben verse el cero y el extremo con la cinta plana; una cinta curvada o que empieza fuera del encuadre no sostiene una cifra exacta. En artículos simétricos compara puntos equivalentes de ambos lados. Estas comprobaciones convierten una impresión subjetiva en una revisión repetible que puede explicarse con precisión al pedir otra foto o iniciar un caso.",
      "Escribe tres umbrales: problema material, pregunta pendiente y diferencia cosmética aceptable. Talla incorrecta, componente ausente, desgarro o cierre inservible pueden ser materiales; hilo suelto, pliegue del envase o leve variación de luz dependen del producto y de tu tolerancia. Termina con aprobar, preguntar o devolver. Aprueba cuando identidad, medidas y estado visible pasan el límite; pregunta si una sola imagen o medida puede resolverlo; devuelve cuando la evidencia ya supera el umbral. Al solicitar una toma adicional, escribe la consecuencia: “conservar si la marca se limpia; devolver si es un corte”. Así la nueva fotografía conduce a una decisión y no consume el plazo sin objetivo.",
      "Guarda opción elegida, registro de almacén, fotos originales, petición adicional y aprobación final en un mismo expediente. Incluye identificador y fecha cuando sea posible para no confundir productos parecidos. Al llegar la caja, repite el orden: identidad, medidas prácticas, construcción y condición visible. Fotografía cualquier diferencia antes de usar el artículo y limita la explicación a lo que realmente muestra la comparación. El expediente no garantiza una solución, pero crea una cronología clara entre oferta, aprobación y recepción. No publiques automáticamente imágenes que contengan referencias de almacén, pedido, dirección u otros datos; primero son prueba privada y solo deberían difundirse con derechos claros y anonimización completa.",
    ],
    "hipobuy-actual-vs-volumetric-weight": [
      "El modelo volumétrico suele multiplicar largo, ancho y alto y dividir por un factor definido por la línea. Lo difícil no es la multiplicación, sino confirmar unidades, divisor, redondeo, mínimo y bandas de tamaño. Transporte aéreo, ferroviario o exprés puede usar reglas distintas y modificarlas. Por eso no conviene publicar un supuesto divisor universal de Hipobuy; la referencia válida es la descripción o cotización activa para ese paquete. Si un lado baja un diez por ciento y los otros permanecen iguales, el volumen baja aproximadamente igual antes del redondeo, pero cruzar una banda puede cambiar más la tarifa. Registra siempre las tres medidas exteriores y si fueron redondeadas.",
      "Antes de pedir un reembalaje genérico, identifica qué dimensión causa el exceso. Una caja de zapatos puede fijar la altura, un objeto enrollado la longitud y varias prendas blandas el volumen general. Pide un esquema o imagen que muestre qué pieza determina la forma. Entonces podrás elegir: retirar cartón comercial, plegar material flexible, usar una caja exterior más ajustada o separar un artículo largo. Cada cambio afecta la protección. La compresión suele ser más tolerable para textiles que para calzado estructurado, accesorios frágiles o electrónica. El objetivo no es la caja mínima a cualquier precio, sino el menor formato que todavía cumple el nivel de protección que aceptaste.",
      "Modela tres casos con idénticos productos y destino: compacto, protegido y dividido si es viable. Para cada uno anota dimensiones previstas, peso real, peso facturable según la ruta, servicio de embalaje, líneas elegibles y coste total. Dos paquetes pueden reducir el volumen individual, pero duplican mínimos, material, seguimientos y posibles incidencias. Uno solo puede parecer barato y perder una línea por un lado demasiado largo. Comprueba por separado las restricciones del contenido antes de calcular. La opción matemáticamente menor no sirve si una de las líneas no acepta su parte. Guarda también las alternativas descartadas y el motivo, porque esa información acelerará la decisión con una mezcla de productos parecida.",
      "Antes de pagar conserva medidas externas, peso de báscula, resultado volumétrico, peso final cobrado, regla de redondeo y precio. Si una medición posterior cambia, podrás ver qué entrada produjo la diferencia. Pide datos medibles al soporte, no una promesa genérica: kilos y centímetros se auditan; “debería ser barato” no. Después de recibir añade duración, estado y coste definitivo. Con varios envíos aparece un patrón sobre qué categorías crean volumen y qué cambio de embalaje realmente cruza una banda tarifaria. Esa historia propia sigue sin garantizar la siguiente ruta, pero permite estimar con paquetes comparables en vez de depender de una fórmula aislada o de una captura sin destino y fecha.",
    ],
    "hipobuy-90-day-warehouse-storage": [
      "Confirma para cada artículo cuándo empieza el periodo anunciado y qué vencimiento muestra la cuenta. Día de pedido, despacho del vendedor, recepción física y publicación de QC no son necesariamente iguales. Además, la posibilidad de devolver al vendedor puede cerrar mucho antes que el almacenamiento. En cada fila guarda llegada, disponibilidad de fotos, último día realista de reclamación y semana de consolidación. Si falta una fecha o parece contradictoria, pregunta temprano identificando el artículo. La frase pública de 90 días no es un calendario individual; el contador visible y las condiciones activas deben controlar la decisión. Revisa cada fila incluso cuando varios productos hayan llegado en la misma fecha.",
      "Una revisión semanal fija es más útil que actualizar a diario o ignorar el almacén durante un mes. Clasifica cada línea como esperada, recibida sin QC, pregunta abierta, devolución en curso o lista. Añade quién debe actuar —vendedor, soporte o tú— y la fecha en que el silencio obliga a escalar. Termina cada revisión con una decisión de paquete, aunque sea esperar siete días más, y escribe qué artículos justifican esa espera y qué harás si no llegan. Así los hallazgos opcionales no extienden indefinidamente el plan y un grupo pequeño no se convierte sin intención en una caja voluminosa con restricciones diferentes.",
      "Define disparadores antes de que el margen se vuelva incómodo: vendedor fuera de su ventana prevista, artículo aún en duda tras una petición precisa, pérdida de la línea elegida o presupuesto superado. Un disparador no impone enviar de inmediato; obliga a comparar opciones concretas como devolver una pieza, despachar el grupo listo o dejar de añadir compras. El tiempo ya invertido no mejora un artículo inadecuado ni un paquete caro. Evalúa solo desde hoy los costes restantes, la protección, las rutas y el valor de esperar. Si una advertencia actual de la cuenta contradice el plan inicial, sigue la advertencia y conserva la evidencia del cambio.",
      "Trabaja hacia atrás desde la fecha en que realmente necesitas la caja. Transporte internacional, exportación, aduana y última milla ocurren después del almacenamiento. Resta al viaje, regalo o temporada un intervalo conservador de tránsito, margen de aduana, tiempo de embalaje y margen de decisión. “Desde cinco días” es el mejor caso anunciado, no un calendario para un evento fijo. Cuando el tiempo importa más que consolidar, envía antes y reduce incertidumbre. Si la fecha es flexible, usa la ventana para llegadas escalonadas, pero vuelve a confirmar línea y estimación justo antes de presentar el paquete, porque la disponibilidad puede cambiar mientras los productos esperan.",
    ],
    "hipobuy-warehouse-return-checklist": [
      "Las opiniones públicas incluyen quejas sobre cargos de devolución o transacción, cancelaciones, reembolsos lentos y comunicación difícil, mientras otras personas describen respuestas rápidas y soluciones fluidas. Ningún post demuestra qué ocurrirá en tu caso ni una conducta general. Sí revela qué campos deben quedar escritos: remedio solicitado, cantidad esperada, posible transporte nacional o servicio, destino del reembolso, etapa prometida y próxima fecha de control. Usa el tema como pregunta para las condiciones visibles de tu pedido, no como acusación probada. Tu opción seleccionada, las fotos del almacén y la respuesta fechada forman una cadena mucho más sólida que la historia de otro cliente.",
      "El primer mensaje debe permitir actuar sin adivinar y puede seguir cinco líneas: identificador, opción exacta, diferencia observable, prueba adjunta y resultado pedido. Por ejemplo: se compró talla M, la etiqueta del almacén muestra L, las imágenes marcadas lo documentan y se solicita devolución o cambio antes del plazo mostrado. Evita etiquetas emocionales e historias largas antes de los datos básicos. Si la diferencia no se puede demostrar, solicita primero una etiqueta legible, una medida o un primer plano y explica que decide un posible retorno. Continúa en el mismo hilo; varias conversaciones paralelas rompen la cronología y pueden producir instrucciones incompatibles.",
      "Registra por separado recepción de la solicitud, aceptación, movimiento físico del producto y devolución del dinero. Una respuesta que confirma lectura no significa que el vendedor haya aceptado, que la pieza haya salido o que el saldo esté disponible. Para cada evento guarda fecha y referencia. Pregunta si una sustitución creará otro registro QC y si el importe vuelve al saldo de la cuenta o al medio original. Tras retirar el artículo del borrador, actualiza peso y dimensiones previstos, pero conserva el expediente hasta ver el resultado financiero. Un reemplazo necesita nuevas fechas de control y consolidación; no debe heredarlas automáticamente del paquete anterior.",
      "Cuando venza el plazo comunicado, envía un seguimiento breve con fecha de solicitud, referencia de aceptación, último paso prometido y el único estado que necesitas conocer. Adjunta las pruebas anteriores en lugar de ampliar el tono. Si existe vía formal de disputa, úsala dentro del periodo visible y no publiques información de pago, dirección o pedido. Al cerrar, registra valor bruto, comisiones retenidas, cantidad reembolsada, destino y fecha. Si el cálculo no coincide con los términos escritos, pide un desglose sin asumir primero que es fraude. Finalmente actualiza tus notas sobre vendedor y producto para que la causa del retorno mejore la próxima selección.",
    ],
  },
  it: {
    "how-to-buy-with-hipobuy": [
      "La scheda Google Play descrive Hipobuy come servizio per acquistare da marketplace cinesi quali Taobao e 1688, con buyer professionali disponibili 24 ore su 24, 90 giorni di deposito gratuito, oltre 200 paesi serviti, numerose opzioni di spedizione e consegna pubblicizzata a partire da cinque giorni. Sono dichiarazioni che spiegano il flusso previsto, non promesse per un prodotto, un indirizzo o una data. La landing pubblica mostra inoltre PayPal, Klarna, Visa, Mastercard e JCB, ma il metodo effettivo può dipendere da paese, account e checkout. Prima di impegnare una somma alta, prova il percorso previsto, leggi il totale dopo il cambio e conserva la conferma con le condizioni visibili.",
      "Un budget che resta utile dopo l’arrivo in magazzino separa tre valori: prezzo confermato degli articoli, stima di consegna nazionale e possibili servizi o conversione, e intervallo autonomo per il trasporto internazionale. Prima delle misure finali è più onesto confrontare un caso compatto e uno ingombrante che fingere una precisione impossibile. Le recensioni pubbliche spiegano il rischio: alcuni utenti apprezzano ordine, foto QC e assistenza, altri riferiscono costi internazionali comparsi più tardi del previsto o difficoltà nel comprendere commissioni e rimborsi. Sono esperienze singole, non dati verificati, ma mostrano perché pagamento dei prodotti e approvazione della spedizione devono restare due decisioni economiche separate.",
      "Il primo acquisto deve collaudare il sistema, non massimizzare il risparmio. Scegli un articolo di valore gestibile, con variante evidente e dimensioni controllabili nelle foto, così un ritardo non crea pressione finanziaria. Registra data d’ordine, spedizione del venditore, ingresso, disponibilità di immagini utilizzabili, eventuale richiesta e primo preventivo. Poi confronta aspettativa e realtà: il venditore ha impiegato più tempo, mancava una misura, la scatola era più grande o un costo era visibile solo in una fase successiva? Trasforma le risposte in regole per il pacco seguente, come massimo numero di casi aperti, ultima settimana di consolidamento e limite totale oltre il quale interrompere.",
      "Prima del pagamento internazionale salva rotta, contenuto dichiarato, peso fatturabile, tre misure esterne, servizi di imballaggio, destinazione e totale. Se esiste protezione o compensazione, leggi gli eventi coperti e le prove richieste: il nome commerciale da solo non basta. Nel tracking osserva soprattutto eccezioni come richiesta di dati, fermo doganale o tentativo di consegna fallito, perché richiedono azioni diverse dal normale transito. Alla ricezione fotografa un involucro visibilmente danneggiato prima di aprirlo con l’etichetta in vista, quindi confronta il contenuto con il dossier QC. Conserva anche i casi senza problemi con peso, misure, durata e costo: i tuoi dati comparabili valgono più di una spedizione altrui eccezionalmente rapida o costosa.",
    ],
    "hipobuy-shipping-cost-guide": [
      "Le recensioni pubbliche servono a trovare l’incertezza, non a copiare un prezzo. Alcune parlano di tempi accettabili, imballo integro e tracking utile; altre dicono che il costo internazionale era superiore alle attese o divenne chiaro solo dopo l’arrivo in magazzino. Paese, CAP, forma del pacco, rotta, promozione, data e aspettative cambiano. Una frase come “quattro chili sono costati X” non è un tariffario se mancano misure esterne, peso volumetrico, restrizioni, protezione e cambio. Usala per formulare domande sul tuo pacco: è stato applicato il volume, sono rimaste le scatole, quale linea era ammessa e quale totale era confermato prima del pagamento? Senza queste risposte il confronto non è pulito.",
      "Quando il magazzino pubblica peso e dimensioni, ricostruisci la stima da zero. Verifica se il valore è massa sulla bilancia, risultato volumetrico o peso fatturabile già arrotondato e controlla che destinazione e limiti degli articoli corrispondano alla linea prevista. Una differenza non prova un errore: protezione, cartoni del venditore, un lato lungo o una fascia tariffaria possono spiegare il salto. Se il preventivo non torna, poni una domanda precisa alla volta sulle misure esterne registrate, sull’imballaggio opzionale o sulla regola usata. Un messaggio con numeri osservabili permette all’assistenza di indagare; “la spedizione costa troppo” non identifica l’input che ha prodotto il totale e non crea una risposta riutilizzabile.",
      "Confronta almeno due scenari completi con identici articoli e destinazione. Uno può mantenere scatole e maggiore protezione; l’altro togliere vuoti inutili, scegliere un cartone più aderente, usare un’altra linea idonea o dividere il pacco. Inserisci in entrambi costi di imballaggio, protezione eventuale, conversione, stima delle spese a destinazione e restrizioni. Un coupon entra nel modello soltanto dopo avere verificato condizioni, scadenza e rotta ammessa. Scegli il totale controllabile, non il titolo più basso: un piccolo risparmio è un cattivo scambio se la linea rifiuta il contenuto, il tracking è insufficiente o un prodotto strutturato perde la protezione necessaria. Annota perché ha vinto una soluzione.",
      "Dopo la consegna calcola il costo completo includendo prodotti, trasporto nazionale, servizi o transazioni, spedizione internazionale e importi realmente pagati a destinazione. Non distribuire il trasporto solo in base al prezzo: un oggetto economico ma voluminoso può occupare più capacità di uno compatto e costoso. Conserva data, linea, paese, peso reale e fatturabile, tre misure, imballaggio, durata e totale. Dopo più ordini comparabili nasce una base personale che condivide indirizzo, abitudini e mix di prodotti. Non prevede un cambio di rotta, ma è più utile di screenshot pubblici privi di contesto. Se il totale supera spesso il limite stabilito, cambia composizione o progetto del pacco prima di affidarti a un altro sconto.",
    ],
    "hipobuy-warehouse-qc-photos": [
      "Una foto di magazzino mostra un articolo, in un momento, con una certa luce e da pochi angoli. Può documentare famiglia cromatica, forma visibile, etichetta, quantità, misure e danni superficiali; non prova durata, costruzione interna, odore, composizione esatta o vestibilità su una persona. Questo limite impedisce che un’immagine gradevole crei più fiducia dei dati disponibili. Alcune recensioni pubbliche lodano le foto QC, mentre altri utenti restano insoddisfatti del prodotto ricevuto. Le due cose possono essere vere perché il controllo riduce l’incertezza senza eliminarla. Prima di aprire le immagini definisci quale differenza visibile richiede un reso, quale domanda necessita di un’altra prova e quale variazione cosmetica sei disposto ad accettare.",
      "Colore e proporzioni sono sensibili a bilanciamento del bianco, monitor, riflessi e grandangolo. Confronta più fotogrammi con sfondo neutro e cerca differenze stabili: famiglia di colore diversa, pannello assente, grafica errata o ferramenta differente contano più di un piccolo cambio di luminosità. Per una misura devono apparire sia lo zero sia il punto finale, con il nastro piatto; se parte fuori dall’immagine o curva sul prodotto non sostiene un dato esatto. Sugli articoli simmetrici confronta riferimenti corrispondenti sui due lati. Queste semplici regole trasformano “sembra strano” in una verifica ripetibile e danno all’assistenza una domanda concreta invece di un’impressione impossibile da valutare.",
      "Scrivi tre soglie: difetto materiale, domanda aperta e variazione cosmetica accettabile. Taglia sbagliata, componente mancante, strappo o chiusura non funzionante possono essere materiali; filo sciolto, piega dell’imballo o lieve variazione dovuta alla luce dipendono dall’articolo. Termina con approvare, chiedere o rendere. Approva quando identità, misure e condizione superano la soglia; chiedi se una sola immagine o misura può risolvere; restituisci quando l’evidenza ha già oltrepassato il limite. Nella richiesta aggiuntiva indica subito la conseguenza, per esempio “tengo se il segno si pulisce, rendo se è un taglio”. In questo modo la nuova foto produce una decisione invece di consumare il termine.",
      "Conserva opzione scelta, registrazione del magazzino, foto originali, richiesta aggiuntiva e approvazione finale nello stesso dossier. Includi identificatore e data quando possibile, così prodotti simili non vengono confusi. Alla consegna ripeti l’ordine: identità, misure pratiche, costruzione e stato visibile. Fotografa una differenza prima dell’uso e descrivi solo ciò che il confronto mostra davvero. Il dossier non garantisce un rimedio, ma crea una cronologia leggibile tra inserzione, approvazione e ricezione. Non pubblicare automaticamente immagini che contengono riferimenti di ordine, magazzino, indirizzo o altre informazioni; sono prima di tutto prove private e possono essere condivise solo con diritti chiari e anonimizzazione completa.",
    ],
    "hipobuy-actual-vs-volumetric-weight": [
      "Il modello volumetrico moltiplica spesso lunghezza, larghezza e altezza e divide per un fattore specifico della linea. La difficoltà non è l’operazione, ma confermare unità, divisore, arrotondamento, minimo e fasce dimensionali. Servizi aerei, ferroviari ed espressi possono applicare regole diverse e cambiarle nel tempo. Per questo non va pubblicato un presunto divisore universale Hipobuy: la fonte affidabile è la descrizione o quotazione attiva del pacco considerato. Se un lato diminuisce del dieci per cento e gli altri restano uguali, il volume scende circa allo stesso modo prima dell’arrotondamento; attraversare una fascia può avere un effetto maggiore. Registra sempre tutte le misure esterne e l’eventuale arrotondamento.",
      "Prima di chiedere genericamente un nuovo imballo, identifica la dimensione che causa il problema. Una scatola di scarpe può fissare l’altezza, un oggetto arrotolato la lunghezza e molti tessili morbidi il volume complessivo. Chiedi un’immagine o schema che mostri quali pezzi definiscono la forma. Poi scegli in modo mirato: rimuovere cartoni commerciali, piegare materiale soffice, usare una scatola più aderente o spedire separatamente un articolo lungo. Ogni intervento ha un costo in protezione. La compressione è più adatta ai tessili che a scarpe strutturate, accessori fragili o elettronica. L’obiettivo non è il contenitore più piccolo possibile, ma la minore forma che rispetta ancora il livello di protezione accettato.",
      "Costruisci tre scenari con gli stessi prodotti e la stessa destinazione: compatto, protetto e diviso se fattibile. Per ognuno annota misure previste, peso reale, peso fatturabile secondo la rotta, servizio di imballo, linee idonee e costo totale. Due pacchi più piccoli possono ridurre il volume singolo ma duplicano minimi, materiali, tracking e possibilità di incidente; uno solo può sembrare economico e perdere una linea per un lato lungo. Verifica separatamente le restrizioni del contenuto. Il valore matematicamente minore non conta se una linea non accetta la sua parte. Conserva anche scenari rifiutati e motivo, perché quel dato accelera la decisione con una composizione futura simile.",
      "Prima del pagamento salva misure esterne, peso di bilancia, risultato volumetrico, peso finale addebitato, arrotondamento e prezzo. Se una misurazione successiva differisce, sarà chiaro quale input è cambiato. Chiedi all’assistenza dati misurabili invece di una promessa generica: chilogrammi e centimetri si verificano, “dovrebbe costare poco” no. Dopo la consegna aggiungi durata, condizione e costo definitivo. Con più spedizioni emerge quali categorie creano sistematicamente volume e quale modifica supera davvero una fascia tariffaria. Lo storico personale non garantisce il futuro, ma consente stime da pacchi comparabili invece di una formula isolata o di uno screenshot senza paese, restrizioni e data.",
    ],
    "hipobuy-90-day-warehouse-storage": [
      "Conferma per ogni articolo quando inizia il periodo pubblicizzato e quale scadenza mostra l’account. Giorno d’ordine, spedizione del venditore, ingresso fisico e disponibilità QC possono essere diversi. Inoltre l’opportunità di reso al venditore può chiudersi molto prima del deposito. In ogni riga salva arrivo, pubblicazione delle foto, ultimo giorno realistico per contestare e settimana di consolidamento. Se una data manca o è contraddittoria, domanda presto indicando l’articolo. La frase pubblica sui 90 giorni non è un calendario individuale; contatore e condizioni correnti devono guidare la decisione. Controlla ciascuna posizione anche quando più prodotti sono arrivati nello stesso giorno.",
      "Una revisione settimanale fissa è più utile che aggiornare continuamente o ignorare il magazzino per un mese. Classifica ogni riga come attesa, ricevuta senza QC, domanda aperta, reso in corso o pronta. Aggiungi chi deve agire —venditore, assistenza o tu— e la data in cui il silenzio richiede escalation. Chiudi ogni controllo con una decisione di pacco, anche se è attendere altri sette giorni, specificando quali articoli giustificano l’attesa e cosa succede se non arrivano. Così gli acquisti facoltativi non allungano il piano senza fine e un gruppo piccolo non diventa involontariamente un mix voluminoso con restrizioni diverse.",
      "Definisci trigger prima che il margine diventi scomodo: il venditore supera la finestra prevista, una domanda resta aperta dopo una richiesta precisa, il pacco combinato perde la linea desiderata o il totale stimato oltrepassa il budget. Un trigger non impone l’invio immediato; obbliga a confrontare opzioni concrete come rendere un articolo, spedire il gruppo pronto o smettere di aggiungere acquisti. Il tempo già speso non migliora un prodotto inadatto né un pacco troppo caro. Valuta da oggi i costi rimanenti, la protezione, le rotte e il vantaggio dell’attesa. Se un avviso corrente contraddice il piano, segui l’avviso e conserva prova del cambiamento.",
      "Lavora a ritroso dalla data in cui serve davvero il pacco. Trasporto internazionale, esportazione, dogana e ultimo miglio iniziano dopo deposito e imballaggio. Sottrai all’evento un intervallo prudente di transito, un margine doganale, tempo di preparazione e margine decisionale. “A partire da cinque giorni” è il caso migliore pubblicizzato, non un calendario per viaggio, regalo o stagione. Se il tempo conta più del vantaggio di consolidare, spedisci prima e riduci l’incertezza. Se la data è flessibile, usa il deposito per arrivi scaglionati, ma ricontrolla linea e stima subito prima della presentazione perché disponibilità e tempi possono cambiare mentre gli articoli aspettano.",
    ],
    "hipobuy-warehouse-return-checklist": [
      "Le recensioni pubbliche includono lamentele su costi di reso o transazione, ordini cancellati, rimborsi lenti e comunicazione difficile; altri utenti descrivono assistenza rapida e soluzioni lineari. Nessun post dimostra come finirà il tuo caso o un comportamento generale. I temi indicano però i campi da registrare: rimedio richiesto, importo atteso, possibile trasporto nazionale o servizio, destinazione del rimborso, fase promessa e prossima data di controllo. Usa l’esperienza altrui come domanda per le condizioni correnti, non come accusa provata. Opzione selezionata, foto del magazzino e risposte datate costituiscono una catena molto più forte.",
      "Il primo messaggio deve essere eseguibile e può seguire cinque righe: identificatore, opzione esatta, differenza osservabile, prova allegata e risultato richiesto. Per esempio: è stata ordinata M, l’etichetta del magazzino mostra L, i fotogrammi segnati documentano il fatto e si chiede reso o cambio prima della scadenza visibile. Evita etichette emotive e cronologie lunghe prima dei dati. Se la differenza non è ancora provabile, chiedi una targhetta leggibile, una misura o un dettaglio e indica che serve alla decisione di reso. Aggiorna lo stesso thread: conversazioni parallele spezzano la linea temporale e possono creare istruzioni incompatibili.",
      "Registra separatamente ricezione della richiesta, accettazione, movimento fisico e rimborso visibile. Una risposta che conferma la lettura non significa consenso del venditore, spedizione completata o denaro disponibile. Salva data e riferimento per ogni evento. Chiedi se una sostituzione creerà un nuovo record QC e se l’importo tornerà nel saldo o sul metodo originale. Dopo avere tolto l’articolo dalla bozza, aggiorna peso e dimensioni previsti, ma conserva il fascicolo fino all’esito finanziario. Un ricambio richiede nuove scadenze di controllo e consolidamento; non può ereditare automaticamente il vecchio calendario del pacco.",
      "Quando scade il tempo indicato, invia un sollecito breve con data della richiesta, riferimento di accettazione, ultimo passo promesso e unico stato necessario. Allega le prove precedenti invece di aumentare il volume dei messaggi. Se esiste una procedura formale, usala entro la scadenza visibile e non pubblicare dati di pagamento, indirizzo o ordine. Alla chiusura registra valore lordo, commissioni trattenute, importo rimborsato, destinazione e data. Se i numeri differiscono dai termini scritti, chiedi un dettaglio senza dichiarare prima un illecito. Infine aggiorna note su venditore e prodotto, così il motivo del reso migliora la prossima selezione. Controlla anche il progetto del pacco e il saldo dopo la chiusura: una riga rimasta attiva può continuare a influire su peso, dimensioni o data prevista. Per un cambio, assegna al nuovo articolo una nuova verifica QC invece di riutilizzare automaticamente l’approvazione precedente. Se il rimborso torna su un metodo diverso da quello atteso, annota la spiegazione e il tempo effettivo prima di considerare concluso il caso. Conserva sia gli esiti positivi sia quelli problematici. Uno storico composto soltanto da incidenti rende il confronto troppo negativo, mentre una tabella con causa, soluzione, tempi e costo mostra quali controlli hanno realmente ridotto il rischio. Prima del pacco successivo rileggi la causa e modifica una sola regola di acquisto o verifica.",
    ],
  },
  pl: {
    "how-to-buy-with-hipobuy": [
      "Karta Google Play opisuje Hipobuy jako usługę pomagającą kupować na chińskich platformach, między innymi Taobao i 1688. Reklamuje profesjonalnych kupujących dostępnych przez całą dobę, 90 dni bezpłatnego magazynowania, ponad 200 krajów docelowych, wiele opcji przewozu i dostawę w najlepszym przypadku od pięciu dni. To opis zamierzonego procesu, nie obietnica dla konkretnego produktu, adresu lub terminu. Publiczna strona pokazuje też PayPal, Klarna, Visa, Mastercard i JCB, lecz widoczność metody może zależeć od kraju, konta oraz chwili płatności. Przed większym zamówieniem przejdź mały test wybranej ścieżki, sprawdź końcową kwotę po przewalutowaniu, czas rozliczenia oraz sposób ewentualnego zwrotu. Zachowaj potwierdzenie, ponieważ samo logo płatnicze nie wyjaśnia wszystkich warunków transakcji.",
      "Budżet odporny na etap magazynu składa się z trzech osobnych liczb: potwierdzonej wartości produktów, roboczego szacunku dostawy krajowej i możliwych usług lub różnicy kursowej oraz niezależnego przedziału dla transportu międzynarodowego. Przed końcowym pomiarem uczciwiej jest policzyć wariant kompaktowy i objętościowy niż podawać jedną pozornie dokładną kwotę. Publiczne opinie pokazują, dlaczego to ważne: część osób chwali prosty proces, zdjęcia QC i pomoc, a inni twierdzą, że koszt wysyłki stał się jasny dopiero później lub że opłaty i refund były trudne do zrozumienia. To pojedyncze doświadczenia, nie audyt, ale wskazują praktyczne ryzyko. Zapłata za towary i zatwierdzenie gotowej paczki muszą pozostać dwiema oddzielnymi decyzjami z własnym limitem.",
      "Pierwsze zamówienie powinno sprawdzić cały system, a nie maksymalizować oszczędność. Wybierz niedrogi artykuł z wariantem łatwym do rozpoznania, wymiarami możliwymi do zweryfikowania i wartością, przy której opóźnienie nie wywoła presji. Zapisz datę zakupu, wysyłki sprzedawcy, przyjęcia, publikacji użytecznych zdjęć, pytania do obsługi i pierwszej wyceny. Następnie porównaj oczekiwania z rzeczywistością: czy sprzedawca wysłał później, brakowało miary, karton okazał się większy, a może koszt pojawił się na kolejnym etapie? Zamień odpowiedzi w reguły dla następnej paczki: maksymalną liczbę nierozwiązanych pozycji, ostatni tydzień konsolidacji, granicę łącznego kosztu i konkretny warunek rezygnacji. Jeden kontrolowany cykl daje bardziej porównywalną wiedzę niż wiele reklamowych historii z innych krajów.",
      "Przed płatnością międzynarodową zapisz wybraną trasę, deklarowaną zawartość, wagę rozliczeniową, trzy zewnętrzne wymiary, usługi pakowania, adres i całkowitą kwotę. Jeżeli oferowana jest ochrona lub rekompensata, przeczytaj objęte zdarzenia, limity i wymagane dowody zamiast ufać samej nazwie. W trackingu obserwuj wyjątki: prośba o informację, zatrzymanie celne albo nieudana próba doręczenia wymagają innych działań niż zwykła przerwa. Przy odbiorze sfotografuj widocznie uszkodzony karton przed otwarciem, z czytelną etykietą, a zawartość porównaj z zapisem QC. Zachowuj również bezproblemowe przesyłki z wagą, wymiarami, czasem i sumą. Własne przypadki o podobnej zawartości i kierunku są lepszą podstawą kolejnego planu niż cudza wyjątkowo szybka lub kosztowna paczka. Dopisz także walutę, kurs i datę płatności, aby końcowy wynik pozostał później porównywalny.",
    ],
    "hipobuy-shipping-cost-guide": [
      "Publiczne recenzje pomagają znaleźć niepewność, lecz nie są cennikiem. Jedni opisują akceptowalny czas, nieuszkodzone opakowanie i użyteczny tracking, inni twierdzą, że międzynarodowa opłata była wysoka albo stała się zrozumiała dopiero po przyjęciu towaru. Kraj, kod, kształt, linia, promocja, data i oczekiwania są różne. Zdanie „cztery kilogramy kosztowały X” pomija zwykle wymiary, wagę objętościową i rozliczeniową, ograniczenia, ochronę oraz kurs. Nie kopiuj kwoty do własnego budżetu. Zamień ją na pytania: czy naliczono objętość, pozostawiono pudełka, jaka trasa była dozwolona, jaki był kod pocztowy i ile potwierdzono przed płatnością? Bez tych pól dwa pakiety o tej samej masie mogą zajmować zupełnie inną przestrzeń i nie tworzą uczciwego porównania. Zawsze odnotuj również datę cytowanej wyceny, ponieważ linia, promocja albo reguła rozliczenia mogły później ulec zmianie. Sprawdź też, czy podana masa była rzeczywista, objętościowa czy już końcowo rozliczona.",
      "Gdy magazyn poda wagę i wymiary, zbuduj wycenę ponownie od początku. Ustal, czy ekran pokazuje masę z wagi, wynik objętościowy czy wagę rozliczeniową po zaokrągleniu, oraz czy cel i ograniczenia odpowiadają planowanej linii. Różnica nie musi być błędem: ochrona, kartony sprzedawcy, długi bok lub nowy przedział mogą zmienić rachunek. Jeśli nie potrafisz go uzgodnić, zadawaj jedno konkretne pytanie naraz: o zapisane wymiary zewnętrzne, zastosowaną usługę albo regułę naliczania. Wiadomość z liczbami daje obsłudze problem możliwy do zbadania; stwierdzenie „wysyłka jest za droga” nie wskazuje wejścia, które utworzyło cenę. Odpowiedź zachowaj obok poprawionej wyceny, aby nie powtarzać tej samej niejasności.",
      "Porównaj co najmniej dwa pełne scenariusze z tym samym koszykiem i kierunkiem. Jeden może zachować pudełka i mocniejszą ochronę, drugi usunąć pustą przestrzeń, użyć dopasowanego kartonu, innej dostępnej linii albo podzielić zawartość. W obu uwzględnij pakowanie, możliwą ochronę, przewalutowanie, spodziewane koszty docelowe i ograniczenia. Kupon dodaj dopiero po sprawdzeniu warunków, terminu i trasy. Wybierz najlepszą kontrolowaną sumę, nie najniższy nagłówek. Niewielka oszczędność jest słaba, jeśli linia odrzuca produkty, śledzenie nie spełnia potrzeb lub strukturalny przedmiot traci ochronę. Zapisz, dlaczego wariant wygrał oraz dlaczego pozostałe odpadły; przy podobnym zamówieniu ta decyzja skróci późniejsze porównanie.",
      "Po dostawie policz koszt pełny: towary, transport krajowy, usługę lub transakcję, przewóz międzynarodowy i rzeczywiście zapłacone kwoty na miejscu. Nie dziel kosztu tylko według cen produktów, bo tani, duży artykuł może zużyć więcej przestrzeni niż drogi, mały. Zapisz datę, trasę, kraj, masę rzeczywistą i rozliczeniową, trzy wymiary, opakowanie, czas oraz sumę. Kilka porównywalnych zamówień tworzy osobistą bazę dla tego samego adresu, nawyków i miksu. Nie przewidzi zmiany taryf, lecz jest lepsza od publicznych zrzutów bez kontekstu. Jeżeli końcowy koszt regularnie przekracza granicę ustaloną przed zakupem, zmień zestaw produktów, wielkość albo sposób podziału, zanim kolejna promocja stanie się jedynym argumentem. Zapisuj również przypadki, w których rzeczywista cena była niższa od górnego szacunku; inaczej historia będzie składać się tylko z problemów i stworzy fałszywie pesymistyczny obraz. Porównuj paczki podobne pod względem kierunku, pory, kategorii oraz ochrony. Dla każdej prognozy zapisz także różnicę między dolną, górną i końcową kwotą. Po kilku cyklach zobaczysz, czy największy błąd pochodził z przewalutowania, pudełek, wagi objętościowej czy opłat docelowych. Wtedy poprawiasz właściwe założenie zamiast zwiększać cały budżet bez wiedzy, gdzie powstała rozbieżność.",
    ],
    "hipobuy-warehouse-qc-photos": [
      "Zdjęcie magazynowe przedstawia jeden artykuł, w jednym momencie, przy określonym świetle i z ograniczonej liczby kątów. Może mocno potwierdzić rodzinę koloru, widoczny kształt, metkę, ilość, wymiary i uszkodzenia powierzchni. Nie dowodzi trwałości, konstrukcji wewnętrznej, zapachu, dokładnego składu ani dopasowania do konkretnej osoby. Ta granica jest ważna, bo ładne zdjęcie może tworzyć więcej zaufania niż niesie dowód. W publicznych opiniach niektórzy chwalą QC, a inni mimo zdjęć pozostają niezadowoleni z otrzymanego produktu. Oba przypadki mogą być prawdziwe: zdjęcia zmniejszają niepewność, ale jej nie eliminują. Przed ich otwarciem ustal, co wymaga zwrotu, co jednego dowodu, a co akceptujesz jako kosmetyczną różnicę.",
      "Kolor i proporcje łatwo zmieniają balans bieli, ekran, odbicie oraz obiektyw szerokokątny. Porównuj kilka ujęć na neutralnym tle i szukaj różnic stałych: inna rodzina barwy, brak panelu, niewłaściwa grafika lub odmienne okucie ma większe znaczenie niż lekka zmiana jasności. Dla pomiaru muszą być widoczne zero i koniec płasko ułożonej taśmy. Taśma zaczynająca się poza kadrem lub zagięta nie wspiera dokładnej liczby. Przy symetrycznych produktach sprawdź odpowiadające punkty po obu stronach. Te proste zasady zamieniają „wygląda dziwnie” w powtarzalną kontrolę, którą można jasno opisać przy prośbie o nowe ujęcie. Używaj własnego przedmiotu o znanych punktach jako wzorca.",
      "Zapisz trzy progi: błąd materialny, otwarte pytanie i dopuszczalna zmiana kosmetyczna. Zły rozmiar, brak części, rozdarcie lub niesprawne zapięcie mogą być istotne; luźna nitka, zagięcie opakowania czy lekka różnica światła zależą od towaru i twojej tolerancji. Zakończ wynikiem: zatwierdzić, zapytać lub zwrócić. Zatwierdź, gdy tożsamość, wymiary i stan przechodzą próg; zapytaj, jeśli jedna fotografia lub miara rozstrzyga; zwróć, gdy widoczny dowód już przekracza limit. Przy dodatkowym zdjęciu dopisz następstwo, na przykład „zachować, jeśli ślad można zetrzeć; zwrócić, jeśli to przecięcie”. Wtedy dowód prowadzi do decyzji zamiast tylko zużywać czas.",
      "Trzymaj wybraną opcję, rekord magazynu, oryginalne fotografie, prośbę o uzupełnienie i końcową zgodę w jednym zestawie. Zachowaj identyfikator oraz datę, gdy są dostępne, aby nie pomylić podobnych rzeczy. Po otrzymaniu sprawdź w tej samej kolejności: tożsamość, praktyczne wymiary, wykonanie i widoczny stan. Sfotografuj różnicę przed użyciem i opisuj wyłącznie to, co pokazuje porównanie. Zestaw nie gwarantuje rozwiązania, ale tworzy czytelną oś od oferty do odbioru. Nie publikuj automatycznie zdjęć zawierających numery zamówienia, magazynu, adres lub inne dane. Służą przede wszystkim jako prywatny dowód i mogą zostać pokazane publicznie tylko przy prawach do materiału oraz pełnym usunięciu identyfikatorów. Dla kilku podobnych produktów nadaj własne krótkie oznaczenia i umieść je przy każdej fotografii. W razie późniejszej różnicy obsługa powinna móc połączyć zamówioną opcję, zaakceptowane zdjęcie i otrzymany egzemplarz bez zgadywania, który kadr należy do której pozycji. Przy odbiorze użyj tej samej listy, którą zastosowano w magazynie, zamiast tworzyć nowe kryteria po fakcie. Jeśli wada była widoczna już wcześniej i została zaakceptowana, opisz to uczciwie; jeżeli pojawiła się między zdjęciem a dostawą, pokaż oba etapy i nie wyciągaj wniosku szerszego niż materiał. Dla artykułu SEO wystarczy przykład zanonimizowanego sposobu oceny; nie trzeba ujawniać cudzej twarzy, adresu, numeru ani zdjęcia bez zgody. Oryginalny diagram lub własna fotografia z usuniętymi danymi buduje wiarygodność bez tworzenia nowego ryzyka prywatności. Każdy opublikowany przykład powinien jasno wyjaśniać, co zdjęcie potwierdza, a czego nadal nie może dowieść.",
    ],
    "hipobuy-actual-vs-volumetric-weight": [
      "Model objętościowy często mnoży długość, szerokość i wysokość, a wynik dzieli przez czynnik ustalony przez linię. Trudność nie polega na mnożeniu, lecz na potwierdzeniu jednostek, dzielnika, zaokrąglenia, minimum oraz progów wymiarowych. Transport lotniczy, kolejowy i ekspresowy może stosować inne zasady, które się zmieniają. Dlatego nie należy podawać rzekomo jednego dzielnika Hipobuy; źródłem jest aktualny opis lub oferta wybranej trasy. Jeżeli jeden bok spadnie o dziesięć procent, a pozostałe się nie zmienią, objętość spada podobnie przed zaokrągleniem. Przejście przez przedział może jednak dać inny efekt. Zapisz trzy zewnętrzne miary w jednej jednostce i sprawdź, czy magazyn zaokrąglił każdą z nich.",
      "Zanim poprosisz ogólnie o przepakowanie, znajdź wymiar powodujący problem. Pudełko po butach może ustalać wysokość, zwinięty produkt długość, a zestaw miękkich ubrań całkowitą objętość. Poproś o zdjęcie lub układ wskazujący, które rzeczy kształtują zewnętrzny karton. Potem wybierz celowo: usuń zbędne opakowanie sprzedażowe, złóż miękki materiał, użyj lepiej dopasowanego pudła albo wydziel długi element. Każda zmiana ma cenę ochrony. Kompresja jest zwykle bezpieczniejsza dla tekstyliów niż dla obuwia o stałym kształcie, delikatnych akcesoriów lub elektroniki. Celem nie jest najmniejszy karton za wszelką cenę, lecz najmniejszy format, który nadal spełnia przyjęty poziom ochrony.",
      "Zbuduj trzy scenariusze z tymi samymi produktami i kierunkiem: kompaktowy, chroniony i podzielony, jeśli dopuszczalny. Dla każdego wpisz przewidywane wymiary, wagę rzeczywistą, rozliczeniową według linii, usługę pakowania, dostępne trasy i koszt pełny. Dwie mniejsze paczki mogą ograniczyć objętość każdej, ale podwajają opłaty minimalne, materiały, numery śledzenia i ryzyko obsługi. Jedna większa może wyglądać taniej, lecz stracić linię z powodu długiego boku. Sprawdź ograniczenia zawartości dla każdej części osobno. Matematycznie najtańszy układ nie pomaga, jeżeli przewoźnik odrzuci produkt. Zachowaj też odrzucone warianty i powód, aby przy podobnej zawartości nie powtarzać całej analizy.",
      "Przed płatnością zachowaj zewnętrzne wymiary, masę z wagi, obliczenie objętościowe, końcową wagę naliczoną, regułę zaokrąglenia i cenę. Jeżeli późniejszy pomiar się zmieni, zobaczysz dokładnie, które wejście stworzyło różnicę. Proś obsługę o mierzalne dane, nie ogólną obietnicę: kilogramy i centymetry można porównać, a „powinno być tanio” nie. Po dostawie dodaj czas, stan i koszt końcowy. Przy kilku wysyłkach widać, jakie kategorie regularnie generują pustą przestrzeń oraz która zmiana naprawdę przekracza próg taryfy. Osobista historia nie gwarantuje następnego wyniku, lecz jest solidniejsza niż sama formuła albo zrzut bez kraju, daty, wymiarów i ograniczeń. Podczas ponownego pakowania zapisz zarówno stan przed zmianą, jak i po niej, w przeciwnym razie nie ocenisz skutku. Jeżeli różnica kilku centymetrów nie zmienia zaokrąglenia ani przedziału, dodatkowa usługa może nie dać oszczędności. Z kolei zmniejszenie jednego krytycznego boku może otworzyć inną linię, dlatego nie patrz wyłącznie na całkowitą objętość. Przelicz każdą opcję w jednostkach używanych przez daną trasę i nie przenoś dzielnika z wcześniejszej paczki. Zapisz, czy limit dotyczy pojedynczego boku, sumy wymiarów czy masy. Dwa pakiety o identycznej objętości mogą mieć różną dostępność, gdy jeden jest długi i wąski, a drugi zbliżony do sześcianu. Kształt jest zatem częścią kosztu, nie tylko estetyką opakowania. Jeżeli linia pokazuje minimalny krok naliczenia, sprawdź koszt po obu stronach tej granicy. Niewielka redukcja może nie zmienić ceny, a nieco większa może obniżyć całe rozliczenie. Wniosek zapisuj po uzyskaniu końcowej wyceny, nie na podstawie samego przewidywania. Do arkusza dodaj kolumnę z datą i nazwą trasy, ponieważ ten sam karton może zostać później policzony według innej bieżącej reguły.",
    ],
    "hipobuy-90-day-warehouse-storage": [
      "Dla każdego produktu potwierdź, kiedy zaczyna się reklamowany okres i jaką datę końcową pokazuje konto. Dzień zamówienia, wysłania przez sprzedawcę, fizycznego przyjęcia i publikacji QC mogą być różne. Jednocześnie możliwość zwrotu do sprzedawcy może skończyć się znacznie wcześniej niż magazynowanie. W jednym wierszu zapisz przyjęcie, dostępność zdjęć, ostatni realny dzień zgłoszenia i tydzień konsolidacji. Jeśli daty brakuje lub jest sprzeczna, zapytaj wcześnie z jednoznacznym identyfikatorem. Publiczne 90 dni nie stanowi indywidualnego kalendarza; widoczny licznik i bieżące warunki muszą kierować decyzją. Sprawdź każdą pozycję osobno nawet wtedy, gdy kilka rzeczy pojawiło się tego samego dnia.",
      "Stały przegląd raz w tygodniu jest lepszy niż ciągłe odświeżanie albo miesiąc bez kontroli. Oznacz pozycje jako oczekiwane, przyjęte bez QC, otwarte pytanie, zwrot w toku lub gotowe. Dodaj właściciela następnej czynności — sprzedawcę, obsługę albo siebie — oraz datę, po której cisza wymaga eskalacji. Każdy przegląd zakończ decyzją o paczce, nawet jeżeli brzmi ona „czekamy siedem dni”. Wskaż, które nadchodzące produkty uzasadniają czekanie i co nastąpi, gdy nie dotrą. To zatrzymuje opcjonalne zakupy przed bezterminowym przedłużaniem planu i pokazuje, kiedy mała grupa zamienia się w duży zestaw o innych ograniczeniach transportowych.",
      "Ustal wyzwalacze zanim margines zrobi się mały: sprzedawca przekroczył spodziewaną wysyłkę, pytanie pozostaje otwarte po jednej precyzyjnej prośbie, połączona paczka traci planowaną linię lub szacowana suma przekracza budżet. Wyzwalacz nie oznacza automatycznej wysyłki, lecz wymusza porównanie konkretnych opcji: zwrócić produkt, wysłać gotową grupę albo przestać dokładać. Już poświęcony czas nie poprawia niewłaściwej rzeczy ani drogiej paczki. Od dzisiaj porównuj pozostałe koszty, ochronę, dostęp do tras i wartość dalszego czekania. Jeżeli aktualne ostrzeżenie konta przeczy dawnemu planowi, zastosuj nowe dane i zachowaj ich zrzut jako wyjaśnienie zmiany.",
      "Planuj wstecz od dnia, w którym paczka jest naprawdę potrzebna. Transport międzynarodowy, eksport, odprawa i ostatnia mila zaczynają się dopiero po przechowaniu i pakowaniu. Od daty podróży, prezentu lub sezonu odejmij ostrożny czas przewozu, margines celny, przygotowanie magazynu oraz bufor decyzji. Hasło „od pięciu dni” opisuje reklamowany najlepszy przypadek, nie harmonogram dla stałego wydarzenia. Gdy termin jest ważniejszy od możliwej korzyści z konsolidacji, wyślij wcześniej. Przy elastycznym czasie korzystaj z okna na różne dostawy, ale ponownie potwierdź trasę i wycenę tuż przed złożeniem paczki, ponieważ dostępność mogła zmienić się podczas oczekiwania. Zostaw także czas na odrzuconą metodę płatności, ponowny pomiar albo prośbę o przepakowanie. Ostatni bezpieczny dzień nie powinien być dniem, w którym dopiero zaczynasz porównywać linie, ponieważ jedna nieudana opcja może odebrać możliwość spokojnej korekty. Raz w tygodniu zapisz również przewidywaną datę zakończenia całego pakietu, a nie tylko poszczególnych produktów. Jeżeli data przesuwa się po każdym nowym zakupie, magazynowanie przestało być buforem i stało się mechanizmem bezterminowego odkładania decyzji. W takim momencie zamknij listę zakupów i rozstrzygnij każdą żółtą pozycję. Kolejny atrakcyjny produkt nie powinien zużywać zapasu przeznaczonego na zdjęcia, odpowiedź wsparcia i poprawkę odrzuconej metody wysyłki. Ostateczny plan powinien zawierać wyraźną datę, po której nie dodajesz już niczego do paczki.",
    ],
    "hipobuy-warehouse-return-checklist": [
      "Publiczne opinie obejmują skargi na opłaty zwrotne lub transakcyjne, anulowanie, wolny refund i trudną komunikację; inni użytkownicy opisują szybką pomoc oraz sprawne rozwiązanie. Żaden wpis nie dowodzi wyniku twojego przypadku ani zachowania całej usługi. Tematy pokazują jednak pola potrzebne w dzienniku: żądany rezultat, spodziewana kwota, możliwy krajowy transport lub usługa, miejsce zwrotu pieniędzy, obiecany etap i następny termin kontroli. Użyj cudzej historii jako pytania do warunków widocznych przy własnym zamówieniu, nie jako potwierdzonego oskarżenia. Wybrana opcja, fotografie magazynu, pomiary i datowana odpowiedź tworzą znacznie mocniejszy łańcuch niż anonimowa opinia bez pełnego finału.",
      "Pierwsza wiadomość powinna pozwolić działać bez zgadywania i może mieć pięć linii: identyfikator, dokładna opcja, obserwowalna różnica, załączony dowód oraz żądany wynik. Przykład: zamówiono M, etykieta magazynu pokazuje L, wskazane kadry dokumentują różnicę i przed widoczną datą prosisz o zwrot albo wymianę. Unikaj emocjonalnych etykiet oraz długiej historii przed faktami. Jeśli problemu nie da się wykazać, poproś najpierw o czytelną metkę, wymiar lub zbliżenie i napisz, że dowód decyduje o zwrocie. Aktualizuj jeden wątek; kilka rozmów rozrywa chronologię, powiela pracę i może prowadzić do sprzecznych instrukcji.",
      "Zapisuj osobno odebranie zgłoszenia, akceptację, fizyczny ruch produktu i widoczny refund. Odpowiedź potwierdzająca wiadomość nie oznacza automatycznie zgody sprzedawcy, wysyłki zwrotnej ani pieniędzy. Dla każdego zdarzenia zachowaj datę i numer. Zapytaj, czy wymiana utworzy nowy rekord QC oraz czy kwota wróci na saldo czy pierwotną metodę. Po usunięciu rzeczy z projektu przelicz wagę i wymiary, ale trzymaj sprawę do wyniku finansowego. Zamiennik potrzebuje nowych dat kontroli i konsolidacji; nie powinien automatycznie mieścić się w starym kalendarzu. Zwrot zmienia jednocześnie pieniądze i logistykę, więc zamknięcie tylko jednego obszaru zostawia niewyjaśnione saldo albo blokadę.",
      "Gdy minie podany czas, wyślij krótki follow-up z datą zgłoszenia, referencją akceptacji, ostatnim obiecanym krokiem i jednym potrzebnym statusem. Dołącz wcześniejsze dowody, zamiast zwiększać objętość wiadomości. Jeśli istnieje formalna ścieżka sporu, użyj jej w widocznym terminie i nie publikuj informacji płatniczych, adresu ani numeru zamówienia. Przy zakończeniu zapisz wartość brutto, potrącone opłaty, otrzymaną kwotę, miejsce i datę. Gdy rachunek różni się od zapisanych warunków, poproś o rozbicie pozycji bez automatycznego oskarżenia. Następnie popraw notatkę o sprzedawcy i produkcie, aby powód zwrotu naprawdę zmienił następny wybór, a nie zniknął po wpływie środków. Sprawdź również saldo oraz projekt paczki kilka dni później, ponieważ zamknięcie rozmowy nie zawsze oznacza równoczesną aktualizację wszystkich widoków. Jeżeli produkt został wymieniony, nadaj nowej pozycji własny termin QC, zwrotu i konsolidacji; nie używaj automatycznie zgody udzielonej dla poprzedniego egzemplarza. Zachowaj neutralny zapis dobrych i złych rezultatów. Tylko kompletna historia pozwala ocenić, czy problem wynikał z niejasnej oferty, wyboru wariantu, sprzedawcy, dowodu magazynowego czy samej obsługi sprawy. Przed kolejnym zakupem przejrzyj trzy elementy: czy wybór na stronie był jednoznaczny, czy polecenie dla kupującego dało się wykonać bez interpretacji oraz czy zdjęcia mogły pokazać ryzyko. Jeżeli odpowiedź brzmi „nie”, popraw proces przed złożeniem nowego zamówienia, zamiast liczyć, że ta sama niejasność tym razem zakończy się inaczej. W przypadku wymiany sprawdź też, czy stary i nowy numer nie są jednocześnie liczone w projekcie paczki. Taka techniczna pomyłka może sztucznie zwiększyć przewidywaną wagę albo blokować wysyłkę. Na końcu nadaj sprawie prostą kategorię: niejasna oferta, błędny wariant, widoczny defekt, brak części, preferencja albo problem proceduralny. Po kilku zwrotach kategorie pokażą, czy należy zmienić sprzedawcę, sposób czytania oferty, listę QC czy limit czasu. To praktyczny efekt dokumentacji, którego nie da sama emocjonalna ocena. Zachowaj też pierwotną wersję wiadomości i krótkie tłumaczenie, jeżeli rozmowa odbywa się w innym języku. Wielokrotne swobodne przekłady mogą zmienić kwotę, termin lub żądany rezultat, dlatego jedna stabilna wersja ułatwia późniejsze sprawdzenie całej chronologii.",
    ],
  },
};

export const reviewParityDetails: Record<LocalizedLang, string[]> = {
  de: [
    "Für eine Kaufentscheidung sollten beworbene Reichweite, Lagerzeit und Geschwindigkeit deshalb jeweils mit dem aktuellen Konto abgeglichen werden. Die von Google Play bereitgestellten Angaben zur Datensicherheit stammen laut Store vom Entwickler; sie nennen mögliche Erfassung von Standort und persönlichen Informationen sowie eine mögliche Weitergabe von Gerätekennungen. Das ist keine unabhängige Sicherheitsprüfung, sondern ein Grund, Berechtigungen, Verschlüsselungshinweis und Löschoptionen selbst zu lesen.",
    "Bewahre bei jeder Zahl einen kleinen Prüfvermerk mit Store, Land, Datum und sichtbarer Stichprobengröße auf. So wird beim nächsten Update sofort erkennbar, ob sich tatsächlich das Nutzerbild verändert hat oder nur eine andere Länderansicht geöffnet wurde. Auch eine Abweichung der angezeigten Review-Anzahl innerhalb derselben Store-Seite ist ein Grund, die Größenordnung statt einer vermeintlich dauerhaften exakten Zahl zu betonen.",
    "Positive Aussagen werden belastbarer, wenn sie einer klaren Verantwortungsstufe zugeordnet werden. Bedienung, Einkauf, Lagerbilder, Verpackung und Weiterleitung betreffen den Agenten; Herstellung, Material und Produktqualität stammen vom Drittverkäufer; Zoll und letzte Meile liegen nochmals außerhalb. Eine gute Lieferung kann mehrere funktionierende Stufen zeigen, beweist aber nicht, dass jeder Verkäufer oder jede Route gleich arbeitet.",
    "Kritische Themen sollten vor Zahlung in Stop-Regeln übersetzt werden: kein weiterer Einkauf ohne separates Versandlimit, keine Freigabe ohne brauchbare Maße und kein Warten ohne sichtbare Rückgabefrist. Damit wird eine Beschwerde nicht ungeprüft übernommen, sondern zu einer Kontrolle, die am eigenen Konto beobachtet werden kann. Fehlen Maße, Ziel oder endgültige Lösung in einer Rezension, darf daraus keine genaue Kosten- oder Häufigkeitsaussage entstehen.",
    "Der Moderationshinweis verändert die Beweiskraft der gesamten Trustpilot-Seite. Deshalb steht er direkt bei der Zusammenfassung und nicht in einer entfernten Fußnote. Er beweist weder, dass jede verbleibende Rezension falsch ist, noch dass jede Beschwerde repräsentativ ist. Zulässig ist eine vorsichtige Themenanalyse mit Hinweis auf die Plattformmaßnahme; unzulässig wäre, eine alte Bewertungsverteilung oder ausgewählte Kundenbilder als unabhängiges Qualitätssiegel zu präsentieren.",
    "Für einen fairen Test müssen Normalpreis und Rabatt getrennt gespeichert werden, damit ein außergewöhnlicher Gutschein das Ergebnis nicht künstlich verbessert. Ändere bei der Paketprüfung möglichst nur eine Variable gleichzeitig und dokumentiere Ausgangs- sowie Endmaße. Setze vor dem Kauf eine Abbruchgrenze für Gesamtbetrag, sichtbare Mängel und fehlende Antwort. Dann misst der Test nicht, ob du im Prozess immer weiterzahlst, sondern ob die zuvor festgelegten Bedingungen tatsächlich erfüllt werden.",
    "Das Urteil bleibt bewusst zeitgebunden. Neue App-Versionen, andere Routen, geänderte Bedingungen oder eine spätere Trustpilot-Moderation können einzelne Signale verändern. Eine Aktualisierung muss dieselben Quellen und Länderansichten erneut prüfen und alte Zahlen ersetzen, statt sie einfach zu ergänzen. Bis dahin ist die sinnvollste Schlussfolgerung weder Werbung noch Warnruf, sondern eine kontrollierte Probebestellung mit getrennter Kostenfreigabe und vollständig gespeicherter Beweiskette.",
  ],
  es: [
    "Estas cifras de alcance, almacenamiento y rapidez deben comprobarse en la cuenta antes de convertirlas en una expectativa. Google Play también publica declaraciones de seguridad aportadas por el desarrollador sobre posible recopilación de ubicación y datos personales y posible intercambio de identificadores. No es una auditoría independiente: conviene revisar permisos, cifrado indicado y opciones de eliminación.",
    "Acompaña cada valoración con tienda, país, fecha y tamaño visible de la muestra. Así una futura actualización puede distinguir una variación real de sentimiento de una simple apertura de otra tienda regional. Si el mismo portal muestra totales distintos en zonas diferentes de la ficha, expresa escala y fecha en lugar de fijar un número permanente para SEO.",
    "Asigna cada elogio al responsable correcto. Interfaz, compra, evidencia de almacén, empaquetado y expedición corresponden al agente; fabricación y características dependen del vendedor; aduana y última milla son otras etapas. Un resultado positivo puede indicar que varias funcionaron, pero no garantiza a todos los vendedores ni rutas.",
    "Convierte las críticas en reglas previas: no ampliar el pedido sin límite de envío separado, no aprobar sin medidas útiles y no esperar sin fecha de devolución visible. Así una experiencia ajena se transforma en una comprobación propia. Si una reseña omite destino, dimensiones o solución final, no permite deducir una tarifa ni frecuencia.",
    "El aviso de moderación cambia el peso de toda la página de Trustpilot y debe aparecer junto al resumen. No demuestra que todas las opiniones restantes sean falsas ni que cada queja sea típica. Permite analizar temas con cautela, pero no reutilizar una distribución anterior ni imágenes seleccionadas como sello independiente.",
    "Separa precio normal y descuento para que un cupón excepcional no haga parecer sostenible el siguiente pedido. Cambia una variable cada vez al probar embalaje y guarda medidas anteriores y posteriores. Define antes los límites de coste, defecto y respuesta; el ensayo debe comprobar condiciones, no justificar pagos sucesivos por haber empezado.",
    "El veredicto está fechado y debe revisarse cuando cambien versiones, rutas, políticas o el estado de moderación. Una actualización correcta vuelve a abrir las mismas fuentes y países y sustituye los datos antiguos. Mientras tanto, la conclusión responsable es probar con poco, aprobar el envío por separado y conservar toda la evidencia.",
  ],
  it: [
    "Portata, deposito e velocità pubblicizzati vanno quindi controllati nell’account prima di diventare aspettative. Google Play riporta anche dichiarazioni di sicurezza fornite dallo sviluppatore su possibile raccolta di posizione e dati personali e condivisione di identificatori. Non è un audit indipendente: l’utente deve leggere permessi, indicazione di cifratura e opzioni di cancellazione.",
    "Accompagna ogni valutazione con negozio, paese, data e dimensione visibile del campione. Un aggiornamento potrà così distinguere un vero cambiamento dal semplice passaggio a un’altra vetrina. Se la stessa pagina mostra totali diversi in punti differenti, usa ordine di grandezza e data invece di fissare una cifra SEO come permanente.",
    "Attribuisci ogni elogio alla fase corretta. Interfaccia, acquisto, prove di magazzino, imballo e inoltro riguardano l’agente; produzione e qualità dipendono dal venditore; dogana e ultimo miglio sono ulteriori passaggi. Un esito positivo può indicare che più fasi hanno funzionato, ma non garantisce tutti i venditori o tutte le rotte.",
    "Trasforma le critiche in regole preventive: niente nuovi articoli senza limite separato di spedizione, nessuna approvazione senza misure utili e nessuna attesa senza termine di reso visibile. Così un’esperienza altrui diventa un controllo verificabile. Se una recensione omette destinazione, dimensioni o soluzione finale, non sostiene una tariffa né una frequenza.",
    "L’avviso di moderazione cambia il peso dell’intera pagina Trustpilot e deve restare accanto alla sintesi. Non dimostra che ogni recensione residua sia falsa o che ogni lamentela sia tipica. Consente un’analisi prudente dei temi, ma non l’uso della vecchia distribuzione o di immagini selezionate come certificazione indipendente.",
    "Separa prezzo normale e sconto, perché un coupon eccezionale può falsare la sostenibilità del prossimo ordine. Cambia una variabile alla volta durante la prova dell’imballo e salva misure prima e dopo. Definisci in anticipo limiti di costo, difetto e risposta: il test deve verificare condizioni, non giustificare altri pagamenti solo perché il processo è iniziato.",
    "Il verdetto è datato e va riesaminato quando cambiano app, rotte, politiche o moderazione. Un aggiornamento serio riapre le stesse fonti e vetrine e sostituisce i dati precedenti. Fino ad allora la conclusione responsabile è una prova piccola, approvazione separata del trasporto e conservazione completa della documentazione.",
  ],
  pl: [
    "Reklamowany zasięg, magazyn i szybkość trzeba więc potwierdzić na koncie. Google Play publikuje również podane przez dewelopera informacje o możliwym zbieraniu lokalizacji i danych osobowych oraz udostępnianiu identyfikatorów urządzenia. Nie jest to niezależny audyt bezpieczeństwa, dlatego przed użyciem warto przeczytać uprawnienia, opis szyfrowania, zakres udostępniania i możliwość usunięcia danych.",
    "Przy każdej ocenie zachowaj sklep, kraj, datę i widoczną wielkość próby. Późniejsza aktualizacja rozpozna wtedy rzeczywistą zmianę nastroju, a nie zwykłe otwarcie innej wersji regionalnej. Jeżeli liczba opinii różni się w częściach tej samej strony, podawaj skalę i moment kontroli zamiast utrwalać pozornie dokładną liczbę jako stałe hasło SEO.",
    "Każdą pochwałę przypisz właściwej warstwie. Interfejs, zakup, zdjęcia, pakowanie i przekazanie przesyłki dotyczą agenta; produkcja, materiał i cechy rzeczy należą do sprzedawcy; odprawa i ostatnia mila to kolejne podmioty. Dobry rezultat może oznaczać, że kilka etapów zadziałało, ale nie gwarantuje wszystkich sprzedawców, produktów ani tras.",
    "Zamień krytyczne tematy w reguły przed płatnością: nie dodawaj produktów bez oddzielnego limitu transportu, nie zatwierdzaj bez użytecznych miar i nie czekaj bez widocznej daty zwrotu. Wtedy cudze doświadczenie staje się własną kontrolą. Opinia bez kraju, wymiarów, ograniczeń i zakończenia nie może dowodzić konkretnej stawki ani częstotliwości problemu.",
    "Ostrzeżenie moderacyjne zmienia wagę całej strony Trustpilot i musi być pokazane przy podsumowaniu. Nie dowodzi, że każda pozostała recenzja jest fałszywa lub każda skarga typowa. Pozwala ostrożnie analizować powtarzające się tematy, lecz nie wykorzystywać dawnego rozkładu ocen ani wybranych obrazów klientów jako niezależnego certyfikatu.",
    "Oddziel cenę zwykłą od rabatu, aby wyjątkowy kupon nie sprawił, że następne zamówienie wyda się równie opłacalne. Przy teście pakowania zmieniaj jedną rzecz naraz i zapisuj miary przed oraz po. Przed zakupem ustal granice kosztu, defektu i braku odpowiedzi; test ma sprawdzić warunki, nie usprawiedliwiać dalsze płatności tylko dlatego, że proces już się zaczął.",
    "Wniosek ma datę i wymaga ponownej kontroli po zmianie aplikacji, tras, polityk lub moderacji. Dobra aktualizacja otwiera te same źródła i kraje oraz zastępuje stare liczby, zamiast doklejać nowe. Do tego czasu odpowiedzialnym rezultatem jest mała próba, osobna akceptacja transportu, zapis pełnego kosztu oraz zachowanie dowodów od oferty po odbiór. Osobistego testu również nie należy przedstawiać jako wyniku wszystkich klientów: powinien zawierać kraj, datę, rodzaj produktu, wybraną linię i zmierzone dane. Dzięki temu czytelnik może ocenić, które elementy są porównywalne z jego sytuacją, a które pozostają jedynie indywidualnym doświadczeniem. Gdy aktualne warunki konta różnią się od publicznego opisu, pierwszeństwo ma ekran używany do decyzji. Zapis rozbieżności jest wartościowym wynikiem badania, ale nie należy go bez dodatkowych danych opisywać jako stałej praktyki dla każdego użytkownika.",
  ],
};
