import Link from "next/link";
import StructuredData from "@/components/StructuredData";
import { Arrow } from "@/components/Icons";
import { SITE_URL } from "../../data";
import { createPageMetadata } from "../../seo";
import { createBreadcrumbList, ORGANIZATION_ID, pageUrl, WEBSITE_ID } from "../../schema";
import { getArticle } from "../data";

const article = getArticle("hacoo-marked-delivered-not-received");
const path = `/articles/${article.slug}`;
const url = pageUrl(path);
const imageUrl = `${SITE_URL}${article.image.path}`;
const imageId = `${url}#primaryimage`;

export const metadata = createPageMetadata({
  title: "Hacoo Marked Delivered but Not Received: What to Do",
  description: article.description,
  path,
  alternates: { canonical: path, languages: { en: path, "x-default": path } },
  type: "article",
  image: { url: imageUrl, width: article.image.width, height: article.image.height, alt: article.image.alt },
});

export default function HacooMarkedDeliveredArticle() {
  const breadcrumb = createBreadcrumbList({ path, items: [
    { name: "Home", path: "/" },
    { name: "Articles", path: "/articles" },
    { name: article.title, path },
  ] });
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", "@id": `${url}#article`, headline: article.title, description: article.description,
      image: { "@id": imageId }, mainEntityOfPage: { "@id": `${url}#webpage` }, author: { "@type": "Organization", name: "Hacoo Pro Editorial", url: `${SITE_URL}/about/` },
      publisher: { "@id": ORGANIZATION_ID }, datePublished: article.published, dateModified: article.modified, inLanguage: "en",
      articleSection: "Hacoo support and policy research", keywords: ["Hacoo marked delivered not received", "Hacoo package says delivered", "Hacoo missing delivered parcel", "Hacoo proof of delivery"], isAccessibleForFree: true, wordCount: 1480 },
    { "@type": "ImageObject", "@id": imageId, url: imageUrl, contentUrl: imageUrl, width: article.image.width, height: article.image.height, caption: article.image.caption },
    { "@type": "WebPage", "@id": `${url}#webpage`, url, name: article.title, description: article.description, inLanguage: "en", primaryImageOfPage: { "@id": imageId }, breadcrumb: { "@id": breadcrumb["@id"] }, isPartOf: { "@id": WEBSITE_ID } },
    breadcrumb,
  ] };

  return <><StructuredData data={schema}/><article className="research-article" data-longform-article>
    <header className="article-hero research-article-hero"><div className="wrap article-head"><span className="section-label">Hacoo delivery support research</span><h1>{article.title}</h1><div className="article-meta"><span>Hacoo Pro Editorial</span><span>{article.read} read</span><span>Published August 27, 2026</span><span>Last checked {article.checkedLabel}</span></div><p>A delivered scan is a carrier event, not proof that the intended recipient has the parcel in hand. Check the exact order, address, delivery evidence and likely handoff locations before opening one traceable case.</p></div></header>
    <figure className="wrap article-cover research-cover"><img src={article.image.path} width={article.image.width} height={article.image.height} alt={article.image.alt}/><figcaption>{article.image.caption} Original graphic by Hacoo Pro; it contains no customer, order, address or tracking data.</figcaption></figure>
    <div className="wrap article-body research-article-body"><aside aria-label="Article contents"><span>In this article</span><a href="#short-answer">Short answer</a><a href="#official">Official baseline</a><a href="#first-checks">First checks</a><a href="#proof">Delivery proof</a><a href="#evidence">Evidence pack</a><a href="#route">Contact route</a><a href="#scenarios">Scenarios</a><a href="#questions">Questions</a></aside>
      <div className="article-content research-copy">
        <section id="short-answer"><span className="section-label">The short answer</span><h2>Freeze the record, search locally, then contact the party that owns the delivered event</h2><p>If a Hacoo package is marked delivered but not received, open the exact order and Logistics Details. Record the carrier, tracking number, delivered wording, location, date and displayed time. Confirm that the expected item belongs to this parcel and that the delivery address in the order is correct. Save the carrier record before it changes.</p><p>Then check ordinary handoff locations: mailbox, reception, parcel locker, porch, garage, safe place, household members and neighbours. Hacoo's current Shipping &amp; Delivery page tells users whose tracking says delivered but whose parcel is missing to report the matter to the relevant carrier using the information on the Tracking Page. It also directs further questions to Hacoo customer support. The page says Hacoo is not responsible for lost or stolen packages; this guide does not turn that statement into a promised refund or denial for a particular case.</p><div className="fact-card"><h3>Official facts checked August 27, 2026</h3><dl><div><dt>Published direction</dt><dd>Report a delivered-but-missing parcel to the relevant shipping carrier using the tracking information.</dd></div><div><dt>Support</dt><dd>Hacoo publishes a customer-support contact for further questions about the process.</dd></div><div><dt>Policy wording</dt><dd>The Shipping &amp; Delivery page states Hacoo is not responsible for lost or stolen packages.</dd></div><div><dt>No guarantee here</dt><dd>No outcome, compensation, investigation time or universal waiting period is promised by this article.</dd></div></dl></div></section>

        <section id="official"><h2>Read the official wording narrowly</h2><p>“Delivered” can describe a carrier's completion scan, a locker deposit, a reception handoff, a safe-place delivery or an address-level event. It does not reveal who physically accepted the parcel unless the carrier supplies additional proof. Start with the carrier's exact event instead of rewriting it as “stolen” or “lost.”</p><p>The official Hacoo page gives a carrier-first route when tracking states that the parcel was delivered. That makes the carrier record central evidence. The Hacoo order remains important for confirming which parcel, items and destination were involved. Use both records together.</p><p>The same page's responsibility statement is general policy wording. Do not assume it answers whether the scan is erroneous, whether the carrier can locate the parcel, whether a handoff record exists or which case-specific process applies. Ask those questions with evidence.</p></section>

        <section id="first-checks"><h2>Complete the first ten checks without exposing private data</h2><ol className="decision-list"><li><span>1</span><div><strong>Match the order.</strong><p>Confirm the item is assigned to the tracking number that shows delivered.</p></div></li><li><span>2</span><div><strong>Read the address.</strong><p>Compare country, postcode, building, apartment and recipient without posting them publicly.</p></div></li><li><span>3</span><div><strong>Record the event.</strong><p>Save the exact delivered wording, location, time and time zone when visible.</p></div></li><li><span>4</span><div><strong>Check proof.</strong><p>Look for a photograph, signature, recipient name, locker code or safe-place note.</p></div></li><li><span>5</span><div><strong>Search the property.</strong><p>Check mailbox, entrance, porch, garage, bins, side doors and designated safe places.</p></div></li><li><span>6</span><div><strong>Ask household members.</strong><p>Use a neutral question and the approximate delivery time.</p></div></li><li><span>7</span><div><strong>Check reception.</strong><p>Ask building staff, concierge or mailroom personnel using a partial tracking reference.</p></div></li><li><span>8</span><div><strong>Ask immediate neighbours.</strong><p>Do not circulate the full address, order or tracking number.</p></div></li><li><span>9</span><div><strong>Check carrier messages.</strong><p>Look for a locker, pickup point, attempted-delivery or alternate-location notice.</p></div></li><li><span>10</span><div><strong>Preserve video lawfully.</strong><p>If doorbell or building footage exists, save the relevant period without publishing neighbours or passers-by.</p></div></li></ol></section>

        <section id="proof"><h2>Evaluate proof of delivery as evidence, not a verdict</h2><p>A delivery photograph is useful when the doorway, parcel, time and address context can be connected without revealing private information. Compare visible features with the normal delivery area. A photograph of an unfamiliar door is a specific discrepancy to give the carrier. A dark or tightly cropped image may be inconclusive.</p><p>A signature needs context. Determine whether a name or relationship is shown and whether the recipient authorized somebody else. Do not accuse the named person publicly. A locker or pickup scan should be checked against access messages and the deadline for collection.</p><p>Carrier coordinates or map pins can be approximate. Treat a location mismatch as a request for investigation rather than proof of intent. The strongest record combines the carrier event, address check, delivery evidence and your local search completed at a stated time.</p><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Visible evidence</th><th>Useful conclusion</th><th>Question to ask</th></tr></thead><tbody><tr><td>Photo matches your door; parcel absent</td><td>A local removal or later handoff remains possible.</td><td>What time and placement details can the carrier confirm?</td></tr><tr><td>Photo shows another location</td><td>The delivery evidence does not match the expected property.</td><td>Can the carrier identify and recover a misdelivery?</td></tr><tr><td>Recipient or signature is unfamiliar</td><td>The recorded handoff needs verification.</td><td>Who was recorded as accepting the parcel and where?</td></tr><tr><td>Locker or pickup event appears</td><td>The parcel may not have been delivered to the door.</td><td>Which location, code and collection deadline apply?</td></tr><tr><td>No proof beyond status text</td><td>The event lacks visible supporting detail.</td><td>Can the carrier supply driver or delivery evidence?</td></tr></tbody></table></div></section>

        <section id="evidence"><h2>Build one missing-delivery evidence pack</h2><p>Keep the complete order and tracking numbers inside official support channels. Your private file should contain: order reference; expected item lines; carrier and tracking number; delivery address as entered; exact delivered event; proof-of-delivery details; local checks completed; and every case number or response.</p><p>Add a timeline with times: when the delivered event appeared, when you searched the property, when household or reception checks were completed, and when the carrier was contacted. A timeline prevents the case from becoming a collection of disconnected screenshots.</p><p>Do not alter screenshots except to make a separate redacted copy for public discussion. Keep the originals. Never post a locker code, full tracking number, telephone number, signature or address while seeking informal advice.</p></section>

        <section id="route"><h2>Contact the carrier first, then keep Hacoo support informed</h2><p>Use the carrier link or contact information reached from the official Hacoo Logistics Details view. Ask for a delivered-parcel investigation or the carrier's equivalent process. Give the exact event and one discrepancy: no parcel at the recorded location, proof showing another property, unknown recipient, or missing delivery proof.</p><p>A concise request is: “Tracking ending 5678 was marked delivered on 27 August at 14:20. The address in my Hacoo order is correct. I checked the entrance, mailbox, safe places, household and reception by 16:00. The proof shows [specific detail]. Please confirm the delivery location and open the appropriate trace.”</p><p>If the carrier provides a case number, driver response, denial or corrected event, add it to the Hacoo support request. Ask Hacoo which current process applies to the order rather than demanding an outcome not published in the checked policy. Keep one consistent narrative.</p></section>

        <section id="scenarios"><h2>Three common scenarios</h2><h3>Wrong-door photograph</h3><p>Save the original proof and note the features that do not match: door colour, number, floor or entrance. Give this discrepancy to the carrier and ask for recovery. Avoid sharing the other property image publicly.</p><h3>Reception handoff not recognized</h3><p>Ask reception with the approximate time and partial reference. If the carrier lists a name, verify it privately. Record shift changes or mailroom logs that affect the search.</p><h3>Status only, with no proof</h3><p>Confirm the address and local search, then ask the carrier for driver notes, handoff type or delivery evidence. The absence of a photo does not itself prove nondelivery, but it identifies the missing evidence.</p></section>

        <section id="questions"><h2>Questions about a Hacoo package marked delivered</h2><div className="article-faq"><details open><summary>Should I wait before reporting it?<span>+</span></summary><p>The checked official page does not publish one universal waiting period. Complete immediate local checks, preserve the event and follow the relevant carrier's current process.</p></details><details><summary>Does a delivered scan prove I received the parcel?<span>+</span></summary><p>No. It records the carrier event. Proof, handoff details and local checks establish what can be verified next.</p></details><details><summary>Should I publish the delivery photo?<span>+</span></summary><p>No. It may reveal your home, a neighbour, an address or another person's property. Share it only through an appropriate official channel.</p></details><details><summary>Does Hacoo promise a refund?<span>+</span></summary><p>No refund promise for this scenario was verified in the Shipping &amp; Delivery wording used here. Follow the case-specific instructions from the carrier and Hacoo support.</p></details></div></section>

        <section className="sources-panel"><h2>Continue with the matching internal guide</h2><ul><li><Link className="source-link" href="/articles/hacoo-tracking-not-updating/">Tracking status guide</Link> — preserve the event sequence before a delivered scan.</li><li><Link className="source-link" href="/articles/hacoo-wrong-address-evidence/">Wrong-address checklist</Link> — compare the order address and shipment state.</li><li><Link className="source-link" href="/articles/hacoo-order-missing-item-split-shipment/">Split-shipment checklist</Link> — confirm which items belong to the delivered parcel.</li><li><Link className="source-link" href="/guides/shipping-planning/">Shipping planning</Link> — keep processing, transit and local delivery separate.</li><li><Link className="source-link" href="/faq/">Hacoo Pro FAQ</Link> — understand what this independent site can and cannot verify.</li></ul></section>
        <div className="article-callout"><h2>Describe the delivered event, then test it.</h2><p>Preserve the carrier record, search every reasonable handoff location and open one evidence-led case through the official route.</p><div className="article-callout-actions"><Link className="button light" href="/articles/hacoo-tracking-not-updating/">Open tracking guide <Arrow/></Link><Link className="button quiet-dark" href="/articles/">All support articles</Link></div></div>
      </div></div>
  </article></>;
}
