import editorial from "./editorial.json";

export const locales = ["en", "de", "fr", "it", "nl", "ms"] as const;
export type Locale = (typeof locales)[number];

export const languageNames: Record<Locale, string> = {
  en: "EN", de: "DE", fr: "FR", it: "IT", nl: "NL", ms: "MS",
};

export type UiCopy = {
  nav: string[]; eyebrow: string; title: string; accent: string; intro: string;
  searchLabel: string; placeholder: string; search: string; routes: string;
  routesNote: string; finds: string; all: string; check: string; checkText: string;
  answers: string; articles: string; articleIntro: string; full: string;
  independent: string; notOfficial: string; back: string; home: string;
  productPage: string; approxPrice: string; beforeShipping: string;
  articleLabel: string; currentSignal: string; browseLabel: string; quickAnswers: string;
  updated: string; readTime: string; allArticles: string; sourceNote: string;
  routesStat: string; findsStat: string; guidesStat: string; languagesStat: string;
};

export const copy: Record<Locale, UiCopy> = {
  en: {nav:["Browse","Finds","QC Check","Answers","Guides"],eyebrow:"SUPERBUY SPREADSHEET / PRODUCT DISCOVERY",title:"THE FIND",accent:"ENGINE.",intro:"A faster route from scattered product links to a find worth inspecting.",searchLabel:"WHAT ARE YOU LOOKING FOR?",placeholder:"shoes, hoodies, jerseys...",search:"SEARCH LIVE CATALOG",routes:"Skip the spreadsheet scroll.",routesNote:"Every route opens a live product category.",finds:"33 dated finds. Zero duplicate links.",all:"See all products",check:"Run the 4-point check.",checkText:"Warehouse photos are a decision point. Approve only when the order, shape and visible construction agree.",answers:"Know before you click.",articles:"Field notes for smarter browsing.",articleIntro:"Independent, fact-checked guides built around product discovery, QC and parcel decisions.",full:"FULL CATALOG",independent:"INDEPENDENT PRODUCT DISCOVERY INDEX",notOfficial:"NOT AN OFFICIAL SUPERBUY WEBSITE",back:"BACK TO TOP",home:"HOME",productPage:"PRODUCT PAGE",approxPrice:"APPROX. USD PRICE",beforeShipping:"BEFORE SHIPPING",articleLabel:"PRACTICAL GUIDES",currentSignal:"CURRENT SIGNAL",browseLabel:"BROWSE",quickAnswers:"QUICK ANSWERS",updated:"UPDATED SEPTEMBER 7, 2026",readTime:"8–10 MIN READ",allArticles:"ALL GUIDES",sourceNote:"Fact-check note: operational details were checked against Superbuy's official User Guidance, Help Center and Fee Structure pages on September 7, 2026. Live terms, fees and route availability can change.",routesStat:"8 ROUTES",findsStat:"4 UNIQUE FINDS",guidesStat:"3 IN-DEPTH GUIDES",languagesStat:"6 LANGUAGES"},
  de: {nav:["Kategorien","Produkte","QC-Prüfung","Antworten","Ratgeber"],eyebrow:"SUPERBUY-TABELLE / PRODUKTSUCHE",title:"DIE FUND",accent:"MASCHINE.",intro:"Der schnellere Weg von verstreuten Produktlinks zu einem Fund, der eine Prüfung wert ist.",searchLabel:"WAS SUCHST DU?",placeholder:"Schuhe, Hoodies, Trikots...",search:"KATALOG DURCHSUCHEN",routes:"Nicht endlos scrollen.",routesNote:"Jede Route öffnet eine aktuelle Produktkategorie.",finds:"33 datierte Funde. Keine doppelten Links.",all:"Alle Produkte ansehen",check:"Der 4-Punkte-Check.",checkText:"Lagerfotos sind ein Entscheidungspunkt. Freigeben solltest du nur, wenn Bestellung, Form und sichtbare Verarbeitung stimmen.",answers:"Vor dem Klick wissen.",articles:"Praxiswissen für eine bessere Suche.",articleIntro:"Unabhängige, faktengeprüfte Leitfäden zu Produktsuche, QC und Paketentscheidungen.",full:"GESAMTER KATALOG",independent:"UNABHÄNGIGER PRODUKTINDEX",notOfficial:"KEINE OFFIZIELLE SUPERBUY-WEBSITE",back:"NACH OBEN",home:"STARTSEITE",productPage:"PRODUKTSEITE",approxPrice:"CA. PREIS IN USD",beforeShipping:"VOR DEM VERSAND",articleLabel:"PRAXISRATGEBER",currentSignal:"AKTUELLE FUNDE",browseLabel:"KATEGORIEN",quickAnswers:"KURZE ANTWORTEN",updated:"AKTUALISIERT AM 7. SEPTEMBER 2026",readTime:"8–10 MIN. LESEZEIT",allArticles:"ALLE RATGEBER",sourceNote:"Faktenhinweis: Die Abläufe wurden am 7. September 2026 mit der offiziellen Superbuy-Nutzeranleitung, dem Hilfezentrum und der Gebührenübersicht abgeglichen. Aktuelle Bedingungen, Gebühren und Versandlinien können sich ändern.",routesStat:"8 KATEGORIEN",findsStat:"4 EINZIGARTIGE FUNDE",guidesStat:"3 AUSFÜHRLICHE RATGEBER",languagesStat:"6 SPRACHEN"},
  fr: {nav:["Catégories","Trouvailles","Contrôle QC","Réponses","Guides"],eyebrow:"TABLEUR SUPERBUY / DÉCOUVERTE PRODUIT",title:"LE MOTEUR",accent:"DE TROUVAILLES.",intro:"Un chemin plus rapide, des liens dispersés jusqu'au produit qui mérite une inspection.",searchLabel:"QUE RECHERCHEZ-VOUS ?",placeholder:"chaussures, sweats, maillots...",search:"CHERCHER LE CATALOGUE",routes:"Évitez le défilement sans fin.",routesNote:"Chaque itinéraire ouvre une catégorie active.",finds:"33 produits datés. Aucun lien dupliqué.",all:"Voir tous les produits",check:"Le contrôle en 4 points.",checkText:"Les photos d'entrepôt servent à décider. N'approuvez que si la commande, la forme et les finitions visibles concordent.",answers:"À savoir avant de cliquer.",articles:"Guides pratiques pour mieux chercher.",articleIntro:"Guides indépendants et vérifiés sur la recherche de produits, le QC et les colis.",full:"CATALOGUE COMPLET",independent:"INDEX PRODUIT INDÉPENDANT",notOfficial:"SITE NON OFFICIEL SUPERBUY",back:"RETOUR EN HAUT",home:"ACCUEIL",productPage:"PAGE PRODUIT",approxPrice:"PRIX USD APPROX.",beforeShipping:"AVANT EXPÉDITION",articleLabel:"GUIDES PRATIQUES",currentSignal:"SÉLECTION ACTUELLE",browseLabel:"CATÉGORIES",quickAnswers:"RÉPONSES RAPIDES",updated:"MIS À JOUR LE 7 SEPTEMBRE 2026",readTime:"8–10 MIN DE LECTURE",allArticles:"TOUS LES GUIDES",sourceNote:"Note de vérification : les procédures ont été comparées le 11 août 2026 avec le guide utilisateur, le centre d'aide et la grille tarifaire officiels de Superbuy. Les conditions, frais et lignes disponibles peuvent changer.",routesStat:"8 CATÉGORIES",findsStat:"4 TROUVAILLES UNIQUES",guidesStat:"3 GUIDES COMPLETS",languagesStat:"6 LANGUES"},
  it: {nav:["Categorie","Prodotti","Controllo QC","Risposte","Guide"],eyebrow:"FOGLIO SUPERBUY / RICERCA PRODOTTI",title:"IL MOTORE",accent:"DI RICERCA.",intro:"Un percorso più rapido dai link sparsi a un prodotto che vale la pena controllare.",searchLabel:"COSA STAI CERCANDO?",placeholder:"scarpe, felpe, maglie...",search:"CERCA NEL CATALOGO",routes:"Salta lo scorrimento infinito.",routesNote:"Ogni percorso apre una categoria aggiornata.",finds:"33 prodotti datati. Nessun link duplicato.",all:"Vedi tutti i prodotti",check:"Controllo in 4 punti.",checkText:"Le foto del magazzino sono un punto decisionale. Approva solo se ordine, forma e lavorazione visibile corrispondono.",answers:"Sapere prima di cliccare.",articles:"Guide pratiche per cercare meglio.",articleIntro:"Guide indipendenti e verificate su prodotti, QC e decisioni di spedizione.",full:"CATALOGO COMPLETO",independent:"INDICE PRODOTTI INDIPENDENTE",notOfficial:"SITO SUPERBUY NON UFFICIALE",back:"TORNA SU",home:"HOME",productPage:"PAGINA PRODOTTO",approxPrice:"PREZZO USD INDICATIVO",beforeShipping:"PRIMA DELLA SPEDIZIONE",articleLabel:"GUIDE PRATICHE",currentSignal:"SELEZIONE ATTUALE",browseLabel:"CATEGORIE",quickAnswers:"RISPOSTE RAPIDE",updated:"AGGIORNATO IL 7 SETTEMBRE 2026",readTime:"8–10 MIN DI LETTURA",allArticles:"TUTTE LE GUIDE",sourceNote:"Nota di verifica: le procedure sono state confrontate il 11 agosto 2026 con la guida utente, il centro assistenza e la struttura delle commissioni ufficiali di Superbuy. Condizioni, costi e linee disponibili possono cambiare.",routesStat:"8 CATEGORIE",findsStat:"4 PRODOTTI UNICI",guidesStat:"3 GUIDE COMPLETE",languagesStat:"6 LINGUE"},
  nl: {nav:["Categorieën","Vondsten","QC-check","Antwoorden","Gidsen"],eyebrow:"SUPERBUY-SPREADSHEET / PRODUCTZOEKER",title:"DE VIND",accent:"MACHINE.",intro:"Een snellere route van losse productlinks naar een vondst die controle waard is.",searchLabel:"WAT ZOEK JE?",placeholder:"schoenen, hoodies, shirts...",search:"ZOEK IN CATALOGUS",routes:"Sla eindeloos scrollen over.",routesNote:"Elke route opent een actuele productcategorie.",finds:"33 gedateerde vondsten. Geen dubbele links.",all:"Bekijk alle producten",check:"Doe de 4-puntencheck.",checkText:"Magazijnfoto's zijn een beslismoment. Keur alleen goed wanneer bestelling, vorm en zichtbare afwerking kloppen.",answers:"Weet het voor je klikt.",articles:"Praktische gidsen voor beter zoeken.",articleIntro:"Onafhankelijke, gecontroleerde gidsen over productvondsten, QC en pakketten.",full:"VOLLEDIGE CATALOGUS",independent:"ONAFHANKELIJKE PRODUCTINDEX",notOfficial:"GEEN OFFICIËLE SUPERBUY-WEBSITE",back:"NAAR BOVEN",home:"HOME",productPage:"PRODUCTPAGINA",approxPrice:"GESCHATTE PRIJS IN USD",beforeShipping:"VOOR VERZENDING",articleLabel:"PRAKTISCHE GIDSEN",currentSignal:"HUIDIGE VONDSTEN",browseLabel:"CATEGORIEËN",quickAnswers:"SNELLE ANTWOORDEN",updated:"BIJGEWERKT OP 7 SEPTEMBER 2026",readTime:"8–10 MIN LEZEN",allArticles:"ALLE GIDSEN",sourceNote:"Factcheck: de werkwijze is op 11 augustus 2026 gecontroleerd aan de hand van Superbuy's officiële gebruikersgids, Help Center en kostenoverzicht. Actuele voorwaarden, tarieven en routes kunnen wijzigen.",routesStat:"8 CATEGORIEËN",findsStat:"4 UNIEKE VONDSTEN",guidesStat:"3 UITGEBREIDE GIDSEN",languagesStat:"6 TALEN"},
  ms: {nav:["Kategori","Pilihan","Semakan QC","Jawapan","Panduan"],eyebrow:"SPREADSHEET SUPERBUY / CARIAN PRODUK",title:"ENJIN",accent:"CARIAN.",intro:"Laluan lebih pantas daripada pautan berselerak kepada produk yang wajar diperiksa.",searchLabel:"APA YANG ANDA CARI?",placeholder:"kasut, hoodie, jersi...",search:"CARI KATALOG LANGSUNG",routes:"Elakkan tatal tanpa henti.",routesNote:"Setiap laluan membuka kategori produk semasa.",finds:"33 produk bertarikh. Tiada pautan pendua.",all:"Lihat semua produk",check:"Semakan 4 perkara.",checkText:"Foto gudang ialah titik membuat keputusan. Luluskan hanya apabila pesanan, bentuk dan mutu yang kelihatan sepadan.",answers:"Ketahui sebelum klik.",articles:"Panduan praktikal untuk carian lebih baik.",articleIntro:"Panduan bebas dan disemak fakta tentang produk, QC dan keputusan bungkusan.",full:"KATALOG PENUH",independent:"INDEKS PRODUK BEBAS",notOfficial:"BUKAN LAMAN RASMI SUPERBUY",back:"KEMBALI KE ATAS",home:"LAMAN UTAMA",productPage:"HALAMAN PRODUK",approxPrice:"ANGGARAN HARGA USD",beforeShipping:"SEBELUM PENGHANTARAN",articleLabel:"PANDUAN PRAKTIKAL",currentSignal:"PILIHAN SEMASA",browseLabel:"KATEGORI",quickAnswers:"JAWAPAN RINGKAS",updated:"DIKEMAS KINI 7 SEPTEMBER 2026",readTime:"BACAAN 8–10 MINIT",allArticles:"SEMUA PANDUAN",sourceNote:"Nota semakan fakta: proses disemak pada 11 Ogos 2026 berdasarkan Panduan Pengguna, Pusat Bantuan dan Struktur Yuran rasmi Superbuy. Syarat, yuran dan laluan semasa boleh berubah.",routesStat:"8 KATEGORI",findsStat:"4 PRODUK UNIK",guidesStat:"3 PANDUAN MENDALAM",languagesStat:"6 BAHASA"},
};

const categorySets: Record<Locale, string[][]> = {
  en:[["Shoes","Sneakers / runners / casual"],["Hoodies","Sweatshirts / knits / layers"],["T-Shirts","Graphics / basics / everyday"],["Jackets","Outerwear / seasonal pieces"],["Pants","Trousers / shorts / sets"],["Jerseys","Football / basketball"],["Headwear","Caps / beanies / more"],["Accessories","Bags / belts / small goods"]],
  de:[["Schuhe","Sneaker / Laufschuhe / Freizeit"],["Hoodies","Sweatshirts / Strick / Lagen"],["T-Shirts","Prints / Basics / Alltag"],["Jacken","Oberbekleidung / Saisonartikel"],["Hosen","Hosen / Shorts / Sets"],["Trikots","Fußball / Basketball"],["Kopfbedeckung","Caps / Mützen / mehr"],["Accessoires","Taschen / Gürtel / Kleinteile"]],
  fr:[["Chaussures","Baskets / running / détente"],["Sweats","Sweats / mailles / superpositions"],["T-shirts","Imprimés / basiques / quotidien"],["Vestes","Manteaux / pièces de saison"],["Pantalons","Pantalons / shorts / ensembles"],["Maillots","Football / basket-ball"],["Couvre-chefs","Casquettes / bonnets / plus"],["Accessoires","Sacs / ceintures / petits articles"]],
  it:[["Scarpe","Sneaker / corsa / casual"],["Felpe","Felpe / maglieria / strati"],["T-shirt","Grafiche / basic / quotidiano"],["Giacche","Capispalla / articoli stagionali"],["Pantaloni","Pantaloni / shorts / completi"],["Maglie","Calcio / basket"],["Copricapi","Cappelli / berretti / altro"],["Accessori","Borse / cinture / piccoli articoli"]],
  nl:[["Schoenen","Sneakers / runners / casual"],["Hoodies","Sweaters / breisels / laagjes"],["T-shirts","Prints / basics / dagelijks"],["Jassen","Bovenkleding / seizoensstukken"],["Broeken","Broeken / shorts / sets"],["Shirts","Voetbal / basketbal"],["Hoofddeksels","Petten / mutsen / meer"],["Accessoires","Tassen / riemen / kleine spullen"]],
  ms:[["Kasut","Sneaker / larian / kasual"],["Hoodie","Baju panas / rajut / lapisan"],["Kemeja-T","Grafik / asas / harian"],["Jaket","Pakaian luar / bermusim"],["Seluar","Seluar / pendek / set"],["Jersi","Bola sepak / bola keranjang"],["Penutup kepala","Topi / beanie / lain-lain"],["Aksesori","Beg / tali pinggang / barangan kecil"]],
};

const categoryLinks = ["https://www.cnfanshp.com/shoes/","https://www.cnfanshp.com/hoodies-sweaters/","https://www.cnfanshp.com/t-shirts/","https://www.cnfanshp.com/jackets/","https://www.cnfanshp.com/pants-shorts/","https://www.cnfanshp.com/Jersey/","https://www.cnfanshp.com/headwear/","https://www.cnfanshp.com/accessories/"];
export function categories(locale:Locale){return categorySets[locale].map((v,i)=>({number:String(i+1).padStart(2,"0"),name:v[0],detail:v[1],href:categoryLinks[i]}));}

export const qc:Record<Locale,string[][]>={
 en:[["ORDER","Match the order","Confirm color, size and selected version against your order notes."],["SHAPE","Scan the silhouette","Compare proportions, symmetry, panels and both sides of the item."],["DETAIL","Zoom into construction","Review seams, print placement, soles, hardware and visible damage."],["PROOF","Request what is missing","Ask for a close-up or measurement whenever a view is unclear."]],
 de:[["BESTELLUNG","Bestellung abgleichen","Farbe, Größe und gewählte Variante mit den Bestellnotizen vergleichen."],["FORM","Silhouette prüfen","Proportionen, Symmetrie, Einsätze und beide Seiten vergleichen."],["DETAIL","Verarbeitung vergrößern","Nähte, Druckposition, Sohlen, Beschläge und sichtbare Schäden prüfen."],["NACHWEIS","Fehlende Ansicht anfordern","Bei unklarer Ansicht ein Nahfoto oder eine Messung anfordern."]],
 fr:[["COMMANDE","Vérifier la commande","Comparer couleur, taille et variante avec les notes de commande."],["FORME","Observer la silhouette","Comparer proportions, symétrie, empiècements et deux côtés."],["DÉTAIL","Zoomer sur la fabrication","Contrôler coutures, placement, semelles, pièces et dommages visibles."],["PREUVE","Demander la vue manquante","Demander un gros plan ou une mesure dès qu'une vue reste ambiguë."]],
 it:[["ORDINE","Confronta l'ordine","Verifica colore, taglia e variante con le note dell'ordine."],["FORMA","Controlla la sagoma","Confronta proporzioni, simmetria, pannelli e i due lati."],["DETTAGLIO","Ingrandisci la lavorazione","Esamina cuciture, stampe, suole, hardware e danni visibili."],["PROVA","Richiedi ciò che manca","Chiedi un primo piano o una misura quando una vista non è chiara."]],
 nl:[["BESTELLING","Vergelijk de bestelling","Controleer kleur, maat en gekozen versie met je bestelnotities."],["VORM","Bekijk het silhouet","Vergelijk verhoudingen, symmetrie, panelen en beide zijden."],["DETAIL","Zoom in op afwerking","Bekijk naden, prints, zolen, hardware en zichtbare schade."],["BEWIJS","Vraag wat ontbreekt","Vraag om een close-up of meting wanneer een beeld onduidelijk is."]],
 ms:[["PESANAN","Padankan pesanan","Sahkan warna, saiz dan versi pilihan dengan nota pesanan."],["BENTUK","Periksa siluet","Bandingkan perkadaran, simetri, panel dan kedua-dua sisi produk."],["BUTIRAN","Zum mutu binaan","Semak jahitan, kedudukan cetakan, tapak, perkakasan dan kerosakan."],["BUKTI","Minta paparan yang tiada","Minta gambar dekat atau ukuran apabila paparan tidak jelas."]],
};

export const faqs:Record<Locale,[string,string][]>= {
 en:[["What is a Superbuy spreadsheet?","An independent directory of product links grouped by category. It helps with discovery; the current product page remains the source of truth for price, options and availability."],["What does Superbuy officially provide at the warehouse?","Superbuy's User Guidance describes warehouse inspection, photos for review and 90 days of free storage. Its current fee page lists detailed photos and re-inspection as optional paid services, so ask for a targeted view when the standard evidence cannot answer a specific question."],["Are the displayed prices final?","No. CNY amounts are dated source-price references. Check the exact live variant price, China domestic delivery, any purchasing fee that applies to the source platform, optional services and international parcel cost before ordering."],["How is international shipping charged?","Superbuy says the deposit estimate depends on destination, selected line and estimated parcel data. The logistics provider's verified size and weight determine the final charge; overpayment is refunded or an underpayment may be collected after reconciliation."],["Is ordinary purchasing always fee-free?","Superbuy currently lists standard purchasing from Taobao, Tmall, JD.com and 1688 as free of purchasing service fees. Second-hand, unlisted and special purchasing services can use flat or percentage fees, so check the live fee structure for the exact source."],["Does 90-day free storage mean a 90-day return window?","No. Warehouse storage and seller after-sales are separate clocks. Superbuy's current fee page says storage charges begin after the free period and gives a maximum storage policy; return eligibility depends on the order, seller, item type and live after-sales status."],["Can every warehouse item use every shipping line?","No. Superbuy says some items are restricted to certain delivery methods. Route eligibility depends on destination, item classification and current carrier rules, so confirm batteries, liquids, powders, magnets and other sensitive goods before buying when the route is critical."],["Is this the official Superbuy website?","No. This is an independent informational product directory and is not affiliated with or endorsed by Superbuy."]],
 de:[["Was ist eine Superbuy-Tabelle?","Ein unabhängiges, nach Kategorien sortiertes Verzeichnis von Produktlinks. Es erleichtert die Suche; für Preis, Varianten und Verfügbarkeit zählt die aktuelle Produktseite."],["Was bietet Superbuy offiziell im Lager?","Die Nutzeranleitung nennt Lagerprüfung, Fotos zur Kontrolle und 90 Tage kostenlose Lagerung. Detailfotos und Nachprüfung stehen in der aktuellen Gebührenübersicht als optionale Leistungen; bei einer konkreten Unsicherheit sollte die Anfrage deshalb gezielt sein."],["Sind die angezeigten Preise endgültig?","Nein. USD-Beträge dienen nur zur Orientierung. Prüfe die exakte Live-Variante, Inlandversand, mögliche plattformabhängige Einkaufsgebühren, Zusatzleistungen und internationale Fracht."],["Wie werden internationale Versandkosten berechnet?","Die Vorauszahlung hängt laut Superbuy von Ziel, Linie und geschätzten Paketdaten ab. Bestätigte Maße und Gewicht bestimmen den Endpreis; Überzahlungen werden erstattet, Unterzahlungen können nachberechnet werden."],["Ist der normale Einkauf immer gebührenfrei?","Superbuy nennt den Standardkauf bei Taobao, Tmall, JD.com und 1688 derzeit gebührenfrei. Für Secondhand-, nicht gelistete oder besondere Einkaufsdienste können Pauschalen oder Prozentgebühren gelten."],["Sind 90 Tage Lagerung zugleich 90 Tage Rückgaberecht?","Nein. Lagerfrist und Verkäufer-Nachverkauf sind getrennt. Nach der kostenlosen Lagerzeit können Lagerkosten entstehen; Rückgabe hängt vom Auftrag, Verkäufer, Produkttyp und aktuellen After-Sales-Status ab."],["Kann jeder Lagerartikel über jede Linie versendet werden?","Nein. Laut Superbuy sind manche Artikel auf bestimmte Versandarten beschränkt. Ziel, Warenklassifizierung und aktuelle Carrier-Regeln entscheiden; sensible Waren sollten vor dem Kauf geprüft werden."],["Ist dies die offizielle Superbuy-Website?","Nein. Dies ist ein unabhängiges Informations- und Produktverzeichnis ohne Verbindung oder Empfehlung durch Superbuy."]],
 fr:[["Qu'est-ce qu'un tableur Superbuy ?","Un répertoire indépendant de liens produits classés par catégorie. Il facilite la découverte ; la page produit actuelle reste la référence pour le prix, les options et la disponibilité."],["Que fournit officiellement Superbuy à l'entrepôt ?","Le guide officiel décrit l'inspection, les photos de contrôle et 90 jours de stockage gratuit. La grille actuelle présente les photos détaillées et la réinspection comme services optionnels : demandez une preuve ciblée si un point reste incertain."],["Les prix affichés sont-ils définitifs ?","Non. Les montants USD sont indicatifs. Vérifiez la variante active, la livraison chinoise, les éventuels frais liés à la plateforme, les services choisis et le transport international."],["Comment le transport international est-il facturé ?","L'acompte dépend de la destination, de la ligne et des données estimées. Le poids et les dimensions vérifiés fixent le total ; un trop-perçu est remboursé et un solde insuffisant peut être réclamé."],["L'achat standard est-il toujours sans frais ?","Superbuy indique actuellement zéro frais d'achat standard pour Taobao, Tmall, JD.com et 1688. Les achats d'occasion, plateformes non listées ou services spéciaux peuvent être facturés différemment."],["Les 90 jours de stockage sont-ils un délai de retour ?","Non. Stockage et après-vente du vendeur suivent deux délais distincts. Des frais peuvent commencer après la période gratuite ; l'éligibilité au retour dépend de la commande et du statut après-vente actif."],["Tous les articles peuvent-ils utiliser toutes les lignes ?","Non. Certains articles sont limités à certaines méthodes. Destination, classification et règles actuelles du transporteur comptent ; vérifiez les produits sensibles avant achat."],["S'agit-il du site officiel Superbuy ?","Non. C'est un répertoire informatif indépendant, sans affiliation ni approbation de Superbuy."]],
 it:[["Cos'è uno spreadsheet Superbuy?","Un elenco indipendente di link a prodotti divisi per categoria. Aiuta la scoperta; la pagina prodotto attuale resta la fonte per prezzo, varianti e disponibilità."],["Cosa offre ufficialmente Superbuy in magazzino?","La guida descrive ispezione, foto di controllo e 90 giorni di deposito gratuito. Foto dettagliate e nuova ispezione sono servizi opzionali nella struttura costi attuale: chiedi una prova mirata quando serve."],["I prezzi mostrati sono definitivi?","No. Gli importi USD sono indicativi. Controlla variante attiva, consegna nazionale, eventuale commissione della piattaforma, servizi scelti e spedizione internazionale."],["Come viene calcolata la spedizione internazionale?","Il deposito dipende da destinazione, linea e dati stimati. Peso e dimensioni verificati fissano il totale; un'eccedenza viene restituita e un importo insufficiente può essere richiesto."],["L'acquisto standard è sempre gratuito?","Superbuy indica attualmente zero commissioni standard per Taobao, Tmall, JD.com e 1688. Usato, piattaforme non elencate o servizi speciali possono avere tariffe diverse."],["I 90 giorni sono anche il termine di reso?","No. Deposito e assistenza del venditore hanno scadenze separate. Dopo il periodo gratuito possono iniziare costi di deposito; il reso dipende dall'ordine e dallo stato after-sales disponibile."],["Ogni articolo può usare ogni linea?","No. Alcuni prodotti sono limitati a determinati metodi. Destinazione, classificazione e regole attuali del vettore contano; verifica gli articoli sensibili prima dell'acquisto."],["Questo è il sito ufficiale Superbuy?","No. È un indice informativo indipendente, non affiliato né approvato da Superbuy."]],
 nl:[["Wat is een Superbuy-spreadsheet?","Een onafhankelijke map met productlinks per categorie. Het versnelt zoeken; de actuele productpagina blijft leidend voor prijs, opties en voorraad."],["Wat biedt Superbuy officieel in het magazijn?","De gebruikersgids beschrijft inspectie, controlefoto's en 90 dagen gratis opslag. Detailfoto's en herinspectie staan als optionele diensten in het actuele kostenoverzicht; vraag gericht bewijs bij twijfel."],["Zijn de getoonde prijzen definitief?","Nee. USD-bedragen zijn indicatief. Controleer de exacte live variant, binnenlandse levering, eventuele platformkosten, gekozen diensten en internationale pakketkosten."],["Hoe worden internationale verzendkosten berekend?","Het voorschot hangt af van bestemming, route en geschatte gegevens. Geverifieerde afmetingen en gewicht bepalen het totaal; te veel betaald wordt teruggestort en een tekort kan worden geïnd."],["Is standaard inkopen altijd kosteloos?","Superbuy noemt standaard inkopen via Taobao, Tmall, JD.com en 1688 momenteel zonder inkoopkosten. Tweedehands, niet-genoemde platforms en speciale diensten kunnen andere tarieven hebben."],["Is 90 dagen opslag ook 90 dagen retourrecht?","Nee. Opslag en verkopersnazorg hebben aparte termijnen. Na de gratis periode kunnen opslagkosten beginnen; retour hangt af van de bestelling en de actieve after-salesstatus."],["Kan elk artikel via elke route worden verzonden?","Nee. Sommige artikelen zijn beperkt tot bepaalde methoden. Bestemming, classificatie en actuele vervoerdersregels bepalen de keuze; controleer gevoelige goederen vóór aankoop."],["Is dit de officiële Superbuy-website?","Nee. Dit is een onafhankelijke informatie- en productindex zonder band met of goedkeuring van Superbuy."]],
 ms:[["Apakah spreadsheet Superbuy?","Direktori bebas pautan produk mengikut kategori. Ia membantu penemuan; halaman produk semasa kekal sebagai sumber sebenar untuk harga, pilihan dan ketersediaan."],["Apakah yang Superbuy sediakan secara rasmi di gudang?","Panduan rasmi menerangkan pemeriksaan, foto semakan dan storan percuma 90 hari. Foto terperinci dan pemeriksaan semula disenaraikan sebagai perkhidmatan pilihan; minta bukti khusus apabila perlu."],["Adakah harga yang dipaparkan muktamad?","Tidak. Nilai USD ialah rujukan. Semak varian langsung, penghantaran China, yuran platform jika ada, perkhidmatan pilihan dan kos bungkusan antarabangsa."],["Bagaimanakah penghantaran antarabangsa dicaj?","Deposit bergantung pada destinasi, laluan dan data anggaran. Berat serta saiz yang disahkan menentukan jumlah; lebihan dipulangkan dan kekurangan mungkin perlu dibayar."],["Adakah pembelian biasa sentiasa tanpa yuran?","Superbuy kini menyatakan pembelian standard Taobao, Tmall, JD.com dan 1688 tanpa yuran pembelian. Platform terpakai, tidak tersenarai atau perkhidmatan khas boleh mempunyai caj lain."],["Adakah storan 90 hari juga tempoh pulangan?","Tidak. Storan dan selepas jualan penjual ialah tempoh berasingan. Caj storan boleh bermula selepas tempoh percuma; pulangan bergantung pada pesanan dan status selepas jualan semasa."],["Bolehkah semua item menggunakan semua laluan?","Tidak. Sesetengah item terhad kepada kaedah tertentu. Destinasi, klasifikasi dan peraturan pembawa semasa menentukan pilihan; semak barangan sensitif sebelum membeli."],["Adakah ini laman rasmi Superbuy?","Tidak. Ini direktori maklumat bebas dan tidak mempunyai hubungan atau pengesahan daripada Superbuy."]],
};

export type ArticleCard={slug:string;tag:Record<Locale,string>;title:Record<Locale,string>;description:Record<Locale,string>;date:string;modified:string;category:string;image:string};
type Body={dek:string;sections:[string,string][]};
export const articles=editorial as unknown as (ArticleCard & {bodies:Record<Locale,Body>})[];
export function articleBody(locale:Locale,slug:string):Body {
 const article=articles.find(item=>item.slug===slug);
 if(!article?.bodies[locale])throw new Error(`Missing complete article: ${locale}/${slug}`);
 return article.bodies[locale];
}

export const sectionTitles:Record<Locale,Record<string,string>>={
 en:{browse:"Browse Product Categories",finds:"Independent Product Finds","qc-check":"QC Photo Check",answers:"Superbuy Spreadsheet Answers",articles:"Superbuy Guides: Finds, QC & Shipping"},
 de:{browse:"Produktkategorien durchsuchen",finds:"Unabhängige Produktfunde","qc-check":"QC-Fotoprüfung",answers:"Antworten zur Superbuy-Tabelle",articles:"Superbuy-Ratgeber: Produktauswahl, QC und Versand"},
 fr:{browse:"Parcourir les catégories",finds:"Sélection de produits indépendante","qc-check":"Contrôle des photos QC",answers:"Réponses sur le tableur Superbuy",articles:"Guides Superbuy : produits, QC et expédition"},
 it:{browse:"Esplora le categorie",finds:"Prodotti selezionati in modo indipendente","qc-check":"Controllo foto QC",answers:"Risposte sullo spreadsheet Superbuy",articles:"Guide Superbuy: prodotti, QC e spedizione"},
 nl:{browse:"Productcategorieën bekijken",finds:"Onafhankelijke productvondsten","qc-check":"QC-fotocontrole",answers:"Antwoorden over de Superbuy-spreadsheet",articles:"Superbuy-gidsen: producten, QC en verzending"},
 ms:{browse:"Lihat kategori produk",finds:"Pilihan produk bebas","qc-check":"Semakan foto QC",answers:"Jawapan spreadsheet Superbuy",articles:"Panduan Superbuy: produk, QC dan penghantaran"},
};
