import Link from "next/link";
import {articleBody, articles, categories, copy, faqs, languageNames, locales, qc, sectionTitles, type Locale} from "./content";
import {categoryLabel, productCopy, products, type CatalogProduct} from "./catalog";
import {trustNav, trustPage, type TrustSlug} from "./trust";
export {locales, type Locale} from "./content";

export function localPath(locale: Locale, path="") { const clean=path.replace(/^\/+|\/+$/g,""); return locale === "en" ? (clean?`/${clean}/`:"/") : (clean?`/${locale}/${clean}/`:`/${locale}/`); }
const researchLabels:Record<Locale,{sections:string;words:string;sources:string;read:string;checked:string;guidance:string;fees:string;help:string}>={
  en:{sections:"SECTIONS",words:"WORDS",sources:"OFFICIAL SOURCES",read:"READ FACT-CHECKED GUIDE",checked:"OFFICIAL SOURCES CHECKED",guidance:"User Guidance",fees:"Fee Structure",help:"Help Center"},
  de:{sections:"ABSCHNITTE",words:"WÖRTER",sources:"OFFIZIELLE QUELLEN",read:"GEPRÜFTEN RATGEBER LESEN",checked:"OFFIZIELLE QUELLEN GEPRÜFT",guidance:"Nutzeranleitung",fees:"Gebührenübersicht",help:"Hilfezentrum"},
  fr:{sections:"SECTIONS",words:"MOTS",sources:"SOURCES OFFICIELLES",read:"LIRE LE GUIDE VÉRIFIÉ",checked:"SOURCES OFFICIELLES VÉRIFIÉES",guidance:"Guide utilisateur",fees:"Grille tarifaire",help:"Centre d’aide"},
  it:{sections:"SEZIONI",words:"PAROLE",sources:"FONTI UFFICIALI",read:"LEGGI LA GUIDA VERIFICATA",checked:"FONTI UFFICIALI CONTROLLATE",guidance:"Guida utente",fees:"Struttura costi",help:"Centro assistenza"},
  nl:{sections:"SECTIES",words:"WOORDEN",sources:"OFFICIËLE BRONNEN",read:"LEES DE GECONTROLEERDE GIDS",checked:"OFFICIËLE BRONNEN GECONTROLEERD",guidance:"Gebruikersgids",fees:"Kostenoverzicht",help:"Helpcentrum"},
  ms:{sections:"BAHAGIAN",words:"PERKATAAN",sources:"SUMBER RASMI",read:"BACA PANDUAN DISEMAK",checked:"SUMBER RASMI DISEMAK",guidance:"Panduan Pengguna",fees:"Struktur Yuran",help:"Pusat Bantuan"},
};

function Header({locale, section=""}:{locale:Locale;section?:string}) {
  const c=copy[locale];
  const links=[["browse",c.nav[0]],["finds",c.nav[1]],["qc-check",c.nav[2]],["answers",c.nav[3]],["articles",c.nav[4]]];
  return <header className="nav">
    <Link className="brand" href={localPath(locale)} aria-label="Superbuy Spreadsheet home"><img src="/superbuy.png" alt="Super" width="726" height="142" /></Link>
    <nav aria-label="Main navigation">{links.map(([href,label])=><Link href={localPath(locale,href)} key={href}>{label}</Link>)}</nav>
    <details className="language"><summary>{languageNames[locale]} <span>⌄</span></summary><div>{locales.map(lang=><Link className={lang===locale?"active":""} href={localPath(lang,section)} key={lang} hrefLang={lang}>{languageNames[lang]}</Link>)}</div></details>
    <a className="nav-cta" href="https://www.cnfanshp.com/AllProducts/" target="_blank" rel="noopener sponsored">{c.full} <span>↗</span></a>
  </header>;
}

function Footer({locale}:{locale:Locale}) { const c=copy[locale]; return <footer><img src="/superbuy.png" alt="Super" width="726" height="142"/><p>{c.independent}<br/>{c.notOfficial}</p><nav aria-label="Trust and policy pages">{(Object.keys(trustNav[locale]) as TrustSlug[]).map(slug=><Link href={localPath(locale,slug)} key={slug}>{trustNav[locale][slug]}</Link>)}</nav><a href="#top">{c.back} ↑</a></footer>; }

function PartnerNotice({locale}:{locale:Locale}){return <p className="partner-notice"><b>{productCopy[locale].partner}:</b> {productCopy[locale].partnerNote}</p>}

function RouteBoard({locale}:{locale:Locale}){return <><PartnerNotice locale={locale}/><div className="route-board">{categories(locale).map(({number,name,detail,href})=><a href={href} target="_blank" rel="noopener sponsored" className="route" key={name}><span className="route-no">{number}</span><i/><strong>{name}</strong><small>{detail}</small><b>↗</b></a>)}</div></>}

function ProductBoard({locale,all=false}:{locale:Locale;all?:boolean}){const pc=productCopy[locale];const shown=all?products:products.slice(0,4);return <div className={`receipts ${all?"catalog-receipts":""}`}>{shown.map((p,i)=><Link className={`receipt ${p.tone}`} href={localPath(locale,`products/${p.slug}`)} key={p.id}><div className="receipt-top"><span>FIND {String(i+1).padStart(3,"0")}</span><span>{pc.details} ↗</span></div><div className="product-photo"><img src={p.image} alt={p.name} loading="lazy" width="700" height="700"/></div><div className="receipt-name"><small>{categoryLabel(locale,p.category)}</small><h3>{p.name}</h3></div><div className="price"><span>{pc.sourcePrice}</span><b>¥{p.priceCny}</b></div><div className="barcode" aria-hidden="true"/></Link>)}</div>}

function QcBoard({locale}:{locale:Locale}){return <ol className="check-track">{qc[locale].map(([tag,title,text],i)=><li key={tag}><span>{String(i+1).padStart(2,"0")}</span><b>{tag}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol>}

function AnswerBoard({locale}:{locale:Locale}){return <div className="answer-list">{faqs[locale].map(([question,answer],i)=><details open={i===0} key={question}><summary><span><small>{String(i+1).padStart(2,"0")} / FAQ</small>{question}</span><b>+</b></summary><p>{answer}</p></details>)}</div>}

function countWords(value:string){return value.trim().split(/\s+/).filter(Boolean).length}
const editorialUi:Record<Locale,{toc:string;minutes:string;finds:string;updated:string;note:string;all:string}>={
 en:{toc:"In this guide",minutes:"min read",finds:"Explore related finds",updated:"UPDATED",note:"Process references reviewed on 6 October 2026: Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure and Freight Estimator. Service availability, account options and charges can change. Product records are dated discovery references, not authentication or delivery guarantees.",all:"View all guides"},
 de:{toc:"In diesem Ratgeber",minutes:"Min. Lesezeit",finds:"Passende Produkte entdecken",updated:"AKTUALISIERT",note:"Prozessquellen geprüft am 6. Oktober 2026: Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure und Freight Estimator. Verfügbarkeit, Kontooptionen und Gebühren können sich ändern. Produktdaten sind datierte Orientierungshilfen, keine Echtheits- oder Liefergarantien.",all:"Alle Ratgeber ansehen"},
 fr:{toc:"Dans ce guide",minutes:"min de lecture",finds:"Découvrir les produits associés",updated:"MIS À JOUR",note:"Références sur les procédures consultées le 6 octobre 2026 : Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure et Freight Estimator. Services, options et frais peuvent changer. Les fiches produits sont des repères datés, sans garantie d’authenticité ni de livraison.",all:"Voir tous les guides"},
 it:{toc:"In questa guida",minutes:"min di lettura",finds:"Scopri i prodotti correlati",updated:"AGGIORNATO",note:"Fonti sulle procedure consultate il 6 ottobre 2026: Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure e Freight Estimator. Servizi, opzioni e costi possono cambiare. Le schede prodotto sono riferimenti datati, senza garanzie di autenticità o consegna.",all:"Vedi tutte le guide"},
 nl:{toc:"In deze gids",minutes:"min leestijd",finds:"Bekijk gerelateerde producten",updated:"BIJGEWERKT",note:"Procesbronnen gecontroleerd op 6 oktober 2026: Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure en Freight Estimator. Diensten, accountopties en kosten kunnen veranderen. Productgegevens zijn gedateerde referenties, geen garanties voor authenticiteit of levering.",all:"Bekijk alle gidsen"},
 ms:{toc:"Dalam panduan ini",minutes:"minit bacaan",finds:"Terokai produk berkaitan",updated:"DIKEMAS KINI",note:"Rujukan proses disemak pada 6 Oktober 2026: Superbuy Homepage, Shopping Agent Guide, Parcel Forwarding Guide, Fee Structure dan Freight Estimator. Perkhidmatan, pilihan akaun dan caj boleh berubah. Rekod produk ialah rujukan bertarikh, bukan jaminan ketulenan atau penghantaran.",all:"Lihat semua panduan"}
};
function ArticleCards({locale,limit}:{locale:Locale;limit?:number}){const l=researchLabels[locale];return <div className="article-grid">{articles.slice(0,limit).map((a,i)=>{const body=articleBody(locale,a.slug);const words=countWords([body.dek,...body.sections.flat()].join(" "));return <Link href={localPath(locale,`articles/${a.slug}`)} className="article-card" key={a.slug}><span>{String(i+1).padStart(2,"0")} / {a.tag[locale]}</span><h3>{a.title[locale]}</h3><p>{a.description[locale]}</p><div className="article-proof"><span>{Math.ceil(words/200)} {editorialUi[locale].minutes}</span><span>{body.sections.length} {l.sections.toLowerCase()}</span></div><b>{l.read} ↗</b></Link>})}</div>}

function FaqSchema({locale}:{locale:Locale}){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs[locale].map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>}

export function HomePage({locale}:{locale:Locale}) { const c=copy[locale]; return <main id="top"><FaqSchema locale={locale}/><Header locale={locale}/>
  <section className="engine"><div className="orbit orbit-one">{c.independent}</div><div className="orbit orbit-two">2026</div><p className="eyebrow"><span/> {c.eyebrow}</p><h1><span className="seo-keyword">SUPERBUY SPREADSHEET</span>{c.title}<br/><em>{c.accent}</em></h1><p className="engine-copy">{c.intro}</p><form className="search-machine" action="https://www.cnfanshp.com/search.html" method="get" target="_blank"><input type="hidden" name="channelid" value="2"/><input type="hidden" name="method" value="1"/><label htmlFor="search">{c.searchLabel}</label><input id="search" name="keywords" placeholder={c.placeholder} required/><button type="submit"><span>{c.search}</span><b>↗</b></button></form><PartnerNotice locale={locale}/><div className="engine-foot"><p>{c.routesStat}</p><p>{products.length} {({en:"FINDS",de:"PRODUKTE",fr:"PRODUITS",it:"PRODOTTI",nl:"PRODUCTEN",ms:"PRODUK"})[locale]}</p><p>{c.guidesStat.replace(/^\d+/,String(articles.length))}</p><p>{c.languagesStat}</p></div></section>
  <section className="routes"><div className="route-heading"><p>01 / {c.browseLabel}</p><h2>{c.routes}</h2><span>{c.routesNote}</span></div><RouteBoard locale={locale}/></section>
  <section className="finds"><div className="finds-title"><p>02 / {c.currentSignal}</p><h2>{c.finds}</h2><Link href={localPath(locale,"finds")}>{c.all} ↗</Link></div><ProductBoard locale={locale}/></section>
  <section className="check"><div className="check-intro"><p>03 / {c.beforeShipping}</p><h2>{c.check}</h2><p className="check-copy">{c.checkText}</p></div><QcBoard locale={locale}/></section>
  <section className="articles-preview"><div className="article-heading"><p>04 / {c.articleLabel}</p><h2>{c.articles}</h2><span>{c.articleIntro}</span></div><ArticleCards locale={locale} limit={4}/><Link className="all-guides" href={localPath(locale,"articles")}>{editorialUi[locale].all} ({articles.length}) →</Link></section>
  <section className="answers"><div className="answers-title"><p>05 / {c.quickAnswers}</p><h2>{c.answers}</h2></div><AnswerBoard locale={locale}/></section><Footer locale={locale}/></main> }

export function SectionPage({locale,section}:{locale:Locale;section:string}) { const c=copy[locale]; const title=sectionTitles[locale][section]||sectionTitles[locale].browse; return <main id="top">{section==="answers"&&<FaqSchema locale={locale}/>}<Header locale={locale} section={section}/><section className="inner-hero"><p>{c.eyebrow} / {section.replace("-"," ").toUpperCase()}</p><h1>{title}</h1><Link href={localPath(locale)}>← {c.home}</Link></section>{section==="browse"&&<section className="routes inner"><RouteBoard locale={locale}/></section>}{section==="finds"&&<section className="finds inner"><PartnerNotice locale={locale}/><ProductBoard locale={locale} all/></section>}{section==="qc-check"&&<section className="check inner"><div className="check-intro"><p>{c.beforeShipping}</p><h2>{c.check}</h2><p className="check-copy">{c.checkText}</p></div><QcBoard locale={locale}/></section>}{section==="answers"&&<section className="answers inner"><div className="answers-title"><h2>{c.answers}</h2></div><AnswerBoard locale={locale}/></section>}{section==="articles"&&<section className="articles-preview inner"><ArticleCards locale={locale}/></section>}<Footer locale={locale}/></main> }

function articleParagraphs(text:string,locale:Locale){
 if(text.includes("\n\n"))return text.split(/\n\n+/);
 const sentences=Array.from(new Intl.Segmenter(locale,{granularity:"sentence"}).segment(text),part=>part.segment);
 const paragraphs:string[]=[];let paragraph="";
 for(const sentence of sentences){paragraph+=sentence;if(countWords(paragraph)>=65){paragraphs.push(paragraph.trim());paragraph="";}}
 if(paragraph.trim())paragraphs.push(paragraph.trim());return paragraphs;
}

export function ArticlePage({locale,slug}:{locale:Locale;slug:string}) {
 const card=articles.find(a=>a.slug===slug)!;
 const a=articleBody(locale,card.slug),c=copy[locale],ui=editorialUi[locale];
 const words=countWords([a.dek,...a.sections.flat()].join(" "));
 const url=`https://superbuys.pro${localPath(locale,`articles/${card.slug}`)}`;
 const articleSchema={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:card.title[locale],description:card.description[locale],datePublished:card.date,dateModified:card.modified,inLanguage:locale,wordCount:words,...(card.image?{image:`https://superbuys.pro${card.image}`} : {}),author:{"@type":"Organization",name:"Superbuy Product Index"},mainEntityOfPage:url},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:c.home,item:`https://superbuys.pro${localPath(locale)}`},{"@type":"ListItem",position:2,name:c.allArticles,item:`https://superbuys.pro${localPath(locale,"articles")}`},{"@type":"ListItem",position:3,name:card.title[locale],item:url}]}]};
 const nextGuides:Record<string,string[]>={
  "superbuy-shoes-spreadsheet-sizing-qc":["superbuy-qc-photos-checklist","superbuy-clothing-spreadsheet-fit-comparison","superbuy-shipping-cost-explained"],
  "superbuy-clothing-spreadsheet-fit-comparison":["superbuy-shoes-spreadsheet-sizing-qc","superbuy-jersey-spreadsheet-size-print-checks","superbuy-qc-photos-checklist"],
  "superbuy-jersey-spreadsheet-size-print-checks":["superbuy-clothing-spreadsheet-fit-comparison","superbuy-qc-photos-checklist","superbuy-first-order-product-link-to-warehouse"],
  "how-to-use-superbuy-spreadsheet":["superbuy-shoes-spreadsheet-sizing-qc","superbuy-clothing-spreadsheet-fit-comparison","superbuy-jersey-spreadsheet-size-print-checks"],
  "superbuy-qc-photos-checklist":["superbuy-shoes-spreadsheet-sizing-qc","superbuy-jersey-spreadsheet-size-print-checks","superbuy-warehouse-storage-qc-guide"],
  "superbuy-warehouse-storage-qc-guide":["superbuy-qc-photos-checklist","superbuy-shipping-expert-packing-requests","superbuy-shipping-cost-explained"]
 };
 const relevantSlugs=nextGuides[slug]||(card.category==="shipping"?["superbuy-shipping-cost-explained","superbuy-shipping-expert-packing-requests","superbuy-fees-shopping-agent-vs-parcel-forwarding","superbuy-warehouse-storage-qc-guide"]:["superbuy-shoes-spreadsheet-sizing-qc","superbuy-warehouse-storage-qc-guide","superbuy-first-order-product-link-to-warehouse","how-to-use-superbuy-spreadsheet"]);
 const related=[...relevantSlugs.map(slug=>articles.find(item=>item.slug===slug)!),...articles].filter((item,i,list)=>item.slug!==card.slug&&list.findIndex(x=>x.slug===item.slug)===i).slice(0,3);
 const relatedProducts=card.category==="hoodies"?["5974","5976","5981"].map(id=>products.find(p=>p.id===id)!):products.filter(p=>card.category==="general"||card.category==="shipping"||p.category===card.category).slice(0,3);
 return <main id="top"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><Header locale={locale} section={`articles/${card.slug}`}/><article className="article-page"><p>{c.eyebrow} / {card.tag[locale]}</p><h1>{card.title[locale]}</h1><div className="article-meta"><span>{ui.updated} <time dateTime={card.modified}>{card.modified}</time></span><span>{Math.ceil(words/200)} {ui.minutes}</span></div><p className="article-dek">{a.dek}</p>{card.image==="/first-order-workflow.svg"&&<figure className="article-workflow"><img src={card.image} alt={card.title[locale]} width="1200" height="630"/></figure>}<nav className="article-toc" aria-label={ui.toc}><h2>{ui.toc}</h2><ol>{a.sections.map(([h],i)=><li key={i}><a href={`#section-${i+1}`}>{h.replace(/^\d+[.)]\s*/,"")}</a></li>)}</ol></nav>{a.sections.map(([h,t],i)=><section id={`section-${i+1}`} key={i}><h2>{h}</h2><div className="article-prose">{articleParagraphs(t,locale).map((paragraph,j)=><p key={j}>{paragraph}</p>)}</div></section>)}<nav className="related-guides" aria-label={ui.all}><b>{ui.all}</b>{related.map(item=><Link href={localPath(locale,`articles/${item.slug}`)} key={item.slug}>{item.title[locale]} →</Link>)}</nav><div className="article-products"><h2>{ui.finds}</h2><div>{relatedProducts.map(p=><Link href={localPath(locale,`products/${p.slug}`)} key={p.id}><img src={p.image} width="300" height="300" loading="lazy" alt={p.name}/><strong>{p.name}</strong><span>{categoryLabel(locale,p.category)} →</span></Link>)}</div></div><aside>{ui.note}<br/><br/>{c.notOfficial}</aside><Link className="article-back" href={localPath(locale,"articles")}>← {c.allArticles}</Link></article><Footer locale={locale}/></main>
}

export function ProductPage({locale,product}:{locale:Locale;product:CatalogProduct}){const pc=productCopy[locale];const url=`https://superbuys.pro${localPath(locale,`products/${product.slug}`)}`;const schema=[{"@context":"https://schema.org","@type":"Product",name:product.name,image:`https://superbuys.pro${product.image}`,category:categoryLabel(locale,product.category),sku:product.id,url},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:copy[locale].home,item:`https://superbuys.pro${localPath(locale)}`},{"@type":"ListItem",position:2,name:sectionTitles[locale].finds,item:`https://superbuys.pro${localPath(locale,"finds")}`},{"@type":"ListItem",position:3,name:product.name,item:url}]}];return <main id="top"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Header locale={locale} section={`products/${product.slug}`}/><article className="product-page"><div className={`product-detail-image ${product.tone}`}><img src={product.image} alt={product.name} width="900" height="900"/></div><div className="product-detail-copy"><p>{pc.specs} / {product.id}</p><h1>{product.name}</h1><dl><div><dt>{pc.category}</dt><dd>{categoryLabel(locale,product.category)}</dd></div><div><dt>{pc.sourcePrice}</dt><dd>¥{product.priceCny}</dd></div><div><dt>{pc.sourceId}</dt><dd>{product.id}</dd></div><div><dt>{pc.updated}</dt><dd>2026-08-11</dd></div></dl><p>{pc.check}</p><p className="partner-notice"><b>{pc.partner}</b><br/>{pc.partnerNote}</p><a className="partner-button" href={product.targetUrl} target="_blank" rel="noopener sponsored">{pc.partner} ↗</a><Link className="article-back" href={localPath(locale,"finds")}>← {pc.back}</Link></div></article><Footer locale={locale}/></main>}

export function TrustPage({locale,slug}:{locale:Locale;slug:TrustSlug}){const p=trustPage(locale,slug);return <main id="top"><Header locale={locale} section={slug}/><article className="article-page trust-page"><p>{copy[locale].independent}</p><h1>{p.title}</h1><p className="article-dek">{p.dek}</p>{p.sections.map(([h,t])=><section key={h}><h2>{h}</h2><p>{t}</p></section>)}{slug==="contact"&&<a className="partner-button" href="https://github.com/hehaize88-code/hacoovip.shop" target="_blank" rel="noopener">PUBLIC PROJECT CHANNEL ↗</a>}</article><Footer locale={locale}/></main>}
