import type { Locale } from "./content";

export const trustSlugs = ["about","contact","privacy","terms","editorial-policy","disclosure"] as const;
export type TrustSlug = typeof trustSlugs[number];

type TrustPage = {title:string;dek:string;sections:[string,string][]};

export const trustNav:Record<Locale,Record<TrustSlug,string>>={
  en:{about:"About",contact:"Contact",privacy:"Privacy",terms:"Terms","editorial-policy":"Editorial Policy",disclosure:"Partner Disclosure"},
  de:{about:"Über uns",contact:"Kontakt",privacy:"Datenschutz",terms:"Bedingungen","editorial-policy":"Redaktionsrichtlinie",disclosure:"Partnerhinweis"},
  fr:{about:"À propos",contact:"Contact",privacy:"Confidentialité",terms:"Conditions","editorial-policy":"Politique éditoriale",disclosure:"Divulgation partenaire"},
  it:{about:"Chi siamo",contact:"Contatti",privacy:"Privacy",terms:"Termini","editorial-policy":"Politica editoriale",disclosure:"Informativa partner"},
  nl:{about:"Over ons",contact:"Contact",privacy:"Privacy",terms:"Voorwaarden","editorial-policy":"Redactioneel beleid",disclosure:"Partnerverklaring"},
  ms:{about:"Tentang",contact:"Hubungi",privacy:"Privasi",terms:"Terma","editorial-policy":"Dasar editorial",disclosure:"Pendedahan rakan kongsi"},
};

const en:Record<TrustSlug,TrustPage>={
  about:{title:"About this independent index",dek:"Superbuys.pro is an independent product-discovery and research site. It is not owned, operated or endorsed by Superbuy.",sections:[["What we publish","We organize product references, category routes, QC checklists and researched guides. Operational statements about Superbuy are checked against official guidance and dated so readers can verify changing terms."],["Where links go","Product, category and search actions can open cnfanshp.com, our partner catalog. We label that handoff beside the action so visitors know they are leaving this site and are not being sent to Superbuy.com."],["What we do not promise","A listing, photo or price does not prove authenticity, availability, fit, durability or delivered cost. Readers should verify the live product, seller terms, warehouse evidence, route restrictions and final charges before ordering."]]},
  contact:{title:"Contact and corrections",dek:"Broken link, factual error or rights concern? Use the public project channel so the correction can be reviewed and documented.",sections:[["Report a problem","Open the project repository linked below and describe the affected URL, the statement or link that needs correction, and supporting evidence. Do not include order numbers, payment details, identity documents or account credentials."],["Editorial corrections","Material factual corrections are reviewed against the cited official source or live target page. If confirmed, the visible page date and relevant structured data are updated together."],["Commercial enquiries","A request for inclusion does not guarantee coverage or favorable wording. Product placement and factual editorial claims are handled separately."]]},
  privacy:{title:"Privacy notice",dek:"This public site is designed for browsing without an account and does not ask visitors to submit personal or payment information.",sections:[["Information you provide","The site has no account system, checkout or contact form. Search terms are sent directly to the partner catalog only when you submit the search form."],["Technical records","The hosting provider may process ordinary security and delivery logs such as IP address, browser type and requested URL. This site does not intentionally build personal advertising profiles."],["External sites","Links to Superbuy official sources, cnfanshp.com, and the public project channel have their own privacy practices. Review those policies before submitting information there."]]},
  terms:{title:"Terms of use",dek:"Use this site as a dated research aid, not as a seller, purchasing agent, authentication service or shipping guarantee.",sections:[["Informational purpose","Product references, prices and guides are provided for general information. Live listings, platform terms, route availability, currency conversion and fees can change without notice."],["Your checks","Before acting, verify the exact product option, seller rules, legality at destination, shipping restrictions, customs obligations and current platform terms. You are responsible for purchase and shipping decisions made on external sites."],["Rights and availability","Names and marks belong to their respective owners. We may correct, update or remove a link when it becomes inaccurate, unavailable or subject to a valid rights concern."]]},
  "editorial-policy":{title:"Editorial policy",dek:"Our standard is simple: distinguish verified platform facts, dated catalog observations and practical judgment.",sections:[["Source hierarchy","Platform operations are checked first against Superbuy's official User Guidance, Help Center and fee pages. Product names, source prices and target URLs are checked against the matching live catalog page."],["Dating and corrections","Articles show a visible update date, Article schema uses the same dateModified, and the sitemap uses the same lastmod. Material corrections are reviewed and dated rather than silently presented as timeless facts."],["Reviews and images","We do not invent customer reviews, delivery results or QC outcomes. Customer-experience articles must identify their source and separate reported experience from verified policy. Product images are locally cached from the linked catalog record to reduce broken-image risk."]]},
  disclosure:{title:"Partner and link disclosure",dek:"The site's Superbuy-focused editorial content and its product destination are not the same service.",sections:[["The relationship","Superbuys.pro is not an official Superbuy website. Product, category and search links may open cnfanshp.com, a separate partner catalog that can present purchasing-platform choices."],["Possible commercial benefit","The site owner may benefit when visitors use partner links. That possibility does not change the standard for describing Superbuy operations, which must be supported by official sources."],["Make an informed click","Buttons that leave the site state the destination. Opening a partner page does not mean Superbuy endorses this site, the catalog, a seller or a product. Check the final destination before entering information or placing an order."]]},
};

const localizedSections:Record<Exclude<Locale,"en">,Record<TrustSlug,[string,string][]>>={
  de:{
    about:[["Was wir veröffentlichen","Wir ordnen Produktverweise, Kategorien, QC-Checklisten und recherchierte Ratgeber. Aussagen zu Superbuy werden mit offiziellen Quellen geprüft und datiert."],["Wohin Links führen","Produkt-, Kategorie- und Suchaktionen können den Partnerkatalog cnfanshp.com öffnen. Der Zielwechsel wird direkt am Button erklärt."],["Was wir nicht versprechen","Ein Eintrag beweist weder Echtheit noch Verfügbarkeit, Passform, Haltbarkeit oder Endpreis. Prüfe Live-Angebot, Verkäuferregeln, Lagerbilder und Versandkosten."]],
    contact:[["Problem melden","Nutze den unten verlinkten öffentlichen Projektkanal und nenne URL, Fehler und Beleg. Teile keine Bestell-, Zahlungs- oder Ausweisdaten."],["Korrekturen","Wesentliche Fehler werden anhand offizieller Quellen oder der aktuellen Zielseite geprüft. Datum, sichtbarer Text und strukturierte Daten werden gemeinsam aktualisiert."],["Kommerzielle Anfragen","Eine Anfrage garantiert weder Aufnahme noch positive Darstellung. Bezahlte Platzierung und redaktionelle Fakten werden getrennt behandelt."]],
    privacy:[["Von dir bereitgestellte Daten","Diese Website hat kein Konto, keinen Checkout und kein Kontaktformular. Suchbegriffe werden erst beim Absenden direkt an den Partnerkatalog übertragen."],["Technische Protokolle","Der Hostinganbieter kann übliche Sicherheits- und Auslieferungsdaten verarbeiten. Wir erstellen absichtlich keine persönlichen Werbeprofile."],["Externe Websites","Superbuy, cnfanshp.com und der Projektkanal haben eigene Datenschutzregeln. Prüfe sie, bevor du dort Daten eingibst."]],
    terms:[["Informationszweck","Produkte, Preise und Ratgeber sind allgemeine, datierte Informationen. Angebote, Plattformregeln, Routen und Gebühren können sich ändern."],["Deine Prüfung","Prüfe Variante, Verkäuferregeln, Recht am Zielort, Versandbeschränkungen, Zoll und aktuelle Plattformbedingungen selbst."],["Rechte und Verfügbarkeit","Marken gehören ihren Eigentümern. Fehlerhafte, nicht verfügbare oder rechtlich beanstandete Links können korrigiert oder entfernt werden."]],
    "editorial-policy":[["Quellenhierarchie","Abläufe werden zuerst mit offiziellen Superbuy-Seiten geprüft; Produktname, CNY-Preis und Ziel-URL mit der passenden Katalogseite."],["Datum und Korrektur","Sichtbares Artikeldatum, dateModified und sitemap-lastmod werden konsistent gehalten. Wesentliche Korrekturen erhalten ein neues Datum."],["Erfahrungen und Bilder","Wir erfinden keine Kundenbewertungen oder QC-Ergebnisse. Fremde Erfahrungen werden als solche gekennzeichnet; Produktbilder werden lokal zwischengespeichert."]],
    disclosure:[["Beziehung","Superbuys.pro ist keine offizielle Superbuy-Website. Produkt-, Kategorie- und Suchlinks können cnfanshp.com öffnen."],["Möglicher Vorteil","Der Betreiber kann von Partnerlinks profitieren. Aussagen über Superbuy müssen trotzdem durch offizielle Quellen belegt sein."],["Bewusst klicken","Externe Buttons nennen ihr Ziel. Ein Partnerlink bedeutet keine Empfehlung durch Superbuy für diese Website, einen Verkäufer oder ein Produkt."]],
  },
  fr:{
    about:[["Ce que nous publions","Nous organisons références produit, catégories, contrôles QC et guides documentés. Les faits sur Superbuy sont vérifiés auprès de sources officielles et datés."],["Destination des liens","Les recherches et boutons produit ou catégorie peuvent ouvrir le catalogue partenaire cnfanshp.com. Cette sortie est signalée près de l’action."],["Ce que nous ne garantissons pas","Une fiche ne prouve ni authenticité, disponibilité, taille, durabilité ni coût livré. Vérifiez l’offre active, le vendeur, les photos d’entrepôt et le transport."]],
    contact:[["Signaler un problème","Utilisez le canal public ci-dessous avec l’URL, l’erreur et une preuve. Ne partagez pas de numéro de commande, paiement, identité ou mot de passe."],["Corrections","Les erreurs importantes sont comparées à la source officielle ou à la page cible active. Le texte, la date et les données structurées sont corrigés ensemble."],["Demandes commerciales","Une demande ne garantit ni inclusion ni avis favorable. Le placement commercial reste séparé des faits éditoriaux."]],
    privacy:[["Données fournies","Le site ne possède ni compte, ni paiement, ni formulaire. Une recherche n’est envoyée au partenaire que lorsque vous la validez."],["Journaux techniques","L’hébergeur peut traiter des journaux ordinaires de sécurité et de diffusion. Nous ne créons pas volontairement de profil publicitaire personnel."],["Sites externes","Superbuy, cnfanshp.com et le canal public appliquent leurs propres politiques. Consultez-les avant d’y transmettre des données."]],
    terms:[["But informatif","Produits, prix et guides sont des informations générales datées. Offres, règles, itinéraires et frais peuvent changer."],["Vos vérifications","Vérifiez variante, vendeur, légalité, restrictions, douane et conditions actuelles avant toute décision externe."],["Droits et disponibilité","Les marques appartiennent à leurs propriétaires. Un lien inexact, indisponible ou contesté peut être corrigé ou supprimé."]],
    "editorial-policy":[["Hiérarchie des sources","Les opérations sont vérifiées sur les pages officielles Superbuy; nom, prix CNY et URL sur la fiche catalogue correspondante."],["Dates et corrections","La date visible, dateModified et lastmod restent cohérents. Une correction importante reçoit une nouvelle date."],["Avis et images","Nous n’inventons ni avis client ni résultat QC. Les expériences externes sont attribuées et les images produit sont mises en cache localement."]],
    disclosure:[["Relation","Superbuys.pro n’est pas un site officiel Superbuy. Les liens produit, catégorie et recherche peuvent ouvrir cnfanshp.com."],["Avantage possible","Le propriétaire peut bénéficier des liens partenaires. Les faits sur Superbuy doivent malgré tout provenir de sources officielles."],["Clic éclairé","Les boutons externes indiquent leur destination. Un lien partenaire ne constitue pas une approbation de Superbuy."]],
  },
  it:{
    about:[["Cosa pubblichiamo","Organizziamo riferimenti prodotto, categorie, checklist QC e guide documentate. I fatti su Superbuy sono verificati su fonti ufficiali e datati."],["Dove portano i link","Ricerca e pulsanti possono aprire il catalogo partner cnfanshp.com. Il cambio di sito è indicato vicino all’azione."],["Cosa non garantiamo","Una scheda non prova autenticità, disponibilità, vestibilità, durata o costo finale. Verifica offerta, venditore, foto di magazzino e spedizione."]],
    contact:[["Segnala un problema","Usa il canale pubblico sotto indicando URL, errore e prova. Non inserire ordini, pagamenti, documenti o credenziali."],["Correzioni","Gli errori importanti sono controllati sulla fonte ufficiale o sulla pagina attiva. Testo, data e dati strutturati vengono aggiornati insieme."],["Richieste commerciali","Una richiesta non garantisce presenza o giudizio favorevole. Il posizionamento commerciale resta separato dai fatti editoriali."]],
    privacy:[["Dati forniti","Il sito non ha account, checkout o moduli. Una ricerca viene inviata al partner solo quando la confermi."],["Registri tecnici","L’hosting può trattare normali log di sicurezza e consegna. Non creiamo intenzionalmente profili pubblicitari personali."],["Siti esterni","Superbuy, cnfanshp.com e il canale pubblico hanno politiche proprie. Leggile prima di inviare dati."]],
    terms:[["Scopo informativo","Prodotti, prezzi e guide sono informazioni generali datate. Offerte, regole, rotte e costi possono cambiare."],["Le tue verifiche","Controlla variante, venditore, legalità, restrizioni, dogana e condizioni correnti prima di agire su siti esterni."],["Diritti e disponibilità","I marchi appartengono ai proprietari. Link errati, non disponibili o contestati possono essere corretti o rimossi."]],
    "editorial-policy":[["Gerarchia delle fonti","Le procedure sono verificate sulle pagine ufficiali Superbuy; nome, prezzo CNY e URL sulla scheda catalogo corrispondente."],["Date e correzioni","Data visibile, dateModified e lastmod restano coerenti. Una correzione rilevante riceve una nuova data."],["Recensioni e immagini","Non inventiamo recensioni o risultati QC. Le esperienze esterne sono attribuite e le immagini prodotto vengono memorizzate localmente."]],
    disclosure:[["Rapporto","Superbuys.pro non è un sito ufficiale Superbuy. Link prodotto, categoria e ricerca possono aprire cnfanshp.com."],["Possibile beneficio","Il proprietario può beneficiare dei link partner. I fatti su Superbuy devono comunque essere sostenuti da fonti ufficiali."],["Clic consapevole","I pulsanti esterni indicano la destinazione. Un link partner non equivale a un’approvazione di Superbuy."]],
  },
  nl:{
    about:[["Wat we publiceren","We ordenen productverwijzingen, categorieën, QC-checks en onderzochte gidsen. Feiten over Superbuy worden aan officiële bronnen getoetst en gedateerd."],["Waar links heen gaan","Zoek-, product- en categorieknoppen kunnen partnercatalogus cnfanshp.com openen. Dat staat direct bij de actie."],["Wat we niet beloven","Een vermelding bewijst geen echtheid, voorraad, pasvorm, levensduur of bezorgde prijs. Controleer live aanbod, verkoper, magazijnbeelden en verzending."]],
    contact:[["Meld een probleem","Gebruik het openbare kanaal hieronder met URL, fout en bewijs. Deel geen order-, betaal-, identiteits- of inloggegevens."],["Correcties","Belangrijke fouten worden vergeleken met de officiële bron of actuele doelpagina. Tekst, datum en gestructureerde gegevens worden samen aangepast."],["Commerciële aanvragen","Een aanvraag garandeert geen opname of gunstige tekst. Commerciële plaatsing blijft gescheiden van redactionele feiten."]],
    privacy:[["Door jou verstrekte gegevens","De site heeft geen account, checkout of formulier. Een zoekterm gaat pas naar de partner wanneer je de zoekopdracht indient."],["Technische logboeken","De host kan gewone beveiligings- en leveringslogs verwerken. We maken bewust geen persoonlijke advertentieprofielen."],["Externe sites","Superbuy, cnfanshp.com en het openbare kanaal hebben eigen regels. Lees die voordat je gegevens verstrekt."]],
    terms:[["Informatief doel","Producten, prijzen en gidsen zijn algemene, gedateerde informatie. Aanbod, regels, routes en kosten kunnen wijzigen."],["Jouw controles","Controleer variant, verkoper, wettigheid, beperkingen, douane en actuele voorwaarden voordat je extern handelt."],["Rechten en beschikbaarheid","Merken zijn van hun eigenaars. Onjuiste, verdwenen of betwiste links kunnen worden aangepast of verwijderd."]],
    "editorial-policy":[["Bronhiërarchie","Werkwijzen worden eerst op officiële Superbuy-pagina’s gecontroleerd; naam, CNY-prijs en URL op de passende cataloguspagina."],["Datums en correcties","Zichtbare datum, dateModified en lastmod blijven gelijk. Een wezenlijke correctie krijgt een nieuwe datum."],["Ervaringen en beelden","We verzinnen geen reviews of QC-resultaten. Externe ervaringen krijgen bronvermelding en productbeelden worden lokaal opgeslagen."]],
    disclosure:[["Relatie","Superbuys.pro is geen officiële Superbuy-site. Product-, categorie- en zoeklinks kunnen cnfanshp.com openen."],["Mogelijk voordeel","De eigenaar kan voordeel hebben van partnerlinks. Feiten over Superbuy moeten toch op officiële bronnen steunen."],["Bewust klikken","Externe knoppen noemen hun bestemming. Een partnerlink is geen aanbeveling van Superbuy."]],
  },
  ms:{
    about:[["Apa yang diterbitkan","Kami menyusun rujukan produk, kategori, senarai QC dan panduan yang dikaji. Fakta Superbuy disemak pada sumber rasmi dan diberi tarikh."],["Destinasi pautan","Carian serta butang produk dan kategori boleh membuka katalog rakan kongsi cnfanshp.com. Peralihan ini dinyatakan berhampiran tindakan."],["Apa yang tidak dijamin","Senarai tidak membuktikan ketulenan, stok, saiz, ketahanan atau kos dihantar. Semak tawaran langsung, penjual, foto gudang dan penghantaran."]],
    contact:[["Laporkan masalah","Gunakan saluran awam di bawah dengan URL, ralat dan bukti. Jangan kongsi nombor pesanan, bayaran, dokumen atau kata laluan."],["Pembetulan","Ralat penting disemak dengan sumber rasmi atau halaman sasaran semasa. Teks, tarikh dan data berstruktur dikemas kini bersama."],["Pertanyaan komersial","Permintaan tidak menjamin kemasukan atau ulasan positif. Penempatan komersial diasingkan daripada fakta editorial."]],
    privacy:[["Data yang diberi","Laman ini tiada akaun, bayaran atau borang. Kata carian dihantar kepada rakan kongsi hanya apabila anda menyerahkannya."],["Log teknikal","Penyedia hos boleh memproses log keselamatan dan penghantaran biasa. Kami tidak sengaja membina profil iklan peribadi."],["Laman luar","Superbuy, cnfanshp.com dan saluran awam mempunyai dasar sendiri. Semak sebelum menghantar data."]],
    terms:[["Tujuan maklumat","Produk, harga dan panduan ialah maklumat umum bertarikh. Tawaran, peraturan, laluan dan yuran boleh berubah."],["Semakan anda","Semak pilihan, penjual, undang-undang, sekatan, kastam dan syarat semasa sebelum bertindak di laman luar."],["Hak dan ketersediaan","Tanda dagangan milik pemiliknya. Pautan salah, hilang atau dipertikai boleh diperbetulkan atau dibuang."]],
    "editorial-policy":[["Hierarki sumber","Proses disemak pada halaman rasmi Superbuy; nama, harga CNY dan URL pada rekod katalog sepadan."],["Tarikh dan pembetulan","Tarikh kelihatan, dateModified dan lastmod dikekalkan sama. Pembetulan penting diberi tarikh baharu."],["Ulasan dan imej","Kami tidak mencipta ulasan atau keputusan QC. Pengalaman luar diberi sumber dan imej produk disimpan setempat."]],
    disclosure:[["Hubungan","Superbuys.pro bukan laman rasmi Superbuy. Pautan produk, kategori dan carian boleh membuka cnfanshp.com."],["Manfaat mungkin","Pemilik mungkin menerima manfaat daripada pautan rakan kongsi. Fakta Superbuy tetap perlu disokong sumber rasmi."],["Klik dengan sedar","Butang luar menyatakan destinasinya. Pautan rakan kongsi bukan pengesahan oleh Superbuy."]],
  },
};

const trustDeks:Record<Exclude<Locale,"en">,string>={de:"Unabhängige Informationen mit klar gekennzeichneten Quellen, Partnerzielen und Grenzen.",fr:"Informations indépendantes avec sources, destinations partenaires et limites clairement indiquées.",it:"Informazioni indipendenti con fonti, destinazioni partner e limiti indicati chiaramente.",nl:"Onafhankelijke informatie met duidelijke bronnen, partnerbestemmingen en beperkingen.",ms:"Maklumat bebas dengan sumber, destinasi rakan kongsi dan batasan yang dinyatakan dengan jelas."};
const translations=Object.fromEntries((["de","fr","it","nl","ms"] as const).map(locale=>[locale,Object.fromEntries(trustSlugs.map(slug=>[slug,{title:trustNav[locale][slug],dek:trustDeks[locale],sections:localizedSections[locale][slug]}]))])) as Record<Exclude<Locale,"en">,Record<TrustSlug,TrustPage>>;

export function trustPage(locale:Locale,slug:TrustSlug):TrustPage{return locale==="en"?en[slug]:translations[locale][slug];}
