export const MAIN_SITE = "https://cnfanshp.com";

export const categories = [
  {
    slug: "shoes",
    name: "Shoes",
    short: "Sneakers & footwear",
    description: "Browse footwear listings, compare available angles, and check shape, outsole, stitching and size-label details.",
    href: `${MAIN_SITE}/shoes/`,
    code: "01",
  },
  {
    slug: "hoodies-sweaters",
    name: "Hoodies",
    short: "Hoodies & sweaters",
    description: "Explore warm layers and use the QC checklist to review fabric weight, print placement, cuffs and measurements.",
    href: `${MAIN_SITE}/hoodies-sweaters/`,
    code: "02",
  },
  {
    slug: "t-shirts",
    name: "T-Shirts",
    short: "Tees & tops",
    description: "Find everyday tops and inspect collar shape, print alignment, seams, tags and the measurement ruler when shown.",
    href: `${MAIN_SITE}/t-shirts/`,
    code: "03",
  },
  {
    slug: "jackets",
    name: "Jackets",
    short: "Outerwear",
    description: "Review outerwear listings with attention to hardware, lining, panel symmetry, embroidery and overall dimensions.",
    href: `${MAIN_SITE}/jackets/`,
    code: "04",
  },
  {
    slug: "pants-shorts",
    name: "Pants",
    short: "Pants & shorts",
    description: "Compare bottoms and check the waist, inseam, pocket placement, drawstrings and size information before ordering.",
    href: `${MAIN_SITE}/pants-shorts/`,
    code: "05",
  },
  {
    slug: "headwear",
    name: "Headwear",
    short: "Caps & hats",
    description: "Browse caps and hats while checking crown shape, embroidery, brim profile, closure hardware and label details.",
    href: `${MAIN_SITE}/headwear/`,
    code: "06",
  },
  {
    slug: "accessories",
    name: "Accessories",
    short: "Bags, watches & more",
    description: "Discover accessories and examine finishing, hardware, dimensions and protective packaging in the available images.",
    href: `${MAIN_SITE}/accessories/`,
    code: "07",
  },
  {
    slug: "jersey",
    name: "Jerseys",
    short: "Teamwear",
    description: "Browse jersey listings and check numbering, badges, print alignment, stitching and size charts before choosing.",
    href: `${MAIN_SITE}/Jersey/`,
    code: "08",
  },
  {
    slug: "electronics",
    name: "Electronics",
    short: "Tech accessories",
    description: "Explore tech-related listings and confirm specifications, plug type, included parts and protective packaging.",
    href: `${MAIN_SITE}/electronics/`,
    code: "09",
  },
];

export const products = [
  {
    id: "6045",
    sourceId: "7750164710",
    name: "Shoes 60",
    category: "shoes",
    price: "330",
    image: "/products/shoes-60.jpg",
    href: `${MAIN_SITE}/AllProducts/6045.html`,
    note: "Footwear listing",
  },
  {
    id: "5974",
    sourceId: "",
    name: "Classic Loose-Fitting Hoodie",
    category: "hoodies-sweaters",
    price: "140",
    image: "/products/hoodie.webp",
    href: `${MAIN_SITE}/AllProducts/5974.html`,
    note: "Hoodie listing",
  },
  {
    id: "5976",
    sourceId: "",
    name: "Piqué Cotton T-Shirt",
    category: "t-shirts",
    price: "215",
    image: "/products/tshirt.webp",
    href: `${MAIN_SITE}/AllProducts/5976.html`,
    note: "T-shirt listing",
  },
  {
    id: "5981",
    sourceId: "",
    name: "Embroidered Jacket",
    category: "jackets",
    price: "298",
    image: "/products/jacket.webp",
    href: `${MAIN_SITE}/AllProducts/5981.html`,
    note: "Outerwear listing",
  },
  {
    id: "5983",
    sourceId: "",
    name: "Drawstring Pants",
    category: "pants-shorts",
    price: "249",
    image: "/products/pants.webp",
    href: `${MAIN_SITE}/AllProducts/5983.html`,
    note: "Pants listing",
  },
  {
    id: "5971",
    sourceId: "",
    name: "Letter-Embroidered Cap",
    category: "headwear",
    price: "89",
    image: "/products/headwear.webp",
    href: `${MAIN_SITE}/AllProducts/5971.html`,
    note: "Headwear listing",
  },
  {
    id: "5952",
    sourceId: "",
    name: "Watch Collection",
    category: "accessories",
    price: "520",
    image: "/products/watch.webp",
    href: `${MAIN_SITE}/AllProducts/5952.html`,
    note: "Accessory listing",
  },
  {
    id: "5850",
    sourceId: "",
    name: "City Edition Jerseys",
    category: "jersey",
    price: "88",
    image: "/products/jersey.webp",
    href: `${MAIN_SITE}/AllProducts/5850.html`,
    note: "Jersey listing",
  },
  {
    id: "5822",
    sourceId: "",
    name: "MagSafe Accessory",
    category: "electronics",
    price: "75",
    image: "/products/electronics.webp",
    href: `${MAIN_SITE}/AllProducts/5822.html`,
    note: "Electronics listing",
  },
];

export const faqs = [
  {
    question: "Does FindQC Pro sell products?",
    answer: "No. FindQC Pro is an independent product-discovery and QC education website. Product pages and purchase actions open the source catalog on cnfanshp.com, where availability and current details should be confirmed.",
  },
  {
    question: "Are the displayed images a guarantee of product quality?",
    answer: "No. Images are reference material, not a guarantee. Check the listing details and any warehouse or inspection images made available for your own order before approving international shipment.",
  },
  {
    question: "What can I search for?",
    answer: "You can search this site's mapped categories and product shortlist by a word such as shoes, hoodie or cap, or enter a known product ID. Matching results keep their exact source-page links instead of sending every query to a generic all-products page.",
  },
  {
    question: "Why should I check QC images before shipping?",
    answer: "A careful image review can help you spot visible issues such as an incorrect colour, obvious damage, missing parts or a measurement mismatch while the parcel is still at the warehouse. It cannot verify every material or performance detail.",
  },
];

export { articles } from "./articles";
