// Generated by scripts/generate-responsive-images.mjs.
export const imageManifest = {
  "/products/catalog/accessories-5874.jpg": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5874-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5874-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5874-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5874-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5922.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5922-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5922-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5922-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5922-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5923.webp": {
    "width": 640,
    "height": 640,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5923-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5923-640.avif",
        "width": 640
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5923-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5923-640.webp",
        "width": 640
      }
    ]
  },
  "/products/catalog/accessories-5924.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5924-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5924-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5924-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5924-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5940.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5940-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5940-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5940-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5940-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5941.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5941-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5941-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5941-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5941-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5943.jpg": {
    "width": 523,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5943-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5943-523.avif",
        "width": 523
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5943-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5943-523.webp",
        "width": 523
      }
    ]
  },
  "/products/catalog/accessories-5944.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5944-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5944-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5944-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5944-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5945.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5945-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5945-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5945-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5945-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5946.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5946-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5946-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5946-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5946-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5947.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5947-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5947-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5947-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5947-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/accessories-5952.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/accessories-5952-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5952-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/accessories-5952-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/accessories-5952-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5615.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5615-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5615-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5615-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5615-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5630.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5630-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5630-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5630-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5630-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5632.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5632-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5632-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5632-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5632-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5650.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5650-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5650-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5650-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5650-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5691.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5691-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5691-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5691-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5691-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5693.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5693-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5693-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5693-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5693-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5732.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5732-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5732-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5732-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5732-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5752.gif": {
    "width": 500,
    "height": 500,
    "avif": [],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5752-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5752-500.webp",
        "width": 500
      }
    ]
  },
  "/products/catalog/electronics-5753.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5753-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5753-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5753-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5753-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5819.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5819-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5819-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5819-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5819-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5821.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5821-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5821-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5821-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5821-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/electronics-5822.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/electronics-5822-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5822-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/electronics-5822-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/electronics-5822-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5741.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5741-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5741-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5741-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5741-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5772.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5772-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5772-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5772-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5772-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5820.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5820-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5820-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5820-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5820-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5863.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5863-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5863-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5863-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5863-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5864.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5864-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5864-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5864-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5864-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5884.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5884-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5884-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5884-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5884-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5885.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5885-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5885-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5885-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5885-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5886.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5886-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5886-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5886-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5886-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5887.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5887-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5887-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5887-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5887-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5888.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5888-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5888-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5888-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5888-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5889.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5889-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5889-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5889-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5889-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/headwear-5971.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/headwear-5971-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5971-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/headwear-5971-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/headwear-5971-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5856.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5856-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5856-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5856-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5856-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5859.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5859-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5859-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5859-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5859-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5891.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5891-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5891-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5891-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5891-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5894.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5894-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5894-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5894-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5894-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5896.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5896-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5896-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5896-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5896-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5902.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5902-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5902-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5902-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5902-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5935.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5935-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5935-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5935-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5935-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5959.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5959-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5959-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5959-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5959-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5960.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5960-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5960-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5960-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5960-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5968.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5968-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5968-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5968-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5968-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5970.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5970-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5970-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5970-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5970-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/hoodies-sweaters-5974.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5974-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5974-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5974-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/hoodies-sweaters-5974-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5899.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5899-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5899-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5899-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5899-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5900.jpg": {
    "width": 563,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5900-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5900-563.avif",
        "width": 563
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5900-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5900-563.webp",
        "width": 563
      }
    ]
  },
  "/products/catalog/jackets-5901.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5901-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5901-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5901-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5901-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5903.jpg": {
    "width": 563,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5903-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5903-563.avif",
        "width": 563
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5903-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5903-563.webp",
        "width": 563
      }
    ]
  },
  "/products/catalog/jackets-5904.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5904-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5904-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5904-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5904-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5905.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5905-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5905-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5905-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5905-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5910.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5910-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5910-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5910-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5910-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5919.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5919-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5919-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5919-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5919-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5933.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5933-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5933-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5933-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5933-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5958.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5958-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5958-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5958-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5958-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5969.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5969-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5969-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5969-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5969-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jackets-5981.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jackets-5981-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5981-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jackets-5981-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jackets-5981-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-4674.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-4674-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4674-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-4674-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4674-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-4681.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-4681-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4681-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-4681-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4681-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-4888.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-4888-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4888-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-4888-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4888-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-4911.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-4911-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4911-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-4911-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4911-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-4929.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-4929-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4929-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-4929-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-4929-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5083.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5083-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5083-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5083-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5083-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5166.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5166-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5166-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5166-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5166-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5176.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5176-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5176-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5176-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5176-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5342.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5342-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5342-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5342-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5342-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5785.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5785-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5785-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5785-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5785-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5846.jpg": {
    "width": 1280,
    "height": 958,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5846-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5846-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5846-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5846-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/jersey-5850.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/jersey-5850-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5850-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/jersey-5850-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/jersey-5850-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5857.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5857-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5857-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5857-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5857-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5895.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5895-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5895-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5895-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5895-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5912.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5912-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5912-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5912-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5912-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5928.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5928-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5928-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5928-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5928-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5972.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5972-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5972-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5972-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5972-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5973.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5973-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5973-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5973-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5973-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5977.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5977-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5977-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5977-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5977-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5978.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5978-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5978-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5978-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5978-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5979.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5979-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5979-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5979-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5979-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5980.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5980-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5980-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5980-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5980-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5982.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5982-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5982-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5982-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5982-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/pants-shorts-5983.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5983-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5983-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/pants-shorts-5983-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/pants-shorts-5983-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6034.jpg": {
    "width": 1080,
    "height": 1080,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6034-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6034-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6034-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6034-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6035.jpg": {
    "width": 800,
    "height": 800,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6035-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6035-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6035-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6035-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6036.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6036-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6036-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6036-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6036-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6037.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6037-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6037-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6037-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6037-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6038.jpg": {
    "width": 1127,
    "height": 1280,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6038-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6038-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6038-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6038-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6039.jpg": {
    "width": 800,
    "height": 598,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6039-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6039-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6039-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6039-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6040.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6040-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6040-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6040-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6040-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6041.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6041-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6041-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6041-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6041-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6042.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6042-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6042-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6042-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6042-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6043.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6043-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6043-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6043-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6043-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6044.jpg": {
    "width": 1280,
    "height": 960,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6044-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6044-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6044-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6044-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/shoes-6045.jpg": {
    "width": 1280,
    "height": 1052,
    "avif": [
      {
        "src": "/optimized/products/catalog/shoes-6045-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6045-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/shoes-6045-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/shoes-6045-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5898.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5898-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5898-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5898-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5898-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5906.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5906-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5906-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5906-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5906-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5915.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5915-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5915-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5915-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5915-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5916.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5916-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5916-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5916-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5916-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5920.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5920-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5920-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5920-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5920-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5925.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5925-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5925-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5925-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5925-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5926.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5926-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5926-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5926-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5926-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5927.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5927-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5927-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5927-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5927-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5931.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5931-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5931-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5931-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5931-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5934.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5934-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5934-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5934-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5934-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5953.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5953-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5953-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5953-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5953-720.webp",
        "width": 720
      }
    ]
  },
  "/products/catalog/t-shirts-5976.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/catalog/t-shirts-5976-360.avif",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5976-720.avif",
        "width": 720
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/catalog/t-shirts-5976-360.webp",
        "width": 360
      },
      {
        "src": "/optimized/products/catalog/t-shirts-5976-720.webp",
        "width": 720
      }
    ]
  },
  "/products/electronics.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/electronics-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/electronics-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/electronics-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/electronics-750.webp",
        "width": 750
      }
    ]
  },
  "/products/headwear.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/headwear-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/headwear-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/headwear-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/headwear-750.webp",
        "width": 750
      }
    ]
  },
  "/products/hoodie.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/hoodie-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/hoodie-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/hoodie-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/hoodie-750.webp",
        "width": 750
      }
    ]
  },
  "/products/jacket.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/jacket-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/jacket-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/jacket-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/jacket-750.webp",
        "width": 750
      }
    ]
  },
  "/products/jersey.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/jersey-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/jersey-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/jersey-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/jersey-750.webp",
        "width": 750
      }
    ]
  },
  "/products/pants.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/pants-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/pants-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/pants-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/pants-750.webp",
        "width": 750
      }
    ]
  },
  "/products/shoes-60.jpg": {
    "width": 1280,
    "height": 1052,
    "avif": [
      {
        "src": "/optimized/products/shoes-60-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/shoes-60-960.avif",
        "width": 960
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/shoes-60-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/shoes-60-960.webp",
        "width": 960
      }
    ]
  },
  "/products/tshirt.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/tshirt-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/tshirt-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/tshirt-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/tshirt-750.webp",
        "width": 750
      }
    ]
  },
  "/products/watch.webp": {
    "width": 750,
    "height": 750,
    "avif": [
      {
        "src": "/optimized/products/watch-480.avif",
        "width": 480
      },
      {
        "src": "/optimized/products/watch-750.avif",
        "width": 750
      }
    ],
    "webp": [
      {
        "src": "/optimized/products/watch-480.webp",
        "width": 480
      },
      {
        "src": "/optimized/products/watch-750.webp",
        "width": 750
      }
    ]
  }
};
