const p = (text) => ({ type: "p", text });
const table = (headers, rows) => ({ type: "table", headers, rows });
const section = (id, title, ...blocks) => ({ id, title, blocks });
const source = (href, label, note) => ({ href, label, note });
const base = {
  date: "5 October 2026",
  dateISO: "2026-10-05",
  updatedISO: "2026-10-05",
  languages: ["en"],
  readTime: "9 min read",
  heroCaption: "Editorial catalog photograph illustrating the topic. This is not a customer order or a warehouse QC record.",
  sourceIntro: "Sources reviewed on 5 October 2026. The checklists, comparison method and worked examples are independent editorial guidance. Examples are hypothetical; service features and shipping rules should be checked again before use.",
};

export const octoberArticles = [
  {
    ...base,
    slug: "findqc-vs-finderqc",
    title: "FindQC vs FinderQC: Search Methods, QC Photos and Key Differences",
    shortTitle: "FindQC vs FinderQC",
    description: "Compare FindQC and FinderQC using their documented search methods, then check listing identity, photo coverage and evidence before choosing your next step.",
    excerpt: "A practical comparison of documented features, with a repeatable way to evaluate results for your own product link.",
    category: "QC Finder Comparison",
    heroImage: "/products/shoes-60.jpg",
    heroAlt: "Editorial footwear example for comparing product identity across QC search results",
    keywords: ["FindQC vs FinderQC", "QC finder comparison", "find QC photos", "FindQC search"],
    intro: [
      "FindQC and FinderQC have similar names, but they are separate websites. A useful FindQC vs FinderQC comparison starts with the input you have and the question you need answered. Someone holding a current product link has a different task from someone trying to identify a jacket from a cropped photograph. Neither task is solved merely by finding a large gallery.",
      "This guide compares publicly documented features, then offers an original worksheet for checking the results yourself. It is not a speed test, database-size ranking or paid-plan review. FindQC Pro is an independent editorial site, separate from both services; our search box opens product results in the cnfanshp.com catalog. That catalog search should not be confused with either external QC research service.",
    ],
    sections: [
      section("documented-features", "1. Compare what the services actually document",
        p("FindQC documents link, keyword and image search, with photo records and optional richer fields. FinderQC's public homepage describes name and product-link searches and displays browsing, filtering and account controls. The table records those public descriptions, not an independently measured success rate."),
        table(["Capability", "FindQC documentation", "FinderQC public homepage"], [
          ["Product-link input", "Taobao, Weidian and 1688", "Taobao, Weidian and 1688"],
          ["Discovery input", "Keywords and images", "Product names"],
          ["Additional evidence", "Premium: video, weight, dimensions and history fields", "Check the individual record; equivalent fields not established here"],
          ["Browsing controls", "Same-item and similar groupings described", "Recommend, New QC, QC Rank and price filters visible"],
        ]),
        p("A feature not established in this comparison is an open question, not proof that it is absent. Likewise, a feature described on a help page may not be populated for your item. Check the live interface and the particular record before depending on it. Account requirements, availability and pricing can change independently of the product photographs.")),
      section("prepare-test", "2. Prepare a fair comparison using your own product",
        p("Choose one product you are genuinely researching. Record its marketplace, source URL, item identifier, seller, intended colour and size. Keep this record separate from either result page. A comparison becomes unreliable if you search a specific link on one service but a broad clothing category on the other, or accidentally switch between two sellers using the same stock image."),
        p("Write down one decision question before opening results. For a sweatshirt it might be whether a ruler photograph shows the body length in your intended size. For footwear it might be whether both shoes are visible together. Define what would answer that question: a readable tape, a clear size label or a paired overhead view. This gives the comparison a useful stopping point."),
        p("Use the same input and check both services during the same research session where practical. Record the date, search wording and whether you were signed in. These notes make your observations reproducible without pretending that a single item represents the entire database. Do not publish another customer's order identifiers or private account screenshots as supporting evidence.")),
      section("identity-first", "3. Judge the match before judging the gallery",
        p("Start with the marketplace and item identifier. Then compare the seller, selected option and visible construction. A similar front print does not establish that two listings share a factory, production batch or fabric. A different seller may reuse a promotional picture. Even the same listing can change its available options after older photographs were recorded."),
        table(["Observation", "Comparison note", "Next action"], [
          ["Matching item and seller; size unreadable", "Listing match, variant unresolved", "Request a readable option or size label"],
          ["Matching appearance; different item identifier", "Visual alternative", "Research separately from the original listing"],
          ["Matching source; older gallery", "Historical evidence", "Check current listing and later exact-unit photos"],
          ["Source identity missing", "Unverified candidate", "Keep searching or ask for provenance"],
        ]),
        p("An attractive interface cannot repair missing identity. If only one service provides a traceable candidate for your particular link, that candidate is more useful for this task. It does not establish that the same service will perform better for all categories. Keep the conclusion attached to the product and the evidence you actually saw.")),
      section("coverage", "4. Compare useful coverage rather than image totals",
        p("Build a small coverage list from your decision question: front, back, relevant detail, option label and measurement if needed. Mark each view as readable, ambiguous or absent. Ten repeated front views may leave the same unresolved issue as one front view. Two clear photographs can sometimes answer a narrow question more directly than a much larger set."),
        p("Separate photographs of one inspected unit from photographs collected across several units. Mixing them can create an imaginary complete inspection: the back belongs to a different size, the label to another colour and the measurement to an older record. Keep each observation tied to its own record. Differences between records are useful prompts for follow-up, not permission to average away a defect."),
        p("For an unclear surface, zoom into the original available view and inspect a wider angle as well. A crop alone can exaggerate a crease or hide the seam that explains it. Describe the uncertainty precisely: the image is too compressed to judge the print edge, or the tape endpoint is outside the frame. A precise gap makes the next request easier.")),
      section("extra-fields", "5. Give each extra field a specific job",
        p("Treat any additional measurement, video or history field as a separate piece of evidence. Ask what was measured, when it was recorded and whether it belongs to the same variant. A number labelled weight needs units and an explanation of included packaging. A delivery statistic needs a defined start and end point before it can influence your planning."),
        p("For example, a hypothetical shopper comparing two oversized tees might find more media on one service but a readable chest measurement on the other. If chest width is the unresolved question, the second record may be more useful. If the measured size differs from the intended size, neither record settles fit. The right conclusion depends on relevance, not the number of interface features."),
        p("Do not turn a missing optional field into a zero. Unknown weight does not mean a lightweight parcel; no visible return information does not mean no returns occurred. Keep unknown values explicit in your notes. That habit prevents polished result pages from creating stronger confidence than their actual records support.")),
      section("no-results", "6. Handle missing results without inventing a winner",
        p("If a product link returns no useful result, first confirm that the source listing still opens and that you copied an item page rather than a store page or private order page. Try a short product description containing the category and one distinguishing feature. If using visual discovery, retain the original source image and avoid crops that remove the important shape."),
        p("A no-match result has several possible explanations, including an unsupported URL shape, an unavailable listing or missing records. Without further evidence, it does not prove the seller is unreliable or the item is new. Switching services is a reasonable recovery step, but compare the recovered candidate against your original identity record before carrying any observations forward."),
        p("When both searches remain inconclusive, stop treating historical QC as a prerequisite that must somehow be satisfied. Record the gap and decide whether the live seller information and your selected agent's inspection process can address it. A deliberate unresolved result is more useful than accepting an unrelated gallery simply to complete the comparison.")),
      section("decision", "7. Write a bounded conclusion and take the next step",
        p("Finish your QC finder comparison with four lines: the input used, the identity established, the question answered and the remaining gap. An example might read: same source item found on both services; only one record showed the relevant back seam; neither record identified the intended size; request exact-unit measurements before warehouse approval. This is a research note, not a product endorsement."),
        p("Revisit the comparison only when the question changes or better evidence appears. Searching repeatedly without defining a new question can produce more photographs while leaving the decision unchanged. Save the useful record URLs and your source listing, then use the category checklist to prepare a short inspection request. The agent handling your order must confirm current services and any transaction steps."),
        p("The most useful service for a particular search is the one that provides traceable evidence relevant to that search. Keep that conclusion narrow. Neither service's name, a prominent ranking nor a collection of favourable images substitutes for checking the item actually received. Use discovery to prepare your inspection, and use your own warehouse evidence for the later approval decision.")),
    ],
    sources: [source("https://findqc.com/how-findqc-works", "FindQC: How FindQC Works", "Public descriptions of search inputs and record types; not an independent performance benchmark."), source("https://finderqc.com/", "FinderQC: public search homepage", "Visible search inputs, browsing controls and service disclaimer reviewed for this comparison.")],
    related: ["findqc-search-methods", "find-qc-photos-by-product-link", "what-qc-photos-can-prove"],
    cta: { eyebrow: "Continue with a specific input", title: "Have a product link? Start with listing identity.", label: "Read the product-link guide", href: "/articles/find-qc-photos-by-product-link", external: false },
  },
  {
    ...base,
    slug: "hoodie-qc-checklist",
    title: "Hoodie QC Checklist: Measurements, Stitching and Print Placement",
    shortTitle: "Hoodie QC Checklist",
    description: "Check hoodie measurements, hood shape, pocket alignment, cuffs, seams and print placement with a practical warehouse-photo checklist before shipping.",
    excerpt: "Inspect the details that matter on a hoodie and turn unclear photographs into specific measurement or close-up requests.",
    category: "Apparel QC",
    heroImage: "/products/catalog/hoodies-sweaters-5891.webp",
    heroAlt: "Editorial hoodie example for checking garment proportions and visible construction",
    keywords: ["hoodie QC", "hoodie QC checklist", "hoodie measurements", "hoodie stitching", "print placement"],
    intro: [
      "A hoodie QC checklist should help you decide what still needs checking before shipment. Start with the ordered size and colour, then review the body measurements, sleeves, hood, pocket, seams and decoration. These checks are most useful on photographs of your own warehouse item. Older QC records can help you prepare questions, but they do not inspect the unit you will receive.",
      "Use a hoodie you already wear as the reference for fit. A familiar size letter is a weak substitute for comparable garment dimensions, especially when switching between cropped, regular and oversized cuts. The workflow below is an editorial inspection aid, not a factory acceptance standard. Set your own priorities before examining the photographs so that a minor cosmetic issue does not distract from a decisive sizing mismatch.",
    ],
    sections: [
      section("identity", "1. Match the ordered hoodie and establish a flat view",
        p("Keep the source listing and order option beside the QC gallery. Confirm pullover or zip construction, intended colour, size label, pocket style and any front or back graphic. Check included pieces when the listing describes a set. If the label and order disagree, pause the fit assessment and ask the agent to reconcile the mismatch first."),
        p("Request front and back views with the body laid flat, sleeves arranged naturally and the hood moved away from the neckline where necessary. A twisted sleeve or folded hem can create an apparent asymmetry. Use those overview photographs to locate a concern, then use a closer view to decide whether it persists. Keep the full view with the detail so that the location remains clear."),
        p("Lighting can make dark colours lose detail and can change the apparent shade of fleece. A single image cannot establish an exact colour match. If shade is decisive, ask for a consistent second view and identify which part looks different. Do not infer fabric composition, warmth or authenticity from the photograph's colour or surface appearance.")),
      section("measurements", "2. Define the measurement points before comparing numbers",
        p("Lay your reference hoodie flat without stretching it. Record the points you use, the units and whether the zip is closed. Repeat those definitions in the warehouse request. Chest width measured below the armholes cannot be compared reliably with a tape placed diagonally across the widest folds. Body length measured from the shoulder is different from length measured from the back collar."),
        table(["Measurement", "Suggested definition to agree", "Common ambiguity"], [
          ["Chest width", "Straight across the flattened body below the armholes", "Circumference confused with flat width"],
          ["Body length", "High shoulder point beside neck to bottom hem", "Hood or collar included in length"],
          ["Sleeve length", "Shoulder seam to cuff along the agreed edge", "Dropped shoulder changes the starting point"],
          ["Hem width", "Across the relaxed bottom opening", "Rib stretched on one garment only"],
        ]),
        p("For a raglan sleeve, agree a different starting point, such as the neck seam, and use it on both garments. There is no useful comparison unless the endpoints match. Keep chest width as a flat dimension in your notes; doubling it is only an approximate circumference comparison and does not capture garment shape or wearing ease.")),
      section("fit-decision", "3. Turn measurements into a personal fit decision",
        p("Suppose your comfortable reference has a flat chest width of 60 cm and the warehouse photograph appears to show 57 cm. This hypothetical three-centimetre difference deserves attention if you want the same room through the body. It is not automatically a defect. First check the tape endpoints, garment arrangement and whether both items were measured without tension."),
        p("Consider body length and sleeve construction together. A wide cropped hoodie can have a roomy chest but a shorter hem than you expect. A dropped shoulder can produce a shorter seam-to-cuff measurement while leaving the overall sleeve reach adequate. Record the style you want instead of treating every difference from the reference as something to eliminate."),
        p("Decide your acceptable range before asking for a remeasurement. That range should reflect your reference garment and preferences, not an invented universal factory tolerance. If the photograph is unreadable, request a retake rather than estimating the nearest number. If a clear measurement falls outside your chosen range, ask about available options before approving the parcel.")),
      section("hood-pocket", "4. Inspect the hood, pocket and closures in context",
        p("Check whether the hood opening looks evenly arranged and whether the attachment seam is visible. Ask for a separate inside view if the lining or seam allowance is your concern. Do not judge hood volume from a tightly folded presentation. A laid-flat image can show construction details but cannot fully establish how the hood sits on your head."),
        p("For a kangaroo pocket, compare the two openings, the top corners and the pocket's position relative to the centre of the body. An angled camera can make one opening look higher. Ask for a straight overhead view before describing a pocket as crooked. Inspect the attachment corners for visible gaps or broken stitching, retaining enough surrounding fabric to identify the location."),
        p("On a zip hoodie, check that the two front halves are aligned in a closed view and request a brief operation check if closure is important. Note whether fabric appears caught near the teeth. For drawcords, check the pictured ends and openings against the listing. Photographs of hardware do not establish long-term durability or suitability for a particular wearer.")),
      section("stitching", "5. Read seams, cuffs and fabric surfaces carefully",
        p("Review the shoulder joins, underarm area, side seams, cuff attachments and bottom rib. Look for a visible opening, a run of missed stitches, persistent puckering or an obvious cut. A loose thread end is a different observation from an open seam. Describe which you see before deciding whether the issue matters or requires a closer inspection."),
        p("Compare both cuffs laid in a similar position. One cuff folded under the sleeve can look narrower even when its relaxed opening is similar. Ask for a close-up that shows the seam joining rib to sleeve if that join appears uneven. Do not request aggressive stretching to test strength; ordinary handling or an agent-confirmed inspection is more appropriate for resolving a visual question."),
        p("Inspect visible fleece or brushed surfaces for an unexplained patch, stain or area that looks damaged. Mark its location in the original image and request a second angle. A shadow, compression mark or lint may resemble a surface defect. Keep the observation provisional until clearer evidence is available, particularly when the original photograph is dark or heavily compressed.")),
      section("print", "6. Check print placement without mistaking folds for errors",
        p("Establish the body centre using stable garment features, then compare the graphic's position in a straight overhead image. Measure from the neck or shoulder reference to the top of the print if placement is important. Use the same reference on the seller's documented specification where one exists. A model photograph taken at an angle is a poor measuring template."),
        p("Review edges, gaps, doubled lines and areas where a graphic crosses a seam or pocket. Ask the agent to flatten a fold before treating it as a missing part of the design. A close-up can help locate visible damage, but it cannot predict wash resistance or adhesion over time. Avoid turning a sharp-looking print into a claim about production method."),
        p("CottonWorks distinguishes visible garment checks from performance characteristics that require measurement or testing. Its shrinkage guidance also explains that laundering-related dimensional change can affect fit and seams. Use those limits practically: record the present dimensions, follow the provided care information and do not promise that a warehouse photograph establishes future shrinkage or colourfastness.")),
      section("handoff", "7. Send one focused request and record the outcome",
        table(["Evidence state", "Useful action", "Record to keep"], [
          ["Critical measurement unreadable", "Request a flat retake with both tape endpoints", "Measurement definition and new photograph"],
          ["Possible pocket or print tilt", "Request a straight, flattened overview", "Original and retaken views together"],
          ["Visible mismatch with ordered option", "Ask agent to verify before shipment", "Order option and identified mismatch"],
          ["Relevant checks satisfactory", "Record remaining limits and your decision", "Exact-unit photos and approval date"],
        ]),
        p("A useful request could say: please photograph this hoodie flat, confirm the size label, and measure chest width straight across below the armholes without stretching. The right pocket corner also appears open in the current image; please provide one closer view showing the surrounding seam. This wording asks for evidence rather than a vague assurance that everything is fine."),
        p("Keep the response attached to the original order. Review the new evidence against your predefined priorities, then decide whether to proceed or ask the agent about another available action. Return eligibility, inspection services and time limits depend on the live transaction. Finish the hoodie QC check with a clear record of what was seen and what remains unknown.")),
    ],
    sources: [source("https://cottonworks.com/learning-hub/garment-manufacturing/garment-quality-control/", "CottonWorks: Garment Quality Control", "Background on fit, seam integrity and the distinction between inspection and performance testing."), source("https://cottonworks.com/learning-hub/quality-assurance/shrinking-and-skewing/", "CottonWorks: Shrinkage & Skewing", "Background on dimensional change; this guide does not predict shrinkage from photographs.")],
    related: ["findqc-qc-measurements-size-guide", "t-shirt-qc-checklist", "findqc-return-evidence-checklist"],
    cta: { eyebrow: "Apply the checklist", title: "Review hoodie listings with your measurement notes ready.", label: "Browse hoodie finds", href: "/categories/hoodies-sweaters", external: false },
  },
  {
    ...base,
    slug: "t-shirt-qc-checklist",
    title: "T-Shirt QC Checklist: Fit, Seams and Print Alignment",
    shortTitle: "T-Shirt QC Checklist",
    description: "Use a T-shirt QC checklist to compare chest width, body length, neckline, sleeve balance, seams and graphic alignment before warehouse approval.",
    excerpt: "A practical T-shirt quality check with consistent measurement points, print-placement checks and a clear request template.",
    category: "Apparel QC",
    heroImage: "/products/catalog/t-shirts-5953.webp",
    heroAlt: "Editorial T-shirt example illustrating a flat garment and print-position review",
    keywords: ["T-shirt QC", "T-shirt quality check", "T-shirt QC checklist", "T-shirt measurements", "print alignment"],
    intro: [
      "A useful T-shirt QC check begins with three questions: is this the ordered option, are its measured proportions suitable, and do the available views show any issue that changes your decision? Check those points before spending time on tiny details. A clear front image can still hide a short body length, an unreadable size label or an unphotographed back graphic.",
      "This checklist is designed for a buyer reviewing warehouse photographs. It does not replace a factory inspection or a wash test. Use historical QC photos to identify questions, then apply the checklist to your own item. Keep one well-fitting T-shirt nearby as a measurement reference and agree the measurement points with the person taking the photographs.",
    ],
    sections: [
      section("ordered-option", "1. Confirm the option and the complete design",
        p("Match the source item, seller and order option before examining the fabric. Check the colour, size label, neckline shape and whether the listing specifies a regular, oversized or cropped fit. Look at both sides of the garment. A small chest graphic and a large back graphic can belong to the same design; a front-only gallery does not establish that the back is correct."),
        p("Record intentional details from the listing, such as raw hems, contrast stitching, dropped shoulders or an asymmetric print. Otherwise you may describe the design itself as a defect. Keep a screenshot or written record of the selected option because a live listing may display a different colour after reopening. Use the option tied to your order as the comparison point."),
        p("Ask for a flat overview with the neckline, shoulders, sleeves and hem visible. The garment should be arranged naturally rather than pulled into a perfect rectangle. If an edge is folded beneath the body, mark it as unobserved. Avoid treating an incomplete view as evidence that the hidden area is satisfactory.")),
      section("fit", "2. Compare fit with matching measurement definitions",
        p("Measure your reference shirt flat and relaxed. Write down the exact start and end points instead of only the numbers. For chest width, agree a straight line below the armholes. For body length, specify a high shoulder point beside the neckline to the bottom hem, or another clearly defined method used consistently on both shirts."),
        table(["Point", "What to record", "What can confuse the comparison"], [
          ["Chest", "Flat width and tape position", "Body circumference or diagonal measurement"],
          ["Length", "Shoulder or collar starting point", "Different start points or curved hems"],
          ["Shoulders", "Seam-to-seam span when applicable", "Dropped shoulders or a seam-free construction"],
          ["Sleeve", "Seam-to-edge length and relaxed opening", "Different sleeve shapes or folded edges"],
        ]),
        p("A hypothetical reference measuring 56 cm across the chest and 72 cm long may feel quite different from a shirt measuring 59 cm by 66 cm. The second is wider and shorter; neither number alone describes the fit. Compare the combination with the silhouette you want. Do not assume that a larger printed size must be longer in every dimension.")),
      section("photo-audit", "3. Audit the measurement photograph before trusting it",
        p("Look for the beginning of the tape, the final reading and the path between them. A tape beginning above zero requires the offset to be considered. A slack tape, a diagonal path or stretched fabric can produce a misleading result. Ask for a retake if the relevant marks are unreadable; magnifying a blurred image does not create a reliable measurement."),
        p("Keep units explicit. If your reference is recorded in inches and the warehouse photograph uses centimetres, convert consistently and keep the original values. One inch equals 2.54 centimetres. Do not introduce artificial precision when the image only supports an approximate reading. A result close to your personal limit may justify a careful second measurement."),
        p("Set your acceptable range from garments you actually wear and the style you intend to buy. This guide supplies no universal centimetre tolerance because different cuts and preferences need different decisions. If the shirt is outside your chosen range, ask about options while the item remains under the agent's control. An attractive graphic does not resolve a fit mismatch.")),
      section("neck-sleeves", "4. Inspect the neckline, shoulders and sleeve balance",
        p("View the neckline from directly above with the shoulders arranged evenly. Check for a visible opening at the neckband join, a twisted attachment or a section that remains unusually distorted after flattening. A collar folded during packing can look uneven in the first photograph. Request a clearer arranged view before concluding that the neckline was sewn incorrectly."),
        p("Compare the shoulder joins and sleeve hems in similar positions. One sleeve pointing upward and the other folded down is not a fair symmetry check. If sleeve balance matters, request both sleeves laid outward and visible from seam to edge. For a deliberately dropped shoulder, compare the overall shape and agreed measurements instead of imposing a regular-fit seam position."),
        p("Inspect the underarm junction where several seams meet. A visible gap or broken stitching there deserves a closer photograph with context. For an exposed thread, determine whether it is an isolated tail or part of a failing join. Describe the location and appearance rather than claiming that every loose end predicts a garment coming apart.")),
      section("body-seams", "5. Review body seams, hems and fabric appearance",
        p("Follow the side seams where present and look at the lower hem across the whole body. An apparent twist can come from how the shirt is arranged, so compare a second flat view if the side seam seems to rotate strongly toward the front. Some shirts use tubular construction without side seams; their absence alone is not a missing feature."),
        p("Look for visible holes, stains, damaged areas, open joins and persistent seam puckering. Use an overview to locate each concern and a detail view to clarify it. Avoid relying on a tiny crop with no indication of scale. Record whether the issue appears on the front, back, inside or an edge so that the agent can inspect the correct place."),
        p("A photograph cannot establish fibre composition, fabric weight per square metre, softness or breathability. A heavier parcel is not proof of a heavier fabric because size, packaging and included items affect weight. CottonWorks treats fit and seam integrity as garment-quality considerations while distinguishing performance properties requiring testing. Keep your visible inspection conclusions within that boundary.")),
      section("graphics", "6. Check graphic position and visible print edges",
        p("Use the garment's centre and an agreed neckline reference to describe print position. Ask for a straight overhead photo with folds smoothed if the graphic appears tilted. If the seller provides a placement measurement, compare it using the same start point. A promotional image worn on a moving model cannot supply a dependable ruler reference."),
        p("Inspect visible edges, gaps, unintended overlaps and areas that cross a seam. Compare the complete design with the ordered option before labelling a distressed graphic as damaged. A close-up can help distinguish a fold from a break in a printed area, but it does not prove the print's adhesion or resistance to washing. Request only the extra view that can resolve the current doubt."),
        p("If both front and back are decorated, inspect them separately and record which side has the concern. Do not judge relative placement from two pictures taken at different scales. For text, check the actual lettering visible in the image rather than relying on the listing title. Describe any suspected mismatch precisely without making an authenticity claim from typography alone.")),
      section("decision-record", "7. Close the check with a specific evidence request",
        p("An effective request might read: please confirm the size label, lay the shirt flat without stretching, and photograph the chest tape from zero to the opposite edge below the armholes. Please also show the complete back graphic. This hypothetical wording tells the warehouse what to capture and gives you a way to judge whether the response answers the question."),
        table(["Current finding", "Decision step", "Avoid"], [
          ["Fit measurement unclear", "Remeasure using agreed points", "Guessing from the printed size"],
          ["Possible graphic tilt", "Request a flat overhead view", "Judging from folds or perspective"],
          ["Clear option mismatch", "Ask the agent to verify the order", "Approving because the item looks appealing"],
          ["Relevant evidence satisfactory", "Save photos and your limited conclusion", "Calling the shirt defect-free"],
        ]),
        p("Keep present condition separate from future performance. CottonWorks explains that dimensional change can occur through several material, processing and care factors; a warehouse photograph cannot predict a wash result. Save the current measurements and care information for later comparison. Finish with the ordered option, evidence checked, unresolved points and the action you chose, while confirming any return or exchange process with your agent.")),
    ],
    sources: [source("https://cottonworks.com/learning-hub/garment-manufacturing/garment-quality-control/", "CottonWorks: Garment Quality Control", "Background on garment fit, seam integrity and performance testing."), source("https://cottonworks.com/learning-hub/quality-assurance/shrinking-and-skewing/", "CottonWorks: Shrinkage & Skewing", "Explains why present measurements do not establish future dimensional stability.")],
    related: ["findqc-qc-measurements-size-guide", "hoodie-qc-checklist", "what-qc-photos-can-prove"],
    cta: { eyebrow: "Use your inspection notes", title: "Explore T-shirt listings with fit and graphic placement in mind.", label: "Browse T-shirt finds", href: "/categories/t-shirts", external: false },
  },
  {
    ...base,
    slug: "qc-weight-dimensions-shipping-estimates",
    title: "QC Weight and Dimensions: From Product Measurements to Shipping Estimates",
    shortTitle: "QC Weight and Shipping Dimensions",
    description: "Understand QC weight, parcel dimensions and actual versus volumetric weight with worked examples and a checklist for checking a shipping estimate.",
    excerpt: "Separate product measurements from the final packed parcel, calculate illustrative volume weight and ask for the inputs behind a quote.",
    category: "Shipping Evidence",
    heroImage: "/products/shoes-60.jpg",
    heroAlt: "Editorial footwear example illustrating why product and packed parcel measurements differ",
    keywords: ["QC weight", "QC dimensions", "actual weight vs volumetric weight", "shipping weight estimate", "parcel dimensions"],
    intro: [
      "QC weight and dimensions can help you plan a purchase, but only when you know what was measured. A product weighed without its box, a seller's packaged item and a final international parcel are three different objects. Using a number from one stage as if it belonged to another can make a shipping estimate look precise while its basic input is wrong.",
      "This guide separates those measurements and shows how actual weight and volumetric weight interact. The calculations are hypothetical examples, not carrier quotes or promises of savings. Use them to understand the questions to ask your shopping agent. The final service, packing, destination, measurement rules and current price schedule determine the actual quotation.",
    ],
    sections: [
      section("measurement-object", "1. Identify exactly what the QC number describes",
        p("Before calculating anything, label the object on the scale or under the tape. Is it a single garment, a shoe pair, an item with a retail box or a sealed shipping parcel? Record the units, measurement date, variant and any visible packaging. If the record does not answer those questions, preserve the number as an uncertain planning reference."),
        table(["Evidence", "Useful for", "Still missing"], [
          ["Product-only weight", "Comparing a documented item variant", "Packaging and final parcel weight"],
          ["Retail-box dimensions", "Understanding one packed item's shape", "Outer carton, cushioning and consolidation"],
          ["Historical parcel record", "Building a rough scenario", "Your exact contents and current packing"],
          ["Current final parcel measurements", "Checking a service quotation", "Service rules, rounding and applicable charges"],
        ]),
        p("A label such as dimensions is not enough by itself. Garment length and chest width describe fit, whereas three external parcel dimensions describe occupied shipping space. Do not put a shirt's body length into a carton calculator. Ask for the final packed object's length, width and height in the units the selected service expects.")),
      section("actual-volume", "2. Separate actual weight from volumetric weight",
        p("Actual weight is the measured mass of the object being weighed. Volumetric weight converts package size into a weight used for rating. DHL Express's UK guidance gives centimetres multiplied together and divided by 5,000, then compares that result with actual weight. The greater value is the chargeable basis in that guidance; the selected service's detailed rules still apply."),
        p("For an illustrative parcel measuring 40 × 30 × 25 cm, the volume is 30,000 cubic centimetres. Dividing by 5,000 gives 6 kg of volumetric weight. If that packed parcel actually weighs 4 kg, the volumetric value is larger. If it weighs 7 kg, actual weight is larger. These calculations identify a weight basis, not a currency price."),
        p("Do not assume the example divisor applies to every agent route or carrier product. Ask which divisor, dimensional rounding and weight increments the selected service uses. Keep centimetres with the corresponding kilogram formula; mixing inches into that formula produces an invalid result. Write the units beside each input before using a calculator or spreadsheet.")),
      section("worked-scenarios", "3. Compare packing scenarios without treating them as quotes",
        table(["Hypothetical packed parcel", "Actual mass", "Volume weight at divisor 5,000", "Larger value before rounding"], [
          ["40 × 30 × 25 cm", "4 kg", "6 kg", "6 kg"],
          ["40 × 30 × 20 cm", "4 kg", "4.8 kg", "4.8 kg"],
          ["40 × 30 × 25 cm", "7 kg", "6 kg", "7 kg"],
        ]),
        p("The first two rows isolate a change in height while keeping actual mass fixed for the example. Reducing the height by 5 cm reduces the calculated volume weight by 1.2 kg. That does not establish the price difference. A service may round the result, apply minimums or use a price schedule whose increments do not match the raw calculation."),
        p("The third row shows why shrinking the box does not always change the weight basis. When actual mass is already larger, a smaller volume can leave that basis unchanged. You still need to check size limits and other service conditions, but do not promise savings solely because the carton looks more compact. Compare actual quotations for available packing options."),
        p("Keep the examples separate from your order record. Replace every illustrative input with confirmed measurements before making a real decision. If a packing change also removes a retail box or adds protection, actual mass may change too; the simplified comparison no longer holds all other factors constant.")),
      section("packing", "4. Discuss packing as a protection and size decision",
        p("Ask what is included in the proposed packing: retail boxes, protective inserts, wrapping and outer carton. Explain whether any original packaging needs to be retained. Removing a box can change the parcel's shape, protection and presentation, so the right choice depends on the item and your priorities. Request the agent's available options before assuming that a particular packing method can be used."),
        p("Do not assume that separate item dimensions can simply be added. Objects may nest, leave gaps or require separation. A consolidated parcel's external dimensions must come from the actual packing arrangement or a clearly identified estimate. The sum of product-only weights also omits packaging and may not equal the final scale reading."),
        p("For a delicate or shape-sensitive item, discuss how the proposed arrangement protects it during ordinary transport handling. A smaller carton is not automatically a better outcome. Record the packing choice along with the resulting measurements so that you can understand why an estimate changed. Avoid requesting compression solely to achieve a target number without considering the contents.")),
      section("historical-data", "5. Use historical QC measurements as planning ranges",
        p("A historical measurement belongs to a particular record. Confirm the item identity and variant before borrowing it for a planning scenario. A different size, included accessory or packaging arrangement can explain a difference. If several records disagree, retain the spread and investigate the measurement context rather than selecting whichever number produces the cheapest estimate."),
        p("Build a low and high planning scenario only from plausible, documented inputs. Label which quantities are observed and which are assumptions. For example, an item-only weight may be observed while outer carton size remains unknown. In that case, calculate a few clearly hypothetical carton sizes to understand sensitivity, then replace them when the warehouse can measure the packed parcel."),
        p("Do not treat a historical average as a promise about your next shipment. An old record also says nothing by itself about a currently available service or price. The useful output of early research is a list of uncertainties and the measurement that would reduce each one. This keeps budgeting decisions tied to evidence instead of an attractive single number.")),
      section("quote-audit", "6. Ask for the inputs behind the shipping estimate",
        p("When a quotation arrives, compare the stated parcel mass and external dimensions with the measurements you requested. Confirm the selected service and destination information, then ask how the chargeable weight was calculated. Keep a copy of the quote date and packing state. A later repack can change the inputs even when the contents remain the same."),
        table(["Question to confirm", "Why it matters"], [
          ["Is this final packed weight or an estimate?", "Distinguishes an observed input from a planning value"],
          ["Which divisor and rounding rules apply?", "Explains the difference from a raw calculation"],
          ["Which charges are included in this quote?", "Prevents comparing unlike totals"],
          ["What changes after repacking or remeasurement?", "Identifies when the estimate must be refreshed"],
        ]),
        p("If the number differs from your calculation, ask for the intermediate values instead of assuming an error. The service may use different rules, dimensions may have changed or the displayed amount may include other components. Resolve the particular discrepancy. Do not infer an explanation from another customer's parcel because their service and packing may differ.")),
      section("record", "7. Keep a measurement trail from item to parcel",
        p("Maintain a short record with separate rows for the product, retail packaging and final parcel. Include the object description, dimensions, mass, units, date and source of each value. Mark estimates visibly. When the final packing is complete, update only the final-parcel row and retain earlier values so that a change has an explanation."),
        p("A useful request might say: please confirm the final sealed parcel's external length, width and height in centimetres and its scale weight in kilograms, with the agreed protection included. Please identify the selected route's volumetric divisor, rounding rules and quotation total. This hypothetical request is designed to make the calculation reviewable, not to impose a carrier rule on the agent."),
        p("Use the result to choose among the options actually offered for your parcel. If a decisive input is still missing, record the estimate as provisional. The purpose of QC weight and dimensions is to improve the quality of planning; the final packed measurements and applicable service rules are what make a shipping quotation meaningful.")),
    ],
    sources: [source("https://www.dhl.com/discover/en-gb/ship-with-dhl/products-and-services/weight-and-dimensions", "DHL Express UK: Weight and Dimensions", "Carrier-specific explanation of divisor 5,000 and actual-versus-volumetric chargeable weight. Examples in this article are independently constructed.")],
    related: ["findqc-standard-vs-premium-qc", "findqc-qc-measurements-size-guide", "findqc-product-intelligence-report-guide"],
    cta: { eyebrow: "Keep measurement types separate", title: "Checking garment fit instead? Use the ruler-photo guide.", label: "Read the measurement guide", href: "/articles/findqc-qc-measurements-size-guide", external: false },
  },
];
