import { notFound } from "next/navigation";
import Link from "next/link";
import { Arrow, CheckIcon } from "@/components/Icons";
import StructuredData from "@/components/StructuredData";
import { categories, categoryResearch, DESTINATION, SITE_URL } from "../../data";
import { languageAlternates } from "../../i18n";
import { createPageMetadata } from "../../seo";

export function generateStaticParams(){ return categories.map(c=>({slug:c.slug})); }
export async function generateMetadata({params}) { const {slug}=await params; const c=categories.find(x=>x.slug===slug); if(!c)return{}; return createPageMetadata({ title:`Hacoo ${c.name}: Product Links & Checks`, description:`Explore the Hacoo ${c.name.toLowerCase()} spreadsheet route, current catalog links and practical checks for measurements, listing details and availability.`, path:`/categories/${c.slug}`, alternates:languageAlternates(`/categories/${c.slug}`,"en") }); }

export default async function CategoryPage({params}) {
  const {slug}=await params; const c=categories.find(x=>x.slug===slug); const research=categoryResearch[slug]; if(!c||!research) notFound();
  const schema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage",name:`Hacoo ${c.name} Spreadsheet`,url:`${SITE_URL}/categories/${c.slug}/`,description:c.description,dateModified:"2026-07-15"},{"@type":"FAQPage",mainEntity:research.faqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};
  return <><StructuredData data={schema}/><section className="category-hero"><div className="category-hero-image"><img src={c.image} alt={`${c.name} discovery category`}/></div><div className="category-hero-copy"><span className="section-label">{c.eyebrow} / Hacoo category</span><h1>{c.name}<br/><em>spreadsheet.</em></h1><p>{c.description}</p><a className="button primary" href={`${DESTINATION}${c.destination}`} target="_blank" rel="noopener noreferrer">Browse live {c.name.toLowerCase()} <Arrow/></a></div></section>
    <section className="section wrap"><div className="split-copy"><div><span className="section-label">Before opening a listing</span><h2>A category-specific checklist.</h2></div><div className="stacked-checks">{c.checklist.map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div></div></section>
    <section className="soft-section"><div className="wrap"><div className="section-heading"><div><span className="section-label">What to compare</span><h2>Three useful reference points.</h2></div><p>{research.intro}</p></div><div className="research-grid">{research.comparison.map(([title,text],index)=><article className="research-card" key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="verification-note"><strong>Catalog route checked:</strong> July 15, 2026. Product options and availability can change after this review.</p></div></section>
    <section className="section wrap"><div className="story-grid"><div><span className="section-label">Avoid false matches</span><h2>Common comparison mistakes.</h2></div><div><p className="large-copy">A focused {c.name.toLowerCase()} page is useful only when the selected option, measurements and live details all refer to the same item.</p><ul className="mistake-list">{research.mistakes.map((mistake)=><li key={mistake}><CheckIcon size={18}/><span>{mistake}</span></li>)}</ul><div className="inline-links"><Link href="/guides/how-to-use-hacoo-spreadsheet">Use the spreadsheet workflow <Arrow size={16}/></Link><Link href="/guides/qc-photo-checklist">Read the photo checklist <Arrow size={16}/></Link></div></div></div></section>
    <section className="soft-section"><div className="wrap category-faq"><div><span className="section-label">Quick answers</span><h2>{c.name} research FAQ.</h2></div><div className="faq-list">{research.faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section></>;
}
