/* Full-length companion paragraphs for every localized article section.
   Each entry mirrors the English article structure; no section is collapsed. */
export const articleDetails: Record<string, Record<string, string[][]>> = {
  de: {
    "how-to-use-usfans": [
      ["Bei diesem Modell entstehen deshalb mindestens zwei getrennte Entscheidungen und meist auch zwei Zahlungen. Die erste betrifft Produkt, Variante und Inlandsversand zum Lager; die zweite betrifft das fertig gepackte internationale Paket. Wer beide Phasen in einer Kalkulation vermischt, unterschätzt leicht Kosten oder Zeit. Prüfe Statusmeldungen immer danach, ob sie vom Verkäufer, vom Lagereingang oder vom internationalen Transport stammen."],
      ["Chinesische Marktplatzangebote bündeln häufig Farben, Größen, Chargen, Zubehör oder Anzahlungen auf derselben Seite. Wähle die konkrete Option und nutze eine Bestellnotiz nur für Angaben, die der Auswahlschalter nicht abbildet. Ein ungewöhnlich niedriger Preis kann nur für ein Zubehörteil oder eine Anzahlung gelten. Ein Agent kann die ausgewählte Bestellung ausführen, aber keine unausgesprochene Präferenz zuverlässig erraten."],
      ["Kontrolliere vor dem Produktkauf auch Inlandsversand, optionale Leistungen und Stückzahl. Änderungen sind vor dem Verkäuferversand deutlich einfacher. Plane bei zeitkritischen Bestellungen Puffer für Verkäuferbearbeitung, Inlandstransport, Lagererfassung, Fotos, Verpackung und Ausfuhr ein. Die auf einer Produktseite angezeigte Lagerprognose bleibt eine Schätzung, weil der Drittverkäufer seinen Versand selbst steuert."],
      ["Öffne jedes Lagerbild in voller Größe und vergleiche es mit dem gespeicherten Angebot. Prüfe Farbe, Größenetikett, sichtbare Maße, Symmetrie, Nähte, Druckposition, Oberflächenschäden und mitgeliefertes Zubehör. Fehlt ein entscheidender Bereich, kann ein gezieltes Zusatzfoto sinnvoll sein. QC soll keine theoretische Perfektion beweisen, sondern Abweichungen erkennen, die deine Kaufentscheidung tatsächlich ändern würden."],
      ["Formuliere einen Rückgabegrund beobachtbar: etwa falsches Größenetikett, abweichende Farbe oder ein Riss an einer bestimmten Naht. Verweise auf das passende Lagerfoto und das gespeicherte Angebot und reiche den Artikel nicht in ein Paket ein, solange der Fall offen ist. Wird der Antrag abgelehnt, frage nach dem Grund und entscheide anhand von Belegen, Verkäuferregeln und voraussichtlichen Versandkosten."],
      ["Konsolidierung kann doppelte Verpackung sparen, doch ein größeres Paket ist nicht automatisch günstiger. Volumengewicht, Größenlimits und Routenbeschränkungen können zwei kleinere Pakete sinnvoller machen. Entferne Verkäuferverpackung nur, wenn die Ersparnis wichtiger ist als der Schutz. Schuhe, formstabile Taschen, Elektronik und zerbrechliches Zubehör benötigen unterschiedliche Maßnahmen gegen Druck, Feuchtigkeit oder Stöße."],
      ["Vergleiche mit den finalen Paketdaten: tatsächliches und abrechenbares Gewicht, Maße, Laufzeitspanne, Tracking, Verbote und Entschädigungsregeln. Eine Linie für normale Kleidung kann Batterien, Flüssigkeiten oder bestimmte Waren ausschließen. Lieferzeiten sind keine Termine; Ausfuhr, Kapazität, Zoll und lokaler Zusteller liegen nicht vollständig in der Hand des Lagers. Sichere Erklärung und Trackingnummer bis zur Zustellung."],
      ["Beginne mit wenigen Artikeln, deren Wartezeit und Wert du verkraften kannst. Speichere Angebot und Zahlung, prüfe jede Variante und setze dir für die Lagerfotos eine eigene Frist innerhalb des veröffentlichten Fünf-Tage-Fensters. Die meisten vermeidbaren Fehler entstehen an übersprungenen Kontrollpunkten: angenommene Varianten, nur als Miniatur betrachtete Fotos, verpasste Rückgabe oder eine als Garantie gelesene Schätzung."]
    ],
    "usfans-qc-photos-guide": [
      ["QC ist Risikoreduktion, keine Zertifizierung. Licht, Kamera und Perspektive können Farbe, Textur und Proportion verändern; innere Verarbeitung, Faseranteil, Akkuzustand oder Wasserdichtigkeit bleiben unsichtbar. Lege vorab fest, welche Mängel deine Entscheidung ändern. Ein loser Faden an einem günstigen Hoodie ist anders zu bewerten als eine falsche Schuhgröße, ein gerissenes Gehäuse oder ein fehlender Taschengurt.", "Eine sinnvolle Entscheidung kombiniert Lagerbilder, Originalangebot, Preis, Verkäuferangaben sowie Rückgabe- und Versandkosten. Dadurch vermeidest du sowohl eine unnötige Ablehnung wegen ungünstiger Beleuchtung als auch die Zustimmung zu einer teuren Abweichung, nur weil du bereits lange gewartet hast."],
      ["Erstelle je Produkt eine kurze Prüfliste. Bei Schuhen können Größenetikett, Sohlenfarbe, Zehenform und beide Seiten wichtig sein; bei Hoodies Druck, Bündchen, Reißverschluss und Maße; bei Taschen Beschläge, Riemen, Verschluss und Innenraum. Zwei Minuten Vorbereitung machen aus dem unscharfen Urteil „sieht gut aus“ einen Vergleich mit konkreten Erwartungen."],
      ["Beginne mit Typ, Farbe, Größe und Menge und gehe danach Front, Rückseite, Seiten, Etiketten und Messbilder durch. Ein fehlender Winkel beweist keinen Fehler, rechtfertigt aber Zurückhaltung, wenn genau dieser Bereich kaufentscheidend ist. Bitte dann um eine einzelne klare Aufnahme, etwa das Größenetikett neben einem Lineal, statt allgemein nach „mehr QC“ zu fragen."],
      ["Betrachte linkes und rechtes Paar zusammen: Zehenform, Fersenstand, Paneele, Nähte, Kleberänder und Sohlenfarbe. Vergleiche verfügbare Innen- oder Außensohlenmaße mit einem passenden eigenen Paar, weil Größenangaben verschiedener Hersteller abweichen können. Breite Kamerawinkel verzerren die Form am Bildrand; deutliche Größenfehler oder beschädigte Sohlen sollten dennoch vor dem teuren internationalen Versand geklärt werden."],
      ["Bei Oberteilen sind Lagermaße oft aussagekräftiger als das Etikett. Vergleiche Brustweite, Länge und Ärmel mit Größentabelle und eigener Kleidung. Nutze Nähte und Ausschnitt als gerade Referenzen für Drucke, Stickereien, Namen, Nummern und Patches. Bei dunklen Stoffen hilft vorsichtig erhöhte Bildschirmhelligkeit, ohne Schatten vorschnell als Flecken zu deuten."],
      ["Eine schöne Vorderansicht sagt wenig über Reißverschluss, Schnalle oder Innenraum. Prüfe Silhouette, Kantenfarbe, Griff- und Riemenbefestigung sowie alle abnehmbaren Teile der gewählten Variante. Bei kleinen Zubehör- oder Elektronikteilen sind verbogene Stifte, fehlende Schrauben, Risse und Kratzer sichtbar; ein sauberes Foto beweist jedoch weder Funktion noch Akkuleistung."],
      ["Nutze drei klare Ergebnisse: behalten, wenn sichtbare Merkmale passen; gezielt nachfragen, wenn ein entscheidender Beleg fehlt; Rückgabe beantragen, wenn Abweichung, Schaden oder Verarbeitung bereits unakzeptabel sind. Das verhindert endlose Prüfung. Reiche Problem, Foto und widersprechende Angebotsangabe innerhalb des Fünf-Tage-Fensters ein und halte den Artikel aus der Paketeinreichung heraus."],
      ["Bewahre ausgewählte Variante, Lagerbilder, Messnotizen und Supportantworten bis nach der Lieferung gemeinsam auf. Notiere kurz sichtbares Ergebnis, offene Frage, Datum und endgültige Entscheidung. So kannst du später echte Ware und Foto vergleichen und lernst, welche Blickwinkel verlässlich waren.", "Eine disziplinierte Routine ist wertvoller als die Suche nach einer angeblich perfekten Charge: zuerst die entscheidenden Punkte prüfen, Frist respektieren und aufhören, sobald die Belege eine Entscheidung tragen. USFans liefert den Foto-Kontrollpunkt; seinen Nutzen erzeugt der Käufer durch sorgfältige Prüfung vor dem Grenztransport."]
    ],
    "usfans-review-2026": [
      ["Die konkreten öffentlichen Aussagen müssen genau gelesen werden. Drei bis sieben kostenlose HD-Fotos sind ein visueller Kontrollpunkt, keine Zusicherung zu Material oder Echtheit. Auch ein Rückgabeantrag innerhalb von fünf Tagen bedeutet nicht automatisch, dass jeder Marktplatzverkäufer jede Rückgabe akzeptiert. Das Agentenmodell verteilt Verantwortung auf Verkäufer, Lager, Käufer und späteren Transporteur."],
      ["Besonders nützlich ist das Modell für Käufer, die Lagerbilder wirklich öffnen, mit dem Original vergleichen und mehrere Bestellungen vor dem Paketentscheid zusammenführen. Wer jedes Bild ungeprüft bestätigt oder die zweite Versandzahlung ignoriert, nutzt den wichtigsten Schutz kaum. Die Plattform ersetzt weder Produktrecherche noch die Bewertung von Kosten, Einschränkungen und Laufzeit einer Route."],
      ["Am Stichtag war die Verteilung deutlich positiv, hatte aber einen relevanten negativen Rand. Der Hinweis auf entfernte gefälschte Bewertungen ist ein zusätzlicher Grund, nicht nur auf Durchschnitt oder Sterne zu schauen. Wiederkehrende Themen sind aussagekräftiger: Positiv wurden Bedienung, QC, Verpackung, Support und termingerechte Ankunft genannt; kritisch erschienen Kommunikation, Verzögerung, Gewichtsberechnung, Kosten und Tracking."],
      ["Glaubwürdiger sind Berichte mit konkreten Umständen: Produkt, Zielland, Dauer einer Stufe oder Lösung eines Problems. Solche Erfahrungen passen zum vorgesehenen Ablauf, wenn Verkäufer, Lagerfotos, Route und Support zusammenspielen. Aussagen wie „am besten“ oder „am billigsten“ bleiben dagegen persönliche Vergleiche; Preise ändern sich nach Ziel, Route, Paketmaßen und Aktionen und sind keine dauerhafte Eigenschaft."],
      ["Ordne Beschwerden der richtigen Stufe zu: bezahlt, aber noch nicht gekauft; gekauft, aber nicht versandt; Inlandstransport; Lageraufnahme; Paketbearbeitung; oder noch keine physische Annahme durch den internationalen Carrier. USFans verweist bei der Lieferung zum Lager nachvollziehbar auf Drittverkäufer. Das erklärt jedoch nicht automatisch jede Frage zu Lagerbearbeitung, Paketentscheidung oder Reaktionszeit. Eine genaue letzte Statusstufe verbessert jede Eskalation."],
      ["Die Daten zeigen eine aktive Plattform mit veröffentlichtem Lager- und Fotoprozess sowie vielen gemischten Erfahrungen, aber keine risikofreie Garantie. Starte mit einem tragbaren Wert, nutze eine Zahlungsart mit geeigneten Nachweisen, sichere Angebot und Supportgespräche und prüfe jede Auswahl. Kaufe keine verbotenen Waren und lies aktuelle Routen- und Entschädigungsbedingungen, statt Zoll oder Zustellung vorauszusetzen."],
      ["Geeignet ist der Dienst für Käufer, die verschiedene Marktplatzverkäufer verstehen, Zeit für mehrere Bearbeitungsstufen einplanen und Fotos sowie Routen aktiv vergleichen. Weniger geeignet ist er für einen einzigen All-inclusive-Preis, garantierte Echtheit, garantierte Zustellung oder sofortige Hilfe rund um die Uhr. Bei einem Termin, den schon eine Verkäuferverzögerung unbrauchbar macht, ist das Modell besonders riskant."],
      ["Das faire Urteil ist bedingt: Einkauf, Lagereingang, echte Fotos, angegebenes Rückgabefenster und internationale Pakethandhabung sind nützliche Werkzeuge; zugleich dokumentieren öffentliche Stimmen ernsthafte Probleme bei Kommunikation, Zeit und Kosten. Hohe Fünf-Sterne-Anteile und eine erhebliche Ein-Sterne-Gruppe müssen gemeinsam betrachtet werden.", "Lies vor der ersten Bestellung aktuelle Bedingungen statt alte Videos oder Couponversprechen. Trenne während des Ablaufs Verkäuferangebot, Lagerbelege und Supportantworten. Prüfe vor dem Versand Endpaket und Route und vergleiche nach der Lieferung den Artikel mit den Lagerbildern. Diese belegorientierte Methode ist langsamer als Hype, führt aber zu einer belastbareren Entscheidung."]
    ]
  },
  es: {
    "how-to-use-usfans": [
      ["Por eso conviene tratar compra y envío como dos decisiones y, normalmente, dos pagos. La primera fase cubre artículo, variante y traslado nacional al almacén; la segunda usa los datos del paquete ya preparado. Si se mezclan ambas, es fácil infravalorar coste o plazo. Lee cada estado identificando si depende del vendedor, de la recepción del almacén o del transportista internacional."],
      ["Los anuncios chinos suelen reunir colores, tallas, lotes, accesorios e incluso depósitos en una sola página. Selecciona la opción exacta y usa notas solo cuando el selector no pueda expresar un dato. Un precio muy inferior puede corresponder a una pieza parcial. El agente ejecuta una instrucción concreta, pero no puede adivinar con seguridad una preferencia que nunca se indicó."],
      ["Antes de pagar confirma también cantidad, transporte nacional y servicios opcionales. Corregir un duplicado o una talla equivocada es mucho más fácil antes de que el vendedor envíe. Para una compra con fecha límite, añade margen para preparación del vendedor, tránsito interno, registro, fotos, embalaje y exportación. La estimación de llegada al almacén no controla al vendedor externo."],
      ["Abre cada imagen a tamaño completo y compárala con la captura guardada. Revisa color, etiqueta, medidas visibles, simetría, costuras, posición del estampado, daños y accesorios. Si falta una zona decisiva, valora pedir una foto concreta antes de que termine el plazo. El objetivo del QC no es prometer perfección, sino encontrar una diferencia capaz de cambiar tu decisión."],
      ["Describe una devolución mediante hechos observables: etiqueta de talla incorrecta, color distinto del negro elegido o rotura junto a una costura. Señala la foto y el detalle del anuncio, y no incluyas el artículo en un paquete mientras el caso siga abierto. Si el vendedor rechaza la solicitud, pide la razón y decide con pruebas, condiciones de posventa y coste probable del envío."],
      ["Consolidar puede eliminar embalaje duplicado, pero un paquete mayor no siempre es más barato. El peso volumétrico, los límites de tamaño y las restricciones pueden favorecer dos paquetes. Retira cajas solo cuando el ahorro compense la pérdida de protección. Calzado, bolsos rígidos, electrónica y artículos frágiles requieren decisiones distintas sobre refuerzo, humedad y golpes."],
      ["Compara peso real y facturable, dimensiones, rango de tránsito, seguimiento, artículos prohibidos y compensación. Una ruta para ropa normal puede rechazar baterías, líquidos u otros productos. Los plazos son rangos, porque exportación, vuelos, aduanas y reparto local no dependen por completo del almacén. Guarda declaración y número de seguimiento hasta recibir un escaneo físico del transportista."],
      ["Para empezar, usa pocos artículos cuyo valor y espera puedas asumir. Guarda cada anuncio y pago, verifica variantes y fija un recordatorio para revisar fotos dentro de los cinco días publicados. Muchos fallos evitables nacen al saltarse un control: suponer la variante, aprobar miniaturas, perder la devolución o convertir una estimación en promesa. Compara al menos dos rutas compatibles antes de pagar el paquete."]
    ],
    "usfans-qc-photos-guide": [
      ["El QC reduce riesgo, pero no certifica. Iluminación, cámara y perspectiva alteran color, textura y forma; tampoco enseñan composición interna, batería, impermeabilidad o autenticidad. Decide antes qué defectos cambiarían tu compra. Un hilo suelto en una sudadera económica no equivale a una talla de zapato errónea, una carcasa rota o una correa ausente.", "Combina imágenes, anuncio original, precio, datos del vendedor y coste de devolver o enviar. Así evitas rechazar por una foto poco favorecedora y también aceptar una diferencia cara solo porque ya esperaste. La evidencia visual sirve cuando se interpreta dentro del contexto correcto."],
      ["Prepara una lista breve por categoría. En zapatos: etiqueta, color de suela, puntera y ambos laterales; en sudaderas: estampado, puños, cremallera y medidas; en bolsos: herrajes, correa, cierre e interior. Dos minutos antes del pedido convierten un simple «se ve bien» en una comparación con expectativas concretas."],
      ["Empieza por tipo, color, talla y cantidad; después recorre frente, espalda, laterales, etiquetas y mediciones. Un ángulo ausente no demuestra un defecto, pero impide una conclusión firme si esa zona es crítica. Pide una imagen específica, por ejemplo la etiqueta junto a una regla, en lugar de solicitar vagamente «más fotos»."],
      ["Compara ambos zapatos como pareja: punteras, talones, paneles, costuras, pegamento y suelas. Si hay medidas, contrástalas con un par propio que te quede bien, porque las etiquetas varían entre fábricas. El gran angular puede deformar los bordes, pero una talla incorrecta, una asimetría fuerte o una suela dañada deben resolverse antes del costoso envío internacional."],
      ["En ropa, las medidas de almacén suelen aportar más que la etiqueta. Compara pecho, largo y manga con la tabla y con una prenda tuya. Usa costuras y cuello como líneas de referencia para estampados, bordados, nombres, números y parches. En prendas oscuras, aumenta el brillo con cuidado para no confundir pliegues y sombras con manchas."],
      ["Una buena vista frontal no confirma cremallera, hebilla ni interior. Revisa silueta, pintura de cantos, unión de asas y correas y todas las piezas desmontables. En accesorios y electrónica pueden verse clavijas dobladas, tornillos ausentes, plástico agrietado o metal rayado, pero una foto limpia no demuestra capacidad de batería ni funcionamiento."],
      ["Usa tres resultados: conservar cuando coincide y las imperfecciones son aceptables; pedir una prueba cuando falta un detalle decisivo; devolver cuando ya se ve error, daño o construcción inaceptable. Presenta descripción, foto y dato contradictorio dentro del plazo de cinco días. Mantén el artículo fuera del paquete mientras se resuelve la posventa."],
      ["Conserva variante elegida, fotos, medidas y respuestas de soporte hasta la entrega. Anota resultado visible, pregunta pendiente, fecha y acción final. Después podrás comparar el producto real con el registro y aprender qué ángulos fueron fiables.", "Una rutina disciplinada vale más que perseguir un lote perfecto: define primero lo que justificaría devolver, revisa esos puntos, respeta el plazo y detente cuando la evidencia permita decidir. USFans aporta el punto de control; el comprador obtiene su valor al usarlo antes de cruzar fronteras."]
    ],
    "usfans-review-2026": [
      ["Las afirmaciones públicas deben leerse con precisión. De tres a siete fotos HD son un control visual, no una garantía de materiales o autenticidad. Solicitar devolución durante cinco días tampoco obliga automáticamente a todos los vendedores a aceptarla. El proceso distribuye responsabilidades entre vendedor, almacén, comprador y, más tarde, transportista."],
      ["El modelo beneficia a quien abre las fotos, las compara con el anuncio y agrupa compras antes de decidir el paquete. Aprobar todo sin mirar o ignorar el segundo pago reduce gran parte de esa ventaja. USFans es una herramienta para un comprador informado; no sustituye la investigación del producto ni la comparación de coste, restricciones y plazo."],
      ["La distribución del día estudiado era claramente positiva, pero incluía una cola negativa relevante. El aviso de reseñas falsas retiradas obliga a mirar algo más que la media. Los patrones repetidos son más útiles: facilidad, QC, embalaje, ayuda y entregas previstas en positivo; comunicación, demoras, peso, coste y seguimiento en negativo."],
      ["Los testimonios más creíbles explican producto, destino, duración de una fase o solución del problema. Encajan con el proceso cuando vendedor, fotos, ruta y soporte funcionan juntos. «El mejor» o «el más barato» son comparaciones personales, no hechos permanentes: las tarifas dependen del país, la ruta, las características del paquete y las promociones."],
      ["Asigna cada queja a su fase: pagado sin comprar, comprado sin enviar, tránsito nacional, registro de almacén, preparación del paquete o falta de aceptación física del transportista. Que el vendedor controle la entrega nacional es una explicación razonable, pero no resuelve automáticamente dudas sobre procesamiento, decisiones de paquete o rapidez de soporte. Un estado preciso facilita la escalada."],
      ["La evidencia muestra una plataforma operativa con proceso publicado y abundante feedback mixto, no una garantía sin riesgo. Empieza con un valor asumible, utiliza un pago con registros adecuados, guarda anuncio y conversaciones y verifica cada selección. No compres mercancía prohibida ni des por hecho el resultado aduanero; lee restricciones y compensación actuales."],
      ["Puede encajar con compradores que entienden a los vendedores, aceptan varias etapas y comparan activamente fotos y rutas. Encaja peor con quien espera un único precio total, fecha garantizada, autenticidad garantizada o respuesta inmediata siempre. También es arriesgado para una compra urgente cuyo objetivo se pierde si el vendedor se retrasa."],
      ["El veredicto razonable es condicional: compra, recepción, fotos reales, plazo publicado y gestión del paquete son herramientas útiles; a la vez, las opiniones recogen problemas serios de comunicación, tiempo y coste. Las cinco estrellas y el grupo de una estrella deben leerse juntos.", "Antes de comprar, consulta condiciones actuales en lugar de vídeos antiguos. Durante el pedido separa anuncio, prueba del almacén y soporte; antes de enviar revisa paquete y ruta; al recibir compara el producto con las fotos. Este método basado en pruebas es menos rápido que el entusiasmo publicitario, pero produce una decisión más sólida."]
    ]
  },
  fr: {
    "how-to-use-usfans": [
      ["Il faut donc traiter achat et expédition comme deux décisions, souvent deux paiements. La première couvre article, variante et transport national vers l’entrepôt ; la seconde dépend du colis emballé. Les confondre conduit à sous-estimer coût et délai. Lisez chaque statut en identifiant s’il relève du vendeur, de la réception USFans ou du transporteur international."],
      ["Une annonce chinoise peut réunir couleurs, tailles, lots, accessoires et acomptes. Choisissez l’option exacte et réservez la remarque aux informations que le sélecteur ne permet pas d’exprimer. Un prix anormalement bas peut concerner une pièce ou un dépôt. L’agent exécute une instruction précise, mais ne peut deviner de façon fiable une préférence non formulée."],
      ["Avant paiement, contrôlez quantité, livraison nationale et services facultatifs. Une erreur se corrige plus facilement avant l’envoi du vendeur. Pour un achat urgent, prévoyez vendeur, transit intérieur, enregistrement, photos, emballage et exportation. L’arrivée estimée à l’entrepôt reste une estimation puisque le vendeur tiers contrôle sa propre préparation."],
      ["Ouvrez chaque image en grand et comparez-la à l’annonce sauvegardée. Vérifiez couleur, étiquette, mesures visibles, symétrie, coutures, placement, dommages et accessoires. Si une zone décisive manque, demandez une photo ciblée avant l’échéance. Le QC ne promet pas la perfection : il sert à repérer l’écart assez important pour modifier votre décision."],
      ["Décrivez un retour par des faits observables : mauvaise taille, couleur différente ou déchirure près d’une couture. Citez la photo et l’élément de l’annonce, et n’ajoutez pas l’article au colis pendant le dossier. En cas de refus, demandez le motif puis arbitrez selon preuves, conditions vendeur et coût probable du transport international."],
      ["Consolider peut réduire les emballages, mais un gros colis n’est pas toujours moins cher. Poids volumétrique, limites et restrictions peuvent favoriser deux colis. Retirez une boîte seulement si l’économie vaut la protection perdue. Chaussures, sacs structurés, électronique et objets fragiles exigent des choix différents de renfort et de protection."],
      ["Comparez poids réel et facturable, dimensions, délai, suivi, interdictions et indemnisation. Une route adaptée aux vêtements peut refuser batteries ou liquides. Les délais restent des fourchettes : export, capacité aérienne, douane et dernier kilomètre échappent en partie à l’entrepôt. Conservez déclaration et suivi jusqu’au premier scan physique du transporteur."],
      ["Commencez par peu d’articles dont vous pouvez supporter valeur et attente. Gardez chaque annonce et paiement, confirmez les variantes et fixez un rappel dans les cinq jours publiés. Beaucoup d’erreurs viennent d’un contrôle sauté : option supposée, miniature approuvée, retour manqué ou estimation prise pour promesse. Comparez au moins deux routes compatibles avant de payer le colis."]
    ],
    "usfans-qc-photos-guide": [
      ["Le QC réduit le risque sans certifier. Éclairage et perspective modifient couleur, texture et forme ; composition, batterie, étanchéité ou authenticité restent invisibles. Définissez d’abord les défauts qui changeraient votre choix. Un fil libre sur un sweat peu coûteux n’équivaut pas à une mauvaise pointure, une coque fendue ou une bandoulière absente.", "Combinez photos, annonce, prix, informations vendeur et coûts de retour ou d’envoi. Vous évitez ainsi de rejeter pour une lumière défavorable, mais aussi d’accepter un écart coûteux simplement parce que vous avez déjà attendu. La preuve visuelle n’est utile qu’avec son contexte."],
      ["Préparez une courte liste par article : pointure, semelle, forme et côtés pour les chaussures ; impression, poignets, zip et mesures pour un hoodie ; métal, sangle, fermeture et intérieur pour un sac. Deux minutes avant achat transforment « cela semble correct » en comparaison avec des attentes précises."],
      ["Commencez par type, couleur, taille et quantité, puis examinez face, dos, côtés, étiquettes et mesures. Un angle absent ne prouve pas un défaut, mais interdit une conclusion sûre si la zone est décisive. Demandez une vue précise, par exemple l’étiquette près d’une règle, plutôt qu’un vague « plus de QC »."],
      ["Comparez les deux chaussures : bouts, talons, empiècements, coutures, colle et semelles. Une mesure disponible doit être rapprochée d’une paire qui vous va, car les tailles varient entre fabricants. Le grand angle déforme parfois les bords, mais taille erronée, forte asymétrie ou semelle abîmée doivent être réglées avant un transport international coûteux."],
      ["Pour les vêtements, les mesures d’entrepôt comptent souvent plus que l’étiquette. Comparez poitrine, longueur et manches avec le tableau et une pièce personnelle. Utilisez coutures et col comme lignes pour impression, broderie, nom, numéro et écusson. Sur tissu sombre, augmentez prudemment la luminosité sans confondre ombre et tache."],
      ["Une belle face avant ne valide ni zip, ni boucle, ni intérieur. Vérifiez silhouette, peinture des bords, attaches des poignées et toutes les pièces amovibles. Sur accessoires et électronique, broches tordues, vis absentes, plastique fendu ou métal rayé peuvent être visibles ; une photo propre ne prouve ni fonctionnement ni capacité de batterie."],
      ["Utilisez trois issues : garder si le visible correspond ; demander une preuve si un détail décisif manque ; retourner si erreur, dommage ou finition inacceptable sont déjà visibles. Joignez description, photo et élément contradictoire dans les cinq jours et gardez l’article hors du colis tant que l’après-vente n’est pas résolu."],
      ["Conservez variante, images, mesures et réponses jusqu’à la livraison. Notez résultat visible, question, date et action. Vous pourrez comparer le produit reçu au dossier et apprendre quels angles étaient fiables.", "Une routine disciplinée vaut mieux que la quête d’un lot parfait : définissez les motifs de retour, contrôlez-les en premier, respectez l’échéance et arrêtez lorsque les preuves suffisent. USFans fournit le point photo ; le client en tire la valeur avant le passage des frontières."]
    ],
    "usfans-review-2026": [
      ["Les déclarations publiques doivent être interprétées précisément. Trois à sept photos HD constituent un contrôle visuel, pas une garantie de matière ou d’authenticité. Une demande en cinq jours n’oblige pas chaque vendeur à accepter tout retour. Le modèle répartit les responsabilités entre vendeur, entrepôt, acheteur et transporteur."],
      ["Le système sert surtout celui qui ouvre les images, les compare à l’annonce et regroupe ses achats avant le colis. Tout approuver sans regarder ou oublier le second paiement réduit son intérêt. USFans est un outil pour acheteur informé, pas un substitut à la recherche produit ni à l’évaluation du coût, des restrictions et du délai."],
      ["La distribution observée était fortement positive mais conservait une part négative significative. L’avis concernant des faux commentaires supprimés impose de dépasser la moyenne. Les thèmes récurrents comptent davantage : simplicité, QC, emballage, aide et livraison prévue d’un côté ; communication, retard, poids, coût et suivi de l’autre."],
      ["Les récits les plus crédibles précisent article, destination, durée d’une étape ou résolution. Ils correspondent au parcours quand vendeur, photos, route et support fonctionnent ensemble. « Meilleur » ou « moins cher » reste un jugement personnel : les tarifs changent selon pays, route, dimensions et promotions et ne constituent pas une propriété permanente."],
      ["Rattachez une plainte à son étape : payé non acheté, acheté non expédié, transit national, réception, emballage ou absence de scan physique international. Que le vendeur contrôle l’arrivée locale est plausible, mais cela ne répond pas automatiquement au traitement d’entrepôt, aux choix de colis ou au support. Un dernier statut précis rend l’escalade plus utile."],
      ["Les éléments montrent une plateforme active avec processus publié et retours nombreux mais mixtes, non une garantie sans risque. Commencez par une valeur supportable, utilisez un paiement traçable, gardez annonce et conversations et vérifiez chaque choix. Évitez les marchandises interdites et lisez restrictions et indemnisation actuelles sans présumer de la douane."],
      ["USFans peut convenir à ceux qui comprennent les vendeurs, acceptent plusieurs étapes et comparent photos et routes. Il convient moins à une attente de prix unique, date garantie, authenticité garantie ou aide instantanée permanente. Il est aussi mal adapté à un achat urgent qu’un simple retard vendeur rendrait inutile."],
      ["Le verdict raisonnable reste conditionnel : achat, réception, photos réelles, fenêtre annoncée et gestion du colis sont utiles ; les avis décrivent aussi des problèmes sérieux de communication, temps et coût. Les cinq étoiles et la part d’une étoile doivent être lues ensemble.", "Avant l’achat, consultez les conditions présentes plutôt qu’une ancienne vidéo. Séparez annonce, preuve d’entrepôt et support ; avant expédition, vérifiez colis et route ; après livraison, comparez l’article au dossier. Cette méthode fondée sur les preuves est moins rapide que le discours promotionnel, mais plus solide."]
    ]
  },
  it: {
    "how-to-use-usfans": [
      ["Considera quindi acquisto e spedizione come due decisioni e spesso due pagamenti. La prima fase riguarda articolo, variante e trasporto nazionale al magazzino; la seconda usa i dati del pacco finito. Confonderle porta a sottostimare costi e tempi. Leggi ogni stato chiedendoti se dipende dal venditore, dalla ricezione USFans o dal vettore internazionale."],
      ["Le inserzioni cinesi possono riunire colori, taglie, lotti, accessori e depositi. Seleziona l’opzione esatta e usa le note solo per dati non esprimibili dal menu. Un prezzo molto basso può riguardare un componente o un anticipo. L’agente esegue istruzioni precise, ma non può indovinare con certezza una preferenza mai dichiarata."],
      ["Prima del pagamento controlla quantità, consegna nazionale e servizi opzionali. Una taglia o riga duplicata si corregge più facilmente prima della spedizione del venditore. Se hai una scadenza, aggiungi margine per preparazione, transito interno, registrazione, foto, imballaggio ed export. La stima di arrivo non controlla i tempi del venditore terzo."],
      ["Apri ogni foto a piena dimensione e confrontala con l’inserzione salvata. Verifica colore, etichetta, misure visibili, simmetria, cuciture, posizione della stampa, danni e accessori. Se manca una zona decisiva, chiedi uno scatto mirato prima della scadenza. Il QC non dimostra perfezione: individua differenze abbastanza importanti da cambiare la decisione."],
      ["Descrivi un reso con fatti osservabili: etichetta errata, colore diverso o strappo vicino a una cucitura. Indica foto e dettaglio dell’inserzione e non inviare l’articolo mentre la pratica è aperta. Se il venditore rifiuta, chiedi il motivo e valuta prove, regole post-vendita e costo probabile del trasporto internazionale."],
      ["Consolidare può eliminare imballaggi doppi, ma un pacco grande non è sempre più economico. Peso volumetrico, limiti e restrizioni possono rendere migliori due colli. Rimuovi scatole solo se il risparmio vale la protezione persa. Scarpe, borse rigide, elettronica e oggetti fragili richiedono scelte diverse su rinforzo, umidità e urti."],
      ["Confronta peso reale e fatturabile, dimensioni, intervallo, tracking, divieti e compensazione. Una rotta per abbigliamento può rifiutare batterie o liquidi. I tempi sono intervalli: export, capacità aerea, dogana e ultimo miglio non dipendono del tutto dal magazzino. Conserva dichiarazione e tracking fino a un’effettiva scansione del vettore."],
      ["Inizia con pochi articoli di valore e attesa sostenibili. Salva inserzioni e pagamenti, verifica le varianti e imposta un promemoria entro i cinque giorni pubblicati. Molti errori derivano da un controllo saltato: opzione presunta, miniatura approvata, reso perso o stima letta come promessa. Confronta almeno due rotte compatibili prima di pagare."]
    ],
    "usfans-qc-photos-guide": [
      ["Il QC riduce il rischio senza certificare. Luce e prospettiva alterano colore, trama e forma; composizione, batteria, impermeabilità e autenticità restano invisibili. Definisci prima quali difetti cambierebbero la scelta. Un filo su una felpa economica è diverso da una taglia scarpa errata, una scocca rotta o una tracolla mancante.", "Combina foto, inserzione, prezzo, dati del venditore e costo di reso o spedizione. Così eviti sia un rifiuto causato da luce sfavorevole, sia l’accettazione di una differenza costosa solo perché hai già aspettato. L’evidenza visiva funziona solo nel suo contesto."],
      ["Prepara una lista breve: etichetta, suola, punta e lati per scarpe; stampa, polsi, zip e misure per felpe; metallo, tracolla, chiusura e interno per borse. Due minuti prima dell’ordine trasformano “sembra bello” in un confronto con aspettative verificabili."],
      ["Controlla prima tipo, colore, taglia e quantità, poi fronte, retro, lati, etichette e misure. Un angolo assente non prova un difetto, ma impedisce certezza se l’area è decisiva. Chiedi una vista specifica, per esempio etichetta accanto al righello, invece di un generico “più QC”."],
      ["Confronta le scarpe come coppia: punte, talloni, pannelli, cuciture, colla e suole. Se disponibili, confronta le misure con una scarpa che calza bene, perché le taglie variano. Il grandangolo può deformare i bordi, ma taglia sbagliata, forte asimmetria o suola danneggiata vanno risolte prima del costoso invio internazionale."],
      ["Per l’abbigliamento le misure del magazzino valgono spesso più dell’etichetta. Confronta torace, lunghezza e manica con tabella e capo personale. Usa cuciture e collo come linee per stampa, ricamo, nome, numero e patch. Sui tessuti scuri aumenta con cautela la luminosità senza scambiare ombre per macchie."],
      ["Una bella vista frontale non conferma zip, fibbia o interno. Controlla profilo, bordi, attacchi di manici e tracolle e componenti rimovibili. Negli accessori possono vedersi perni piegati, viti mancanti, plastica crepata o metallo graffiato; una foto pulita non dimostra funzione o capacità della batteria."],
      ["Usa tre esiti: tieni se coincide; chiedi prova se manca un dettaglio decisivo; rendi se errore, danno o lavorazione inaccettabile sono visibili. Invia descrizione, foto e dato contrario entro cinque giorni e lascia l’articolo fuori dal pacco finché il post-vendita non è risolto."],
      ["Conserva variante, immagini, misure e risposte fino alla consegna. Annota risultato, domanda, data e azione, poi confronta il prodotto ricevuto con il registro per capire quali angoli erano affidabili.", "Una routine disciplinata vale più della ricerca del lotto perfetto: definisci prima i motivi di reso, controllali, rispetta la scadenza e fermati quando le prove bastano. USFans offre il punto fotografico; il compratore ne crea il valore prima del confine."]
    ],
    "usfans-review-2026": [
      ["Le dichiarazioni pubbliche vanno lette con precisione. Tre-sette foto HD sono un controllo visivo, non garanzia di materiale o autenticità. La richiesta entro cinque giorni non obbliga ogni venditore ad accettare ogni reso. Il modello divide responsabilità fra venditore, magazzino, acquirente e vettore."],
      ["Il sistema serve soprattutto chi apre le foto, le confronta con l’inserzione e consolida prima di decidere il pacco. Approvare tutto senza guardare o ignorare il secondo pagamento riduce il vantaggio. USFans è uno strumento per un compratore informato, non sostituisce ricerca del prodotto e valutazione di costo, limiti e tempi."],
      ["La distribuzione era molto positiva ma con una coda negativa rilevante. L’avviso sulle recensioni false rimosse impone di guardare oltre la media. Contano i temi ripetuti: semplicità, QC, imballo, assistenza e arrivi previsti in positivo; comunicazione, ritardi, peso, costo e tracking in negativo."],
      ["I racconti più credibili specificano articolo, destinazione, durata di una fase o soluzione. Funzionano con il modello quando venditore, foto, rotta e supporto si allineano. “Migliore” o “più economico” resta personale: le tariffe variano con paese, rotta, caratteristiche del pacco e promozioni."],
      ["Assegna ogni reclamo alla fase: pagato non acquistato, acquistato non spedito, transito nazionale, ingresso, imballaggio o mancata scansione fisica internazionale. Che il venditore controlli l’arrivo locale è plausibile, ma non risponde automaticamente a lavorazione, scelte del pacco o velocità del supporto. Uno stato preciso aiuta l’escalation."],
      ["Le prove mostrano una piattaforma attiva con processo pubblicato e molto feedback misto, non assenza di rischio. Inizia con valore sostenibile, usa pagamenti tracciabili, salva inserzione e chat e verifica ogni scelta. Evita merci vietate e leggi limiti e compensazione correnti senza presumere la dogana."],
      ["Può essere adatto a chi comprende i venditori, accetta più fasi e confronta foto e rotte. È meno adatto a prezzo unico, data garantita, autenticità garantita o supporto immediato continuo. È rischioso anche per un acquisto urgente che un semplice ritardo del venditore renderebbe inutile."],
      ["Il verdetto è condizionale: acquisto, ricezione, foto reali, finestra dichiarata e gestione del pacco sono utili; le opinioni documentano anche problemi seri di comunicazione, tempo e costo. Cinque stelle e quota a una stella vanno lette insieme.", "Prima dell’ordine consulta condizioni attuali, non vecchi video. Separa inserzione, prova di magazzino e supporto; prima dell’invio verifica pacco e rotta; dopo la consegna confronta l’articolo con le foto. Il metodo basato su prove è meno rapido dell’hype, ma più affidabile."]
    ]
  },
  pl: {
    "how-to-use-usfans": [
      ["Traktuj zakup i wysyłkę jako dwie decyzje i zwykle dwie płatności. Pierwsza obejmuje produkt, wariant i transport krajowy do magazynu; druga zależy od gotowej paczki. Ich mieszanie zaniża koszt i czas. Każdy status odczytuj według odpowiedzialności sprzedawcy, przyjęcia przez USFans albo międzynarodowego przewoźnika."],
      ["Chińska oferta może łączyć kolory, rozmiary, partie, dodatki i zaliczki. Wybierz dokładną opcję, a uwagę stosuj tylko do danych, których nie ma w selektorze. Nietypowo niska cena może dotyczyć części lub depozytu. Agent realizuje jasne polecenie, lecz nie może pewnie odgadnąć niewypowiedzianej preferencji."],
      ["Przed płatnością sprawdź ilość, dostawę krajową i usługi dodatkowe. Błąd łatwiej poprawić przed wysyłką sprzedawcy. Przy terminowym zakupie dodaj zapas na przygotowanie, krajowy tranzyt, rejestrację, zdjęcia, pakowanie i eksport. Szacowane przyjęcie nie kontroluje czasu zewnętrznego sprzedawcy."],
      ["Otwórz każde zdjęcie w pełnym rozmiarze i porównaj z zapisaną ofertą. Sprawdź kolor, metkę, widoczne wymiary, symetrię, szwy, położenie nadruku, uszkodzenia i dodatki. Jeśli brakuje kluczowego miejsca, poproś o konkretne ujęcie przed terminem. QC nie dowodzi perfekcji, lecz wykrywa różnicę zmieniającą decyzję."],
      ["Opisz zwrot obserwowalnymi faktami: zła metka, inny kolor albo rozdarcie przy szwie. Wskaż zdjęcie i fragment oferty, a produktu nie dodawaj do paczki podczas sprawy. Po odmowie zapytaj o powód i oceń dowody, zasady sprzedawcy oraz prawdopodobny koszt wysyłki międzynarodowej."],
      ["Konsolidacja usuwa powtórne opakowania, ale większa paczka nie zawsze jest tańsza. Waga objętościowa, limity i ograniczenia mogą przemawiać za dwoma paczkami. Usuń pudełko tylko, gdy oszczędność przewyższa ochronę. Buty, sztywne torby, elektronika i kruche akcesoria wymagają innych zabezpieczeń."],
      ["Porównaj wagę rzeczywistą i rozliczeniową, wymiary, czas, tracking, zakazy i odszkodowanie. Trasa dla odzieży może odrzucać baterie lub płyny. Terminy są przedziałami, bo eksport, loty, cło i dostawa lokalna nie zależą całkowicie od magazynu. Zachowaj deklarację i numer do fizycznego skanu przewoźnika."],
      ["Zacznij od kilku rzeczy o akceptowalnej wartości i czasie. Zapisz oferty i płatności, potwierdź warianty i ustaw przypomnienie w pięciodniowym oknie. Wiele błędów wynika z pominięcia kontroli: założonego wariantu, akceptacji miniatury, spóźnionego zwrotu lub potraktowania szacunku jak obietnicy. Porównaj co najmniej dwie zgodne trasy."]
    ],
    "usfans-qc-photos-guide": [
      ["QC zmniejsza ryzyko, ale nie certyfikuje. Światło i perspektywa zmieniają kolor, fakturę i kształt; skład, bateria, wodoodporność i autentyczność pozostają niewidoczne. Wcześniej ustal wady zmieniające wybór. Luźna nitka w taniej bluzie różni się od złego rozmiaru buta, pękniętej obudowy lub brakującego paska.", "Łącz zdjęcia, ofertę, cenę, dane sprzedawcy i koszt zwrotu lub wysyłki. W ten sposób nie odrzucisz produktu przez niekorzystne światło ani nie zaakceptujesz kosztownej różnicy tylko dlatego, że już czekałeś. Dowód wizualny wymaga kontekstu."],
      ["Przygotuj listę: metka, podeszwa, nosek i boki dla butów; nadruk, mankiety, zamek i miary dla bluzy; okucia, pasek, zamknięcie i wnętrze dla torby. Dwie minuty przed zakupem zmieniają „wygląda dobrze” w porównanie z konkretnymi oczekiwaniami."],
      ["Najpierw typ, kolor, rozmiar i ilość, potem przód, tył, boki, metki i pomiary. Brak kąta nie dowodzi wady, lecz nie pozwala na pewny wniosek, jeśli miejsce jest kluczowe. Poproś o jedno precyzyjne ujęcie, np. metkę obok linijki, zamiast ogólnego „więcej QC”."],
      ["Porównaj oba buty: noski, pięty, panele, szwy, klej i podeszwy. Dostępne miary zestaw z pasującą własną parą, bo etykiety producentów różnią się. Szeroki kąt może zniekształcić brzegi, ale zły rozmiar, duża asymetria lub uszkodzona podeszwa wymagają decyzji przed kosztownym transportem."],
      ["W odzieży miary magazynowe bywają ważniejsze niż metka. Porównaj klatkę, długość i rękaw z tabelą oraz własnym ubraniem. Użyj szwów i dekoltu jako linii dla nadruku, haftu, nazwiska, numeru i naszywek. Przy ciemnym materiale ostrożnie zwiększ jasność, nie myląc cienia z plamą."],
      ["Ładny przód nie potwierdza zamka, klamry ani wnętrza. Sprawdź sylwetkę, krawędzie, mocowanie uchwytów i odpinane części. W dodatkach widać wygięte styki, brak śrub, pęknięcia lub rysy; czyste zdjęcie nie dowodzi działania ani pojemności baterii."],
      ["Stosuj trzy wyniki: zostaw, gdy widoczne cechy pasują; poproś o dowód, gdy brakuje kluczowego szczegółu; zwróć, gdy błąd, szkoda lub wykonanie są nieakceptowalne. W ciągu pięciu dni dołącz opis, zdjęcie i sprzeczną informację, a produktu nie wysyłaj podczas sprawy."],
      ["Zachowaj wariant, obrazy, pomiary i odpowiedzi do dostawy. Zapisz wynik, pytanie, datę i decyzję, a później porównaj rzecz z dokumentacją, by ocenić wiarygodne kąty.", "Dyscyplina jest lepsza niż szukanie idealnej partii: zdefiniuj powód zwrotu, sprawdź go najpierw, pilnuj terminu i zakończ, gdy dowody wystarczą. USFans daje punkt fotograficzny; kupujący wykorzystuje go przed przekroczeniem granicy."]
    ],
    "usfans-review-2026": [
      ["Publiczne deklaracje trzeba czytać precyzyjnie. Trzy–siedem zdjęć HD to kontrola wizualna, nie gwarancja materiału lub autentyczności. Pięciodniowy wniosek nie zmusza każdego sprzedawcy do przyjęcia zwrotu. Odpowiedzialność dzieli się między sprzedawcę, magazyn, kupującego i przewoźnika."],
      ["Model pomaga głównie osobie, która otwiera zdjęcia, porównuje ofertę i konsoliduje zakupy przed paczką. Akceptowanie bez kontroli lub ignorowanie drugiej płatności ogranicza korzyść. USFans jest narzędziem dla świadomego klienta, nie zastępuje badania produktu ani porównania kosztu, ograniczeń i czasu."],
      ["Rozkład był bardzo pozytywny, ale z istotną częścią negatywną. Informacja o usuniętych fałszywych recenzjach nakazuje patrzeć dalej niż średnia. Ważniejsze są powtarzalne tematy: prostota, QC, pakowanie, pomoc i terminowe dostawy kontra komunikacja, opóźnienia, waga, koszt i tracking."],
      ["Najbardziej wiarygodne relacje podają produkt, kierunek, czas etapu lub rozwiązanie. Pasują do modelu, gdy sprzedawca, zdjęcia, trasa i wsparcie działają razem. „Najlepszy” lub „najtańszy” to osobista ocena: stawki zależą od kraju, trasy, paczki i promocji."],
      ["Przypisz skargę do etapu: zapłacono bez zakupu, zakupiono bez wysyłki, tranzyt krajowy, przyjęcie, pakowanie albo brak fizycznego skanu. Sprzedawca kontroluje dostawę lokalną, ale to nie wyjaśnia automatycznie obsługi magazynu, decyzji paczkowych ani szybkości wsparcia. Dokładny status ułatwia eskalację."],
      ["Dowody pokazują aktywną platformę z opublikowanym procesem i dużą liczbą mieszanych opinii, nie brak ryzyka. Zacznij od akceptowalnej wartości, użyj płatności z dokumentacją, zapisz ofertę i rozmowy i weryfikuj wybory. Unikaj zakazanych towarów i czytaj bieżące ograniczenia oraz odszkodowania."],
      ["Usługa może odpowiadać osobom rozumiejącym sprzedawców, akceptującym etapy i porównującym zdjęcia oraz trasy. Gorzej pasuje do jednej pełnej ceny, gwarantowanej daty, autentyczności albo natychmiastowej pomocy. Jest też ryzykowna przy zakupie pilnym, który opóźnienie sprzedawcy czyni bezużytecznym."],
      ["Werdykt jest warunkowy: zakup, przyjęcie, realne zdjęcia, opisane okno i obsługa paczki są użyteczne; opinie dokumentują też poważne problemy komunikacji, czasu i kosztu. Pięć gwiazdek i jedna gwiazdka muszą być czytane razem.", "Przed zakupem sprawdź aktualne warunki, nie stare filmy. Oddziel ofertę, dowód magazynu i wsparcie; przed wysyłką sprawdź paczkę i trasę; po dostawie porównaj produkt ze zdjęciami. Podejście oparte na dowodach jest wolniejsze od reklamy, lecz bardziej wiarygodne."]
    ]
  },
  pt: {
    "how-to-use-usfans": [
      ["Trate compra e envio como duas decisões e normalmente dois pagamentos. A primeira fase cobre item, variante e transporte nacional ao armazém; a segunda depende do pacote final. Misturá-las subestima custo e prazo. Leia cada status identificando se a responsabilidade é do vendedor, da receção pela USFans ou da transportadora internacional."],
      ["Anúncios chineses podem reunir cores, tamanhos, lotes, acessórios e depósitos. Selecione a opção exata e use notas apenas para o que o seletor não expressa. Um preço muito baixo pode ser de uma peça ou sinal. O agente executa instruções claras, mas não consegue adivinhar com segurança uma preferência não declarada."],
      ["Antes de pagar, confirme quantidade, entrega nacional e serviços opcionais. Um erro é mais fácil de corrigir antes do envio do vendedor. Para compras com data, reserve tempo para preparação, trânsito interno, entrada, fotos, embalagem e exportação. A estimativa do armazém não controla o prazo do vendedor externo."],
      ["Abra cada imagem em tamanho integral e compare com o anúncio salvo. Verifique cor, etiqueta, medidas visíveis, simetria, costura, posição da estampa, danos e acessórios. Se faltar uma área decisiva, peça uma foto específica antes do prazo. QC não promete perfeição; encontra diferenças capazes de mudar sua decisão."],
      ["Descreva a devolução com fatos observáveis: etiqueta errada, cor diferente ou rasgo perto da costura. Aponte foto e detalhe do anúncio e não inclua o item no pacote durante o caso. Se o vendedor recusar, peça a razão e avalie provas, regras de pós-venda e custo provável do frete internacional."],
      ["Consolidar reduz embalagens duplicadas, mas um pacote maior nem sempre é mais barato. Peso volumétrico, limites e restrições podem favorecer dois volumes. Remova caixas só quando a economia compensar a proteção. Calçados, bolsas rígidas, eletrônicos e itens frágeis exigem escolhas diferentes de reforço, umidade e impacto."],
      ["Compare peso real e faturável, dimensões, intervalo, rastreio, proibições e compensação. Uma rota para roupas pode recusar baterias ou líquidos. Prazos são faixas porque exportação, voos, alfândega e entrega local não dependem totalmente do armazém. Guarde declaração e rastreio até uma leitura física da transportadora."],
      ["Comece com poucos itens cujo valor e espera sejam aceitáveis. Salve anúncios e pagamentos, confirme variantes e programe a revisão dentro dos cinco dias. Muitos erros surgem de uma verificação pulada: opção presumida, miniatura aprovada, devolução perdida ou estimativa tratada como promessa. Compare pelo menos duas rotas compatíveis."]
    ],
    "usfans-qc-photos-guide": [
      ["QC reduz risco, mas não certifica. Luz e perspetiva alteram cor, textura e forma; composição, bateria, impermeabilidade e autenticidade ficam invisíveis. Defina antes os defeitos que mudariam a escolha. Um fio solto em moletom barato não equivale a tamanho errado, carcaça rachada ou alça ausente.", "Combine fotos, anúncio, preço, dados do vendedor e custo de devolver ou enviar. Isso evita rejeitar por luz ruim e também aceitar diferença cara apenas porque já esperou. Evidência visual só funciona com contexto."],
      ["Prepare uma lista curta: etiqueta, sola, bico e lados para tênis; estampa, punhos, zíper e medidas para moletom; ferragens, alça, fecho e interior para bolsa. Dois minutos antes do pedido transformam “parece bom” em comparação com expectativas concretas."],
      ["Primeiro confira tipo, cor, tamanho e quantidade; depois frente, costas, lados, etiquetas e medidas. Ângulo ausente não prova defeito, mas impede certeza se a área é crítica. Peça uma vista específica, como etiqueta ao lado da régua, em vez de um vago “mais QC”."],
      ["Compare os dois calçados: bicos, calcanhares, painéis, costuras, cola e solas. Quando houver medidas, use um par próprio que sirva bem, pois etiquetas variam. Grande angular distorce bordas, mas tamanho errado, forte assimetria ou sola danificada devem ser resolvidos antes do frete internacional caro."],
      ["Em roupas, medidas do armazém valem mais que a etiqueta. Compare peito, comprimento e manga com tabela e roupa própria. Use costuras e gola como linhas para estampa, bordado, nome, número e patches. Em tecido escuro, aumente o brilho com cuidado sem confundir sombras com manchas."],
      ["Uma boa frente não confirma zíper, fivela ou interior. Verifique forma, bordas, fixação de alças e peças removíveis. Em acessórios podem aparecer pinos tortos, parafusos ausentes, plástico rachado ou metal riscado; foto limpa não prova funcionamento nem capacidade da bateria."],
      ["Use três resultados: manter se coincide; pedir prova se faltar detalhe decisivo; devolver se erro, dano ou acabamento inaceitável já estiver visível. Envie descrição, foto e dado contrário dentro de cinco dias e mantenha o item fora do pacote durante o pós-venda."],
      ["Guarde variante, imagens, medidas e respostas até a entrega. Anote resultado, dúvida, data e ação e depois compare o item com o registro para aprender quais ângulos foram confiáveis.", "Rotina disciplinada vale mais que procurar lote perfeito: defina motivos de devolução, verifique primeiro, respeite o prazo e pare quando as provas bastarem. A USFans fornece o ponto fotográfico; o comprador cria valor antes da fronteira."]
    ],
    "usfans-review-2026": [
      ["As declarações públicas precisam de leitura precisa. Três a sete fotos HD são controle visual, não garantia de material ou autenticidade. O pedido em cinco dias não obriga todo vendedor a aceitar qualquer devolução. O modelo divide responsabilidades entre vendedor, armazém, comprador e transportadora."],
      ["O sistema ajuda sobretudo quem abre fotos, compara o anúncio e consolida antes do pacote. Aprovar sem olhar ou ignorar o segundo pagamento reduz a vantagem. A USFans é ferramenta para comprador informado; não substitui pesquisa do produto nem avaliação de custo, restrições e prazo."],
      ["A distribuição era muito positiva, mas tinha uma parcela negativa relevante. O aviso de avaliações falsas removidas exige olhar além da média. Temas repetidos importam mais: facilidade, QC, embalagem, ajuda e entrega prevista em positivo; comunicação, atrasos, peso, custo e rastreio em negativo."],
      ["Relatos mais confiáveis informam item, destino, duração de etapa ou solução. Eles combinam com o modelo quando vendedor, fotos, rota e suporte funcionam juntos. “Melhor” ou “mais barato” é opinião pessoal: tarifas variam por país, rota, características do pacote e promoções."],
      ["Associe cada reclamação à fase: pago não comprado, comprado não enviado, trânsito nacional, entrada, embalagem ou falta de leitura física internacional. O vendedor controlar a entrega local é plausível, mas não explica automaticamente processamento, decisões de pacote ou velocidade do suporte. Status preciso melhora a escalada."],
      ["As provas mostram plataforma ativa com processo publicado e muito feedback misto, não ausência de risco. Comece com valor aceitável, use pagamento documentado, salve anúncio e conversas e verifique cada escolha. Evite itens proibidos e leia restrições e compensação atuais sem presumir alfândega."],
      ["Pode servir a quem entende vendedores, aceita várias etapas e compara fotos e rotas. Serve menos a quem espera preço único, data garantida, autenticidade garantida ou ajuda instantânea contínua. Também é ruim para compra urgente que um atraso simples do vendedor tornaria inútil."],
      ["O veredito é condicional: compra, entrada, fotos reais, janela publicada e gestão do pacote são úteis; opiniões documentam problemas sérios de comunicação, tempo e custo. Cinco estrelas e uma estrela precisam ser lidas juntas.", "Antes do pedido consulte condições atuais, não vídeos antigos. Separe anúncio, prova do armazém e suporte; antes do envio confira pacote e rota; após a entrega compare o item com as fotos. O método baseado em evidências é mais lento que a propaganda, porém mais confiável."]
    ]
  },
  "zh-cn": {
    "how-to-use-usfans": [
      ["因此，使用购物代理时至少要做两次独立判断，通常也会发生两次付款。第一阶段围绕商品本身、所选规格以及卖家发往中国仓库的国内运输；第二阶段则以最终打包后的重量、尺寸和可用线路为准。把两个阶段混成一次普通网购，很容易低估总成本和等待时间。查看订单状态时，也要分清当前问题由平台卖家、仓库处理还是国际承运商负责。"],
      ["中国电商商品页经常在同一个链接里放入多种颜色、尺码、批次、配件，甚至定金选项。应逐项确认真正选择的规格，订单备注只补充选择器无法表达的信息。价格明显低于其他选项时，要检查它是否只是配件、单个部件或预付款。代理可以按明确指令采购，却无法可靠猜出客户没有写明的颜色、版本或尺码偏好。"],
      ["付款前还要核对数量、国内运费以及是否加入可选服务。此时发现重复商品或错误尺码，远比卖家发货后容易处理。对有明确使用日期的商品，应把卖家处理、国内运输、仓库入库、拍照、打包和国际运输都计入缓冲时间。USFans 展示的预计到仓时间只能作为参考，因为第三方卖家何时真正发出商品并不由仓库控制。"],
      ["不要只凭仓库列表里的缩略图作决定，应打开每张原图并与下单时保存的商品页对照。重点查看颜色、尺码标签、可见测量、左右对称、车线、印花位置、表面破损以及配件是否齐全。若影响决定的区域没有拍到，可以在期限结束前提出明确的补拍需求。质检的目的不是证明商品完美，而是找出足以改变保留或退货决定的可见差异。"],
      ["申请退货时，应使用可以在照片中核实的描述，例如“尺码标签与所选规格不符”“颜色不是订单中的黑色”或“左侧接缝附近有明显破口”。同时指出对应仓库照片和原商品页证据，售后未结束前不要把商品提交进国际包裹。若卖家拒绝，应先了解拒绝原因，再结合证据、卖家售后条件、国内退回费用和继续国际运输的成本作决定。"],
      ["合包可能减少重复外包装，但更大的包裹不必然更便宜或更安全。体积重量、线路尺寸上限、目的地规则和商品限制，都可能让两个小包裹更合理。去除卖家包装前，要权衡节省的重量与失去的保护。鞋盒、定型包袋、电子产品和易碎配件对挤压、防潮、护角与加固的需求完全不同，不能只用同一套方案。"],
      ["比较线路时，应查看最终实重、体积尺寸、计费重量规则、预计运输区间、追踪能力、禁运范围和赔付条件。能运输普通服装的线路未必接收电池、液体或某些受限商品。国际时效是范围而不是预约日期，出口处理、航班容量、海关和本地派送都不完全由仓库控制。保存申报信息与追踪号，并以承运商真实揽收扫描作为进入国际运输的更可靠信号。"],
      ["第一次使用时，建议从数量少、金额和等待时间都能承受的商品开始。保存每个原链接、规格截图和付款记录，在到仓后给自己设置早于公开五天期限的检查提醒。最常见的可避免错误都来自跳过节点：默认规格、只看小图、错过退货窗口，或把预计时间当成保证。提交包裹前至少比较两条真正适用于当前商品和目的地的线路，并再次核对最终包裹数据。"]
    ],
    "usfans-qc-photos-guide": [
      ["质检照片的作用是降低风险，而不是提供认证。灯光、镜头和拍摄角度会改变颜色、纹理与比例；面料成分、内部结构、电池健康、防水能力、长期耐用性和真伪通常无法仅凭照片证明。查看图片前先定义哪些问题会让自己退货。低价卫衣的一根线头，与错误鞋码、开裂外壳或缺少肩带并不是同等级风险。", "决定时应把仓库照片、原商品页、价格、卖家信息以及退回或国际运输成本放在一起。这样既不会因为仓库灯光不漂亮就拒绝可接受商品，也不会因为已经等待很久就接受明显而昂贵的错误。照片只有放回购买背景中，才是有效证据。"],
      ["每个品类提前列一张很短的核对表。鞋类可以记录尺码标签、鞋底颜色、鞋头形状和左右侧面；卫衣可记录胸前图案、标签、袖口、拉链与尺寸；包袋可记录五金颜色、肩带、开合和内里。下单前花两分钟准备，能把模糊的“看起来不错”变成对具体承诺的逐项检查，也能避免国际发出后才想起关键角度没有看。"],
      ["先做最基本的清点：商品类型、颜色、尺码和数量是否正确；随后依次查看正面、背面、侧面、标签与测量图。缺少某个角度并不等于商品有问题，但当那个位置会直接影响决定时，就不应过度自信地批准。补拍请求越具体越容易执行，例如要求“尺码标签与直尺同框”，比笼统要求“多拍几张质检照”更有效。"],
      ["鞋类要把左右两只当成一组比较，查看鞋头形状、后跟高度、拼接位置、车线路径、溢胶和鞋底颜色。若有鞋垫或外底测量，应与自己穿着合适的一双鞋比较，因为不同工厂的尺码标签不一定完全一致。广角镜头会让画面边缘变形，但错误尺码、明显左右不对称或鞋底破损，应在支付较高的国际运费前处理。"],
      ["服装检查时，仓库测量往往比单看尺码标签更有价值。将胸宽、衣长和袖长与卖家尺码表以及自己的合身衣物对照，再检查正反面印花、刺绣、领口、袖口、拉链、污渍或勾丝。查看球衣时还要核对球员姓名、号码、补丁和所选版本。深色衣物可适当提高屏幕亮度，但不要把褶皱形成的阴影误认成污点。"],
      ["包袋不能只看漂亮的正面图，还要检查整体包型、边油、提手和肩带连接、开合结构、五金颜色、内里以及所选规格中应包含的可拆部件。配件和电子小商品可能出现弯曲触点、缺少螺丝、塑料开裂、金属划伤或接口损坏。照片能确认型号与可见状态，但如果没有明确提供功能测试，就不能从外观干净推断电池容量或完整功能正常。"],
      ["把结果限定为三类会更高效：可见情况与所选规格相符且小问题能够接受，就保留；一个影响决定的细节缺失或含糊，就补充证据；已经看到明确错误、破损或无法接受的做工，就及时申请退货。根据 USFans 商品页目前公开的五天窗口，提交简洁问题说明、对应照片和冲突的商品页细节，售后解决前不要提交国际包裹。"],
      ["把所选商品页、仓库原图、测量记录和客服回复放在一起保存到最终收货。可以用四项简短记录：所选规格、可见结果、未解决问题、最终动作；若提出补拍，也记录日期，因为公开退货期限仍在继续。收到实物后再与照片对照，能够帮助你了解哪些视觉线索可靠、哪些角度容易误导。", "稳定的质检习惯比追求所谓完美批次更有价值。先明确什么问题会触发退货，再优先检查这些点，尊重处理期限，并在证据足以支持决定时停止无休止的挑图。USFans 提供了跨境运输前的照片节点；这个节点是否真正有用，取决于客户能否在付款发往海外前认真使用。"]
    ],
    "usfans-review-2026": [
      ["这些官方功能需要准确理解。3–7 张免费高清照片只是可见状态的检查节点，不等于材料、耐用性或真伪保证；到仓后五天内可以提出退货申请，也不代表所有第三方卖家都会无条件接受。购物代理流程把责任分散在平台卖家、仓库、客户和后续国际承运商之间，评价服务时不能把任何一个环节的问题全部归到同一方。"],
      ["购物代理最适合真正使用仓库检查节点的人：打开原图、与保存的卖家页面对比，并在多个卖家商品到仓后再决定如何组合包裹。若客户不查看照片就全部批准，或忽略后续国际运费，就几乎放弃了这种模式的核心优势。USFans 可以提供采购、仓储和转运工具，但不能替代客户对商品、价格、限制和运输线路的判断。"],
      ["研究日期当天的评分分布整体明显偏正面，但仍有不可忽视的一星比例。页面同时提示曾删除部分虚假评价，因此不能只把平均分当成结论。更有价值的是反复出现的主题：正面反馈常提到操作方便、质检照片、包装、客服协助和在预计范围内到达；负面反馈则集中在沟通、等待、重量计算、运费、包裹处理和追踪停滞。"],
      ["更可信的正面评价通常包含可核对的细节，例如购买了什么、寄往哪个国家、某个阶段持续多久，以及问题最终如何解决。当卖家正常发货、仓库照片清楚、线路适合、客服也能响应时，确实可能形成顺畅体验。但“最好”或“最便宜”仍是个人比较，不是长期事实；运费会随目的地、线路、重量尺寸和活动变化。"],
      ["遇到负面情况时，应先定位最后完成的节点：已经付款但尚未采购、采购后卖家未发、国内运输中、仓库尚未完成入库、包裹打包处理中，还是国际承运商尚无真实揽收扫描。USFans 公开解释第三方卖家决定送仓速度，这对国内阶段是合理说明，但不能自动回答仓库处理、包裹选择或客服速度的所有问题。准确状态能让后续沟通更有效。"],
      ["现有证据显示这是一个有公开采购、仓库、照片和售后流程的平台，也存在大量正负混合的客户反馈，但任何公开评价都无法保证下一笔交易没有风险。更稳妥的方式是从可承受金额开始，使用在所在国家能保留合适记录与保障的付款方法，保存卖家页、服务选择和客服沟通，逐阶段核对。不要购买禁运商品，也不要预设海关一定按某种方式处理。"],
      ["USFans 更适合了解第三方卖家模式、愿意经过多个处理阶段、并主动比较仓库照片和运输线路的客户。它不适合期待一次付款就是全部费用、保证到达日期、保证真伪，或任何时段都能立即获得回复的人。若商品有不可错过的使用日期，而卖家稍微延迟就会失去意义，那么这种多节点采购和转运模式风险尤其高。"],
      ["较为诚实的结论应当带有条件：代购、仓库收货、实物照片、公开五天申请窗口和国际包裹处理，都是有实际价值的工具；与此同时，公开评价也记录了沟通、时间和包裹费用方面的严重不满。较高五星占比和明显的一星尾部必须同时阅读，不能只选择符合预设立场的一边。", "首次下单前应查看当前服务与线路规则，而不是依赖旧视频或优惠口号。下单过程中，把卖家商品页、仓库证据和客服处理分开判断；国际发出前核对最终包裹与线路；收货后再将实物与仓库记录比较。以证据为中心的方法比宣传式结论更慢，却能形成更可靠、也更能帮助下一次购买的判断。"]
    ]
  }
};
