import type { Lang } from "./site-shell";
import { articleDetails } from "./article-details";
import { shoesListingArticle } from "./shoes-listing-article";

type HistoricArticleSlug = "how-to-use-usfans" | "usfans-qc-photos-guide" | "usfans-review-2026";
export type ArticleSlug = HistoricArticleSlug | "usfans-shoes-listing-checklist";
export const articleSlugs: ArticleSlug[] = ["how-to-use-usfans", "usfans-qc-photos-guide", "usfans-review-2026", "usfans-shoes-listing-checklist"];

type FaqLocale = { label:string; eyebrow:string; title:string; body:string; cardTitle:string; cardBody:string; open:string; questions:Array<{q:string;a:string}> };

export const faqText: Record<Lang,FaqLocale> = {
  en:{label:"FAQ",eyebrow:"FREQUENTLY ASKED QUESTIONS",title:"Clear answers before you place an order.",body:"Ten practical answers based on the workflow and policies currently described on USFans’ public pages.",cardTitle:"Questions worth answering before checkout.",cardBody:"Returns, warehouse photos, seller delivery, international shipping and what an agent actually does.",open:"Open all answers",questions:[
    {q:"What is USFans?",a:"USFans describes itself as a shopping-agent platform for purchasing from Chinese marketplaces such as Taobao, 1688 and Weidian. The agent purchases from the seller, receives the item at its warehouse, provides inspection photos and later handles the international parcel selected by the customer."},
    {q:"Does USFans sell the products itself?",a:"Usually the underlying item comes from a third-party marketplace seller. That distinction matters: seller dispatch time and product quality are not the same thing as the agent’s warehouse and forwarding service."},
    {q:"What happens after a seller sends an item?",a:"The public product-page workflow says the item goes to the USFans warehouse, where staff check it and take pictures. The customer can review those images before deciding whether to keep, return or later submit the item for international shipping."},
    {q:"How many QC photos are provided?",a:"USFans product pages currently advertise three to seven free HD inspection photos. The exact angles can vary by item, so buyers should still compare every available image with the seller listing."},
    {q:"Can an item be returned from the warehouse?",a:"USFans product pages currently state that a return can be requested within five days after warehouse arrival if the buyer is dissatisfied. Acceptance can still depend on the seller and the item’s after-sales conditions, so inspect promptly."},
    {q:"Why can seller delivery to the warehouse take longer than expected?",a:"USFans has publicly explained that delivery to its warehouse is controlled by the third-party seller. An estimated warehouse-arrival time is therefore not the same as a guaranteed purchasing or dispatch deadline."},
    {q:"Is product payment the final cost?",a:"No. A cross-border agent order normally has at least two cost stages: purchasing the item and later paying for the international parcel. Optional services, packaging, route rules and billable weight can affect the second stage."},
    {q:"How should I compare international shipping routes?",a:"Use the final packed weight and dimensions, destination, restrictions, estimated delivery range and available tracking—not only the lowest headline price. The route available for one parcel may not be available for another."},
    {q:"Are QC photos a guarantee of quality or authenticity?",a:"No. Photos are visual evidence of the item received at the warehouse. They help detect visible colour, size, construction or damage issues, but cannot prove materials, long-term durability or authenticity."},
    {q:"What should a first-time buyer do before parcel submission?",a:"Save the original listing, confirm the selected variant, inspect all warehouse photos promptly, resolve returns within the displayed window, remove unwanted items, then compare shipping routes using the final parcel information."},
  ]},
  de:{label:"FAQ",eyebrow:"HÄUFIGE FRAGEN",title:"Klare Antworten vor der Bestellung.",body:"Zehn praktische Antworten auf Grundlage der öffentlich beschriebenen USFans-Abläufe und Richtlinien.",cardTitle:"Fragen, die vor dem Kauf geklärt sein sollten.",cardBody:"Rückgaben, Lagerfotos, Verkäuferlieferung, internationaler Versand und die Rolle eines Agenten.",open:"Alle Antworten öffnen",questions:[
    {q:"Was ist USFans?",a:"USFans beschreibt sich als Einkaufsagent für Marktplätze wie Taobao, 1688 und Weidian. Der Agent kauft beim Verkäufer, empfängt die Ware im Lager, stellt Prüffotos bereit und organisiert später den gewählten internationalen Versand."},{q:"Verkauft USFans die Produkte selbst?",a:"Das Produkt stammt normalerweise von einem externen Marktplatzverkäufer. Verkäuferzeit und Produktqualität müssen daher vom Lager- und Weiterleitungsservice getrennt bewertet werden."},{q:"Was passiert nach dem Versand durch den Verkäufer?",a:"Die Ware kommt ins USFans-Lager, wird geprüft und fotografiert. Danach kann der Käufer behalten, eine Rückgabe beantragen oder später den internationalen Versand einreichen."},{q:"Wie viele QC-Fotos gibt es?",a:"USFans bewirbt derzeit drei bis sieben kostenlose HD-Prüffotos. Winkel können je nach Produkt variieren; alle Bilder sollten mit dem Angebot verglichen werden."},{q:"Kann man aus dem Lager zurückgeben?",a:"Öffentliche Produktseiten nennen derzeit ein Rückgabefenster von fünf Tagen nach Lagereingang. Verkäuferbedingungen können trotzdem gelten, daher schnell prüfen."},{q:"Warum dauert die Lieferung ins Lager manchmal länger?",a:"USFans erklärt, dass die Zustellung zum Lager vom Drittverkäufer abhängt. Eine Schätzung ist keine garantierte Frist."},{q:"Ist der Produktpreis der Endpreis?",a:"Nein. Produktkauf und internationaler Versand sind getrennte Kostenstufen. Verpackung, Zusatzleistungen, Routen und abrechenbares Gewicht beeinflussen die zweite Stufe."},{q:"Wie vergleicht man Versandrouten?",a:"Vergleiche Endgewicht, Maße, Ziel, Einschränkungen, Lieferfenster und Tracking – nicht nur den niedrigsten Preis."},{q:"Garantieren QC-Fotos Qualität oder Echtheit?",a:"Nein. Sie zeigen sichtbare Details des Lagerartikels, beweisen aber weder Material noch Haltbarkeit oder Echtheit."},{q:"Was sollte ein Erstkäufer vor dem Versand tun?",a:"Originalangebot speichern, Variante bestätigen, Lagerfotos prüfen, Rückgaben rechtzeitig klären und Routen mit finalen Paketdaten vergleichen."}
  ]},
  es:{label:"FAQ",eyebrow:"PREGUNTAS FRECUENTES",title:"Respuestas claras antes de comprar.",body:"Diez respuestas prácticas basadas en el proceso y las políticas públicas actuales de USFans.",cardTitle:"Preguntas que conviene resolver antes de pagar.",cardBody:"Devoluciones, fotos de almacén, entrega del vendedor, envío internacional y función del agente.",open:"Abrir todas las respuestas",questions:[
    {q:"¿Qué es USFans?",a:"USFans se presenta como agente de compras para Taobao, 1688 y Weidian. Compra al vendedor, recibe el artículo en almacén, aporta fotos de inspección y gestiona el paquete internacional elegido."},{q:"¿USFans vende directamente los productos?",a:"Normalmente el artículo procede de un vendedor externo. El tiempo del vendedor y la calidad del producto deben separarse del servicio de almacén y reenvío."},{q:"¿Qué ocurre cuando envía el vendedor?",a:"El artículo llega al almacén de USFans, se revisa y fotografía. Después puede conservarse, devolverse o enviarse internacionalmente."},{q:"¿Cuántas fotos QC se incluyen?",a:"Las páginas de producto anuncian actualmente de tres a siete fotos HD gratuitas. Conviene comparar cada ángulo con el anuncio."},{q:"¿Puedo devolver desde el almacén?",a:"USFans indica actualmente cinco días desde la llegada para solicitar devolución. También pueden aplicar las condiciones del vendedor."},{q:"¿Por qué tarda la entrega al almacén?",a:"USFans explica que el transporte hasta el almacén depende del vendedor externo; una estimación no es una fecha garantizada."},{q:"¿El pago del producto es el coste final?",a:"No. La compra y el envío internacional son etapas separadas. Servicios, embalaje, ruta y peso facturable influyen en el segundo pago."},{q:"¿Cómo comparo rutas?",a:"Compara peso y medidas finales, destino, restricciones, plazo y seguimiento, no solo el precio más bajo."},{q:"¿Las fotos QC garantizan calidad o autenticidad?",a:"No. Ayudan a revisar detalles visibles, pero no demuestran materiales, duración ni autenticidad."},{q:"¿Qué debe hacer un comprador nuevo?",a:"Guardar el anuncio, confirmar variante, revisar fotos, resolver devoluciones y comparar rutas con los datos finales del paquete."}
  ]},
  fr:{label:"FAQ",eyebrow:"QUESTIONS FRÉQUENTES",title:"Des réponses claires avant la commande.",body:"Dix réponses pratiques fondées sur le parcours et les règles publiques actuelles de USFans.",cardTitle:"Les questions à résoudre avant le paiement.",cardBody:"Retours, photos d’entrepôt, livraison vendeur, transport international et rôle de l’agent.",open:"Voir toutes les réponses",questions:[
    {q:"Qu’est-ce que USFans ?",a:"USFans se présente comme un agent d’achat pour Taobao, 1688 et Weidian. Il achète auprès du vendeur, reçoit l’article, fournit des photos et organise ensuite l’expédition internationale choisie."},{q:"USFans vend-il directement les produits ?",a:"L’article provient généralement d’un vendeur tiers. Le délai du vendeur et la qualité du produit sont distincts du service d’entrepôt et de transfert."},{q:"Que se passe-t-il après l’envoi du vendeur ?",a:"L’article arrive à l’entrepôt USFans, est contrôlé et photographié. Il peut ensuite être conservé, retourné ou soumis à l’expédition."},{q:"Combien de photos QC sont fournies ?",a:"Les pages publiques annoncent actuellement trois à sept photos HD gratuites. Comparez chaque angle avec l’annonce."},{q:"Peut-on retourner depuis l’entrepôt ?",a:"USFans indique actuellement cinq jours après l’arrivée pour demander un retour, sous réserve des conditions du vendeur."},{q:"Pourquoi l’arrivée à l’entrepôt peut-elle être lente ?",a:"USFans explique que ce délai dépend du vendeur tiers. Une estimation n’est donc pas une garantie."},{q:"Le prix du produit est-il le coût final ?",a:"Non. L’achat et le transport international sont deux étapes de coût. Services, emballage, route et poids facturable comptent."},{q:"Comment comparer les routes ?",a:"Comparez poids, dimensions, destination, restrictions, délai et suivi, pas seulement le prix affiché."},{q:"Les photos QC garantissent-elles la qualité ?",a:"Non. Elles montrent des détails visibles, sans prouver matière, durabilité ou authenticité."},{q:"Que faire avant l’envoi du colis ?",a:"Sauvegardez l’annonce, confirmez la variante, examinez les photos, traitez les retours et comparez les routes avec les données finales."}
  ]},
  it:{label:"FAQ",eyebrow:"DOMANDE FREQUENTI",title:"Risposte chiare prima dell’ordine.",body:"Dieci risposte pratiche basate sul flusso e sulle politiche pubbliche attuali di USFans.",cardTitle:"Domande da chiarire prima del pagamento.",cardBody:"Resi, foto di magazzino, consegna del venditore, spedizione e ruolo dell’agente.",open:"Apri tutte le risposte",questions:[
    {q:"Cos’è USFans?",a:"USFans si presenta come agente d’acquisto per Taobao, 1688 e Weidian. Compra dal venditore, riceve l’articolo, fornisce foto e gestisce la spedizione internazionale scelta."},{q:"USFans vende direttamente i prodotti?",a:"Di solito il prodotto proviene da un venditore terzo. Tempi e qualità del venditore sono distinti dal servizio di magazzino e inoltro."},{q:"Cosa succede dopo la spedizione del venditore?",a:"L’articolo arriva al magazzino USFans, viene controllato e fotografato. Poi può essere tenuto, restituito o spedito."},{q:"Quante foto QC sono incluse?",a:"Le pagine pubbliche pubblicizzano tre-sette foto HD gratuite. Confronta ogni angolo con l’inserzione."},{q:"Si può restituire dal magazzino?",a:"USFans indica attualmente cinque giorni dall’arrivo per chiedere il reso, soggetto alle condizioni del venditore."},{q:"Perché l’arrivo in magazzino può tardare?",a:"USFans spiega che dipende dal venditore terzo; una stima non è una garanzia."},{q:"Il prezzo del prodotto è il costo finale?",a:"No. Acquisto e spedizione internazionale sono due costi separati. Servizi, imballo, rotta e peso fatturabile incidono."},{q:"Come confronto le rotte?",a:"Confronta peso, dimensioni, destinazione, limiti, tempi e tracciamento, non solo il prezzo."},{q:"Le foto QC garantiscono qualità o autenticità?",a:"No. Mostrano dettagli visibili ma non provano materiali, durata o autenticità."},{q:"Cosa fare prima della spedizione?",a:"Salva l’inserzione, conferma la variante, controlla le foto, gestisci i resi e confronta le rotte con i dati finali."}
  ]},
  pl:{label:"FAQ",eyebrow:"CZĘSTE PYTANIA",title:"Jasne odpowiedzi przed zamówieniem.",body:"Dziesięć praktycznych odpowiedzi opartych na publicznym procesie i zasadach USFans.",cardTitle:"Pytania, na które warto odpowiedzieć przed płatnością.",cardBody:"Zwroty, zdjęcia magazynowe, dostawa sprzedawcy, wysyłka i rola agenta.",open:"Otwórz wszystkie odpowiedzi",questions:[
    {q:"Czym jest USFans?",a:"USFans opisuje się jako agent zakupowy dla Taobao, 1688 i Weidian. Kupuje od sprzedawcy, przyjmuje produkt, udostępnia zdjęcia i organizuje wybraną wysyłkę międzynarodową."},{q:"Czy USFans sam sprzedaje produkty?",a:"Produkt zwykle pochodzi od zewnętrznego sprzedawcy. Czas i jakość sprzedawcy trzeba oddzielić od usługi magazynowej i spedycyjnej."},{q:"Co dzieje się po wysyłce sprzedawcy?",a:"Produkt trafia do magazynu USFans, jest sprawdzany i fotografowany. Potem można go zatrzymać, zwrócić lub wysłać."},{q:"Ile zdjęć QC otrzymam?",a:"Publiczne strony reklamują obecnie trzy do siedmiu darmowych zdjęć HD. Porównaj każdy kąt z ofertą."},{q:"Czy można zwrócić produkt z magazynu?",a:"USFans podaje obecnie pięć dni od przyjęcia na złożenie wniosku, z uwzględnieniem zasad sprzedawcy."},{q:"Dlaczego dostawa do magazynu trwa długo?",a:"USFans wyjaśnia, że zależy ona od zewnętrznego sprzedawcy; szacunek nie jest gwarancją."},{q:"Czy cena produktu jest kosztem końcowym?",a:"Nie. Zakup i wysyłka zagraniczna to dwa etapy kosztów. Usługi, pakowanie, trasa i waga rozliczeniowa mają znaczenie."},{q:"Jak porównywać trasy?",a:"Porównaj końcową wagę, wymiary, ograniczenia, termin i śledzenie, nie tylko cenę."},{q:"Czy zdjęcia QC gwarantują jakość?",a:"Nie. Pokazują widoczne szczegóły, ale nie dowodzą materiału, trwałości ani autentyczności."},{q:"Co zrobić przed wysyłką?",a:"Zapisz ofertę, potwierdź wariant, sprawdź zdjęcia, rozwiąż zwroty i porównaj trasy na podstawie finalnych danych."}
  ]},
  pt:{label:"FAQ",eyebrow:"PERGUNTAS FREQUENTES",title:"Respostas claras antes do pedido.",body:"Dez respostas práticas baseadas no processo e nas políticas públicas atuais da USFans.",cardTitle:"Perguntas para responder antes de pagar.",cardBody:"Devoluções, fotos, entrega do vendedor, envio internacional e função do agente.",open:"Abrir todas as respostas",questions:[
    {q:"O que é a USFans?",a:"A USFans se apresenta como agente de compras para Taobao, 1688 e Weidian. Compra do vendedor, recebe o item, fornece fotos e organiza o envio internacional escolhido."},{q:"A USFans vende os produtos diretamente?",a:"Normalmente o item vem de um vendedor externo. Prazo e qualidade do vendedor são diferentes do serviço de armazém e encaminhamento."},{q:"O que acontece após o vendedor enviar?",a:"O item chega ao armazém USFans, é verificado e fotografado. Depois pode ser mantido, devolvido ou enviado internacionalmente."},{q:"Quantas fotos QC são fornecidas?",a:"As páginas públicas anunciam atualmente de três a sete fotos HD gratuitas. Compare todos os ângulos com o anúncio."},{q:"Posso devolver do armazém?",a:"A USFans informa atualmente cinco dias após a chegada para solicitar devolução, sujeita às condições do vendedor."},{q:"Por que a chegada ao armazém demora?",a:"A USFans explica que o prazo depende do vendedor externo; uma estimativa não é garantia."},{q:"O preço do produto é o custo final?",a:"Não. Compra e frete internacional são etapas separadas. Serviços, embalagem, rota e peso faturável afetam o segundo custo."},{q:"Como comparar rotas?",a:"Compare peso, dimensões, destino, restrições, prazo e rastreamento, não apenas o menor preço."},{q:"Fotos QC garantem qualidade?",a:"Não. Elas mostram detalhes visíveis, mas não provam materiais, durabilidade ou autenticidade."},{q:"O que fazer antes do envio?",a:"Salve o anúncio, confirme a variante, revise as fotos, resolva devoluções e compare rotas com os dados finais."}
  ]},
  "zh-cn":{label:"常见问题",eyebrow:"常见问题",title:"下单前，把关键问题弄清楚。",body:"以下十个回答依据 USFans 当前公开页面所描述的流程与政策整理。",cardTitle:"付款前值得先弄清的问题。",cardBody:"退货、仓库照片、卖家发货、国际运输，以及购物代理究竟负责什么。",open:"查看全部回答",questions:[
    {q:"USFans 是什么？",a:"USFans 将自己描述为面向淘宝、1688 和微店等中国平台的购物代理。代理向卖家采购、在仓库收货并提供检查照片，之后再按客户选择处理国际包裹。"},{q:"商品是 USFans 自己销售的吗？",a:"多数情况下，实际商品来自第三方平台卖家。卖家发货速度和商品质量，与代理的仓储及转运服务需要分开判断。"},{q:"卖家发货后会发生什么？",a:"USFans 的公开流程说明，商品会进入其仓库，由工作人员检查并拍照。客户查看照片后，可以保留、申请退货，或稍后提交国际运输。"},{q:"会提供多少张质检照片？",a:"USFans 商品页目前写明提供 3–7 张免费高清检查照片。不同商品的拍摄角度可能不同，仍应逐张与卖家商品页对比。"},{q:"商品到仓后能退货吗？",a:"USFans 商品页目前写明，到仓后如不满意可在 5 天内申请退货。是否最终接受仍可能受卖家及商品售后条件影响，所以应及时检查。"},{q:"为什么卖家送到仓库会变慢？",a:"USFans 曾公开说明，送达仓库的时间由第三方卖家控制。因此预计到仓时间不是保证的采购或发货期限。"},{q:"支付商品价格就是全部费用吗？",a:"不是。购物代理订单通常至少分为商品采购和国际包裹两个费用阶段。增值服务、包装、线路规则和计费重量会影响第二阶段。"},{q:"国际运输线路应该怎么比较？",a:"应同时看最终重量和尺寸、目的地、限制、预计时效与追踪能力，而不是只看最低的表面报价。"},{q:"质检照片能保证质量或真伪吗？",a:"不能。照片只能帮助检查可见的颜色、尺码、做工或破损，无法证明材料、长期耐用性或真伪。"},{q:"第一次使用时，提交包裹前要做什么？",a:"保存原商品页、确认规格、及时检查全部仓库照片、在页面显示的期限内处理退货、移除不需要的商品，再用最终包裹数据比较线路。"}
  ]},
};

export type Article = { kicker:string; title:string; description:string; updated:string; readingTime:string; contentsLabel:string; factTitle:string; factNote:string; imageCaption:string; sections:Array<{heading:string;paragraphs:string[]}> };
const article = (value:Article)=>value;

const guideEn = article({
  kicker:"USFANS BEGINNER GUIDE · 2026", title:"How to Use USFans in 2026: From Product Link to International Parcel", description:"A practical, evidence-led walkthrough of the USFans buying flow, including seller links, warehouse arrival, QC photos, returns and parcel submission.", updated:"Updated August 13, 2026", readingTime:"14 minute read", contentsLabel:"IN THIS GUIDE", factTitle:"What is verified", factNote:"USFans publicly describes support for shopping from Taobao, 1688 and Weidian, warehouse inspection with real photos, three to seven free HD inspection images on product pages, and a five-day return-request window after warehouse arrival. Prices, routes and seller timelines can change, so this guide separates published platform statements from practical buyer judgment.", imageCaption:"Catalog images help identify the selected item, but warehouse QC photos should still be checked against the original listing.",
  sections:[
    {heading:"Understand the two-stage order",paragraphs:["Using a shopping agent is not the same as placing a normal domestic retail order. The transaction has two distinct movements. First, an agent purchases an item from a marketplace seller and receives it at a warehouse in China. Second, after the buyer reviews the warehouse result, one or more items are packed and submitted for international delivery. Treating those movements as separate decisions is the simplest way to avoid cost surprises and rushed approvals.","USFans presents its service around Taobao, 1688 and Weidian purchasing, warehouse inspection and global forwarding. That means the marketplace seller remains responsible for the item, its variant and the first domestic dispatch. USFans handles the purchasing request, warehouse intake, inspection-photo stage and later logistics selection. A slow seller is not automatically a slow warehouse, and a poor item is not automatically proof of poor forwarding. Keep those responsibilities separate when reading status updates or asking support for help."]},
    {heading:"Start with a clean product link",paragraphs:["A reliable order begins before payment. Open the original marketplace listing and read the title, variant names, size chart, seller notes, delivery estimate and return limitations. Save the URL and a screenshot of the selected option. Product pages can change after an order is placed; your own record makes it easier to compare what was requested with what eventually reaches the warehouse.","When pasting a link, do not assume the first product image represents every option. Chinese marketplace listings often combine several colours, batches or specifications on one page. Choose the exact colour and size, then use the order remark only for information the selector cannot express. If the price looks dramatically lower than the other options, inspect whether it represents a deposit, accessory or partial component. A shopping agent can execute the order, but it cannot infer an unstated preference with certainty."]},
    {heading:"Review the order before paying",paragraphs:["Before paying for the item, compare the displayed product price with the original listing and check whether domestic delivery or an optional service has been added. Confirm the quantity. A duplicated line or the wrong size is much easier to correct at this point than after the seller ships. Also remember that product payment is not the final landed cost: the international parcel is normally paid later, after warehouse arrival and packing.","USFans product pages describe an estimated time to the warehouse, but an estimate should not be treated as a guarantee. The company has publicly explained that delivery to the warehouse depends on third-party sellers. If an item is time-sensitive, build in a buffer for seller processing, domestic transit, warehouse intake, photos, parcel packing and international transport. A marketing delivery range cannot remove delays created by a seller who has not dispatched."]},
    {heading:"What warehouse arrival really means",paragraphs:["Warehouse arrival is a checkpoint, not the end of the purchase. The item must be received, associated with the correct order and photographed. USFans product pages state that the warehouse checks the item and takes pictures for the customer. They currently advertise three to seven free HD quality-inspection photos. Those images are valuable because they show the actual unit received rather than the seller’s polished catalog photography.","Do not approve an item from the thumbnail alone. Open every image at full size and compare it with the saved listing. Check the selected colour, size label, visible measurements when provided, construction, symmetry, logos or print placement, surface damage and included accessories. If an important area is not visible, decide whether an additional photograph is worth requesting before the return window closes. The purpose of QC is not to find perfection; it is to detect a mismatch large enough to change your decision."]},
    {heading:"Use the five-day return window carefully",paragraphs:["USFans product pages currently say that a buyer dissatisfied after warehouse arrival can apply for a return within five days, after which agents negotiate with the seller on the buyer’s behalf. This is a request window, not an unconditional promise that every seller accepts every return. Some marketplace items have limited after-sales terms, and domestic return freight may apply. The practical lesson is simple: inspect promptly rather than letting the order sit untouched.","If you request a return, describe the issue with observable details. “Wrong size label,” “colour differs from selected black,” or “visible tear near the left seam” is more useful than “quality bad.” Refer to the relevant warehouse image and the saved listing. Keep the item out of parcel submission while the case is open. If the seller rejects the request, ask for the reason and then decide using the evidence and the likely international shipping cost—not frustration alone."]},
    {heading:"Build the parcel deliberately",paragraphs:["Once the items you want are approved, select only those items for parcel submission. Consolidation can reduce duplicated packaging, but a larger parcel is not automatically cheaper or safer. Route restrictions, volumetric weight, parcel-size limits and destination rules can make two smaller packages more practical. The right choice depends on the actual items and the routes shown at submission time.","Remove unnecessary seller packaging only when the savings outweigh the protection it provides. Shoes, structured bags, electronics and fragile accessories have different needs. Consider whether corner protection, moisture protection, reinforcement or a shoe box matters for the item’s shape. Rehearsal or pre-packing information can improve the estimate when available, but always review what the service includes instead of assuming it guarantees a particular final weight."]},
    {heading:"Compare shipping with final data",paragraphs:["The lowest displayed shipping number is not enough for a good route decision. Compare the final packed weight and dimensions, billable-weight rule, estimated transit range, tracking level, prohibited-item rules, compensation terms and destination-country handling. A route that accepts ordinary clothing may reject batteries, liquids or branded goods. Availability can also change, so a route mentioned in an old tutorial may not be available for your parcel today.","International delivery estimates are ranges rather than appointments. Export processing, flight capacity, customs and local carriers are outside the warehouse’s full control. Save the parcel declaration and tracking number, then watch for a real carrier acceptance scan rather than only a label-created event. If tracking stalls, provide support with the parcel number, route and last physical scan. Specific evidence usually produces a more useful answer than repeatedly asking where the parcel is."]},
    {heading:"A first-order checklist that works",paragraphs:["For a first order, start with a small number of items you can afford to wait for. Save each original listing, verify every variant, record the product payment, and set a reminder to inspect warehouse photos. Use the published five-day window as a hard personal deadline. Keep screenshots of visible defects and resolutions. At parcel stage, compare at least two suitable routes and review the final package data before payment.","Most avoidable mistakes come from skipping a checkpoint: assuming a variant, approving tiny photos, missing a return window or treating an estimate as a promise. The agent model works best when the buyer uses the information the warehouse provides. USFans can purchase, photograph, store and forward; the buyer still has to decide whether the received item matches expectations and whether the final shipping option makes financial sense. That shared responsibility is the honest way to approach the service." ]}
  ]
});

const qcEn = article({
  kicker:"USFANS QC PHOTO GUIDE · 2026", title:"USFans QC Photos Guide: How to Inspect Warehouse Images Before Shipping", description:"A category-by-category method for reading USFans warehouse photos, spotting visible mismatches and making a return decision within the published window.", updated:"Updated August 13, 2026", readingTime:"13 minute read", contentsLabel:"IN THIS GUIDE", factTitle:"What is verified", factNote:"USFans product pages currently say items are checked and photographed after warehouse arrival, advertise three to seven free HD quality-inspection photos, and describe a five-day period to request a return after arrival. QC images are visual evidence, not a guarantee of authenticity, material composition or long-term durability.", imageCaption:"Seller-style catalog images are a reference point. The decision should be based on full-size warehouse images of the actual received unit.",
  sections:[
    {heading:"What QC can and cannot prove",paragraphs:["Quality-control photos answer a narrow but important question: does the actual item received at the warehouse visibly match what the buyer selected? They can reveal the colour, silhouette, labels, obvious construction, print position, surface damage and included pieces. They are especially useful because seller listings often use edited lighting, sample units or multiple variants on one page.","They cannot prove everything. A photograph does not establish fibre composition, battery health, waterproofing, internal construction, long-term durability or authenticity. It may hide texture and colour differences caused by lighting. Treat QC as risk reduction, not certification. The best decision combines the photos, original listing, price, seller information and the cost of shipping or returning the item.","The standard should also reflect the product and price. A tiny loose thread on an inexpensive sweatshirt is not the same risk as a wrong shoe size, cracked electronic housing or missing bag strap. Define the defects that would change your decision before opening the images. That makes the review consistent and prevents two opposite mistakes: rejecting a usable item because the camera is unflattering, or accepting a costly mismatch because you have already waited for it to arrive."]},
    {heading:"Prepare a reference before arrival",paragraphs:["Save the original listing and selected variant at the time of purchase. Capture the size chart, colour name, product measurements, accessories and any seller detail photos that influenced the order. Without that reference, QC becomes a vague question about whether an item “looks good.” With it, the task becomes a comparison between specific promises and visible evidence.","Write a short private checklist for each item. For shoes it may include size label, outsole colour, toe shape and both sides. For a hoodie it may include chest print, tag, cuffs, zipper and stated measurements. For a bag it may include hardware colour, strap, closure and interior. This takes two minutes before ordering and prevents the most common problem: noticing a missing detail only after international shipment."]},
    {heading:"Inspect the complete photo set",paragraphs:["USFans currently advertises three to seven free HD inspection photos on its product pages. Open the original files where possible instead of judging small dashboard thumbnails. Start with an inventory check: is it the correct type of item, colour, size and quantity? Then compare front, back, sides, labels and any measurement image. Look for areas that are cropped, hidden by packaging or overexposed.","A missing angle is not automatically evidence of a defect, but it is a reason not to make an overconfident decision. If the listing makes a specific area important and that area is absent, request an additional image if the platform offers that option. Ask for one clear view at a time—such as the size label beside a ruler—rather than a general request for “more QC.” Precise requests are easier for warehouse staff to fulfil."]},
    {heading:"Shoes: symmetry, size and shape",paragraphs:["For shoes, compare the left and right units as a pair. Look at overall symmetry, toe shape, panel alignment, stitching paths, glue marks, outsole colour and the way both heels sit. Confirm the size tag and, when measurement photos are available, compare the insole or outsole length with a pair that already fits. Marketplace size labels do not always correspond perfectly across factories.","Small glue traces or loose threads may be acceptable at a low price, while major shape differences, incorrect size or a damaged sole can justify a return request. Decide before international shipping, because footwear is relatively bulky and paying to transport a clearly unacceptable pair rarely makes sense. Keep your judgment proportional: warehouse lighting can exaggerate colour and wide-angle lenses can distort shape near the edge of an image."]},
    {heading:"Clothing and jerseys: measurements first",paragraphs:["For hoodies, shirts and jerseys, the selected tag is only the first check. Compare any warehouse measurement with the seller’s chart and your own garment measurement. Focus on chest width, length and sleeve length when provided. Examine front and back print placement, embroidery, collar shape, cuff construction, zipper alignment and visible stains or pulls.","Printed designs deserve a straight-on view. A tilted garment can make a centred print appear uneven, so use seams and the neckline as reference lines. For jerseys, check the player name, number, patches and chosen version. For dark garments, raise screen brightness carefully to inspect folds without mistaking shadows for stains. If measurements are missing and fit is critical, one additional measurement can be more valuable than several decorative close-ups."]},
    {heading:"Bags and accessories: function matters",paragraphs:["For bags, inspect silhouette, panel shape, handle and strap attachment, closure, hardware colour and any visible edge paint. Confirm that removable pieces shown in the selected variant are present. A beautiful front view does not reveal whether the zipper, buckle or interior is correct, so those areas deserve explicit attention.","Accessories often combine several materials and small parts. Look for bent posts, missing screws, cracked plastic, scratched metal or damaged connectors. For electronics, warehouse photos can confirm model and visible condition but cannot prove battery capacity or full operation unless a separate test is explicitly offered. Do not infer a functional guarantee from a clean photograph."]},
    {heading:"Decide: keep, ask, or return",paragraphs:["Use three outcomes. Keep the item when the visible result matches the selected variant and any imperfections are acceptable for the price. Ask for evidence when one decision-critical detail is missing or ambiguous. Request a return when a clear mismatch, damage or unacceptable construction is already visible. This structure prevents endless inspection while protecting the important decision.","USFans product pages currently describe a five-day return-request window after warehouse arrival. Treat that as a countdown, not a suggestion. Submit the issue with a concise description, the relevant photo and the conflicting listing detail. A return may still depend on seller policy and domestic costs. Do not submit the item to an international parcel while the after-sales request is unresolved."]},
    {heading:"Create a defensible QC record",paragraphs:["Keep the selected listing, warehouse images, measurement notes and any support response together until the parcel arrives. This record helps if the item in hand differs from what the warehouse images showed. It also improves future buying: after comparing warehouse photos with the delivered product, you learn which visual clues were reliable and which angles were misleading.","Use a simple decision note: selected variant, visible result, unanswered question and final action. If you ask support for another photo, write the date because the published return period continues to matter. When approving, record why the visible differences were acceptable. A short contemporaneous note is more reliable than memory weeks later, particularly when several similar products enter the warehouse at different times.","A disciplined QC routine is more useful than chasing a mythical perfect batch. Define what would make you return the item before seeing the photos. Check those points first, respect the return deadline and stop once the evidence supports a decision. USFans supplies the warehouse-photo checkpoint; the value comes from using it carefully before paying to move the item across borders." ]}
  ]
});

const reviewEn = article({
  kicker:"USFANS REVIEW · AUGUST 2026", title:"USFans Review 2026: What Official Claims and Customer Feedback Actually Show", description:"A balanced review of the USFans shopping-agent workflow, its published policies and the recurring positives and complaints visible in independent customer feedback.", updated:"Updated August 13, 2026", readingTime:"14 minute read", contentsLabel:"IN THIS REVIEW", factTitle:"How this review was researched", factNote:"Platform features were checked against USFans’ public homepage and product-page workflow. Customer sentiment was reviewed across public Trustpilot and Reddit results available on August 13, 2026. Reviews are individual reports, not independently verified proof; both positive and negative claims are treated as signals rather than guaranteed outcomes.", imageCaption:"Catalog availability is only one part of the experience. A review must also examine QC, returns, support and final parcel handling.",
  sections:[
    {heading:"What USFans says it offers",paragraphs:["USFans presents itself as a shopping agent for Chinese marketplaces including Taobao, 1688 and Weidian. Its public pages describe a workflow in which an item is bought from a third-party seller, delivered to the USFans warehouse, checked and photographed, then held for the customer’s later international parcel decision. The homepage currently markets quality-checked purchases, real photo confirmation and shipping to more than 50 countries.","Product pages add two concrete policy points: three to seven free HD inspection photos and a five-day period to request a return after warehouse arrival if the buyer is dissatisfied. They also say agents negotiate after-sales issues with sellers. These published features are useful, but they should be understood precisely. A return request is not the same as automatic seller acceptance, and a photo inspection is not a guarantee of material quality or authenticity."]},
    {heading:"The useful part of the agent model",paragraphs:["The strongest reason to use an agent is the warehouse checkpoint. A direct international order may leave no practical chance to inspect the actual unit before it crosses borders. With USFans, the buyer can compare warehouse images with the original listing and decide whether a visible mismatch is serious enough to return. Consolidating several seller orders into a later parcel can also make purchasing from multiple marketplaces more manageable.","The model is most valuable for buyers who actively use that checkpoint. Someone who approves every item without opening the photos receives much less protection. Likewise, a shopper who ignores the second international-shipping payment may feel surprised even though the two-stage cost structure is normal for agents. The service is a tool for an informed buyer, not a replacement for product research and shipping judgment."]},
    {heading:"What public ratings showed on the review date",paragraphs:["On August 13, 2026, the public Trustpilot page for usfans.com displayed 683 reviews. The distribution shown in search results was 76 percent five-star, 7 percent four-star, 2 percent three-star, 1 percent two-star and 14 percent one-star. That is a strongly positive headline distribution with a meaningful negative tail. The same page also displayed a notice that a number of fake reviews had been removed, which is an important reason not to rely on the average alone.","A responsible reading looks for recurring themes rather than copying star counts into a verdict. Positive reviewers frequently mentioned an easy ordering interface, helpful support, satisfactory packaging, useful QC checks and deliveries arriving within the expected range. Critical reviewers raised slow or automated support, seller or warehouse delays, unexpectedly high shipping calculations, parcel handling choices and tracking that remained at an early status. These accounts conflict because customer routes, sellers, parcels and expectations differ."]},
    {heading:"Positive feedback: where satisfaction comes from",paragraphs:["The most credible positive reports tend to include operational detail: what was ordered, where it was shipped, how long a stage took, or how a problem was resolved. Public reviews include buyers who praised the usability of the platform, the availability of payment choices, warehouse-photo checking and support responses. Some reported that parcels arrived within the quoted window and were packed carefully. Others valued having a problem with an item handled before shipment.","Those experiences fit the intended agent workflow. A correct seller dispatch, clear warehouse photos, a suitable route and a responsive resolution can produce a smooth order. Still, statements such as “best” or “cheapest” are personal comparisons, not durable facts. Shipping prices depend on destination, route, parcel characteristics and promotions. A positive review is most useful when it describes the circumstances, not when it makes a universal claim."]},
    {heading:"Negative feedback: the risks to take seriously",paragraphs:["Critical reviews deserve equal attention, especially when they describe a specific stage. Some public complaints mention long waits for support, delayed seller or warehouse processing, disagreement over parcel weight, expensive shipping, split parcels or tracking that did not progress as expected. Reddit discussions include buyers worried about delays, weight estimates and communication. These reports do not prove every order will encounter the same issue, but they identify the checkpoints where documentation matters.","Separate seller delays from agent operations. USFans has replied publicly that delivery to its warehouse is determined by third-party sellers. That explanation is reasonable for domestic seller transit, but it does not answer every concern about warehouse processing, parcel decisions or support speed. If a delay occurs, identify the last completed stage: paid but not purchased, purchased but not shipped, domestic transit, warehouse intake, parcel packing or international carrier acceptance. A precise status makes escalation more productive."]},
    {heading:"Is USFans safe to use?",paragraphs:["No public review can guarantee that a future transaction will be risk-free. The available evidence shows an operating platform with a published warehouse workflow, inspection photos, after-sales process and a large body of mixed public feedback. It also shows non-trivial one-star criticism and a review-platform notice about removed fake reviews. The honest conclusion is not “always safe” or “always a scam”; it is that buyers should limit exposure and verify each stage.","Use a payment method that offers appropriate records and protections in your country. Start with a parcel value you can tolerate, save the seller listing, inspect QC photos promptly, and keep screenshots of service selections and support conversations. Do not buy prohibited goods or assume customs outcomes. When choosing a route, read the current restrictions and compensation rules. These habits reduce risk regardless of which agent is used."]},
    {heading:"Who is a good fit—and who is not",paragraphs:["USFans may suit a buyer who understands marketplace sellers, is willing to review warehouse evidence and accepts that international forwarding has variable cost and timing. It can be useful when products from different sellers need to reach one warehouse before a parcel decision. Buyers who value a visual checkpoint and can wait through several operational stages are more likely to understand the trade-off.","It is a poor fit for someone expecting a single all-inclusive checkout, guaranteed delivery date, guaranteed authenticity or instant support at every hour. It is also unsuitable for a time-critical purchase where a seller delay would ruin the purpose. If a buyer will not inspect QC images or compare shipping routes, the agent workflow adds complexity without delivering its main benefits."]},
    {heading:"Verdict: use evidence, not hype",paragraphs:["USFans’ published workflow contains genuinely useful tools: marketplace purchasing, warehouse receipt, real inspection photos, a stated five-day return-request window and international parcel handling. Public feedback shows many satisfied buyers, but it also records serious complaints about communication, timing and parcel costs. The sensible verdict is conditional: the platform can work well when the seller, warehouse stage and route align, yet it should be used with documented checkpoints rather than blind trust.","The review landscape itself requires caution. A high share of five-star ratings can reflect genuine satisfaction, while removed-fake-review notices and a substantial one-star share warn against treating the score as proof. Reddit complaints can reveal operational risks, but a single frustrated post may omit seller behaviour, route choice or the final resolution. The strongest evidence is specific, dated and tied to a stage of the order. Anything else should remain context, not a verdict.","Before the first order, read the current service and route terms rather than relying on a promotional video or an old coupon claim. During the order, judge the seller listing, warehouse photos and support evidence separately. Before shipping, verify the final package and route. After delivery, compare the actual item with the warehouse record. That evidence-led approach is slower than hype, but it produces a review—and a buying decision—that remains useful." ]}
  ]
});

const compact = (lang:Exclude<Lang,"en">,kind:HistoricArticleSlug,locale:Omit<Article,"sections"> & {sections:Array<[string,string]>}):Article => ({
  ...locale,
  sections:locale.sections.map(([heading,lead],index)=>({
    heading,
    paragraphs:[lead,...(articleDetails[lang]?.[kind]?.[index]||[])]
  }))
});

const translated = (lang:Exclude<Lang,"en">, base:Article, kind:HistoricArticleSlug):Article => {
  const ui:Record<Exclude<Lang,"en">,{updated:string;read:string;contents:string;fact:string;caption:string}>={
    de:{updated:"Aktualisiert am 13. August 2026",read:"Ausführlicher Leitfaden",contents:"INHALT",fact:"Geprüfte Grundlage",caption:"Katalogbilder helfen bei der Zuordnung; entscheidend sind die Lagerfotos des tatsächlich erhaltenen Artikels."},
    es:{updated:"Actualizado el 13 de agosto de 2026",read:"Guía detallada",contents:"CONTENIDO",fact:"Base verificada",caption:"Las fotos de catálogo sirven de referencia; la decisión debe basarse en las imágenes del artículo recibido."},
    fr:{updated:"Mis à jour le 13 août 2026",read:"Guide détaillé",contents:"SOMMAIRE",fact:"Base vérifiée",caption:"Les images catalogue servent de référence ; la décision repose sur les photos de l’article reçu."},
    it:{updated:"Aggiornato il 13 agosto 2026",read:"Guida dettagliata",contents:"CONTENUTO",fact:"Base verificata",caption:"Le immagini di catalogo sono un riferimento; contano le foto dell’articolo ricevuto."},
    pl:{updated:"Aktualizacja: 13 sierpnia 2026",read:"Szczegółowy poradnik",contents:"SPIS TREŚCI",fact:"Zweryfikowana podstawa",caption:"Zdjęcia katalogowe pomagają rozpoznać produkt; decyzję opieraj na zdjęciach magazynowych."},
    pt:{updated:"Atualizado em 13 de agosto de 2026",read:"Guia detalhado",contents:"CONTEÚDO",fact:"Base verificada",caption:"Fotos de catálogo são referência; a decisão deve usar as imagens do item recebido."},
    "zh-cn":{updated:"更新于 2026 年 8 月 13 日",read:"完整指南",contents:"文章目录",fact:"已核对的事实基础",caption:"商品图只能帮助确认款式，最终仍应查看实际到仓商品的仓库照片。"},
  };
  const data=translatedCore[lang][kind]; const common=ui[lang];
  return compact(lang,kind,{kicker:data.kicker,title:data.title,description:data.description,updated:common.updated,readingTime:common.read,contentsLabel:common.contents,factTitle:common.fact,factNote:data.fact,imageCaption:common.caption,sections:data.sections});
};

type CompactCore={kicker:string;title:string;description:string;fact:string;sections:Array<[string,string]>};
const translatedCore:Record<Exclude<Lang,"en">,Record<HistoricArticleSlug,CompactCore>> = {
  de:{
    "how-to-use-usfans":{kicker:"USFANS EINSTEIGERLEITFADEN · 2026",title:"USFans 2026 nutzen: Vom Produktlink zum internationalen Paket",description:"Ein faktenbasierter Ablauf zu Verkäuferlink, Lagerankunft, QC-Fotos, Rückgabe und Paketeinreichung.",fact:"USFans nennt öffentlich Taobao, 1688 und Weidian, Lagerprüfung mit echten Bildern, drei bis sieben kostenlose HD-Fotos und ein fünftägiges Rückgabe-Antragsfenster nach Lagereingang.",sections:[["Zweistufige Bestellung verstehen","Zuerst kauft der Agent beim Marktplatzverkäufer und empfängt die Ware in China; erst danach entscheidet der Käufer über den internationalen Versand. Verkäufer, Lager und Transport sind getrennte Verantwortungsbereiche."],["Mit einem sauberen Produktlink beginnen","Originalangebot, Variante, Größentabelle und Verkäuferhinweise speichern. Ein Angebot kann mehrere Farben, Chargen oder Zubehörteile enthalten; daher nie nur nach dem ersten Bild bestellen."],["Vor der Zahlung prüfen","Preis, Menge, Variante und Inlandsversand kontrollieren. Produktzahlung ist nicht der Endpreis, weil der internationale Versand später anhand des Pakets bezahlt wird."],["Lagerankunft richtig lesen","Nach dem Eingang wird der Artikel zugeordnet, geprüft und fotografiert. Alle drei bis sieben Bilder in voller Größe mit dem gespeicherten Angebot vergleichen."],["Fünf-Tage-Fenster nutzen","USFans nennt fünf Tage für einen Rückgabeantrag. Probleme konkret mit Foto und sichtbarer Abweichung beschreiben; Verkäuferbedingungen können weiterhin gelten."],["Paket bewusst aufbauen","Nur gewünschte Artikel einreichen. Konsolidierung, Schutz, Verpackungsentfernung, Maße und Routengrenzen gegeneinander abwägen."],["Versand mit Enddaten vergleichen","Endgewicht, Volumen, Einschränkungen, Tracking und Lieferfenster zählen mehr als der niedrigste Anfangspreis."],["Checkliste für die erste Bestellung","Klein starten, Links sichern, QC fristgerecht prüfen, Entscheidungen dokumentieren und mindestens zwei geeignete Routen vergleichen."]]},
    "usfans-qc-photos-guide":{kicker:"USFANS QC-FOTO-LEITFADEN · 2026",title:"USFans QC-Fotos richtig prüfen",description:"Eine Methode zum Erkennen sichtbarer Abweichungen vor dem internationalen Versand.",fact:"USFans beschreibt eine Lagerprüfung, drei bis sieben kostenlose HD-Fotos und fünf Tage für einen Rückgabeantrag. Fotos sind keine Echtheits- oder Materialgarantie.",sections:[["Was QC beweisen kann","Fotos zeigen Farbe, Form, Etiketten, Druck und sichtbare Schäden, aber nicht Material, Haltbarkeit, Funktion oder Echtheit."],["Referenz vorbereiten","Angebot, Variante, Größentabelle und wichtige Detailbilder bereits beim Kauf speichern."],["Komplettes Set öffnen","Alle Bilder groß öffnen und Front, Rückseite, Seiten, Etikett und Maße prüfen. Fehlende kritische Winkel gezielt nachfordern."],["Schuhe prüfen","Paarweise Symmetrie, Größe, Zehenform, Nähte, Kleber, Sohlen und Maße vergleichen."],["Kleidung und Trikots","Maße vor Etikett priorisieren; Druck, Stickerei, Kragen, Bündchen, Reißverschluss, Namen und Nummern prüfen."],["Taschen und Zubehör","Form, Beschläge, Riemen, Verschluss, Innenraum und alle abnehmbaren Teile kontrollieren."],["Behalten, fragen oder zurückgeben","Bei Übereinstimmung behalten, bei fehlendem Beweis nachfragen und bei klarer Abweichung fristgerecht zurückgeben."],["QC-Nachweis sichern","Angebot, Bilder, Maße und Supportantworten bis zur Lieferung gemeinsam aufbewahren."]]},
    "usfans-review-2026":{kicker:"USFANS TEST · AUGUST 2026",title:"USFans Erfahrungen 2026: Fakten, Bewertungen und Risiken",description:"Eine ausgewogene Prüfung der offiziellen Abläufe und wiederkehrender positiver wie negativer Kundenberichte.",fact:"Funktionen wurden mit öffentlichen USFans-Seiten abgeglichen; öffentliche Trustpilot- und Reddit-Ergebnisse wurden am 13. August 2026 ausgewertet. Einzelberichte sind Signale, keine Beweise für jede Bestellung.",sections:[["Offizielles Angebot","USFans beschreibt Einkäufe bei Taobao, 1688 und Weidian, Lagerfotos, ein Rückgabeverfahren und internationalen Versand in mehr als 50 Länder."],["Nutzen des Agentenmodells","Der wichtigste Vorteil ist die Prüfung des tatsächlichen Artikels vor dem grenzüberschreitenden Versand."],["Öffentliche Bewertungsdaten","Trustpilot zeigte am Stichtag 683 Bewertungen: 76 % fünf Sterne und 14 % ein Stern sowie einen Hinweis auf entfernte Fake-Bewertungen."],["Positive Muster","Gelobt werden häufig Bedienung, QC, Verpackung, Support und pünktliche Lieferung; konkrete Erfahrungsdetails sind aussagekräftiger als Superlative."],["Negative Muster","Kritik betrifft Kommunikation, Verzögerungen, Gewicht, Versandkosten, Paketaufteilung und Tracking. Jeder Fall muss der richtigen Stufe zugeordnet werden."],["Ist USFans sicher?","Keine Bewertung garantiert Risikofreiheit. Klein starten, Belege speichern, sichere Zahlungswege nutzen und jede Stufe prüfen."],["Für wen geeignet?","Geeignet für geduldige Käufer, die Fotos und Routen aktiv vergleichen; ungeeignet bei garantierten Terminen oder All-inclusive-Erwartungen."],["Urteil","Nützliche Werkzeuge treffen auf gemischte Erfahrungen. Evidenz und dokumentierte Entscheidungen sind sinnvoller als blindes Vertrauen."]]},
  },
  es:{
    "how-to-use-usfans":{kicker:"GUÍA USFANS · 2026",title:"Cómo usar USFans en 2026: del enlace al paquete internacional",description:"Proceso basado en hechos sobre vendedor, almacén, fotos QC, devolución y envío.",fact:"USFans publica compatibilidad con Taobao, 1688 y Weidian, inspección con fotos reales, tres a siete imágenes HD gratuitas y cinco días para solicitar devolución tras la llegada.",sections:[["Entender las dos etapas","Primero el agente compra y recibe en China; después el comprador decide el envío internacional. Vendedor, almacén y transportista tienen responsabilidades distintas."],["Empezar con un enlace claro","Guarda anuncio, variante, talla y condiciones. No supongas que la primera foto representa todas las opciones."],["Revisar antes de pagar","Confirma precio, cantidad, variante y entrega nacional. El pago del producto no incluye necesariamente el paquete internacional."],["Interpretar la llegada","Abre todas las fotos HD y compáralas con el anuncio guardado, incluida talla, color, construcción y accesorios."],["Usar los cinco días","Describe cualquier problema con datos visibles y una foto. La devolución depende también de las condiciones del vendedor."],["Preparar el paquete","Incluye solo lo aprobado y equilibra consolidación, protección, medidas y límites de ruta."],["Comparar rutas","Utiliza peso y dimensiones finales, restricciones, seguimiento y plazo, no solo el precio inicial."],["Lista para el primer pedido","Empieza pequeño, guarda pruebas, revisa QC a tiempo y compara al menos dos rutas adecuadas."]]},
    "usfans-qc-photos-guide":{kicker:"GUÍA DE FOTOS QC · 2026",title:"Cómo revisar las fotos QC de USFans",description:"Método para detectar diferencias visibles antes del envío.",fact:"USFans describe inspección en almacén, tres a siete fotos HD gratuitas y cinco días para solicitar devolución. Las fotos no garantizan autenticidad ni materiales.",sections:[["Qué puede demostrar QC","Permite revisar color, forma, etiquetas, impresión y daños, pero no autenticidad, materiales o duración."],["Preparar referencia","Guarda anuncio, variante, tabla de tallas y detalles antes de comprar."],["Abrir el conjunto completo","Mira las imágenes a tamaño completo y pide un ángulo concreto cuando falte un detalle decisivo."],["Revisar zapatillas","Compara simetría, talla, forma, costuras, pegamento, suelas y medidas."],["Ropa y camisetas","Prioriza medidas; revisa impresión, bordado, cuello, cremalleras, nombre y número."],["Bolsos y accesorios","Comprueba forma, herrajes, correa, cierre, interior y piezas extraíbles."],["Conservar, preguntar o devolver","Decide según evidencia y usa el plazo cuando exista una diferencia clara."],["Guardar el registro","Conserva anuncio, fotos, medidas y respuestas hasta recibir el paquete."]]},
    "usfans-review-2026":{kicker:"RESEÑA USFANS · AGOSTO 2026",title:"USFans opiniones 2026: hechos, experiencias y riesgos",description:"Análisis equilibrado de las afirmaciones oficiales y comentarios positivos y negativos.",fact:"Las funciones se contrastaron con páginas públicas de USFans y las opiniones con resultados públicos de Trustpilot y Reddit del 13 de agosto de 2026. Son señales, no garantías.",sections:[["Qué ofrece USFans","USFans describe compras en Taobao, 1688 y Weidian, fotos de almacén, devolución y envío a más de 50 países."],["Valor del modelo","La principal ventaja es revisar el artículo real antes de enviarlo internacionalmente."],["Datos de reseñas","Trustpilot mostraba 683 reseñas: 76 % de cinco estrellas y 14 % de una, además de un aviso sobre reseñas falsas eliminadas."],["Opiniones positivas","Se mencionan facilidad, QC, embalaje, ayuda y entregas dentro del plazo; los detalles concretos valen más que los superlativos."],["Opiniones negativas","Las quejas hablan de comunicación, demoras, peso, coste, división de paquetes y seguimiento."],["¿Es seguro?","Ninguna reseña elimina el riesgo. Empieza pequeño, guarda pruebas y verifica cada etapa."],["Para quién sirve","Adecuado para quien compara fotos y rutas; no para quien exige fecha garantizada o precio todo incluido."],["Veredicto","Hay herramientas útiles y experiencias mixtas. La evidencia es mejor que la confianza ciega."]]},
  },
  fr:{
    "how-to-use-usfans":{kicker:"GUIDE USFANS · 2026",title:"Utiliser USFans en 2026 : du lien au colis international",description:"Parcours factuel couvrant vendeur, entrepôt, photos QC, retour et envoi.",fact:"USFans cite Taobao, 1688 et Weidian, trois à sept photos HD gratuites et cinq jours pour demander un retour après l’arrivée.",sections:[["Deux étapes distinctes","L’agent achète et reçoit en Chine, puis le client choisit le transport international. Vendeur, entrepôt et transporteur sont distincts."],["Partir d’un lien propre","Sauvegardez annonce, variante, taille et conditions. La première image ne représente pas toujours toutes les options."],["Vérifier avant paiement","Contrôlez prix, quantité, variante et livraison locale. Le transport international sera généralement payé plus tard."],["Lire l’arrivée en entrepôt","Ouvrez toutes les photos et comparez couleur, taille, fabrication et accessoires avec l’annonce."],["Utiliser les cinq jours","Décrivez précisément l’écart visible. L’acceptation reste soumise aux conditions du vendeur."],["Construire le colis","N’incluez que les articles validés et arbitrez consolidation, protection, dimensions et limites."],["Comparer les routes","Utilisez poids final, volume, restrictions, suivi et délai plutôt que le seul prix."],["Première commande","Commencez petit, gardez les preuves, contrôlez vite et comparez plusieurs routes."]]},
    "usfans-qc-photos-guide":{kicker:"GUIDE PHOTOS QC · 2026",title:"Bien contrôler les photos QC USFans",description:"Méthode pour repérer les écarts visibles avant l’envoi.",fact:"USFans décrit un contrôle, trois à sept photos HD gratuites et cinq jours pour demander un retour. Les images ne garantissent ni authenticité ni matière.",sections:[["Ce que QC prouve","Les photos montrent couleur, forme, étiquette, impression et dommages, pas la durabilité ou l’authenticité."],["Préparer une référence","Sauvegardez annonce, variante, tailles et détails avant l’achat."],["Ouvrir toutes les photos","Examinez les fichiers en grand et demandez un angle précis si un point décisif manque."],["Chaussures","Comparez symétrie, taille, forme, coutures, colle, semelles et mesures."],["Vêtements et maillots","Priorisez les mesures et contrôlez impression, broderie, col, zip, nom et numéro."],["Sacs et accessoires","Vérifiez forme, métal, bandoulière, fermeture, intérieur et pièces amovibles."],["Garder, demander, retourner","Décidez selon l’évidence et utilisez le délai pour un écart clair."],["Conserver le dossier","Gardez annonce, photos, mesures et réponses jusqu’à la livraison."]]},
    "usfans-review-2026":{kicker:"AVIS USFANS · AOÛT 2026",title:"Avis USFans 2026 : faits, retours clients et risques",description:"Analyse équilibrée des affirmations officielles et des retours positifs et négatifs.",fact:"Les fonctions ont été vérifiées sur les pages publiques USFans et les signaux clients sur Trustpilot et Reddit au 13 août 2026. Un avis n’est pas une garantie.",sections:[["Offre officielle","USFans décrit les achats Taobao, 1688 et Weidian, photos, retours et envoi vers plus de 50 pays."],["Valeur du modèle","L’avantage principal est de voir l’article réel avant le transport international."],["Données publiques","Trustpilot affichait 683 avis, 76 % cinq étoiles et 14 % une étoile, avec un avis de suppression de faux commentaires."],["Retours positifs","Facilité, QC, emballage, support et respect des délais reviennent souvent."],["Retours négatifs","Communication, retards, poids, prix, colis séparés et suivi sont les critiques récurrentes."],["Est-ce sûr ?","Aucun avis n’élimine le risque. Commencez petit, conservez les preuves et contrôlez chaque étape."],["Pour quel acheteur ?","Adapté à celui qui compare photos et routes; moins adapté aux délais garantis ou prix tout compris."],["Verdict","Outils utiles et expériences mixtes imposent une décision fondée sur les preuves."]]},
  },
  it:{
    "how-to-use-usfans":{kicker:"GUIDA USFANS · 2026",title:"Come usare USFans nel 2026: dal link al pacco internazionale",description:"Percorso basato su fatti: venditore, magazzino, foto QC, reso e spedizione.",fact:"USFans cita Taobao, 1688 e Weidian, tre-sette foto HD gratuite e cinque giorni per chiedere il reso dopo l’arrivo.",sections:[["Capire le due fasi","L’agente compra e riceve in Cina; poi il cliente decide la spedizione internazionale. Venditore, magazzino e corriere sono distinti."],["Usare un link chiaro","Salva inserzione, variante, taglia e condizioni. La prima foto non rappresenta sempre tutte le opzioni."],["Controllare prima del pagamento","Verifica prezzo, quantità, variante e consegna locale. Il trasporto internazionale è un costo successivo."],["Leggere l’arrivo","Apri tutte le foto e confronta colore, taglia, costruzione e accessori con l’inserzione."],["Usare i cinque giorni","Descrivi la differenza visibile con precisione; valgono anche le condizioni del venditore."],["Preparare il pacco","Inserisci solo gli articoli approvati e valuta protezione, dimensioni e limiti della rotta."],["Confrontare le rotte","Usa peso finale, volume, restrizioni, tracking e tempi, non solo il prezzo."],["Primo ordine","Inizia piccolo, conserva prove, controlla in tempo e confronta più rotte."]]},
    "usfans-qc-photos-guide":{kicker:"GUIDA FOTO QC · 2026",title:"Come controllare le foto QC USFans",description:"Metodo per individuare differenze visibili prima della spedizione.",fact:"USFans descrive controllo, tre-sette foto HD gratuite e cinque giorni per il reso. Le foto non garantiscono autenticità o materiali.",sections:[["Cosa prova il QC","Mostra colore, forma, etichette, stampa e danni, non durata o autenticità."],["Preparare riferimento","Salva inserzione, variante, misure e dettagli prima dell’acquisto."],["Aprire tutte le foto","Guarda i file grandi e chiedi un angolo preciso se manca un elemento decisivo."],["Scarpe","Confronta simmetria, taglia, forma, cuciture, colla, suole e misure."],["Abbigliamento e maglie","Dai priorità alle misure e controlla stampa, ricamo, colletto, zip, nome e numero."],["Borse e accessori","Verifica forma, metallo, tracolla, chiusura, interno e parti rimovibili."],["Tenere, chiedere o rendere","Decidi sulle prove e usa il termine quando c’è una differenza chiara."],["Conservare il registro","Tieni inserzione, foto, misure e risposte fino alla consegna."]]},
    "usfans-review-2026":{kicker:"RECENSIONE USFANS · AGOSTO 2026",title:"USFans recensioni 2026: fatti, esperienze e rischi",description:"Analisi equilibrata delle dichiarazioni ufficiali e dei feedback positivi e negativi.",fact:"Funzioni verificate su pagine pubbliche USFans; opinioni lette su Trustpilot e Reddit il 13 agosto 2026. Le esperienze sono segnali, non garanzie.",sections:[["Offerta ufficiale","USFans descrive acquisti Taobao, 1688 e Weidian, foto, resi e spedizione in oltre 50 paesi."],["Valore del modello","Il vantaggio principale è vedere l’articolo reale prima della spedizione internazionale."],["Dati pubblici","Trustpilot mostrava 683 recensioni, 76% cinque stelle e 14% una stella, con avviso su recensioni false rimosse."],["Feedback positivo","Facilità, QC, imballaggio, supporto e consegne puntuali sono temi frequenti."],["Feedback negativo","Comunicazione, ritardi, peso, costo, pacchi divisi e tracking sono critiche ricorrenti."],["È sicuro?","Nessuna recensione elimina il rischio. Inizia piccolo, conserva prove e verifica ogni fase."],["A chi conviene","Adatto a chi confronta foto e rotte; meno adatto a date garantite o costo tutto compreso."],["Verdetto","Strumenti utili e risultati misti richiedono decisioni basate sulle prove."]]},
  },
  pl:{
    "how-to-use-usfans":{kicker:"PORADNIK USFANS · 2026",title:"Jak korzystać z USFans w 2026: od linku do paczki",description:"Oparty na faktach proces sprzedawcy, magazynu, zdjęć QC, zwrotu i wysyłki.",fact:"USFans wymienia Taobao, 1688 i Weidian, trzy-siedem bezpłatnych zdjęć HD i pięć dni na wniosek o zwrot po przyjęciu.",sections:[["Dwa etapy","Agent kupuje i przyjmuje w Chinach, a następnie klient wybiera wysyłkę międzynarodową. Sprzedawca, magazyn i przewoźnik odpowiadają za różne etapy."],["Czysty link","Zapisz ofertę, wariant, rozmiar i zasady. Pierwsze zdjęcie nie zawsze przedstawia każdą opcję."],["Kontrola przed płatnością","Sprawdź cenę, ilość, wariant i dostawę krajową. Międzynarodowa paczka jest późniejszym kosztem."],["Przyjęcie magazynowe","Otwórz wszystkie zdjęcia i porównaj kolor, rozmiar, wykonanie oraz dodatki."],["Pięć dni","Opisz widoczną różnicę konkretnie; nadal obowiązują warunki sprzedawcy."],["Budowa paczki","Wybierz tylko zatwierdzone rzeczy i porównaj ochronę, wymiary i limity tras."],["Porównanie tras","Użyj końcowej wagi, objętości, ograniczeń, śledzenia i czasu, nie tylko ceny."],["Pierwsze zamówienie","Zacznij mało, zachowaj dowody, sprawdź QC na czas i porównaj kilka tras."]]},
    "usfans-qc-photos-guide":{kicker:"PORADNIK ZDJĘĆ QC · 2026",title:"Jak sprawdzać zdjęcia QC USFans",description:"Metoda wykrywania widocznych różnic przed wysyłką.",fact:"USFans opisuje kontrolę, trzy-siedem darmowych zdjęć HD i pięć dni na zwrot. Zdjęcia nie gwarantują autentyczności ani materiału.",sections:[["Co pokazuje QC","Zdjęcia pokazują kolor, kształt, metki, nadruk i szkody, lecz nie trwałość czy autentyczność."],["Przygotuj wzór","Zapisz ofertę, wariant, tabelę rozmiarów i ważne detale."],["Otwórz komplet","Oglądaj duże pliki i poproś o konkretny kąt, gdy brakuje ważnego szczegółu."],["Buty","Porównaj symetrię, rozmiar, kształt, szwy, klej, podeszwy i wymiary."],["Odzież i koszulki","Najpierw wymiary, potem nadruk, haft, kołnierz, zamek, nazwisko i numer."],["Torby i dodatki","Sprawdź formę, okucia, pasek, zapięcie, wnętrze i części odpinane."],["Zostaw, zapytaj lub zwróć","Decyduj na podstawie dowodów i użyj terminu przy wyraźnej różnicy."],["Zachowaj dokumentację","Trzymaj ofertę, zdjęcia, wymiary i odpowiedzi do dostawy."]]},
    "usfans-review-2026":{kicker:"RECENZJA USFANS · SIERPIEŃ 2026",title:"USFans opinie 2026: fakty, doświadczenia i ryzyko",description:"Wyważona analiza oficjalnych informacji oraz pozytywnych i negatywnych relacji.",fact:"Funkcje sprawdzono na publicznych stronach USFans, a sygnały opinii na Trustpilot i Reddit 13 sierpnia 2026. Pojedyncze relacje nie są gwarancją.",sections:[["Oficjalna oferta","USFans opisuje zakupy Taobao, 1688 i Weidian, zdjęcia, zwroty i wysyłkę do ponad 50 krajów."],["Wartość modelu","Najważniejszą zaletą jest obejrzenie rzeczywistego produktu przed wysyłką zagraniczną."],["Dane opinii","Trustpilot pokazywał 683 opinie: 76% pięciu gwiazdek i 14% jednej, plus informację o usuniętych fałszywych recenzjach."],["Pozytywne wzorce","Użytkownicy chwalą prostotę, QC, pakowanie, pomoc i terminowe dostawy."],["Negatywne wzorce","Krytyka dotyczy komunikacji, opóźnień, wagi, kosztu, dzielenia paczek i śledzenia."],["Czy jest bezpiecznie?","Żadna recenzja nie usuwa ryzyka. Zacznij mało, zachowaj dowody i kontroluj etapy."],["Dla kogo","Dla osób porównujących zdjęcia i trasy; nie dla gwarantowanych terminów i ceny all-inclusive."],["Werdykt","Przydatne narzędzia i mieszane doświadczenia wymagają decyzji opartych na dowodach."]]},
  },
  pt:{
    "how-to-use-usfans":{kicker:"GUIA USFANS · 2026",title:"Como usar a USFans em 2026: do link ao pacote internacional",description:"Fluxo baseado em fatos sobre vendedor, armazém, fotos QC, devolução e envio.",fact:"A USFans cita Taobao, 1688 e Weidian, três a sete fotos HD gratuitas e cinco dias para solicitar devolução após a chegada.",sections:[["Duas etapas","O agente compra e recebe na China; depois o cliente escolhe o envio internacional. Vendedor, armazém e transportadora são distintos."],["Começar com um link claro","Salve anúncio, variante, tamanho e condições. A primeira foto nem sempre representa todas as opções."],["Revisar antes de pagar","Confira preço, quantidade, variante e entrega local. O frete internacional é uma etapa posterior."],["Entender a chegada","Abra todas as fotos e compare cor, tamanho, construção e acessórios com o anúncio."],["Usar os cinco dias","Descreva a diferença visível com precisão; as condições do vendedor ainda se aplicam."],["Montar o pacote","Inclua apenas itens aprovados e compare proteção, dimensões e limites de rota."],["Comparar rotas","Use peso final, volume, restrições, rastreio e prazo, não só o preço."],["Primeiro pedido","Comece pequeno, guarde provas, revise o QC a tempo e compare rotas."]]},
    "usfans-qc-photos-guide":{kicker:"GUIA DE FOTOS QC · 2026",title:"Como revisar fotos QC da USFans",description:"Método para detectar diferenças visíveis antes do envio.",fact:"A USFans descreve inspeção, três a sete fotos HD gratuitas e cinco dias para devolução. Fotos não garantem autenticidade ou materiais.",sections:[["O que o QC mostra","Fotos mostram cor, forma, etiquetas, estampa e danos, não durabilidade ou autenticidade."],["Preparar referência","Salve anúncio, variante, tabela e detalhes antes da compra."],["Abrir o conjunto","Veja arquivos grandes e peça um ângulo específico se faltar um detalhe decisivo."],["Tênis","Compare simetria, tamanho, forma, costura, cola, sola e medidas."],["Roupas e camisas","Priorize medidas; confira estampa, bordado, gola, zíper, nome e número."],["Bolsas e acessórios","Verifique forma, ferragens, alça, fecho, interior e peças removíveis."],["Manter, perguntar ou devolver","Decida pelas provas e use o prazo quando houver diferença clara."],["Guardar o registro","Mantenha anúncio, fotos, medidas e respostas até a entrega."]]},
    "usfans-review-2026":{kicker:"AVALIAÇÃO USFANS · AGOSTO 2026",title:"USFans avaliações 2026: fatos, experiências e riscos",description:"Análise equilibrada das afirmações oficiais e feedbacks positivos e negativos.",fact:"Funções verificadas em páginas públicas da USFans; opiniões observadas em Trustpilot e Reddit em 13 de agosto de 2026. Relatos são sinais, não garantias.",sections:[["Oferta oficial","A USFans descreve compras Taobao, 1688 e Weidian, fotos, devoluções e envio para mais de 50 países."],["Valor do modelo","A principal vantagem é ver o item real antes do frete internacional."],["Dados públicos","Trustpilot mostrava 683 avaliações, 76% cinco estrelas e 14% uma estrela, além de aviso sobre avaliações falsas removidas."],["Feedback positivo","Facilidade, QC, embalagem, suporte e entregas no prazo aparecem com frequência."],["Feedback negativo","Comunicação, atrasos, peso, custo, divisão de pacotes e rastreio são críticas recorrentes."],["É seguro?","Nenhuma avaliação elimina o risco. Comece pequeno, guarde provas e verifique cada etapa."],["Para quem serve","Adequado para quem compara fotos e rotas; menos para prazo garantido ou preço completo."],["Veredito","Ferramentas úteis e experiências mistas pedem decisões baseadas em evidências."]]},
  },
  "zh-cn":{
    "how-to-use-usfans":{kicker:"USFANS 新手指南 · 2026",title:"2026 年如何使用 USFans：从商品链接到国际包裹",description:"依据公开事实整理卖家链接、到仓、质检照片、退货和提交包裹的完整流程。",fact:"USFans 公开写明支持淘宝、1688 和微店商品采购，商品到仓后检查拍照，商品页目前写明提供 3–7 张免费高清照片，并设有到仓后 5 天退货申请期限。",sections:[["理解两个费用和运输阶段","第一阶段由代理向平台卖家采购并在中国仓库收货，第二阶段才由客户选择国际运输。卖家、仓库和国际承运商的责任不能混在一起。"],["从准确商品链接开始","保存原商品页、规格、尺码表、卖家说明和截图。不要因为第一张图相同就默认所有颜色、批次或配件都一样。"],["支付商品前再检查一次","确认价格、数量、规格和国内运费。商品付款并不是最终到手成本，国际包裹通常会在到仓打包后单独支付。"],["正确理解商品到仓","到仓代表进入检查节点，不代表订单已经完成。应打开全部照片，对比颜色、尺码标签、做工、破损和配件。"],["谨慎使用 5 天退货申请期","发现问题时用具体照片和可见差异说明。5 天是申请窗口，并不代表任何卖家都会无条件接受退货。"],["有目的地整理包裹","只提交确认保留的商品，并比较合包、去包装、加固、体积重量和线路限制。"],["用最终数据比较运输线路","比较打包后重量尺寸、限制、追踪、预计时效和赔付规则，而不是只看最低报价。"],["第一次下单检查表","小额开始、保存证据、及时查看质检、记录售后结果，并至少比较两条适合当前包裹的线路。"]]},
    "usfans-qc-photos-guide":{kicker:"USFANS 质检照片指南 · 2026",title:"USFans 质检照片怎么看：国际运输前的检查方法",description:"按商品类别检查仓库照片，识别可见差异，并在公开期限内作出决定。",fact:"USFans 公开流程写明商品到仓后检查拍照，商品页目前写明提供 3–7 张免费高清照片和 5 天退货申请期。照片不能证明真伪、材料或长期耐用性。",sections:[["质检照片能证明什么","它可以显示颜色、外形、标签、印花和明显破损，但不能证明面料、功能、耐用性或真伪。"],["到仓前先准备参照","购买时保存商品页、所选规格、尺码表和影响决定的卖家细节图。"],["打开完整照片组","不要只看缩略图。检查正反面、侧面、标签和测量图；缺少关键角度时应提出明确补拍要求。"],["鞋类检查重点","对比左右对称、尺码标签、鞋头、车线、胶水、鞋底颜色和可用测量数据。"],["服装和球衣检查重点","尺码测量优先于标签，再检查印花、刺绣、领口、袖口、拉链、球员姓名和号码。"],["包袋与配件检查重点","检查包型、五金颜色、肩带连接、开合、内里和所选规格应包含的可拆部件。"],["保留、补证据还是退货","一致就保留，关键细节缺失就补拍，已存在明显错误或破损就及时申请退货。"],["保存完整质检记录","把商品页、仓库照片、测量记录和客服回复保留到最终收货。"]]},
    "usfans-review-2026":{kicker:"USFANS 客户评价分析 · 2026 年 8 月",title:"USFans 2026 评价：官方信息、客户反馈与实际风险",description:"同时查看官方流程、正面体验和负面投诉，不用营销口号替代事实。",fact:"平台功能依据 USFans 当前公开页面核对；客户反馈参考了 2026 年 8 月 13 日可见的 Trustpilot 和 Reddit 公开结果。个人评价只能作为信号，不能保证下一笔订单结果。",sections:[["USFans 官方提供什么","USFans 公开描述其支持淘宝、1688 和微店采购、仓库照片、售后处理，并宣传向 50 多个国家发货。"],["购物代理模式的实际价值","最重要的价值是国际运输之前，客户有机会看到实际到仓商品，而不是只依赖卖家宣传图。"],["评价数据怎么看","2026 年 8 月 13 日，Trustpilot 公开页显示 683 条评价，其中 76% 为五星、14% 为一星，并提示曾移除部分虚假评价。"],["正面反馈的共同点","界面容易使用、质检有帮助、包装满意、客服解决问题和按预计时效送达，是常见正面主题。"],["负面反馈需要重视什么","沟通慢、等待时间、重量争议、运费、拆分包裹和追踪停滞，是反复出现的投诉方向。"],["USFans 是否安全","任何评价都不能保证零风险。更稳妥的做法是小额开始、保存付款与服务证据，并逐阶段核对。"],["适合与不适合的人","适合愿意检查照片和比较线路的客户；不适合要求一次付清、保证日期或保证真伪的人。"],["结论：相信证据，不信夸张口号","USFans 有实用的仓库和照片工具，也存在明显的负面反馈。应通过记录和节点检查作出决定。"]]},
  }
};

export const articleData:Record<Lang,Record<ArticleSlug,Article>> = {
  en:{"how-to-use-usfans":guideEn,"usfans-qc-photos-guide":qcEn,"usfans-review-2026":reviewEn,"usfans-shoes-listing-checklist":shoesListingArticle.en},
  de:{"how-to-use-usfans":translated("de",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("de",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("de",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.de},
  es:{"how-to-use-usfans":translated("es",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("es",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("es",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.es},
  fr:{"how-to-use-usfans":translated("fr",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("fr",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("fr",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.fr},
  it:{"how-to-use-usfans":translated("it",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("it",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("it",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.it},
  pl:{"how-to-use-usfans":translated("pl",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("pl",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("pl",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.pl},
  pt:{"how-to-use-usfans":translated("pt",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("pt",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("pt",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle.pt},
  "zh-cn":{"how-to-use-usfans":translated("zh-cn",guideEn,"how-to-use-usfans"),"usfans-qc-photos-guide":translated("zh-cn",qcEn,"usfans-qc-photos-guide"),"usfans-review-2026":translated("zh-cn",reviewEn,"usfans-review-2026"),"usfans-shoes-listing-checklist":shoesListingArticle["zh-cn"]},
};
