import type { Lang } from "./site-shell";
import { allArticles, allShipping } from "./content-data";
export const articleSlugs = ["usfans-jacket-finds-sizing-packing", "usfans-pants-shorts-waist-inseam", "usfans-t-shirt-finds-sizing-print", "how-to-use-usfans", "usfans-bag-accessory-listing-checklist", "usfans-hoodie-listing-checklist", "usfans-jersey-listing-checklist", "usfans-listing-red-flags", "usfans-product-links-guide", "usfans-qc-photos-guide", "usfans-review-2026", "usfans-shoes-listing-checklist", "usfans-spreadsheet-2026", "usfans-wear-size-fabric-guide"] as const;
export type ArticleSlug = typeof articleSlugs[number];
export const localizedArticleSlugs: readonly ArticleSlug[] = articleSlugs;
export const articleSlugsForLanguage = (_lang:Lang): readonly ArticleSlug[] => articleSlugs;
export type Article = { slug:string; lang:string; published:string; modified:string; kicker:string; title:string; description:string; updated:string; readingTime:string; contentsLabel:string; factTitle:string; factNote:string; imageCaption:string; sections:Array<{heading:string;paragraphs:string[]}> };
export const faqText: Record<Lang,FaqLocale> = {
  en:{label:"FAQ",eyebrow:"FREQUENTLY ASKED QUESTIONS",title:"Clear answers before you place an order.",body:"Ten practical answers based on the workflow and policies currently described on USFans’ public pages.",cardTitle:"Questions worth answering before checkout.",cardBody:"Returns, warehouse photos, seller delivery, international shipping and what an agent actually does.",open:"Open all answers",questions:[
    {q:"What is USFans?",a:"USFans describes itself as a shopping-agent platform for purchasing from Chinese marketplaces such as Taobao, 1688 and Weidian. The agent purchases from the seller, receives the item at its warehouse, provides inspection photos and later handles the international parcel selected by the customer."},
    {q:"Does USFans sell the products itself?",a:"Usually the underlying item comes from a third-party marketplace seller. That distinction matters: seller dispatch time and product quality are not the same thing as the agent’s warehouse and forwarding service."},
    {q:"What happens after a seller sends an item?",a:"The public product-page workflow says the item goes to the USFans warehouse, where staff check it and take pictures. The customer can review those images before deciding whether to keep, return or later submit the item for international shipping."},
    {q:"How many QC photos are provided?",a:"USFans product pages currently advertise three to seven free HD inspection photos. The exact angles can vary by item, so buyers should still compare every available image with the seller listing."},
    {q:"Can an item be returned from the warehouse?",a:"USFans product pages currently state that a return can be requested within five days after warehouse arrival if the buyer is dissatisfied. Acceptance can still depend on the seller and the item’s after-sales conditions, so inspect promptly."},
    {q:"Why can seller delivery to the warehouse take longer than expected?",a:"USFans has publicly explained that delivery to its warehouse is controlled by the third-party seller. An estimated warehouse-arrival time is therefore not the same as a guaranteed purchasing or dispatch deadline."},
    {q:"Is product payment the final cost?",a:"No. A cross-border agent order normally has at least two cost stages: purchasing the item and later paying for the international parcel. Optional services, packaging, route rules and billable weight can affect the second stage."},
    {q:"How should I compare international shipping routes?",a:"Use the final packed weight and dimensions, destination, restrictions, estimated delivery range and available tracking—not only the lowest headline price. The route available for one parcel may not be available for another."},
    {q:"Are QC photos a guarantee of quality or authenticity?",a:"No. Photos are visual evidence of the item received at the warehouse. They help detect visible colour, size, construction or damage issues, but cannot prove materials, long-term durability or authenticity."},
    {q:"What should a first-time buyer do before parcel submission?",a:"Save the original listing, confirm the selected variant, inspect all warehouse photos promptly, resolve returns within the displayed window, remove unwanted items, then compare shipping routes using the final parcel information."},
  ]},
  de:{label:"FAQ",eyebrow:"HÄUFIGE FRAGEN",title:"Klare Antworten vor der Bestellung.",body:"Zehn praktische Antworten auf Grundlage der öffentlich beschriebenen USFans-Abläufe und Richtlinien.",cardTitle:"Fragen, die vor dem Kauf geklärt sein sollten.",cardBody:"Rückgaben, Lagerfotos, Verkäuferlieferung, internationaler Versand und die Rolle eines Agenten.",open:"Alle Antworten öffnen",questions:[
    {q:"Was ist USFans?",a:"USFans beschreibt sich als Einkaufsagent für Marktplätze wie Taobao, 1688 und Weidian. Der Agent kauft beim Verkäufer, empfängt die Ware im Lager, stellt Prüffotos bereit und organisiert später den gewählten internationalen Versand."},{q:"Verkauft USFans die Produkte selbst?",a:"Das Produkt stammt normalerweise von einem externen Marktplatzverkäufer. Verkäuferzeit und Produktqualität müssen daher vom Lager- und Weiterleitungsservice getrennt bewertet werden."},{q:"Was passiert nach dem Versand durch den Verkäufer?",a:"Die Ware kommt ins USFans-Lager, wird geprüft und fotografiert. Danach kann der Käufer behalten, eine Rückgabe beantragen oder später den internationalen Versand einreichen."},{q:"Wie viele QC-Fotos gibt es?",a:"USFans bewirbt derzeit drei bis sieben kostenlose HD-Prüffotos. Winkel können je nach Produkt variieren; alle Bilder sollten mit dem Angebot verglichen werden."},{q:"Kann man aus dem Lager zurückgeben?",a:"Öffentliche Produktseiten nennen derzeit ein Rückgabefenster von fünf Tagen nach Lagereingang. Verkäuferbedingungen können trotzdem gelten, daher schnell prüfen."},{q:"Warum dauert die Lieferung ins Lager manchmal länger?",a:"USFans erklärt, dass die Zustellung zum Lager vom Drittverkäufer abhängt. Eine Schätzung ist keine garantierte Frist."},{q:"Ist der Produktpreis der Endpreis?",a:"Nein. Produktkauf und internationaler Versand sind getrennte Kostenstufen. Verpackung, Zusatzleistungen, Routen und abrechenbares Gewicht beeinflussen die zweite Stufe."},{q:"Wie vergleicht man Versandrouten?",a:"Vergleiche Endgewicht, Maße, Ziel, Einschränkungen, Lieferfenster und Tracking – nicht nur den niedrigsten Preis."},{q:"Garantieren QC-Fotos Qualität oder Echtheit?",a:"Nein. Sie zeigen sichtbare Details des Lagerartikels, beweisen aber weder Material noch Haltbarkeit oder Echtheit."},{q:"Was sollte ein Erstkäufer vor dem Versand tun?",a:"Originalangebot speichern, Variante bestätigen, Lagerfotos prüfen, Rückgaben rechtzeitig klären und Routen mit finalen Paketdaten vergleichen."}
  ]},
  es:{label:"FAQ",eyebrow:"PREGUNTAS FRECUENTES",title:"Respuestas claras antes de comprar.",body:"Diez respuestas prácticas basadas en el proceso y las políticas públicas actuales de USFans.",cardTitle:"Preguntas que conviene resolver antes de pagar.",cardBody:"Devoluciones, fotos de almacén, entrega del vendedor, envío internacional y función del agente.",open:"Abrir todas las respuestas",questions:[
    {q:"¿Qué es USFans?",a:"USFans se presenta como agente de compras para Taobao, 1688 y Weidian. Compra al vendedor, recibe el artículo en almacén, aporta fotos de inspección y gestiona el paquete internacional elegido."},{q:"¿USFans vende directamente los productos?",a:"Normalmente el artículo procede de un vendedor externo. El tiempo del vendedor y la calidad del producto deben separarse del servicio de almacén y reenvío."},{q:"¿Qué ocurre cuando envía el vendedor?",a:"El artículo llega al almacén de USFans, se revisa y fotografía. Después puede conservarse, devolverse o enviarse internacionalmente."},{q:"¿Cuántas fotos QC se incluyen?",a:"Las páginas de producto anuncian actualmente de tres a siete fotos HD gratuitas. Conviene comparar cada ángulo con el anuncio."},{q:"¿Puedo devolver desde el almacén?",a:"USFans indica actualmente cinco días desde la llegada para solicitar devolución. También pueden aplicar las condiciones del vendedor."},{q:"¿Por qué tarda la entrega al almacén?",a:"USFans explica que el transporte hasta el almacén depende del vendedor externo; una estimación no es una fecha garantizada."},{q:"¿El pago del producto es el coste final?",a:"No. La compra y el envío internacional son etapas separadas. Servicios, embalaje, ruta y peso facturable influyen en el segundo pago."},{q:"¿Cómo comparo rutas?",a:"Compara peso y medidas finales, destino, restricciones, plazo y seguimiento, no solo el precio más bajo."},{q:"¿Las fotos QC garantizan calidad o autenticidad?",a:"No. Ayudan a revisar detalles visibles, pero no demuestran materiales, duración ni autenticidad."},{q:"¿Qué debe hacer un comprador nuevo?",a:"Guardar el anuncio, confirmar variante, revisar fotos, resolver devoluciones y comparar rutas con los datos finales del paquete."}
  ]},
  fr:{label:"FAQ",eyebrow:"QUESTIONS FRÉQUENTES",title:"Des réponses claires avant la commande.",body:"Dix réponses pratiques fondées sur le parcours et les règles publiques actuelles de USFans.",cardTitle:"Les questions à résoudre avant le paiement.",cardBody:"Retours, photos d’entrepôt, livraison vendeur, transport international et rôle de l’agent.",open:"Voir toutes les réponses",questions:[
    {q:"Qu’est-ce que USFans ?",a:"USFans se présente comme un agent d’achat pour Taobao, 1688 et Weidian. Il achète auprès du vendeur, reçoit l’article, fournit des photos et organise ensuite l’expédition internationale choisie."},{q:"USFans vend-il directement les produits ?",a:"L’article provient généralement d’un vendeur tiers. Le délai du vendeur et la qualité du produit sont distincts du service d’entrepôt et de transfert."},{q:"Que se passe-t-il après l’envoi du vendeur ?",a:"L’article arrive à l’entrepôt USFans, est contrôlé et photographié. Il peut ensuite être conservé, retourné ou soumis à l’expédition."},{q:"Combien de photos QC sont fournies ?",a:"Les pages publiques annoncent actuellement trois à sept photos HD gratuites. Comparez chaque angle avec l’annonce."},{q:"Peut-on retourner depuis l’entrepôt ?",a:"USFans indique actuellement cinq jours après l’arrivée pour demander un retour, sous réserve des conditions du vendeur."},{q:"Pourquoi l’arrivée à l’entrepôt peut-elle être lente ?",a:"USFans explique que ce délai dépend du vendeur tiers. Une estimation n’est donc pas une garantie."},{q:"Le prix du produit est-il le coût final ?",a:"Non. L’achat et le transport international sont deux étapes de coût. Services, emballage, route et poids facturable comptent."},{q:"Comment comparer les routes ?",a:"Comparez poids, dimensions, destination, restrictions, délai et suivi, pas seulement le prix affiché."},{q:"Les photos QC garantissent-elles la qualité ?",a:"Non. Elles montrent des détails visibles, sans prouver matière, durabilité ou authenticité."},{q:"Que faire avant l’envoi du colis ?",a:"Sauvegardez l’annonce, confirmez la variante, examinez les photos, traitez les retours et comparez les routes avec les données finales."}
  ]},
  it:{label:"FAQ",eyebrow:"DOMANDE FREQUENTI",title:"Risposte chiare prima dell’ordine.",body:"Dieci risposte pratiche basate sul flusso e sulle politiche pubbliche attuali di USFans.",cardTitle:"Domande da chiarire prima del pagamento.",cardBody:"Resi, foto di magazzino, consegna del venditore, spedizione e ruolo dell’agente.",open:"Apri tutte le risposte",questions:[
    {q:"Cos’è USFans?",a:"USFans si presenta come agente d’acquisto per Taobao, 1688 e Weidian. Compra dal venditore, riceve l’articolo, fornisce foto e gestisce la spedizione internazionale scelta."},{q:"USFans vende direttamente i prodotti?",a:"Di solito il prodotto proviene da un venditore terzo. Tempi e qualità del venditore sono distinti dal servizio di magazzino e inoltro."},{q:"Cosa succede dopo la spedizione del venditore?",a:"L’articolo arriva al magazzino USFans, viene controllato e fotografato. Poi può essere tenuto, restituito o spedito."},{q:"Quante foto QC sono incluse?",a:"Le pagine pubbliche pubblicizzano tre-sette foto HD gratuite. Confronta ogni angolo con l’inserzione."},{q:"Si può restituire dal magazzino?",a:"USFans indica attualmente cinque giorni dall’arrivo per chiedere il reso, soggetto alle condizioni del venditore."},{q:"Perché l’arrivo in magazzino può tardare?",a:"USFans spiega che dipende dal venditore terzo; una stima non è una garanzia."},{q:"Il prezzo del prodotto è il costo finale?",a:"No. Acquisto e spedizione internazionale sono due costi separati. Servizi, imballo, rotta e peso fatturabile incidono."},{q:"Come confronto le rotte?",a:"Confronta peso, dimensioni, destinazione, limiti, tempi e tracciamento, non solo il prezzo."},{q:"Le foto QC garantiscono qualità o autenticità?",a:"No. Mostrano dettagli visibili ma non provano materiali, durata o autenticità."},{q:"Cosa fare prima della spedizione?",a:"Salva l’inserzione, conferma la variante, controlla le foto, gestisci i resi e confronta le rotte con i dati finali."}
  ]},
  pl:{label:"FAQ",eyebrow:"CZĘSTE PYTANIA",title:"Jasne odpowiedzi przed zamówieniem.",body:"Dziesięć praktycznych odpowiedzi opartych na publicznym procesie i zasadach USFans.",cardTitle:"Pytania, na które warto odpowiedzieć przed płatnością.",cardBody:"Zwroty, zdjęcia magazynowe, dostawa sprzedawcy, wysyłka i rola agenta.",open:"Otwórz wszystkie odpowiedzi",questions:[
    {q:"Czym jest USFans?",a:"USFans opisuje się jako agent zakupowy dla Taobao, 1688 i Weidian. Kupuje od sprzedawcy, przyjmuje produkt, udostępnia zdjęcia i organizuje wybraną wysyłkę międzynarodową."},{q:"Czy USFans sam sprzedaje produkty?",a:"Produkt zwykle pochodzi od zewnętrznego sprzedawcy. Czas i jakość sprzedawcy trzeba oddzielić od usługi magazynowej i spedycyjnej."},{q:"Co dzieje się po wysyłce sprzedawcy?",a:"Produkt trafia do magazynu USFans, jest sprawdzany i fotografowany. Potem można go zatrzymać, zwrócić lub wysłać."},{q:"Ile zdjęć QC otrzymam?",a:"Publiczne strony reklamują obecnie trzy do siedmiu darmowych zdjęć HD. Porównaj każdy kąt z ofertą."},{q:"Czy można zwrócić produkt z magazynu?",a:"USFans podaje obecnie pięć dni od przyjęcia na złożenie wniosku, z uwzględnieniem zasad sprzedawcy."},{q:"Dlaczego dostawa do magazynu trwa długo?",a:"USFans wyjaśnia, że zależy ona od zewnętrznego sprzedawcy; szacunek nie jest gwarancją."},{q:"Czy cena produktu jest kosztem końcowym?",a:"Nie. Zakup i wysyłka zagraniczna to dwa etapy kosztów. Usługi, pakowanie, trasa i waga rozliczeniowa mają znaczenie."},{q:"Jak porównywać trasy?",a:"Porównaj końcową wagę, wymiary, ograniczenia, termin i śledzenie, nie tylko cenę."},{q:"Czy zdjęcia QC gwarantują jakość?",a:"Nie. Pokazują widoczne szczegóły, ale nie dowodzą materiału, trwałości ani autentyczności."},{q:"Co zrobić przed wysyłką?",a:"Zapisz ofertę, potwierdź wariant, sprawdź zdjęcia, rozwiąż zwroty i porównaj trasy na podstawie finalnych danych."}
  ]},
  pt:{label:"FAQ",eyebrow:"PERGUNTAS FREQUENTES",title:"Respostas claras antes do pedido.",body:"Dez respostas práticas baseadas no processo e nas políticas públicas atuais da USFans.",cardTitle:"Perguntas para responder antes de pagar.",cardBody:"Devoluções, fotos, entrega do vendedor, envio internacional e função do agente.",open:"Abrir todas as respostas",questions:[
    {q:"O que é a USFans?",a:"A USFans se apresenta como agente de compras para Taobao, 1688 e Weidian. Compra do vendedor, recebe o item, fornece fotos e organiza o envio internacional escolhido."},{q:"A USFans vende os produtos diretamente?",a:"Normalmente o item vem de um vendedor externo. Prazo e qualidade do vendedor são diferentes do serviço de armazém e encaminhamento."},{q:"O que acontece após o vendedor enviar?",a:"O item chega ao armazém USFans, é verificado e fotografado. Depois pode ser mantido, devolvido ou enviado internacionalmente."},{q:"Quantas fotos QC são fornecidas?",a:"As páginas públicas anunciam atualmente de três a sete fotos HD gratuitas. Compare todos os ângulos com o anúncio."},{q:"Posso devolver do armazém?",a:"A USFans informa atualmente cinco dias após a chegada para solicitar devolução, sujeita às condições do vendedor."},{q:"Por que a chegada ao armazém demora?",a:"A USFans explica que o prazo depende do vendedor externo; uma estimativa não é garantia."},{q:"O preço do produto é o custo final?",a:"Não. Compra e frete internacional são etapas separadas. Serviços, embalagem, rota e peso faturável afetam o segundo custo."},{q:"Como comparar rotas?",a:"Compare peso, dimensões, destino, restrições, prazo e rastreamento, não apenas o menor preço."},{q:"Fotos QC garantem qualidade?",a:"Não. Elas mostram detalhes visíveis, mas não provam materiais, durabilidade ou autenticidade."},{q:"O que fazer antes do envio?",a:"Salve o anúncio, confirme a variante, revise as fotos, resolva devoluções e compare rotas com os dados finais."}
  ]},
  "zh-cn":{label:"常见问题",eyebrow:"常见问题",title:"下单前，把关键问题弄清楚。",body:"以下十个回答依据 USFans 当前公开页面所描述的流程与政策整理。",cardTitle:"付款前值得先弄清的问题。",cardBody:"退货、仓库照片、卖家发货、国际运输，以及购物代理究竟负责什么。",open:"查看全部回答",questions:[
    {q:"USFans 是什么？",a:"USFans 将自己描述为面向淘宝、1688 和微店等中国平台的购物代理。代理向卖家采购、在仓库收货并提供检查照片，之后再按客户选择处理国际包裹。"},{q:"商品是 USFans 自己销售的吗？",a:"多数情况下，实际商品来自第三方平台卖家。卖家发货速度和商品质量，与代理的仓储及转运服务需要分开判断。"},{q:"卖家发货后会发生什么？",a:"USFans 的公开流程说明，商品会进入其仓库，由工作人员检查并拍照。客户查看照片后，可以保留、申请退货，或稍后提交国际运输。"},{q:"会提供多少张质检照片？",a:"USFans 商品页目前写明提供 3–7 张免费高清检查照片。不同商品的拍摄角度可能不同，仍应逐张与卖家商品页对比。"},{q:"商品到仓后能退货吗？",a:"USFans 商品页目前写明，到仓后如不满意可在 5 天内申请退货。是否最终接受仍可能受卖家及商品售后条件影响，所以应及时检查。"},{q:"为什么卖家送到仓库会变慢？",a:"USFans 曾公开说明，送达仓库的时间由第三方卖家控制。因此预计到仓时间不是保证的采购或发货期限。"},{q:"支付商品价格就是全部费用吗？",a:"不是。购物代理订单通常至少分为商品采购和国际包裹两个费用阶段。增值服务、包装、线路规则和计费重量会影响第二阶段。"},{q:"国际运输线路应该怎么比较？",a:"应同时看最终重量和尺寸、目的地、限制、预计时效与追踪能力，而不是只看最低的表面报价。"},{q:"质检照片能保证质量或真伪吗？",a:"不能。照片只能帮助检查可见的颜色、尺码、做工或破损，无法证明材料、长期耐用性或真伪。"},{q:"第一次使用时，提交包裹前要做什么？",a:"保存原商品页、确认规格、及时检查全部仓库照片、在页面显示的期限内处理退货、移除不需要的商品，再用最终包裹数据比较线路。"}
  ]},
};


export const articleData = allArticles as Record<Lang,Record<ArticleSlug,Article>>;
export const shippingData = allShipping as Record<Lang,Article>;
