import type { Lang } from "./site-shell";
import type { Article } from "./localized-content";

const localized = (copy: Omit<Article, "sections"> & { sections: Array<[string, string]> }): Article => ({
  ...copy,
  sections: copy.sections.map(([heading, body]) => ({ heading, paragraphs: body.split("\n\n") })),
});

export const shoesListingArticle: Record<Lang, Article> = {
  en: localized({
    kicker: "SHOES LISTING AUDIT · 2026",
    title: "USFans Shoes Listing Checklist: Verify Size, Variant and Seller Evidence",
    description: "A product-discovery checklist for deciding whether a shoe listing is clear enough to order—before warehouse QC or parcel planning begins.",
    updated: "Published and checked August 14, 2026",
    readingTime: "8 minute read",
    contentsLabel: "Listing audit",
    factTitle: "What this guide verifies",
    factNote: "This guide audits the information visible before ordering. It does not certify authenticity, predict warehouse condition, or recommend a specific product.",
    imageCaption: "Two shoe cards from the existing index illustrate why model, option and size must be checked on the current detail page rather than inferred from a thumbnail.",
    sections: [
      ["Confirm that the card and destination describe the same shoe", `A shoes index is useful only when its card leads to a detail page for the same product. Open the destination and compare the product family, silhouette, colour treatment and seller-page title with the card you clicked. Do not assume a similar hero image is enough: sellers can reuse photographs across different batches, materials, colourways or option structures.

Check the final URL after any redirect. A product link may still load while landing on a generic category, an unavailable-item notice, a search page or a replacement listing. Record the seller or shop name and the visible listing identifier when available. If the destination no longer identifies the shoe, treat the row as stale rather than trying to reconstruct the intended product from the image.

This first check prevents the most basic failure: carefully reviewing size and price on a page that does not represent the indexed item. A valid click should preserve enough identity to compare the card, option selector and current offer without guesswork.`],
      ["Read the option selector before reading the headline price", `Marketplace shoe pages often combine several colours, versions, accessories or payment types under one listing. The headline price may reflect the least expensive selectable entry rather than the shoe in the first photograph. Open every relevant selector and match the option text with its image and price.

Look specifically for entries that represent a deposit, balance payment, replacement part, accessory or after-sales add-on. Do not treat those as a discounted full pair. Confirm that the quantity is one pair and that both shoes are included; a seller image showing a pair is not a contractual quantity field.

Save the selected option text exactly as displayed. If automatic translation is unclear, keep a screenshot beside a short note describing the chosen image. A clean record lets the purchasing agent execute a precise choice and gives you something concrete to compare when the warehouse record appears.`],
      ["Use measurements, not a familiar size label", `A printed EU, US, UK or centimetre size is only a label until the seller explains how it maps to the product. Look for a size chart tied to the current listing and identify whether it describes foot length, insole length, outsole length or a general recommended size. Those measurements are not interchangeable.

Measure a shoe that already fits, using the same measurement type stated by the seller. If the chart gives insole length, compare insole with insole. If it gives foot length, measure the foot as instructed. Leave room for sock thickness and the intended fit, but do not invent a universal conversion between brands or models.

Pause when the listing has only a size label and fit is critical. A warehouse size-tag photograph can later confirm the label received, but it cannot prove the shoe will fit. The strongest pre-order evidence combines the seller chart, a comparable shoe and a clearly selected variant.`],
      ["Audit the images for one consistent product", `Move beyond the first image. Compare lateral and medial sides, heel, toe, tongue, outsole, insole, fastening and packaging where shown. Check whether logos, panel lines, sole shape and material texture remain consistent across the gallery. Sudden changes may mean the listing mixes colourways, batches or reference photographs.

Treat lifestyle images as context, not specification. Lighting can change colour and wide-angle lenses can distort shape. Look for neutral product views and detail photographs connected to the selectable option. If only one angle exists, record that limitation instead of filling it with assumptions.

The goal is not to perform warehouse QC before the item exists. It is to decide whether the seller page defines a product clearly enough to order. Visible consistency is evidence; silence about material, internal construction or long-term wear is still silence.`],
      ["Separate seller claims from verifiable fields", `Place each important statement into one of three columns: selected field, seller claim or unknown. Size option, quantity and displayed price are selected fields. Statements about leather, cushioning, version or quality are seller claims unless supported by a useful specification. Authenticity, durability and exact comfort usually remain unknown before independent evidence.

Do not convert promotional wording into an editorial conclusion. A phrase such as “top version” does not identify a batch or measurable construction standard. If version matters, look for a seller-defined code, material list or comparison that distinguishes it from other options on the same page.

This classification makes the later decision clearer. You can order with some unknowns when their risk is acceptable, but you should not describe an unknown as verified merely because it appears in a translated title.`],
      ["Check seller and transaction signals", `Review the seller information visible on the marketplace page: shop identity, how long the listing appears to have existed, available sales or feedback context, dispatch information and after-sales wording. Not every marketplace exposes the same fields, and no single score proves the next pair will be correct.

Prefer a coherent pattern over one impressive number. A seller page with stable product details, clear variants, usable size information and defined after-sales terms gives you more to verify than a page with only promotional photographs. If recent feedback includes useful size or option references, treat it as attributed user reporting, not a guarantee.

Record domestic delivery and any quantity rule before checkout. Seller-to-warehouse cost and dispatch are part of the listing decision, even though international shipping is a later stage.`],
      ["Estimate the shoe-specific parcel trade-off", `Shoes are a product-discovery decision with a packaging consequence. A retail box can preserve shape and presentation but adds weight and volume. Removing it may reduce volume but can increase crushing risk if replacement protection is weak. Do not promise savings before the packed dimensions and route rules are known.

Before ordering, compare two plausible scenarios: pair with box and pair without retail box but with protective packing. If the shoe is rigid, delicate or intended as a gift, protection may outweigh the cheapest theoretical parcel. If the box has no value and the shoe tolerates compact packing, the volume trade-off may point the other way.

This is not a shipping-cost article; it is a go/no-go check. If the purchase only looks sensible under an unrealistic zero-volume packaging assumption, the listing is a poor shortlist candidate regardless of its product price.`],
      ["Score the listing and decide", `Give one point for each resolved field: correct destination, seller identity, full-pair option, colour, model or version, quantity, useful size evidence, coherent images, domestic delivery and acceptable packaging scenario. Mark any field that depends only on a claim.

An unresolved cosmetic detail may be acceptable. An unresolved identity, quantity, payment type or size field is more serious because warehouse photos may arrive after you have already paid the seller. Use a stop rule: do not order when one missing field could turn the purchase into a different product, wrong size or partial payment.

Save the final audit with the date, link, option screenshot and decision. Recheck the live page immediately before payment. A good USFans shoes listing is not the one with the boldest thumbnail; it is the one whose identity, option, size evidence and risks remain understandable after every field is opened.`],
    ],
  }),
  de: localized({ kicker:"SCHUH-ANGEBOTSPRÜFUNG · 2026", title:"USFans Schuhe: Listing, Größe und Variante prüfen", description:"Prüfliste für Identität, Option, Größenbeleg, Bilder, Verkäuferangaben und Verpackungsrisiko vor der Bestellung.", updated:"Veröffentlicht und geprüft am 14. August 2026", readingTime:"6 Minuten", contentsLabel:"Listing-Prüfung", factTitle:"Grenze dieser Prüfung", factNote:"Geprüft werden vorbestellbare Angebotsdaten, nicht Echtheit, Lagerzustand oder eine Produktempfehlung.", imageCaption:"Zwei vorhandene Schuhkarten zeigen, warum Modell, Option und Größe auf der aktuellen Detailseite geprüft werden müssen.", sections:[["Karte und Ziel abgleichen","Produktfamilie, Form, Farbe, Titel und endgültige URL vergleichen. Eine Weiterleitung auf Kategorie, Suche oder Ersatzlisting macht den Eintrag veraltet. Verkäufer und sichtbare Listing-ID sichern.\n\nEin ähnliches Bild reicht nicht, da Fotos für Chargen oder Optionen wiederverwendet werden können."],["Option vor Preis lesen","Alle Farb-, Versions-, Zubehör- und Zahlungsoptionen öffnen. Kopfpreis kann Zubehör, Anzahlung oder kleinste Auswahl betreffen. Volles Paar und Menge bestätigen; Optionstext und Bild speichern."],["Maße statt Etikett nutzen","Prüfen, ob die Tabelle Fuß-, Einlegesohlen- oder Außensohlenlänge meint. Nur gleiche Messarten vergleichen und keinen allgemeinen Marken-Umrechner erfinden. Ohne passende Maßangabe bei kritischer Passform pausieren."],["Bilder auf Konsistenz prüfen","Außen- und Innenseite, Ferse, Zehe, Zunge, Sohle und Verpackung vergleichen. Wechselnde Paneele oder Materialien können gemischte Referenzen zeigen. Lifestyle-Bilder sind Kontext, keine Spezifikation."],["Felder, Behauptungen und Unbekanntes trennen","Größe, Menge und Preis sind Auswahlfelder; Material, Version und Qualität oft Verkäuferbehauptungen; Echtheit und Haltbarkeit bleiben meist unbekannt. Werbesprache nicht als verifiziert darstellen."],["Verkäufersignale prüfen","Shop-Identität, Angebotskonsistenz, Größenangaben, Versand und Nachverkaufsbedingungen gemeinsam betrachten. Ein einzelner Score beweist nichts. Inlandsversand und Mengenregel vor Checkout notieren."],["Verpackungsfolge abschätzen","Schuhkarton schützt, erhöht aber Volumen; Entfernung kann sparen und Druckrisiko erhöhen. Szenario mit Karton und ohne Karton mit Schutz vergleichen. Nur realistische Packannahmen verwenden."],["Bewerten und entscheiden","Punkte für Link, Verkäufer, Paaroption, Farbe, Version, Menge, Größenbeleg, Bilder, Inlandsversand und Verpackung vergeben. Bei ungeklärter Identität, Teilzahlung, Menge oder Größe stoppen und unmittelbar vor Zahlung neu prüfen."]]}),
  es: localized({ kicker:"AUDITORÍA DE CALZADO · 2026", title:"USFans zapatos: comprobar anuncio, talla y variante", description:"Lista para validar identidad, opción, medidas, imágenes, vendedor y riesgo de embalaje antes de comprar.", updated:"Publicado y revisado el 14 de agosto de 2026", readingTime:"6 minutos", contentsLabel:"Auditoría", factTitle:"Límite de la guía", factNote:"Revisa datos visibles antes de comprar; no certifica autenticidad, estado futuro ni recomienda un producto.", imageCaption:"Dos tarjetas de calzado muestran por qué modelo, opción y talla deben comprobarse en la ficha actual.", sections:[["Compara tarjeta y destino","Contrasta familia, silueta, color, título y URL final. Si redirige a categoría, búsqueda o sustituto, marca el enlace como obsoleto. Guarda vendedor e identificador.\n\nUna imagen parecida no demuestra el mismo producto."],["Lee la opción antes del precio","Abre colores, versiones, accesorios y tipos de pago. El precio principal puede ser accesorio, depósito u opción barata. Confirma par completo y cantidad; guarda texto e imagen de la opción."],["Usa medidas, no una etiqueta familiar","Distingue pie, plantilla y suela exterior. Compara el mismo tipo de medida con un zapato que ajuste y evita conversiones universales. Pausa si falta evidencia y el ajuste es crítico."],["Revisa coherencia de imágenes","Compara laterales, talón, puntera, lengüeta, suela, plantilla y caja. Cambios de panel o material pueden mezclar referencias. Fotos de estilo no son especificaciones."],["Separa campos, afirmaciones y desconocidos","Talla, cantidad y precio son campos; material, versión y calidad suelen ser afirmaciones; autenticidad y duración quedan desconocidas. No conviertas promoción en verificación."],["Comprueba señales del vendedor","Valora identidad de tienda, claridad, talla, despacho y posventa en conjunto. Un número no garantiza el siguiente par. Anota envío nacional y reglas de cantidad."],["Estima la consecuencia de embalaje","La caja protege pero añade volumen; retirarla puede ahorrar y aumentar aplastamiento. Compara escenario con caja y sin caja con protección. No uses supuestos imposibles."],["Puntúa y decide","Puntúa URL, vendedor, par, color, versión, cantidad, talla, imágenes, entrega nacional y embalaje. Detén ante identidad, pago parcial, cantidad o talla ambiguas y vuelve a revisar antes de pagar."]]}),
  fr: localized({ kicker:"AUDIT CHAUSSURES · 2026", title:"Chaussures USFans : vérifier annonce, pointure et option", description:"Contrôle de l’identité, option, mesures, images, vendeur et risque d’emballage avant commande.", updated:"Publié et vérifié le 14 août 2026", readingTime:"6 minutes", contentsLabel:"Audit", factTitle:"Limite du guide", factNote:"Ce guide vérifie les données visibles avant achat, sans certifier authenticité, état futur ni recommandation.", imageCaption:"Deux cartes de chaussures illustrent pourquoi modèle, option et pointure se vérifient sur la fiche actuelle.", sections:[["Comparer carte et destination","Comparer famille, silhouette, couleur, titre et URL finale. Une redirection vers catégorie, recherche ou remplacement rend la ligne obsolète. Conserver vendeur et identifiant.\n\nUne image semblable ne suffit pas."],["Lire l’option avant le prix","Ouvrir couleurs, versions, accessoires et types de paiement. Le prix principal peut être accessoire, acompte ou option minimale. Confirmer paire complète et quantité; sauvegarder texte et image."],["Utiliser des mesures, pas l’étiquette","Distinguer longueur du pied, semelle intérieure et extérieure. Comparer la même mesure avec une chaussure adaptée et éviter toute conversion universelle. Suspendre si l’ajustement est critique et les données absentes."],["Vérifier la cohérence des images","Comparer côtés, talon, avant, languette, semelle et boîte. Des changements de panneaux ou matières peuvent révéler des références mixtes. Les photos lifestyle ne sont pas une spécification."],["Séparer champs, affirmations et inconnues","Pointure, quantité et prix sont des champs; matière, version et qualité sont souvent des affirmations; authenticité et durabilité restent inconnues. Ne pas transformer le marketing en preuve."],["Contrôler les signaux vendeur","Évaluer ensemble identité, stabilité, taille, expédition et après-vente. Un score isolé ne garantit rien. Noter livraison intérieure et quantité."],["Estimer l’emballage","La boîte protège mais augmente le volume; son retrait peut économiser et accroître l’écrasement. Comparer avec boîte et sans boîte mais protégé, avec des hypothèses réalistes."],["Noter et décider","Noter URL, vendeur, paire, couleur, version, quantité, mesure, images, livraison et emballage. Arrêter si identité, paiement partiel, quantité ou taille restent ambiguës, puis revérifier avant paiement."]]}),
  it: localized({ kicker:"AUDIT SCARPE · 2026", title:"Scarpe USFans: verificare inserzione, taglia e variante", description:"Checklist per identità, opzione, misure, immagini, venditore e rischio di imballaggio prima dell’ordine.", updated:"Pubblicato e verificato il 14 agosto 2026", readingTime:"6 minuti", contentsLabel:"Audit", factTitle:"Limite della guida", factNote:"Verifica i dati visibili prima dell’acquisto; non certifica autenticità, condizioni future o raccomandazioni.", imageCaption:"Due schede scarpe mostrano perché modello, opzione e taglia vanno controllati sulla pagina corrente.", sections:[["Confronta scheda e destinazione","Verifica famiglia, forma, colore, titolo e URL finale. Categoria, ricerca o sostituzione indicano link obsoleto. Salva venditore e identificativo.\n\nUn’immagine simile non prova lo stesso prodotto."],["Leggi l’opzione prima del prezzo","Apri colori, versioni, accessori e tipi di pagamento. Il prezzo iniziale può essere accessorio, deposito o opzione minima. Conferma coppia e quantità; salva testo e immagine."],["Usa misure, non etichette","Distingui piede, soletta e suola esterna. Confronta lo stesso tipo di misura con una scarpa adatta; evita conversioni universali. Sospendi se mancano dati critici."],["Controlla coerenza delle immagini","Confronta lati, tallone, punta, linguetta, suola, soletta e scatola. Cambi di pannelli o materiali possono mescolare riferimenti. Le foto lifestyle non sono specifiche."],["Separa campi, affermazioni e ignoti","Taglia, quantità e prezzo sono campi; materiale, versione e qualità spesso affermazioni; autenticità e durata restano ignote. Non trasformare marketing in prova."],["Controlla i segnali del venditore","Valuta identità, chiarezza, taglie, spedizione e post-vendita insieme. Un punteggio non garantisce il prossimo paio. Registra consegna interna e quantità."],["Stima l’imballaggio","La scatola protegge ma aggiunge volume; rimuoverla può risparmiare e aumentare schiacciamento. Confronta con scatola e senza ma protetto usando ipotesi credibili."],["Punteggia e decidi","Punteggia URL, venditore, coppia, colore, versione, quantità, misura, immagini, consegna e imballaggio. Ferma identità, pagamento parziale, quantità o taglia ambigue e ricontrolla prima di pagare."]]}),
  pl: localized({ kicker:"AUDYT OFERTY OBUWIA · 2026", title:"Buty USFans: jak sprawdzić ofertę, rozmiar i wariant", description:"Lista kontroli tożsamości, opcji, wymiarów, zdjęć, sprzedawcy i ryzyka opakowania przed zamówieniem.", updated:"Opublikowano i sprawdzono 14 sierpnia 2026", readingTime:"6 minut", contentsLabel:"Audyt oferty", factTitle:"Zakres poradnika", factNote:"Sprawdza dane widoczne przed zakupem; nie potwierdza autentyczności, stanu po dostawie ani nie rekomenduje produktu.", imageCaption:"Dwie karty obuwia pokazują, dlaczego model, opcję i rozmiar trzeba sprawdzić na aktualnej stronie.", sections:[["Porównaj kartę z miejscem docelowym","Zestaw rodzinę produktu, kształt, kolor, tytuł i końcowy URL. Kategoria, wyszukiwanie lub oferta zastępcza oznaczają nieaktualny link. Zapisz sprzedawcę i identyfikator.\n\nPodobne zdjęcie nie dowodzi zgodności produktu."],["Przeczytaj opcję przed ceną","Otwórz kolory, wersje, dodatki i typy płatności. Cena nagłówkowa może dotyczyć akcesorium, zaliczki lub najmniejszej opcji. Potwierdź pełną parę i ilość; zapisz tekst i obraz wariantu."],["Użyj wymiarów zamiast etykiety","Rozróżnij długość stopy, wkładki i podeszwy. Porównuj ten sam typ pomiaru z pasującym obuwiem i unikaj uniwersalnych przeliczników. Przy braku ważnych danych wstrzymaj zakup."],["Sprawdź spójność zdjęć","Porównaj boki, piętę, nosek, język, podeszwę, wkładkę i pudełko. Zmiany paneli lub materiałów mogą oznaczać mieszane referencje. Zdjęcia stylizowane nie są specyfikacją."],["Oddziel pola, twierdzenia i niewiadome","Rozmiar, ilość i cena to pola wyboru; materiał, wersja i jakość często są twierdzeniem sprzedawcy; autentyczność i trwałość pozostają nieznane. Nie nazywaj reklamy weryfikacją."],["Sprawdź sygnały sprzedawcy","Oceń łącznie tożsamość sklepu, jasność opcji, rozmiary, wysyłkę i posprzedaż. Jeden wynik niczego nie gwarantuje. Zapisz dostawę krajową i zasady ilości."],["Oszacuj skutek opakowania","Pudełko chroni, ale zwiększa objętość; usunięcie może oszczędzić i zwiększyć zgniatanie. Porównaj wariant z pudełkiem i bez niego, lecz z ochroną. Używaj realnych założeń."],["Oceń i zdecyduj","Przyznaj punkty za URL, sprzedawcę, pełną parę, kolor, wersję, ilość, wymiar, zdjęcia, dostawę i opakowanie. Zatrzymaj zakup przy niejasnej tożsamości, częściowej płatności, ilości lub rozmiarze; sprawdź ponownie przed płatnością."]]}),
  pt: localized({ kicker:"AUDITORIA DE CALÇADO · 2026", title:"Calçados USFans: verificar anúncio, tamanho e variante", description:"Checklist de identidade, opção, medidas, imagens, vendedor e risco de embalagem antes do pedido.", updated:"Publicado e verificado em 14 de agosto de 2026", readingTime:"6 minutos", contentsLabel:"Auditoria", factTitle:"Limite do guia", factNote:"Verifica dados visíveis antes da compra; não certifica autenticidade, estado futuro ou recomendação.", imageCaption:"Dois cartões de calçados mostram por que modelo, opção e tamanho devem ser conferidos na página atual.", sections:[["Compare cartão e destino","Confira família, formato, cor, título e URL final. Categoria, busca ou substituto indicam link desatualizado. Salve vendedor e identificador.\n\nImagem parecida não prova o mesmo produto."],["Leia a opção antes do preço","Abra cores, versões, acessórios e tipos de pagamento. O preço principal pode ser acessório, depósito ou opção menor. Confirme par completo e quantidade; salve texto e imagem."],["Use medidas, não etiqueta","Diferencie pé, palmilha e sola externa. Compare o mesmo tipo de medida com calçado adequado e evite conversões universais. Pare se faltar dado crítico."],["Revise a coerência das imagens","Compare lados, calcanhar, bico, língua, sola, palmilha e caixa. Mudanças de painéis ou materiais podem misturar referências. Fotos de estilo não são especificação."],["Separe campos, alegações e desconhecidos","Tamanho, quantidade e preço são campos; material, versão e qualidade geralmente alegações; autenticidade e duração permanecem desconhecidas. Não trate marketing como prova."],["Verifique sinais do vendedor","Avalie identidade, clareza, tamanho, despacho e pós-venda em conjunto. Um número não garante o próximo par. Registre entrega interna e quantidade."],["Estime a embalagem","Caixa protege mas aumenta volume; retirar pode economizar e aumentar esmagamento. Compare com caixa e sem caixa com proteção, usando cenários realistas."],["Pontue e decida","Pontue URL, vendedor, par, cor, versão, quantidade, medida, imagens, entrega e embalagem. Pare diante de identidade, pagamento parcial, quantidade ou tamanho ambíguos e verifique novamente antes de pagar."]]}),
  "zh-cn": localized({ kicker:"鞋类商品页核验 · 2026", title:"USFans 鞋类商品页核验：尺码、规格与卖家信息", description:"下单前逐项核对商品身份、规格、尺码依据、图片一致性、卖家信息和包装风险。", updated:"发布并核查于 2026 年 8 月 14 日", readingTime:"约 6 分钟", contentsLabel:"商品页核验", factTitle:"本指南的边界", factNote:"这里只核验下单前可见字段，不证明真伪、未来到仓状态，也不推荐具体商品。", imageCaption:"选品库中的两张鞋类卡片说明：不能从缩略图推断型号、规格和尺码，必须回到当前详情页核对。", sections:[["核对卡片与落地页是否为同一双鞋","对比产品系列、鞋型、配色、标题和跳转后的最终网址。如果落到分类、搜索或替代商品页，应标记为失效链接。保存卖家和可见商品编号。\n\n相似主图并不能证明商品相同。"],["先看规格选项，再看最低价格","展开颜色、版本、配件和付款类型。标题价格可能对应配件、定金或最低选项。确认是一整双且数量正确，并保存规格文字与图片。"],["用测量依据，不只看熟悉尺码","区分脚长、鞋垫长和外底长，只用同一种测量方式与合脚鞋比较，不套用通用换算。合脚很重要但详情页没有依据时，应暂停下单。"],["检查整组图片是否一致","对比内外侧、后跟、鞋头、鞋舌、鞋底、鞋垫和鞋盒。拼接或材质突然变化可能代表不同批次或参考图。穿搭图不能替代规格说明。"],["区分字段、卖家说法与未知项","尺码、数量和价格是选择字段；材质、版本和质量往往只是卖家说法；真伪和耐用性通常仍未知。不要把宣传词写成已核验结论。"],["检查卖家与交易信号","综合查看店铺身份、规格清晰度、尺码资料、发货和售后说明。单一分数不能保证下一双鞋。付款前记录国内运费和数量规则。"],["预估鞋盒取舍","鞋盒能保护鞋型但增加体积；去盒可能省空间，也可能增加挤压。比较保留鞋盒与去盒后增加保护两种合理场景，不使用不现实的零包装假设。"],["打分并决定","分别核对链接、卖家、整双规格、配色、版本、数量、尺码证据、图片、国内运费和包装。商品身份、部分付款、数量或尺码有一项关键不清楚，就暂停并在付款前重新检查。"]]})
};
