"use client";

import { useEffect, useMemo, useState } from "react";
import { articleData, articleSlugs, faqText, type ArticleSlug } from "./localized-content";

export type PageName = "home" | "categories" | "finds" | "articles" | "article" | "faq" | "qc" | "shipping";
export type Lang = "en" | "de" | "es" | "fr" | "it" | "pl" | "pt" | "zh-cn";

const languages: Array<{ code: Lang; label: string }> = [
  { code: "en", label: "English" }, { code: "de", label: "Deutsch" },
  { code: "es", label: "Español" }, { code: "fr", label: "Français" },
  { code: "it", label: "Italiano" }, { code: "pl", label: "Polski" },
  { code: "pt", label: "Português" }, { code: "zh-cn", label: "简体中文" },
];

const en = {
  home: "Home", categories: "Product categories", finds: "Product finds", articles: "SEO articles", qc: "QC guide", shipping: "Shipping",
  open: "Open full collection", atlas: "USFans product discovery atlas", titleA: "Don’t scroll.", titleB: "Explore.", intro: "Choose a trail, see the exact product image, and continue to the matching product when you are ready.",
  search: "Search a product, category or paste a link", searchBtn: "Search", shoes: "Shoes", hoodies: "Hoodies", bags: "Bags", jerseys: "Jerseys", trail: "Choose a trail", start: "Start trail", checkpoints: "Fit + fabric", hardware: "Hardware + shape", print: "Print + sizing",
  field: "FIELD CARDS / 01", visual: "Start with a real product.", every: "See every category", catEyebrow: "CATEGORY TRAILS / 02", catTitle: "Browse the collection by direction.", catCta: "Open category", artEyebrow: "FIELD NOTES / 03", artTitle: "Guides that help before checkout.", read: "Read guide",
  route: "ROUTE NOTES / 04", routeTitle: "Know where you are before you move on.", routeBody: "Confirm the seller listing, review warehouse photos, then submit only the items you want for international shipping.", beginner: "Open the QC guide", productTrails: "PRODUCT TRAILS", qcWaypoints: "QC WAYPOINTS", shippingNotes: "SHIPPING NOTES", from: "From main collection", view: "View product",
  categoriesPage: "Four clear ways into the collection.", categoriesBody: "Each card goes directly to the matching category on the main collection.", findsPage: "The same product, from image to click.", findsBody: "Every image and link below matches the product page on the main collection.", articlesPage: "Practical notes for smarter orders.", articlesBody: "Short, useful guides covering product links, warehouse photos and parcel planning.", qcPage: "Check the visible details before shipping.", qcBody: "Use warehouse photos to compare colour, size labels, construction and obvious defects with the seller listing.", shippingPage: "Plan the parcel, not only the product.", shippingBody: "Consolidate carefully, compare available routes and review the final parcel weight before submission.",
  article1: "How to read a USFans product listing", article1d: "A quick checklist for links, variants and seller information.", article2: "What to check in warehouse QC photos", article2d: "Visible details that deserve a second look before parcel submission.", article3: "How to plan international parcel shipping", article3d: "Weight, consolidation and route choices explained in plain language.",
  step1: "Confirm listing", step1d: "Match the title, selected variant and seller link.", step2: "Review QC", step2d: "Compare visible details with the original listing.", step3: "Consolidate", step3d: "Keep only the items you want in the parcel.", step4: "Choose route", step4d: "Compare weight, delivery estimate and restrictions.", order: "ORDER", warehouse: "WAREHOUSE", parcel: "PARCEL",
  disclaimer: "Independent product-discovery and buying guide. Product links continue to the main collection.", continue: "Continue to the collection",
};
type Copy = { [K in keyof typeof en]: string };
const mk = (value: Copy) => value;

const copies: Record<Lang, Copy> = {
  en,
  de: mk({ home:"Startseite",categories:"Produktkategorien",finds:"Produktfunde",articles:"SEO-Artikel",qc:"QC-Leitfaden",shipping:"Versand",open:"Gesamte Kollektion öffnen",atlas:"USFans Produkt-Entdeckungsatlas",titleA:"Nicht scrollen.",titleB:"Entdecken.",intro:"Wähle eine Route, sieh das genaue Produktbild und öffne das passende Produkt.",search:"Produkt, Kategorie oder Link suchen",searchBtn:"Suchen",shoes:"Schuhe",hoodies:"Hoodies",bags:"Taschen",jerseys:"Trikots",trail:"Route wählen",start:"Route starten",checkpoints:"Passform + Stoff",hardware:"Beschläge + Form",print:"Druck + Größe",field:"PRODUKTKARTEN / 01",visual:"Mit einem echten Produkt starten.",every:"Alle Kategorien",catEyebrow:"KATEGORIEN / 02",catTitle:"Kollektion nach Richtung entdecken.",catCta:"Kategorie öffnen",artEyebrow:"LEITFÄDEN / 03",artTitle:"Hilfreiche Hinweise vor dem Kauf.",read:"Leitfaden lesen",route:"ROUTENHINWEISE / 04",routeTitle:"Wisse, wo du bist, bevor du weitergehst.",routeBody:"Angebot prüfen, Lagerfotos ansehen und nur gewünschte Artikel für den Versand einreichen.",beginner:"QC-Leitfaden öffnen",productTrails:"PRODUKTROUTEN",qcWaypoints:"QC-PUNKTE",shippingNotes:"VERSANDHINWEISE",from:"Aus der Hauptkollektion",view:"Produkt ansehen",categoriesPage:"Vier klare Wege in die Kollektion.",categoriesBody:"Jede Karte führt direkt zur passenden Kategorie der Hauptkollektion.",findsPage:"Dasselbe Produkt, vom Bild bis zum Klick.",findsBody:"Jedes Bild und jeder Link entspricht der Produktseite der Hauptkollektion.",articlesPage:"Praktische Hinweise für bessere Bestellungen.",articlesBody:"Kurze Leitfäden zu Links, Lagerfotos und Paketplanung.",qcPage:"Sichtbare Details vor dem Versand prüfen.",qcBody:"Vergleiche Farbe, Größenetiketten, Verarbeitung und sichtbare Mängel mit dem Angebot.",shippingPage:"Plane das Paket, nicht nur das Produkt.",shippingBody:"Sorgfältig bündeln, Routen vergleichen und Endgewicht prüfen.",article1:"USFans-Produktangebote richtig lesen",article1d:"Checkliste für Links, Varianten und Verkäuferinfos.",article2:"Was auf QC-Lagerfotos zu prüfen ist",article2d:"Sichtbare Details vor der Paketeinreichung.",article3:"Internationalen Paketversand planen",article3d:"Gewicht, Bündelung und Routen einfach erklärt.",step1:"Angebot prüfen",step1d:"Titel, Variante und Verkäuferlink abgleichen.",step2:"QC prüfen",step2d:"Sichtbare Details mit dem Angebot vergleichen.",step3:"Bündeln",step3d:"Nur gewünschte Artikel im Paket behalten.",step4:"Route wählen",step4d:"Gewicht, Lieferzeit und Einschränkungen vergleichen.",order:"BESTELLUNG",warehouse:"LAGER",parcel:"PAKET",disclaimer:"Unabhängiger Produkt- und Einkaufsleitfaden. Produktlinks führen zur Hauptkollektion.",continue:"Zur Kollektion" }),
  es: mk({ home:"Inicio",categories:"Categorías",finds:"Productos",articles:"Artículos SEO",qc:"Guía QC",shipping:"Envío",open:"Abrir colección completa",atlas:"Atlas de productos USFans",titleA:"No deslices.",titleB:"Explora.",intro:"Elige una ruta, mira la imagen exacta y abre el producto correspondiente.",search:"Buscar producto, categoría o pegar enlace",searchBtn:"Buscar",shoes:"Zapatillas",hoodies:"Sudaderas",bags:"Bolsos",jerseys:"Camisetas",trail:"Elige una ruta",start:"Iniciar ruta",checkpoints:"Ajuste + tejido",hardware:"Herrajes + forma",print:"Estampado + talla",field:"FICHAS / 01",visual:"Empieza con un producto real.",every:"Ver categorías",catEyebrow:"CATEGORÍAS / 02",catTitle:"Explora la colección por dirección.",catCta:"Abrir categoría",artEyebrow:"GUÍAS / 03",artTitle:"Ayuda útil antes de comprar.",read:"Leer guía",route:"RUTA / 04",routeTitle:"Sabe dónde estás antes de seguir.",routeBody:"Confirma el anuncio, revisa las fotos de almacén y envía solo los artículos deseados.",beginner:"Abrir guía QC",productTrails:"RUTAS DE PRODUCTO",qcWaypoints:"PUNTOS QC",shippingNotes:"NOTAS DE ENVÍO",from:"De la colección principal",view:"Ver producto",categoriesPage:"Cuatro caminos claros a la colección.",categoriesBody:"Cada tarjeta abre la categoría correspondiente de la colección principal.",findsPage:"El mismo producto, de la imagen al clic.",findsBody:"Cada imagen y enlace coincide con la página del producto principal.",articlesPage:"Notas prácticas para mejores pedidos.",articlesBody:"Guías breves sobre enlaces, fotos de almacén y paquetes.",qcPage:"Revisa los detalles visibles antes del envío.",qcBody:"Compara color, etiquetas, confección y defectos con el anuncio.",shippingPage:"Planifica el paquete, no solo el producto.",shippingBody:"Consolida, compara rutas y revisa el peso final.",article1:"Cómo leer un producto de USFans",article1d:"Lista rápida para enlaces, variantes y vendedor.",article2:"Qué revisar en fotos QC",article2d:"Detalles visibles antes de enviar el paquete.",article3:"Cómo planificar el envío internacional",article3d:"Peso, consolidación y rutas en lenguaje claro.",step1:"Confirmar anuncio",step1d:"Comprueba título, variante y vendedor.",step2:"Revisar QC",step2d:"Compara detalles con el anuncio.",step3:"Consolidar",step3d:"Conserva solo los artículos deseados.",step4:"Elegir ruta",step4d:"Compara peso, plazo y restricciones.",order:"PEDIDO",warehouse:"ALMACÉN",parcel:"PAQUETE",disclaimer:"Guía independiente de productos y compras. Los enlaces llevan a la colección principal.",continue:"Ir a la colección" }),
  fr: mk({ home:"Accueil",categories:"Catégories",finds:"Produits",articles:"Articles SEO",qc:"Guide QC",shipping:"Livraison",open:"Ouvrir la collection",atlas:"Atlas de découverte USFans",titleA:"Ne défilez pas.",titleB:"Explorez.",intro:"Choisissez une piste, voyez l’image exacte et ouvrez le produit correspondant.",search:"Rechercher un produit, une catégorie ou coller un lien",searchBtn:"Rechercher",shoes:"Chaussures",hoodies:"Sweats",bags:"Sacs",jerseys:"Maillots",trail:"Choisir une piste",start:"Démarrer",checkpoints:"Coupe + tissu",hardware:"Métal + forme",print:"Impression + taille",field:"FICHES / 01",visual:"Commencez par un vrai produit.",every:"Voir les catégories",catEyebrow:"CATÉGORIES / 02",catTitle:"Explorez la collection par direction.",catCta:"Ouvrir la catégorie",artEyebrow:"GUIDES / 03",artTitle:"Des conseils utiles avant l’achat.",read:"Lire le guide",route:"PARCOURS / 04",routeTitle:"Sachez où vous êtes avant d’avancer.",routeBody:"Vérifiez l’annonce, examinez les photos d’entrepôt puis soumettez seulement les articles voulus.",beginner:"Ouvrir le guide QC",productTrails:"PARCOURS PRODUITS",qcWaypoints:"ÉTAPES QC",shippingNotes:"NOTES LIVRAISON",from:"Collection principale",view:"Voir le produit",categoriesPage:"Quatre accès clairs à la collection.",categoriesBody:"Chaque carte ouvre la catégorie correspondante de la collection principale.",findsPage:"Le même produit, de l’image au clic.",findsBody:"Chaque image et lien correspond à la page produit principale.",articlesPage:"Des notes pratiques pour mieux commander.",articlesBody:"Guides courts sur les liens, photos et colis.",qcPage:"Vérifiez les détails visibles avant l’envoi.",qcBody:"Comparez couleur, étiquettes, fabrication et défauts avec l’annonce.",shippingPage:"Planifiez le colis, pas seulement le produit.",shippingBody:"Regroupez, comparez les routes et vérifiez le poids final.",article1:"Lire une fiche produit USFans",article1d:"Checklist pour liens, variantes et vendeur.",article2:"Contrôler les photos QC",article2d:"Détails visibles avant l’envoi du colis.",article3:"Planifier une livraison internationale",article3d:"Poids, regroupement et routes simplement expliqués.",step1:"Confirmer l’annonce",step1d:"Vérifiez titre, variante et vendeur.",step2:"Examiner QC",step2d:"Comparez les détails avec l’annonce.",step3:"Regrouper",step3d:"Gardez seulement les articles voulus.",step4:"Choisir la route",step4d:"Comparez poids, délai et restrictions.",order:"COMMANDE",warehouse:"ENTREPÔT",parcel:"COLIS",disclaimer:"Guide indépendant de découverte et d’achat. Les liens mènent à la collection principale.",continue:"Voir la collection" }),
  it: mk({ home:"Home",categories:"Categorie",finds:"Prodotti",articles:"Articoli SEO",qc:"Guida QC",shipping:"Spedizione",open:"Apri collezione completa",atlas:"Atlante prodotti USFans",titleA:"Non scorrere.",titleB:"Esplora.",intro:"Scegli un percorso, guarda l’immagine esatta e apri il prodotto corrispondente.",search:"Cerca prodotto, categoria o incolla link",searchBtn:"Cerca",shoes:"Scarpe",hoodies:"Felpe",bags:"Borse",jerseys:"Maglie",trail:"Scegli un percorso",start:"Inizia",checkpoints:"Vestibilità + tessuto",hardware:"Dettagli + forma",print:"Stampa + taglia",field:"SCHEDE / 01",visual:"Inizia da un prodotto reale.",every:"Vedi categorie",catEyebrow:"CATEGORIE / 02",catTitle:"Esplora la collezione per direzione.",catCta:"Apri categoria",artEyebrow:"GUIDE / 03",artTitle:"Consigli utili prima dell’acquisto.",read:"Leggi guida",route:"PERCORSO / 04",routeTitle:"Sai dove sei prima di proseguire.",routeBody:"Conferma l’inserzione, controlla le foto di magazzino e invia solo gli articoli desiderati.",beginner:"Apri guida QC",productTrails:"PERCORSI PRODOTTO",qcWaypoints:"PUNTI QC",shippingNotes:"NOTE SPEDIZIONE",from:"Dalla collezione principale",view:"Vedi prodotto",categoriesPage:"Quattro accessi chiari alla collezione.",categoriesBody:"Ogni scheda apre la categoria corrispondente della collezione principale.",findsPage:"Lo stesso prodotto, dall’immagine al clic.",findsBody:"Ogni immagine e link corrisponde alla pagina prodotto principale.",articlesPage:"Note pratiche per ordini migliori.",articlesBody:"Guide brevi su link, foto e pianificazione pacchi.",qcPage:"Controlla i dettagli visibili prima della spedizione.",qcBody:"Confronta colore, etichette, lavorazione e difetti con l’inserzione.",shippingPage:"Pianifica il pacco, non solo il prodotto.",shippingBody:"Consolida, confronta le rotte e controlla il peso finale.",article1:"Come leggere un prodotto USFans",article1d:"Checklist per link, varianti e venditore.",article2:"Cosa controllare nelle foto QC",article2d:"Dettagli visibili prima dell’invio.",article3:"Pianificare la spedizione internazionale",article3d:"Peso, consolidamento e rotte spiegati semplicemente.",step1:"Conferma inserzione",step1d:"Controlla titolo, variante e venditore.",step2:"Controlla QC",step2d:"Confronta i dettagli con l’inserzione.",step3:"Consolida",step3d:"Tieni solo gli articoli desiderati.",step4:"Scegli rotta",step4d:"Confronta peso, tempi e restrizioni.",order:"ORDINE",warehouse:"MAGAZZINO",parcel:"PACCO",disclaimer:"Guida indipendente a prodotti e acquisti. I link portano alla collezione principale.",continue:"Vai alla collezione" }),
  pl: mk({ home:"Start",categories:"Kategorie",finds:"Produkty",articles:"Artykuły SEO",qc:"Poradnik QC",shipping:"Wysyłka",open:"Otwórz całą kolekcję",atlas:"Atlas produktów USFans",titleA:"Nie przewijaj.",titleB:"Odkrywaj.",intro:"Wybierz trasę, zobacz dokładne zdjęcie i otwórz pasujący produkt.",search:"Szukaj produktu, kategorii lub wklej link",searchBtn:"Szukaj",shoes:"Buty",hoodies:"Bluzy",bags:"Torby",jerseys:"Koszulki",trail:"Wybierz trasę",start:"Rozpocznij",checkpoints:"Krój + materiał",hardware:"Okucia + kształt",print:"Nadruk + rozmiar",field:"KARTY / 01",visual:"Zacznij od prawdziwego produktu.",every:"Zobacz kategorie",catEyebrow:"KATEGORIE / 02",catTitle:"Przeglądaj kolekcję według kierunku.",catCta:"Otwórz kategorię",artEyebrow:"PORADNIKI / 03",artTitle:"Pomocne wskazówki przed zakupem.",read:"Czytaj",route:"TRASA / 04",routeTitle:"Wiedz, gdzie jesteś, zanim ruszysz dalej.",routeBody:"Potwierdź ofertę, sprawdź zdjęcia magazynowe i wyślij tylko wybrane produkty.",beginner:"Otwórz poradnik QC",productTrails:"TRASY PRODUKTÓW",qcWaypoints:"PUNKTY QC",shippingNotes:"NOTATKI WYSYŁKI",from:"Z głównej kolekcji",view:"Zobacz produkt",categoriesPage:"Cztery proste drogi do kolekcji.",categoriesBody:"Każda karta prowadzi do odpowiedniej kategorii głównej kolekcji.",findsPage:"Ten sam produkt, od zdjęcia do kliknięcia.",findsBody:"Każde zdjęcie i link odpowiada stronie produktu w głównej kolekcji.",articlesPage:"Praktyczne wskazówki dla lepszych zamówień.",articlesBody:"Krótkie poradniki o linkach, zdjęciach i paczkach.",qcPage:"Sprawdź widoczne szczegóły przed wysyłką.",qcBody:"Porównaj kolor, metki, wykonanie i wady z ofertą.",shippingPage:"Planuj paczkę, nie tylko produkt.",shippingBody:"Łącz produkty, porównuj trasy i sprawdzaj wagę.",article1:"Jak czytać ofertę USFans",article1d:"Lista kontroli linków, wariantów i sprzedawcy.",article2:"Co sprawdzać na zdjęciach QC",article2d:"Widoczne szczegóły przed wysyłką.",article3:"Jak planować wysyłkę międzynarodową",article3d:"Waga, łączenie i trasy w prostych słowach.",step1:"Potwierdź ofertę",step1d:"Sprawdź tytuł, wariant i sprzedawcę.",step2:"Sprawdź QC",step2d:"Porównaj szczegóły z ofertą.",step3:"Połącz",step3d:"Zostaw tylko wybrane produkty.",step4:"Wybierz trasę",step4d:"Porównaj wagę, czas i ograniczenia.",order:"ZAMÓWIENIE",warehouse:"MAGAZYN",parcel:"PACZKA",disclaimer:"Niezależny poradnik produktów i zakupów. Linki prowadzą do głównej kolekcji.",continue:"Przejdź do kolekcji" }),
  pt: mk({ home:"Início",categories:"Categorias",finds:"Produtos",articles:"Artigos SEO",qc:"Guia QC",shipping:"Envio",open:"Abrir coleção completa",atlas:"Atlas de produtos USFans",titleA:"Não deslize.",titleB:"Explore.",intro:"Escolha uma trilha, veja a imagem exata e abra o produto correspondente.",search:"Buscar produto, categoria ou colar link",searchBtn:"Buscar",shoes:"Tênis",hoodies:"Moletons",bags:"Bolsas",jerseys:"Camisas",trail:"Escolha uma trilha",start:"Começar",checkpoints:"Caimento + tecido",hardware:"Ferragens + forma",print:"Estampa + tamanho",field:"CARTÕES / 01",visual:"Comece com um produto real.",every:"Ver categorias",catEyebrow:"CATEGORIAS / 02",catTitle:"Explore a coleção por direção.",catCta:"Abrir categoria",artEyebrow:"GUIAS / 03",artTitle:"Ajuda útil antes da compra.",read:"Ler guia",route:"ROTA / 04",routeTitle:"Saiba onde está antes de avançar.",routeBody:"Confirme o anúncio, revise as fotos do armazém e envie apenas os itens desejados.",beginner:"Abrir guia QC",productTrails:"TRILHAS DE PRODUTO",qcWaypoints:"PONTOS QC",shippingNotes:"NOTAS DE ENVIO",from:"Da coleção principal",view:"Ver produto",categoriesPage:"Quatro caminhos claros para a coleção.",categoriesBody:"Cada cartão abre a categoria correspondente na coleção principal.",findsPage:"O mesmo produto, da imagem ao clique.",findsBody:"Cada imagem e link corresponde à página do produto principal.",articlesPage:"Notas práticas para pedidos melhores.",articlesBody:"Guias curtos sobre links, fotos e planejamento de pacotes.",qcPage:"Confira detalhes visíveis antes do envio.",qcBody:"Compare cor, etiquetas, acabamento e defeitos com o anúncio.",shippingPage:"Planeje o pacote, não apenas o produto.",shippingBody:"Consolide, compare rotas e confira o peso final.",article1:"Como ler um produto USFans",article1d:"Checklist para links, variantes e vendedor.",article2:"O que conferir nas fotos QC",article2d:"Detalhes visíveis antes do envio.",article3:"Como planejar o envio internacional",article3d:"Peso, consolidação e rotas em linguagem simples.",step1:"Confirmar anúncio",step1d:"Confira título, variante e vendedor.",step2:"Revisar QC",step2d:"Compare detalhes com o anúncio.",step3:"Consolidar",step3d:"Mantenha apenas os itens desejados.",step4:"Escolher rota",step4d:"Compare peso, prazo e restrições.",order:"PEDIDO",warehouse:"ARMAZÉM",parcel:"PACOTE",disclaimer:"Guia independente de produtos e compras. Os links levam à coleção principal.",continue:"Ir para a coleção" }),
  "zh-cn": mk({ home:"首页",categories:"产品分类",finds:"产品精选",articles:"SEO文章",qc:"质检指南",shipping:"物流指南",open:"打开完整选品库",atlas:"USFans 产品探索地图",titleA:"别再滑动。",titleB:"开始探索。",intro:"选择一条路线，查看与主站一致的产品首图，然后进入对应商品。",search:"搜索产品、分类或粘贴链接",searchBtn:"搜索",shoes:"鞋子",hoodies:"连帽衫",bags:"包袋",jerseys:"球衣",trail:"选择路线",start:"开始路线",checkpoints:"版型 + 面料",hardware:"五金 + 包型",print:"印花 + 尺码",field:"产品卡片 / 01",visual:"从真实产品开始。",every:"查看全部分类",catEyebrow:"产品分类 / 02",catTitle:"按方向浏览完整选品库。",catCta:"进入分类",artEyebrow:"实用文章 / 03",artTitle:"下单前值得阅读的指南。",read:"阅读指南",route:"流程说明 / 04",routeTitle:"进入下一步之前，先确认你所在的环节。",routeBody:"先确认卖家商品页，查看仓库质检照片，再只提交你要保留的商品进行国际运输。",beginner:"打开质检指南",productTrails:"产品路线",qcWaypoints:"质检节点",shippingNotes:"物流说明",from:"来自主站选品库",view:"查看商品",categoriesPage:"四条清晰的主站选品路线。",categoriesBody:"每张卡片都会跳转到主站对应的产品分类。",findsPage:"从图片到点击，始终是同一件产品。",findsBody:"下方每张图片和链接都与主站商品详情页一一对应。",articlesPage:"让下单更清楚的实用内容。",articlesBody:"围绕商品链接、仓库照片和包裹规划的简明指南。",qcPage:"发货之前，先检查看得见的细节。",qcBody:"将颜色、尺码标签、做工和明显瑕疵与卖家商品页逐项对比。",shippingPage:"不仅要选产品，也要规划包裹。",shippingBody:"合理合包、比较可用路线，并在提交前核对最终包裹重量。",article1:"如何阅读 USFans 商品信息",article1d:"快速核对链接、规格和卖家信息。",article2:"仓库质检照片需要看什么",article2d:"提交包裹前值得二次确认的可见细节。",article3:"如何规划国际包裹运输",article3d:"用简单语言说明重量、合包和线路选择。",step1:"确认商品页",step1d:"核对标题、所选规格和卖家链接。",step2:"查看质检",step2d:"将可见细节与原商品页对比。",step3:"整理合包",step3d:"包裹中只保留需要的商品。",step4:"选择线路",step4d:"比较重量、时效和运输限制。",order:"下单",warehouse:"仓库",parcel:"包裹",disclaimer:"独立的产品发现与购物指南。产品链接将跳转到主站选品库。",continue:"进入主站选品库" }),
};

const products = [
  { key:"shoes", name:"AF1 Air Force 1 Shoes Sneakers", price:"¥139", image:"/products/af1-shoes.webp", href:"https://www.cnfanshp.com/AllProducts/3861.html", category:"https://www.cnfanshp.com/shoes/", code:"01" },
  { key:"hoodies", name:"Corteiz Hoodie", price:"¥262", image:"/products/corteiz-hoodie.webp", href:"https://www.cnfanshp.com/AllProducts/3574.html", category:"https://www.cnfanshp.com/hoodies-sweaters/", code:"02" },
  { key:"bags", name:"Chanel bags", price:"¥390", image:"/products/chanel-bag.webp", href:"https://www.cnfanshp.com/AllProducts/5163.html", category:"https://www.cnfanshp.com/accessories/", code:"03" },
  { key:"jerseys", name:"Amiri B22 Jersey/Shorts Set", price:"¥95", image:"/products/amiri-jersey.webp", href:"https://www.cnfanshp.com/AllProducts/5178.html", category:"https://www.cnfanshp.com/Jersey/", code:"04" },
] as const;
const paths: Record<PageName,string> = { home:"/",categories:"/categories",finds:"/finds",articles:"/articles",article:"/articles",faq:"/faq",qc:"/qc-guide",shipping:"/shipping" };
const Arrow = () => <span aria-hidden="true">↗</span>;

export function SiteShell({ page, article }: { page: PageName; article?: ArticleSlug }) {
  const [lang,setLang] = useState<Lang>("en");
  useEffect(() => { const value=new URLSearchParams(window.location.search).get("lang") as Lang|null; if(value&&languages.some(x=>x.code===value)) setLang(value); },[]);
  useEffect(() => { document.documentElement.lang=lang; },[lang]);
  const t=copies[lang];
  const link=(name:PageName)=>`${paths[name]}${lang==="en"?"":`?lang=${lang}`}`;
  const change=(next:Lang)=>{ setLang(next); const url=new URL(window.location.href); if(next==="en") url.searchParams.delete("lang"); else url.searchParams.set("lang",next); window.history.replaceState({},"",`${url.pathname}${url.search}`); };
  return <div className="atlas" id="top"><Header page={page} link={link} lang={lang} change={change} t={t}/><main>{page==="home"?<HomeContent t={t} link={link} lang={lang}/>:page==="article"&&article?<ArticleDetail slug={article} lang={lang}/>:<InnerPage page={page as Exclude<PageName,"home"|"article">} t={t} link={link} lang={lang}/>}</main><Footer t={t} link={link}/></div>;
}

function Header({page,link,lang,change,t}:{page:PageName;link:(p:PageName)=>string;lang:Lang;change:(l:Lang)=>void;t:Copy}) {
  const nav:Array<[PageName,string]>=[["home",t.home],["categories",t.categories],["finds",t.finds],["articles",t.articles],["faq",faqText[lang].label],["qc",t.qc],["shipping",t.shipping]];
  return <header className="site-header"><a className="logo-link" href={link("home")} aria-label="USFans home"><img src="/usfans-logo.png" alt="USFans"/></a><nav aria-label="Primary navigation">{nav.map(([name,label])=><a className={(page===name||(page==="article"&&name==="articles"))?"active":""} href={link(name)} key={name}>{label}</a>)}</nav><div className="header-tools"><label className="language"><span className="sr-only">Language</span><select value={lang} onChange={e=>change(e.target.value as Lang)}>{languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><a className="header-cta" href="https://www.cnfanshp.com" target="_blank" rel="noreferrer">{t.open} <Arrow/></a></div></header>;
}

function SearchBox({t}:{t:Copy}) { const [term,setTerm]=useState(""); const destination=useMemo(()=>term.trim()?`https://www.cnfanshp.com/AllProducts/?keywords=${encodeURIComponent(term.trim())}`:"https://www.cnfanshp.com/AllProducts/",[term]); return <form className="search-box" onSubmit={e=>{e.preventDefault();window.open(destination,"_blank","noopener,noreferrer")}}><span aria-hidden="true">⌕</span><input aria-label={t.search} value={term} onChange={e=>setTerm(e.target.value)} placeholder={t.search}/><button type="submit">{t.searchBtn} <Arrow/></button></form>; }
function ProductCards({t}:{t:Copy}) { return <div className="find-grid">{products.map(item=><a className="find-card" href={item.href} target="_blank" rel="noreferrer" key={item.code}><div className="product-image"><img src={item.image} alt={item.name}/><span>{item.code}</span></div><div className="find-meta"><small>{t[item.key]}</small><strong>{item.name}</strong><span>{item.price} <Arrow/></span></div></a>)}</div>; }
function MapStage({t}:{t:Copy}) { const note={shoes:t.start,hoodies:t.checkpoints,bags:t.hardware,jerseys:t.print}; return <div className="map-stage"><div className="map-lines"/>{products.map(item=><a href={item.href} className={`map-product pin-${item.key}`} target="_blank" rel="noreferrer" key={item.key}><b>{item.code}</b><img src={item.image} alt=""/><span>{t[item.key]}<small>{note[item.key]}</small></span></a>)}<div className="map-key"><span>{t.productTrails}</span><span>{t.qcWaypoints}</span><span>{t.shippingNotes}</span></div></div>; }
function TrailStrip({t}:{t:Copy}) { return <section className="trail-strip"><span>{t.trail}</span>{products.map(item=><a href={item.href} target="_blank" rel="noreferrer" key={item.key}><img src={item.image} alt=""/><b>{t[item.key]}</b><small>{item.code}</small></a>)}</section>; }
function CategoryCards({t}:{t:Copy}) { return <div className="category-grid">{products.map(item=><a href={item.category} target="_blank" rel="noreferrer" key={item.key}><span>{item.code}</span><img src={item.image} alt=""/><div><small>{t.from}</small><h3>{t[item.key]}</h3><b>{t.catCta} <Arrow/></b></div></a>)}</div>; }
function ArticleCards({t,lang}:{t:Copy;lang:Lang}) { return <div className="article-grid">{articleSlugs.map((slug,index)=>{const item=articleData[lang][slug];return <a href={`/articles/${slug}${lang==="en"?"":`?lang=${lang}`}`} key={slug}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.description}</p><b>{t.read} <Arrow/></b></a>})}</div>; }

function FaqCard({lang,link}:{lang:Lang;link:(p:PageName)=>string}) { const f=faqText[lang]; return <a className="faq-home-card" href={link("faq")}><span>FAQ / 04</span><div><h3>{f.cardTitle}</h3><p>{f.cardBody}</p></div><b>{f.open} <Arrow/></b></a>; }

function HomeContent({t,link,lang}:{t:Copy;link:(p:PageName)=>string;lang:Lang}) { return <><section className="atlas-hero"><div className="atlas-copy"><p className="eyebrow"><span/> {t.atlas}</p><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.intro}</p><SearchBox t={t}/></div><MapStage t={t}/></section><TrailStrip t={t}/><section className="section atlas-finds"><SectionHead eyebrow={t.field} title={t.visual} href={link("finds")} cta={t.every}/><ProductCards t={t}/></section><section className="section category-section"><SectionHead eyebrow={t.catEyebrow} title={t.catTitle} href={link("categories")} cta={t.every}/><CategoryCards t={t}/></section><section className="section articles-section"><SectionHead eyebrow={t.artEyebrow} title={t.artTitle} href={link("articles")} cta={t.read}/><ArticleCards t={t} lang={lang}/></section><section className="section faq-home-section"><FaqCard lang={lang} link={link}/></section><RouteSection t={t} link={link}/></>; }
function SectionHead({eyebrow,title,href,cta}:{eyebrow:string;title:string;href:string;cta:string}) { return <div className="section-head"><p>{eyebrow}</p><h2>{title}</h2><a href={href}>{cta} <Arrow/></a></div>; }
function RouteSection({t,link}:{t:Copy;link:(p:PageName)=>string}) { return <section className="section atlas-process"><div className="atlas-route"><span>{t.order}</span><i/><span>{t.warehouse}</span><i/><span>QC</span><i/><span>{t.parcel}</span></div><div className="atlas-process-copy"><p>{t.route}</p><h2>{t.routeTitle}</h2><p>{t.routeBody}</p><a href={link("qc")}>{t.beginner} <Arrow/></a></div><div className="compass"><div>N</div><span>QC</span><i/></div></section>; }
function InnerPage({page,t,link,lang}:{page:Exclude<PageName,"home"|"article">;t:Copy;link:(p:PageName)=>string;lang:Lang}) { const f=faqText[lang]; const heading=page==="categories"?[t.categories,t.categoriesPage,t.categoriesBody]:page==="finds"?[t.finds,t.findsPage,t.findsBody]:page==="articles"?[t.articles,t.articlesPage,t.articlesBody]:page==="faq"?[f.eyebrow,f.title,f.body]:page==="qc"?[t.qc,t.qcPage,t.qcBody]:[t.shipping,t.shippingPage,t.shippingBody]; const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:f.questions.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))}; return <><section className="inner-hero"><p className="eyebrow"><span/> {heading[0]}</p><h1>{heading[1]}</h1><p>{heading[2]}</p></section>{page==="categories"&&<section className="section inner-content"><CategoryCards t={t}/></section>}{page==="finds"&&<section className="section inner-content"><ProductCards t={t}/></section>}{page==="articles"&&<section className="section inner-content"><ArticleCards t={t} lang={lang}/></section>}{page==="faq"&&<section className="section inner-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><div className="faq-list">{f.questions.map((item,index)=><details key={item.q}><summary><span>{String(index+1).padStart(2,"0")}</span>{item.q}<b>+</b></summary><p>{item.a}</p></details>)}</div></section>}{(page==="qc"||page==="shipping")&&<section className="section inner-content"><div className="steps-grid">{[["01",t.step1,t.step1d],["02",t.step2,t.step2d],["03",t.step3,t.step3d],["04",t.step4,t.step4d]].map(([n,title,body])=><article key={n}><span>{n}</span><h2>{title}</h2><p>{body}</p></article>)}</div></section>}</>; }

function ArticleDetail({slug,lang}:{slug:ArticleSlug;lang:Lang}) { const article=articleData[lang][slug]; const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,dateModified:"2026-08-13",datePublished:"2026-08-13",inLanguage:lang,author:{"@type":"Organization",name:"USFans Product Discovery Atlas"},mainEntityOfPage:`https://usfanss.store/articles/${slug}`}; return <article className="long-article"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="article-hero"><p className="eyebrow"><span/> {article.kicker}</p><h1>{article.title}</h1><p>{article.description}</p><div><span>{article.updated}</span><span>{article.readingTime}</span></div></header><div className="article-layout"><aside><b>{article.contentsLabel}</b>{article.sections.map((section,index)=><a href={`#section-${index+1}`} key={section.heading}>{String(index+1).padStart(2,"0")} {section.heading}</a>)}</aside><div className="article-content"><div className="fact-box"><b>{article.factTitle}</b><p>{article.factNote}</p></div>{article.sections.map((section,index)=><section id={`section-${index+1}`} key={section.heading}><span>{String(index+1).padStart(2,"0")}</span><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph.slice(0,60)}>{paragraph}</p>)}{index===2&&<figure><div className="article-image-row"><img src="/products/af1-shoes.webp" alt="Product listing example"/><img src="/products/corteiz-hoodie.webp" alt="Product listing example"/></div><figcaption>{article.imageCaption}</figcaption></figure>}</section>)}</div></div></article>; }
function Footer({t,link}:{t:Copy;link:(p:PageName)=>string}) { return <footer><a className="logo-link" href={link("home")}><img src="/usfans-logo.png" alt="USFans"/></a><p>{t.disclaimer}</p><a href="https://www.cnfanshp.com" target="_blank" rel="noreferrer">{t.continue} <Arrow/></a></footer>; }
