export const LEGAL_COPY = {
  en: {
    reviewed: "Last reviewed July 16, 2026",
    contact: {
      title: "Contact Hacoo Pro",
      description: "Contact the Hacoo Pro editorial guide about corrections, broken links, content updates or rights concerns.",
      label: "Contact",
      heading: ["Corrections", "make guides better."],
      intro: "For a factual correction, broken-link report, rights concern or editorial question, contact our shared editorial desk. This address is operated by the same publishing team as CNFansHP. Please include the exact Hacoo Pro URL and the information you believe should be reviewed.",
      important: "Important",
      note: "Hacoo Pro publishes editorial guidance and does not process orders. Transaction support must be requested from the website that handled the transaction.",
    },
    privacy: {
      title: "Hacoo Pro Privacy Policy",
      heading: "Privacy Policy",
      description: "Read how Hacoo Pro handles basic site usage, its publisher relationship with CNFansHP, external links and privacy requests.",
      intro: "This policy explains the privacy approach used by Hacoo Pro, an editorial discovery guide operated by the same publishing team as CNFansHP.",
      sections: [["Information handled", "The site does not provide user accounts or accept payments. Standard hosting logs may include IP address, browser information, referring pages and requested URLs for security and performance purposes."], ["Publisher relationship", "Hacoo Pro and CNFansHP are operated by the same publishing team but perform separate site functions. Hacoo Pro provides editorial research and navigation; CNFansHP provides external catalog destinations."], ["External websites", "Links may open CNFansHP or another external destination. Leaving Hacoo Pro means the destination website's privacy policy, cookies and controls apply, even when the destination shares the same publishing team."], ["Cookies and analytics", "No advertising or behavioral analytics cookies are intentionally included. If analytics or advertising tools are added, this policy and any required consent experience will be updated first."], ["Contact", "Privacy questions can be sent to the shared editorial desk at service@cnfanshp.com. Do not send order, payment or other unnecessary sensitive information to Hacoo Pro."]],
    },
    terms: {
      title: "Hacoo Pro Terms of Use",
      heading: "Terms of Use",
      description: "Read Hacoo Pro's terms, publisher relationship with CNFansHP and external-link limitations.",
      intro: "These terms describe the publisher relationship, role, limits and external-link practices of Hacoo Pro.",
      sections: [["Publisher and relationship", "Hacoo Pro is an editorial and navigation guide operated by the same publishing team as CNFansHP (cnfanshp.com). Hacoo Pro is not the official Hacoo website and is not affiliated with, endorsed by or operated by Hacoo, CNFans, Taobao, Weidian, 1688 or any other marketplace or platform."], ["Separate site functions", "Hacoo Pro publishes research and navigation. CNFansHP hosts the external catalog pages linked from this guide. The shared publisher relationship does not make either site an official service of Hacoo, CNFans or any marketplace."], ["No sales or transaction processing", "Hacoo Pro does not sell products, accept payments, process orders or control external listings. Transactions made after leaving this site take place on CNFansHP or the applicable external service under that destination's own terms."], ["Accuracy and changing information", "We aim to provide useful context, but external prices, images, availability, specifications, shipping options and policies may change without notice. Users must verify current information on the destination page."], ["Intellectual property", "Third-party names and images are used only for identification, commentary and navigation. Rights remain with their respective owners. Contact service@cnfanshp.com with the specific URL for a rights concern."], ["Limitation", "Use of this site and external links is at the user's discretion. Hacoo Pro does not guarantee product quality, legality, suitability, delivery or third-party performance."]],
    },
  },
  es: {
    reviewed: "Última revisión: 16 de julio de 2026",
    contact: {
      title: "Contacto de Hacoo Pro",
      description: "Contacta con la guía editorial Hacoo Pro para comunicar correcciones, enlaces rotos, actualizaciones o asuntos de derechos.",
      label: "Contacto",
      heading: ["Las correcciones", "mejoran las guías."],
      intro: "Para comunicar una corrección factual, un enlace roto, un asunto de derechos o una pregunta editorial, escribe a nuestro equipo editorial compartido. Esta dirección la gestiona el mismo equipo editor de CNFansHP. Incluye la URL exacta de Hacoo Pro y la información que crees que debe revisarse.",
      important: "Importante",
      note: "Hacoo Pro publica orientación editorial y no procesa pedidos. La asistencia sobre una transacción debe solicitarse al sitio web que la gestionó.",
    },
    privacy: {
      title: "Política de privacidad de Hacoo Pro",
      heading: "Política de privacidad",
      description: "Consulta cómo trata Hacoo Pro el uso básico del sitio, su relación editorial con CNFansHP, los enlaces externos y las solicitudes de privacidad.",
      intro: "Esta política explica el enfoque de privacidad de Hacoo Pro, una guía editorial de descubrimiento gestionada por el mismo equipo editor de CNFansHP.",
      sections: [["Información tratada", "El sitio no ofrece cuentas de usuario ni acepta pagos. Los registros estándar del alojamiento pueden incluir dirección IP, navegador, páginas de referencia y URLs solicitadas para fines de seguridad y rendimiento."], ["Relación editorial", "Hacoo Pro y CNFansHP están gestionados por el mismo equipo editor, pero cumplen funciones separadas. Hacoo Pro ofrece investigación y navegación editorial; CNFansHP proporciona destinos de catálogo externos."], ["Sitios externos", "Los enlaces pueden abrir CNFansHP u otro destino externo. Al salir de Hacoo Pro se aplican la política de privacidad, las cookies y los controles del sitio de destino, aunque comparta el mismo equipo editor."], ["Cookies y analítica", "No se incluyen intencionadamente cookies publicitarias ni de analítica conductual. Si se añaden herramientas de analítica o publicidad, esta política y cualquier consentimiento necesario se actualizarán primero."], ["Contacto", "Las consultas de privacidad pueden enviarse a service@cnfanshp.com. No envíes a Hacoo Pro datos de pedidos, pagos ni otra información sensible innecesaria."]],
    },
    terms: {
      title: "Condiciones de uso de Hacoo Pro",
      heading: "Condiciones de uso",
      description: "Consulta las condiciones de Hacoo Pro, su relación editorial con CNFansHP y los límites aplicables a los enlaces externos.",
      intro: "Estas condiciones describen la relación editorial, la función, los límites y las prácticas de enlaces externos de Hacoo Pro.",
      sections: [["Editor y relación", "Hacoo Pro es una guía editorial y de navegación gestionada por el mismo equipo editor de CNFansHP (cnfanshp.com). No es el sitio oficial de Hacoo ni está afiliado, respaldado u operado por Hacoo, CNFans, Taobao, Weidian, 1688 u otro mercado o plataforma."], ["Funciones separadas", "Hacoo Pro publica investigación y navegación. CNFansHP aloja las páginas de catálogo externas enlazadas. Compartir equipo editor no convierte a ninguno de los sitios en servicio oficial de Hacoo, CNFans o un mercado."], ["Sin ventas ni procesamiento de transacciones", "Hacoo Pro no vende productos, acepta pagos, procesa pedidos ni controla anuncios externos. Las transacciones realizadas tras salir del sitio se rigen por las condiciones del destino correspondiente."], ["Exactitud e información cambiante", "Procuramos ofrecer contexto útil, pero precios, imágenes, disponibilidad, especificaciones, envíos y políticas externas pueden cambiar sin aviso. El usuario debe comprobar la información actual en el destino."], ["Propiedad intelectual", "Los nombres e imágenes de terceros se usan únicamente para identificación, comentario y navegación. Los derechos pertenecen a sus titulares. Para un asunto de derechos, escribe a service@cnfanshp.com e indica la URL exacta."], ["Limitación", "El uso de este sitio y de los enlaces externos queda a criterio del usuario. Hacoo Pro no garantiza calidad, legalidad, idoneidad, entrega ni actuación de terceros."]],
    },
  },
  fr: {
    reviewed: "Dernière révision : 16 juillet 2026",
    contact: {
      title: "Contacter Hacoo Pro",
      description: "Contactez le guide éditorial Hacoo Pro pour une correction, un lien rompu, une mise à jour ou une question de droits.",
      label: "Contact",
      heading: ["Les corrections", "améliorent les guides."],
      intro: "Pour signaler une erreur factuelle, un lien rompu, une question de droits ou une demande éditoriale, écrivez à notre équipe éditoriale commune. Cette adresse est gérée par la même équipe éditrice que CNFansHP. Indiquez l’URL Hacoo Pro exacte et l’information à vérifier.",
      important: "Important",
      note: "Hacoo Pro publie des conseils éditoriaux et ne traite aucune commande. L’assistance liée à une transaction doit être demandée au site qui l’a traitée.",
    },
    privacy: {
      title: "Politique de confidentialité Hacoo Pro",
      heading: "Politique de confidentialité",
      description: "Découvrez comment Hacoo Pro traite l’usage du site, sa relation éditoriale avec CNFansHP, les liens externes et les demandes de confidentialité.",
      intro: "Cette politique explique l’approche de confidentialité de Hacoo Pro, un guide éditorial géré par la même équipe éditrice que CNFansHP.",
      sections: [["Informations traitées", "Le site ne propose pas de compte utilisateur et n’accepte aucun paiement. Les journaux d’hébergement standard peuvent inclure l’adresse IP, le navigateur, les pages référentes et les URLs demandées à des fins de sécurité et de performance."], ["Relation éditoriale", "Hacoo Pro et CNFansHP sont gérés par la même équipe éditrice mais remplissent des fonctions distinctes. Hacoo Pro fournit recherche et navigation éditoriales ; CNFansHP fournit des destinations de catalogue externes."], ["Sites externes", "Les liens peuvent ouvrir CNFansHP ou un autre site. Après avoir quitté Hacoo Pro, la politique de confidentialité, les cookies et les contrôles du site de destination s’appliquent, même s’il partage la même équipe éditrice."], ["Cookies et analyse", "Aucun cookie publicitaire ou d’analyse comportementale n’est volontairement inclus. Si de tels outils sont ajoutés, cette politique et l’expérience de consentement requise seront d’abord mises à jour."], ["Contact", "Les questions de confidentialité peuvent être envoyées à service@cnfanshp.com. N’envoyez pas à Hacoo Pro d’informations de commande, de paiement ou d’autres données sensibles inutiles."]],
    },
    terms: {
      title: "Conditions d’utilisation Hacoo Pro",
      heading: "Conditions d’utilisation",
      description: "Consultez les conditions de Hacoo Pro, sa relation éditoriale avec CNFansHP et les limites des liens externes.",
      intro: "Ces conditions décrivent la relation éditoriale, le rôle, les limites et les pratiques de liens externes de Hacoo Pro.",
      sections: [["Éditeur et relation", "Hacoo Pro est un guide éditorial et de navigation géré par la même équipe éditrice que CNFansHP (cnfanshp.com). Ce n’est pas le site officiel Hacoo et il n’est ni affilié, ni approuvé, ni exploité par Hacoo, CNFans, Taobao, Weidian, 1688 ou toute autre plateforme."], ["Fonctions distinctes", "Hacoo Pro publie recherche et navigation. CNFansHP héberge les pages de catalogue externes liées. Le partage d’un éditeur ne fait d’aucun des sites un service officiel de Hacoo, CNFans ou d’une plateforme."], ["Aucune vente ni transaction", "Hacoo Pro ne vend pas, n’accepte pas de paiement, ne traite pas de commande et ne contrôle pas les annonces externes. Les transactions après avoir quitté le site relèvent des conditions du site de destination."], ["Exactitude et évolution", "Nous cherchons à fournir un contexte utile, mais prix, images, disponibilité, caractéristiques, livraison et politiques externes peuvent changer sans préavis. Vérifiez les données actuelles sur le site de destination."], ["Propriété intellectuelle", "Les noms et images de tiers servent uniquement à l’identification, au commentaire et à la navigation. Les droits restent à leurs propriétaires. Pour une question de droits, écrivez à service@cnfanshp.com avec l’URL précise."], ["Limitation", "L’usage du site et des liens externes relève du choix de l’utilisateur. Hacoo Pro ne garantit ni qualité, légalité, adéquation, livraison ni performance de tiers."]],
    },
  },
  de: {
    reviewed: "Zuletzt geprüft am 16. Juli 2026",
    contact: {
      title: "Kontakt zu Hacoo Pro",
      description: "Kontaktiere den Hacoo-Pro-Ratgeber zu Korrekturen, defekten Links, Aktualisierungen oder Rechtefragen.",
      label: "Kontakt",
      heading: ["Korrekturen", "machen Ratgeber besser."],
      intro: "Melde sachliche Korrekturen, defekte Links, Rechtefragen oder redaktionelle Anliegen an unser gemeinsames Redaktionsteam. Diese Adresse wird vom selben Herausgeberteam wie CNFansHP betreut. Nenne die genaue Hacoo-Pro-URL und die zu prüfende Angabe.",
      important: "Wichtig",
      note: "Hacoo Pro veröffentlicht redaktionelle Hinweise und verarbeitet keine Bestellungen. Hilfe zu einer Transaktion muss bei der Website angefordert werden, die sie abgewickelt hat.",
    },
    privacy: {
      title: "Datenschutzerklärung von Hacoo Pro",
      heading: "Datenschutzerklärung",
      description: "Erfahre, wie Hacoo Pro grundlegende Nutzung, die Herausgeberbeziehung zu CNFansHP, externe Links und Datenschutzanfragen behandelt.",
      intro: "Diese Erklärung beschreibt den Datenschutzansatz von Hacoo Pro, einem redaktionellen Ratgeber desselben Herausgeberteams wie CNFansHP.",
      sections: [["Verarbeitete Informationen", "Die Website bietet keine Benutzerkonten und nimmt keine Zahlungen an. Übliche Hosting-Protokolle können IP-Adresse, Browserangaben, verweisende Seiten und aufgerufene URLs für Sicherheit und Leistung enthalten."], ["Herausgeberbeziehung", "Hacoo Pro und CNFansHP werden vom selben Herausgeberteam betrieben, erfüllen aber getrennte Aufgaben. Hacoo Pro bietet redaktionelle Recherche und Navigation; CNFansHP stellt externe Katalogziele bereit."], ["Externe Websites", "Links können CNFansHP oder andere Ziele öffnen. Nach dem Verlassen von Hacoo Pro gelten Datenschutz, Cookies und Einstellungen der Zielseite, auch wenn sie dasselbe Herausgeberteam hat."], ["Cookies und Analyse", "Werbe- oder verhaltensbezogene Analyse-Cookies werden nicht absichtlich eingebunden. Vor der Einführung solcher Tools werden diese Erklärung und eine erforderliche Einwilligung aktualisiert."], ["Kontakt", "Datenschutzfragen können an service@cnfanshp.com gesendet werden. Übermittle Hacoo Pro keine Bestell-, Zahlungs- oder anderen unnötigen sensiblen Daten."]],
    },
    terms: {
      title: "Nutzungsbedingungen von Hacoo Pro",
      heading: "Nutzungsbedingungen",
      description: "Lies die Bedingungen von Hacoo Pro, die Herausgeberbeziehung zu CNFansHP und die Grenzen externer Links.",
      intro: "Diese Bedingungen beschreiben Herausgeberbeziehung, Rolle, Grenzen und externe Verlinkung von Hacoo Pro.",
      sections: [["Herausgeber und Beziehung", "Hacoo Pro ist ein redaktioneller Navigationsratgeber desselben Herausgeberteams wie CNFansHP (cnfanshp.com). Es ist nicht die offizielle Hacoo-Website und weder mit Hacoo, CNFans, Taobao, Weidian, 1688 noch einer anderen Plattform verbunden, von ihr empfohlen oder betrieben."], ["Getrennte Website-Funktionen", "Hacoo Pro veröffentlicht Recherche und Navigation. CNFansHP hostet die verlinkten externen Katalogseiten. Ein gemeinsamer Herausgeber macht keine Seite zu einem offiziellen Dienst von Hacoo, CNFans oder einer Plattform."], ["Keine Verkäufe oder Transaktionen", "Hacoo Pro verkauft keine Produkte, nimmt keine Zahlungen an, verarbeitet keine Bestellungen und kontrolliert keine externen Angebote. Transaktionen nach dem Verlassen der Seite unterliegen den Bedingungen des jeweiligen Ziels."], ["Richtigkeit und Änderungen", "Wir wollen nützlichen Kontext bieten; externe Preise, Bilder, Bestand, Spezifikationen, Versandoptionen und Richtlinien können sich jedoch ohne Hinweis ändern. Prüfe aktuelle Angaben auf der Zielseite."], ["Geistiges Eigentum", "Namen und Bilder Dritter dienen nur Identifikation, Kommentar und Navigation. Rechte bleiben bei den jeweiligen Inhabern. Rechtefragen bitte mit genauer URL an service@cnfanshp.com senden."], ["Haftungsgrenze", "Die Nutzung dieser Website und externer Links erfolgt nach Ermessen des Nutzers. Hacoo Pro garantiert weder Produktqualität, Rechtmäßigkeit, Eignung, Lieferung noch Leistungen Dritter."]],
    },
  },
  it: {
    reviewed: "Ultima revisione: 16 luglio 2026",
    contact: {
      title: "Contatta Hacoo Pro",
      description: "Contatta la guida editoriale Hacoo Pro per correzioni, link non funzionanti, aggiornamenti o questioni relative ai diritti.",
      label: "Contatti",
      heading: ["Le correzioni", "migliorano le guide."],
      intro: "Per una correzione fattuale, un link non funzionante, una questione relativa ai diritti o una domanda editoriale, scrivi alla nostra redazione condivisa. L’indirizzo è gestito dallo stesso team editoriale di CNFansHP. Includi l’URL Hacoo Pro esatto e l’informazione da verificare.",
      important: "Importante",
      note: "Hacoo Pro pubblica contenuti editoriali e non gestisce ordini. L’assistenza per una transazione deve essere richiesta al sito che l’ha elaborata.",
    },
    privacy: {
      title: "Informativa sulla privacy di Hacoo Pro",
      heading: "Informativa sulla privacy",
      description: "Scopri come Hacoo Pro tratta l’uso di base del sito, il rapporto editoriale con CNFansHP, i link esterni e le richieste sulla privacy.",
      intro: "Questa informativa descrive l’approccio alla privacy di Hacoo Pro, una guida editoriale gestita dallo stesso team di CNFansHP.",
      sections: [["Informazioni trattate", "Il sito non offre account utente e non accetta pagamenti. I normali log di hosting possono includere indirizzo IP, browser, pagine di provenienza e URL richiesti per sicurezza e prestazioni."], ["Rapporto editoriale", "Hacoo Pro e CNFansHP sono gestiti dallo stesso team editoriale ma hanno funzioni separate. Hacoo Pro offre ricerca e navigazione editoriale; CNFansHP fornisce destinazioni di catalogo esterne."], ["Siti esterni", "I link possono aprire CNFansHP o un altro sito. Dopo aver lasciato Hacoo Pro si applicano privacy, cookie e controlli della destinazione, anche se condivide lo stesso team editoriale."], ["Cookie e analisi", "Non vengono inseriti intenzionalmente cookie pubblicitari o di analisi comportamentale. Prima di aggiungere tali strumenti saranno aggiornate l’informativa e l’eventuale esperienza di consenso."], ["Contatto", "Le domande sulla privacy possono essere inviate a service@cnfanshp.com. Non inviare a Hacoo Pro dati di ordine, pagamento o altre informazioni sensibili non necessarie."]],
    },
    terms: {
      title: "Termini di utilizzo di Hacoo Pro",
      heading: "Termini di utilizzo",
      description: "Leggi i termini di Hacoo Pro, il rapporto editoriale con CNFansHP e i limiti dei link esterni.",
      intro: "Questi termini descrivono il rapporto editoriale, il ruolo, i limiti e le pratiche di collegamento esterno di Hacoo Pro.",
      sections: [["Editore e rapporto", "Hacoo Pro è una guida editoriale e di navigazione gestita dallo stesso team di CNFansHP (cnfanshp.com). Non è il sito ufficiale Hacoo e non è affiliato, approvato o gestito da Hacoo, CNFans, Taobao, Weidian, 1688 o altra piattaforma."], ["Funzioni separate", "Hacoo Pro pubblica ricerca e navigazione. CNFansHP ospita le pagine di catalogo esterne collegate. La condivisione dell’editore non rende i siti servizi ufficiali di Hacoo, CNFans o una piattaforma."], ["Nessuna vendita o transazione", "Hacoo Pro non vende prodotti, accetta pagamenti, elabora ordini o controlla inserzioni esterne. Le transazioni effettuate dopo l’uscita seguono i termini della destinazione applicabile."], ["Accuratezza e cambiamenti", "Cerchiamo di offrire contesto utile, ma prezzi, immagini, disponibilità, specifiche, spedizioni e politiche esterne possono cambiare senza preavviso. Verifica i dati attuali sulla destinazione."], ["Proprietà intellettuale", "Nomi e immagini di terzi sono usati solo per identificazione, commento e navigazione. I diritti restano ai rispettivi titolari. Per questioni relative ai diritti, scrivi a service@cnfanshp.com indicando l’URL preciso."], ["Limitazione", "L’uso del sito e dei link esterni è a discrezione dell’utente. Hacoo Pro non garantisce qualità, legalità, idoneità, consegna o prestazioni di terzi."]],
    },
  },
  pt: {
    reviewed: "Última revisão: 16 de julho de 2026",
    contact: {
      title: "Contactar o Hacoo Pro",
      description: "Contacte o guia editorial Hacoo Pro sobre correções, links com falhas, atualizações ou questões de direitos.",
      label: "Contacto",
      heading: ["As correções", "melhoram os guias."],
      intro: "Para comunicar uma correção factual, um link com falha, uma questão de direitos ou uma pergunta editorial, escreva à nossa equipa editorial partilhada. Este endereço é gerido pela mesma equipa da CNFansHP. Inclua o URL exato do Hacoo Pro e a informação a rever.",
      important: "Importante",
      note: "O Hacoo Pro publica orientação editorial e não processa encomendas. O apoio relativo a uma transação deve ser pedido ao site que a processou.",
    },
    privacy: {
      title: "Política de privacidade do Hacoo Pro",
      heading: "Política de privacidade",
      description: "Saiba como o Hacoo Pro trata a utilização do site, a relação editorial com a CNFansHP, links externos e pedidos de privacidade.",
      intro: "Esta política explica a abordagem de privacidade do Hacoo Pro, um guia editorial gerido pela mesma equipa da CNFansHP.",
      sections: [["Informação tratada", "O site não disponibiliza contas de utilizador nem aceita pagamentos. Os registos normais de alojamento podem incluir endereço IP, navegador, páginas de referência e URLs pedidos para segurança e desempenho."], ["Relação editorial", "O Hacoo Pro e a CNFansHP são geridos pela mesma equipa editorial, mas têm funções separadas. O Hacoo Pro oferece pesquisa e navegação editorial; a CNFansHP fornece destinos externos de catálogo."], ["Sites externos", "Os links podem abrir a CNFansHP ou outro destino. Ao sair do Hacoo Pro, aplicam-se a privacidade, os cookies e os controlos do site de destino, mesmo quando partilha a mesma equipa editorial."], ["Cookies e análise", "Não são incluídos intencionalmente cookies de publicidade ou análise comportamental. Se essas ferramentas forem adicionadas, esta política e qualquer experiência de consentimento necessária serão primeiro atualizadas."], ["Contacto", "As questões de privacidade podem ser enviadas para service@cnfanshp.com. Não envie ao Hacoo Pro dados de encomendas, pagamentos ou outra informação sensível desnecessária."]],
    },
    terms: {
      title: "Termos de utilização do Hacoo Pro",
      heading: "Termos de utilização",
      description: "Leia os termos do Hacoo Pro, a relação editorial com a CNFansHP e os limites dos links externos.",
      intro: "Estes termos descrevem a relação editorial, a função, os limites e as práticas de links externos do Hacoo Pro.",
      sections: [["Editor e relação", "O Hacoo Pro é um guia editorial e de navegação gerido pela mesma equipa da CNFansHP (cnfanshp.com). Não é o site oficial da Hacoo e não é afiliado, aprovado ou operado pela Hacoo, CNFans, Taobao, Weidian, 1688 ou qualquer outra plataforma."], ["Funções separadas", "O Hacoo Pro publica pesquisa e navegação. A CNFansHP aloja as páginas externas de catálogo ligadas. A relação editorial comum não torna nenhum dos sites um serviço oficial da Hacoo, CNFans ou de qualquer plataforma."], ["Sem vendas ou processamento", "O Hacoo Pro não vende produtos, aceita pagamentos, processa encomendas ou controla anúncios externos. As transações realizadas após sair do site decorrem no destino aplicável segundo os seus próprios termos."], ["Exatidão e alterações", "Procuramos oferecer contexto útil, mas preços, imagens, disponibilidade, especificações, envio e políticas externas podem mudar sem aviso. Confirme sempre a informação atual no destino."], ["Propriedade intelectual", "Nomes e imagens de terceiros são usados apenas para identificação, comentário e navegação. Os direitos pertencem aos respetivos titulares. Para uma questão de direitos, escreva para service@cnfanshp.com com o URL específico."], ["Limitação", "A utilização do site e de links externos fica ao critério do utilizador. O Hacoo Pro não garante qualidade, legalidade, adequação, entrega ou desempenho de terceiros."]],
    },
  },
};

export function getLegalCopy(locale = "en") {
  return LEGAL_COPY[locale] || LEGAL_COPY.en;
}
