export const PRODUCT_PAGE_COPY = {
  en: {
    eyebrow: "Checked product index",
    title: ["Current product", "references."],
    lead: "Browse eight image-matched product references across the main Hacoo Pro categories. Each detail route was opened and checked against its current catalog image.",
    detailStat: "detail routes checked",
    categoryStat: "category checklists",
    reviewed: "Last checked",
    reviewedDate: "July 15, 2026",
    directoryLabel: "Verified directory",
    directoryTitle: "Start with a current match.",
    directoryText: "Open the Hacoo Pro reference first for the matching image and category checks, or continue to the current external listing. A live-search fallback remains available if a detail address changes later.",
    all: "All products",
    reference: "Research page",
    listing: "Open listing",
    fallback: "Search fallback",
    checked: "Checked",
    status: "Detail route responded",
    noticeTitle: "Live listings can change.",
    notice: "A successful check confirms that the address, catalog label and image matched at the review time. It does not guarantee stock, price, quality, authenticity or future availability. Recheck the selected option on the destination page.",
  },
  es: {
    eyebrow: "Índice de productos comprobados",
    title: ["Referencias de producto", "actuales."],
    lead: "Consulta ocho referencias con imagen verificada en las principales categorías de Hacoo Pro. Cada página se abrió y se comparó con su imagen actual.",
    detailStat: "enlaces de detalle comprobados",
    categoryStat: "listas por categoría",
    reviewed: "Última comprobación",
    reviewedDate: "15 de julio de 2026",
    directoryLabel: "Directorio verificado",
    directoryTitle: "Empieza con una coincidencia actual.",
    directoryText: "Abre primero la referencia de Hacoo Pro para ver la imagen y las comprobaciones, o continúa al anuncio externo. Si cambia el enlace, usa la búsqueda alternativa.",
    all: "Todos",
    reference: "Página de análisis",
    listing: "Abrir anuncio",
    fallback: "Búsqueda alternativa",
    checked: "Comprobado",
    status: "El enlace respondió",
    noticeTitle: "Los anuncios pueden cambiar.",
    notice: "La comprobación confirma la coincidencia de dirección, etiqueta e imagen en la fecha indicada. No garantiza stock, precio, calidad, autenticidad ni disponibilidad futura.",
  },
  fr: {
    eyebrow: "Index de produits vérifiés",
    title: ["Références produit", "actuelles."],
    lead: "Parcourez huit références dont l’image a été vérifiée dans les principales catégories Hacoo Pro. Chaque page a été ouverte et comparée à son image actuelle.",
    detailStat: "liens produit vérifiés",
    categoryStat: "listes de contrôle",
    reviewed: "Dernière vérification",
    reviewedDate: "15 juillet 2026",
    directoryLabel: "Répertoire vérifié",
    directoryTitle: "Commencez par une correspondance actuelle.",
    directoryText: "Ouvrez d’abord la référence Hacoo Pro pour retrouver l’image et les contrôles, ou continuez vers l’annonce externe. Une recherche de secours reste disponible.",
    all: "Tous les produits",
    reference: "Page de recherche",
    listing: "Ouvrir l’annonce",
    fallback: "Recherche de secours",
    checked: "Vérifié",
    status: "Le lien a répondu",
    noticeTitle: "Les annonces peuvent changer.",
    notice: "La vérification confirme l’adresse, le libellé et l’image à la date indiquée. Elle ne garantit ni stock, ni prix, ni qualité, ni authenticité, ni disponibilité future.",
  },
  de: {
    eyebrow: "Geprüfter Produktindex",
    title: ["Aktuelle", "Produktreferenzen."],
    lead: "Acht bildgeprüfte Referenzen aus den wichtigsten Hacoo-Pro-Kategorien. Jede Detailseite wurde geöffnet und mit ihrem aktuellen Katalogbild verglichen.",
    detailStat: "Detailseiten geprüft",
    categoryStat: "Kategorie-Checklisten",
    reviewed: "Zuletzt geprüft",
    reviewedDate: "15. Juli 2026",
    directoryLabel: "Geprüftes Verzeichnis",
    directoryTitle: "Mit einem aktuellen Treffer beginnen.",
    directoryText: "Öffne zuerst die Hacoo-Pro-Referenz für Bild und Prüfpunkte oder gehe zum externen Angebot. Falls sich der Link ändert, steht eine Suchalternative bereit.",
    all: "Alle Produkte",
    reference: "Recherche-Seite",
    listing: "Angebot öffnen",
    fallback: "Suchalternative",
    checked: "Geprüft",
    status: "Detailseite erreichbar",
    noticeTitle: "Angebote können sich ändern.",
    notice: "Die Prüfung bestätigt Adresse, Katalogbezeichnung und Bild zum genannten Zeitpunkt. Sie garantiert weder Bestand, Preis, Qualität, Echtheit noch künftige Verfügbarkeit.",
  },
  it: {
    eyebrow: "Indice prodotti verificati",
    title: ["Riferimenti prodotto", "aggiornati."],
    lead: "Consulta otto riferimenti con immagine verificata nelle principali categorie Hacoo Pro. Ogni pagina è stata aperta e confrontata con l’immagine attuale.",
    detailStat: "pagine prodotto verificate",
    categoryStat: "checklist di categoria",
    reviewed: "Ultima verifica",
    reviewedDate: "15 luglio 2026",
    directoryLabel: "Elenco verificato",
    directoryTitle: "Inizia da una corrispondenza attuale.",
    directoryText: "Apri prima il riferimento Hacoo Pro per immagine e controlli, oppure continua all’inserzione esterna. Se il collegamento cambia, usa la ricerca alternativa.",
    all: "Tutti i prodotti",
    reference: "Pagina di ricerca",
    listing: "Apri inserzione",
    fallback: "Ricerca alternativa",
    checked: "Verificato",
    status: "Pagina raggiungibile",
    noticeTitle: "Le inserzioni possono cambiare.",
    notice: "La verifica conferma indirizzo, etichetta e immagine alla data indicata. Non garantisce disponibilità, prezzo, qualità, autenticità o presenza futura.",
  },
  pt: {
    eyebrow: "Índice de produtos verificados",
    title: ["Referências de produto", "atuais."],
    lead: "Consulte oito referências com imagem verificada nas principais categorias Hacoo Pro. Cada página foi aberta e comparada com a imagem atual.",
    detailStat: "páginas de detalhe verificadas",
    categoryStat: "checklists de categoria",
    reviewed: "Última verificação",
    reviewedDate: "15 de julho de 2026",
    directoryLabel: "Diretório verificado",
    directoryTitle: "Comece por uma correspondência atual.",
    directoryText: "Abra primeiro a referência Hacoo Pro para ver a imagem e as verificações, ou continue para o anúncio externo. Se o endereço mudar, use a pesquisa alternativa.",
    all: "Todos os produtos",
    reference: "Página de pesquisa",
    listing: "Abrir anúncio",
    fallback: "Pesquisa alternativa",
    checked: "Verificado",
    status: "Página acessível",
    noticeTitle: "Os anúncios podem mudar.",
    notice: "A verificação confirma o endereço, o rótulo e a imagem na data indicada. Não garante stock, preço, qualidade, autenticidade ou disponibilidade futura.",
  },
};

export function getProductPageCopy(locale = "en") {
  return PRODUCT_PAGE_COPY[locale] || PRODUCT_PAGE_COPY.en;
}
