import type { Lang } from "./i18n";
import { localizedDepth } from "./articleDepth";
import { localizedDepthExtra } from "./articleDepthExtra";
import { localizedDepthFinal } from "./articleDepthFinal";

export type ArticleSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type ArticleContent = { standfirst: string; sections: ArticleSection[]; takeaway: string };

const en: ArticleContent[] = [
  {
    standfirst: "A useful USFans product index is not a magic catalogue and it should never be treated as proof that a seller, price or variant is still available. Its real value is speed: it helps you move from a broad idea to a product page that you can verify. This guide explains a repeatable way to search, compare and document a listing before money leaves your account.",
    sections: [
      { heading: "Start with intent, not an endless scroll", paragraphs: [
        "Before opening dozens of cards, write down what you are actually trying to buy: category, approximate budget, size, colour, material and the details you will not compromise on. A search for “hoodie” produces noise; a search plan such as “heavy zip hoodie, dark grey, chest measurement available” gives you a way to reject weak listings quickly. This matters because an index can organise links, but it cannot decide whether a product suits your body, climate or expectations.",
        "Use category pages to create a shortlist, then open the current product listing for every candidate. USFans publicly positions itself as an agent for Taobao, 1688 and Weidian purchases. That means the source listing remains important: sellers can change prices, remove variants, edit photographs or stop selling an item. Save the product name, chosen variant and a screenshot or note of the key details you relied on. A short record prevents confusion later when several similar orders reach the warehouse."
      ], bullets: ["Define category, budget, size and non-negotiable details.", "Shortlist first; verify the current listing second.", "Record the exact colour, size and seller option before ordering."] },
      { heading: "Read the listing like a specification sheet", paragraphs: [
        "Treat the title as a label, not a complete description. Work through the variant selector, size information, material notes, seller photographs, domestic delivery estimate and any warning shown by the agent. If a listing offers several batches or versions, do not assume the highest price is automatically best. Look for measurable differences and ask for clarification when the distinction is vague. A useful decision is based on evidence you can check later, not on a product name that sounds premium.",
        "Product pages indexed by USFans can display estimated time to warehouse, weight and package dimensions. Those fields are planning signals rather than guarantees: examples visible on the platform vary by product, and a seller still has to dispatch the order. Weight and dimensions are especially useful because they connect the purchase decision to international shipping. A low product price can become poor value if the item is unusually bulky, includes heavy packaging or can travel only through a limited route."
      ] },
      { heading: "Separate the three prices", paragraphs: [
        "New buyers often remember only the item price. In practice, there are at least three cost layers: the seller’s product price, domestic delivery to the warehouse, and international parcel charges after the item is stored. Payment conversion, optional services, packaging and destination taxes can add further cost. Keep a simple running total for each item and a second estimate for the parcel. This makes it easier to decide whether another low-cost accessory genuinely improves the haul or merely increases chargeable weight.",
        "Never present an early estimate as a final shipping quote. The final parcel may be charged by actual weight or volumetric weight, depending on the route. Removing unnecessary packaging can reduce volume, while protective packaging can increase it. The correct question is not “What is the cheapest line?” but “Which eligible line gives an acceptable balance of chargeable weight, tracking, restrictions, delivery range and protection for this particular parcel?”"
      ] },
      { heading: "Use warehouse arrival as a verification gate", paragraphs: [
        "USFans states on current product pages that purchased items are sent to its warehouse, checked and photographed. Many listings also state that 3–7 HD quality-inspection photos are provided free. This is the point where an online listing becomes a physical item you can inspect indirectly. Compare the warehouse images with the exact variant you recorded: colour, overall shape, visible branding, size label, quantity and obvious damage should all agree before you continue.",
        "Do not approve on the strength of a single attractive angle. Zoom in and compare left and right sides, stitching paths, print placement, hardware, labels and proportions. If a critical area is not visible, ask whether an additional photograph or measurement is available and check the current fee before requesting it. QC is not laboratory authentication and it cannot reveal every material or durability issue. It is a practical visual checkpoint designed to catch visible mismatches while the item is still in China."
      ] },
      { heading: "Act while after-sales options are still open", paragraphs: [
        "Current USFans product pages commonly state that a buyer who is dissatisfied after warehouse arrival can apply for a return within five days, after which the agent negotiates with the seller. Treat that as a narrow action window, not an unconditional promise. Seller policy, custom products, hygiene-sensitive goods, return freight and the condition of the item can affect the result. Read the terms shown on the actual order and do not wait until parcel submission to raise an obvious problem.",
        "When reporting an issue, be precise. “Looks wrong” is weak; “the ordered size is XL but the photographed label shows M” is actionable. Attach the relevant listing reference and identify the image that shows the problem. A clear message reduces back-and-forth and helps the agent discuss the case with the seller. Keep the item separate from the parcel until the return, exchange or acceptance decision is complete."
      ] },
      { heading: "Build the parcel only after every item passes", paragraphs: [
        "A consolidated parcel is easier to plan when every stored item has a status: accept, question, return or waiting for another item. Do not rush because one product arrived early. Check route restrictions before combining batteries, liquids, magnets, fragile goods or unusually large boxes with ordinary clothing. USFans product pages warn that prohibited or limited items, logistics restrictions, weight and volume limits can affect available routes. Eligibility is therefore part of product research, not a last-minute shipping detail.",
        "Use the platform’s estimation and rehearsal functions as planning tools when they are available in your account. Rehearsal can help establish a more realistic packed size and weight before final submission, but the displayed options and fees at the time of parcel creation remain the authority. Verify the recipient, country, postcode and phone format carefully. A perfect product shortlist is wasted if address data or route selection creates an avoidable delivery problem."
      ] },
      { heading: "A compact workflow you can repeat", paragraphs: [
        "The fastest reliable method is a funnel. Begin with ten plausible listings, remove those with unclear variants or weak measurements, compare the remaining three or four on total likely cost, and order only after recording the exact option. At warehouse arrival, compare QC with that record, resolve problems inside the after-sales window, and consolidate only accepted items. This process takes a little longer before payment but saves far more time than untangling an ambiguous order later.",
        "An index should reduce discovery friction, not remove judgement. Prices, stock, seller behaviour and route eligibility change. Rechecking the current product page is therefore part of every purchase, even when the link worked perfectly last week. The most valuable spreadsheet user is not the person who opens the most links; it is the person who keeps a clear evidence trail and knows exactly why each item belongs in the parcel."
      ] }
    ],
    takeaway: "Best order of work: define the item → verify the current listing → record the exact variant → estimate the complete cost → inspect warehouse QC → resolve after-sales issues → choose an eligible parcel route."
  },
  {
    standfirst: "QC photographs are most useful when you approach them with a checklist rather than a vague feeling. USFans says purchased items are checked at its warehouse, and many current product pages advertise 3–7 free HD quality-inspection photographs. Those images can reveal visible mistakes before international shipping, but only if you know what each angle can and cannot prove. Build the habit before your first order: preserve the seller reference, decide which differences would justify a return, and inspect promptly after warehouse arrival. That turns QC from passive browsing into a decision tool with a clear purpose and deadline.",
    sections: [
      { heading: "What warehouse QC can genuinely tell you", paragraphs: [
        "A warehouse photograph can confirm the item that arrived, the visible colour, approximate silhouette, quantity, labelled size and obvious damage. It can also reveal uneven print placement, missing hardware, major stains, poor alignment or a product that is plainly different from the ordered variant. That is already valuable: correcting a visible error while the item is in the warehouse is normally more practical than discovering it after an international parcel reaches you.",
        "QC cannot guarantee authenticity, long-term durability, fabric composition, internal construction or a perfect fit. Lighting changes colour; camera distance affects proportions; a folded garment can hide its shape. Treat every image as evidence with limits. The goal is not to convince yourself that the item is flawless. The goal is to identify differences that are visible, material to your decision and still actionable before parcel submission."
      ] },
      { heading: "Prepare a reference before the item arrives", paragraphs: [
        "Good inspection starts at purchase. Save the seller’s main image, the exact selected variant, the size chart and any detail that influenced your choice. If you care about a particular embroidery position, sole colour or pocket design, record it. Without a reference, QC becomes a memory test, and similar products quickly blur together. A small order note makes it possible to compare what was promised with what physically reached the warehouse.",
        "Use objective criteria whenever possible. Replace “I want it oversized” with a target chest width and length. Replace “the logo should look right” with its expected position relative to a seam or pocket. Not every seller provides reliable measurements, but recording what is available exposes gaps before ordering. It also gives you a precise request if an extra warehouse measurement is needed."
      ] },
      { heading: "Inspect clothing in a fixed sequence", paragraphs: [
        "For tops and jackets, begin with the full front and back. Check overall shape, symmetry, colour panels, print or embroidery placement, zipper direction and the number of pockets. Move to the neck and size label, then inspect cuffs, hem, major seams and visible hardware. For trousers, compare waist style, rise, leg shape, pocket placement and hem. If measurements are shown, compare them with the listing’s measurement method rather than assuming two sellers measure in the same way.",
        "Fabric weight and hand-feel are difficult to judge from a photograph, so avoid unsupported conclusions. You can sometimes see thinness against strong light or obvious surface texture, but a camera does not establish material quality. Focus first on discrepancies that can be demonstrated: wrong colour, wrong label, missing feature, visible hole, stain, crooked graphic or measurement outside an acceptable tolerance."
      ] },
      { heading: "Inspect footwear as a pair, not two objects", paragraphs: [
        "Compare the left and right shoe together from the front, sides, heel and top. Look at toe shape, panel alignment, lace placement, sole colour, heel height, stitching paths and symmetry. A tilted camera can create false differences, so use more than one angle before judging. Check the size label against the ordered size and, when fit risk is high, consider whether an insole or outsole measurement is available.",
        "Boxes add volume and can be damaged during domestic delivery without the shoes themselves being affected. Decide whether the box is important before parcel packing. Removing it may reduce volumetric weight, while keeping it may offer structure or collector value. There is no universal right answer; connect the choice to route pricing, protection and your reason for buying."
      ] },
      { heading: "Bags, accessories and small parts", paragraphs: [
        "For bags, check the overall shape, handle symmetry, strap inclusion, closures, corners, lining where visible and the placement of external details. Small accessories require a quantity check: pairs, screws, charms, spare laces or detachable pieces are easy to overlook. Reflective or metallic surfaces can look different under warehouse lights, so compare several images before calling a colour or finish defective.",
        "Electronics, liquids, batteries, magnets and other restricted items also have a logistics dimension. A product can look correct yet reduce the routes available for the entire parcel. Check restrictions before acceptance and consolidation. The platform’s own product notices acknowledge that prohibited or limited goods, line limitations, weight and volume can affect shipping options."
      ] },
      { heading: "Request more evidence only when it changes a decision", paragraphs: [
        "USFans listings commonly advertise 3–7 free HD QC images, which may be sufficient for a straightforward product. Ask for more only when a decision-critical detail is missing: a measurement, serial area, damaged corner, print alignment or the contents of a set. Before requesting a paid service, confirm the current charge and describe the desired angle precisely. “More photos” can produce another unhelpful view; “photograph the inside size label straight-on” is much clearer.",
        "Do not mistake image quantity for inspection quality. Five planned views can be more useful than fifteen random ones. Keep your request short, polite and tied to an action. If the new evidence shows the item meets your tolerance, accept it. If it confirms a material mismatch, begin the applicable after-sales process rather than repeatedly requesting photos that will not change the outcome."
      ] },
      { heading: "Use the five-day return statement carefully", paragraphs: [
        "Many current product pages state that a return application can be made within five days after warehouse arrival and that agents will negotiate with the seller. Check the terms attached to your actual order immediately because seller acceptance, customisation, hygiene rules, domestic return freight and item condition may matter. The statement is a reason to inspect promptly, not a guarantee that every return is free or approved.",
        "A strong issue report names the ordered variant, identifies the visible mismatch, points to the relevant QC image and states the requested resolution. Keep screenshots of the listing and the order selection. This evidence makes the case understandable without emotional language. Do not submit the item in an international parcel while the case is open."
      ] },
      { heading: "The final ten-point QC check", paragraphs: [
        "Before acceptance, confirm: item identity, variant, labelled size, quantity, front view, back view, left-right symmetry, visible damage, included parts and any measurement that controls fit. Then ask one final question: is the remaining uncertainty something another photograph can resolve? If yes, request the specific evidence. If not, decide whether the uncertainty is acceptable or whether the item should be returned under the current terms.",
        "QC works best as a disciplined pause between purchase and shipping. It is neither a guarantee nor a decorative gallery. Used properly, it turns warehouse time into a practical quality-control window and gives you a chance to keep obvious problems out of an expensive international parcel."
      ] }
    ],
    takeaway: "Judge visible facts, compare against a saved reference, request only decision-changing evidence, and act before the applicable after-sales window closes. Review every stored item as soon as its photographs appear, because a disciplined early decision preserves more practical options than a rushed inspection during parcel submission."
  },
  {
    standfirst: "International shipping is not one fixed price attached to an item. It is the result of packed weight, packed volume, destination, route rules, optional services and sometimes local charges. USFans exposes estimation and rehearsal functions, while product pages may show estimated weight, volume and warehouse timing. The smart approach is to plan a parcel as a system rather than chase a single cheap-looking quote. Begin planning while products are still candidates, not after every item is already stored. Early estimates reveal bulky low-value purchases, incompatible restrictions and budgets that depend on unrealistic assumptions. A good plan also keeps room for measurement differences, protective packaging and destination charges. None of these steps predicts the carrier perfectly; together they give you enough evidence to compare realistic options and avoid feeling trapped by the first number shown at parcel submission.",
    sections: [
      { heading: "Understand actual and volumetric weight", paragraphs: [
        "Actual weight is what the packed parcel weighs on a scale. Volumetric weight converts the space occupied by the parcel into a chargeable figure using a divisor set by the carrier or route. A light but large package can therefore cost more than a compact, heavier one. The applicable formula and whether the route charges the greater figure must be checked in the live line details; never assume one divisor works for every country and service.",
        "Product pages can show estimated item weight and dimensions, but those numbers are planning inputs. The final parcel includes consolidation choices, outer packaging and protective material. Boxes, shoe packaging and empty space can increase volume. Compression or removal services may reduce it, while corner protection or extra cushioning may add both weight and dimensions."
      ] },
      { heading: "Estimate before buying the final item", paragraphs: [
        "Start a parcel worksheet while shopping. Record the item price, domestic delivery, estimated weight, estimated dimensions and whether the product may be restricted. Add a buffer because estimates can differ from the warehouse measurement. Once several items are shortlisted, test realistic combinations in the platform’s estimation function. The aim is not an exact forecast; it is to identify obviously inefficient purchases and route conflicts before they become stored inventory.",
        "Bulky low-value products deserve special attention. A large bag, plush item, shoe box or padded jacket can occupy far more chargeable space than its price suggests. Conversely, several compact garments may consolidate efficiently. Compare the expected delivered cost per useful item, not merely the seller price or headline shipping rate."
      ] },
      { heading: "Check eligibility before comparing prices", paragraphs: [
        "The cheapest displayed route is irrelevant if the parcel is not eligible. Current USFans product notices explain that prohibited items, limited goods, logistics restrictions, weight and volume limits can exist. Batteries, liquids, magnets, cosmetics, food, fragile goods and branded or sensitive categories may change the available lines. Rules also vary by destination. Review each item’s restriction status before consolidation and check the live route description again before payment.",
        "Avoid building a mixed parcel that forces ordinary clothing onto a specialised or costly line because of one restricted item. Sometimes separating parcels is sensible; sometimes the extra base charge makes it worse. Compare both scenarios with current eligible lines. There is no fixed “best parcel weight” that applies globally because rate brackets, limits and destination conditions differ."
      ] },
      { heading: "Use rehearsal to replace guesses with a packed estimate", paragraphs: [
        "USFans account navigation publicly includes Parcel, Rehearsal and Estimation functions. Rehearsal is useful when the difference between estimated and packed volume could change the route or cost materially. It can account for consolidation and selected packaging instructions before the final parcel is submitted. Check the current service description and fee in your account, because the available process may change.",
        "Give packaging instructions that reflect the goods. Soft clothing may tolerate compression; structured bags, fragile items and footwear may need support. Removing retail packaging can reduce volume but may also reduce protection or value to you. Choose deliberately. A rehearsal result is more informative than adding raw item weights, yet the final carrier assessment and route terms still control the shipment."
      ] },
      { heading: "Compare routes on more than price", paragraphs: [
        "Build a simple comparison with six fields: chargeable weight, total quoted cost, tracking level, delivery estimate, restriction fit and compensation or insurance terms. Add customs handling or tax collection information when the line provides it. A slightly higher quote may be rational if it has clearer tracking, better eligibility or protection appropriate to the parcel. Equally, paying for speed on a low-value, non-urgent parcel may add little value.",
        "Delivery estimates are ranges, not appointments. Seller dispatch, warehouse processing, parcel preparation, export handling, flights, customs and local delivery all add variability. Avoid publishing or relying on a universal promise. Take a screenshot of the selected line’s current terms and keep the parcel number after submission."
      ] },
      { heading: "Plan for taxes, currency and optional services", paragraphs: [
        "The international freight quote is not always the entire landed cost. Currency conversion, payment provider charges, declared-value rules, destination VAT or customs duties, remote-area fees and optional protection may apply. Which charges are collected in advance depends on the line and destination. Use official customs guidance for your country and the current checkout information; a social-media total from another country is not a reliable forecast for yours.",
        "Insurance or compensation should be read as a contract, not a badge. Check eligible events, excluded goods, evidence requirements, value caps and claim deadlines. Photograph or save QC evidence and parcel records before shipping. Good documentation helps both routine tracking questions and any later claim."
      ] },
      { heading: "Prevent address and declaration mistakes", paragraphs: [
        "Review the recipient’s full name, street, unit number, city, region, postcode, country and phone format before submission. Transliteration rules and character limits may differ by carrier. Make sure the declared description is accurate, understandable and permitted by the line. Do not copy a random declaration from another buyer whose parcel, country and rules are different.",
        "After payment, monitor the parcel record and retain the tracking number. Tracking can pause between export and the first destination scan without proving the parcel is lost. Use the line’s stated process and support channel when the defined time threshold is exceeded. Clear records—order list, QC images, rehearsal result, parcel weight, selected service and payment—make support conversations much faster."
      ] },
      { heading: "A practical parcel budget", paragraphs: [
        "Create three numbers before shipping: an optimistic estimate, a working budget and a maximum acceptable delivered cost. The working budget should use realistic packed weight and volume plus known fees. The maximum tells you when to remove an item, change packaging, split the parcel or stop. This prevents the common situation in which buyers feel forced to pay an unattractive quote because every item is already stored.",
        "Recalculate after QC and before final submission. Confirm that every accepted item is included, rejected items are excluded, packaging instructions are correct and the chosen route remains eligible. Shipping decisions improve when they are made early, compared on complete terms and checked again against the actual packed parcel."
      ] }
    ],
    takeaway: "Estimate early, screen for restrictions, rehearse when volume matters, compare eligible routes on complete terms, and keep a buffer for packaging and destination charges. Reopen the live quote immediately before payment: stored inventory, route availability, exchange rates and carrier conditions can change between the first estimate and final parcel submission. Preserve the final route terms, parcel measurements and payment record together so later tracking questions or claims begin with a complete, dated evidence set."
  }
];

const es: ArticleContent[] = [
  {
    standfirst: "Un índice de productos USFans útil no es un catálogo mágico ni demuestra que un vendedor, precio o variante siga disponible. Su valor real es ahorrar tiempo: permite pasar de una idea general a una ficha que puedes verificar. Esta guía propone un método repetible para buscar, comparar y documentar cada producto antes de pagar.",
    sections: [
      { heading:"Empieza por la intención, no por desplazarte sin fin", paragraphs:["Antes de abrir decenas de tarjetas, define categoría, presupuesto aproximado, talla, color, material y detalles irrenunciables. Buscar simplemente «sudadera» genera ruido; buscar una sudadera gruesa con cremallera, gris oscuro y medidas publicadas permite descartar rápido las fichas débiles. El índice ordena enlaces, pero no puede decidir si una prenda encaja con tu cuerpo, clima o expectativas.","Crea una lista corta y abre la ficha actual de cada candidato. USFans se presenta públicamente como agente para compras de Taobao, 1688 y Weidian, por lo que la publicación de origen sigue siendo decisiva: el vendedor puede cambiar precio, fotos, variantes o stock. Guarda nombre, opción elegida y los detalles en los que basaste la compra."],bullets:["Define categoría, presupuesto, talla y detalles imprescindibles.","Primero crea una lista corta; después verifica la ficha vigente.","Registra color, talla y opción exacta antes de comprar."]},
      { heading:"Lee la ficha como una especificación", paragraphs:["El título es una etiqueta, no una descripción completa. Revisa variantes, tabla de tallas, materiales, fotografías, entrega nacional y avisos del agente. Si existen diferentes lotes o versiones, no supongas que el más caro es automáticamente mejor: busca diferencias medibles y pide aclaración cuando la distinción sea imprecisa.","Las fichas indexadas pueden mostrar tiempo estimado al almacén, peso y dimensiones. Son señales de planificación, no garantías. El peso y el volumen conectan la compra con el envío internacional: un artículo barato puede dejar de serlo si es voluminoso, conserva un embalaje pesado o solo admite rutas limitadas."]},
      { heading:"Separa las capas de coste", paragraphs:["Considera al menos precio del producto, entrega nacional al almacén y transporte internacional. Conversión de moneda, servicios opcionales, embalaje e impuestos de destino pueden añadir coste. Lleva un total por artículo y otra estimación para el paquete; así sabrás si un accesorio barato mejora realmente el pedido o solo incrementa el peso facturable.","No presentes una estimación inicial como precio final. La ruta puede cobrar peso real o volumétrico. Quitar embalaje reduce volumen; proteger añade peso y medidas. La mejor pregunta no es cuál línea parece más barata, sino cuál línea elegible ofrece un equilibrio aceptable entre coste, seguimiento, límites y protección."]},
      { heading:"Convierte la llegada al almacén en una puerta de control", paragraphs:["USFans indica en fichas actuales que los artículos se envían al almacén, se revisan y se fotografían. Muchas anuncian además entre 3 y 7 fotos HD de inspección gratuitas. Compara esas imágenes con la variante guardada: color, forma, marca visible, etiqueta de talla, cantidad y daños evidentes deben coincidir.","No apruebes por un solo ángulo atractivo. Amplía laterales, costuras, impresión, herrajes, etiquetas y proporciones. Si falta un detalle esencial, solicita una foto o medida concreta y comprueba antes el coste vigente. El QC no autentica ni descubre todos los fallos internos; es un control visual para detectar discrepancias visibles mientras el artículo sigue en China."]},
      { heading:"Actúa dentro del plazo posventa", paragraphs:["Muchas fichas actuales señalan que, tras la llegada al almacén, se puede solicitar devolución dentro de cinco días y que el agente negociará con el vendedor. Es una ventana estrecha, no una promesa incondicional. Política del vendedor, personalización, higiene, transporte de devolución y estado del artículo pueden alterar el resultado.","Describe el problema con precisión. «Se ve mal» ayuda poco; «pedí XL y la etiqueta fotografiada muestra M» es accionable. Adjunta la referencia de la ficha e identifica la foto. Mantén el artículo fuera del paquete hasta que termine la decisión de devolución, cambio o aceptación."]},
      { heading:"Consolida solo artículos aprobados", paragraphs:["Asigna a cada artículo un estado: aceptar, preguntar, devolver o esperar. Comprueba restricciones antes de mezclar baterías, líquidos, imanes, artículos frágiles o cajas grandes con ropa corriente. Las propias fichas advierten de mercancías prohibidas o limitadas y de límites logísticos, de peso y de volumen.","Usa Estimation y Rehearsal cuando aparezcan en tu cuenta. El ensayo puede acercar el peso y tamaño del paquete final, pero mandan las opciones y tarifas vigentes al crear el envío. Revisa destinatario, país, código postal y teléfono. Una buena selección se desperdicia con una dirección incorrecta."]},
      { heading:"Un flujo que puedes repetir", paragraphs:["Empieza con diez candidatos, elimina los de variantes confusas o medidas débiles, compara tres o cuatro por coste total probable y registra la opción exacta antes de comprar. Al llegar, compara QC con ese registro, resuelve incidencias dentro del plazo y consolida solo lo aceptado.","Un índice reduce fricción, no sustituye el juicio. Precio, stock, comportamiento del vendedor y elegibilidad cambian. El usuario más eficaz no abre más enlaces: conserva evidencias claras y sabe por qué cada artículo merece ocupar espacio en el paquete."]}
    ], takeaway:"Orden recomendado: definir → verificar ficha vigente → registrar variante → estimar coste completo → revisar QC → resolver incidencias → elegir ruta elegible."
  },
  {
    standfirst:"Las fotografías QC resultan útiles cuando se revisan con una lista, no con una sensación. USFans afirma que revisa los artículos en el almacén y muchas fichas anuncian entre 3 y 7 fotografías HD gratuitas. Pueden revelar errores visibles antes del envío internacional, siempre que entiendas qué puede demostrar cada ángulo. La revisión debe hacerse nada más aparecer el artículo en el almacén: guarda la ficha vigente, compara la opción elegida y anota por escrito cualquier diferencia. Así distingues una preferencia subjetiva de un error verificable y conservas tiempo para preguntar o iniciar una solicitud posventa.",
    sections:[
      {heading:"Qué puede demostrar realmente el QC",paragraphs:["Una foto puede confirmar identidad, color visible, silueta aproximada, cantidad, talla etiquetada y daños obvios. También puede mostrar impresión descentrada, herrajes ausentes, manchas, asimetría o una variante equivocada. Corregirlo en el almacén suele ser más práctico que descubrirlo tras el transporte internacional.","No garantiza autenticidad, durabilidad, composición interna ni ajuste perfecto. La luz cambia el color y la distancia altera proporciones. Cada imagen es evidencia limitada: busca diferencias visibles, importantes para tu decisión y todavía solucionables."]},
      {heading:"Prepara una referencia antes de la llegada",paragraphs:["Guarda imagen principal, variante exacta, tabla de tallas y detalles decisivos. Si te importa la posición de un bordado, el color de la suela o un bolsillo, anótalo. Sin referencia, el QC se convierte en una prueba de memoria.","Prefiere criterios objetivos: ancho de pecho y largo en lugar de «oversize»; posición respecto a una costura en lugar de «logo correcto». Registrar lo disponible descubre lagunas antes de pagar y permite pedir una medida concreta después."]},
      {heading:"Ropa: revisa siempre en el mismo orden",paragraphs:["Empieza por frontal y espalda completos. Comprueba forma, simetría, paneles, estampado, cremallera y bolsillos. Continúa por cuello, etiqueta, puños, bajo, costuras y herrajes. En pantalones revisa cintura, tiro, pierna, bolsillos y dobladillo.","El gramaje y el tacto no se demuestran bien en cámara. Concéntrate en discrepancias demostrables: color o talla equivocados, piezas ausentes, agujeros, manchas, gráfico torcido o medida fuera de tolerancia."]},
      {heading:"Calzado: compara el par",paragraphs:["Mira ambos zapatos juntos desde frente, laterales, talón y parte superior. Compara puntera, paneles, cordones, suela, altura, costuras y simetría. Un ángulo inclinado puede crear diferencias falsas; usa varias vistas. Confirma etiqueta de talla y, si el ajuste es crítico, una medida de plantilla o suela.","La caja añade volumen y puede dañarse sin afectar al calzado. Decide antes si tiene valor para ti. Quitarla puede reducir peso volumétrico; conservarla aporta estructura. Relaciona la decisión con coste, protección y motivo de compra."]},
      {heading:"Bolsos, accesorios y piezas pequeñas",paragraphs:["En bolsos revisa forma, asas, correa, cierres, esquinas, forro visible y detalles exteriores. En accesorios cuenta pares, tornillos, charms, cordones o piezas desmontables. Superficies metálicas cambian bajo luz de almacén, así que compara varias imágenes.","Baterías, líquidos, imanes y mercancía limitada añaden un problema logístico. Aunque se vean correctos, pueden reducir rutas para todo el paquete. Comprueba restricciones antes de aceptar y consolidar."]},
      {heading:"Pide evidencia adicional solo si cambia la decisión",paragraphs:["Entre 3 y 7 imágenes pueden bastar para un producto sencillo. Pide más cuando falta algo decisivo: medida, esquina dañada, alineación o contenido de un set. Confirma el coste vigente y describe el ángulo exacto; «foto frontal recta de la etiqueta interior» funciona mejor que «más fotos».","La cantidad no equivale a calidad. Cinco vistas planificadas superan quince aleatorias. Si la nueva evidencia confirma un fallo material, inicia posventa en vez de acumular fotografías que no cambiarán la decisión."]},
      {heading:"Usa con cuidado la mención de cinco días",paragraphs:["Las fichas suelen mencionar solicitud de devolución dentro de cinco días tras la llegada y negociación del agente con el vendedor. Revisa enseguida las condiciones de tu pedido: aceptación del vendedor, personalización, higiene, portes y estado pueden influir.","Un informe sólido identifica variante pedida, discrepancia visible, imagen relevante y solución solicitada. Guarda capturas y no envíes internacionalmente el artículo mientras el caso esté abierto."]},
      {heading:"Comprobación final de diez puntos",paragraphs:["Confirma identidad, variante, talla, cantidad, frontal, espalda, simetría, daños, piezas incluidas y medidas clave. Después pregunta si una foto adicional puede resolver la incertidumbre. Si no, decide si aceptas el riesgo o solicitas devolución según las condiciones.","Antes de cerrar la decisión, separa tres resultados: aceptar, pedir una prueba concreta o abrir una incidencia. Acepta cuando la evidencia coincide con tu referencia y el riesgo restante es razonable. Pide una medida o ángulo si esa única prueba cambiaría la decisión. Abre incidencia cuando la imagen demuestra talla, color, cantidad, daño o variante incorrectos. Guarda capturas, número de pedido y fecha de llegada; una descripción breve y objetiva ayuda más que un mensaje genérico. No añadas el artículo al paquete mientras la solicitud siga abierta.","El QC es una pausa disciplinada entre compra y envío. No es garantía ni galería decorativa: convierte el tiempo de almacén en una oportunidad real para mantener problemas evidentes fuera de un paquete caro."]}
    ],takeaway:"Juzga hechos visibles, compara con una referencia guardada, pide solo evidencia que cambie la decisión y actúa antes de cerrar el plazo posventa."
  },
  {
    standfirst:"Enviar un paquete USFans a España no tiene un precio fijo ligado al producto. Depende del peso embalado, el volumen, la línea disponible, el destino concreto y los cargos de importación. Esta guía, revisada el 13 de agosto de 2026, separa el cálculo logístico de las reglas españolas de IVA y aduanas y distingue Península, Baleares, Canarias, Ceuta y Melilla.",
    sections:[
      {heading:"Peso real y peso volumétrico",paragraphs:["El peso real sale de la báscula. El volumétrico convierte el espacio ocupado en una cifra facturable mediante un divisor de la ruta. Un paquete ligero y grande puede costar más que otro compacto y pesado. Revisa la fórmula viva de cada línea y si cobra la cifra mayor.","Los datos del producto son entradas de planificación. El paquete final incluye consolidación, caja exterior y protección. Cajas y huecos aumentan volumen; compresión o retirada lo reducen; refuerzos añaden peso y medidas."]},
      {heading:"Estima antes del último artículo",paragraphs:["Registra precio, transporte nacional, peso y dimensiones estimados y posibles restricciones. Añade margen porque el almacén puede medir diferente. Prueba combinaciones realistas en Estimation para detectar compras ineficientes y conflictos de ruta antes de tener inventario almacenado.","Los objetos voluminosos y baratos requieren especial cuidado. Cajas de zapatos, peluches, bolsos y chaquetas acolchadas ocupan más espacio del que su precio sugiere. Compara coste entregado por artículo útil, no solo precio del vendedor."]},
      {heading:"Primero elegibilidad, después precio",paragraphs:["La ruta más barata no sirve si el paquete no es elegible. Las fichas reconocen mercancías prohibidas o limitadas y límites de logística, peso y volumen. Baterías, líquidos, imanes, cosmética, comida, artículos frágiles o sensibles pueden cambiar las líneas disponibles.","No dejes que un solo producto fuerce toda la ropa a una línea especial cara. A veces dividir funciona y otras el nuevo cargo base empeora el total. Compara ambos escenarios con las líneas vigentes. No existe un peso perfecto universal."]},
      {heading:"Usa Rehearsal para sustituir conjeturas",paragraphs:["La navegación pública de USFans incluye Parcel, Rehearsal y Estimation. El ensayo es útil cuando el volumen embalado puede cambiar el precio o la elegibilidad. Comprueba descripción y tarifa actuales porque el proceso puede variar.","Da instrucciones adecuadas: ropa blanda admite compresión; bolsos estructurados, frágiles y calzado pueden necesitar soporte. Quitar embalaje reduce volumen, pero también protección o valor. Decide con intención."]},
      {heading:"Compara rutas con seis campos",paragraphs:["Anota peso facturable, coste total, seguimiento, plazo estimado, ajuste de restricciones y compensación o seguro. Añade información fiscal o aduanera cuando la línea la ofrezca. Una opción algo más cara puede ser racional si protege mejor un paquete valioso.","Los plazos son rangos. Despacho del vendedor, almacén, preparación, exportación, vuelos, aduana y reparto generan variación. Guarda las condiciones de la línea y el número del paquete."]},
      {heading:"Península y Baleares: calcula el coste entregado",paragraphs:["Para una dirección peninsular o balear, separa producto, transporte interno en China, envío internacional, IVA, aranceles y posibles gastos de gestión del transportista. No copies el total publicado por otro comprador: una diferencia de código postal, línea, peso embalado o momento de compra puede alterar tanto las opciones como el importe.","La Agencia Tributaria explica que, para compras enviadas desde fuera de la Unión Europea, el IVA puede haberse cobrado mediante IOSS o puede ser exigido por el transportista antes de la entrega, junto con gastos de gestión. Comprueba en el pago qué conceptos están incluidos y conserva la factura o justificante." ]},
      {heading:"Canarias, Ceuta y Melilla no son un simple cambio de código postal",paragraphs:["No des por hecho que una tarifa para Madrid o Barcelona sirve para Canarias, Ceuta o Melilla. Estos territorios tienen particularidades fiscales y aduaneras y algunas líneas no los admiten o los tratan como destinos separados. Confirma que la línea acepta el destino exacto antes de consolidar y evita presentar una estimación peninsular como presupuesto local.","Para Baleares también conviene revisar recargos de zona, límites de la línea y entrega de última milla. El nombre del país no basta: introduce provincia, isla, localidad y código postal reales en la herramienta vigente para comparar solo opciones utilizables." ]},
      {heading:"IVA y nuevo arancel para envíos de hasta 150 euros",paragraphs:["La Agencia Tributaria indica que desde el 1 de julio de 2026 las compras por Internet de hasta 150 euros cuya mercancía se encuentre fuera de la UE pagan, además del IVA aplicable, un arancel fijo de 3 euros por cada categoría de artículos. El lugar desde el que se envía la mercancía es determinante; un dominio .es o precios en euros no convierten un envío extracomunitario en europeo.","La misma guía oficial señala que la plataforma puede cobrar el arancel al comprar o que el transportista puede exigirlo antes de entregar. También advierte que el arancel no se devuelve por una devolución ordinaria, salvo que se justifique mercancía defectuosa o incumplimiento contractual. Estas reglas no son una invitación a alterar valores o descripciones: la declaración debe ser correcta, comprensible y compatible con la línea." ]},
      {heading:"Ejemplo de presupuesto en euros, no de tarifa garantizada",paragraphs:["Imagina 82 euros de productos, 7 euros de transporte interno, 36 euros de envío internacional estimado y 4 euros de embalaje. El subtotal logístico sería 129 euros antes de los conceptos de importación o gestión. Si el envío entra en las reglas de bajo valor, revisa si el IVA y el nuevo arancel por categorías ya aparecen incluidos; si no, reserva margen para el cobro del transportista.","El ejemplo solo enseña el orden de cálculo. No representa una tarifa de USFans ni una liquidación aduanera: el número de categorías, el valor admitido, el régimen de IVA, el destino y los gastos del operador cambian el total. Repite el cálculo con el paquete ensayado y con la información que muestre la línea el día del pago." ]},
      {heading:"Moneda, protección y fuentes comprobadas",paragraphs:["El flete puede no ser todo el coste entregado. Conversión, proveedor de pago, servicios opcionales, zona remota y protección pueden aplicarse. Lee el seguro como contrato: eventos cubiertos, exclusiones, pruebas, límites y plazos deben corresponder al contenido del paquete.","Información fiscal comprobada el 13 de agosto de 2026 en la guía pública de la Agencia Estatal de Administración Tributaria «Envíos por un valor de hasta 150 euros». Funciones de estimación, ensayo, fotografías QC y ventana de solicitud de devolución contrastadas con páginas públicas de USFans. Verifica de nuevo ambas fuentes antes de pagar porque tarifas, líneas y procedimientos pueden cambiar." ]},
      {heading:"Evita errores de dirección y declaración",paragraphs:["Revisa nombre, calle, unidad, ciudad, región, código postal, país y teléfono. Las reglas de caracteres cambian por transportista. La descripción declarada debe ser correcta, comprensible y permitida; no copies la declaración aleatoria de otro comprador.","Después del pago guarda tracking. Una pausa entre exportación y primer escaneo local no demuestra pérdida. Sigue el proceso de la línea cuando supere el umbral definido y aporta registros claros."]},
      {heading:"Crea un presupuesto de paquete",paragraphs:["Define estimación optimista, presupuesto de trabajo y coste máximo aceptable. El presupuesto usa peso y volumen realistas más cargos conocidos; el máximo indica cuándo quitar un artículo, cambiar embalaje, dividir o detenerse.","Recalcula tras el QC y antes de enviar. Confirma que solo están los aceptados, instrucciones correctas y ruta elegible. Las mejores decisiones se toman pronto y se validan contra el paquete realmente embalado."]}
    ],takeaway:"Estima pronto, filtra restricciones, ensaya si importa el volumen, compara solo rutas elegibles y conserva margen para embalaje y cargos de destino."
  }
];

type CompactArticle = { standfirst:string; headings:string[]; bodies:string[]; takeaway:string };
const splitLocalizedBody = (body:string) => {
  const sentences = body.match(/[^.!?。！？]+[.!?。！？]+|[^.!?。！？]+$/g)?.map(item=>item.trim()).filter(Boolean) || [body];
  if(sentences.length > 1){
    const middle = Math.ceil(sentences.length / 2);
    return [sentences.slice(0,middle).join(" "),sentences.slice(middle).join(" ")];
  }
  const pivot = Math.max(body.indexOf(";"),body.indexOf("，"),body.indexOf(","));
  return pivot > 25 ? [body.slice(0,pivot+1).trim(),body.slice(pivot+1).trim()] : [body,""];
};
const buildLocalized = (lang:Lang, items: CompactArticle[]): ArticleContent[] => items.map((item,articleIndex) => ({
  standfirst:item.standfirst,
  takeaway:item.takeaway,
  sections:item.headings.map((heading,index)=>{
    const [lead,follow] = splitLocalizedBody(item.bodies[index]);
    const depth = [localizedDepth[lang]?.[articleIndex]?.[index],localizedDepthExtra[lang]?.[articleIndex]?.[index],localizedDepthFinal[lang]?.[articleIndex]?.[index]].filter(Boolean).join(" ");
    return {heading,paragraphs:[lead,[follow,depth].filter(Boolean).join(" ")],bullets:articleIndex===0&&index===0?item.bodies.slice(0,3):undefined};
  })
}));

const fr = buildLocalized("fr", [
  {standfirst:"Un index USFans sert à trouver plus vite une fiche vérifiable, pas à garantir le stock ou le vendeur. Voici une méthode fondée sur les informations actuellement visibles sur USFans.",headings:["Définir l’achat","Vérifier la fiche actuelle","Calculer le coût complet","Contrôler à l’entrepôt","Agir pendant le SAV","Consolider avec méthode","Flux répétable"],bodies:["Notez catégorie, budget, taille, couleur et critères essentiels. Faites une liste courte au lieu de parcourir sans fin.","USFans achète sur Taobao, 1688 et Weidian. Ouvrez la fiche en cours, vérifiez variantes et mesures, puis conservez la référence exacte car prix et stock changent.","Séparez prix produit, livraison chinoise et transport international. Poids, volume, emballage, conversion et taxes peuvent modifier le total livré.","De nombreuses fiches annoncent 3 à 7 photos QC HD gratuites. Comparez couleur, taille, quantité, forme et dommages avec votre référence; le QC reste un contrôle visuel, pas une authentification.","Des fiches indiquent une demande de retour sous cinq jours après l’arrivée et une négociation avec le vendeur. Vérifiez les conditions de votre commande et signalez un écart précis immédiatement.","N’ajoutez au colis que les articles acceptés. Contrôlez les restrictions, puis utilisez Estimation ou Rehearsal si disponibles avant de confirmer adresse et ligne.","Définir, vérifier, enregistrer, estimer, contrôler le QC, résoudre les problèmes et choisir une ligne admissible: ce rythme évite les décisions improvisées."],takeaway:"L’index accélère la recherche; la fiche actuelle, le QC et les conditions de la ligne restent les sources de décision."},
  {standfirst:"Les photos QC peuvent éviter d’expédier une erreur visible, mais seulement avec une référence et une liste de contrôle.",headings:["Limites du QC","Préparer la référence","Vêtements","Chaussures","Sacs et accessoires","Photos supplémentaires","Fenêtre de retour","Contrôle final"],bodies:["Le QC montre identité, couleur visible, quantité, taille et dommages évidents. Il ne prouve ni authenticité, matière interne, durabilité ni ajustement parfait.","Sauvegardez la variante, le guide des tailles et les détails importants avant l’achat. Utilisez des mesures et positions objectives plutôt qu’une impression générale.","Inspectez face, dos, symétrie, imprimé, fermetures, poches, étiquette, poignets et coutures dans un ordre fixe. Concentrez-vous sur les différences démontrables.","Comparez les deux chaussures sous plusieurs angles, vérifiez l’étiquette et demandez une mesure de semelle si le risque de taille est important. Décidez aussi si la boîte mérite son volume.","Vérifiez forme, poignées, sangle, fermetures, coins, quantité et petites pièces. Batteries, liquides ou aimants peuvent aussi limiter les routes.","Demandez une vue précise uniquement si elle peut changer la décision et contrôlez le tarif actuel. Cinq vues utiles valent mieux que quinze images aléatoires.","Inspectez dès l’arrivée. Les cinq jours mentionnés sur de nombreuses fiches restent soumis au vendeur, au type d’article, à son état et au fret de retour.","Confirmez identité, variante, taille, quantité, vues, symétrie, dommages, pièces et mesures avant d’accepter ou de lancer le SAV."],takeaway:"Comparez aux preuves sauvegardées et agissez tant que la solution reste possible en Chine."},
  {standfirst:"Le coût international dépend du poids emballé, du volume, de la destination, des restrictions et des services, pas seulement du poids de l’article.",headings:["Poids réel et volumétrique","Estimer tôt","Admissibilité","Rehearsal","Comparer les lignes","Taxes et protection","Adresse et déclaration","Budget final"],bodies:["Le poids volumétrique transforme l’espace en poids facturable. Vérifiez la formule et la règle de la ligne active; les dimensions produit ne sont qu’une estimation.","Enregistrez prix, livraison locale, poids, volume et restriction dès la sélection. Testez plusieurs combinaisons et surveillez les objets volumineux bon marché.","La ligne la moins chère ne compte pas si le colis est refusé. Vérifiez marchandises limitées, poids, volume et destination avant consolidation.","Le menu USFans inclut Estimation et Rehearsal. Un essai peut donner une taille emballée plus réaliste; adaptez compression ou protection aux produits.","Comparez coût, poids facturable, suivi, délai, restrictions et compensation. Les délais restent des fourchettes influencées par export, douane et livraison locale.","Prévoyez conversion, paiement, TVA ou douane, zone éloignée et services optionnels. Lisez exclusions et preuves de toute assurance.","Contrôlez nom, rue, unité, ville, code postal, pays, téléphone et description déclarée. Gardez QC, poids, ligne, paiement et suivi.","Fixez estimation optimiste, budget réaliste et plafond acceptable, puis recalculez après QC avant la soumission finale."],takeaway:"Estimez tôt, filtrez les restrictions et comparez uniquement des lignes réellement admissibles."}
]);

const de = buildLocalized("de", [
  {standfirst:"Ein USFans-Index beschleunigt die Suche, garantiert aber weder Bestand noch Verkäufer. Diese Methode stützt sich auf aktuell überprüfbare USFans-Angaben.",headings:["Kaufziel festlegen","Aktuelles Angebot prüfen","Gesamtkosten trennen","Lager als Prüfstufe","Rechtzeitig handeln","Sinnvoll bündeln","Wiederholbarer Ablauf"],bodies:["Definiere Kategorie, Budget, Größe, Farbe und unverzichtbare Details, bevor du viele Links öffnest.","USFans vermittelt Käufe bei Taobao, 1688 und Weidian. Prüfe Varianten und Maße im aktuellen Angebot und speichere die genaue Auswahl, da Preis und Bestand wechseln können.","Trenne Produktpreis, Inlandversand und internationalen Versand. Volumen, Verpackung, Umrechnung und Einfuhrkosten können den Endbetrag verändern.","Viele Angebote nennen 3–7 kostenlose HD-QC-Fotos. Vergleiche Farbe, Größe, Menge, Form und Schäden; QC ist eine Sichtprüfung, keine Echtheitsgarantie.","Viele Seiten nennen fünf Tage für einen Rückgabeantrag nach Lagereingang und eine Verhandlung mit dem Verkäufer. Prüfe die Bedingungen der konkreten Bestellung sofort.","Bündle nur akzeptierte Artikel. Prüfe Beschränkungen und nutze Estimation oder Rehearsal, wenn verfügbar, bevor Adresse und Versandlinie bestätigt werden.","Ziel definieren, Angebot prüfen, Variante dokumentieren, Gesamtkosten schätzen, QC kontrollieren, Probleme lösen und eine zulässige Linie wählen."],takeaway:"Der Index spart Suchzeit; aktuelles Angebot, QC und Linienbedingungen bestimmen die Entscheidung."},
  {standfirst:"QC-Fotos helfen, sichtbare Fehler vor dem internationalen Versand zu erkennen—mit Referenz und fester Prüfliste.",headings:["Aussagekraft und Grenzen","Referenz vorbereiten","Kleidung prüfen","Schuhe prüfen","Taschen und Zubehör","Zusatzfotos","Rückgabefenster","Letzte Kontrolle"],bodies:["QC zeigt Identität, sichtbare Farbe, Menge, Etikettengröße und klare Schäden. Material, Haltbarkeit, Echtheit und perfekte Passform werden nicht bewiesen.","Speichere Variante, Größentabelle und kaufentscheidende Details. Nutze Maße und konkrete Positionen statt eines bloßen Eindrucks.","Prüfe Vorderseite, Rückseite, Symmetrie, Druck, Reißverschluss, Taschen, Etikett, Bündchen und Nähte in fester Reihenfolge.","Vergleiche beide Schuhe aus mehreren Winkeln, kontrolliere das Größenetikett und erwäge bei hohem Passformrisiko eine Innen- oder Außensohlenmessung.","Kontrolliere Form, Griffe, Riemen, Verschlüsse, Ecken, Stückzahl und Kleinteile. Batterien, Flüssigkeiten und Magnete können Versandwege begrenzen.","Fordere nur ein entscheidungsrelevantes Detailbild an und prüfe vorher die aktuelle Gebühr. Präzise Anweisungen liefern bessere Ergebnisse.","Prüfe sofort nach Ankunft. Die häufig genannten fünf Tage hängen weiterhin von Verkäuferregeln, Artikelart, Zustand und Rücksendekosten ab.","Bestätige Identität, Variante, Größe, Menge, Ansichten, Symmetrie, Schäden, Zubehör und kritische Maße."],takeaway:"Mit gespeicherter Referenz vergleichen und handeln, solange eine Lösung in China möglich ist."},
  {standfirst:"Internationale Versandkosten entstehen aus Packgewicht, Volumen, Ziel, Einschränkungen und Leistungen—nicht nur aus dem Artikelgewicht.",headings:["Ist- und Volumengewicht","Früh schätzen","Zulässigkeit","Rehearsal nutzen","Linien vergleichen","Steuern und Schutz","Adresse und Deklaration","Paketbudget"],bodies:["Volumengewicht bewertet den belegten Raum. Prüfe Formel und Abrechnungsregel der aktuellen Linie; Produktmaße bleiben Planwerte.","Notiere Preis, Inlandversand, geschätztes Gewicht, Volumen und Einschränkungen. Teste Kombinationen und beobachte sperrige Billigartikel besonders.","Die billigste Linie hilft nicht, wenn das Paket unzulässig ist. Prüfe eingeschränkte Waren, Gewichts- und Volumengrenzen sowie das Zielland vor dem Bündeln.","USFans zeigt Estimation und Rehearsal im Konto. Eine Probe kann realistischere Packmaße liefern; passe Kompression und Schutz an den Inhalt an.","Vergleiche abrechenbares Gewicht, Gesamtpreis, Tracking, Zeitrahmen, Beschränkungen und Entschädigung. Lieferzeiten sind keine festen Termine.","Plane Umrechnung, Zahlungsgebühren, Mehrwertsteuer oder Zoll, entlegene Gebiete und optionale Leistungen ein. Lies Versicherungsbedingungen vollständig.","Prüfe Name, Straße, Einheit, Ort, Postleitzahl, Land, Telefon und zulässige Deklaration. Bewahre QC- und Versanddaten auf.","Lege optimistische Schätzung, Arbeitsbudget und Kostengrenze fest und rechne nach QC vor der Zahlung neu."],takeaway:"Früh schätzen, Beschränkungen filtern und nur tatsächlich nutzbare Linien vergleichen."}
]);

const it = buildLocalized("it", [
  {standfirst:"Un indice USFans velocizza la ricerca ma non garantisce disponibilità o affidabilità del venditore. Ecco un metodo basato su dati verificabili della piattaforma.",headings:["Definisci l’obiettivo","Verifica la scheda attuale","Separa i costi","Usa il magazzino come controllo","Agisci in tempo","Consolida con criterio","Flusso ripetibile"],bodies:["Prima di aprire molti link, definisci categoria, budget, taglia, colore e dettagli indispensabili.","USFans acquista da Taobao, 1688 e Weidian. Controlla varianti e misure nella scheda corrente e salva l’opzione esatta perché prezzo e stock cambiano.","Distingui prezzo del prodotto, spedizione nazionale e spedizione internazionale. Volume, imballaggio, conversione e imposte possono cambiare il totale.","Molte schede promettono 3–7 foto QC HD gratuite. Confronta colore, taglia, quantità, forma e danni; il QC è visivo e non certifica autenticità.","Molte pagine citano cinque giorni dall’arrivo per chiedere un reso, con negoziazione dell’agente. Verifica subito i termini dell’ordine specifico.","Inserisci nel pacco solo articoli accettati. Controlla restrizioni e usa Estimation o Rehearsal quando disponibili prima di confermare indirizzo e linea.","Definisci, verifica, registra, stima, controlla il QC, risolvi i problemi e scegli una linea idonea."],takeaway:"L’indice fa risparmiare tempo; scheda attuale, QC e condizioni di spedizione guidano la decisione."},
  {standfirst:"Le foto QC evitano errori visibili prima della spedizione internazionale solo se usi un riferimento e una checklist.",headings:["Cosa prova il QC","Prepara il riferimento","Abbigliamento","Calzature","Borse e accessori","Foto aggiuntive","Finestra di reso","Controllo finale"],bodies:["Il QC mostra identità, colore visibile, quantità, taglia e danni evidenti. Non prova materiale interno, durata, autenticità o vestibilità perfetta.","Salva variante, tabella taglie e dettagli decisivi. Preferisci misure e posizioni oggettive a impressioni generiche.","Controlla fronte, retro, simmetria, stampa, zip, tasche, etichetta, polsini e cuciture sempre nello stesso ordine.","Confronta entrambe le scarpe da più angoli, verifica l’etichetta e, se necessario, richiedi una misura della soletta o suola.","Verifica forma, manici, tracolla, chiusure, angoli, quantità e piccoli pezzi. Batterie, liquidi e magneti possono limitare le linee.","Richiedi solo l’immagine che può cambiare la decisione e controlla prima il costo attuale. Un’istruzione precisa produce prove migliori.","Ispeziona subito: i cinque giorni spesso indicati dipendono comunque dal venditore, dal tipo di prodotto, dallo stato e dal costo di ritorno.","Conferma identità, variante, taglia, quantità, viste, simmetria, danni, accessori e misure critiche."],takeaway:"Confronta prove salvate e agisci mentre il problema può ancora essere gestito in Cina."},
  {standfirst:"Il costo internazionale dipende da peso imballato, volume, destinazione, limiti e servizi, non soltanto dal peso dell’articolo.",headings:["Peso reale e volumetrico","Stima in anticipo","Idoneità","Usa Rehearsal","Confronta le linee","Tasse e protezione","Indirizzo e dichiarazione","Budget finale"],bodies:["Il peso volumetrico converte lo spazio occupato in peso fatturabile. Verifica formula e regola della linea attiva; i dati prodotto sono stime.","Registra prezzo, spedizione interna, peso, volume e restrizioni. Prova combinazioni e presta attenzione agli articoli economici ma ingombranti.","La linea più economica è inutile se il pacco non è idoneo. Controlla merci limitate, peso, volume e destinazione prima della consolidazione.","USFans include Estimation e Rehearsal. Una prova può fornire misure imballate più realistiche; adatta compressione e protezione al contenuto.","Confronta peso fatturabile, costo, tracking, intervallo di consegna, restrizioni e compensazione. Le tempistiche non sono appuntamenti garantiti.","Considera conversione, pagamento, IVA o dogana, zone remote e servizi opzionali. Leggi esclusioni e prove richieste dall’assicurazione.","Verifica nome, via, interno, città, CAP, paese, telefono e dichiarazione consentita. Conserva QC, peso, linea, pagamento e tracking.","Fissa stima ottimistica, budget realistico e limite massimo, poi ricalcola dopo il QC prima dell’invio."],takeaway:"Stima presto, filtra le restrizioni e confronta soltanto linee realmente utilizzabili."}
]);

const pl = buildLocalized("pl", [
  {standfirst:"Indeks USFans przyspiesza wyszukiwanie, ale nie gwarantuje stanu ani sprzedawcy. Poniższy proces opiera się na sprawdzalnych informacjach platformy.",headings:["Określ cel","Sprawdź aktualną ofertę","Oddziel koszty","Magazyn jako bramka kontroli","Działaj szybko","Konsoliduj świadomie","Powtarzalny proces"],bodies:["Zanim otworzysz wiele linków, określ kategorię, budżet, rozmiar, kolor i najważniejsze szczegóły.","USFans pośredniczy w zakupach z Taobao, 1688 i Weidian. Sprawdź warianty i wymiary w aktualnej ofercie oraz zapisz dokładny wybór, bo cena i stan mogą się zmienić.","Oddziel cenę produktu, dostawę krajową i wysyłkę międzynarodową. Objętość, opakowanie, przewalutowanie i podatki wpływają na koszt końcowy.","Wiele ofert podaje 3–7 bezpłatnych zdjęć QC HD. Porównaj kolor, rozmiar, ilość, kształt i uszkodzenia; QC jest kontrolą wizualną, nie potwierdzeniem autentyczności.","Wiele stron wspomina pięć dni na wniosek o zwrot po dotarciu do magazynu i negocjacje z sprzedawcą. Natychmiast sprawdź warunki konkretnego zamówienia.","Do paczki dodawaj tylko zaakceptowane rzeczy. Sprawdź ograniczenia i użyj Estimation lub Rehearsal, jeśli są dostępne.","Określ, zweryfikuj, zapisz, oszacuj, sprawdź QC, rozwiąż problem i wybierz dopuszczalną linię."],takeaway:"Indeks oszczędza czas; decyzję opieraj na aktualnej ofercie, QC i warunkach linii."},
  {standfirst:"Zdjęcia QC pomagają zatrzymać widoczny błąd przed wysyłką, jeśli porównujesz je z zapisaną referencją.",headings:["Możliwości i ograniczenia QC","Przygotuj referencję","Odzież","Obuwie","Torby i akcesoria","Dodatkowe zdjęcia","Okno zwrotu","Kontrola końcowa"],bodies:["QC pokazuje tożsamość, widoczny kolor, ilość, oznaczony rozmiar i oczywiste uszkodzenia. Nie dowodzi materiału, trwałości, autentyczności ani idealnego dopasowania.","Zapisz wariant, tabelę rozmiarów i kluczowe detale. Używaj pomiarów oraz konkretnych punktów odniesienia zamiast ogólnego wrażenia.","Sprawdź przód, tył, symetrię, nadruk, zamek, kieszenie, metkę, mankiety i szwy zawsze w tej samej kolejności.","Porównaj oba buty pod kilkoma kątami, sprawdź metkę i w razie dużego ryzyka poproś o pomiar wkładki lub podeszwy.","Sprawdź kształt, uchwyty, pasek, zapięcia, rogi, ilość i drobne części. Baterie, płyny i magnesy mogą ograniczać transport.","Proś tylko o ujęcie, które zmieni decyzję, i wcześniej sprawdź opłatę. Precyzyjne polecenie daje lepszy materiał.","Kontroluj od razu po przyjęciu. Wspominane pięć dni zależy od zasad sprzedawcy, rodzaju produktu, stanu i kosztu zwrotu.","Potwierdź produkt, wariant, rozmiar, ilość, widoki, symetrię, uszkodzenia, dodatki i krytyczne pomiary."],takeaway:"Porównuj z zapisaną ofertą i działaj, dopóki rozwiązanie w Chinach jest możliwe."},
  {standfirst:"Koszt wysyłki zależy od wagi paczki, objętości, kraju, ograniczeń i usług, a nie tylko od masy produktu.",headings:["Waga rzeczywista i gabarytowa","Szacuj wcześnie","Dopuszczalność","Rehearsal","Porównanie linii","Podatki i ochrona","Adres i deklaracja","Budżet paczki"],bodies:["Waga gabarytowa zamienia zajętą przestrzeń na wagę rozliczeniową. Sprawdź wzór aktywnej linii; dane produktu są jedynie wskazówką.","Zapisuj cenę, dostawę krajową, wagę, objętość i ograniczenia. Testuj kombinacje i uważaj na tanie, ale duże rzeczy.","Najtańsza linia nie ma znaczenia, jeśli paczka jest niedopuszczalna. Sprawdź towary ograniczone, limity i kraj przed konsolidacją.","USFans pokazuje Estimation i Rehearsal. Próba może dać realniejsze wymiary po zapakowaniu; dobierz kompresję i ochronę do zawartości.","Porównuj wagę rozliczeniową, koszt, śledzenie, zakres czasu, ograniczenia i odszkodowanie. Termin nie jest gwarantowaną datą.","Uwzględnij przewalutowanie, płatność, VAT lub cło, strefę odległą i usługi. Czytaj wyłączenia ubezpieczenia.","Sprawdź nazwę, ulicę, lokal, miasto, kod, kraj, telefon i dozwoloną deklarację. Zachowaj QC i dokumentację paczki.","Ustal wariant optymistyczny, realny budżet i maksymalny koszt, a po QC przelicz wszystko ponownie."],takeaway:"Szacuj wcześnie, filtruj ograniczenia i porównuj tylko rzeczywiście dostępne linie."}
]);

const pt = buildLocalized("pt", [
  {standfirst:"Um índice USFans acelera a pesquisa, mas não garante stock nem vendedor. Este método usa informações atualmente verificáveis na plataforma.",headings:["Definir a intenção","Confirmar a página atual","Separar custos","Usar o armazém como controlo","Agir a tempo","Consolidar com critério","Fluxo repetível"],bodies:["Defina categoria, orçamento, tamanho, cor e detalhes essenciais antes de abrir dezenas de links.","A USFans intermedeia compras no Taobao, 1688 e Weidian. Verifique variantes e medidas na página atual e guarde a opção exata, pois preço e stock mudam.","Separe preço do produto, entrega doméstica e envio internacional. Volume, embalagem, câmbio e impostos podem alterar o total entregue.","Muitas páginas anunciam 3–7 fotos QC HD gratuitas. Compare cor, tamanho, quantidade, forma e danos; QC é inspeção visual, não autenticação.","Muitas páginas referem cinco dias após a chegada para pedir devolução e negociação com o vendedor. Confirme imediatamente os termos da encomenda específica.","Inclua no pacote apenas artigos aceites. Verifique restrições e use Estimation ou Rehearsal quando disponíveis antes de confirmar morada e linha.","Defina, verifique, registe, estime, reveja QC, resolva problemas e escolha uma linha elegível."],takeaway:"O índice poupa tempo; a página atual, o QC e as condições da linha orientam a decisão."},
  {standfirst:"As fotos QC evitam enviar um erro visível quando são comparadas com uma referência e uma lista fixa.",headings:["O que o QC prova","Preparar referência","Roupa","Calçado","Malas e acessórios","Fotos adicionais","Prazo de devolução","Controlo final"],bodies:["QC mostra identidade, cor visível, quantidade, tamanho e danos óbvios. Não prova material interno, durabilidade, autenticidade ou ajuste perfeito.","Guarde variante, tabela de tamanhos e detalhes decisivos. Prefira medidas e posições objetivas a uma impressão vaga.","Reveja frente, costas, simetria, impressão, fecho, bolsos, etiqueta, punhos e costuras sempre na mesma ordem.","Compare ambos os sapatos em vários ângulos, confirme a etiqueta e peça medida da palmilha ou sola se o risco de tamanho for elevado.","Verifique formato, pegas, alça, fechos, cantos, quantidade e peças pequenas. Baterias, líquidos e ímanes podem limitar rotas.","Peça apenas a imagem que pode mudar a decisão e confirme a taxa atual. Uma instrução específica produz melhor prova.","Inspecione logo à chegada. Os cinco dias frequentemente mencionados continuam sujeitos ao vendedor, tipo de artigo, estado e custo de devolução.","Confirme identidade, variante, tamanho, quantidade, vistas, simetria, danos, acessórios e medidas críticas."],takeaway:"Compare com provas guardadas e aja enquanto a solução ainda pode ocorrer na China."},
  {standfirst:"O custo internacional depende do peso embalado, volume, destino, limites e serviços, não só do peso do artigo.",headings:["Peso real e volumétrico","Estimar cedo","Elegibilidade","Usar Rehearsal","Comparar linhas","Impostos e proteção","Morada e declaração","Orçamento final"],bodies:["O peso volumétrico converte espaço em peso faturável. Verifique fórmula e regra da linha ativa; dimensões do produto são estimativas.","Registe preço, entrega local, peso, volume e restrições. Teste combinações e vigie artigos baratos mas volumosos.","A linha mais barata é inútil se o pacote não for elegível. Confirme mercadorias limitadas, peso, volume e destino antes de consolidar.","A USFans inclui Estimation e Rehearsal. Um ensaio pode produzir medidas embaladas mais realistas; ajuste compressão e proteção ao conteúdo.","Compare peso faturável, custo, tracking, prazo, restrições e compensação. Os prazos são intervalos, não datas garantidas.","Considere câmbio, pagamento, IVA ou alfândega, zona remota e serviços opcionais. Leia exclusões e provas do seguro.","Confirme nome, rua, unidade, cidade, código postal, país, telefone e declaração permitida. Guarde QC e registos do pacote.","Defina estimativa otimista, orçamento realista e limite máximo; recalcule depois do QC antes de pagar."],takeaway:"Estime cedo, filtre restrições e compare apenas linhas realmente utilizáveis."}
]);

const zh = buildLocalized("zh", [
  {standfirst:"USFans 商品索引的价值是提高筛选效率，并不代表卖家、价格或库存始终有效。下面的方法只采用目前能从平台公开页面核实的信息。",headings:["先明确购买目标","核对当前商品页","拆分完整成本","把入库当作检查关口","在售后期内处理","有计划地合并包裹","可重复执行的流程"],bodies:["打开大量链接前，先写清分类、预算、尺码、颜色、材质以及不能妥协的细节，避免无目的浏览。","USFans 公开说明可代购 Taobao、1688 和 Weidian 商品。下单前核对当前规格和尺寸，并保存准确选项，因为价格、图片和库存都会变化。","分别计算商品价、国内运费和国际运费。体积、包装、汇率、可选服务与目的地税费都可能改变最终到手成本。","很多当前商品页写明免费提供 3–7 张高清 QC 图。根据保存的规格检查颜色、尺码、数量、外形和损伤；QC 是外观检查，不是鉴定。","很多页面写明到仓后五天内可申请退货，并由代理与卖家协商。请立即查看具体订单条款，卖家政策、商品性质和退回运费都可能影响结果。","只把确认接受的商品加入包裹。先查限制，再按需要使用 Estimation 或 Rehearsal，并最终核对地址、电话和可用线路。","明确需求、核对商品页、记录规格、估算总成本、检查 QC、处理问题、选择合规线路，能减少临时决定带来的错误。"],takeaway:"索引负责提高发现效率；当前商品页、QC 证据和实时线路条款才是决定依据。"},
  {standfirst:"只有用保存的商品参考和固定清单去检查，QC 照片才能在国际发货前帮助你拦住明显错误。",headings:["QC 能证明什么","提前保存参考","检查衣服","检查鞋子","箱包和配饰","追加照片","退货时间窗口","最终十项检查"],bodies:["QC 能确认商品身份、可见颜色、数量、尺码标签和明显损伤，但不能证明内部材质、长期耐用性、真实性或完美合身。","保存卖家主图、准确规格、尺码表和关键细节。尽量使用测量数据与明确位置，而不是“看起来差不多”的印象。","依次检查正面、背面、对称性、印花、拉链、口袋、标签、袖口和主要走线，重点找可以客观说明的差异。","把左右鞋放在一起从多个角度比较，确认尺码标签；如果合脚风险高，可询问鞋垫或外底测量。鞋盒是否保留应结合体积和保护需求决定。","检查包型、提手、肩带、闭合、四角、数量与小配件。电池、液体和磁性物品即使外观正常，也可能减少可选线路。","只有缺失细节会改变决定时才追加照片，并先核对当前费用。明确提出“正面拍摄内侧尺码标签”比笼统说“多拍几张”更有效。","商品一到仓就检查。页面常见的五天说明仍受卖家规则、商品类型、状态和退回运费影响，不能理解为所有商品无条件免费退。","确认商品、规格、尺码、数量、前后视图、左右对称、损伤、附件与关键测量，再决定接受或启动售后。"],takeaway:"围绕可见事实判断，和下单时保存的证据比较，并在仍可于中国境内处理时及时行动。"},
  {standfirst:"国际运费由打包后的重量、体积、目的地、线路限制和服务共同决定，并不是商品重量对应一个固定价格。",headings:["实际重量与体积重","尽早估算","先确认线路资格","使用 Rehearsal","比较完整线路条件","税费与保障","地址和申报","建立包裹预算"],bodies:["实际重量来自称重；体积重把占用空间换算成计费重量。每条线路的公式和计费规则可能不同，商品页尺寸只能用于前期计划。","购物时记录价格、国内运费、预估重量、尺寸和限制，并测试不同组合。尤其注意价格低但体积大的鞋盒、玩偶、包和厚外套。","如果包裹不符合要求，最低价线路没有意义。合并前核对限制品、重量体积上限与目的地规则，避免一个特殊商品迫使整包使用昂贵线路。","USFans 账户导航公开包含 Estimation 与 Rehearsal。预演可更接近最终包装尺寸；软衣物可考虑压缩，结构化或易碎商品则需要支撑保护。","至少比较计费重量、总价、追踪、预计时效、限制适配和赔付条款。时效只是范围，会受到出口、航班、海关和末端配送影响。","预算中加入换汇、支付、VAT 或关税、偏远地区和可选保障。购买保险前阅读除外项目、证据要求、赔付上限与申请期限。","提交前核对姓名、街道、房号、城市、地区、邮编、国家、电话和允许的申报描述，并保存 QC、重量、线路、付款与追踪记录。","提前设定乐观估算、实际工作预算与最高可接受成本。QC 完成后再计算一次，确认包裹内容、包装指示和线路资格。"],takeaway:"尽早估算、先过滤限制、体积重要时做预演，并且只比较当前真正可以使用的线路。"}
]);

export const articleContent: Record<Lang, ArticleContent[]> = {
  es: es.map((article,articleIndex)=>({...article,sections:article.sections.map((section,sectionIndex)=>({...section,paragraphs:section.paragraphs.map((paragraph,paragraphIndex)=>paragraphIndex===section.paragraphs.length-1?[paragraph,localizedDepthExtra.es?.[articleIndex]?.[sectionIndex]].filter(Boolean).join(" "):paragraph)}))})),
  en,
  fr,
  de,
  it,
  pl,
  pt,
  zh,
};
