import type { Lang } from "./i18n";

export const localizedDepthFinal: Partial<Record<Lang, string[][]>> = {
  it: [
    ["Confronta ogni candidato con gli stessi criteri e scarta subito ciò che non offre dati sufficienti.","Registra anche data e nome del prodotto per distinguere facilmente ordini quasi identici in magazzino.","Ricalcola il costo quando cambia una variante, perché dimensioni e imballaggio possono cambiare insieme al prezzo.","Se una foto non permette un confronto reale, considerala prova insufficiente e richiedi solo il dettaglio decisivo.","Una richiesta precisa accelera la discussione con il venditore e conserva meglio il tempo disponibile per agire.","Verifica infine nome, paese, CAP e telefono: un errore di indirizzo può annullare tutto il lavoro precedente.","Applica lo stesso schema a ogni acquisto e aggiorna le note quando il prezzo o la disponibilità cambiano."],
    ["Valuta soltanto caratteristiche che la fotografia mostra davvero e segnala separatamente ciò che resta impossibile da confermare.","Conserva la tabella originale perché il venditore potrebbe sostituirla dopo che l’articolo è già stato acquistato.","Confronta le misure usando lo stesso metodo della scheda, senza mescolare larghezza piatta e circonferenza completa.","Controlla anche che entrambe le scarpe appartengano allo stesso modello, colore e numero prima di esaminare i dettagli.","Per i set, confronta il numero di pezzi ricevuti con la quantità descritta e fotografata nella pagina.","Formula una sola domanda per richiesta, così il magazzino può produrre un’immagine chiara e direttamente utilizzabile.","Apri il caso appena appare l’anomalia e non aspettare l’arrivo degli altri articoli della stessa spedizione.","Archivia il risultato finale insieme all’ordine, utile sia per il pacco sia per eventuali richieste successive."],
    ["Controlla sempre se la linea usa il maggiore tra peso reale e volumetrico prima di stimare il totale.","Attribuisci a ogni oggetto un costo di consegna stimato per individuare quelli che rendono inefficiente la consolidazione.","Rivedi l’idoneità dopo ogni modifica del contenuto, perché togliere o aggiungere un articolo cambia le opzioni disponibili.","Chiedi il rehearsal soprattutto quando una piccola variazione di volume può spostare il pacco in una fascia diversa.","Confronta il costo per chilogrammo solo tra linee con restrizioni, tracking e protezione realmente comparabili.","Conserva ricevute e termini prima della partenza, quando tutte le informazioni sono ancora accessibili nel conto.","Correggi immediatamente ogni campo incompleto: il supporto non può indovinare un interno, un CAP o un telefono mancante.","Usa il tetto massimo come regola decisionale reale, non come cifra da ignorare quando arriva il preventivo finale."]
  ],
  pl: [
    ["Porównuj kandydatów tymi samymi kryteriami i odrzucaj oferty bez danych potrzebnych do decyzji.","Zapisz datę i nazwę produktu, aby rozróżnić podobne zamówienia po przyjęciu do magazynu.","Przelicz koszt po zmianie wariantu, ponieważ cena, wymiary i opakowanie mogą zmienić się razem.","Jeśli ujęcie nie pozwala na realne porównanie, uznaj dowód za niewystarczający i poproś o konkretny detal.","Precyzyjne zgłoszenie przyspiesza rozmowę ze sprzedawcą i lepiej wykorzystuje dostępny czas na działanie.","Na końcu sprawdź nazwę, kraj, kod i telefon, bo błąd adresu może zniweczyć wcześniejszą kontrolę.","Stosuj ten sam schemat przy każdym zakupie i aktualizuj notatki po zmianie ceny lub stanu."],
    ["Oceniaj wyłącznie cechy widoczne na zdjęciach, a osobno zapisuj wszystko, czego nie można potwierdzić.","Zachowaj oryginalną tabelę, ponieważ sprzedawca może ją zmienić już po dokonaniu zakupu.","Porównuj pomiary tą samą metodą i nie mieszaj szerokości na płasko z pełnym obwodem.","Najpierw potwierdź, że oba buty mają ten sam model, kolor i rozmiar, dopiero potem badaj detale.","W zestawach porównaj liczbę otrzymanych elementów z ilością opisaną i pokazaną w ofercie.","W jednej prośbie zadawaj jedno konkretne pytanie, aby magazyn dostarczył jednoznaczny materiał.","Otwórz sprawę natychmiast po wykryciu różnicy i nie czekaj na pozostałe produkty.","Zapisz ostateczny wynik razem z zamówieniem, paczką i dokumentacją potrzebną do późniejszego wsparcia."],
    ["Przed kalkulacją sprawdź, czy linia rozlicza większą wartość z wagi rzeczywistej i gabarytowej.","Przypisz każdej rzeczy szacowany koszt dostawy, aby wykryć produkty pogarszające opłacalność konsolidacji.","Sprawdź dopuszczalność po każdej zmianie zawartości, ponieważ dodanie lub usunięcie rzeczy zmienia dostępne linie.","Rehearsal jest szczególnie przydatny, gdy niewielka zmiana objętości może zmienić próg cenowy.","Porównuj koszt za kilogram tylko między liniami o porównywalnych ograniczeniach, trackingu i ochronie.","Zachowaj potwierdzenia i warunki przed wysyłką, kiedy pełne dane są jeszcze dostępne na koncie.","Popraw każdy brakujący element adresu; obsługa nie może odgadnąć lokalu, kodu ani telefonu.","Traktuj maksymalny budżet jak rzeczywistą zasadę, a nie liczbę ignorowaną przy końcowej wycenie."]
  ],
  pt: [
    ["Compare todos os candidatos pelos mesmos critérios e elimine páginas sem dados suficientes para decidir.","Registe data e nome do produto para distinguir encomendas quase iguais quando chegam ao armazém.","Recalcule após mudar a variante, pois preço, dimensões e embalagem podem mudar ao mesmo tempo.","Se a imagem não permite comparação real, trate-a como prova insuficiente e peça apenas o detalhe decisivo.","Um pedido preciso acelera a negociação com o vendedor e preserva melhor o tempo disponível para agir.","Confirme nome, país, código postal e telefone; um erro de morada pode anular todo o controlo anterior.","Aplique o mesmo método a cada compra e atualize notas quando preço ou disponibilidade mudarem."],
    ["Avalie apenas características realmente visíveis e registe separadamente o que a fotografia não consegue confirmar.","Guarde a tabela original, porque o vendedor pode substituí-la depois de a compra ser efetuada.","Compare medidas pelo mesmo método e não misture largura plana com circunferência completa.","Confirme primeiro que ambos os sapatos têm modelo, cor e tamanho iguais antes de analisar detalhes.","Nos conjuntos, compare o número de peças recebidas com a quantidade descrita e fotografada.","Faça uma pergunta específica por pedido para o armazém produzir uma imagem clara e utilizável.","Abra o caso logo após encontrar a diferença e não espere pelos outros artigos da encomenda.","Arquive a decisão final com a encomenda, o pacote e os dados necessários para apoio futuro."],
    ["Confirme se a linha cobra o maior valor entre peso real e volumétrico antes de calcular.","Atribua custo de entrega estimado a cada artigo para identificar o que torna a consolidação ineficiente.","Reveja elegibilidade após mudar o conteúdo, pois adicionar ou remover artigos altera as linhas disponíveis.","Use Rehearsal quando uma pequena alteração de volume puder mover o pacote para outra faixa.","Compare custo por quilograma apenas entre linhas com restrições, tracking e proteção equivalentes.","Guarde comprovativos e termos antes da partida, enquanto toda a informação permanece acessível na conta.","Corrija imediatamente campos incompletos; o apoio não pode adivinhar unidade, código postal ou telefone.","Use o limite máximo como regra real, não como número ignorado quando surge a cotação final."]
  ]
};
