import type { ArticleContent } from './articleContent';

export { octoberSlugs } from "./articleRoutes";
export const octoberCards = [
  ['Presupuesto', 'USFans comisiones: calcula el coste total antes de comprar', 'Separa producto, cambio de moneda, servicios y envío. Incluye un ejemplo de presupuesto sin inventar tarifas de USFans.', '8 min'],
  ['Tallas', 'Guía de tallas USFans: ropa y zapatillas con medidas', 'Compara centímetros, tablas del vendedor y fotos QC para elegir talla sin depender de una conversión genérica.', '8 min'],
  ['Envíos', 'USFans rehearsal y peso volumétrico: calcula tu paquete', 'Un ejemplo con medidas explica el peso facturable, cuándo valorar el rehearsal y cómo comparar dos embalajes.', '8 min'],
  ['Enlaces', 'Un link de USFans no funciona: cómo encontrar la ficha correcta', 'Distingue un enlace roto, una redirección, un producto cambiado y una variante agotada antes de volver a comprar.', '7 min'],
];
const guide = { label: 'Guía oficial de USFans: consulta las opciones vigentes', url: 'https://www.usfans.com/beginner-guide' };
const help = { label: 'Ayuda oficial de USFans', url: 'https://www.usfans.com/help' };
const related = (slug: string, label: string) => ({label, url: `/articles/${slug}/`});
export const octoberArticles: ArticleContent[] = [
{
 standfirst: 'El coste total de un pedido de USFans no se obtiene multiplicando el precio de una camiseta por la cantidad. El producto, los pagos, el transporte hasta el almacén y el envío internacional pueden aparecer en momentos diferentes. Esta guía propone un presupuesto que puedes completar con los importes reales de tu cuenta. No publica una tabla de comisiones supuestamente universal: las opciones, la moneda, el destino y el paquete concreto determinan lo que terminarás pagando.',
 sections: [
 {heading: 'Separa el precio del producto del coste entregado', paragraphs: [
 'Empieza con dos cifras: el subtotal de los artículos y el límite que aceptarías pagar por recibirlos. La diferencia debe cubrir los conceptos restantes. Un producto económico puede resultar poco conveniente si ocupa mucho espacio, requiere protección especial o solo admite determinadas líneas. Evaluar el precio aislado hace que esos costes aparezcan cuando ya has comprometido parte del dinero.',
 'Crea una hoja con estas columnas: concepto, importe, moneda, fecha, estado y documento de referencia. En estado utiliza estimado, cotizado o pagado. Así podrás sustituir una previsión por una factura sin sumar ambas. Reserva una fila independiente para cada envío nacional y para cada paquete internacional; no supongas que todas las compras comparten el mismo transporte.'
 ], bullets: ['Productos y variantes elegidas.', 'Transporte del vendedor al almacén.', 'Conversión y costes de pago que figuren en la operación.', 'Servicios opcionales, embalaje y envío internacional.', 'Impuestos o gestión aplicables que no estén ya incluidos.']},
 {heading: 'Comprueba la moneda antes de comparar comisiones', paragraphs: [
 'Una cifra en un catálogo puede cambiar cuando seleccionas otra moneda. Comprueba el código de moneda, la variante y el importe final de la operación. Un símbolo de dólar junto a una cantidad no permite reconstruir por sí solo el precio original en yuanes. Conserva el importe que se carga realmente y la moneda de tu medio de pago; esa es la base para comparar opciones.',
 'Si una recarga convierte euros a saldo y después compras con ese saldo, registra las dos fases sin contar la recarga completa como gasto adicional al producto. Parte del dinero podría seguir en la cuenta. Para comparar pagos, calcula cuánto recibes utilizable por cada euro cargado, incluyendo solo los costes mostrados. No publiques ni compartas capturas con datos bancarios o números completos de pedido.'
 ]},
 {heading: 'Solicita el desglose de los servicios que sí necesitas', paragraphs: [
 'Una fotografía adicional, una medición, un ensayo de embalaje o un refuerzo pueden ser útiles, pero no deben añadirse automáticamente al presupuesto como si fueran obligatorios. Consulta qué está incluido en tu pedido y cuánto cuesta cada opción antes de seleccionarla. Si una medición decide si aceptarás una prenda, tiene un propósito distinto al de pedir varias fotos que repiten la misma vista.',
 'Anota también si el servicio se aplica por artículo o por paquete. La unidad cambia la cuenta cuando compras varias prendas. Guarda la descripción seleccionada y el importe confirmado. Si una opción no aparece en la cuenta, pide aclaración al soporte; un tutorial antiguo no demuestra que esa prestación siga disponible ni que conserve el precio de entonces.'
 ], links: [help, related('qc-photos-guide', 'Revisar fotos QC y pedir una evidencia concreta')]},
 {heading: 'Ejemplo de presupuesto con cifras ficticias', paragraphs: [
 'Imagina tres artículos que, tras expresar todos los importes en la misma moneda, suman 72 €. Añade 6 € de transporte nacional, 3 € de costes de pago identificados, 4 € de servicios elegidos y una estimación internacional de 38 €. El subtotal sería 123 €. Son cifras didácticas, no tarifas, cotizaciones ni una experiencia de compra en USFans.',
 'Supón que, después de embalar, el envío cotizado pasa de 38 € a 46 €. Sustituye la estimación: el subtotal pasa a 131 €, no a 169 €. La diferencia de 8 € se debe investigar comparando peso, medidas y línea. Todavía faltaría añadir cualquier concepto aplicable no incluido y restar reembolsos confirmados. Mantén los importes pendientes separados del saldo que ya has pagado.',
 'Si habías fijado un límite de 140 €, en el segundo escenario quedarían 9 € para los conceptos todavía pendientes. Esa comparación puede revelar que el pedido supera tu margen antes de pagarlo. Un presupuesto sirve para tomar una decisión, no para justificarla después: considera modificar el contenido, el embalaje o la compra si las alternativas realmente disponibles no encajan.'
 ]},
 {heading: 'El envío cambia con el paquete, no solo con los kilos', paragraphs: [
 'Compara cotizaciones que compartan destino, contenido, medidas y servicios. Una línea basada en volumen y otra basada en otra regla no se pueden ordenar únicamente por el precio anunciado de un kilo. Revisa el peso facturable, los tramos, el redondeo y los límites que muestra cada opción. Las dimensiones del paquete preparado aportan más información que sumar pesos aproximados de productos.',
 'Para distribuir el envío entre artículos puedes usar una regla contable propia: partes iguales, proporción de peso o contribución al volumen. Indica cuál utilizas. Ninguna convierte una parte del coste compartido en una tarifa oficial por producto. Si un artículo grande eleva mucho el total, compara el paquete con y sin él manteniendo iguales las demás condiciones.'
 ], links: [related('usfans-rehearsal-peso-volumetrico', 'Ejemplo de peso volumétrico y comparación del embalaje')]},
 {heading: 'Impuestos y gestión: verifica lo incluido', paragraphs: [
 'Para un destino español, revisa la información fiscal correspondiente al territorio y la fecha de compra. La Agencia Tributaria informa de cambios desde el 1 de julio de 2026 para determinadas compras por Internet de hasta 150 € enviadas desde fuera de la Unión Europea: además del IVA, describe un arancel de 3 € por categoría de artículos. No lo interpretes como un importe único por paquete ni como una comisión del agente.',
 'Comprueba en la cotización qué conceptos se han cobrado y qué justificante los documenta. Canarias, Ceuta y Melilla requieren consultar su régimen específico. Una etiqueta comercial de una línea no sustituye esas comprobaciones. Si la información es ambigua, solicita el desglose antes de pagar y conserva la respuesta con el presupuesto.'
 ], links: [{label:'Agencia Tributaria: compras por Internet de hasta 150 euros',url:'https://sede.agenciatributaria.gob.es/Sede/aduanas/comercio-electronico-pipe-envios-particulares/compras-internet-envios-particulares/envios-valor-hasta-150-euros.html'},related('usfans-canarias-envios','Guía específica para envíos a Canarias')]},
 {heading: 'Cupones, saldo y devoluciones sin dobles cuentas', paragraphs: [
 'Apunta un descuento únicamente cuando el resumen de pago confirme su aplicación. Comprueba si reduce el producto, el envío o un servicio y si exige una condición. Un cupón no utilizado no es un ahorro del pedido. Tampoco compenses una devolución solicitada como si el dinero ya estuviera disponible: primero registra la solicitud y después el abono confirmado.',
 'Al cerrar la cuenta, separa lo pagado, lo reembolsado, el saldo sin gastar y los cargos aún pendientes. Este registro permite explicar una diferencia sin confundir depósitos con consumo. Para una siguiente compra, conserva también las dimensiones finales del paquete y su contenido; ese historial propio resulta más útil para estimar que un precio aislado publicado por otra persona.'
 ], links: [related('usfans-devoluciones-almacen','Devoluciones desde el almacén: evidencias y costes'), guide]},
 ],
 takeaway: 'Utiliza una moneda común, identifica cada concepto y reemplaza las estimaciones por cargos confirmados. Decide con el coste entregado y un límite de presupuesto, no con el precio aislado del producto.'
},
{
 standfirst: 'Elegir talla en USFans exige leer la ficha del vendedor y comprobar medidas; el nombre del agente no define un tallaje único. Una M, una XL o un número europeo pueden describir prendas y hormas diferentes según la publicación. Este método conecta una referencia que ya te queda bien con la tabla actual y con las pruebas que puedes solicitar al llegar al almacén. Sirve para reducir incertidumbre, sin prometer que una fotografía pueda garantizar comodidad.',
 sections: [
 {heading: 'Empieza por una referencia que realmente utilices', paragraphs: [
 'Escoge una prenda de la misma categoría y del ajuste deseado. Para una sudadera gruesa utiliza otra sudadera, no una camiseta elástica. Extiéndela sobre una superficie plana y anota cómo tomas cada medida. Pecho de axila a axila, longitud desde un punto definido, hombros y manga suelen aportar más contexto que la talla de la etiqueta. Conserva también una fotografía de tu forma de medir.',
 'Distingue medidas de la prenda y medidas del cuerpo. Una tabla puede mostrar contorno completo mientras tú has medido un ancho en plano. Si dos valores no usan el mismo método, no son comparables. Tampoco conviertas automáticamente el doble de un ancho en una medida corporal recomendada: el patrón, el tejido y la holgura elegida siguen influyendo.'
 ]},
 {heading: 'Lee la tabla de la variante actual', paragraphs: [
 'Abre el anuncio que vas a comprar y busca la tabla asociada a esa versión. Comprueba unidades, nombres de columnas y cualquier tolerancia declarada por el vendedor. Una tabla encontrada en otro color, otro lote o una publicación antigua puede no corresponder. Guarda la imagen o los valores que fundamentan tu elección junto con el enlace y la opción exacta.',
 'Si falta una dimensión decisiva, pregunta antes de realizar la orden. Una respuesta como “talla normal” no aclara el ancho de una chaqueta ni la longitud de un pantalón. Formula la consulta con un punto de inicio, un punto final y centímetros. Cuando el vendedor no aporta información suficiente, considera otra ficha con medidas más completas; comprar una talla al azar traslada el problema al almacén.'
 ]},
 {heading: 'Ejemplo: comparar dos tallas de una sudadera', paragraphs: [
 'Tu sudadera de referencia mide 58 cm de ancho entre axilas y 70 cm de largo, ambos en plano. Una tabla ficticia muestra M con 57 y 69 cm, y L con 60 y 72 cm. La comparación útil es M: 1 cm menos en ambos ejes; L: 2 cm más. Estos datos no son una tabla de un vendedor real ni una recomendación universal de talla.',
 'El siguiente paso es decidir qué diferencia puedes aceptar. Una persona que quiere el mismo ajuste no busca necesariamente la misma opción que otra que desea una silueta más amplia. Revisa además manga y hombros, porque coincidir en pecho no garantiza coincidir en proporciones. Si el anuncio declara una tolerancia, compárala con el margen que estás dispuesto a aceptar antes de elegir.',
 'No resuelvas una discrepancia decisiva con una media entre tallas. Si ninguna satisface las medidas importantes, puede que el patrón no sea adecuado para ti. Anota el motivo de la elección y qué comprobación pedirás al llegar. Así, cuando veas las fotos QC, tendrás un criterio previo y evitarás aceptar la prenda únicamente porque ya has esperado por ella.'
 ]},
 {heading: 'Pantalones, chaquetas y prendas elásticas', paragraphs: [
 'En pantalones revisa cintura con el método indicado, tiro, muslo y longitud. Una cintura elástica en reposo no es igual a su contorno máximo estirado. Pide que la medición especifique el estado del tejido y no lo compares con una tabla corporal sin aclaración. Para un ajuste cómodo, tu referencia debe ser una prenda de uso parecido, no una cifra recordada de otra tienda.',
 'En chaquetas y prendas para llevar encima de otras capas presta atención al espacio y a la movilidad que buscas. La longitud de manga puede medirse desde el hombro o desde otro punto; los hombros caídos también cambian la interpretación. No añadas centímetros de forma automática a todas las medidas. Define primero el uso y después compara dimensiones equivalentes.'
 ]},
 {heading: 'Zapatillas: centímetros y horma antes que conversiones', paragraphs: [
 'Para unas zapatillas, registra la longitud de ambos pies con un método consistente y considera el mayor como referencia al consultar la tabla del modelo. Lee qué representa la columna en centímetros: longitud de pie recomendada, plantilla u otra medida. No son intercambiables. Las conversiones EU, US o UK tampoco deben trasladarse entre vendedores sin comprobar el modelo y la tabla concreta.',
 'Compara con un par que uses para una actividad similar y con el tipo de calcetín previsto. El ancho, la forma de la puntera y el volumen interior pueden importar aunque la longitud parezca adecuada. Una medida de la suela exterior no revela el espacio interior. Si solicitas una fotografía de la plantilla, úsala como información complementaria y aclara cómo se ha medido.'
 ]},
 {heading: 'Pide una medición QC que permita decidir', paragraphs: [
 'Cuando llegue la prenda al almacén, contrasta primero identidad, variante y etiqueta. Si la duda es la medida, solicita una vista con la prenda extendida, la cinta visible y ambos extremos reconocibles. Una instrucción útil sería: medir el ancho en plano de axila a axila, sin estirar, con el cero y la lectura final dentro de la fotografía. Comprueba antes si esa solicitud está disponible y su coste.',
 'Evita pedir simplemente que comprueben si la talla está bien. El personal no conoce tu cuerpo ni tu ajuste deseado. También evita deducir centímetros de una foto inclinada sin escala. Si la imagen no permite leer un extremo, pide aclaración sobre esa evidencia concreta. No presentes un cálculo obtenido de píxeles como si fuera una medición física del artículo.'
 ], links: [related('qc-photos-guide','Cómo revisar fotos QC antes del envío'), help]},
 {heading: 'Resuelve discrepancias antes de consolidar', paragraphs: [
 'Compara la medición con la tabla guardada y con tu referencia, teniendo en cuenta el método y la tolerancia publicada. Si parece existir una diferencia, conserva la foto, la opción comprada y el valor esperado. Solicita que se aclare si hubo un error de variante, una medida tomada de otra forma o una característica real de la prenda. Son situaciones distintas y no tienen necesariamente la misma solución.',
 'Consulta las condiciones y los plazos de tu pedido inmediatamente. Una solicitud de cambio o devolución depende de lo que corresponda a esa compra y no queda garantizada por esta guía. Mientras la decisión siga abierta, evita incluir el artículo en el paquete internacional. Si aceptas una diferencia, deja anotado qué aceptaste; no pierdas el criterio al revisar varias prendas parecidas.'
 ], links: [related('usfans-devoluciones-almacen','Gestionar una devolución desde el almacén')]},
 {heading: 'Conserva un registro útil para la siguiente compra', paragraphs: [
 'Después de recibir el artículo, añade una nota sobre el ajuste real, las medidas y el uso. Una talla acertada en una publicación concreta es una referencia para ese producto, no para toda la plataforma. Si cambia la ficha, vuelve a comprobarla. Mantén separadas tus preferencias personales y las medidas observables para recordar por qué una prenda te funciona.',
 'Tu registro mínimo puede incluir enlace, vendedor o referencia, variante, talla, tabla, medición QC, fecha y valoración del ajuste. No necesitas una colección enorme: unas pocas referencias consistentes ofrecen mejor información que muchas recomendaciones sin contexto. Completa la elección con el presupuesto total, porque cambiar de talla o devolver una prenda puede añadir tiempo y costes.'
 ], links: [related('usfans-ropa-guia','Encontrar ropa y comparar fichas'),related('usfans-comisiones-coste-total','Preparar el coste total de la compra'),guide]},
 ],
 takeaway: 'Compara medidas tomadas de la misma forma, conserva la tabla de la variante y pide una prueba concreta cuando una dimensión determine tu decisión. La talla de una etiqueta es una referencia, no una garantía de ajuste.'
},
{
 standfirst: 'En una búsqueda sobre USFans rehearsal o calculadora de envío, la duda central suele ser la misma: por qué un paquete ligero puede tener un envío caro. La respuesta está en los datos que utiliza cada línea para calcular el peso facturable y en el embalaje final. Esta guía explica un ejemplo numérico y un método para comparar opciones. Las fórmulas de los ejemplos son supuestos didácticos; debes utilizar las reglas y servicios que aparezcan disponibles en tu cuenta.',
 sections: [
 {heading: 'Distingue peso real, volumen y peso facturable', paragraphs: [
 'El peso real es la masa del paquete preparado, con sus protecciones y caja. El volumen representa el espacio que ocupa. El peso volumétrico convierte ese espacio mediante un divisor definido por la línea. El peso facturable es el valor que finalmente se utiliza para tarifar, tras aplicar las reglas de comparación, mínimos o redondeos de esa opción. No son cuatro nombres para el mismo dato.',
 'Antes de estimar, anota de dónde procede cada valor. El peso declarado de un producto puede no incluir embalaje. Las dimensiones de una caja comercial pueden cambiar al consolidarla. Una calculadora con datos aproximados produce una previsión, aunque muestre céntimos. No trates su precisión visual como una confirmación del importe que se cobrará.'
 ]},
 {heading: 'Un ejemplo de peso volumétrico paso a paso', paragraphs: [
 'Considera una caja ficticia de 40 × 30 × 25 cm y 3 kg de peso real. Su volumen es 30.000 cm³. Si una línea hipotética utilizara el divisor 5.000, el peso volumétrico sería 6 kg. Si otra utilizara 6.000, sería 5 kg. Estos divisores ilustran la operación; no se presentan como condiciones vigentes de una línea de USFans.',
 'Si además la primera línea hipotética cobrase por el mayor entre peso real y volumétrico, antes de cualquier redondeo tomaría 6 kg. El artículo pesa 3 kg, pero ocupa el espacio que esa regla valora en 6 kg. Para calcular la tarifa todavía faltaría consultar precio por tramo, mínimos, redondeos, recargos y elegibilidad. No multipliques ese resultado por un precio encontrado para otra ruta.',
 'Comprueba las unidades: el divisor del ejemplo presupone centímetros y expresa el resultado en kilogramos. Introducir milímetros o metros sin adaptar la fórmula altera completamente la cuenta. Guarda las tres dimensiones por separado y conserva el divisor junto a la línea y la fecha. Así podrás reproducir el cálculo si el presupuesto cambia después de embalar.'
 ]},
 {heading: 'Compara embalajes con el mismo contenido', paragraphs: [
 'Imagina que el mismo contenido puede prepararse en una caja de 40 × 30 × 20 cm conservando la protección necesaria. El volumen pasa a 24.000 cm³. Con el divisor hipotético 5.000, el peso volumétrico sería 4,8 kg en vez de 6 kg. La reducción de altura modifica el cálculo, pero no demuestra todavía una rebaja idéntica en el precio: la línea puede cobrar por tramos.',
 'Mantén constantes destino, contenido y nivel de protección al comparar. Quitar una caja puede reducir tamaño, pero también eliminar una función que necesitas. No comprimas objetos frágiles ni retires material solo para alcanzar una cifra. Valora cuánto ahorro real produce la nueva cotización y qué riesgo o pérdida de presentación aceptas a cambio.'
 ]},
 {heading: 'Cuándo valorar un rehearsal', paragraphs: [
 'Un ensayo de embalaje puede ser útil cuando la incertidumbre sobre medidas cambia tu decisión: varios pares con cajas, artículos de formas distintas o un paquete próximo a los límites de una línea. Comprueba en la cuenta si el servicio está disponible, qué resultado entrega, cuánto cuesta y en qué momento se solicita. La palabra rehearsal por sí sola no define lo incluido.',
 'Pide instrucciones específicas sobre qué conservar y qué retirar, y confirma que todos los artículos están aceptados. No tiene sentido calcular un paquete definitivo con una devolución pendiente. Si las medidas no van a cambiar tu selección o el ahorro posible es menor que el coste del servicio, compara primero con los datos que ya tienes; el rehearsal es una herramienta para decidir, no un paso obligatorio universal.'
 ], links: [help, related('usfans-devoluciones-almacen','Cerrar incidencias antes de consolidar')]},
 {heading: 'Los datos que necesitas de una calculadora de envío', paragraphs: [
 'Reúne país y región de destino, código postal cuando sea necesario, contenido, peso real estimado, dimensiones, valor y servicios. Indica las características que condicionan la admisión según la plataforma. Una línea que aparece para ropa común puede no aceptar otros contenidos. Primero filtra las opciones elegibles y después compara sus importes; el precio más bajo de una ruta no disponible no es una alternativa real.',
 'Para cada opción guarda el peso facturable calculado, el coste completo, la previsión de entrega, el seguimiento disponible y las condiciones de compensación. Conserva también lo que no incluye la cotización. El dato fiscal de un destino o una obligación de documentación no se resuelve cambiando el divisor. Una calculadora logística no sustituye las condiciones contractuales y aduaneras.'
 ], bullets: ['Mismo destino y contenido en todas las comparaciones.', 'Medidas en las unidades exigidas por la línea.', 'Divisor, redondeo y límites anotados.', 'Servicios y conceptos incluidos identificados.']},
 {heading: 'Una caja frente a dos: calcula ambos escenarios', paragraphs: [
 'Dividir un conjunto puede hacer que un objeto voluminoso deje de condicionar el resto, pero también puede duplicar cargos mínimos, embalajes o servicios. No existe una regla que convierta siempre dos paquetes en la opción barata. Cotiza una caja y dos cajas con sus medidas y contenido respectivos, y suma todos los componentes de cada escenario.',
 'Compara también la cantidad de entregas, los registros de seguimiento y la protección. No dividas pedidos para falsear valores ni para ocultar contenido. Mantén descripciones y documentación correctas. Si una opción solo parece funcionar al omitir un coste o al cambiar una condición esencial, la comparación no es equivalente y debes corregirla antes de decidir.'
 ], links: [related('shipping-cost-guide','Planificar el envío internacional'),related('usfans-comisiones-coste-total','Contabilizar todos los costes del pedido')]},
 {heading: 'Qué revisar cuando la cifra final cambia', paragraphs: [
 'Compara la estimación guardada con el paquete preparado: dimensiones, peso, cantidad, embalaje, línea y servicios. Busca una diferencia concreta antes de atribuir el cambio a una comisión desconocida. Una caja más alta, un mínimo tarifario o una opción de refuerzo pueden explicar parte de la variación. Si no aparece el desglose, solicita aclaración antes de aprobar el pago.',
 'Guarda la cotización confirmada y las características finales junto con las instrucciones de embalaje. Si haces cambios después, comprueba si se requiere una nueva medición o cotización. El resultado anterior describe una configuración concreta; no garantiza el precio de un paquete al que acabas de añadir otro artículo.'
 ]},
 {heading: 'Confirma el paquete que realmente quieres enviar', paragraphs: [
 'Antes de autorizar el envío, revisa que la lista coincida con los artículos aprobados, que el embalaje conserve la protección elegida y que no haya incidencias abiertas. Verifica dirección y teléfono por separado de la comparación de precios. La selección de una línea económica no corrige un número de vivienda incompleto ni una región de destino equivocada.',
 'Deja un registro del motivo de tu elección: coste confirmado, medidas utilizadas y condición que consideraste prioritaria. Cuando recibas el paquete, esa información permitirá mejorar una futura estimación. Evita extrapolar el resultado a cualquier compra: contenido, medidas, destino y reglas de la línea pueden cambiar.'
 ], links: [related('usfans-spain-address-checklist','Lista de dirección para España'),guide]},
 ],
 takeaway: 'Calcula con las reglas de la línea disponible y con el paquete preparado. Usa el rehearsal cuando unas medidas más fiables puedan cambiar tu decisión, y compara el coste completo de cada embalaje.'
},
{
 standfirst: 'Que un link de USFans no funcione puede significar varias cosas: la ficha desapareció, una redirección perdió la ruta, el catálogo cambió de producto o la variante dejó de estar disponible. Antes de volver a buscar, identifica qué resultado estás viendo. Esta guía permite recuperar contexto y encontrar una alternativa verificable sin asumir que un número de producto o una fotografía antigua siguen apuntando al mismo artículo.',
 sections: [
 {heading: 'Identifica el tipo de fallo antes de cambiar el enlace', paragraphs: [
 'Abre el enlace y observa la dirección final, el título y el contenido visible. Si llegas a una página de inicio, puede haberse perdido la ruta de detalle durante una redirección. Si aparece una página no encontrada, la dirección concreta ya no ofrece la ficha. Si hay un producto distinto, el enlace técnicamente abre, pero no cumple lo que prometía la tarjeta de origen.',
 'Un aviso de acceso, una sesión requerida o una restricción del servicio no prueban que el artículo se haya agotado. No intentes sortear esos controles ni descargues herramientas para “desbloquear” una ficha. Utiliza los canales normales del servicio y conserva la referencia que buscabas. Separar un problema de acceso de un problema de catálogo evita reemplazar sin motivo un producto que quizá siga publicado.'
 ], bullets: ['Inicio en vez de ficha: comprueba la ruta final.', 'Página inexistente: busca la referencia desde el catálogo.', 'Producto diferente: vuelve a verificar identidad y variante.', 'Ficha correcta sin tu opción: revisa disponibilidad de esa variante.']},
 {heading: 'Una comprobación real en este catálogo', paragraphs: [
 'En la revisión del 7 de octubre de 2026 detectamos que enlaces del catálogo externo sin www terminaban en la página de inicio durante la navegación. Los enlaces con www conservaron la ficha de producto y la búsqueda probada. También encontramos tarjetas cuyo nombre e imagen antiguos ya no coincidían con el producto que mostraba su dirección de destino.',
 'Por ese motivo actualizamos los enlaces, nombres, imágenes y precios visibles de la selección. Esta es una observación de esa revisión, no una regla general para todos los sitios. Añadir www a cualquier dominio no es una solución universal. La prueba útil consiste en abrir el destino, observar la dirección resultante y verificar que el producto coincide.'
 ], links: [{label:'Abrir el catálogo externo comprobado',url:'https://www.cnfanshp.com/AllProducts/'}]},
 {heading: 'Recupera la referencia, no solo el número', paragraphs: [
 'Reúne el nombre del artículo, el modelo, la categoría, una imagen de referencia y la variante que necesitabas. Conserva el enlace original como dato histórico. Un identificador numérico puede ayudar a reconocer una ruta, pero no demuestra identidad ni disponibilidad. Si una ficha ha cambiado, no reutilices automáticamente su título anterior para describir lo que contiene ahora.',
 'Para una prenda, añade tipo, color, patrón y medidas relevantes. Para unas zapatillas, distingue modelo y versión antes de comparar fotografías. Si solo conservas una imagen, utiliza sus detalles para construir una búsqueda, pero no deduzcas vendedor, composición o autenticidad. La similitud visual sirve para encontrar candidatos; la ficha actual debe aportar la información para elegir.'
 ]},
 {heading: 'Busca por etapas y comprueba cada candidato', paragraphs: [
 'Empieza con marca o modelo y un tipo de producto. Si los resultados son muy amplios, añade un detalle diferenciador; si no hay resultados, elimina un término secundario. Prueba el nombre tal como aparece en el catálogo cuando lo conozcas. Una búsqueda demasiado larga puede excluir publicaciones que describen el mismo artículo de otra forma.',
 'Abre solo los candidatos que correspondan a la categoría y compara nombre, imagen principal, opciones y precio con su moneda. Comprueba la variante después de seleccionarla, porque el importe inicial puede representar otra opción. Si la ficha ofrece un enlace al vendedor o al agente, verifica también ese siguiente destino antes de dar por recuperada la compra.',
 'No llenes tu lista con sustitutos apenas parecidos para mantener un enlace activo. Una alternativa útil debe satisfacer las características que motivaron la búsqueda. Si cambia el material, la talla disponible o el contenido del conjunto, escribe esa diferencia. Cuando no exista una opción suficientemente documentada, conservar la búsqueda como pendiente es más claro que presentar un reemplazo como idéntico.'
 ], links: [related('usfans-index-guide','Utilizar una spreadsheet con una lista corta'),related('usfans-ropa-guia','Encontrar ropa por categoría y referencia')]},
 {heading: 'Distingue producto disponible y variante disponible', paragraphs: [
 'Una publicación puede seguir visible aunque falte tu color o talla. Comprueba las opciones seleccionables y los avisos actuales. No interpretes una fotografía del color deseado como una confirmación de stock. Tampoco asumas que una cantidad mostrada garantiza que el vendedor podrá preparar la orden cuando el agente la tramite.',
 'Si aceptas otra variante, vuelve a comprobar precio y medidas. Cambiar de color o de versión puede implicar una tabla distinta o detalles diferentes. Guarda la opción final y elimina de tu nota cualquier descripción anterior que ya no corresponda. Esa actualización evita comparar después las fotos QC con una referencia que tú mismo cambiaste al comprar.'
 ], links: [related('usfans-guia-tallas','Comprobar medidas de la variante elegida')]},
 {heading: 'Antes de pagar de nuevo, revisa los pedidos existentes', paragraphs: [
 'Si el enlace falla después de haber realizado una orden, entra por los accesos habituales de tu cuenta y revisa el pedido y los mensajes. Una ficha pública retirada no cancela automáticamente una compra ni demuestra que debas repetirla. Comprueba el estado de la operación y solicita aclaración sobre ese pedido antes de crear uno nuevo.',
 'Conserva número de pedido, fecha y evidencias en tu registro privado. Al pedir ayuda, comparte únicamente la información necesaria por el canal oficial. No publiques datos personales, direcciones de entrega ni comprobantes completos para que otras personas busquen el producto. Resolver el enlace y resolver el estado de una compra son tareas relacionadas, pero requieren evidencias diferentes.'
 ], links: [help,related('usfans-tiempos-envio-tracking','Interpretar las etapas y el seguimiento')]},
 {heading: 'Mantén enlaces que puedas volver a verificar', paragraphs: [
 'Una lista útil incluye referencia, URL de destino, variante, precio con moneda y fecha de comprobación. Añade un estado breve: coincide, variante no disponible, redirección o pendiente de revisión. No mantengas una marca de “verificado” sin indicar qué comprobaste. Abrir una página no confirma calidad, autenticidad ni fiabilidad del vendedor.',
 'Cuando sustituyas una referencia, conserva una nota que explique el cambio y vuelve a revisar las condiciones de compra. Antes de consolidar, contrasta el producto recibido con la variante registrada mediante QC. Un enlace reparado solo resuelve el acceso a información; todavía quedan las decisiones de talla, coste y aceptación del artículo.'
 ], links: [related('qc-photos-guide','Contrastar el producto recibido con el QC'),related('usfans-comisiones-coste-total','Recalcular el presupuesto cuando cambia un producto'),guide]},
 ],
 takeaway: 'Comprueba dirección final, identidad del producto y variante. Recuperar un enlace significa llegar a una ficha que puedes verificar; no basta con que la página deje de mostrar un error.'
}
];
