import type { ArticleContent } from './articleContent';
export const octoberEnglishCards = [
 ['Budget', 'USFans fees: calculate the full cost before buying', 'Separate products, currency conversion, optional services and shipping with a worked budget that does not invent USFans rates.', '7 min'],
 ['Sizing', 'USFans size guide: measure clothing and shoes before ordering', 'Compare centimetres, the seller’s current size chart and warehouse QC instead of relying on a generic size conversion.', '7 min'],
 ['Shipping', 'USFans rehearsal and volumetric weight: calculate your parcel', 'A worked example explains chargeable weight, when to consider rehearsal packing and how to compare packaging options.', '7 min'],
 ['Product links', 'USFans link not working: find and verify the correct listing', 'Distinguish a broken URL, a redirect, a changed product and an unavailable variant before ordering again.', '7 min'],
];
const link = (slug: string,label: string) => ({label,url:`/articles/${slug}/`});
const guide = {label:'USFans official beginner guide',url:'https://www.usfans.com/beginner-guide'};
const help = {label:'USFans official help',url:'https://www.usfans.com/help'};
export const octoberEnglishArticles: ArticleContent[] = [
{
standfirst:'The full cost of a USFans order is not simply the price of a T-shirt multiplied by the quantity. Products, payments, delivery to the warehouse and international shipping can be charged at different stages. This guide gives you a budget you can complete with the actual amounts shown in your account. It does not present a universal commission table: the payment method, currency, destination and prepared parcel determine the amount you ultimately pay.',
sections:[
{heading:'Separate the product price from the delivered cost',paragraphs:[
'Start with two figures: the subtotal of the items you want and the maximum you would accept paying to receive them. The difference must cover the remaining expenses. A cheap product can be poor value if it occupies a lot of space, needs extra protection or only qualifies for particular shipping services. Judging the product price alone leaves those costs to appear after you have already committed money.',
'Create a simple record with columns for the expense, amount, currency, date, status and supporting document. Use estimated, quoted or paid as the status. This lets you replace a forecast with a confirmed charge without counting both. Keep a separate line for each domestic delivery and each international parcel. Do not assume that purchases from different sellers share one domestic shipping charge.',
'You do not need a complicated spreadsheet to make this useful. A short, consistent list is enough if every figure has a clear meaning. Record an unknown amount as pending rather than zero. Zero means there is no charge; pending means you still need information before the budget is complete.'
],bullets:['Products and selected variants.','Seller-to-warehouse delivery.','Conversion or payment costs shown in the transaction.','Chosen services, packaging and international shipping.','Applicable taxes or handling charges not already included.']},
{heading:'Check the currency before comparing fees',paragraphs:[
'A catalogue amount may change after another currency is selected or the page finishes loading. Check the currency code, selected variant and final payment summary together. A dollar symbol beside a number does not, by itself, establish the original yuan price. Keep the amount actually charged and the currency used by your payment method; those are the starting points for a meaningful comparison.',
'If you deposit euros into an account balance and then spend that balance on products, record the two stages without adding the whole deposit to the product expense again. Some money may remain unused. When comparing ways to pay, calculate the usable balance received for the amount charged, including the costs disclosed in that transaction. Keep financial screenshots private and avoid sharing complete payment or order details.'
]},
{heading:'Request a breakdown of the services you need',paragraphs:[
'An additional photo, a measurement, a packing rehearsal or protective packaging can help you decide, but none should automatically appear in your budget as a universal requirement. Check what your particular order includes and what each selected option costs. A measurement that determines whether you accept a garment serves a different purpose from several extra pictures repeating a view you already have.',
'Also note whether a charge applies per item or per parcel. The unit makes a significant difference when you buy several pieces. Save the service description and confirmed amount. If an option is absent from your account, ask support to clarify it. An old tutorial is not evidence that a service remains available or still costs the same amount.'
],links:[help,link('qc-photos-guide','Review QC photos and request a specific piece of evidence')]},
{heading:'A worked budget using fictional amounts',paragraphs:[
'Imagine three items that total €72 after you have expressed every amount in the same currency. Add €6 for domestic delivery, €3 in identified payment costs, €4 for selected services and an estimated €38 for international shipping. The subtotal is €123. These figures illustrate a calculation; they are not USFans rates, a quotation or a report of an actual purchase.',
'Now suppose the packed parcel receives a shipping quote of €46 instead of the earlier €38 estimate. Replace the estimate, rather than adding both: the subtotal becomes €131, not €169. Investigate the €8 difference by comparing weight, dimensions, shipping service and packaging. Any applicable expense not included still needs to be added, and only confirmed refunds should be subtracted.',
'If your spending limit was €140, the revised scenario leaves €9 for everything still unresolved. That may reveal a budget problem before another payment is made. Consider changing the contents, packaging or purchase if the available alternatives do not fit the limit. A budget should help you make the decision, rather than rationalise it after the money has gone.'
]},
{heading:'Shipping depends on the parcel, not just the kilograms',paragraphs:[
'Compare quotations for the same destination, contents, dimensions and services. A route that uses volumetric weight and a route with different billing rules cannot be ranked simply by an advertised one-kilogram price. Check chargeable weight, weight bands, rounding and limits for each available option. Measurements of the prepared parcel are more informative than adding approximate product weights.',
'For your own accounts, you can allocate shared shipping equally, by item weight or by contribution to parcel volume. State which method you use. This does not turn an allocation into an official shipping price for a particular product. If one bulky item pushes the total up, compare the parcel with and without that item while keeping the other assumptions consistent.'
],links:[link('usfans-rehearsal-peso-volumetrico','Calculate volumetric weight and compare packaging')]},
{heading:'For Spain, check which import costs are included',paragraphs:[
'Check the current rules for the destination territory and purchase date. Spain’s tax authority describes changes applying from 1 July 2026 to certain online purchases worth up to €150 shipped from outside the European Union: alongside VAT, its guidance describes a €3 duty per category of goods. Do not treat that as one flat fee per parcel or as an agent commission.',
'Review the quotation and supporting documents to establish what has already been collected. The Canary Islands, Ceuta and Melilla require their own territory-specific checks. A shipping line’s marketing label does not replace those checks. If the information is ambiguous, request a breakdown before paying and retain the response with the budget.'
],links:[{label:'Spanish tax authority: online purchases worth up to €150',url:'https://sede.agenciatributaria.gob.es/Sede/aduanas/comercio-electronico-pipe-envios-particulares/compras-internet-envios-particulares/envios-valor-hasta-150-euros.html'}]},
{heading:'Keep discounts, unused balance and refunds separate',paragraphs:[
'Record a discount only after the payment summary confirms that it applies. Check whether it reduces the product price, shipping or another service, and whether any conditions apply. An unused coupon is not an actual saving. Likewise, do not count a requested refund as available money: first record the request, then record the confirmed credit if and when it arrives.',
'When closing the budget, distinguish payments, refunds, unused balance and outstanding charges. This makes differences explainable without confusing a deposit with spending. Keep the final parcel dimensions and contents as well. Your own consistent records will be more useful for the next estimate than an isolated shipping price posted by somebody with a different parcel and destination.'
],links:[guide]},
],takeaway:'Use one comparison currency, identify each expense and replace estimates with confirmed charges. Make the purchase decision using the delivered cost and your spending limit, rather than the product price alone.'
},
{
standfirst:'Choosing a size through USFans means checking the seller’s listing and comparing measurements. The agent’s name does not define a universal sizing system. An M, XL or European shoe number can describe different cuts and shapes in different listings. This method connects an item that already fits you with the current size chart and the evidence you can request after warehouse arrival. It reduces uncertainty without claiming that a photograph can guarantee comfort.',
sections:[
{heading:'Start with a reference you actually wear',paragraphs:[
'Choose a reference from the same category with the fit you want. For a thick sweatshirt, use another sweatshirt rather than a stretchy T-shirt. Lay it on a flat surface and record how each measurement is taken. Chest width from armpit to armpit, length from a defined starting point, shoulders and sleeves usually provide more context than the letter on the label. Keep a photograph of your measuring method.',
'Distinguish garment measurements from body measurements. A seller’s chart may give a full circumference while you have measured a flat width. Unless both figures use the same method, they are not directly comparable. Doubling a flat measurement does not automatically produce a recommended body size either: the cut, material and intended ease still matter.',
'Write down which dimensions are essential and which differences you could tolerate. This gives you a decision rule before you look at available sizes. It also prevents a tempting photograph or a low price from making you overlook the dimension most likely to make the item unsuitable.'
]},
{heading:'Read the chart for the current variant',paragraphs:[
'Open the exact listing you intend to order and find the chart associated with that version. Check units, column labels and any measurement tolerance the seller states. A chart from another colour, production version or older listing may not apply. Save the image or values you relied on alongside the URL and exact variant.',
'If a decisive dimension is missing, ask before ordering. A reply such as “normal sizing” does not establish a jacket’s chest width or a pair of trousers’ length. Specify the starting point, finishing point and unit. If the seller cannot provide enough information, consider a better-documented listing. Choosing a size at random simply moves the uncertainty to the warehouse stage.'
]},
{heading:'Worked example: compare two sweatshirt sizes',paragraphs:[
'Your reference sweatshirt measures 58 cm across the chest and 70 cm in length when laid flat. A fictional chart lists M as 57 cm by 69 cm and L as 60 cm by 72 cm. The useful comparison is that M is 1 cm smaller on both dimensions, while L is 2 cm larger. These are illustrative numbers, not a real seller’s chart or a universal size recommendation.',
'Next, decide which difference fits your intended result. Someone seeking the same fit may choose differently from someone wanting a roomier silhouette. Check sleeves and shoulders too, because a similar chest measurement does not guarantee similar proportions. If the listing states a tolerance, compare it with the range you could accept before making a selection.',
'Do not resolve a decisive mismatch by averaging the sizes mentally. If neither option satisfies the measurements that matter, the cut may not suit your needs. Record why you chose a size and what you will check at arrival. That prior decision rule makes it easier to judge QC evidence without accepting an unsuitable item merely because you have waited for it.'
]},
{heading:'Trousers, jackets and stretch fabrics need clear methods',paragraphs:[
'For trousers, check the waist using the seller’s method, together with rise, thigh width and length. An elastic waist measured at rest is not the same as its maximum stretched circumference. Request clarification about the fabric’s state during measurement instead of comparing it with an unrelated body chart. Your reference should be a garment used in a similar way, not a size you remember buying elsewhere.',
'For jackets and clothing worn over other layers, consider the space and movement you want. Sleeve length may be measured from the shoulder or another point; a dropped shoulder changes how the figures relate to fit. Do not add an arbitrary number of centimetres to every measurement. Define the intended use first, then compare equivalent dimensions.'
]},
{heading:'Shoes: understand centimetres and shape before converting sizes',paragraphs:[
'For footwear, measure both feet consistently and consider the longer measurement when reading the model’s chart. Establish what a centimetre column represents: recommended foot length, insole length or something else. Those figures are not interchangeable. Do not move EU, US or UK conversions between sellers without checking the actual model and chart.',
'Compare with a pair you wear for a similar activity and consider the socks you intend to use. Width, toe shape and internal volume can matter even when length appears suitable. An outsole measurement does not reveal internal space. If you request an insole photograph, use it as supplementary evidence and make sure the measurement method is clear.',
'No single photograph establishes how a shoe will feel while walking. Keep that limitation separate from visible checks such as matching labels, the ordered size and obvious differences between the two shoes. If the available information leaves a significant fit risk, decide whether that uncertainty is acceptable before arranging international shipping.'
]},
{heading:'Ask for a QC measurement that can answer your question',paragraphs:[
'After warehouse arrival, first confirm product identity, variant and label. If the concern is size, request a view with the garment flat, the measuring tape visible and both endpoints identifiable. For example, ask for flat chest width from armpit to armpit without stretching, with the zero mark and final reading visible. Check whether the request is available and what it costs before selecting it.',
'Avoid simply asking staff to check whether the size is right. They do not know your body or preferred fit. Also avoid estimating centimetres from an angled photograph without a scale. If one endpoint cannot be read, request clarification about that particular image. A value inferred from pixels should not be presented as a physical measurement of the garment.'
],links:[link('qc-photos-guide','Read QC photos before shipping'),help]},
{heading:'Resolve differences before consolidation',paragraphs:[
'Compare the warehouse measurement with the saved chart and your reference, allowing for the stated method and tolerance. If there is a discrepancy, retain the photo, ordered option and expected value. Ask whether it reflects an incorrect variant, a different measurement method or the actual dimensions of the product. Those are different situations and may require different responses.',
'Check the conditions and deadlines for your order promptly. Whether an exchange or return is possible depends on that transaction; this guide does not guarantee approval. Keep the item out of an international parcel while the decision remains open. If you accept a difference, record precisely what you accepted so that the decision is not lost among several similar purchases.'
]},
{heading:'Keep useful records after delivery',paragraphs:[
'After receiving the item, add notes about the actual fit, measurements and use. A successful size from one listing is a reference for that product, not for the whole platform. Recheck if the listing changes. Separate personal preferences from observable dimensions so that you remember why the garment worked for you.',
'A useful record includes the URL, product reference, variant, size, chart, QC measurement, date and fit notes. A small set of consistent references is more useful than many recommendations without context. Complete the sizing decision with the full budget: replacing or returning an item can involve additional time and costs.'
],links:[link('usfans-comisiones-coste-total','Plan the total cost of the purchase'),guide]},
],takeaway:'Compare measurements taken in the same way, save the chart for the selected variant and request specific evidence when one dimension determines your decision. A label size is a reference, not a guarantee of fit.'
},
{
standfirst:'People searching for USFans rehearsal or a shipping calculator often share one question: why can a light parcel be expensive to send? The answer depends on the information each shipping service uses to calculate chargeable weight and on the final packaging. This guide explains a numerical example and a way to compare options. Every divisor in the worked examples is hypothetical; use the actual rules and services currently available in your account.',
sections:[
{heading:'Distinguish actual, volumetric and chargeable weight',paragraphs:[
'Actual weight is the mass of the prepared parcel, including its box and protective materials. Volume is the space the parcel occupies. Volumetric weight converts that space using a divisor specified by a shipping service. Chargeable weight is the value ultimately used for billing after applying the service’s comparison rules, minimums or rounding. These terms describe related but different quantities.',
'Before estimating, record where each measurement comes from. A product’s listed weight might not include packaging. A retail box may be removed or rearranged during consolidation. A calculator supplied with approximate dimensions still produces an estimate, even if its result includes cents. The apparent precision of the display is not confirmation of the amount you will finally be charged.',
'Keep estimated and measured values distinguishable in your notes. When new measurements arrive, replace the old assumptions and rerun the comparison. This prevents a later quotation from appearing mysterious simply because you have forgotten which dimensions you entered the first time.'
]},
{heading:'Calculate a hypothetical parcel step by step',paragraphs:[
'Consider a fictional box measuring 40 × 30 × 25 cm with an actual weight of 3 kg. Its volume is 30,000 cm³. If a hypothetical service used a divisor of 5,000, its volumetric weight would be 6 kg. If another used 6,000, the result would be 5 kg. These divisors demonstrate the arithmetic; they are not presented as the current terms of a USFans shipping line.',
'If the first hypothetical service also billed the greater of actual and volumetric weight, it would use 6 kg before any rounding. The parcel weighs 3 kg but takes up space valued at 6 kg under that rule. To work out the shipping charge, you would still need the price bands, minimums, rounding, surcharges and eligibility conditions. Do not multiply that result by a rate advertised for an unrelated service.',
'Check your units carefully. The example’s divisor assumes dimensions in centimetres and gives a result in kilograms. Entering millimetres or metres without adapting the calculation changes the answer completely. Save the three dimensions separately, together with the divisor, service name and date, so that you can reproduce the calculation when comparing a later quote.'
]},
{heading:'Compare packaging with the contents held constant',paragraphs:[
'Imagine the same contents can be prepared in a 40 × 30 × 20 cm box while retaining the protection you need. Volume falls to 24,000 cm³. With the hypothetical divisor of 5,000, volumetric weight becomes 4.8 kg rather than 6 kg. Reducing the height changes the weight calculation, but it does not yet prove a matching percentage saving in the price: the service may charge in bands.',
'Keep the destination, contents and intended protection consistent during the comparison. Removing a box can reduce size while also removing a function you value. Do not compress fragile objects or discard necessary protection merely to achieve a lower figure. Compare the actual revised quotation with the protection or presentation trade-off you are willing to accept.'
]},
{heading:'Decide whether rehearsal packing would change your decision',paragraphs:[
'A packing rehearsal can be worth considering when uncertainty about dimensions affects your choice: several pairs of shoes with boxes, items with different shapes or a parcel close to a service’s limits. Check whether the option is available, what result it provides, what it costs and when it must be requested. The word rehearsal alone does not define what is included.',
'Give specific instructions about what should be retained or removed, and confirm that all included products have been accepted. There is little value in calculating a final parcel while an item may still be returned. If better measurements would not change your choice, or the potential saving is smaller than the service cost, first compare using the information you already have. Rehearsal is a decision tool, not a universal compulsory step.',
'Retain the instructions alongside the result. If a measurement was produced for a parcel without shoe boxes, do not later use it to price a parcel with those boxes restored. The result belongs to the configuration that was actually measured.'
],links:[help]},
{heading:'Supply the calculator with comparable information',paragraphs:[
'Gather the destination country and region, postcode where needed, contents, estimated actual weight, dimensions, value and services. Declare the characteristics the platform uses to determine eligibility. A route available for ordinary clothing may not accept other contents. Filter for usable options first and compare their prices afterwards; the lowest price for an unavailable service is not a real alternative.',
'For each eligible option, retain chargeable weight, full quoted cost, estimated delivery range, available tracking and compensation terms. Also record what the quote excludes. A destination’s tax treatment or documentation requirements cannot be solved by choosing a different divisor. A logistics calculator does not replace the relevant shipping terms or customs requirements.'
],bullets:['Use the same destination and contents for each comparison.','Enter dimensions in the units required by the service.','Record the divisor, rounding and size limits.','Identify included services and outstanding charges.']},
{heading:'Compare one parcel with two complete quotations',paragraphs:[
'Splitting a group may prevent one bulky item from determining the shipping options for everything else. It can also duplicate minimum charges, packaging or services. There is no rule making two parcels universally cheaper. Obtain estimates for one parcel and for two parcels using their respective dimensions and contents, then total every component of each scenario.',
'Compare the number of deliveries, tracking records and protection requirements as well. Do not split orders to misrepresent values or conceal contents. Keep descriptions and documents accurate. If an option only appears cheaper because one expense was omitted or an essential condition changed, correct the comparison before using it to make a decision.'
],links:[link('shipping-cost-guide','Plan international shipping'),link('usfans-comisiones-coste-total','Account for all purchase costs')]},
{heading:'Investigate changes in the final quote',paragraphs:[
'Compare the saved estimate with the prepared parcel: dimensions, weight, quantity, packaging, shipping service and optional extras. Look for an identifiable difference before attributing the increase to an unexplained fee. A taller box, minimum billing weight or selected reinforcement may explain part of the change. Ask for clarification if the breakdown does not account for it.',
'Save the confirmed quote and final parcel details with the packing instructions. If you change the contents or packaging afterwards, check whether new measurements or a new quote are required. The earlier result describes one configuration; it does not guarantee the cost of a parcel to which you have just added another item.'
]},
{heading:'Approve the parcel you actually intend to send',paragraphs:[
'Before authorising shipping, check that the contents match the accepted products, the chosen protection remains in place and there are no unresolved issues. Verify the delivery address and telephone number separately from the price comparison. Selecting an economical service cannot correct an incomplete apartment number or an incorrectly selected destination region.',
'Keep a brief record of why you chose the option: confirmed cost, dimensions used and the condition you valued most. After delivery, that information can improve your next estimate. Do not extrapolate one result to every purchase; contents, packaging, destination and shipping rules can all change.'
],links:[link('usfans-spain-address-checklist','Check a delivery address for Spain'),guide]},
],takeaway:'Calculate using the rules of an available shipping service and measurements of the prepared parcel. Consider rehearsal when more reliable dimensions could change your decision, and compare the complete cost of each packaging option.'
},
{
standfirst:'A USFans link that does not work can describe several different problems: a listing has disappeared, a redirect lost its detail path, the catalogue now shows another product or your chosen variant is unavailable. Identify the result you are seeing before starting again. This guide explains how to recover the useful product reference and verify an alternative without assuming that an old number or photograph still represents the same item.',
sections:[
{heading:'Identify the failure before changing the URL',paragraphs:[
'Open the link and inspect the final address, page title and visible product. If it ends on a homepage, a redirect may have lost the product path. A not-found page means that specific address is not providing a listing. If a different product opens, the link is technically reachable but no longer fulfils the promise made by the original card.',
'An access notice, required sign-in or service restriction does not establish that an item is sold out. Do not try to bypass those controls or download tools claiming to unlock the listing. Use the service’s normal access and support channels while keeping the reference you were looking for. Distinguishing an access problem from a catalogue problem avoids replacing a product without evidence.',
'Write down the result rather than simply marking every failure as broken. A homepage redirect, changed product and unavailable size require different next steps. The record also helps you recognise whether a later check has actually resolved the original problem.'
],bullets:['Homepage instead of listing: check the final path.','Not-found page: search for the reference from the catalogue.','Different product: verify identity and options again.','Correct listing without your option: check that variant’s availability.']},
{heading:'What we observed when checking this catalogue',paragraphs:[
'During the 7 October 2026 review, external catalogue links without www ended on the homepage in the browser. The checked www URLs preserved the product detail pages and the tested search. We also found cards whose old names and images no longer matched the products displayed by their destination addresses.',
'The updated selection therefore uses the checked destination names, main images and visible USD prices. This describes an observation from that review, not a rule for every website. Adding www to any domain is not a universal repair. The useful test is to open the destination, inspect the resulting address and confirm that the visible product matches the reference.',
'A successful check is dated evidence, not a permanent guarantee. Catalogue content, prices and options may change again. Before buying, repeat the identity and variant checks on the current page instead of relying exclusively on the last date shown by an external index.'
],links:[{label:'Open the checked external catalogue',url:'https://www.cnfanshp.com/AllProducts/'}]},
{heading:'Recover the reference, not only its number',paragraphs:[
'Gather the product name, model, category, reference image and variant you needed. Keep the original URL as a historical note. A numeric identifier can help identify a route, but it does not prove product identity or availability. If the listing has changed, do not automatically reuse the old title to describe its current contents.',
'For clothing, add the type, colour, pattern and relevant dimensions. For shoes, distinguish the model and version before comparing photographs. If you only have an image, use its visible details to form a search, but do not infer a seller, composition or authenticity from appearance. Visual similarity helps locate candidates; the current listing must provide the information needed to choose.',
'Keep uncertainty explicit when the reference is incomplete. “Similar appearance, different available size” is more useful than declaring a replacement identical without evidence. The aim is to recover a purchase option that meets your needs, not merely to replace one clickable address with another.'
]},
{heading:'Search in stages and inspect each candidate',paragraphs:[
'Start with a brand or model name and a product type. Add a distinguishing detail if the results are too broad; remove a secondary term if there are no results. Use the catalogue’s own product wording when you know it. An overly long search can exclude listings that describe a similar item in different terms.',
'Open candidates from the relevant category and compare the name, main image, options and price with its currency. Recheck the price after selecting the variant because the initial amount may refer to another option. If the listing provides a further seller or agent link, verify that destination as well before treating the purchase route as recovered.',
'Do not fill a list with barely similar substitutes just to keep it active. A useful alternative must satisfy the characteristics that motivated the original search. Record changes in material, available size or the contents of a set. If no sufficiently documented option exists, leaving the search pending is clearer than presenting an unverified substitute as the same product.'
],links:[link('usfans-index-guide','Use a spreadsheet to build a verifiable shortlist')]},
{heading:'Separate listing availability from variant availability',paragraphs:[
'A product page may remain visible after your colour or size becomes unavailable. Check the selectable options and current notices. A photograph showing the colour you want is not stock confirmation. Nor does a displayed quantity guarantee that the seller can fulfil an order when the agent attempts to place it.',
'If you accept another variant, check the price and measurements again. A different colour or version may use another chart or include different details. Save the final choice and remove outdated descriptions from your notes. Otherwise, you could later compare warehouse QC against a reference you changed during the purchase itself.'
],links:[link('usfans-guia-tallas','Check the selected variant’s measurements')]},
{heading:'Check existing orders before paying again',paragraphs:[
'If the link fails after you have already ordered, use the normal access to your account and inspect the order and messages. Removal of a public listing does not automatically cancel a purchase and is not evidence that you should place it again. Check the transaction’s status and request clarification about that order before creating another one.',
'Keep order numbers, dates and supporting evidence in your private records. Share only the necessary details through an official support channel when asking for help. Do not publish personal information, delivery addresses or complete receipts so that strangers can search for a product. Recovering a listing and resolving the status of a purchase are related but distinct tasks.',
'If support identifies an unavailable variant or another order issue, use that specific information to decide the next step. Avoid assumptions based solely on what an external index displays. The account record and the seller’s current options provide different evidence, and both may be needed to understand the situation.'
],links:[help]},
{heading:'Maintain links you can verify again',paragraphs:[
'A useful list includes the reference, destination URL, selected variant, price with currency and checking date. Add a brief status such as matches, variant unavailable, redirect or pending review. Do not retain a verified label without explaining what was checked. Opening a page does not establish quality, authenticity or seller reliability.',
'When replacing a reference, retain a note explaining the change and review the current purchase conditions. Before consolidation, compare the received product with the recorded variant using QC evidence. Repairing a link restores access to information; the decisions about sizing, total cost and acceptance of the product still remain.'
],links:[link('qc-photos-guide','Compare the received item with QC evidence'),link('usfans-comisiones-coste-total','Recalculate the budget when a product changes'),guide]},
],takeaway:'Check the final address, product identity and selected variant. Recovering a link means reaching a listing you can verify, not simply making a not-found message disappear.'
}
];
