import type { ArticleContent } from "./articleContent";
import type { Lang } from "./i18n";

const en: ArticleContent = {
  standfirst: "A Spain delivery address is not a line of prose. It is a routing record that must survive several systems: the parcel form, the international label, a carrier handoff and the final delivery round. A missing door, a postcode that conflicts with the locality or an unreachable phone can turn an otherwise routine parcel into an avoidable exception. This USFans Spain address checklist shows how to prepare, enter and audit recipient data before parcel submission, without guessing about a route or publishing private information.",
  sections: [
    {
      heading: "Build the address from independent fields",
      paragraphs: [
        "Start outside the parcel form. Create a private worksheet with one field for each piece of delivery data: recipient name, street type, street name, building number, portal or block, staircase, floor, door, five-digit postcode, locality, province, country and reachable phone. Correos forms separate many of these elements, which is a useful model even when another checkout presents only two address lines. Separate fields make omissions visible and reduce the chance that an apartment detail disappears inside a long sentence.",
        "Do not use a sample copied from the internet as your real address. Ask the recipient to provide the exact format used successfully for local deliveries, then compare it with an official postcode search. A safe fictional pattern is “Calle [street], 18, portal 2, 3º B”; it demonstrates order without identifying anyone. If your residence has no portal, block or staircase, leave that field blank rather than inventing a zero or dash that a label system might treat as data.",
      ],
      bullets: ["One fact per field", "No invented apartment components", "Keep the private master record outside the checkout"],
    },
    {
      heading: "Use the recipient name that can support delivery",
      paragraphs: [
        "Enter the real recipient name consistently. Nicknames, social handles and shortened names may be familiar to friends but can be poor identifiers if a carrier, pickup point or customs process requests supporting information. The practical rule is simple: the person named on the parcel should be able to recognise the shipment and respond if the carrier asks for clarification. Do not put identity-document numbers in an ordinary address line unless the live shipping process explicitly asks for them in a dedicated, secure field.",
        "For a company or workplace, confirm whether the organisation name, department and named recipient all fit the available fields. Add the company only when the location accepts personal parcels. A building receptionist cannot route a box from a vague business name alone. Keep names stable from parcel submission through tracking; changing the intended recipient after dispatch may not be available and should never be assumed as a recovery method.",
      ],
    },
    {
      heading: "Preserve the street and apartment hierarchy",
      paragraphs: [
        "Spanish addresses often need more than a street and number. The useful hierarchy is street type and name, number, then portal, block, staircase, floor and door where applicable. Preserve the local abbreviations the recipient normally uses, but avoid decorative punctuation and duplicated labels. If the form has Address line 1 and Address line 2, line 1 should normally carry the street and number; line 2 can carry the building and apartment detail. Never move the postcode into an apartment field simply to make a character limit work.",
        "Check every character against the recipient’s source. Number 18 is not 81; “1º A” is not “I A”; a block letter can be mistaken for a door. Accents and ñ are valid local characters, but some international label systems may normalise them. Keep a plain-Latin backup spelling in your private record only if the form rejects a character. Do not translate street names: “Calle del Sol” should not become “Sun Street”, because local databases and drivers work with the registered name.",
      ],
    },
    {
      heading: "Make postcode, locality and province agree",
      paragraphs: [
        "Treat the five-digit postcode as a validation key, not a guess based on a nearby district. Correos provides an official postcode finder that searches by street, number and city. Use it before parcel submission, especially after a move or when an address sits near a municipal boundary. Then compare the result with the locality and province entered in the parcel form. Autocomplete is helpful, but it is not authority when the selected suggestion belongs to a different place with a similar street name.",
        "A four-way check catches most transcription problems: street and number should resolve to the intended postcode; postcode should match the locality; locality should belong to the selected province; and country must be Spain. Preserve leading zeroes in postcodes. Store the postcode as text in a spreadsheet, because numeric formatting can remove a leading zero and silently create an invalid label. If the official finder and the recipient’s usual address disagree, pause and resolve the difference before paying for the parcel.",
      ],
    },
    {
      heading: "Flag the Spanish destination region before line selection",
      paragraphs: [
        "Spain is not one interchangeable delivery zone. A mainland address, the Balearic Islands, the Canary Islands, Ceuta and Melilla can produce different route availability, handoffs or document requirements. This checklist does not predict those conditions. Its job is to label the destination correctly before you compare live shipping options. Record the actual province and postcode first; never choose a mainland province merely to reveal a cheaper quote.",
        "When the stored items are ready, compare only the lines that the live parcel tool offers for the exact destination and contents. A line shown for one Spanish address is not evidence that it serves every Spanish territory. If the platform flags a restriction or requests additional information, stop and follow the current instructions. Region-aware preflight is a separate decision from address formatting, but both depend on accurate recipient data.",
      ],
    },
    {
      heading: "Provide a phone that can answer the last mile",
      paragraphs: [
        "Use a mobile number that the recipient checks and can answer during delivery. Include the correct country code when the form requests international format, and do not repeat the code if the interface inserts it automatically. A phone field is operational data: it may be used for a delivery notice, access question or exception. A disconnected number or a number belonging to someone who does not know about the parcel removes a useful recovery channel.",
        "Email can also carry tracking or delivery messages, but neither contact method repairs a wrong physical address. Confirm spelling, country code and availability with the recipient. Never place a phone number in the public order note, product remark or article screenshot. Use the dedicated checkout fields, keep the private record securely, and share tracking only with the intended recipient.",
      ],
    },
    {
      heading: "Run a copy-lock test before you pay",
      paragraphs: [
        "Address errors often appear during copying rather than research. After entering the parcel form, compare it character by character with the master record. Check whether the interface trimmed Address line 2, replaced a special character, dropped a leading zero or duplicated the province. If a field has a length limit, shorten only standard labels or move a complete apartment component to the correct second line. Do not compress the address until a number becomes ambiguous.",
        "Then use a reverse read: postcode and locality, province and country, street and number, apartment detail, recipient, phone. Reading in a different order makes your brain less likely to glide over a familiar typo. Save a private screenshot of the final summary if it does not expose the data to a public location. The goal is an evidence trail for your own comparison, not a document to post online.",
      ],
    },
    {
      heading: "Final two-pass USFans Spain address audit",
      paragraphs: [
        "Pass one is postal. Confirm the real recipient name; registered street name and number; every required portal, block, staircase, floor and door; five-digit postcode with leading zero preserved; matching locality and province; Spain as country; and a reachable phone. Pass two is parcel-specific. Confirm that the destination region is correct, the live route accepts the parcel contents, the label preview retains all fields, and no product remark has been mistaken for delivery instructions.",
        "Do not submit if a material field is uncertain. One message to the recipient or one official postcode lookup is cheaper than an address correction, return or failed delivery. After payment, preserve the final address summary and tracking reference privately. This workflow cannot guarantee delivery, because carriers and border processes remain outside the buyer’s control. It does remove the preventable errors that come from guessing, collapsing fields or approving a label without reading it.",
      ],
    },
  ],
  takeaway: "Prepare the address as structured data: verified recipient, complete street hierarchy, matching five-digit postcode/locality/province, correct destination region and reachable phone. Compare the final label with that private record twice before parcel submission.",
};

const compact = (standfirst: string, headings: string[], bodies: string[], takeaway: string): ArticleContent => ({
  standfirst,
  sections: headings.map((heading, index) => ({ heading, paragraphs: [bodies[index]] })),
  takeaway,
});

const es = compact(
  "Una dirección de entrega en España es un registro de ruta, no una frase libre. Debe conservar nombre, calle, vivienda, código postal, localidad, provincia y contacto desde el formulario hasta el reparto. Esta lista permite revisar esos datos antes de enviar el paquete.",
  ["Construye campos separados", "Usa un destinatario identificable", "Conserva la jerarquía de la vivienda", "Cruza código postal, localidad y provincia", "Marca la región de destino", "Añade un teléfono operativo", "Haz una prueba de copia", "Auditoría final en dos pasadas"],
  [
    "Prepara en privado campos separados para nombre, tipo y nombre de vía, número, portal, bloque, escalera, piso, puerta, código postal de cinco cifras, localidad, provincia, país y teléfono. Los formularios de Correos separan estos componentes y su buscador oficial permite comprobar calle, número y ciudad. Deja vacío lo que no exista; no inventes ceros ni guiones.",
    "Escribe el nombre real que pueda respaldar la entrega, no un alias. En una empresa, confirma que acepta paquetes personales y añade departamento o persona cuando proceda. No pongas números de documento en una línea libre salvo que el proceso activo los solicite en un campo seguro.",
    "La línea principal debe mantener vía y número; la segunda puede contener portal, bloque, escalera, piso y puerta. Revisa números y letras, conserva el nombre oficial de la calle y no lo traduzcas. Si un sistema rechaza un carácter, guarda también una versión latina clara sin cambiar el significado.",
    "Consulta el código postal con calle, número y ciudad, conserva los ceros iniciales y comprueba que localidad y provincia coinciden. Guarda el código como texto en una hoja de cálculo. Si el dato habitual y el buscador oficial discrepan, resuélvelo antes de pagar.",
    "Península, Baleares, Canarias, Ceuta y Melilla no son zonas intercambiables. Registra provincia y código reales y compara solo las líneas que el sistema muestre para ese destino y contenido. Nunca elijas otra provincia para obtener una estimación más barata.",
    "Usa un móvil que el destinatario atienda, con prefijo internacional solo cuando corresponda. Comprueba también el correo, pero recuerda que ningún aviso corrige una dirección física errónea. Introduce los contactos solo en campos privados del envío.",
    "Compara el resumen carácter por carácter con el registro maestro: línea 2, caracteres, ceros, provincia y teléfono. Lee después en orden inverso para detectar errores familiares. Guarda la confirmación de forma privada, nunca en una captura pública.",
    "Primera pasada postal: nombre, vía, número, vivienda, código, localidad, provincia, país y teléfono. Segunda pasada del paquete: región correcta, línea disponible para el contenido y etiqueta completa. Si falta un dato material, pregunta o comprueba antes de enviar.",
  ],
  "Trata la dirección como datos estructurados y compárala dos veces con la etiqueta final. Verificar antes de pagar elimina errores evitables, aunque no garantiza la actuación posterior del transportista.",
);

const fr = compact("Une adresse espagnole est un ensemble de données d’acheminement. Cette liste vérifie le destinataire, l’immeuble, le code postal et le contact avant la soumission du colis.", ["Séparer les champs", "Identifier le destinataire", "Respecter la hiérarchie du logement", "Faire correspondre code, ville et province", "Identifier la zone espagnole", "Donner un téléphone joignable", "Tester la copie", "Contrôle final en deux passes"], ["Préparez séparément nom, voie, numéro, portail, bloc, escalier, étage, porte, code postal à cinq chiffres, localité, province, pays et téléphone. Laissez vide tout élément inexistant.", "Utilisez le vrai nom capable de soutenir la remise, pas un pseudonyme. Pour une entreprise, confirmez qu’elle accepte le colis. Un numéro d’identité ne va que dans un champ sécurisé explicitement demandé.", "Gardez rue et numéro sur la première ligne et les détails du logement sur la seconde. Ne traduisez pas le nom officiel de la rue et vérifiez soigneusement chiffres, lettres et abréviations.", "Vérifiez rue, numéro et ville dans l’outil officiel de Correos. Conservez les zéros initiaux et faites correspondre code postal, localité et province avant de payer.", "Péninsule, Baléares, Canaries, Ceuta et Melilla peuvent avoir des options différentes. Enregistrez la province réelle et comparez uniquement les lignes proposées au véritable code postal.", "Saisissez un mobile que le destinataire consulte, avec l’indicatif seulement selon le format demandé. Utilisez les champs privés, jamais une remarque publique.", "Comparez le récapitulatif caractère par caractère avec votre fiche privée, puis relisez en ordre inverse. Vérifiez que la deuxième ligne et les zéros n’ont pas disparu.", "Passe postale : identité et adresse complète. Passe colis : région, éligibilité de la ligne et aperçu de l’étiquette. Toute incertitude matérielle doit être résolue avant l’envoi."], "Une adresse structurée et relue deux fois réduit les exceptions évitables sans promettre le résultat du transport.");

const de = compact("Eine spanische Lieferadresse ist ein strukturierter Routendatensatz. Diese Checkliste prüft Empfänger, Gebäudeangaben, Postleitzahl und Kontakt vor der Paketabgabe.", ["Felder getrennt aufbauen", "Empfänger eindeutig nennen", "Wohnungsstruktur erhalten", "PLZ, Ort und Provinz abgleichen", "Zielregion kennzeichnen", "Erreichbare Telefonnummer", "Kopiertest durchführen", "Zwei abschließende Prüfungen"], ["Erfasse Name, Straßenart und -name, Nummer, Portal, Block, Treppe, Etage, Tür, fünfstellige PLZ, Ort, Provinz, Land und Telefon getrennt. Nicht vorhandene Angaben bleiben leer.", "Nutze den echten Namen, der die Zustellung stützen kann. Bei einer Firma müssen Annahme, Abteilung und Person geklärt sein. Ausweisnummern gehören nur in ausdrücklich verlangte sichere Felder.", "Straße und Nummer stehen in Zeile eins; Portal, Block, Treppe, Etage und Tür können in Zeile zwei. Übersetze den amtlichen Straßennamen nicht und prüfe Zahlen sowie Buchstaben.", "Prüfe Straße, Nummer und Ort mit der offiziellen Correos-Postleitzahlsuche. Erhalte führende Nullen und gleiche PLZ, Ort und Provinz ab.", "Festland, Balearen, Kanaren, Ceuta und Melilla können unterschiedliche Optionen haben. Gib die echte Provinz an und vergleiche nur für die genaue Adresse angebotene Linien.", "Verwende eine erreichbare Mobilnummer und füge die Landesvorwahl nur passend zum Formular hinzu. Kontaktangaben gehören in private Versandfelder.", "Vergleiche die Zusammenfassung Zeichen für Zeichen mit dem privaten Datensatz und lies anschließend rückwärts. Achte auf gekürzte zweite Zeilen und entfernte Nullen.", "Postprüfung: vollständige Anschrift. Paketprüfung: richtige Region, zulässiger Inhalt und vollständige Etikettenvorschau. Unklare Pflichtdaten vor Zahlung klären."], "Strukturierte Daten und zwei Vergleiche verhindern vermeidbare Adressfehler, ohne eine Zustellgarantie zu geben.");

const it = compact("Un indirizzo spagnolo è un record di instradamento strutturato. Questa lista controlla destinatario, edificio, CAP e contatto prima di inviare il pacco.", ["Separare i campi", "Identificare il destinatario", "Mantenere la gerarchia dell’abitazione", "Allineare CAP, località e provincia", "Segnalare la zona spagnola", "Telefono raggiungibile", "Testare la copia", "Doppio controllo finale"], ["Prepara separatamente nome, tipo e nome della via, numero, portale, blocco, scala, piano, porta, CAP di cinque cifre, località, provincia, paese e telefono. Non inventare campi assenti.", "Usa il nome reale che possa sostenere la consegna, non un alias. Per un’azienda verifica accettazione, reparto e persona. I documenti vanno solo in campi sicuri esplicitamente richiesti.", "Via e numero vanno nella prima riga; i dettagli dell’appartamento nella seconda. Non tradurre il nome ufficiale e verifica numeri, lettere e abbreviazioni.", "Controlla via, numero e città con lo strumento ufficiale di Correos. Conserva gli zeri iniziali e fai coincidere CAP, località e provincia.", "Penisola, Baleari, Canarie, Ceuta e Melilla possono avere opzioni diverse. Registra la provincia reale e confronta solo le linee offerte per il CAP esatto.", "Inserisci un cellulare seguito dal destinatario e usa il prefisso internazionale secondo il modulo. I contatti restano nei campi privati di spedizione.", "Confronta il riepilogo carattere per carattere con il record privato, poi rileggi al contrario. Cerca righe tagliate, zeri mancanti e province duplicate.", "Prima verifica postale: indirizzo completo. Seconda verifica del pacco: regione, ammissibilità del contenuto ed etichetta. Risolvi ogni dubbio prima del pagamento."], "Dati strutturati e due letture riducono gli errori evitabili senza garantire la consegna del vettore.");

const pl = compact("Hiszpański adres dostawy jest uporządkowanym rekordem trasy. Ta lista sprawdza odbiorcę, budynek, kod pocztowy i kontakt przed nadaniem paczki.", ["Rozdziel pola", "Jednoznaczny odbiorca", "Zachowaj hierarchię lokalu", "Uzgodnij kod, miasto i prowincję", "Oznacz region Hiszpanii", "Działający telefon", "Test kopiowania", "Końcowa kontrola dwuetapowa"], ["Oddziel nazwę, typ i nazwę ulicy, numer, portal, blok, klatkę, piętro, drzwi, pięciocyfrowy kod, miejscowość, prowincję, kraj i telefon. Nie wymyślaj brakujących elementów.", "Użyj prawdziwego imienia, nie pseudonimu. W firmie potwierdź odbiór i dział. Numer dokumentu wpisuj tylko w bezpiecznym polu wyraźnie wymaganym przez bieżący proces.", "Ulica i numer trafiają do pierwszej linii, a szczegóły lokalu do drugiej. Nie tłumacz urzędowej nazwy ulicy i dokładnie sprawdź cyfry, litery oraz skróty.", "Sprawdź ulicę, numer i miasto w oficjalnej wyszukiwarce Correos. Zachowaj zera początkowe i zgodność kodu, miejscowości oraz prowincji.", "Kontynent, Baleary, Kanary, Ceuta i Melilla mogą mieć inne opcje. Wpisz prawdziwą prowincję i porównuj tylko linie dostępne dla dokładnego kodu.", "Podaj aktywny telefon odbiorcy i dodaj prefiks tylko zgodnie z formularzem. Dane kontaktowe należą do prywatnych pól wysyłki.", "Porównaj podsumowanie znak po znaku z prywatnym rekordem, potem przeczytaj od końca. Sprawdź drugą linię, zera i prowincję.", "Kontrola pocztowa obejmuje pełny adres; kontrola paczki obejmuje region, dopuszczalność zawartości i etykietę. Niepewne dane wyjaśnij przed płatnością."], "Uporządkowany adres i dwa porównania ograniczają możliwe do uniknięcia wyjątki, ale nie gwarantują pracy przewoźnika.");

const pt = compact("Um endereço espanhol é um registo estruturado de encaminhamento. Esta lista confirma destinatário, edifício, código postal e contacto antes de submeter o pacote.", ["Separar os campos", "Identificar o destinatário", "Preservar a hierarquia da habitação", "Alinhar código, localidade e província", "Assinalar a região espanhola", "Telefone contactável", "Testar a cópia", "Auditoria final em duas passagens"], ["Prepare nome, tipo e nome da via, número, portal, bloco, escada, piso, porta, código postal de cinco dígitos, localidade, província, país e telefone separadamente. Não invente elementos.", "Use o nome real capaz de apoiar a entrega. Numa empresa, confirme receção, departamento e pessoa. Documento de identidade só entra num campo seguro expressamente pedido.", "Rua e número ficam na primeira linha; detalhes da habitação na segunda. Não traduza o nome oficial e confirme números, letras e abreviaturas.", "Valide rua, número e cidade na ferramenta oficial dos Correos. Preserve zeros iniciais e faça coincidir código, localidade e província.", "Península, Baleares, Canárias, Ceuta e Melilla podem ter opções diferentes. Registe a província real e compare apenas linhas oferecidas para o código exato.", "Indique um telemóvel atendido pelo destinatário e use o indicativo conforme o formulário. Contactos pertencem aos campos privados do envio.", "Compare o resumo carácter por carácter com o registo privado e depois leia ao contrário. Procure a segunda linha cortada, zeros removidos ou província duplicada.", "Primeira passagem postal: endereço completo. Segunda passagem do pacote: região, conteúdo elegível e etiqueta. Resolva qualquer dado incerto antes do pagamento."], "Dados estruturados e duas leituras reduzem erros evitáveis sem prometer a entrega do transportador.");

const zh = compact("西班牙收货地址是一组用于路由的结构化数据，而不是随意拼成的一句话。本清单在提交包裹前核对收件人、楼栋信息、邮编、城市和联系方式。", ["拆分地址字段", "使用可核实的收件人", "保留住宅层级", "核对邮编、城市和省份", "标明西班牙目的地区域", "填写可联系的电话", "执行复制检查", "两轮最终审计"], ["分别保存姓名、道路类型与名称、门牌号、单元、楼栋、楼梯、楼层、门号、五位邮编、城市、省份、国家和电话。不存在的字段留空，不要填零或横线。", "填写能配合收件的真实姓名，不使用网名。寄到公司时先确认是否代收并注明部门或联系人。证件号码只应放在当前流程明确要求的安全字段中。", "第一行保留街道和门牌，第二行放单元、楼栋、楼梯、楼层和门号。不要翻译官方街道名，并逐字核对数字、字母和缩写。", "使用 Correos 官方工具按街道、门牌和城市查邮编，保留开头的零，并确保邮编、城市和省份一致。若有冲突，付款前先确认。", "西班牙本土、巴利阿里群岛、加那利群岛、休达和梅利利亚可能有不同选项。填写真实省份，只比较准确邮编下当前显示的线路。", "填写收件人会接听的手机号，并按表单要求处理国际区号。电话和邮箱只放在私密运输字段，不放公开备注或截图。", "把结算摘要与私密原始记录逐字比较，再倒序阅读。重点检查第二行是否截断、邮编开头零是否消失、省份是否重复。", "第一轮核对完整邮政地址；第二轮核对地区、商品是否符合线路以及标签是否保留全部字段。有关键疑问时先确认再付款。"], "把地址当作结构化数据，并与最终标签核对两次，可以消除可避免的错误，但不能保证承运商后续操作。");

export const spainAddressArticle: Record<Lang, ArticleContent> = { es, en, fr, de, it, pl, pt, zh };
