import type { Metadata } from "next";
import { InnerHero, SiteChrome } from "../site-chrome";
export const metadata:Metadata={title:"Hipobuy Spreadsheet FAQ 2026",description:"Clear answers about Hipobuy spreadsheet links, USD references, QC photos and shipping estimates."};
const faqs=[
  ["What is Hipobuy?","Hipobuy describes itself as a global shopping app that helps users purchase products from Chinese marketplaces such as Taobao and 1688, then arrange international shipping. It is an intermediary workflow, not the manufacturer of the products shown in seller listings."],
  ["Does Hipobuy ship to more than 200 countries?","The current Apple App Store and Google Play descriptions say the service can deliver to more than 200 countries. That is a platform-level claim, not a guarantee that every route accepts every destination or item. Check live route eligibility for the actual parcel."],
  ["Is 90-day warehouse storage currently advertised?","Yes. Hipobuy’s current official app descriptions advertise 90 days of free storage so orders can be collected before shipping. Treat that as a current platform statement and confirm the live account terms, start date and any item-specific limits before relying on the full period."],
  ["Does ‘delivery in as fast as 5 days’ mean my parcel will arrive in five days?","No. The official app listing uses ‘as fast as 5 days’ as a best-case shipping claim. It is not a universal delivery promise. Processing, route choice, carrier handoff, customs and last-mile delivery can all change the actual timeline."],
  ["Are spreadsheet prices the final amount paid?","No. A spreadsheet price is a dated product reference. A realistic total may also include domestic delivery to the warehouse, optional services, packing, payment or exchange effects and international shipping calculated from the completed parcel."],
  ["What does ‘link checked’ mean?","It means the destination page responded during the stated check. It does not prove that a variant is in stock, that the seller is reliable, that the product will match promotional photographs or that a shipping route will accept it."],
  ["Do product photographs replace warehouse QC photos?","No. Seller images describe a listing. Warehouse photos can only document visible aspects of the item that arrived, such as color, labels, quantity, measurements and obvious damage. They cannot prove long-term durability, composition or fit on your body."],
  ["Can this sheet predict Hipobuy shipping cost?","Only as a planning range. The final quote needs destination, measured weight, parcel dimensions, contents, packing choices, route rules and current pricing. Compare routes only after confirming that each one is eligible for the parcel."],
  ["What do current customer reviews actually show?","Public reviews are mixed: users report both easy ordering and fast delivery, as well as complaints about shipping cost, refunds and support. Trustpilot currently marks Hipobuy’s rating unavailable because of a guidelines breach and says it removed a number of fake reviews. Treat individual reviews as anecdotes, not proof of a typical outcome."],
  ["Is this the official Hipobuy website?","No. This is an independent product-discovery and education resource. Platform policies, fees, storage rules, available routes and checkout terms can change, so confirm time-sensitive information in the live service before payment or parcel submission."],
];
export default function FAQPage(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))};return <SiteChrome><main className="inner-main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><InnerHero eyebrow="Fact-checked · reviewed 24 Aug 2026" title="Know what the sheet can—and cannot—tell you." intro="These answers separate current official platform statements from planning assumptions and third-party anecdotes. Live checkout and route terms always take priority."/><section className="faq-list">{faqs.map((f,i)=><details key={f[0]} open={i===0}><summary><span>{String(i+1).padStart(2,"0")}</span>{f[0]}<b>+</b></summary><p>{f[1]}</p></details>)}</section></main></SiteChrome>}
