import type { Article, Locale } from "./content";

export const arrivalChecklist: Record<Locale, Article> = {
  en: {
    slug: "superbuy-warehouse-arrival-checklist",
    title: "Superbuy Warehouse Arrival Checklist: Verify an Order Before the Next Step",
    dek: "An evidence-led intake routine for matching the stored item to the Shopping Agent order before extra photos, after-sales action or parcel submission.",
    sections: [
      { heading: "Treat warehouse arrival as a new decision point", paragraphs: ["A Superbuy Shopping Agent order reaching the warehouse means the domestic seller-to-warehouse leg has produced an intake record. It does not mean the product is automatically correct, ready to ship internationally or proven to meet every seller claim. The useful response is to reconcile the order while the original selection and seller page are still easy to retrieve.", "This checklist is for Shopping Agent purchases. Parcel Forwarding begins from a different ownership and service context: the customer sends an already purchased item to a forwarding address. Do not transfer shopping-agent purchasing, seller after-sales or standard inspection assumptions to a forwarded parcel unless the current forwarding terms expressly provide them.", "Open three records side by side: the order confirmation, the live or saved seller listing and the warehouse item page. Your first question is identity, not quality. Confirm that the stored record belongs to the order you intended to evaluate before interpreting photographs or planning a parcel." ] },
      { heading: "Reconcile the order identity", paragraphs: ["Match the warehouse item number with the purchasing order, then compare product title, seller, selected option, colour, size, model, quantity and any included pieces. A translated warehouse title may be shorter than the marketplace title, so use the order number and selected variant rather than demanding identical wording.", "Look for differences that change what you own: one item instead of a set, a different colour code, an unexpected size tag, a deposit-only order, a missing accessory or a substituted model. Record each important field as match, mismatch or not visible. Do not mark an unseen detail as accepted merely because the general silhouette looks familiar.", "Keep the original listing evidence. Seller pages can change after purchase, and a later screenshot may no longer show the option you selected. A saved order screen, option image and concise purchase note create a better comparison than memory." ] },
      { heading: "Read the warehouse intake data before the photos", paragraphs: ["Superbuy's current Shopping Agent guide says received items are weighed and inspected and that three photos of the actual product are provided. Read the stored item's recorded weight and any dimensions or status notes that appear in the account. They are intake data, not the final packed parcel measurements.", "An intake weight can help identify a large discrepancy, but it should not be treated as an exact international shipping quote. The later parcel can add or remove seller packaging, combine multiple items and use protective services. Final route pricing depends on the finished parcel and available line rules.", "If the intake record flags an issue, read that message before judging the images. A note about damage, prohibited characteristics, missing pieces or an unusual size may define the action more clearly than a thumbnail." ] },
      { heading: "Inspect the standard photographs against a written brief", paragraphs: ["Use the three published standard images as a visual checkpoint, not a universal inspection certificate. First confirm visible product identity, quantity and option. Then examine overall form, major panels, colour family, labels that are shown, surface marks, damaged packaging and included accessories visible in the frame.", "Apply category-specific checks. For shoes, compare the pair, visible size labels, outsole and obvious asymmetry. For clothing, compare the colour, printed or embroidered placement, size label and general construction. For bags, check shape, hardware, strap count and corners. For fragile items, inspect the visible exterior while remembering that photographs do not prove survival in international transport.", "Lighting and perspective can mislead. A single shadow is not automatically a stain, and a wide-angle edge can distort shape. Look for the same issue across images or request one targeted clarification when a material decision depends on it." ] },
      { heading: "Classify every open question by the evidence needed", paragraphs: ["Place an open question into one of four buckets: visible in existing photos, answerable with a targeted photo or measurement, answerable only by a documented optional service, or not reasonably verifiable at the warehouse. This prevents a vague request for more inspection from producing more images without a better decision.", "A chest measurement, insole length, size tag, connector panel or all set pieces laid out together can be a targeted request. Material composition, authenticity, long-term durability, waterproofing and exact fit usually cannot be proven from ordinary warehouse photographs. Functional testing should never be assumed unless a current, clearly described service provides it for the item.", "Write the decision rule before requesting evidence: 'keep if the flat chest is at least 58 cm' or 'seek after-sales help if the second strap is absent.' A rule turns information into an action." ] },
      { heading: "Choose accept, clarify or after-sales", paragraphs: ["Accept means the available evidence matches the selected order closely enough for your risk tolerance. Clarify means one material question could still be resolved by a specific photo, measurement or order message. After-sales means the record documents a wrong option, missing part, visible damage or another mismatch that crosses your pre-set threshold.", "When raising a problem, state the expected field, observed field and supporting image. 'Ordered black, size 42; intake photo shows blue, size 41' is actionable. 'Looks bad' is not. Keep the item out of an international parcel while the case is open, because seller-side correction becomes harder after outbound submission.", "Available remedies depend on current timing, seller cooperation and the live order instructions. Use the current account path and Help Center rather than importing an old return window from a forum or from another platform." ] },
      { heading: "Connect intake evidence to storage and parcel planning", paragraphs: ["Once the item is accepted, record the arrival date and the parcel group it may join. The purpose is not to turn this article into a storage calendar; it is to stop accepted goods from drifting without an owner or next decision. Different seller arrivals may justify consolidation, but the oldest item and current account deadline should remain visible.", "Do not use intake weight as the final parcel total. Decide whether original packaging matters, whether a shoe box can be folded or removed, whether a fragile item needs reinforcement and whether different product types should be split. Then compare routes only after the parcel contents and packaging request are defined.", "Keep the identity evidence until delivery. If the received parcel later has a missing or different item, the order, intake images, parcel submission record and unboxing evidence form a traceable chain." ] },
      { heading: "Use a five-minute arrival worksheet", paragraphs: ["Create one row per item with these columns: order number, seller, selected variant, quantity, intake status, recorded weight, visible match, visible problem, open question, evidence request, decision and next review date. The worksheet can be a note; consistency matters more than software.", "Complete it when the arrival notice appears, not days later. Save only evidence needed to explain the decision and avoid personal address or payment details in shared files. Mark a resolved question rather than deleting it so the reasoning remains visible.", "The warehouse arrival checkpoint is valuable because it sits between seller delivery and international commitment. A disciplined five-minute reconciliation catches wrong identities, separates visible facts from unknowns and gives every stored item a clear next action. That is different from merely watching an order status: it is an evidence-based intake decision." ] }
    ]
  },
  fr: {
    slug: "superbuy-warehouse-arrival-checklist", title: "Arrivée en entrepôt Superbuy : checklist avant l’étape suivante", dek: "Une méthode de rapprochement entre commande Shopping Agent, données d’entrée et preuves visibles avant photo supplémentaire, après-vente ou colis.",
    sections: [
      { heading:"Traiter l’arrivée comme une nouvelle décision", paragraphs:["L’arrivée d’une commande Shopping Agent crée un dossier d’entrée; elle ne prouve pas automatiquement que tout est correct ou prêt à partir. Ouvrez commande, annonce sauvegardée et fiche d’entrepôt côte à côte.","Ce guide ne concerne pas le Parcel Forwarding. Un colis déjà acheté et envoyé à une adresse de transfert relève d’un autre cadre; ne lui appliquez pas les promesses d’achat, d’inspection ou d’après-vente du Shopping Agent sans règle explicite."]},
      { heading:"Rapprocher l’identité de la commande", paragraphs:["Comparez numéro, vendeur, option, couleur, taille, modèle, quantité et pièces incluses. Le titre traduit peut être plus court; le numéro et la variante sont plus fiables qu’une égalité mot à mot.","Classez chaque champ : conforme, différent ou non visible. Conservez l’écran d’option original, car la fiche vendeur peut changer après l’achat."]},
      { heading:"Lire les données d’entrée avant les photos", paragraphs:["Le guide Shopping Agent actuel indique pesée, inspection et trois photos du produit réel. Lisez poids enregistré, statut et éventuelles notes. Ce poids d’entrée n’est pas la mesure finale du colis emballé.","Une alerte de dommage, pièce manquante ou caractéristique restreinte peut guider l’action mieux qu’une vignette. L’emballage et la consolidation modifieront plus tard les données d’expédition."]},
      { heading:"Comparer les photos à une consigne écrite", paragraphs:["Confirmez identité, quantité et option, puis forme, panneaux, couleur, étiquette visible, traces et accessoires. Pour chaussures, comparez la paire; pour vêtements, taille et placement; pour sacs, forme, quincaillerie et sangles.","Les photos ne certifient ni authenticité, matière interne, durée ni survie au transport. Ombre et perspective peuvent tromper; cherchez un problème sur plusieurs vues."]},
      { heading:"Définir la preuve nécessaire", paragraphs:["Classez la question : déjà visible, résoluble par photo ou mesure ciblée, nécessitant un service documenté, ou non vérifiable. Une mesure de poitrine, longueur de semelle ou vue des pièces du lot est précise; « plus de QC » ne l’est pas.","Écrivez la règle de décision avant la demande, par exemple conserver si la poitrine atteint 58 cm. La preuve doit conduire à une action."]},
      { heading:"Accepter, clarifier ou lancer l’après-vente", paragraphs:["Accepter signifie que les preuves suffisent; clarifier qu’une question matérielle peut être résolue; après-vente qu’un écart visible franchit votre seuil.","Décrivez attendu, observé et photo. Gardez l’article hors du colis pendant le dossier et suivez les instructions actuelles du compte et du centre d’aide, pas une ancienne publication."]},
      { heading:"Relier réception, stockage et colis", paragraphs:["Après acceptation, notez date d’arrivée et groupe de colis envisagé. Gardez visible l’article le plus ancien et son échéance actuelle.","N’utilisez pas le poids d’entrée comme total final. Décidez boîte, protection et séparation avant de comparer les lignes. Conservez les preuves jusqu’à la livraison."]},
      { heading:"Utiliser une fiche de cinq minutes", paragraphs:["Une ligne par article : commande, vendeur, variante, quantité, statut, poids, correspondance, problème, question, preuve, décision et date de revue.","Complétez-la à la notification. Cette discipline détecte les mauvaises identités, sépare faits et inconnues et donne une action claire à chaque article stocké."]}
    ]
  },
  de: {
    slug: "superbuy-warehouse-arrival-checklist", title: "Superbuy-Lagereingang: Checkliste vor dem nächsten Schritt", dek: "Bestellung, Eingangsdaten und sichtbare Belege einer Shopping-Agent-Bestellung abgleichen, bevor Zusatzfoto, After-Sales oder Paket folgen.",
    sections: [
      { heading:"Lagereingang als neuen Entscheidungspunkt behandeln", paragraphs:["Der Eingang einer Shopping-Agent-Bestellung erzeugt einen Lagerdatensatz; er beweist nicht automatisch Richtigkeit oder Versandbereitschaft. Bestellbestätigung, gespeichertes Listing und Lagerseite nebeneinander öffnen.","Parcel Forwarding hat einen anderen Ausgangspunkt. Einkauf, Verkäufer-After-Sales und Standardprüfung nicht auf ein bereits gekauftes Weiterleitungspaket übertragen, sofern aktuelle Bedingungen dies nicht ausdrücklich vorsehen."]},
      { heading:"Bestellidentität abgleichen", paragraphs:["Nummer, Verkäufer, Option, Farbe, Größe, Modell, Menge und Teile vergleichen. Ein übersetzter Lagertitel darf kürzer sein; Nummer und gewählte Variante sind wichtiger als Wortgleichheit.","Jedes Feld als passend, abweichend oder nicht sichtbar markieren. Originales Optionsbild sichern, weil das Verkäuferlisting später geändert werden kann."]},
      { heading:"Eingangsdaten vor den Fotos lesen", paragraphs:["Der aktuelle Shopping-Agent-Leitfaden nennt Wiegen, Prüfen und drei Fotos des tatsächlichen Produkts. Gewicht, Status und Hinweise lesen. Das Eingangsgewicht ist nicht das Endmaß des fertig gepackten Pakets.","Warnhinweise zu Schaden, fehlenden Teilen oder Beschränkungen können die Handlung klarer bestimmen als ein Vorschaubild. Verpackung und Konsolidierung ändern spätere Versanddaten."]},
      { heading:"Standardfotos mit einem Brief vergleichen", paragraphs:["Identität, Menge und Option, danach Form, Hauptpaneele, Farbfamilie, sichtbare Etiketten, Spuren und Zubehör prüfen. Bei Schuhen das Paar, bei Kleidung Größe und Platzierung, bei Taschen Form, Beschläge und Riemen vergleichen.","Fotos beweisen weder Echtheit, innere Materialien, Haltbarkeit noch sicheren Transport. Schatten und Perspektive können täuschen; wichtige Auffälligkeiten über mehrere Ansichten prüfen."]},
      { heading:"Benötigten Beleg bestimmen", paragraphs:["Offene Frage einordnen: bereits sichtbar, mit gezieltem Foto oder Maß lösbar, nur durch dokumentierten Dienst beantwortbar oder im Lager nicht sinnvoll prüfbar. Brustweite, Einlegesohlenlänge oder alle Set-Teile sind präzise; „mehr QC“ nicht.","Vorher Entscheidungsregel schreiben, etwa behalten ab 58 cm Brustweite. Belege müssen eine Handlung ermöglichen."]},
      { heading:"Akzeptieren, klären oder After-Sales", paragraphs:["Akzeptieren heißt, die Belege reichen; klären, eine wichtige Frage ist lösbar; After-Sales, eine dokumentierte Abweichung überschreitet die Grenze.","Erwartetes Feld, Beobachtung und Bild nennen. Artikel während des Falls nicht ins Auslands-Paket geben und aktuelle Konto- und Help-Center-Anweisungen statt alter Forenfristen nutzen."]},
      { heading:"Eingang mit Lagerung und Paket verbinden", paragraphs:["Nach Annahme Eingangsdatum und geplante Paketgruppe notieren. Ältesten Artikel und aktuelle Frist sichtbar halten.","Eingangsgewicht nicht als Endbetrag verwenden. Box, Schutz und Aufteilung vor Routenvergleich entscheiden. Belegkette bis zur Lieferung aufbewahren."]},
      { heading:"Fünf-Minuten-Eingangsblatt nutzen", paragraphs:["Eine Zeile je Artikel: Bestellung, Verkäufer, Variante, Menge, Status, Gewicht, sichtbare Übereinstimmung, Problem, Frage, Beleg, Entscheidung und Prüftermin.","Bei Benachrichtigung ausfüllen. So werden falsche Identitäten erkannt, Fakten von Unbekanntem getrennt und jeder Lagerartikel erhält eine klare nächste Aktion."]}
    ]
  }
};
