export type Locale = "en" | "fr" | "de";

export const ROOT = "https://www.cnfanshp.com";

export const localeNames: Record<Locale, string> = {
  en: "English",
  fr: "Français",
  de: "Deutsch",
};

export const categories = [
  { key: "shoes", href: `${ROOT}/shoes/` },
  { key: "hoodies", href: `${ROOT}/hoodies-sweaters/` },
  { key: "tees", href: `${ROOT}/t-shirts/` },
  { key: "jackets", href: `${ROOT}/jackets/` },
  { key: "bottoms", href: `${ROOT}/pants-shorts/` },
  { key: "headwear", href: `${ROOT}/headwear/` },
  { key: "accessories", href: `${ROOT}/accessories/` },
  { key: "jerseys", href: `${ROOT}/Jersey/` },
  { key: "electronics", href: `${ROOT}/electronics/` },
  { key: "other", href: `${ROOT}/other-stuff/` },
] as const;

export const edit = [
  {
    number: "No. 01",
    image: `${ROOT}/uploads/allimg/20260427/1-26042G03A3226.webp`,
    href: `${ROOT}/AllProducts/6049.html`,
    className: "feature feature--wide",
  },
  {
    number: "No. 02",
    image: `${ROOT}/uploads/allimg/20260427/1-26042G03505957.webp`,
    href: `${ROOT}/AllProducts/6048.html`,
    className: "feature feature--portrait",
  },
  {
    number: "No. 03",
    image: `${ROOT}/uploads/allimg/20260427/1-26042G0310V93.webp`,
    href: `${ROOT}/AllProducts/6047.html`,
    className: "feature feature--small",
  },
  {
    number: "No. 04",
    image: `${ROOT}/uploads/allimg/20260427/1-26042G0293E05.webp`,
    href: `${ROOT}/AllProducts/6046.html`,
    className: "feature feature--offset",
  },
] as const;

const shared = {
  en: {
    nav: { home: "Cover", categories: "Directory", guides: "Guides", faq: "FAQ", articles: "Articles", browse: "Browse all" },
    searchLabel: "Looking for something specific?",
    searchPlaceholder: "Try shoes, hoodie, jersey…",
    searchButton: "Search",
    back: "Back to cover",
    open: "Open",
    read: "Read article",
    updated: "Updated 12 August 2026",
    disclaimer: "Independent Superbuy-related product discovery guide. Not affiliated with or endorsed by Superbuy. Product details, availability, shipping routes and policies can change; verify them before acting.",
    cat: {
      shoes: ["Shoes", "Everyday runners and statement pairs"], hoodies: ["Hoodies & sweaters", "Layers for every rotation"],
      tees: ["T-shirts", "Graphics and daily basics"], jackets: ["Jackets", "Outer layers and seasonal pieces"],
      bottoms: ["Pants & shorts", "Shape, proportion and comfort"], headwear: ["Headwear", "Caps and finishing details"],
      accessories: ["Accessories", "Bags, small goods and extras"], jerseys: ["Jerseys", "Match-day and sport-inspired pieces"],
      electronics: ["Electronics", "Small devices and useful add-ons"], other: ["Other finds", "Everything outside the usual edit"],
    },
  },
  fr: {
    nav: { home: "Couverture", categories: "Répertoire", guides: "Guides", faq: "FAQ", articles: "Articles", browse: "Tout voir" },
    searchLabel: "Vous cherchez quelque chose de précis ?",
    searchPlaceholder: "Essayez chaussures, sweat, maillot…",
    searchButton: "Rechercher",
    back: "Retour à la couverture",
    open: "Ouvrir",
    read: "Lire l’article",
    updated: "Mis à jour le 12 août 2026",
    disclaimer: "Guide indépendant de découverte de produits liés à Superbuy. Ce site n’est ni affilié à Superbuy ni approuvé par celui-ci. Les produits, disponibilités, itinéraires et règles peuvent changer ; vérifiez-les avant d’agir.",
    cat: {
      shoes: ["Chaussures", "Paires quotidiennes et modèles forts"], hoodies: ["Sweats et pulls", "Des couches pour chaque rotation"],
      tees: ["T-shirts", "Graphismes et essentiels"], jackets: ["Vestes", "Couches extérieures et pièces de saison"],
      bottoms: ["Pantalons et shorts", "Forme, proportion et confort"], headwear: ["Couvre-chefs", "Casquettes et détails finaux"],
      accessories: ["Accessoires", "Sacs, petits objets et compléments"], jerseys: ["Maillots", "Pièces sportives et jour de match"],
      electronics: ["Électronique", "Petits appareils et accessoires utiles"], other: ["Autres trouvailles", "Tout ce qui sort de la sélection habituelle"],
    },
  },
  de: {
    nav: { home: "Cover", categories: "Verzeichnis", guides: "Ratgeber", faq: "FAQ", articles: "Artikel", browse: "Alles ansehen" },
    searchLabel: "Suchst du etwas Bestimmtes?",
    searchPlaceholder: "Zum Beispiel Schuhe, Hoodie, Trikot…",
    searchButton: "Suchen",
    back: "Zurück zum Cover",
    open: "Öffnen",
    read: "Artikel lesen",
    updated: "Aktualisiert am 12. August 2026",
    disclaimer: "Unabhängiger Leitfaden zur Entdeckung von Superbuy-bezogenen Produkten. Keine Verbindung zu oder Unterstützung durch Superbuy. Produkte, Verfügbarkeit, Versandwege und Regeln können sich ändern; prüfe sie vor jeder Entscheidung.",
    cat: {
      shoes: ["Schuhe", "Alltagssneaker und auffällige Paare"], hoodies: ["Hoodies & Pullover", "Layer für jede Rotation"],
      tees: ["T-Shirts", "Grafiken und tägliche Basics"], jackets: ["Jacken", "Outerwear und saisonale Stücke"],
      bottoms: ["Hosen & Shorts", "Form, Proportion und Komfort"], headwear: ["Kopfbedeckung", "Caps und letzte Details"],
      accessories: ["Accessoires", "Taschen, Kleinteile und Extras"], jerseys: ["Trikots", "Sport- und Spieltagsstücke"],
      electronics: ["Elektronik", "Kleine Geräte und nützliche Ergänzungen"], other: ["Weitere Funde", "Alles außerhalb der üblichen Auswahl"],
    },
  },
} as const;

export const copy = {
  en: {
    ...shared.en,
    home: {
      eyebrow: "Independent product discovery journal", titleA: "THE", titleB: "SUPERBUY", titleC: "INDEX",
      deck: "A quieter way to move through Superbuy finds—organized as an edit, not an endless feed.",
      coverAlt: "Featured low-profile shoe from the current edit", coverCaption: "Cover find / No. 01",
      directoryKicker: "Directory / 01", directoryIntro: "Choose a section, then browse the complete collection.",
      directoryTitle: "Find your section.", routes: "10 routes",
      editKicker: "The visual edit / 04 finds", editSource: "Images from live listings", editTitle: "Four ways to start.",
      editIntro: "Selected as browsing directions, not endorsements. Open the destination listing and review every detail before making a decision.",
      names: [["Low-profile runner", "Muted palette / daily rotation"], ["Technical sneaker", "Layered upper / bold sole"], ["Statement pair", "High contrast / weekend pick"], ["Quiet essential", "Simple lines / easy styling"]],
      idea: "The idea", statement: ["Fewer tabs.", "Better routes.", "A clearer find."], enter: "Enter the full index",
      notesKicker: "Reading room / 03", notesTitle: "Field notes", notesIntro: "Practical, fact-checked context for discovery, warehouse review and parcel planning.",
      notes: [
        ["Start here", "How to use a Superbuy spreadsheet without guessing", "Move from a promising find to the exact variant, a written inspection brief and a realistic two-stage budget.", "product-listing-checklist"],
        ["QC desk", "What useful QC photos should help you check", "Review shape, color consistency, visible marks and the details that matter to you. A photo is evidence to examine—not a promise of quality.", "superbuy-qc-photos-guide"],
        ["Parcel", "Why product price is only half the decision", "International delivery depends on packed size, weight, route and destination. Consider the likely parcel before building a haul.", "superbuy-shipping-cost-guide"],
      ],
    },
    categoriesPage: { kicker: "Product directory / 10 routes", title: "Browse by category.", intro: "Each route opens the matching collection on the destination catalog. Use this index when you know the kind of product you want but not the exact listing." },
    guidesPage: { kicker: "Practical guides / 03", title: "Plan before you click.", intro: "Straightforward explanations based on Superbuy’s published shopping-agent flow: ordering, warehouse inspection, storage, consolidation and international delivery." },
    articlesPage: { kicker: "SEO library / Issue 01", title: "Superbuy guides & field notes.", intro: "Three human-written, 1,200–1,800 word guides built around distinct search intent: spreadsheet workflow, QC photos and international shipping cost." },
    faqPage: { kicker: "Help desk / 12 answers", title: "Questions, answered.", intro: "These answers summarize Superbuy’s published guidance as checked on 12 August 2026. Route availability, costs and policies can change." },
  },
  fr: {
    ...shared.fr,
    home: {
      eyebrow: "Journal indépendant de découverte produit", titleA: "LE", titleB: "SUPERBUY", titleC: "INDEX",
      deck: "Une façon plus calme d’explorer les trouvailles Superbuy : une sélection éditée, pas un flux sans fin.",
      coverAlt: "Chaussure basse présentée dans la sélection", coverCaption: "Trouvaille couverture / N° 01",
      directoryKicker: "Répertoire / 01", directoryIntro: "Choisissez une section, puis explorez toute la collection.",
      directoryTitle: "Trouvez votre section.", routes: "10 parcours",
      editKicker: "Sélection visuelle / 04 trouvailles", editSource: "Images de fiches actives", editTitle: "Quatre points de départ.",
      editIntro: "Des directions de recherche, pas des recommandations. Ouvrez la fiche de destination et vérifiez chaque détail avant de décider.",
      names: [["Runner profil bas", "Palette douce / rotation quotidienne"], ["Sneaker technique", "Tige superposée / semelle forte"], ["Paire affirmée", "Contraste élevé / choix du week-end"], ["Essentiel discret", "Lignes simples / facile à assortir"]],
      idea: "L’idée", statement: ["Moins d’onglets.", "De meilleurs parcours.", "Une trouvaille plus claire."], enter: "Entrer dans l’index complet",
      notesKicker: "Salle de lecture / 02", notesTitle: "Notes de terrain", notesIntro: "Un contexte pratique pour chercher, vérifier et planifier avant de vous engager.",
      notes: [
        ["Commencer ici", "Lire une fiche produit avant de l’ouvrir", "Le titre, les photos du vendeur et les variantes permettent de décider si une trouvaille mérite un examen. Gardez vos questions pour l’étape de contrôle.", "product-listing-checklist"],
        ["Bureau QC", "Ce que des photos QC utiles doivent permettre de vérifier", "Examinez la forme, la cohérence des couleurs, les marques visibles et les détails importants. Une photo est une preuve à étudier, pas une promesse de qualité.", "superbuy-qc-photos-guide"],
        ["Colis", "Pourquoi le prix produit n’est que la moitié de la décision", "La livraison internationale dépend du volume emballé, du poids, de l’itinéraire et de la destination. Pensez au colis probable avant de composer un lot.", "superbuy-shipping-cost-guide"],
      ],
    },
    categoriesPage: { kicker: "Répertoire produits / 10 parcours", title: "Parcourir par catégorie.", intro: "Chaque parcours ouvre la collection correspondante du catalogue de destination. Utilisez l’index quand vous connaissez le type de produit, mais pas encore la fiche exacte." },
    guidesPage: { kicker: "Guides pratiques / 03", title: "Planifiez avant de cliquer.", intro: "Des explications claires fondées sur le parcours publié par Superbuy : commande, inspection en entrepôt, stockage, regroupement et livraison internationale." },
    articlesPage: { kicker: "Bibliothèque SEO / Numéro 01", title: "Guides Superbuy et notes de terrain.", intro: "Des guides approfondis sur de vraies questions : examiner les fiches, lire les photos QC et estimer la décision complète liée au colis." },
    faqPage: { kicker: "Aide / 10 réponses", title: "Vos questions, nos réponses.", intro: "Ces réponses résument les informations publiées par Superbuy et vérifiées en août 2026. Les lignes, coûts et politiques peuvent évoluer." },
  },
  de: {
    ...shared.de,
    home: {
      eyebrow: "Unabhängiges Magazin zur Produktentdeckung", titleA: "DER", titleB: "SUPERBUY", titleC: "INDEX",
      deck: "Ein ruhigerer Weg durch Superbuy-Funde – als kuratierte Auswahl statt endlosem Feed.",
      coverAlt: "Ausgewählter flacher Sneaker aus der aktuellen Edition", coverCaption: "Cover-Fund / Nr. 01",
      directoryKicker: "Verzeichnis / 01", directoryIntro: "Wähle einen Bereich und öffne anschließend die vollständige Sammlung.",
      directoryTitle: "Finde deinen Bereich.", routes: "10 Wege",
      editKicker: "Visuelle Auswahl / 04 Funde", editSource: "Bilder aus aktiven Listings", editTitle: "Vier Wege zum Start.",
      editIntro: "Als Suchrichtungen ausgewählt, nicht als Empfehlungen. Öffne das Ziel-Listing und prüfe jedes Detail vor deiner Entscheidung.",
      names: [["Flacher Runner", "Ruhige Farben / tägliche Rotation"], ["Technischer Sneaker", "Mehrlagiges Oberteil / starke Sohle"], ["Statement-Paar", "Hoher Kontrast / Wochenendwahl"], ["Ruhiges Essential", "Klare Linien / leicht zu kombinieren"]],
      idea: "Die Idee", statement: ["Weniger Tabs.", "Bessere Wege.", "Ein klarerer Fund."], enter: "Zum vollständigen Index",
      notesKicker: "Leseraum / 02", notesTitle: "Notizen aus der Praxis", notesIntro: "Praktischer Kontext zum Suchen, Prüfen und Planen vor deiner Entscheidung.",
      notes: [
        ["Hier starten", "Ein Produkt-Listing lesen, bevor du es öffnest", "Titel, Verkäuferbilder und Varianten zeigen, ob sich ein genauer Blick lohnt. Notiere Fragen für die spätere Prüfung.", "product-listing-checklist"],
        ["QC-Schreibtisch", "Was hilfreiche QC-Fotos zeigen sollten", "Prüfe Form, Farbkonsistenz, sichtbare Spuren und wichtige Details. Ein Foto ist Material zur Beurteilung – kein Qualitätsversprechen.", "superbuy-qc-photos-guide"],
        ["Paket", "Warum der Produktpreis nur die halbe Entscheidung ist", "Internationaler Versand hängt von Packmaß, Gewicht, Route und Ziel ab. Denke vor dem Zusammenstellen eines Hauls an das wahrscheinliche Paket.", "superbuy-shipping-cost-guide"],
      ],
    },
    categoriesPage: { kicker: "Produktverzeichnis / 10 Wege", title: "Nach Kategorie stöbern.", intro: "Jeder Weg öffnet die passende Sammlung im Zielkatalog. Nutze diesen Index, wenn du die Produktart kennst, aber noch kein bestimmtes Listing." },
    guidesPage: { kicker: "Praxisratgeber / 03", title: "Plane, bevor du klickst.", intro: "Klare Erklärungen auf Grundlage des veröffentlichten Superbuy-Ablaufs: Bestellung, Lagerprüfung, Aufbewahrung, Konsolidierung und internationaler Versand." },
    articlesPage: { kicker: "SEO-Bibliothek / Ausgabe 01", title: "Superbuy-Ratgeber & Praxisnotizen.", intro: "Ausführliche Antworten auf reale Fragen: Listings prüfen, QC-Fotos lesen und die gesamte Paketentscheidung einschätzen." },
    faqPage: { kicker: "Hilfe / 10 Antworten", title: "Fragen, beantwortet.", intro: "Diese Antworten fassen die im August 2026 geprüften Superbuy-Informationen zusammen. Routen, Kosten und Regeln können sich ändern." },
  },
} as const;

export const faq = {
  en: [
    ["What does a Superbuy shopping-agent order involve?", "Superbuy’s published process has five broad stages: select a product, submit the shopping-agent order, let the agent purchase it, review it after warehouse arrival, and then submit stored items as an international parcel. The product order and the later parcel are separate transactions, so the product price is not the complete delivered cost."],
    ["Do I pay once or twice?", "Normally twice. Superbuy’s first-stage payment covers the item, any Chinese domestic delivery and chosen product-level add-ons. The second payment is made when warehouse items are submitted for international delivery. That payment depends on the selected route, destination and estimated parcel data, then is reconciled after packing."],
    ["Does ordinary Superbuy purchasing have a service fee?", "The fee-composition page checked on 12 August 2026 states that ordinary shopping-agent purchasing has a CN¥0 service fee. Optional services and special purchasing services can cost extra; for example, the same page lists a 10% Shipping Expert fee with a stated minimum and maximum. Always review the live checkout breakdown because pricing can change."],
    ["What do the three warehouse photos actually prove?", "Superbuy’s current agent guide states that three photos of the actual item are provided after warehouse receipt. They are useful for confirming the visible variant, quantity, general shape and obvious damage. They cannot prove authenticity, fit, hidden construction, battery health or long-term durability, so ask for targeted evidence when one of those details matters."],
    ["How long can items stay in the warehouse?", "The current fee page gives items 90 days of free storage after arrival. It then states a storage charge of CN¥0.1 per item per day and a maximum storage period of 180 days, after which unsubmitted and unanswered items may be treated as abandoned. Check the live account deadline for each item rather than relying on memory."],
    ["Can several orders be consolidated into one parcel?", "Yes. Superbuy’s published fee and agent guides say multiple stored items can be consolidated, and the current fee page describes basic consolidation as free. Consolidation may remove duplicated outer packaging, but it is not guaranteed to reduce cost: a bigger parcel may attract dimensional-weight pricing or lose access to a preferred route."],
    ["How is the international shipping deposit calculated?", "Superbuy says the deposit uses estimated weight, the selected shipping method and the destination. After the warehouse packs and weighs the parcel, the final charge is based on verified parcel data and the logistics provider’s bill. The platform then adjusts the difference rather than treating the first estimate as the final price."],
    ["Which packaging options are available?", "The official guidance lists optional services such as packaging removal or replacement, reinforcement and insurance. Its current fee page also lists choices including vacuum packaging and folding shoe boxes. The useful option depends on the item: reducing volume can help soft goods, while fragile or crush-sensitive products may justify more protection."],
    ["How many destinations can Superbuy ship to?", "The current international-delivery guide says available delivery methods reach more than 82 countries and regions. Superbuy separately says it has served users in more than 200 countries and regions; that is a historical customer-coverage statement, not a promise that every route is currently available to every destination."],
    ["Are customs taxes and delays included in Superbuy’s promise?", "No. Superbuy’s guide says international delivery is carried out by designated third-party providers and that processing time, item restrictions and customs tax are not fully under its control. Buyers should check the destination’s rules, restricted-item status and the route’s current terms before submitting a parcel."],
    ["What should I do if the warehouse photos show a problem?", "Document the exact mismatch—wrong variant, missing part, visible damage or measurement—and act through the current order page promptly. Superbuy’s help center provides after-sales paths, but the available remedy depends on timing, seller acceptance and the specific order. A marked screenshot and a precise request are more useful than a vague complaint."],
    ["Is this website operated by Superbuy?", "No. This is an independent product-discovery and educational site. It does not operate Superbuy accounts, place agent orders, handle payments or make promises for Superbuy. Platform facts on this page were checked against Superbuy’s published English guidance on 12 August 2026 and should be rechecked before a time-sensitive decision."],
  ],
  fr: [
    ["Que fait un agent d’achat ?", "Un agent reçoit un lien ou une demande, achète l’article en Chine, le réceptionne dans un entrepôt puis permet au client de soumettre les articles stockés à la livraison internationale. Le parcours publié par Superbuy sépare le paiement du produit de celui du colis international."],
    ["Superbuy fournit-il des photos QC ?", "La page anglaise et le guide actuels indiquent que l’inspection en entrepôt comprend trois photos gratuites du produit réel. Elles aident à examiner l’état visible et les détails, sans garantir l’authenticité, la taille ou la qualité générale."],
    ["Combien de temps dure le stockage gratuit ?", "Le guide officiel actuel indique 90 jours de stockage gratuit. Vérifiez toujours les notifications du compte et la politique à jour avant de compter sur toute cette période."],
    ["Peut-on regrouper plusieurs commandes ?", "Oui. Le processus publié permet de soumettre plusieurs commandes stockées dans un seul colis. Le regroupement évite certains emballages en double, mais peut modifier le poids facturable, le volume et les lignes disponibles."],
    ["Comment les frais internationaux sont-ils calculés ?", "L’acompte dépend du poids estimé, du mode d’envoi et de la destination. Le coût final repose sur le volume et le poids vérifiés après emballage ; l’écart avec l’acompte est ajusté sur le compte."],
    ["Combien de pays Superbuy dessert-il ?", "La page d’accueil parle d’utilisateurs servis dans plus de 200 pays et régions. Le guide d’acheminement indique séparément que les modes de livraison actuels atteignent plus de 82 pays et régions. Vérifiez donc la disponibilité pour votre destination exacte."],
    ["Peut-on modifier l’emballage ?", "Le guide officiel cite le retrait d’emballage, le renforcement et l’assurance parmi les services supplémentaires. Leur disponibilité dépend du colis et de la ligne."],
    ["Les taxes douanières sont-elles comprises ?", "Ne le supposez pas. Superbuy précise ne pas contrôler entièrement la douane, les restrictions et les transporteurs tiers. La fiscalité dépend de la destination, du contenu déclaré et des règles locales."],
    ["Puis-je suivre mon colis ?", "Le parcours publié indique que le suivi apparaît dans la zone My Parcel après l’expédition. Les événements du transporteur peuvent mettre du temps à s’afficher."],
    ["Ce site est-il Superbuy ?", "Non. Il s’agit d’un site indépendant de découverte et d’information. Il ne fournit pas les services Superbuy, ne traite pas les paiements et ne fait aucune promesse au nom de Superbuy."],
  ],
  de: [
    ["Was macht ein Shopping Agent?", "Ein Shopping Agent erhält einen Produktlink oder eine Anfrage, kauft den Artikel in China, nimmt ihn im Lager an und ermöglicht anschließend den internationalen Versand eingelagerter Waren. Im veröffentlichten Superbuy-Ablauf sind Produktzahlung und spätere Paketzahlung getrennt."],
    ["Stellt Superbuy QC-Fotos bereit?", "Die aktuelle englische Startseite und der Leitfaden nennen drei kostenlose Fotos des tatsächlichen Produkts bei der Lagerprüfung. Sie helfen bei der Sichtprüfung, garantieren aber weder Echtheit noch Größe oder Gesamtqualität."],
    ["Wie lange ist die Lagerung kostenlos?", "Der aktuelle offizielle Leitfaden nennt 90 Tage kostenlose Lagerung. Prüfe vor der Nutzung immer die Hinweise im Konto und die gültige Richtlinie."],
    ["Kann ich mehrere Bestellungen zusammen versenden?", "Ja. Laut veröffentlichtem Ablauf können verschiedene Lagerbestellungen in einem Paket eingereicht werden. Konsolidierung reduziert doppelte Verpackung, kann aber Gewicht, Maße und verfügbare Routen verändern."],
    ["Wie werden internationale Versandkosten berechnet?", "Die Vorauszahlung basiert auf geschätztem Gewicht, Versandart und Ziel. Der Endbetrag richtet sich nach Größe und Gewicht des fertig gepackten Pakets; Unterschiede werden im Konto ausgeglichen."],
    ["Wie viele Länder bedient Superbuy?", "Die Startseite spricht von Nutzern in mehr als 200 Ländern und Regionen. Der Paketleitfaden nennt separat Liefermöglichkeiten in mehr als 82 Länder und Regionen. Prüfe deshalb die konkrete Route für dein Ziel."],
    ["Kann die Verpackung angepasst werden?", "Der offizielle Leitfaden nennt Entfernung von Verpackung, Verstärkung und Versicherung als Zusatzleistungen. Verfügbarkeit und Eignung hängen von Paket und Route ab."],
    ["Sind Zollabgaben enthalten?", "Gehe nicht davon aus. Superbuy erklärt, dass Zoll, Beschränkungen und Drittanbieter-Logistik nicht vollständig kontrolliert werden. Steuern richten sich nach Ziel, Inhalt und örtlichen Regeln."],
    ["Kann ich ein Paket verfolgen?", "Laut veröffentlichtem Ablauf ist die Sendungsverfolgung nach Versand im Bereich My Parcel verfügbar. Carrier-Ereignisse können verzögert erscheinen."],
    ["Ist diese Website Superbuy?", "Nein. Dies ist eine unabhängige Entdeckungs- und Informationsseite. Sie betreibt keine Superbuy-Dienste, verarbeitet keine Zahlungen und gibt keine Zusagen im Namen von Superbuy."],
  ],
} as const;

type Article = { slug: string; title: string; dek: string; sections: { heading: string; paragraphs: string[] }[] };

export const articles: Record<Locale, Article[]> = {
  en: [
    { slug: "product-listing-checklist", title: "How to Use a Superbuy Spreadsheet in 2026: A Practical Product-Finding Workflow", dek: "A human-first method for moving from a spreadsheet find to the correct variant, useful warehouse evidence and a parcel you can actually budget for.", sections: [
      { heading: "A spreadsheet is a discovery layer, not the seller record", paragraphs: ["People usually search for a Superbuy spreadsheet because they want to skip the least useful part of browsing: opening hundreds of unrelated marketplace results. A good index narrows the field by category and gives you a route to a live product page. That is valuable, but it is only the beginning. The index does not control the seller’s stock, current price, variant labels or description, and it cannot know whether a listing changed after it was added. Treat every card as a lead that needs to be rechecked, not as a frozen catalogue entry.", "Open the destination page and identify five things before you become attached to the item: the current title, the selected variant, the current price, the seller’s measurements or specifications, and what is actually included. A low headline price can belong to an accessory or the smallest option. One product page may also contain several materially different versions. If the title, image and selected option do not describe the same thing, stop and resolve that mismatch before submitting an agent order." ] },
      { heading: "Turn the desired variant into a one-line purchase brief", paragraphs: ["Before ordering, write a compact brief such as: black, size 43, version B, one pair, shoe box not essential. For a hoodie it might include color, tagged size, chest width, length and whether a detachable accessory is expected. This sounds basic, yet it prevents a common failure: remembering the general look while forgetting the exact option. The brief becomes the reference used at the seller page, order review, warehouse photo stage and any after-sales request.", "Measurements deserve more weight than letter sizes. A seller’s M, L or XL is only a label; cut and sizing conventions vary. Compare the seller’s flat measurements with a similar item you already own, using the same measurement points. For shoes, use the measurement method or internal-length guidance shown by the seller if it is available. When a decisive measurement is missing, the honest conclusion is not that the item will probably fit. The conclusion is that one material question remains unanswered." ] },
      { heading: "Understand the two-payment structure before building a haul", paragraphs: ["Superbuy’s current shopping-agent guide explains that the process is divided into two payments. The first stage covers the item, any Chinese domestic delivery and chosen product-level services. After the order arrives at the warehouse, you later create an international parcel and pay the shipping deposit. This structure matters because a cheap product can still be an expensive international parcel item if it is bulky, heavy, fragile or restricted to a costly route.", "The fee-composition page checked on 12 August 2026 lists ordinary shopping-agent purchasing at a CN¥0 service fee, while optional and specialized services can add charges. That does not make the total transaction free. Domestic shipping, optional detailed photos or inspections, packaging services, international freight, customs-related charges and payment conversion can all affect the real cost. Build a two-column budget—product stage and parcel stage—rather than comparing only listing prices." ] },
      { heading: "Use the warehouse as a decision checkpoint", paragraphs: ["The current Superbuy agent guidance states that items are weighed and inspected when received and that three photos of the actual product are provided. Those images are most useful when you arrive with a checklist. First confirm quantity and visible variant, then compare overall shape, color family, major panels or graphics, obvious surface marks and included accessories. A quick glance at one attractive angle wastes the value of the checkpoint.", "Warehouse photos have limits. They do not authenticate an item, test long-term durability, confirm how clothing fits on a body or reveal every hidden surface. If a critical point is not visible, ask for targeted evidence through the current order workflow when that option is available. A ruler beside one exact dimension is more useful than five general photos. A close image of a connector or label is more useful than digitally zooming a wide shot until the pixels become ambiguous." ] },
      { heading: "Plan storage and consolidation rather than drifting into them", paragraphs: ["Superbuy’s current fee page gives stored items 90 days of free warehouse time. It then states a charge of CN¥0.1 per item per day beyond the free period and a maximum storage period of 180 days. These rules make storage a planning tool, not an unlimited waiting room. Record each item’s arrival date and expected parcel group. If one late seller delays the entire shipment, compare the likely saving from waiting with the risk of storage charges or an approaching deadline.", "The same official material describes basic consolidation of multiple stored items as free. Consolidation can remove repeated outer packaging and combine orders into one shipment, but it does not automatically make every kilogram cheaper. A larger parcel can trigger dimensional-weight pricing, exceed a route limit or combine restricted and ordinary goods in an awkward way. Group items by compatible handling needs and likely route, not simply by the fact that they are all in the warehouse." ] },
      { heading: "Choose packaging according to the product, not a universal rule", paragraphs: ["Superbuy’s published guidance lists optional services such as package removal or replacement, reinforcement and insurance. The current fee page also shows services including vacuum packaging and folding shoe boxes. Each option solves a different problem. Vacuum packing may reduce the volume of soft clothing. Removing an unnecessary retail box may help a lightweight parcel. Reinforcement may be sensible for something crush-sensitive, while a collector may value the original box enough to keep it despite the volume.", "Think in trade-offs. Reducing packaging can lower size but remove protection. Keeping multiple rigid boxes can preserve them while increasing chargeable volume. Insurance can address certain covered losses but cannot make fragile goods physically stronger or eliminate customs risk. Write clear packaging instructions only after checking the current route requirements and service descriptions. A short, item-specific request is more reliable than a generic instruction to make the parcel as small as possible." ] },
      { heading: "Make a clean ship, review or reject decision", paragraphs: ["At warehouse stage, place the result into one of three categories. Ship means the visible item matches the purchase brief closely enough and the parcel plan remains acceptable. Review means one important question can still be answered with a measurement, closer photo or agent clarification. Reject or seek after-sales help means there is a documented mismatch such as the wrong option, missing part or visible damage. This simple classification prevents vague uncertainty from turning into an automatic shipment.", "After-sales options depend on timing, seller cooperation and the live platform process, so review warehouse notifications promptly. Save the active product URL, chosen variant, order note and screenshots of decisive seller details. If a problem appears, mark the relevant area and describe the requested outcome precisely. The best Superbuy spreadsheet workflow is not the one that finds the most products. It is the one that carries a clear product brief, evidence standard and parcel budget from discovery to dispatch." ] },
      { heading: "Judge the spreadsheet by transparency, not by its product count", paragraphs: ["A large spreadsheet can be useful, but the headline number is not a quality metric by itself. Prefer an index that gives clear categories, working destinations and realistic descriptions without promising that every listing is verified forever. Check a few random routes before relying on the collection. If cards repeatedly lead to removed products, unrelated variants or prices that no longer exist, use the index as inspiration only.", "Independent indexes should also be clear about their role. They can organize discovery and teach a checking method; they cannot guarantee seller behavior, warehouse outcomes, international route availability or customs treatment. That boundary is good for the user. It encourages a workflow based on current product pages and current account information instead of treating an attractive catalogue as proof that every later stage will be effortless." ] },
    ] },
    { slug: "superbuy-qc-photos-guide", title: "How to Read Superbuy QC Photos: A 2026 Warehouse Inspection Checklist", dek: "A realistic method for checking variants, measurements, visible defects and missing details without pretending three photos can prove everything.", sections: [
      { heading: "Know what Superbuy says the warehouse stage includes", paragraphs: ["Superbuy’s current English shopping-agent guidance says an item is weighed and inspected after warehouse receipt and that three photos of the actual product are provided. Think of this as a visual handover checkpoint between the Chinese seller and the later international parcel. The photos can show whether an obvious wrong item arrived, whether the broad color and model match, and whether visible damage or missing parts deserve attention before international shipping makes correction harder.", "The word inspection can sound broader than the evidence actually available. Three images do not form an authentication service, performance test or full condition report. They cannot reveal hidden stitching, internal electronics, battery health, smell, fabric feel or long-term durability. They also cannot tell you how clothing fits. A useful review begins by separating what can be seen from what you merely hope is true." ] },
      { heading: "Prepare the checklist before the photos arrive", paragraphs: ["QC works best when the standard is written before you see the item. Copy the ordered color, size label, version, quantity and included accessories into a short list. Add two or three visible characteristics that would make you reject the item: perhaps a missing strap, badly shifted graphic, cracked housing or incorrect sole color. This protects you from lowering the standard simply because the seller image looked exciting and the warehouse photos finally arrived.", "Keep the seller’s live listing and key screenshots beside the order record. Product pages can change, so save measurements and included-item claims at purchase time. Do not turn promotional language into a QC requirement unless it points to something visible and specific. “Premium quality” cannot be checked from a wide photo; “two detachable straps included” can. Good criteria are observable, measurable and tied to the selected variant." ] },
      { heading: "Review the images in a repeatable order", paragraphs: ["Start with identity: quantity, color family, visible size tag and model. Then check the overall silhouette and proportions. Move next to alignment—paired shoes, pockets, printed graphics, seams, panels and hardware. Finish with surfaces and included pieces, looking for stains, scratches, dents, glue marks, tears or missing accessories. The order matters because it keeps one clean hero angle from distracting you from a wrong label or absent part.", "Compare the photos side by side with the seller page rather than relying on memory. Lighting, white balance and phone screens can shift subtle colors, so prioritize large differences. Perspective can make a shoe toe or bag shape appear distorted. Look for the same issue across more than one angle before drawing a conclusion. When the decision depends on an exact shade or proportion, the correct status is often unresolved, not automatically defective." ] },
      { heading: "Ask for evidence that answers one precise question", paragraphs: ["If the supplied photos do not answer a material question, a targeted request is more efficient than asking for more pictures in general. Request a ruler across the chest width, a close view of a zipper, the connector panel on an electronic item or all included accessories laid out together. State the option ordered and the reason the detail matters. Specific requests are easier for warehouse staff to execute and easier for you to interpret.", "Measurements are especially useful for apparel, shoes, bags and graphics. Compare them with an item you own using the same points and the same flat-lay method. A ruler image turns “looks small” into evidence. It still does not guarantee fit, because fabric stretch and cut matter, but it narrows uncertainty. Avoid asking QC photos to answer subjective questions such as whether a material feels expensive; the camera cannot provide that information." ] },
      { heading: "Handle common categories with different priorities", paragraphs: ["For footwear, compare pair symmetry, visible size labels, sole shape, upper panels and whether expected accessories are present. For clothing, prioritize tagged size, flat measurements, print position, seam condition and obvious marks. For bags, check hardware, strap count, closures, corners and shape. For electronics, confirm model identifiers, plug type and visible ports, but do not infer functional testing unless the order specifically includes a documented service that performs it.", "Fragile goods need both item review and parcel planning. A clean warehouse photo does not guarantee survival in international transit. If an item has glass, ceramic, sharp protrusions or a crush-sensitive shape, separately consider reinforcement, packaging changes and route restrictions. Superbuy’s official guide lists reinforcement and insurance among optional parcel-stage services, but those services do not eliminate every third-party carrier or customs risk." ] },
      { heading: "Respond to a mismatch while the evidence is fresh", paragraphs: ["If the wrong variant, missing component or visible damage appears, act through the current order page promptly. Crop or mark the relevant image, quote the ordered option and request a concrete next step. “The item is bad” is hard to relay. “The ordered black size 43 pair arrived with a size 42 label; see photo two” gives the agent something exact to communicate. Keep the tone factual because the goal is resolution, not a dramatic review.", "Available after-sales outcomes depend on the seller, timing and current platform rules. Do not rely on an old forum post for a universal return window. Superbuy’s help center includes after-sales paths, but the live order status and instructions should control the action. Store screenshots of the original listing, option and QC issue together so the evidence remains understandable if the seller edits the page." ] },
      { heading: "Use a three-state decision instead of chasing certainty", paragraphs: ["Mark the item acceptable when the visible checks meet your written criteria. Mark it unresolved when an important question is not answered but could be clarified. Mark it mismatched when the photos document a difference or defect that crosses your pre-set threshold. This method prevents two opposite mistakes: approving too quickly because the item looks broadly similar, or rejecting a normal lighting or perspective variation as proof of a flaw.", "QC photos are valuable precisely because they create a pause before international shipment. Use that pause well. Compare with a checklist, request one focused piece of evidence when necessary, and make a timely decision. Do not advertise the photos to yourself as a guarantee. Their real value is narrower and more practical: they can catch certain visible problems while the item is still in the warehouse and the order history is easy to document." ] },
      { heading: "Use customer reviews as questions, not universal proof", paragraphs: ["Public customer reviews can reveal recurring questions worth checking—slow seller dispatch, confusing sizing, weak packaging or a route that produced unexpected dimensional weight. They are less useful as precise predictions. A review usually reflects one seller, one parcel, one country and one moment in time. Without the order details, a dramatic shipping total or delivery time cannot be transferred directly to your purchase.", "When researching reviews, look for repeated patterns across independent reports and then verify the underlying rule on the current platform. Turn a pattern into a question: does this product need a ruler photo, is the retail box unusually large, or is the destination route currently accepting the item? This produces useful evidence without inventing a platform-wide conclusion from a small sample.", "Photographs attached to a review deserve the same discipline as warehouse images. Check whether the reviewer shows the original listing, the received item and the issue from more than one angle. A single close crop may omit normal context; a polished unboxing image may say little about the seller variant. Useful review evidence connects a visible observation to an order detail. It should help you refine your own checklist, not invite you to assume that every future order will reproduce one person’s result. Record the review date as well, because fees, warehouse services and international routes can change after the experience being described." ] },
    ] },
    { slug: "superbuy-shipping-cost-guide", title: "Superbuy Shipping Cost Guide 2026: Estimate Weight, Volume and Consolidation", dek: "A fact-checked way to budget the second payment, understand the shipping deposit and choose packaging without assuming consolidation always saves money.", sections: [
      { heading: "Separate product cost from delivered parcel cost", paragraphs: ["Superbuy’s published shopping-agent flow requires two payment decisions. The first covers the product stage: item price, Chinese domestic delivery and any selected product-level services. The second happens after items reach the warehouse and you submit them for international delivery. This is the point at which route, destination, packed dimensions, weight and parcel services become concrete. A product can be inexpensive at stage one and still be poor value after stage two.", "Build the budget before ordering. Record product cost, domestic shipping and optional services in one column. In a second column, estimate international freight, packaging choices, payment conversion and a customs reserve appropriate to the destination. The purpose is not to predict an exact final number from incomplete data. It is to identify items—large boxes, rigid objects, heavy shoes or restricted goods—that may dominate the parcel decision later." ] },
      { heading: "Understand why the first shipping figure is a deposit", paragraphs: ["Superbuy’s current international-delivery guidance says the shipping deposit is calculated from estimated product weight, the chosen method and the destination. The final shipping fee is determined after the parcel is packed and the logistics provider verifies its size and weight. If the final amount differs from the deposit, the platform reconciles the difference in the account. The estimate is therefore a planning figure, not a guaranteed quote.", "Net item weight is only one input. The finished parcel includes packaging and may be billed using dimensional weight when its volume is large relative to its mass. A lightweight puffer jacket in a large box can occupy costly space; dense small items can be heavy without being bulky. Route rules also use different charging increments and restrictions. This is why copying another buyer’s cost-per-kilogram rarely predicts your own final bill." ] },
      { heading: "Use the current fee breakdown as a checklist", paragraphs: ["The fee-composition page checked on 12 August 2026 describes international shipping as a combination that may include an initial-weight charge, additional-weight units, customs-related charges, fuel surcharge and an operation fee, depending on the route. Not every line displays every component in the same way. Read the live breakdown for the route being considered rather than assuming one screenshot represents the entire platform.", "The same page says ordinary shopping-agent purchasing currently carries a CN¥0 service fee and that multiple items can be consolidated for free. Optional value-added services are charged separately when selected. This distinction is useful: basic purchasing and consolidation may be free as services, while the goods, domestic delivery, add-ons and international logistics still create the total cost. “No service fee” should never be read as “no transaction cost.”" ] },
      { heading: "Consolidate compatible items, not every item", paragraphs: ["Combining orders can remove repeated seller packaging and replace several international shipments with one parcel. That may improve efficiency, especially when each separate parcel would pay its own initial-weight charge. But consolidation is not automatically cheaper. One oversized parcel can attract high dimensional weight, exceed a route’s size limit or force all contents onto a more expensive line because one item is restricted.", "Group products by physical and regulatory compatibility. Soft clothing often works well together. A fragile collectible may need a different protection strategy from vacuum-packed garments. Battery items, liquids or unusually long products can narrow route choices. Before combining everything, compare at least two plausible parcel plans: one consolidated shipment and a split that isolates the bulky, fragile or restricted item. The lower-risk plan can be better value even if the headline freight is slightly higher." ] },
      { heading: "Treat warehouse time as a planning window", paragraphs: ["Superbuy’s current fee page states that items receive 90 days of free storage after arrival. Beyond that, it lists a storage charge of CN¥0.1 per item per day and a maximum period of 180 days, after which unattended goods may be treated as abandoned. Record the arrival date of each item and choose a target parcel date. Do not wait indefinitely for the perfect haul while early items approach a deadline.", "A practical rule is to decide the parcel group before the first product is ordered. If one seller is slow, compare three options: wait and keep the intended group, ship ready items, or cancel the late item if the order stage permits. The right answer depends on expected savings, storage time and route compatibility. The important point is that the warehouse clock belongs in the shipping calculation just as much as weight and volume." ] },
      { heading: "Select packaging by modelling the trade-off", paragraphs: ["Superbuy’s official guidance lists package removal or replacement, reinforcement and insurance among optional services. Its current fee page also lists vacuum packaging and folding shoe boxes. Removing or folding a box can reduce volume; vacuum packing can compress suitable soft goods; reinforcement can help a crush-sensitive parcel. None of these choices is universally best because reducing size, preserving retail packaging and adding physical protection pull in different directions.", "Estimate the value of the original packaging before removing it. For ordinary shoes, a buyer may prefer lower volume. For a collectible, box condition may be part of the value. Vacuum packing is sensible for compressible textiles, not for structured items. Reinforcement adds material and sometimes weight but may be worth it for fragile contents. Insurance addresses defined financial risks under its terms; it cannot prevent customs action, delay or physical mishandling." ] },
      { heading: "Compare routes using the parcel you actually have", paragraphs: ["Superbuy’s guide says its international delivery methods reach more than 82 countries and regions, but availability depends on the destination and item characteristics. It also warns that third-party providers and customs affect processing time, restrictions and taxes. A route that appears in a broad guide may not be available for a specific battery item, parcel size or destination postcode when you submit it.", "Once all intended items are stored, revisit the shipping calculator with warehouse weights and a realistic packed shape. Compare the route’s charge, estimated delivery range, tracking, restrictions, compensation terms and customs treatment. Do not rank routes by price alone. A slightly more expensive line can be preferable if it accepts the contents cleanly and provides the service level you need. Recheck the live route notice immediately before payment." ] },
      { heading: "Create a final parcel decision sheet", paragraphs: ["Before submission, write down destination, item list, warehouse weights, likely packed volume, chosen packaging, restricted-item flags, candidate routes and a contingency budget. Note which assumptions are still estimates. This one-page record makes it easier to compare a split parcel with a consolidated one and protects against the false precision of a single calculator result.", "The most useful Superbuy shipping estimate is a range with reasons, not a copied number. It acknowledges that the first charge is a deposit, the finished parcel controls the final bill and route availability can change. Estimate early enough to avoid buying uneconomic items, then calculate again when warehouse data exists. That two-pass method is more reliable than trying to guess the final international cost from product pages alone." ] },
      { heading: "Read shipping reviews without copying somebody else’s total", paragraphs: ["Customer reports are useful for discovering friction, but a bare statement such as “shipping was expensive” has almost no diagnostic value. Look for destination, route, packed weight, box size, item type, packaging services, date and whether the amount discussed was the deposit or final charge. When those details are missing, treat the review as a prompt to investigate rather than a benchmark.", "A responsible review article should compare patterns instead of manufacturing an average from incomparable parcels. Repeated reports of large shoe boxes, slow seller dispatch or confusing route restrictions can shape a practical checklist. The current calculator and warehouse data must still decide the actual shipment. Reviews make the guide more human when their limits are visible; they become misleading when one person’s parcel is presented as a universal price promise." ] },
    ] },
  ],
  fr: [],
  de: [],
};

const translateArticles = (locale: "fr" | "de", rows: Article[]) => { articles[locale] = rows; };

translateArticles("fr", [
  { slug: "product-listing-checklist", title: "Checklist d’une fiche Superbuy : que vérifier avant de commander", dek: "Un contrôle pratique du titre, des variantes, des photos vendeur, des mesures, des restrictions et de la fiche de destination.", sections: [
    { heading: "Commencez par la source, pas par la vignette", paragraphs: ["Une carte de sélection est un itinéraire, pas la fiche produit complète. Ouvrez la destination et comparez le titre, les photos du vendeur, les options et le prix actuel. Une vignette peut rester visible après la modification d’une variante ; la page active doit donc guider la décision finale.", "Notez exactement ce que vous voulez : couleur, taille, version, matière et quantité. Cette ligne devient une checklist lorsque les options sont mal traduites ou que plusieurs variantes proches partagent la même page."] },
    { heading: "Traitez chaque variante comme une décision séparée", paragraphs: ["Ne supposez pas que toutes les options ont la même matière, les mêmes dimensions ou les mêmes accessoires. Un prix d’appel peut correspondre à un petit accessoire. Associez le libellé de l’option à son image et à son prix avant de soumettre la commande.", "Pour les vêtements et chaussures, comparez les mesures du vendeur à un article que vous possédez. Les tailles en lettres sont insuffisantes, car les coupes varient. Si une mesure essentielle manque, considérez la question comme non résolue."] },
    { heading: "Séparez les preuves visibles des affirmations", paragraphs: ["Les photos vendeur montrent une présentation ; les photos QC montrent l’article reçu sous quelques angles. Aucune ne prouve tous les détails cachés. Définissez les éléments visibles importants : forme, couleur, alignement, marques, accessoires ou étiquettes.", "Superbuy indique actuellement que le parcours d’agent comprend trois photos gratuites du produit réel. Comparez-les à votre checklist, sans oublier qu’elles ne prouvent ni la coupe, ni la durabilité, ni l’authenticité."] },
    { heading: "Pensez au colis avant de payer", paragraphs: ["Le prix produit n’est que le premier paiement. La livraison internationale est calculée plus tard selon le poids et le volume emballés, la ligne et la destination. Les boîtes volumineuses ou les objets rigides peuvent changer l’intérêt économique d’une trouvaille bon marché.", "Si l’article est fragile, très long, équipé d’une batterie ou liquide, vérifiez les restrictions actuelles. Un produit achetable en Chine n’est pas automatiquement accepté par toutes les lignes internationales."] },
    { heading: "Gardez une trace propre", paragraphs: ["Conservez l’URL active, la variante, le prix et une capture des mesures ou éléments inclus. Une page peut changer entre l’achat, l’arrivée à l’entrepôt et l’après-vente. Un dossier compact aide à expliquer un écart.", "Une bonne décision n’est pas celle qui ouvre le plus d’onglets : c’est celle où la variante, les preuves, l’impact probable sur le colis et les questions restantes sont clairs."] },
  ] },
  { slug: "superbuy-qc-photos-guide", title: "Lire les photos QC Superbuy sans surestimer ce qu’elles prouvent", dek: "Une méthode pour examiner forme, couleur, alignement, défauts visibles et conformité de l’option.", sections: [
    { heading: "Comprendre le rôle des photos QC", paragraphs: ["Les photos d’entrepôt constituent un point de contrôle entre la livraison du vendeur et l’envoi international. Le guide actuel de Superbuy indique qu’une inspection est réalisée à l’entrée en stock et que trois photos du produit réel sont fournies. Elles servent surtout à confirmer la correspondance générale et à repérer les problèmes évidents.", "Elles ne sont ni un rapport de laboratoire, ni un certificat d’authenticité, ni un essayage. Une image propre ne révèle pas la construction interne, l’état d’une batterie ou le toucher d’un vêtement."] },
    { heading: "Comparer dans un ordre fixe", paragraphs: ["Commencez par la variante commandée : couleur, taille, modèle et quantité. Vérifiez ensuite la silhouette et les proportions, puis la symétrie, les coutures, les impressions, la quincaillerie, les marques et accessoires. Un ordre constant évite qu’un angle flatteur détourne l’attention.", "Placez la photo QC et la fiche vendeur côte à côte. L’éclairage peut modifier les couleurs : cherchez les écarts importants. Si la teinte est essentielle, une photo supplémentaire sous lumière neutre est plus utile qu’un zoom numérique."] },
    { heading: "Mesurer lorsque l’échelle compte", paragraphs: ["La perspective peut déformer une chaussure, un sac ou un motif. Une photo avec règle transforme une impression en mesure. Demandez la dimension précise qui influence votre décision plutôt qu’une série d’images génériques.", "Pour les vêtements, comparez la mesure à un article similaire posé à plat chez vous. C’est plus fiable qu’une conversion entre tailles régionales sans connaître la coupe."] },
    { heading: "Savoir quand s’arrêter", paragraphs: ["Mettez la décision en pause si l’étiquette d’option diffère, si des pièces manquent, si un dommage est visible ou si un élément majeur ne correspond pas. Utilisez des captures annotées et une description précise.", "Les solutions après-vente dépendent du délai, du vendeur et du processus en vigueur. Examinez les photos rapidement et suivez les instructions du compte plutôt qu’un ancien tutoriel."] },
    { heading: "Décider d’expédier ou de vérifier", paragraphs: ["Classez le résultat comme acceptable, non résolu ou non conforme. Acceptable signifie que les contrôles visibles répondent à vos critères. Non résolu signifie que les images ne répondent pas à une question importante. Non conforme signifie qu’un écart est visible.", "Cette méthode garde le QC réaliste : utilisez les photos pour ce qu’elles montrent, demandez une preuve ciblée pour le reste et ne transformez jamais un contrôle limité en garantie."] },
  ] },
  { slug: "superbuy-shipping-cost-guide", title: "Frais d’envoi Superbuy : estimez le colis, pas seulement le produit", dek: "Pourquoi volume emballé, poids vérifié, destination, ligne et regroupement façonnent la décision finale.", sections: [
    { heading: "Deux paiements, deux questions", paragraphs: ["Dans le parcours publié, le client paie d’abord le produit et la livraison intérieure. Le transport international intervient après l’arrivée à l’entrepôt et la création du colis. Traitez-les comme deux décisions budgétaires.", "La première demande si le produit vaut l’achat ; la seconde si le colis final vaut l’envoi par une ligne disponible vers votre destination."] },
    { heading: "Estimation et coût final diffèrent", paragraphs: ["Superbuy explique que l’acompte international utilise le poids estimé, le mode d’envoi et la destination. Le tarif final dépend du volume et du poids vérifiés après emballage ; l’écart est ajusté sur le compte.", "Le poids net d’un produit ne suffit donc pas. Les boîtes, la protection et la facturation volumétrique comptent, surtout pour les objets grands mais légers."] },
    { heading: "Le regroupement n’est pas une économie automatique", paragraphs: ["Réunir plusieurs commandes peut supprimer des emballages extérieurs répétés et créer un seul envoi. Mais un grand colis peut dépasser les limites d’une ligne ou coûter cher au volume. Comparez les formes de colis probables.", "Le guide actuel indique 90 jours de stockage gratuit pour regrouper. Vérifiez la politique du compte et ne laissez pas cette fenêtre devenir une échéance involontaire."] },
    { heading: "Choisir l’emballage selon l’objet", paragraphs: ["Le guide officiel cite retrait d’emballage, renforcement et assurance. Retirer une boîte inutile réduit parfois le volume ; un objet fragile peut exiger plus de protection. Le bon choix dépend de la valeur de la boîte, de la fragilité et de la ligne.", "Formulez clairement les demandes spéciales. Aucun emballage n’élimine tous les risques liés au transport ou à la douane."] },
    { heading: "Construire une estimation réaliste", paragraphs: ["Listez destination, nombre d’articles, dimensions emballées probables, poids, restrictions et protection souhaitée. Utilisez le calculateur actuel comme estimation et gardez une marge. Revérifiez lorsque tous les articles sont réellement en stock.", "La meilleure comparaison n’est pas prix contre prix, mais valeur totale du colis final contre options internationales vérifiées au moment de la soumission."] },
  ] },
]);

translateArticles("de", [
  { slug: "product-listing-checklist", title: "Superbuy-Listing-Checkliste: Was du vor der Bestellung prüfen solltest", dek: "Ein praktischer Vorabcheck für Titel, Varianten, Verkäuferbilder, Maße, Einschränkungen und das aktuelle Ziel-Listing.", sections: [
    { heading: "Beginne bei der Quelle, nicht beim Vorschaubild", paragraphs: ["Eine Auswahlkarte ist ein Wegweiser, nicht der vollständige Produktdatensatz. Öffne das Ziel-Listing und vergleiche Titel, Verkäuferbilder, Optionen und aktuellen Preis. Ein Vorschaubild kann nach einer Änderung sichtbar bleiben; die aktive Zielseite muss deshalb die letzte Entscheidung bestimmen.", "Notiere genau, was du kaufen willst: Farbe, Größe, Version, Material und Menge. Diese Zeile wird zur Checkliste, wenn Optionen schlecht übersetzt sind oder ähnliche Varianten eine Seite teilen."] },
    { heading: "Behandle jede Variante als eigene Entscheidung", paragraphs: ["Gehe nicht davon aus, dass alle Optionen dieselben Materialien, Maße oder Zubehörteile enthalten. Ein niedriger Einstiegspreis kann zu einem kleinen Zusatzteil gehören. Ordne Optionsname, Bild und Preis einander zu, bevor du bestellst.", "Vergleiche bei Kleidung und Schuhen die Verkäufermaße mit einem eigenen Stück. Buchstabengrößen sind schwache Hinweise, weil Systeme und Schnitte variieren. Fehlt ein wichtiges Maß, bleibt die Frage offen."] },
    { heading: "Trenne sichtbare Hinweise von Behauptungen", paragraphs: ["Verkäuferfotos zeigen die Präsentation; QC-Fotos zeigen den erhaltenen Artikel aus wenigen Blickwinkeln. Beides beweist keine verborgenen Details. Lege fest, welche sichtbaren Merkmale zählen: Form, Farbe, Ausrichtung, Spuren, Zubehör oder Etiketten.", "Superbuy nennt aktuell drei kostenlose Fotos des tatsächlichen Produkts. Vergleiche sie mit deiner Checkliste, ohne daraus Aussagen zu Passform, Haltbarkeit oder Echtheit abzuleiten."] },
    { heading: "Denke vor dem Bezahlen an das Paket", paragraphs: ["Der Produktpreis ist nur die erste Zahlung. Der internationale Versand wird später nach Packmaß, Gewicht, Route und Ziel berechnet. Große Kartons, starre Verpackungen und sperrige Artikel können die Wirtschaftlichkeit eines günstigen Fundes verändern.", "Prüfe bei zerbrechlichen, langen, batteriehaltigen oder flüssigen Waren die aktuellen Beschränkungen. Ein im Inland kaufbares Produkt passt nicht automatisch zu jeder internationalen Linie."] },
    { heading: "Halte die Entscheidung sauber fest", paragraphs: ["Speichere aktive URL, Variante, Preis und Screenshots wichtiger Maße oder Lieferbestandteile. Seiten können sich zwischen Kauf, Lagereingang und After-Sales ändern. Ein kompakter Nachweis erleichtert die Erklärung einer Abweichung.", "Eine gute Entscheidung hat nicht die meisten offenen Tabs. Sie macht Variante, sichtbare Belege, wahrscheinlichen Paketeffekt und offene Fragen vor der Zahlung klar."] },
  ] },
  { slug: "superbuy-qc-photos-guide", title: "Superbuy-QC-Fotos richtig lesen, ohne ihre Aussagekraft zu überschätzen", dek: "Eine Methode zur Prüfung von Form, Farbe, Ausrichtung, sichtbaren Mängeln und Variantenrichtigkeit.", sections: [
    { heading: "Den Zweck von QC-Fotos verstehen", paragraphs: ["Lagerfotos sind ein Kontrollpunkt zwischen Verkäuferlieferung und internationalem Versand. Der aktuelle Superbuy-Leitfaden nennt eine Prüfung beim Einlagern und drei Fotos des tatsächlichen Produkts. Am besten bestätigen sie die grobe Übereinstimmung und zeigen offensichtliche Probleme.", "Sie sind kein Laborbericht, Echtheitszertifikat oder Passformtest. Ein sauberes Foto beweist keine inneren Materialien, Batteriezustände oder das Tragegefühl von Kleidung."] },
    { heading: "In einer festen Reihenfolge vergleichen", paragraphs: ["Beginne mit der bestellten Variante: Farbe, Größenetikett, Modell und Menge. Prüfe dann Silhouette und Proportionen, anschließend Symmetrie, Nähte, Drucke, Beschläge, Oberflächenspuren und Zubehör. Eine feste Reihenfolge schützt vor Ablenkung durch einen attraktiven Winkel.", "Lege QC-Bild und Verkäuferlisting nebeneinander. Beleuchtung verschiebt Farben; suche deshalb nach deutlichen Abweichungen. Ist der Farbton entscheidend, hilft ein Zusatzfoto bei neutralem Licht mehr als digitales Zoomen."] },
    { heading: "Messen, wenn Maßstab wichtig ist", paragraphs: ["Perspektive kann Schuhe, Taschen oder Grafiken verzerren. Ein Linealfoto macht aus einem Eindruck eine messbare Frage. Bitte um das konkrete Maß, das deine Entscheidung beeinflusst, statt um viele allgemeine Bilder.", "Vergleiche Kleidungsmaße mit einem ähnlichen, flach liegenden Stück zu Hause. Das ist zuverlässiger als eine Umrechnung von Buchstabengrößen ohne Kenntnis des Schnitts."] },
    { heading: "Wissen, wann man pausiert", paragraphs: ["Pausiere bei falschem Optionsetikett, fehlenden Teilen, sichtbaren Schäden oder deutlichen Designabweichungen. Markierte Screenshots und eine präzise Beschreibung lassen sich leichter an den Verkäufer weitergeben.", "After-Sales-Optionen hängen von Fristen, Verkäuferregeln und dem aktuellen Prozess ab. Prüfe Fotos zeitnah und folge den Kontoanweisungen statt einem alten Tutorial."] },
    { heading: "Versenden oder weiter prüfen", paragraphs: ["Ordne das Ergebnis als akzeptabel, ungeklärt oder abweichend ein. Akzeptabel erfüllt die sichtbaren Kriterien. Ungeklärt bedeutet, dass Bilder eine wichtige Frage nicht beantworten. Abweichend bedeutet, dass ein Unterschied belegt ist.", "So bleibt QC realistisch: Nutze Fotos für das, was sie zeigen, fordere gezielte Belege für den Rest an und mache aus einer begrenzten Sichtprüfung keine Garantie."] },
  ] },
  { slug: "superbuy-shipping-cost-guide", title: "Superbuy-Versandkosten: Schätze das Paket, nicht nur das Produkt", dek: "Wie Packmaß, geprüftes Gewicht, Ziel, Route und Konsolidierung die internationale Versandentscheidung formen.", sections: [
    { heading: "Zwei Zahlungen, zwei Fragen", paragraphs: ["Im veröffentlichten Ablauf bezahlt der Kunde zuerst Produkt und Inlandslieferung. Internationaler Versand folgt nach dem Lagereingang und der Paketeinreichung. Behandle beide als getrennte Budgetentscheidungen.", "Die erste Frage lautet, ob das Produkt den Kauf wert ist. Die zweite, ob sich das fertige Paket über eine verfügbare Route zum Ziel lohnt."] },
    { heading: "Schätzung und Endbetrag sind nicht identisch", paragraphs: ["Superbuy erklärt, dass die internationale Vorauszahlung geschätztes Gewicht, Versandart und Ziel nutzt. Der Endbetrag basiert auf Größe und Gewicht des fertig gepackten Pakets; Unterschiede werden im Konto ausgeglichen.", "Darum sagt das Nettogewicht allein wenig aus. Kartons, Schutzmaterial und Volumengewicht zählen besonders bei großen, leichten Artikeln."] },
    { heading: "Konsolidierung spart nicht automatisch", paragraphs: ["Mehrere Lagerbestellungen können doppelte Außenverpackung vermeiden und eine Sendung bilden. Ein größeres Paket kann jedoch Routenlimits überschreiten oder nach Volumen teuer werden. Vergleiche wahrscheinliche Paketformen.", "Der aktuelle Leitfaden nennt 90 Tage kostenlose Lagerung für das Sammeln. Prüfe die Kontorichtlinie und mache aus dem Zeitfenster keine unbeabsichtigte Frist."] },
    { heading: "Verpackung passend zum Artikel wählen", paragraphs: ["Der offizielle Leitfaden nennt Entfernen von Verpackung, Verstärkung und Versicherung. Eine unnötige Box zu entfernen kann Volumen sparen; Zerbrechliches braucht möglicherweise Schutz. Die Wahl hängt vom Wert der Originalbox, Druckempfindlichkeit und Route ab.", "Formuliere Sonderwünsche klar. Verpackungsänderungen beseitigen nicht jedes Risiko bei Drittanbietern oder Zoll."] },
    { heading: "Eine realistische Schätzung bauen", paragraphs: ["Notiere Ziel, Artikelzahl, wahrscheinliche Packmaße, Gewicht, Beschränkungen und Schutzbedarf. Nutze den aktuellen Rechner als Schätzung und plane eine Reserve ein. Prüfe erneut, wenn alle Artikel wirklich im Lager sind.", "Der beste Vergleich ist nicht Produktpreis gegen Produktpreis, sondern Gesamtwert des fertigen Pakets gegen die zum Einreichungszeitpunkt verfügbaren internationalen Optionen."] },
  ] },
]);
