import type { Article, Locale } from "./content";

export const orderRemarksArticle: Record<Locale, Article> = {
  en: {
    slug: "superbuy-order-remarks-writing-guide",
    title: "Superbuy Order Remarks: Write Instructions the Agent Can Verify",
    dek: "A practical Shopping Agent method for turning listing evidence into short, testable order remarks without asking warehouse staff to guess.",
    sections: [
      { heading: "Decide whether a remark is needed at all", paragraphs: ["A Superbuy Shopping Agent order begins with a product page, selected options and quantity. Those structured fields should carry the basic purchase instruction. An order remark is useful only when one material detail is not represented reliably by those fields or when the listing itself tells the buyer to communicate a specific choice. Repeating every selected option in a long message can introduce a contradiction instead of adding protection.", "Open the live seller page and the imported order form side by side. Confirm seller, product identity, colour, size, model, quantity and included pieces. If they already agree, keep the remark empty or use it only to restate the single detail most vulnerable to translation. If they do not agree, pause. A sentence cannot repair a source page that shows incompatible titles, images and option labels.", "This guide concerns Shopping Agent purchasing. Parcel Forwarding starts from an item the customer has already bought and sent to a forwarding address; the forwarding form and inspection limits are different. Do not use a shopping-agent purchase remark to assume that a forwarding warehouse will negotiate with the original seller or verify product promises." ] },
      { heading: "Write observable facts, not quality wishes", paragraphs: ["A useful remark names something another person can compare with the seller page or received item. ‘Black, size 42, one pair; match the black option image’ is observable. ‘Best quality,’ ‘perfect pair’ and ‘choose a good one’ have no shared test. They ask an agent to make a subjective purchasing decision without a measurable threshold.", "Convert each concern into a field: selected colour, printed model code, quantity, version, plug type, text placement or included accessory. If fit matters, preserve the seller chart and specify the labelled size being ordered; do not ask the purchasing agent to guarantee that it will fit. If material matters, quote the exact published specification while recognizing that normal warehouse images may not prove composition.", "Avoid claims that exceed the listing. A seller photograph may show styling props that are not included. A low price may refer to an add-on or deposit. The remark should not turn an inference into an order term. When included quantity is unclear, ask for clarification before payment rather than writing ‘include everything shown.’" ] },
      { heading: "Use a compact four-part remark", paragraphs: ["A reliable structure has four parts: the exact option, the quantity, one listing reference and the action if the detail is unavailable. For example: ‘Navy, XL, quantity 1; use the option image with the white chest mark; do not substitute—ask before purchase.’ This is short enough to translate and specific enough to audit later.", "Keep punctuation simple and place the most important fact first. Marketplace option names may be machine translated, so retain a model number or source-language option text when it is the only stable identifier. Add an image reference only when the order interface supports it and the image unambiguously identifies the choice. Never place payment credentials, identity documents or unnecessary personal data in an order note.", "One order should have one final instruction set. If support clarifies a detail after submission, keep the dated conversation beside the order and update through the current account action if available. Several conflicting messages create an evidence problem: later staff cannot know which sentence superseded the others." ] },
      { heading: "Handle seller price or stock changes without silent approval", paragraphs: ["The official Superbuy Shopping Agent guidance says agents may contact buyers when more information is needed. A seller can also change stock, domestic delivery or the price attached to an option. Your original remark is evidence of what you requested; it is not blanket permission to accept a different product or amount.", "Pre-write a substitution rule. ‘No substitution without confirmation’ is useful when colour, version or size is material. If a nearby option is acceptable, define the boundary: ‘If navy is unavailable, ask before changing to black.’ Do not authorize ‘similar’ unless you can explain which attributes may change and which must remain fixed.", "When a new amount appears, compare the selected option, seller shipping and any named service line. Approve or reject through the live order record, then save the decision. Do not infer a hidden fee from the difference between two totals. The evidence should show which line changed and why." ] },
      { heading: "Plan warehouse evidence separately from purchase remarks", paragraphs: ["An order remark tells the purchasing stage what to buy. A warehouse evidence request tells the intake stage what visible fact would help you decide. Combining the two can produce false expectations. Superbuy’s public Shopping Agent material describes warehouse inspection and three photographs of the actual product, but standard views cannot answer every measurement, internal or functional question.", "Before paying, write a private QC brief beside the order: the views already expected, one possible targeted photo, and the threshold that would change the decision. A shoe buyer might need the size label and insole length; a set buyer might need all included pieces in one frame. Request that evidence through the current warehouse service only if standard material leaves the decision unresolved.", "Do not phrase a purchase note as a guaranteed test. ‘Please make sure it is authentic, waterproof and durable’ cannot be established by ordinary images. Identity, visible label, quantity and a ruler measurement are narrower and auditable. Separating the two briefs makes later after-sales evidence clearer." ] },
      { heading: "Use category-specific examples", paragraphs: ["For footwear, a defensible note is: ‘Grey, EU 43, one pair; match the option image and do not replace the selected size.’ For clothing: ‘Black, size L, quantity 1; use the option labelled heavyweight; no alternate colour.’ For a multi-piece listing: ‘Option B, two-piece set; confirm both named pieces are included before purchase.’ Each instruction points to a visible listing field.", "For electronics or accessories, record model, connector, voltage or compatibility exactly as the seller publishes it, but avoid claiming safety certification or function unless the current service explicitly tests it. For fragile goods, purchase identity belongs in the order remark; reinforcement, outer waterproofing or package removal belongs to the later parcel instruction.", "Manual or DIY orders need even more source detail because automatic parsing may be incomplete. Supply the exact product URL, seller, option, unit price, China domestic delivery, quantity and a neutral description. A clear manual-order record reduces ambiguity, but it still does not expand the platform’s inspection or seller-return boundaries." ] },
      { heading: "Create an audit trail before you submit", paragraphs: ["Save the live URL, seller name, chosen option, item image, quantity, displayed item amount, domestic delivery and your final remark with the check date. After submission, add the order number and confirmation screen. This compact record establishes what the purchasing agent received before the seller page changes.", "When the item reaches the warehouse, compare the intake record with the structured order fields first and the remark second. Mark each material field as match, mismatch or not visible. If a mismatch exists, quote the expected field, observed field and relevant image. ‘Ordered option B with two pieces; intake image shows one’ is actionable. ‘Order ignored my note’ is not enough by itself.", "Keep the remark even after the item is accepted. If a later delivery dispute concerns a missing part or wrong version, the source listing, order instruction, warehouse record and unboxing evidence form one chronology. Store only necessary records and remove personal address or payment information from anything shared publicly." ] },
      { heading: "Run the thirty-second final check", paragraphs: ["Before payment, ask six questions. Does the live listing identify the full product? Do selected fields match the intended option? Is the remark limited to an observable detail? Does it avoid unsupported quality claims? Is the no-substitution rule clear? Is the later warehouse question stored separately? A ‘no’ on identity or option should pause the purchase.", "Read the sentence once as if you were a purchasing agent translating it without the buyer present. Remove adjectives, duplicate instructions and background stories. Put the decision-changing noun and number near the start. If the note needs a paragraph to explain the product, the listing or manual-order data is probably not clear enough yet.", "Superbuy order remarks work best as compact evidence, not insurance against every uncertainty. The seller page defines the offered product, structured selections define the order, the remark resolves one bounded gap, and warehouse evidence supports a later decision. Keeping those roles separate produces fewer contradictions and a stronger record from purchase to parcel." ] }
    ]
  },
  fr: {
    slug: "superbuy-order-remarks-writing-guide", title: "Remarques de commande Superbuy : écrire une consigne vérifiable", dek: "Transformer les preuves de l’annonce en consignes courtes et contrôlables pour une commande Shopping Agent.", sections: [
      {heading:"Déterminer si une remarque est nécessaire",paragraphs:["Les champs structurés doivent porter couleur, taille, modèle et quantité. Une remarque n’est utile que pour un détail matériel absent ou ambigu. Comparez l’annonce active et le formulaire; si l’identité ne concorde pas, suspendez l’achat au lieu de réparer l’annonce par une phrase.","Ce guide vise Shopping Agent. Parcel Forwarding part d’un achat déjà effectué et ne reprend pas automatiquement les obligations d’achat ou d’après-vente du vendeur."]},
      {heading:"Écrire des faits observables",paragraphs:["« Noir, taille 42, une paire; correspondre à l’image de l’option noire » peut être vérifié. « Meilleure qualité » ou « paire parfaite » n’a pas de critère partagé. Transformez la préoccupation en couleur, code, quantité, version ou accessoire.","Ne déduisez pas le contenu d’une photo d’ambiance. Si la quantité ou le type de lien reste ambigu, demandez une clarification avant paiement."]},
      {heading:"Utiliser une structure en quatre parties",paragraphs:["Indiquez option exacte, quantité, référence de l’annonce et action en cas d’indisponibilité : « Marine, XL, 1; image avec marque blanche; ne pas remplacer—demander avant achat. »", "Gardez un texte court, un identifiant source si nécessaire et aucune donnée personnelle inutile. Une seule consigne finale évite les contradictions."]},
      {heading:"Gérer changement de prix ou de stock",paragraphs:["La consigne d’origine ne vaut pas autorisation de substitution. Écrivez « pas de remplacement sans confirmation » lorsque taille, couleur ou version sont essentielles.","Si un montant change, comparez option, livraison intérieure et ligne nommée, puis approuvez ou refusez dans le dossier actif. N’inventez pas un frais caché."]},
      {heading:"Séparer achat et preuve d’entrepôt",paragraphs:["La remarque dit quoi acheter; une demande de preuve dit quel fait visible aidera la décision après réception. Trois photos standard ne répondent pas à toute mesure ou question fonctionnelle.","Préparez une question ciblée—étiquette, longueur de semelle, pièces du lot—et utilisez le service actuel seulement si les images normales ne suffisent pas."]},
      {heading:"Adapter la consigne à la catégorie",paragraphs:["Chaussures : option, pointure et absence de remplacement. Vêtement : couleur, taille et version. Lot : nommer chaque pièce. Électronique : recopier modèle et connecteur sans promettre un test non documenté.","Protection et retrait d’emballage appartiennent à l’instruction de colis, non à la remarque d’achat."]},
      {heading:"Créer une piste d’audit",paragraphs:["Conservez URL, vendeur, option, image, quantité, montant, livraison intérieure, remarque et date, puis le numéro de commande. À l’entrepôt, classez chaque champ : conforme, différent ou non visible.","Pour un écart, décrivez attendu, observé et image. Gardez les preuves nécessaires sans partager adresse ni paiement."]},
      {heading:"Faire le contrôle final",paragraphs:["Vérifiez identité, option, caractère observable, absence de promesse subjective, règle de substitution et séparation de la question QC. Un problème d’identité doit arrêter l’achat.","Une bonne remarque résout un manque précis; elle ne remplace ni l’annonce, ni les choix structurés, ni la décision d’entrepôt."]}
    ]
  },
  de: {
    slug: "superbuy-order-remarks-writing-guide", title: "Superbuy-Bestellhinweise: prüfbare Anweisungen schreiben", dek: "Listing-Belege in kurze, überprüfbare Shopping-Agent-Hinweise übersetzen, ohne das Lager raten zu lassen.", sections: [
      {heading:"Prüfen, ob ein Hinweis nötig ist",paragraphs:["Strukturierte Felder tragen Farbe, Größe, Modell und Menge. Ein Hinweis löst nur eine materielle Lücke. Stimmen Live-Listing und Formular nicht überein, Kauf pausieren statt den Widerspruch mit Text zu überdecken.","Shopping Agent und Parcel Forwarding haben unterschiedliche Ausgangspunkte; Einkaufs- und Verkäuferpflichten nicht auf Weiterleitung übertragen."]},
      {heading:"Beobachtbare Fakten schreiben",paragraphs:["„Schwarz, Größe 42, ein Paar; schwarzes Optionsbild abgleichen“ ist prüfbar. „Beste Qualität“ oder „perfekt“ hat keinen gemeinsamen Maßstab. Sorge in Farbe, Code, Menge, Version oder Zubehör übersetzen.","Lieferumfang nicht aus einem Lifestyle-Bild ableiten. Bei unklarer Menge oder Linkart vor Zahlung klären."]},
      {heading:"Vier Teile verwenden",paragraphs:["Exakte Option, Menge, Listing-Referenz und Handlung bei Nichtverfügbarkeit: „Marine, XL, 1; Bild mit weißer Brustmarke; nicht ersetzen—vor Kauf fragen.“", "Kurz schreiben, stabile Quellbezeichnung behalten und keine unnötigen Personendaten einfügen. Eine endgültige Anweisung verhindert Konflikte."]},
      {heading:"Preis- und Bestandsänderungen behandeln",paragraphs:["Der ursprüngliche Hinweis genehmigt keinen Ersatz. Wenn Größe, Farbe oder Version wesentlich sind: „Keine Substitution ohne Bestätigung.“", "Bei neuem Betrag Option, Inlandsversand und benannte Zeile vergleichen und im aktuellen Datensatz entscheiden. Keine unsichtbare Gebühr erfinden."]},
      {heading:"Kaufhinweis und Lagerbeleg trennen",paragraphs:["Der Hinweis definiert den Kauf; die spätere Belegfrage definiert ein sichtbares Entscheidungskriterium. Standardfotos beantworten nicht jede Mess- oder Funktionsfrage.","Gezielte Frage vorbereiten—Etikett, Einlegesohlenlänge oder alle Set-Teile—und nur bei ungelöster Entscheidung über aktuelle Dienste anfordern."]},
      {heading:"Nach Kategorie formulieren",paragraphs:["Schuhe: Option, Größe, kein Ersatz. Kleidung: Farbe, Größe, Ausführung. Set: jedes Teil benennen. Elektronik: Modell und Anschluss exakt übernehmen, keinen nicht dokumentierten Test versprechen.","Verstärkung oder Verpackungsentfernung gehört zur späteren Paketanweisung."]},
      {heading:"Prüfspur anlegen",paragraphs:["URL, Verkäufer, Option, Bild, Menge, Betrag, Inlandsversand, Hinweis und Datum sichern; danach Bestellnummer ergänzen. Im Lager jedes Feld als passend, abweichend oder nicht sichtbar markieren.","Bei Abweichung Erwartung, Beobachtung und Bild nennen. Nur nötige Belege behalten und Adress- oder Zahlungsdaten nicht öffentlich teilen."]},
      {heading:"Abschlussprüfung durchführen",paragraphs:["Identität, Option, Beobachtbarkeit, keine subjektive Zusage, Ersatzregel und getrennte QC-Frage prüfen. Ein Identitätsproblem stoppt den Kauf.","Ein guter Hinweis schließt eine begrenzte Lücke; er ersetzt weder Listing noch Auswahlfelder noch Lagerentscheidung."]}
    ]
  }
};
