import type { Article, Locale } from "./content";

export const sellerNotShippedArticle: Record<Locale, Article> = {
  en: {
    slug: "superbuy-seller-not-shipped-delay-record",
    title: "Superbuy Seller Not Shipped: Build a Delay Record Before You Urge Delivery",
    dek: "A Shopping Agent workflow for separating seller delay from purchase processing, preserving dated evidence and asking for one clear next action.",
    sections: [
      { heading: "Start with the service and the exact order stage", paragraphs: [
        "A Superbuy Shopping Agent order passes through a purchasing stage before the seller sends the item to the warehouse. A quiet order page does not by itself prove that the seller has refused to ship. The agent may still be confirming an option, waiting for a seller response, completing the purchase or recording domestic logistics. Begin with the current order record, not an assumed cause.",
        "Confirm that the order belongs to Shopping Agent rather than Parcel Forwarding. With Shopping Agent, Superbuy purchases from the seller and the seller sends the item to the selected warehouse. Parcel Forwarding begins with an item the customer has already bought and requires its own submission and logistics record. Mixing those workflows produces the wrong question and the wrong evidence.",
        "Write down the displayed order number, item, selected variant, payment time and current status exactly as shown. Do not rename the status in your notes or translate it into a stronger conclusion. The useful starting statement is factual: the order shows a particular stage and no seller-to-warehouse tracking number is visible at the time checked."
      ] },
      { heading: "Build a dated delay record before contacting anyone", paragraphs: [
        "Create one short timeline instead of opening several disconnected enquiries. Record the time the item payment was confirmed, the time the purchasing stage appeared, every request for missing information, any price or stock message, and the latest time the order page was checked. Attach a saved listing snapshot and the final selected option so a later reply can be compared with the original instruction.",
        "Use separate fields for facts and unknowns. Facts may include a confirmed order number, a visible status, a dated message and whether domestic tracking is present. Unknowns may include whether the agent has placed the purchase, whether the seller accepted it, whether stock remains, and whether a tracking number has simply not been uploaded. This separation prevents an unverified guess from becoming the premise of the enquiry.",
        "Keep the record proportionate. A screenshot of the order area, the relevant seller listing and one message thread is usually more useful than a gallery of repeated refreshes. Hide names, addresses, balance details and payment identifiers before sharing anything outside the account. The purpose is to preserve the decision trail, not to publish a private order."
      ] },
      { heading: "Use the official three-day urge point carefully", paragraphs: [
        "Superbuy's public Help Center currently states that a Shopping Agent order can be urged for delivery after three days. Treat that as the availability of an account action, not a promise that the seller must dispatch within three days. The seller's own handling time, stock position and domestic carrier collection can still affect what happens next.",
        "Count from the timestamp that the live account associates with the relevant purchasing stage, not from the moment you first saved a product link. If the account exposes an Urged Delivery action, use that current interface after the stated threshold and record the time. Do not send repeated reminders through several channels on the same day; duplicate messages can fragment the answer and obscure which request is active.",
        "If the action is unavailable despite the elapsed time, preserve a screenshot of the stage and use the order-enquiry route shown for the order. Describe the dates rather than asserting that the system is broken. Interface labels and eligibility can change, so the live account and current Help Center should override an old tutorial or a remembered button location."
      ] },
      { heading: "Ask for one answer that changes the decision", paragraphs: [
        "A useful enquiry contains the order number, current displayed stage, purchase or payment date, absence of visible domestic tracking, and one requested outcome. Ask whether the seller has accepted the order and whether a dispatch date or domestic tracking reference is available. If neither is available, ask what buyer action is currently possible. This gives support a bounded question they can take to the seller.",
        "Avoid messages such as 'ship now', 'why so slow' or 'please solve urgently' without an order reference. They express frustration but do not identify the missing fact. A clearer note is: 'Order [number] has shown [status] since [date]. No domestic tracking is visible. Please confirm whether the seller accepted the order and advise the next available action if no dispatch date exists.'",
        "Keep option and substitution rules visible. If the selected size, colour or version is essential, restate that no substitute should be accepted without confirmation. If the seller proposes another option or a higher amount, treat it as a new decision. The earlier order remark is evidence of the original request, not permission for an unrecorded change."
      ] },
      { heading: "Separate four common explanations", paragraphs: [
        "First, the agent may still need information from the buyer. Superbuy's Shopping Agent guidance says agents may contact the customer by email or message when details are required. Check the account inbox and the order enquiry before escalating a seller delay. A missed colour choice, manual-order field or price-change confirmation can pause progress even when the listing still looks available.",
        "Second, the seller may have accepted the purchase but not handed it to a domestic carrier. Third, a parcel may have moved while tracking is absent or incomplete. Fourth, the listing may be out of stock, repriced or no longer consistent with the selected option. These situations can look similar from a single status label but require different responses: complete information, wait for dispatch, request tracking, or decide whether to cancel or approve a change.",
        "Do not use an international parcel tracker for this stage. The item has not yet completed seller-to-warehouse movement, so international route, customs and delivery estimates are not relevant. Domestic tracking belongs to the purchase record; international tracking begins only after warehouse acceptance, parcel submission, packing and carrier handoff."
      ] },
      { heading: "Choose wait, clarify or cancel from evidence", paragraphs: [
        "Waiting is reasonable when the seller has confirmed stock and given a dated dispatch expectation that fits your plan. Clarification is better when the order stage is ambiguous, a message is unanswered or tracking is said to exist but is not visible. A cancellation question becomes appropriate when stock is unavailable, the seller cannot provide a dispatch expectation, a material option has changed, or the delay threatens the buyer's warehouse and parcel plan.",
        "Do not present cancellation as automatic. Whether it is currently possible can depend on the stage, seller progress and the live rules shown in the account. Ask what action is available and what consequences are recorded before confirming. If a refund follows, keep its request, approval and settlement as separate dated events rather than assuming that cancellation and returned funds occur at the same moment.",
        "Consider the whole planned parcel without turning the article into a shipping-cost guide. A late item may hold back other stored orders, but dispatching everything else can change grouping and packaging decisions. Record the oldest warehouse arrival, the desired consolidation group and the latest acceptable decision date. This converts vague impatience into a defined trade-off."
      ] },
      { heading: "Close the record when domestic tracking appears", paragraphs: [
        "A domestic tracking number is evidence of a logistics record, not proof that the warehouse has received the correct item. Save the number, carrier if shown, first scan time and order association. Watch for the warehouse intake event instead of declaring the delay finished from a number alone. A label can be created before the carrier records meaningful movement.",
        "When the item arrives, compare the warehouse record with the order number, selected variant, quantity and any seller-change message. Then review the available inspection evidence under the warehouse-arrival workflow. Keep purchase delay, warehouse condition and later parcel submission as distinct stages; each has different actors, records and remedies.",
        "If tracking stops before warehouse delivery, extend the same chronology with scan dates and the latest account response. Do not invent a loss date or carrier conclusion. Ask whether the seller or agent has opened the appropriate domestic enquiry and what evidence is required from the buyer."
      ] },
      { heading: "Run a final seller-delay checklist", paragraphs: [
        "Before sending an enquiry, verify eight fields: service type, order number, item and option, payment or purchase date, current displayed stage, last message, presence of domestic tracking, and the single decision you need. Check whether three days have elapsed according to the live order timeline and whether the Urged Delivery action is available. Remove assumptions and private payment data from the note.",
        "After sending, add the enquiry time and wait for the current response channel rather than starting parallel threads. When a reply arrives, classify it as information needed, seller accepted, dispatch expected, tracking supplied, stock or price changed, or action available. Set the next review date from that reply; do not let an unresolved order disappear inside a general inbox.",
        "The practical goal is not to force a prediction from a silent status. It is to show what stage the Shopping Agent order has reached, what seller-to-warehouse evidence is missing, when the official urge action became available, and which next action the buyer can actually choose. A compact dated record makes that conversation faster and protects later decisions if the listing or order changes."
      ] }
    ]
  },
  fr: {
    slug: "superbuy-seller-not-shipped-delay-record",
    title: "Vendeur Superbuy sans expédition : constituer un dossier de retard avant de relancer",
    dek: "Une méthode Shopping Agent pour distinguer le retard vendeur du traitement d'achat, conserver les preuves datées et demander une prochaine action claire.",
    sections: [
      { heading: "Commencer par le service et l'étape exacte", paragraphs: [
        "Une commande Superbuy Shopping Agent passe par une étape d'achat avant que le vendeur envoie l'article à l'entrepôt. Une page de commande silencieuse ne prouve pas à elle seule que le vendeur refuse d'expédier. L'agent peut encore confirmer une option, attendre une réponse, finaliser l'achat ou enregistrer la logistique intérieure. Partez du dossier actuel, pas d'une cause supposée.",
        "Vérifiez que la commande relève de Shopping Agent et non de Parcel Forwarding. Avec Shopping Agent, Superbuy achète au vendeur, qui envoie ensuite l'article à l'entrepôt choisi. Parcel Forwarding commence avec un article déjà acheté par le client et exige sa propre soumission et son propre suivi. Confondre ces parcours produit la mauvaise question et les mauvaises preuves.",
        "Notez exactement le numéro affiché, l'article, la variante, l'heure de paiement et le statut actuel. Ne renommez pas le statut et ne le traduisez pas en conclusion plus forte. Le bon constat initial reste factuel : la commande affiche une étape précise et aucun suivi vendeur-entrepôt n'est visible au moment du contrôle."
      ] },
      { heading: "Créer un dossier daté avant de contacter le support", paragraphs: [
        "Construisez une courte chronologie plutôt que plusieurs demandes isolées. Consignez la confirmation du paiement, l'apparition de l'étape d'achat, chaque demande d'information, tout message de prix ou de stock et la dernière vérification. Joignez un instantané de l'annonce et l'option finale afin de comparer une réponse ultérieure avec l'instruction d'origine.",
        "Séparez faits et inconnues. Les faits comprennent le numéro confirmé, le statut visible, un message daté et la présence du suivi intérieur. Les inconnues comprennent l'achat réellement passé, l'acceptation du vendeur, le stock restant ou un numéro simplement non ajouté. Cette séparation évite qu'une hypothèse devienne le point de départ de la demande.",
        "Gardez un dossier proportionné. Une capture de la commande, l'annonce pertinente et un fil de messages sont plus utiles qu'une série de rafraîchissements identiques. Masquez noms, adresses, solde et identifiants de paiement avant tout partage hors du compte. Il s'agit de conserver la décision, pas de publier une commande privée."
      ] },
      { heading: "Utiliser avec prudence le seuil officiel de trois jours", paragraphs: [
        "Le centre d'aide public de Superbuy indique actuellement qu'une commande Shopping Agent peut être relancée après trois jours. Il s'agit de la disponibilité d'une action de compte, pas d'une promesse que le vendeur doit expédier sous trois jours. Son délai de préparation, le stock et la collecte par le transporteur intérieur peuvent encore influencer la suite.",
        "Comptez depuis l'horodatage associé par le compte à l'étape d'achat concernée, et non depuis l'enregistrement initial d'un lien produit. Si l'action Urged Delivery apparaît, utilisez l'interface active après le seuil et notez l'heure. N'envoyez pas plusieurs rappels par différents canaux le même jour : ils fragmentent la réponse et masquent la demande active.",
        "Si l'action reste indisponible malgré le délai, conservez une capture de l'étape et utilisez la demande liée à la commande. Décrivez les dates sans affirmer que le système est défectueux. Les libellés et l'éligibilité changent; le compte actif et le centre d'aide actuel priment sur un ancien tutoriel ou le souvenir d'un bouton."
      ] },
      { heading: "Demander une réponse qui change la décision", paragraphs: [
        "Une demande utile contient le numéro, l'étape affichée, la date d'achat ou de paiement, l'absence de suivi intérieur et un seul résultat demandé. Demandez si le vendeur a accepté la commande et si une date d'expédition ou une référence intérieure existe. Sinon, demandez quelle action est actuellement possible pour l'acheteur. La question reste ainsi limitée et vérifiable.",
        "Évitez « expédiez maintenant », « pourquoi si lent » ou « urgent » sans référence. Une formule plus claire est : « La commande [numéro] affiche [statut] depuis [date]. Aucun suivi intérieur n'est visible. Merci de confirmer si le vendeur a accepté et d'indiquer l'action disponible si aucune date d'expédition n'existe. »",
        "Gardez visibles les règles d'option et de remplacement. Si taille, couleur ou version est essentielle, rappelez qu'aucun substitut ne doit être accepté sans confirmation. Une autre option ou un montant supérieur constitue une nouvelle décision. La remarque initiale prouve la demande d'origine; elle n'autorise pas un changement non consigné."
      ] },
      { heading: "Distinguer quatre explications fréquentes", paragraphs: [
        "Première possibilité : l'agent attend encore une information de l'acheteur. Le guide Shopping Agent précise que l'agent peut contacter le client par courriel ou message. Vérifiez messagerie et demande de commande avant d'escalader. Une couleur oubliée, un champ manuel ou une approbation de prix peut bloquer le progrès même si l'annonce paraît disponible.",
        "Deuxièmement, le vendeur peut avoir accepté sans remettre l'article au transporteur. Troisièmement, le colis peut bouger sans suivi complet. Quatrièmement, l'annonce peut être épuisée, réévaluée ou incompatible avec l'option. Un seul statut masque ces différences; les réponses sont distinctes : compléter, attendre, demander le suivi, annuler ou approuver un changement.",
        "N'utilisez pas un suivi international à ce stade. L'article n'a pas fini le trajet vendeur-entrepôt; ligne internationale, douane et délai final ne sont pas pertinents. Le suivi intérieur appartient au dossier d'achat. Le suivi international commence après réception, soumission du colis, emballage et remise au transporteur."
      ] },
      { heading: "Choisir attente, clarification ou annulation sur preuves", paragraphs: [
        "Attendre est raisonnable si le vendeur confirme le stock et fournit une attente datée compatible avec le plan. Clarifiez si l'étape est ambiguë, un message reste sans réponse ou un suivi annoncé n'est pas visible. Une question d'annulation devient pertinente si le stock manque, si aucune date n'est donnée, si une option change ou si le retard menace le plan d'entrepôt et de colis.",
        "Ne présentez pas l'annulation comme automatique. Sa possibilité dépend de l'étape, de l'avancement vendeur et des règles visibles. Demandez l'action disponible et ses conséquences avant de confirmer. Si un remboursement suit, conservez demande, approbation et règlement comme événements séparés au lieu de supposer que l'annulation et le retour des fonds sont simultanés.",
        "Considérez le colis prévu sans transformer ce guide en calcul de transport. Un article tardif peut retenir les autres, mais expédier le reste modifie regroupement et emballage. Notez la plus ancienne arrivée, le groupe souhaité et la dernière date de décision acceptable. L'impatience devient alors un arbitrage défini."
      ] },
      { heading: "Clore le retard lorsque le suivi intérieur apparaît", paragraphs: [
        "Un numéro intérieur prouve l'existence d'un dossier logistique, pas la réception du bon article. Conservez numéro, transporteur s'il est affiché, premier scan et association à la commande. Attendez l'entrée en entrepôt avant de déclarer le retard terminé. Une étiquette peut être créée avant tout mouvement significatif.",
        "À l'arrivée, comparez le dossier d'entrepôt au numéro, à la variante, à la quantité et aux messages de changement. Examinez ensuite les preuves d'inspection selon le parcours de réception. Gardez distincts retard d'achat, état à l'entrepôt et soumission du colis : les acteurs, preuves et solutions diffèrent.",
        "Si le suivi s'arrête avant la livraison à l'entrepôt, prolongez la chronologie avec scans et dernière réponse. N'inventez ni date de perte ni conclusion du transporteur. Demandez si le vendeur ou l'agent a ouvert la demande intérieure appropriée et quelles preuves l'acheteur doit fournir."
      ] },
      { heading: "Effectuer la vérification finale du retard vendeur", paragraphs: [
        "Avant d'envoyer, vérifiez huit champs : service, numéro, article et option, date de paiement ou d'achat, étape affichée, dernier message, suivi intérieur et décision recherchée. Contrôlez si trois jours se sont écoulés selon la chronologie active et si Urged Delivery est disponible. Retirez hypothèses et données de paiement privées.",
        "Après l'envoi, ajoutez l'heure et attendez le canal actuel au lieu d'ouvrir des fils parallèles. Classez la réponse : information nécessaire, vendeur accepté, expédition prévue, suivi fourni, stock ou prix changé, action disponible. Fixez la prochaine date de contrôle à partir de cette réponse pour que la commande ne disparaisse pas dans une boîte générale.",
        "Le but n'est pas de forcer une prédiction depuis un statut silencieux. Il faut montrer l'étape atteinte, la preuve vendeur-entrepôt manquante, le moment où la relance officielle devient disponible et l'action réellement ouverte à l'acheteur. Un dossier compact et daté accélère l'échange et protège les décisions si l'annonce ou la commande change."
      ] }
    ]
  },
  de: {
    slug: "superbuy-seller-not-shipped-delay-record",
    title: "Superbuy-Verkäufer hat nicht versandt: Verzögerung vor dem Nachhaken dokumentieren",
    dek: "Ein Shopping-Agent-Ablauf, der Verkäuferverzug von Kaufbearbeitung trennt, datierte Belege sichert und nach einem klaren nächsten Schritt fragt.",
    sections: [
      { heading: "Mit Dienst und genauer Bestellstufe beginnen", paragraphs: [
        "Eine Superbuy-Shopping-Agent-Bestellung durchläuft eine Kaufphase, bevor der Verkäufer den Artikel ans Lager sendet. Eine unveränderte Bestellseite beweist nicht, dass der Verkäufer den Versand verweigert. Der Agent kann noch eine Option bestätigen, auf Antwort warten, den Kauf abschließen oder Inlandlogistik erfassen. Ausgangspunkt ist der aktuelle Datensatz, nicht eine vermutete Ursache.",
        "Prüfe, ob die Bestellung Shopping Agent und nicht Parcel Forwarding betrifft. Beim Shopping Agent kauft Superbuy beim Verkäufer, der zum gewählten Lager sendet. Parcel Forwarding beginnt mit einem bereits vom Kunden gekauften Artikel und verlangt eine eigene Anmeldung samt Logistikdatensatz. Eine Vermischung führt zur falschen Frage und zu falschen Belegen.",
        "Notiere Bestellnummer, Artikel, Variante, Zahlungszeit und aktuellen Status genau wie angezeigt. Benenne den Status nicht um und mache daraus keine stärkere Schlussfolgerung. Die brauchbare Ausgangsaussage ist sachlich: Die Bestellung zeigt eine bestimmte Stufe, und zum Prüfzeitpunkt ist keine Verkäufer-zum-Lager-Sendungsnummer sichtbar."
      ] },
      { heading: "Vor dem Kontakt einen datierten Verzögerungsnachweis anlegen", paragraphs: [
        "Erstelle eine kurze Zeitleiste statt mehrerer unverbundener Anfragen. Erfasse Zahlungsbestätigung, Beginn der Kaufphase, jede Informationsanforderung, Preis- oder Bestandsmeldung und den letzten Prüfzeitpunkt. Sichere Listing und endgültige Option, damit eine spätere Antwort mit der ursprünglichen Anweisung verglichen werden kann.",
        "Trenne Fakten und Unbekanntes. Fakten sind bestätigte Nummer, sichtbarer Status, datierte Nachricht und vorhandene Inlandverfolgung. Unbekannt sind der tatsächlich platzierte Kauf, Verkäuferannahme, Restbestand oder eine nur noch nicht eingetragene Sendungsnummer. So wird eine Vermutung nicht zur Grundlage der Anfrage.",
        "Halte den Datensatz angemessen. Ein Bild des Bestellbereichs, das relevante Listing und ein Nachrichtenverlauf sind nützlicher als viele identische Aktualisierungen. Verberge Namen, Adressen, Guthaben und Zahlungskennungen vor externer Weitergabe. Ziel ist die Entscheidungsspur, nicht die Veröffentlichung einer privaten Bestellung."
      ] },
      { heading: "Den offiziellen Drei-Tage-Punkt vorsichtig verwenden", paragraphs: [
        "Das öffentliche Superbuy Help Center erklärt derzeit, dass eine Shopping-Agent-Bestellung nach drei Tagen zur Lieferung angemahnt werden kann. Das bedeutet, dass eine Kontoaktion verfügbar wird, nicht dass der Verkäufer zwingend binnen drei Tagen versendet. Bearbeitungszeit, Bestand und Abholung durch den Inlandfrachtführer können den nächsten Schritt weiterhin beeinflussen.",
        "Zähle ab dem Zeitstempel, den das Konto der betreffenden Kaufphase zuordnet, nicht ab dem Speichern eines Produktlinks. Wenn Urged Delivery erscheint, nutze die aktuelle Oberfläche nach der Schwelle und protokolliere die Zeit. Sende nicht am selben Tag über mehrere Kanäle wiederholt Erinnerungen; sie zerteilen Antworten und verschleiern die aktive Anfrage.",
        "Ist die Aktion trotz verstrichener Zeit nicht verfügbar, sichere die Stufe und nutze die zur Bestellung gehörende Anfrage. Beschreibe Daten, ohne einen Systemfehler zu behaupten. Bezeichnungen und Berechtigung können sich ändern; Live-Konto und aktuelles Help Center haben Vorrang vor alten Tutorials oder einer erinnerten Schaltfläche."
      ] },
      { heading: "Nach einer entscheidungsrelevanten Antwort fragen", paragraphs: [
        "Eine nützliche Anfrage enthält Nummer, angezeigte Stufe, Kauf- oder Zahlungsdatum, fehlende Inlandverfolgung und ein gewünschtes Ergebnis. Frage, ob der Verkäufer angenommen hat und ob Versanddatum oder Referenz vorliegen. Wenn nicht, frage nach der aktuell möglichen Käuferaktion. So erhält der Support eine begrenzte, prüfbare Frage.",
        "Vermeide Nachrichten wie „jetzt versenden“, „warum so langsam“ oder „dringend lösen“ ohne Referenz. Klarer ist: „Bestellung [Nummer] zeigt seit [Datum] [Status]. Keine Inlandverfolgung ist sichtbar. Bitte bestätige die Verkäuferannahme und nenne die verfügbare Aktion, falls kein Versanddatum existiert.“",
        "Halte Options- und Ersatzregeln sichtbar. Ist Größe, Farbe oder Version wesentlich, darf kein Ersatz ohne Bestätigung angenommen werden. Eine andere Option oder ein höherer Betrag ist eine neue Entscheidung. Die frühere Bestellnotiz belegt die ursprüngliche Anfrage; sie erlaubt keine undokumentierte Änderung."
      ] },
      { heading: "Vier häufige Erklärungen auseinanderhalten", paragraphs: [
        "Erstens kann der Agent noch Angaben des Käufers benötigen. Laut Shopping-Agent-Leitfaden kann er Kunden per E-Mail oder Nachricht kontaktieren. Prüfe Postfach und Bestellanfrage, bevor du Verkäuferverzug eskalierst. Eine fehlende Farbe, ein manuelles Feld oder die Bestätigung einer Preisänderung kann den Ablauf trotz verfügbar wirkendem Listing anhalten.",
        "Zweitens kann der Verkäufer angenommen, aber noch nicht an den Inlandfrachtführer übergeben haben. Drittens kann die Ware ohne vollständiges Tracking unterwegs sein. Viertens kann das Listing ausverkauft, neu bepreist oder nicht mehr mit der Option vereinbar sein. Ein Status sieht ähnlich aus, verlangt aber Ergänzen, Warten, Trackinganfrage oder Entscheidung über Storno beziehungsweise Änderung.",
        "Nutze in dieser Phase keine internationale Paketverfolgung. Der Artikel hat Verkäufer-zum-Lager noch nicht abgeschlossen; internationale Route, Zoll und Lieferprognose sind irrelevant. Inlandtracking gehört zum Kaufdatensatz. Internationales Tracking beginnt erst nach Lagerannahme, Paketeinreichung, Verpackung und Frachtführerübergabe."
      ] },
      { heading: "Warten, klären oder stornieren anhand von Belegen", paragraphs: [
        "Warten ist vertretbar, wenn der Verkäufer Bestand bestätigt und eine datierte Versanderwartung nennt, die zum Plan passt. Klären ist besser bei unklarer Stufe, unbeantworteter Nachricht oder angekündigtem, aber unsichtbarem Tracking. Eine Stornofrage wird relevant bei fehlendem Bestand, fehlender Prognose, geänderter Option oder wenn die Verzögerung Lager- und Paketplanung gefährdet.",
        "Stelle Stornierung nicht als automatisch dar. Ob sie möglich ist, hängt von Stufe, Verkäuferfortschritt und sichtbaren Regeln ab. Frage nach verfügbarer Aktion und protokollierten Folgen. Folgt eine Erstattung, führe Antrag, Genehmigung und Gutschrift als getrennte Ereignisse; Storno und Rückkehr der Mittel geschehen nicht zwingend gleichzeitig.",
        "Betrachte das geplante Paket, ohne daraus einen Versandkostenratgeber zu machen. Ein später Artikel kann andere zurückhalten; der Versand des Rests ändert Gruppierung und Verpackung. Notiere ältesten Lagereingang, gewünschte Gruppe und spätestes akzeptables Entscheidungsdatum. So wird Ungeduld zu einer definierten Abwägung."
      ] },
      { heading: "Den Datensatz bei sichtbarem Inlandtracking schließen", paragraphs: [
        "Eine Inlandnummer belegt einen Logistikdatensatz, nicht den Eingang des richtigen Artikels. Sichere Nummer, Frachtführer falls angezeigt, ersten Scan und Bestellzuordnung. Warte auf den Lagereingang, bevor du die Verzögerung für beendet hältst. Ein Etikett kann vor echter Bewegung erzeugt werden.",
        "Vergleiche nach Ankunft den Lagerdatensatz mit Bestellnummer, Variante, Menge und Änderungsnachricht. Prüfe dann die Inspektionsbelege im Wareneingangsablauf. Halte Kaufverzögerung, Lagerzustand und spätere Paketeinreichung getrennt; sie haben verschiedene Beteiligte, Aufzeichnungen und Lösungen.",
        "Stoppt das Tracking vor dem Lager, erweitere die Chronologie um Scans und letzte Kontoantwort. Erfinde weder Verlustdatum noch Frachtführerurteil. Frage, ob Verkäufer oder Agent die passende Inlandsanfrage eröffnet hat und welche Belege vom Käufer nötig sind."
      ] },
      { heading: "Abschließende Verkäuferverzugsprüfung durchführen", paragraphs: [
        "Prüfe vor dem Senden acht Felder: Dienst, Nummer, Artikel und Option, Zahlungs- oder Kaufdatum, sichtbare Stufe, letzte Nachricht, Inlandtracking und benötigte Entscheidung. Kontrolliere anhand der Live-Zeitleiste, ob drei Tage verstrichen sind und Urged Delivery verfügbar ist. Entferne Annahmen und private Zahlungsdaten.",
        "Ergänze nach dem Senden die Zeit und warte im aktuellen Kanal, statt parallele Threads zu eröffnen. Ordne die Antwort ein: Angaben benötigt, Verkäufer angenommen, Versand erwartet, Tracking geliefert, Bestand oder Preis geändert, Aktion verfügbar. Setze daraus das nächste Prüfdatum, damit die Bestellung nicht in einem allgemeinen Postfach verschwindet.",
        "Ziel ist nicht, aus einem stillen Status eine Prognose zu erzwingen. Der Datensatz soll zeigen, welche Shopping-Agent-Stufe erreicht ist, welcher Verkäufer-zum-Lager-Beleg fehlt, wann die offizielle Mahnaktion verfügbar wurde und was der Käufer tatsächlich wählen kann. Eine kompakte datierte Spur beschleunigt das Gespräch und schützt spätere Entscheidungen bei Änderungen."
      ] }
    ]
  }
};
