import type { Guide } from "./guides";

const maintenanceSource = {
  title: "AllChinaBuy public homepage — maintenance notice",
  url: "https://www.allchinabuy.com/",
  scope: "Observed October 5, 2026. The notice describes maintenance following a hacker attack and directs order enquiries to support. It gives no confirmed reopening date or order-specific outcome.",
};
const evidenceNote = "The official homepage maintenance notice was checked on October 5, 2026. The workflows and examples below are editorial guidance, not confirmation that account functions are currently available. Historical service descriptions are identified as historical; current fees, deadlines and individual order outcomes have not been verified.";
const base = {
  updated: "October 5, 2026", publishedDate: "2026-10-05", modifiedDate: "2026-10-05",
  readingTime: "9 min read", hideSourceLinks: true, evidenceNote,
};

export const octoberGuides: Guide[] = [
  {
    ...base,
    slug: "allchinabuy-website-status-maintenance",
    title: "AllChinaBuy Website Status: Maintenance and Order Support",
    eyebrow: "Platform status",
    description: "Read the confirmed AllChinaBuy maintenance notice, distinguish website access from order status, and prepare a clear support request with dated evidence.",
    keyFacts: [
      "The official homepage displayed a maintenance notice when checked on October 5, 2026.",
      "The notice does not establish a reopening date, permanent closure or the status of an individual order.",
      "A useful support request identifies the order, payment, last confirmed event and the specific action requested.",
    ],
    figure: { src: "/images/guides/allchinabuy-workflow.svg", alt: "Editorial diagram of the product, warehouse and parcel stages", caption: "Use the order stage to organise evidence. This diagram is an explanatory model, not a live service-status monitor.", sourceUrl: "" },
    sections: [
      { title: "What the official notice actually confirms", paragraphs: [
        "If AllChinaBuy is not working when you try to open it, start by identifying exactly what the official website says. On October 5, 2026, the public homepage displayed a maintenance notice. It attributed the maintenance and upgrade process to an ongoing hacker attack and directed users with order questions to customer support. That is the verified platform statement available for this update. It is a statement about the website; it is not a record of your purchase, stored item or international parcel.",
        "The notice did not give a confirmed reopening date or explain the outcome of every pending order. It also did not, by itself, establish permanent closure. A third-party headline may make a stronger claim, but a stronger headline is not stronger evidence. Keep separate notes for what the official notice confirms, what your own account or carrier record confirms, and what remains unknown. This separation prevents a general access problem from becoming an unsupported conclusion about money or goods.",
      ] },
      { title: "Separate website access, account access and parcel movement", paragraphs: [
        "Three different systems can be involved in an AllChinaBuy status check. The public website serves pages. The account area holds your order information. A carrier records physical events after it receives a shipment. One can be unavailable while another still produces useful information. A maintenance page therefore cannot tell you whether a seller has dispatched your product or a carrier has delivered a parcel. Equally, a working public product page does not prove that new orders, withdrawals or warehouse operations are available.",
        "Write the problem as a precise observation: the homepage shows a notice; the account page fails after login; the order has no new event; or the carrier shows an exception. Include the date, time and relevant URL without sharing a password or session token. A screenshot of a failed page is useful evidence of that page at that moment. Avoid repeatedly changing passwords or creating replacement accounts merely because an unrelated public page does not load.",
      ], checklist: ["Record the exact page and time of the access problem.", "Keep account status separate from public website status.", "Use the named carrier for a parcel that already has a valid tracking number."] },
      { title: "Choose the next step from your last confirmed order stage", paragraphs: [
        "For an item not yet purchased, pause the decision until you can verify the current service and payment terms. A saved spreadsheet row can remain useful for product research, but it is not evidence that an agent can presently process that item. Check the original marketplace item identity and preserve the size, colour and quantity you intended to buy. Do not make a second payment simply to test whether the first one failed.",
        "For an existing paid order, collect the order reference, payment receipt and last visible status. If it was already in a warehouse, keep the warehouse item reference and any QC photographs. If an international parcel was submitted, add the parcel reference, selected route and carrier tracking number. These stages require different questions: confirmation of purchase, confirmation of storage, or confirmation of a physical handoff. Asking for the next missing record is more useful than asking only when everything will work again.",
      ] },
      { title: "Build one dated evidence file", paragraphs: [
        "A small chronological record is easier to review than many disconnected screenshots. Start with a table containing date, source, reference, observed event and supporting file. Preserve the original payment amount and currency, the recipient shown by your payment provider, and any order confirmation. For a warehouse item, add the saved QC set and your selected option. For a shipped parcel, add the last carrier event exactly as written, including its timezone if shown.",
        "Use a separate column for interpretation. For example, ‘payment completed’ is a transaction observation; ‘the seller has purchased the item’ is a different claim that needs an order record. Similarly, a tracking number being generated does not establish physical carrier acceptance. Label unknown information as unknown rather than filling gaps with estimates. Keep original files unchanged and use copies when highlighting a relevant line, cropping unrelated information or preparing an attachment for support.",
      ], takeaway: "One timeline should show what happened, where the evidence came from and what still needs confirmation." },
      { title: "Send a support request that can be answered", paragraphs: [
        "Use the support route identified on the official website and verify the destination before submitting personal information. This independent directory cannot access an AllChinaBuy account, cancel an order or release a refund. A clear message begins with one order or parcel reference, a short dated timeline and the action requested. If several orders share a parcel, identify the relationship explicitly instead of combining unrelated references in one paragraph.",
        "A practical message might say that payment was recorded on a stated date, the last order screen showed a stated stage, and you need confirmation of whether the purchase was completed. Attach only the relevant evidence and ask what information is missing. Save the case number and response. When following up, refer to that case and describe any new event. Do not present a fictional deadline from a blog as the platform's policy or send card security codes, passwords or one-time login codes.",
      ] },
      { title: "Treat reopening claims and replacement links carefully", paragraphs: [
        "A search result for ‘AllChinaBuy down’ can lead to old cached pages, affiliate articles, copied branding or messages with no date. Check who published the statement and whether its evidence can be traced to the official service. A page bearing the logo is not enough to establish that it controls your account. The same caution applies to a claimed migration: do not assume an old balance, warehouse inventory or refund request transfers to another service without explicit confirmation tied to your own record.",
        "If you compare another catalogue, match the original product identity and selected variant before treating two listings as equivalent. A title, thumbnail or shortened link can hide a different quantity, seller or option. This site's product links lead to the associated main catalogue; they do not transfer existing AllChinaBuy orders. Keep any new shopping decision separate from resolving a previous transaction, so an unrelated purchase does not obscure which service is responsible for each record.",
      ] },
      { title: "Work through a hypothetical access problem", paragraphs: [
        "Consider a buyer with two records: a paid jacket order and a parcel of shoes already assigned a carrier number. The public homepage now shows maintenance, and the buyer cannot open the account area. The jacket's last saved status is a purchase request, while the shoes have a carrier acceptance event. These facts do not support one combined conclusion about both purchases. The jacket needs a purchase-stage confirmation from the service. The shoes can be researched using the known carrier record. Putting both into a single ‘website down, everything missing’ description would conceal the most useful distinction.",
        "The buyer can prepare two short entries in the same file. The first contains the jacket order number, amount paid, selected variant and the date of the last screenshot, followed by a request to confirm whether the seller purchase was completed. The second contains the shoes' parcel reference, tracking number, carrier acceptance date and next unresolved handoff. If the carrier later records delivery, only the second entry changes. The maintenance note remains a separate dated observation. This example is fictional and illustrates record keeping; it does not predict how quickly support will answer or which operations remain available.",
      ] },
      { title: "Use a clear recheck and decision routine", paragraphs: [
        "Recheck the official notice before relying on instructions that require a working account. Record the new observation rather than replacing the old one. If access returns, first reconcile the existing orders, balances and messages against your saved file. Verify whether each relevant function works and whether its current terms are visible. An accessible login screen is only the beginning of that check. It does not automatically confirm purchasing, after-sales service or international dispatch.",
        "For each unresolved item, assign a next action and its evidence requirement: obtain a purchase confirmation, request a storage record, clarify a refund transaction or identify the carrier handoff. If a payment question remains unresolved, consult your own payment provider's published support process and applicable deadlines; this article does not determine eligibility or promise recovery. Keep the status record dated. A useful AllChinaBuy maintenance guide should make uncertainty easier to manage, while refusing to turn missing information into a confident claim.",
      ] },
    ],
    sources: [maintenanceSource],
    relatedSlugs: ["allchinabuy-tracking-not-updating", "allchinabuy-return-refund-stages", "product-link-safety"],
  },
  {
    ...base,
    slug: "allchinabuy-tracking-not-updating",
    title: "AllChinaBuy Tracking Not Updating: Status and Next Steps",
    eyebrow: "Parcel tracking",
    description: "Separate AllChinaBuy order, warehouse and carrier references, understand missing tracking events, and prepare a focused enquiry about the last confirmed handoff.",
    keyFacts: [
      "An order reference, a warehouse reference and a carrier tracking number identify different records.",
      "A generated shipping label does not by itself confirm that the carrier received a parcel.",
      "A missing scan alone cannot establish loss, seizure, delivery or a guaranteed arrival date.",
    ],
    figure: { src: "/images/guides/pre-shipment-check.svg", alt: "Editorial checklist for parcel records and shipping evidence", caption: "Keep the parcel record beside the tracking history. This is a checklist, not a display of live tracking data.", sourceUrl: "" },
    sections: [
      { title: "Start with the correct reference", paragraphs: [
        "When AllChinaBuy tracking is not updating, first check what number you are using. A product order number normally identifies the purchase record. A domestic shipment can have a separate number for the seller-to-warehouse journey. A warehouse item reference identifies stored goods, while an international parcel may combine several purchases. The carrier tracking number belongs to that parcel's transport record. These references are related, but they are not interchangeable. A tracking website rejecting an order reference does not prove that the order disappeared.",
        "Create a simple mapping: product order, domestic shipment if known, warehouse item, international parcel and carrier number. Copy each reference from its original record rather than retyping it from a cropped screenshot. Preserve leading zeros and check for visually similar letters and numbers. Record the carrier or route name as displayed. If you only have a parcel reference, ask support which carrier number is assigned and whether a physical handoff has been recorded.",
      ] },
      { title: "Read a tracking event as a dated observation", paragraphs: [
        "Each event should be read together with its date, location and source. ‘Information received’ or similar wording may indicate electronic shipment data rather than physical acceptance. An acceptance scan is stronger evidence of possession by the named carrier. An export event, an arrival event and a delivery attempt describe different stages. Carriers use different language, so this guide offers a reading method rather than an official translation of every status code.",
        "Keep the original wording when asking for help. A paraphrase such as ‘stuck in China’ can hide whether the last event was label creation, warehouse packing, carrier acceptance or export processing. Check the timezone before deciding that two events are out of order. Some systems display a local scan time and others display the viewing location's time. A duplicated event or delayed data feed can also change the appearance of the timeline without proving that the physical parcel moved twice.",
      ], checklist: ["Exact event wording and event date", "Carrier or service that supplied the event", "Location and timezone when provided", "Whether the event confirms physical receipt or only electronic data"] },
      { title: "Separate the domestic and international journeys", paragraphs: [
        "A seller's domestic tracking can finish when a parcel reaches the receiving warehouse. That does not mean the international shipment has begun. Goods may still need identification, inspection, packing decisions and a separate parcel submission. If your domestic number shows delivered, compare it with the warehouse receipt record and item reference. Ask about an unresolved receipt using those matching references instead of checking the domestic number for an overseas event that it cannot provide.",
        "The international journey begins under its own records and may involve multiple logistics partners. A line description is not always the name of the final delivery company. If a replacement or last-mile number appears, save both numbers and the source that connects them. Do not guess a replacement number or select a carrier merely because it produces a result. A result for an unrelated shipment is worse than an explicit ‘not found’ because it creates false confidence.",
      ] },
      { title: "Investigate a quiet timeline without inventing a deadline", paragraphs: [
        "There is no responsible universal rule that every AllChinaBuy parcel must scan within a fixed number of days. The next event depends on the actual transport arrangement, departure schedule, carrier reporting and destination process. An old community screenshot cannot set the terms for your route. Use the estimated timeframe and enquiry instructions attached to your own shipment, while recognising that an estimate is not a delivery guarantee.",
        "Compare the last confirmed event with the stage that should follow. Before carrier acceptance, the useful question is whether the parcel was handed over. After acceptance, ask the named operator about its next expected event and enquiry process. After a delivery attempt, check the carrier's official instructions promptly. If the timeline contains an explicit problem such as an address request, respond through the verified channel instead of waiting for a generic ‘normal delay’ period to expire.",
      ] },
      { title: "Handle exceptions using the responsible record", paragraphs: [
        "An exception message is a prompt to identify an action, not a final diagnosis. An address issue may need corrected delivery information; a customs request may need genuine purchase documentation; a failed delivery may have collection or redelivery instructions. Check the actual message and the operator's official contact route. This article cannot determine customs charges, release a parcel or interpret a legal deadline for a specific destination. Those decisions belong to the responsible authority or carrier.",
        "Provide documents that match the shipment. An invoice for a different item, an unrelated payment screenshot or an altered declared value can create further confusion. Keep a copy of what you sent and when you sent it. If a status says returned, establish returned to whom and under which number. A return event is not the same as a completed refund, and a delivered event is not evidence that every item inside the parcel was correct or undamaged.",
      ] },
      { title: "Prepare a short, useful tracking enquiry", paragraphs: [
        "A good enquiry contains the order-to-parcel mapping, the exact tracking number, the selected route, the last event and the date of your latest check. Ask one question that identifies the missing handoff. For example, request confirmation of the carrier acceptance record rather than asking for a prediction of the final delivery day. If support assigns a case number, keep it with the parcel record and include it in later correspondence.",
        "Avoid posting an unredacted address label or full tracking page in a public discussion. Those pages can contain recipient names, addresses and phone numbers. Private support may need some of that information, but a public screenshot rarely does. Preserve the original for your records and share a redacted copy when asking a community to explain general status wording. Advice from another buyer can suggest a question; it cannot replace the carrier's shipment-specific evidence.",
      ] },
      { title: "Compare two hypothetical quiet timelines", paragraphs: [
        "Imagine parcel A shows only ‘shipment information received,’ while parcel B shows a physical carrier acceptance followed by an export event. Both timelines have been quiet for several days, but the evidence questions differ. For parcel A, ask whether the carrier has actually taken possession and request the handoff record if one exists. For parcel B, ask the operator about the next transport stage and the enquiry process associated with the selected service. Neither record, on its own, justifies declaring the parcel lost or calculating a guaranteed arrival date. The same number of quiet days does not make the underlying situations equivalent.",
        "Suppose a new event later appears for parcel B with an earlier timestamp. Preserve both the event time and the date on which you first saw it. That lets you distinguish delayed reporting from the date of physical movement. If parcel A receives a different last-mile number, save the official connection between the two numbers before using the new one. Add these updates to the existing record rather than erasing the previous uncertainty. This fictional comparison is a diagnostic exercise, not a description of current AllChinaBuy parcel performance. Its purpose is to improve the question you send to the responsible party.",
      ] },
      { title: "Account for the current maintenance notice", paragraphs: [
        "The AllChinaBuy public homepage showed a maintenance notice when checked on October 5, 2026. That notice is relevant if you cannot retrieve your account's parcel details, but it does not independently explain a carrier's tracking pause. Use numbers and receipts you already possess, and request the missing record through the support route identified by the official service. Do not infer that every parcel is lost or that every parcel is still moving because of a general website announcement.",
        "When the account becomes accessible, reconcile the displayed parcel contents, route, payment and tracking numbers with your saved file. Add a resolution only when evidence supports it: a carrier acceptance, a delivery record, a confirmed return, or a refund transaction. If the case remains open, retain a dated next action rather than repeatedly refreshing unrelated trackers. This approach makes AllChinaBuy tracking more useful because it turns a vague lack of updates into a specific question about custody, information or delivery.",
      ] },
    ],
    sources: [maintenanceSource],
    relatedSlugs: ["allchinabuy-website-status-maintenance", "allchinabuy-return-refund-stages", "allchinabuy-domestic-shipping-seller-to-warehouse"],
  },
  {
    ...base,
    slug: "allchinabuy-return-refund-stages",
    title: "AllChinaBuy Returns and Refunds: Order and Parcel Stages",
    eyebrow: "After-sales records",
    description: "Organise an AllChinaBuy cancellation, warehouse return or parcel enquiry with matching records, and distinguish a requested refund from a completed credit.",
    keyFacts: [
      "Cancellation, seller return, parcel investigation and completed refund are different events.",
      "Eligibility, deductions, deadlines and payment destinations must be confirmed for the actual transaction.",
      "The October 5 maintenance notice provides no order-specific refund promise or completion date.",
    ],
    figure: { src: "/images/guides/checkout-ledger.svg", alt: "Editorial ledger separating product, service and shipping amounts", caption: "Keep each charge and each credit on its own row; an example ledger is not a statement of current refund policy.", sourceUrl: "" },
    sections: [
      { title: "Identify which process you need", paragraphs: [
        "Searching for an AllChinaBuy refund can describe several different problems. You may want to cancel an unpurchased item, return goods held in a warehouse, correct an amount, investigate a parcel, or understand a credit already shown in your account. These processes need different evidence and may involve different parties. Begin with the last confirmed stage, the specific issue and the remedy you want. A single word such as ‘refund’ is not enough to show what happened.",
        "This guide does not publish a universal AllChinaBuy refund policy or promise that a request will be accepted. The public homepage showed a maintenance notice on October 5, 2026, and the current account-only rules could not be independently verified. The practical method below is designed to organise your records and questions. Keep the seller's terms, the platform transaction and your payment provider's process separate instead of assuming that one automatically determines the others.",
      ] },
      { title: "Before seller purchase: confirm whether cancellation is possible", paragraphs: [
        "A payment receipt confirms a payment event, not necessarily that an agent has completed the seller purchase. If you want to cancel, ask whether the purchase has been placed and whether the order can still be stopped. Save the order reference, selected option, quantity, amount and date. If an order screen is available, preserve its exact status and the cancellation options displayed. Do not treat a disabled button as proof that no support process exists, or a visible button as proof that the cancellation has succeeded.",
        "After sending the request, look for a confirmation that identifies the order and action. A message acknowledging receipt is different from an approved cancellation. Likewise, approval is different from a completed financial credit. Record each stage separately. If a second order was placed accidentally, disclose both references and explain which one you intended to keep. Do not create another payment or replacement order solely because the first request is slow to receive a response.",
      ] },
      { title: "At the warehouse: document the reason and preserve the item", paragraphs: [
        "For an item already received, compare the selected option with the available QC evidence. A wrong colour, missing component, visible defect and an unexpected fit are different reasons for a request. Describe the observable issue precisely and attach the relevant image or measurement. A statement that a seam appears open is easier to investigate than an unsupported claim that everything is poor quality. If the photograph is ambiguous, request clarification before describing the ambiguity as a confirmed defect.",
        "Ask whether a seller return is available, which deadline applies, whether packaging or tags must be preserved, and which charges would be deducted or remain non-refundable. This article cannot set those terms. Avoid authorising repacking, disposal of packaging or international shipment while a return decision is unresolved, unless the responsible support team explains the consequences and you accept them. Save the response so your next action can be traced to the actual instruction for that item.",
      ], checklist: ["Order and warehouse item references", "Selected variant and relevant QC evidence", "Specific reason for the request", "Confirmed return deadline, condition requirements and possible deductions"] },
      { title: "After parcel submission: establish custody first", paragraphs: [
        "Once goods have been allocated to a parcel, a request may require a packing change, a shipment stop or a carrier investigation. First establish whether the parcel is only created, packed, handed to a carrier or already in transit. A parcel reference alone does not answer that question. Ask what action is still possible at the confirmed stage and whether it has a cost. Do not assume a domestic seller-return procedure can be applied unchanged to an international parcel.",
        "If goods arrive damaged or incomplete, retain the packaging, shipping label and item evidence while you ask about the relevant process. Photograph the received condition honestly and distinguish exterior damage, missing contents and an incorrect product. Keep any unboxing record you already have; do not reconstruct an event and present it as original evidence. A carrier delivery confirmation may establish delivery of a package but does not, by itself, resolve a dispute about its contents.",
      ] },
      { title: "Reconcile the money in separate rows", paragraphs: [
        "Build a ledger with the original product amount, domestic delivery, service charges, international freight and every subsequent credit or adjustment. Use the recorded currency and date for each row. An account balance, an authorised refund and a settled credit at your bank are different financial records. Ask where an approved amount will be credited, whether any further withdrawal step is required and which transaction reference identifies completion. Never assume that a credit automatically returns to the original payment instrument.",
        "A hypothetical example illustrates the bookkeeping rather than platform policy. If your record contains a product payment of 40 units and a separate delivery payment of 5 units, a credit of 40 does not establish what happened to the other 5. Mark the delivery row unresolved until the response explains it. If conversion or processing differences appear, preserve the original and credited currencies and request a breakdown. Do not label every difference an improper fee without checking the corresponding transaction terms.",
      ], takeaway: "Requested, approved and credited should be separate entries in your refund timeline." },
      { title: "Use one case file and a specific requested remedy", paragraphs: [
        "Put the essential evidence into a chronological file: order confirmation, payment, warehouse receipt, QC issue, return request, reply and financial outcome. Include only the stages that apply. Begin the message with the desired action, such as confirming cancellation, arranging an eligible return or explaining a missing credit. State the relevant references and describe what is still unknown. This makes it easier for a reviewer to match your question to the correct system record.",
        "Save every case number and follow up within the same thread when possible. If you receive an answer that resolves only part of the issue, identify the remaining row rather than starting the explanation again. Keep copies of original documents and redact unrelated personal information in shared copies. Never send a card PIN, card security code, password or one-time login code as proof of a refund request. Use the official support route and verify unexpected requests independently.",
      ] },
      { title: "Check a hypothetical partial resolution", paragraphs: [
        "Consider an order containing a jacket and a cap. The jacket has a documented option mismatch, while the cap matches the selected listing. A request to return the jacket should identify its own order or item reference and specify whether the cap is to remain unchanged. If the two items are allocated to a planned parcel, ask whether the parcel needs to be revised before any dispatch. A message saying only ‘cancel my order’ may be too broad. Clear item-level instructions reduce the chance that the support response addresses the wrong part of the purchase.",
        "Now imagine the response approves the jacket return but says nothing about domestic delivery charges. Record the approval, preserve any instructions for the return, and leave the unanswered charge row open. Do not mark the entire case complete simply because one message uses the word ‘refunded.’ Confirm the credited amount, currency, destination and transaction reference against the financial record. If the cap is later shipped, its parcel number belongs in a separate row. This scenario is an editorial example, not a claim about a customer's experience or a refund policy. It shows why the physical goods and the financial outcome need separate reconciliation.",
      ] },
      { title: "Handle maintenance and unresolved cases without guessing", paragraphs: [
        "A general maintenance announcement does not approve your refund, reject it or reset an applicable deadline. Record the access problem and the dates of attempts to obtain assistance. Consult the current published process of the service or payment provider responsible for the question. Available remedies and deadlines can depend on the transaction and jurisdiction, so this article does not prescribe a universal dispute period or guarantee a payment-provider outcome.",
        "Close the file only when the practical and financial result is clear. A completed return should have an identified receiving or acceptance record where one is provided; a completed refund should have a traceable credit in the stated destination. If the result is partial, record what was settled and what remains open. Keeping product research, any new purchase and the unresolved AllChinaBuy transaction separate will make later reconciliation easier. The goal is an accurate record that supports a decision, not a promise based on another buyer's experience.",
      ] },
    ],
    sources: [maintenanceSource],
    relatedSlugs: ["allchinabuy-website-status-maintenance", "allchinabuy-tracking-not-updating", "qc-photo-checklist"],
  },
  {
    ...base,
    slug: "allchinabuy-shoe-sizing-insole-qc",
    title: "AllChinaBuy Shoe Sizing: Insole Measurements and QC Photos",
    eyebrow: "Shoe sizing",
    description: "Compare seller size charts with a well-fitting pair, write precise insole measurement requests, and check shoe QC photos without confusing labels with fit.",
    keyFacts: [
      "A size label needs context: chart system, measurement method and the exact model or option.",
      "Foot length, removable insole length and exterior outsole length are different measurements.",
      "QC photos can reveal visible mismatches but cannot guarantee comfort, authenticity or long-term durability.",
    ],
    figure: { src: "/images/guides/qc-photo-checklist.svg", alt: "Editorial QC sequence for identity, size, measurements and condition", caption: "Read sizing evidence in a fixed order. The diagram is illustrative and is not a warehouse photograph of a tested shoe.", sourceUrl: "" },
    sections: [
      { title: "Begin with the exact shoe and the exact size system", paragraphs: [
        "An AllChinaBuy shoe sizing decision begins with the original listing and selected option, not a universal conversion chart. Two sellers can use the same number while describing different size systems or measurement methods. Record the model, seller, colour, selected size and the chart shown for that listing. If a chart appears to cover several models, ask whether it applies to the exact item. A familiar brand name or similar photograph does not establish that the fit matches a pair you already own.",
        "Treat UK, US and EU labels as labels until the source explains the corresponding measurements. Do not silently apply a men's chart to a women's model, or an adult chart to a children's product. If the listing contains conflicting tables, save both and seek clarification. The purpose of this guide is to compare evidence consistently. It cannot supply a guaranteed AllChinaBuy size chart because the underlying products, sellers and individual fit preferences are not identical.",
      ] },
      { title: "Use a well-fitting reference pair", paragraphs: [
        "Choose a pair you actually wear comfortably for a similar activity and sock thickness. Record its stated size and model, but also write down what makes it fit: toe space, heel hold, width and any pressure point. A shoe that is long enough can still be too narrow or too shallow. A loose heel can be a problem even when a length measurement looks reasonable. A reference pair gives the numbers a practical context that a generic conversion table lacks.",
        "If the reference pair has a removable insole that can be taken out without damage, measure it using a documented method. Lay it naturally on a flat surface and show the start and end of the ruler. Do not stretch a flexible insole or force a curved part flat without noting what you did. Keep a photograph of the method so a requested warehouse measurement can use comparable endpoints. If the insole is fixed, do not tear it out merely to obtain a number.",
      ] },
      { title: "Keep foot, insole and outsole measurements separate", paragraphs: [
        "Foot length describes the foot under a specified measurement method. Insole length describes the removable component, while outsole length describes an external part of the shoe. These values can differ for perfectly ordinary construction reasons. A thick heel, extended toe bumper, curved insole or raised heel cup changes what is being measured. Comparing a warehouse outsole measurement with your reference insole can therefore create an apparent sizing error that is really a method mismatch.",
        "Use centimetres or millimetres consistently and retain the unit with every value. If someone supplies a number without naming the measured component, request clarification before converting it into a size. A ruler that starts away from zero also needs to be read as a difference between two marks. Ask for the full measurement to be visible, including the starting point, endpoint and scale. The camera should make those marks readable without relying on a caption typed by someone else.",
      ], checklist: ["Name the measured component.", "Use the same endpoints on the reference and ordered pair.", "Keep the unit beside the number.", "Show the complete ruler scale and both endpoints."] },
      { title: "Write a measurement request that answers one decision", paragraphs: [
        "A request such as ‘check the size’ leaves too much room for interpretation. A more useful request identifies the item and asks for a single observable result: if the insole is removable without damage, photograph its heel-to-toe length in centimetres with the ruler and both endpoints visible. If removal is not possible, ask the service to explain what alternative measurement it can provide. Do not request destructive handling without understanding and accepting its consequences.",
        "The historical AllChinaBuy public order description reviewed for this site's July guide recommended one precise requirement per detailed-photo request. That historical description is not confirmation of current availability or fees. The October maintenance notice makes it especially important to verify that a request can currently be accepted. When a new photograph arrives, compare it against your wording. If it shows the wrong component or hides the ruler's beginning, explain the mismatch instead of treating an unusable measurement as reliable evidence.",
      ] },
      { title: "Review the pair before inspecting tiny details", paragraphs: [
        "Start the AllChinaBuy shoe QC review with product identity, colour, quantity and the labels on both shoes. Confirm that the photographed pair corresponds to the selected option. Ask whether an image belongs to your received goods when its connection to the order is unclear. Seller listing photographs and editorial illustrations are useful references, but they should not be presented as your warehouse evidence. Keep those image types labelled in the record.",
        "Then compare left and right shape, visible seams, closure parts, outsole edges and obvious damage. View a suspected asymmetry from a centred angle before calling it a defect. Perspective, uneven placement and lighting can affect what a photograph suggests. Describe the observable feature and request a clarifying angle when necessary. A photo review cannot authenticate a branded item, prove material composition or predict months of wear. Avoid making those claims from logos, packaging or a single favourable image.",
      ] },
      { title: "Turn the comparison into an explicit decision", paragraphs: [
        "Use a small worksheet containing the selected label, seller chart method, reference measurement, warehouse measurement and unresolved fit concern. For a hypothetical example, a reference insole measured at 27.0 centimetres and an ordered insole measured at 27.6 centimetres differ by 0.6 centimetres. That arithmetic does not prove the second shoe is wrong or right. First confirm the same endpoints and shape, then consider width, construction and the wearer's actual preference. This example is not a size recommendation.",
        "Choose one recorded outcome: enough evidence to proceed, another measurement needed, or a return enquiry required. If a return may be necessary, check the actual seller and order terms before authorising international shipping. Do not assume removing packaging or consolidating a parcel leaves every remedy unchanged. Link the sizing record to the order reference so a later response can identify the correct item. Keeping the decision written also helps you avoid repeating the same uncertain purchase in another colour.",
      ] },
      { title: "Resolve an unclear measurement before interpreting the size", paragraphs: [
        "Imagine a warehouse photograph shows a shoe beside a tape, with the beginning of the tape hidden under the heel. The visible endpoint reads 28 centimetres. That image does not necessarily establish a 28-centimetre length because the starting mark is unknown. It also appears to measure the exterior outsole, while your reference note contains an insole length. There are two separate evidence problems: an unreadable starting point and a different measured component. Converting the endpoint into a size would leave both problems unresolved, even if the resulting number happens to match a familiar chart.",
        "A better follow-up identifies both issues in plain language and asks whether a comparable measurement can be provided without damaging the shoe. Keep the first photograph, your clarification and the replacement photograph together. If a removable insole cannot be shown, record that limitation and decide whether the remaining evidence is sufficient. You might ask for the seller's model-specific chart or a clearer option label, but neither should be presented as the missing physical measurement. This hypothetical case illustrates how a precise request can prevent a false conclusion. It does not mean every insole is removable or every measurement service is currently available.",
      ] },
      { title: "Keep the useful measurements for future purchases", paragraphs: [
        "After receiving and trying the shoes, add your own fit observations to the record. Note the sock type and whether the pair was tried indoors, then describe any difference between the photograph-based expectation and actual wear. Record only your real experience. Do not invent customer testimonials or generalise one person's fit to every size and foot shape. If you share the comparison, distinguish measured values, personal impressions and unresolved construction details.",
        "Use that history to improve the next request. A previous length measurement may have been sufficient, or it may show that you also needed usable width or a clearer view of the heel shape. Compare like with like and preserve the exact model reference. During any period when AllChinaBuy account functions cannot be verified, you can still organise saved charts and existing photographs, but new service availability must be checked separately. Better sizing decisions come from consistent measurements and honest limits, rather than confidence in a generic conversion number.",
      ] },
    ],
    sources: [maintenanceSource, { title: "AllChinaBuy public order-confirmation description — historical reference", url: "https://m.allchinabuy.com/en/confirmorder/?isformcart=1", scope: "Detailed-photo wording recorded in this site's July 17, 2026 review. Not reverified as a currently available service during the October maintenance period." }],
    relatedSlugs: ["qc-photo-checklist", "allchinabuy-detailed-photos", "allchinabuy-return-refund-stages"],
  },
];
